### ISSUE TITLE
bug zul jin boss zul aman

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1000]
Le boss a été mis à 71% il a bug (il nous affiche qu'il est hors champs de vision pour le tapper alors qu'il est en face de nous et impossible à le tapper (donc le boss se skip actuellement CE QUI N'EST PAS NORMAL) il faut le tuer car il est sur le chemin du last il doit pas se mettre en forme HORS champs de vision et etre en face des joueurs

**Comment by joshwhedon** [comment]
Corrige prochaine maj
