### ISSUE TITLE
Quête "Là bas, tout en bas"

### ISSUE THREAD

**Issue by Aloawan** [way-of-elendil/3.3.5#1001]
Lors de la quête le familier ne ramasse pas les cristaux chancreux

**Comment by joshwhedon** [comment]
J'ai teste et elle a l'air de fonctionner. Il faut charmer un geist, l'approcher d'un cristal et utiliser l'aptitude dans sa barre de sort. Il s'approchera du cristal et ensuite ira a l'entree de la ziggourat. Il est possible que si vous avez un pet de sorti il y ait un conflit. Des addons posent aussi parfois des problemes avec les barres de sort de pet.
