### ISSUE TITLE
Quête La casse aux ectoplasmes

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1002]
https://woehead.way-of-elendil.fr/?quest=8924
Dans cette quête, lorsque l'on utilise https://woehead.way-of-elendil.fr/?item=21946, on peut voir les différents ectoplasmes à looter sur les mobs de la quête cependant le loot ne peut être ramassé que dans de très rares cas. (On clique sur le loot dans la table de butin et la fenêtre se ferme sans rien looter)
https://woehead.way-of-elendil.fr/?item=21935
https://woehead.way-of-elendil.fr/?item=21936
https://woehead.way-of-elendil.fr/?item=21937
Sans utiliser l'alambic on ne voit pas le loot (Donc normal)
Dans de rares fois, le loot peut être ramassé mais je n'ai pas pu déterminer pourquoi dans ces cas il l'était.
J'ai testé de poser l'alambic en étant en combat, avant le combat, de bien vérifier que le buff de l'alambic est présent au moment de la mort du mob mais rien ne change. Tu aura peut être une idée, ou quelque chose à tester pour trouver le soucis.

**Comment by joshwhedon** [comment]
Fixe prochaine maj
