### ISSUE TITLE
position 26.44 / 19.90 (spot pêche bug)

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1003]
le spot pêche à la position Côte sauvage (région strangleronce) en 26.44 / 19.90 est bug il est affiché dans une zone ''eau peu profonde'' donc impossible à pêcher alr qu'un banc de poisson s'y trouve (on y pêche des bouches noires huileux)

**Comment by Babyface-187** [comment]
X: -12014.936523 Y: 533.450256 Z: 1.310410

**Comment by joshwhedon** [comment]
Corrige prochaine maj
