### ISSUE TITLE
Capacité résistence (minage)

### ISSUE THREAD

**Issue by LLPPAA** [way-of-elendil/3.3.5#1004]
D'après le client, le talent résistance rang 6 ( https://woehead.way-of-elendil.fr/?spell=53040 ) nécessite le niveau 55 pour être utilisé/actif, or il fournit bien ses 60 points d'endurance quelque soit le niveau (en l’occurrence, niveau 48).

C'est le client qui se trompe en affichant une restriction qui n'est pas réelle, ou il y'a un bug et la restriction n'est pas appliqué ?
![image](https://user-images.githubusercontent.com/14274351/91469944-5d84a780-e894-11ea-925b-3f3637aca841.png)

**Comment by joshwhedon** [comment]
A premiere vue c'est bien suppose y avoir un niveau minimum depuis 3.1. Je corrige prochaine maj, mais ca risque aussi d'affecter d'autres sorts similaires.
