### ISSUE TITLE
Puit de lumière du prêtre sacré

### ISSUE THREAD

**Issue by JalloWoe** [way-of-elendil/3.3.5#1005]
Bonjour, après quelques tests sur le puit de lumière, nous avons constaté que le HOT de celui-ci s'interrompait au moindre dégât reçu alors qu'il est indiqué sur le sort qu'il faudrait que la cible du HOT prenne 30% de son total de points de vie en dégâts avant qu'il soit interrompu.

- Classe : prêtre 
- Race : Elfe de sang
- Spécialisation : sacré
- Sort : Puit de lumière

**Comment by JalloWoe** [comment]
Y a personne ici pour répondre?

**Comment by joshwhedon** [comment]
Pas encore eu l'occasion de regarder

**Comment by joshwhedon** [comment]
Corrige prochaine maj.
