### ISSUE TITLE
Bug Combustion ardente target halion

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#1006]
**Description**
Halion c'est target lui même avec le spell combustion ardente ( https://woehead.way-of-elendil.fr/?spell=74562 ) alors qu'il est sensé ciblé uniquement les cibles ennemi donc le raid. A la fin du timer la combustion a donc fait une énorme flaque au sol

**Étapes de reproduction**
- sanctum rubis
- 25
- halion
- combustion ardente en P1

**Comportement attendu**
Halion est sensé target uniquement le raid et pas lui même

**Captures d’écran / Vidéos**
je sais pas héberger des images mais j'ai 2 screen disponible en mp discord si besoin

**Comment by Ischjgt** [comment]
```
Ischjgtisch gagne Renvoi de sort |2 Ischjgtisch.
Combustion ardente Halion est renvoyé par Ischjgtisch.
```

Tag can't be reflected 
https://fr.wowhead.com/spell=74562/combustion-ardente

**Comment by Fairivier** [comment]
donc le spell aurait été renvoyé par un war ?

**Comment by joshwhedon** [comment]
Corrige prochaine maj
