### ISSUE TITLE
NPC: Petit dragon mécanique

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1008]
**Description**
10576 - [Petit dragon mécanique en mithril] 
4396 - [Petit dragon mécanique] 
Qui invoquent respectivement :
8615 - [Mithril Dragonling] 
2678 - [Mechanical Dragonling] 

Les créatures invoquées sont hostiles aux personnages d'une faction différentes dans les sanctuaires. (testé à Dalaran)

**Comment by joshwhedon** [comment]
Corrige prochaine maj
