### ISSUE TITLE
NPC: Thane Korth'azz et Baron Vaillefendre - Naxxramas

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1009]
**Description**
16064 - [Thane Korth'azz] 
30549 - [Baron Vaillefendre] 
10 et 25

Les 2 NPCs qui peuvent attaquer à l'auto attaque et qui se placent devant suivent leur cible au lieu de rester au point où il doit se trouver

https://wowwiki.fandom.com/wiki/Four_Horsemen

**Comment by joshwhedon** [comment]
Je crois pas qu'ils soient suppose rester au point ou ils doivent se trouver, ils y vont et ensuite suivent en melee. Sinon c'est trop facile suffit d'avoir un tank qui reste a distance.
"The Korth'azz and Rivendare tanks should drag their Horseman to near the door where you enter and taunt off each other"
clairement ils ont l'air de pouvoir suivre leur cible. Ou alors j'ai pas compris le bug.
