### ISSUE TITLE
DK sang talent puissance de Mograine

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#1010]
**Description**
Je pense que la frappe au cœur( https://woehead.way-of-elendil.fr/?spell=55262 ) ne prend pas en compte le talent puissance de mograine ( https://woehead.way-of-elendil.fr/?spell=49534 ) ou du moins pas entièrement car la différence entre les dégats crit avec et sans talent est de l'ordre de 20-25% au lieu de 45%

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- dk
- orc
- sang
- frappe au coeur et puissance de mograine

**Comportement attendu**
les dégats critiques sonnt sensé etre augmenté de 45% avec 3 pts dans la puissance de mograine et non 25%

**Captures d’écran / Vidéos**
https://image.noelshack.com/fichiers/2020/36/6/1599323899-test-sans.png test sans le talent puissance de mograine avec des dégats moyen de 3699
https://image.noelshack.com/fichiers/2020/36/6/1599323906-test-avec.png test avec 3/3 dans puissance de mograine avec des dégats moyen des crit de 4619
Or 3699*1.45 = 5363 il y a donc une différence notable avec les 4619 obeservé avec 3/3 dans le talent

**Comment by Fairivier** [comment]
si besoin j'ai fait d'autre test qui  donnent tous le meme ratio d'une augmentation de 20-25%

**Comment by joshwhedon** [comment]
C'est uniquement le bonus de degats qui est augmente hein, pas les degats eux memes. Donc un coup critique ne fera pas 45% de degats en plus avec le talent. Il fera uniquement 45% de degats critiques en plus (donc (degats critiques - degats normaux) * 45 / 100 en plus).
