### ISSUE TITLE
Arène des Tranchantes: Charges impossibles

### ISSUE THREAD

**Issue by Kaderharicot** [way-of-elendil/3.3.5#1011]
**Description**
L'arène des tranchantes présente de nombreuses anomalies au niveau des charges, en guerrier en tout cas (pas de l'ombre du voleur et charge des druides féraux non testés), qui fait que l'on ne peut pas charger sur une majorité de la map

**Étapes de reproduction**
Il faut jouer guerrier sur l'arène des tranchantes (non testé sur l'arène non phasé qui se situe en outreterre, mais sur l'arène phasé lorsque l'on tag escarmouche / arène côté, il y a de multiple endroits depuis lesquels il est impossible de lancer une charge / interception

**Comportement attendu**
Quand un ennemie se situe en face de nous, sans obstacle et avec la même hauteur ( sur la même plateforme) il devrait être possible de le charger

**Captures d’écran / Vidéos**
Pas de vidéo mais possible de faire une démonstration en jeu, ou éventuellement s'il y a vraiment besoin, de cliper sur twitch.

**Ressources additionnelles**
Je n'ai pas forcément de sources pour prouver que l'on devrait pouvoir charge dès lors que la personne est sur la même plateforme que nous sans obstacle, mais j'espère que ce n'est pas nécessaire d'en fournir

**Comment by joshwhedon** [comment]
On y peut rien, les maps sont comme ca malheureusement. D'ici quelques semaines de nouvelles maps seront deployees, peut etre que ca changera quelque chose, peut etre pas.
