### ISSUE TITLE
event échec (avant dernier boss karazhan)

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1012]
**Description**

L'event est complètement broken; il y a une impossibilité de prendre plusieurs pièce; au bout d'un moment on arrive plus à y rentrer dedant (dans les pièces); le boss se regen malgré les ads heal dead; fin il faudrait le script

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues?q=%C3%A9chec

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/918

**Comment by Ischjgt** [comment]
https://wowwiki.fandom.com/wiki/Chess_event
1. "Whenever a game is going on, there is a silence debuff in the chess room to prevent clearing the trash mobs leading to Prince Malchezaar. "
2. À la fin de l'event, on remarque qu'on ne peut pas loot le coffre, il y a marqué qu'il est hors de portée
=> Je crois qu'en se mettant sur une pièce et en y ressortant, la position du joueur est toujours estimé dans le véhicule
Un exemple :
- Lancer l'event et prendre possession d'un pion (il faudra peut-être s'y prendre à 2 fois pour entrer), 
- Ressortir
- Il est impossible d'interagir avec toutes les pièces qui ne sont pas adjacentes à celle que je viens de prendre

**Comment by joshwhedon** [comment]
On y peut rien c'est un event de merde, il faut faire avec.
