### ISSUE TITLE
Quest: La bataille pour fossoyeuse

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1013]
**Description**
Il est possible de faire la version alliance et la version horde de la suite de quête.
Que dans un sens, en commençant alliance, changefaction puis en faisant la suite côté horde.
Pas possible en commençant côté horde.

Alliance :
13347 - 13369 - 13370 - 13371 - 13377

Horde :
13242 - 13257 - 13266 - 13267

**Comment by joshwhedon** [comment]
Corrige prochaine maj
