### ISSUE TITLE
Évicération cassé

### ISSUE THREAD

**Issue by Hydro-woe** [way-of-elendil/3.3.5#1015]
Description
Le talent "Agressivité" de la branche Combat du rogue n'applique pas le bon modificateur au dégâts

Étapes de reproduction
suivre ce lien : https://woehead.way-of-elendil.fr/?spell=48668
posé la formule sur excel et voir que pour un rogue avec 4564 de PA la plage de dégâts, avec et sans le talent, est 2662 à 3828 sans et 3061 à 4403 avec.
constaté que dans le jeux la plage de dégâts est de 2681 à 3886 avec le talent (ce qui daube un peu comme boost pour 5 pts de talents)

Ressources additionnelles
le talent "Évicération améliorée" de la branche Assassinat applique quand a lui le bon modificateur

PS: je veux bien qu'on me rembourse les 10 po de respé claqué pour le test ;)

**Comment by Ischjgt** [comment]
Sans talent, 1 point de combo
Sans talent, 5 points
Avec talent, 1 point
Avec Talent, 5 points
<img width="266" alt="Capture d’écran 2020-09-11 à 13 32 09" src="https://user-images.githubusercontent.com/60295792/92921729-ea069c80-f434-11ea-9dc6-7205de771ae4.png">
<img width="249" alt="Capture d’écran 2020-09-11 à 13 36 14" src="https://user-images.githubusercontent.com/60295792/92921733-ea9f3300-f434-11ea-8408-e2292e88ec32.png">
<img width="257" alt="Capture d’écran 2020-09-11 à 13 39 56" src="https://user-images.githubusercontent.com/60295792/92921736-eb37c980-f434-11ea-9d04-bc237b0d635a.png">
<img width="275" alt="Capture d’écran 2020-09-11 à 13 41 52" src="https://user-images.githubusercontent.com/60295792/92921738-ebd06000-f434-11ea-96d2-01d840dd4558.png">
