### ISSUE TITLE
Timer Event Zul Aman  Urgent

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1016]
**Description**
L'event du timer ne se lance pas dans Zul Aman, ce qui empêche les coffres d'apparaître.

**Étapes de reproduction**
-  Zul Aman
- Raid TBC 10 joueurs
- Entrée du raid lors du lancement de l'event du gong
- 3 à 10 joueurs

**Comportement attendu**
Enter the instance and talk to Harrison Jones to start the event and open the doors. You will now have 20 minutes to defeat the first animal-boss of your choice. Any of the loa spirit bosses will do and there is no required order, but two of them will add extra time to the timer.

Killing Nalorakk (bear) will add 15 minutes to your timer.
Killing Akil'zon (eagle) will add 10 minutes to your timer.
Other bosses will not grant additional time.
Therefore you have exactly 45 minutes to kill the first four bosses, which is a challenging task! Guilds that are doing Serpentshrine Cavern and The Eye will likely get three bosses down within 45 minutes, whereas guilds doing Battle for Mount Hyjal and Black Temple content are the only ones likely to get all four. Karazhan / Tier 4 equipped raids should be able to get at least the first two chests, until they gear up with Zul'Aman and heroic badge equipment. Note that you must kill the boss before the timer expires. Unlike the Baron timed quest, engaging a boss before the timer expires is not sufficient.

The loot from the event is dependent on the number of hostages you rescue. All loot is from the Zul'Aman timed event loot table (see below).

First hostage will give a random piece of armor (iLvl 128).
Second hostage will give a random weapon (iLvl 132).
Third hostage will give a random ring (iLvl 141).
Fourth hostage will give a random ring (iLvl 141).

Source : https://wow.gamepedia.com/Zul%27Aman_timed_event

**Comment by joshwhedon** [comment]
Ce event n'existe plus depuis wotlk.
