### ISSUE TITLE
[Bug Mineur] Démoniste : Bug d'affichage après utilisation de l'oeil de Kilrogg

### ISSUE THREAD

**Issue by lMeteorzl** [way-of-elendil/3.3.5#1017]
Après avoir utilisé la compétence l'oeil de Kilrogg, la barre affichant les compétences du familier n'apparait plus.

**Etapes de reproduction :** 

1.  Avoir un familier invoqué (ex: le marcheur du vide)
2. Utiliser la compétence "Oeil de Kilrogg"
3. Mettre fin à la compétence (ou attendre la fin)

**Observations (correspondantes aux étapes de reproduction) :** 

1. La barre de compétences du familier sont affichées (Attaque, Aggressif, Défensif, Passif, ect....)
2. La barre de compétences du familier disparaît pour faire place à la barre correspondante à l'oeil de Kilrogg (Invocation, Annuler)
3. La barre correspondante à l'oeil de Kilrogg disparaît mais la barre de compétences du familier ne réapparait pas (alors que le familier est bien à nos côtés)

**Remarque :** On peut facilement contourner ce bug en utilisant une monture. Monter puis descendre de la monture permet de réafficher la barre de compétences du familier

**Comment by lMeteorzl** [comment]
**Avant d'utiliser l'oeil de Kilrogg :** 

![Avant l'utilisation Oeil de Kilrogg](https://user-images.githubusercontent.com/71191511/93003464-1f97ac80-f53f-11ea-9130-15756e04216e.jpg)

**Après avoir utilisé l'oeil de Kilrogg :** 

![Après l'utilisation Oeil de Kilrogg](https://user-images.githubusercontent.com/71191511/93003466-21fa0680-f53f-11ea-92c3-760263ab0b8d.jpg)

**Comment by joshwhedon** [comment]
Merci le probleme a deja ete signale malheureusment aucune solution n'a encore pu etre trouvee.
https://github.com/way-of-elendil/3.3.5/issues/140
