### ISSUE TITLE
Zul Aman Event Timer Urgent (Seul L'ours a disparu de la plage des recompenses !L'EVENT EST ENCORE PRESENT A TLK! )

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1018]
**Description**
L'event du timer de Zul aman ne se lance pas, Josh a répondu a une précédentes requête similaire en disant que les recompenses n'étaient plus disponible à partir de Wotlk sauf qu'érreur de sa part l'évent est toujours existant seul l'ours de guerre amani a été retiré de la plage de loot  a la 3.0.2 CF les patchnot blizzard (https://wowwiki.fandom.com/wiki/Amani_War_Bear#:~:text=The%20bear%20is%20decorated%20with,no%20longer%20obtainable%20by%20players.)
Ecrit ici aussi : 
https://worldofwarcraft.judgehype.com/news/wotlk-la-disparition-de-l-ours-de-zul-aman-114270/
Qu'ils souhaitent juste enlever l'ours des récompenses en sauvant les prisonniers mentionnant ainsi que l'event resterait présent ainsi que ces autres récompenses.
Le timer est encore présent jusqu'à cataclysme où l'instance sera retravaillée pour être un donjon à 5 joueurs. Il n'est mention nul part d'une disparition de l'évent de rapidité ni de la disparition des autres récompenses qui y sont liées 

Vidéo à l'appuie : 
https://www.youtube.com/watch?v=KcniogUqGGk
https://www.youtube.com/watch?v=InjQfvA-v2Q
https://www.youtube.com/watch?v=7r7b4eUeUE0
https://www.youtube.com/watch?v=aWMhi_0Qq5U

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Zul Aman
- Raid TBC 10 joueurs 
- Début d'évènement des gongs pour l'ouverture de la porte
- 3 à 10 joueurs (afin d'au minimum lancer l'évènement de la porte)

**Comportement attendu**
Enter the instance and talk to Harrison Jones to start the event and open the doors. You will now have 20 minutes to defeat the first animal-boss of your choice. Any of the loa spirit bosses will do and there is no required order, but two of them will add extra time to the timer.

Killing Nalorakk (bear) will add 15 minutes to your timer.
Killing Akil'zon (eagle) will add 10 minutes to your timer.
Other bosses will not grant additional time.
Therefore you have exactly 45 minutes to kill the first four bosses, which is a challenging task! Guilds that are doing Serpentshrine Cavern and The Eye will likely get three bosses down within 45 minutes, whereas guilds doing Hyjal and Black Temple content are the only ones likely to get all four. Karazhan / Tier 4 equipped raids should be able to get at least the first two chests, until they gear up with Zul'Aman and heroic badge equipment. Note that you must kill the boss before the timer expires. Unlike the Baron timed quest, engaging a boss before the timer expires is not sufficient.

The loot from the event is dependent on the number of hostages you rescue. All loot is from the Zul'Aman timed event loot table (see below).

First hostage will give a random piece of armor (iLvl 128).
Second hostage will give a random weapon (iLvl 132).
Third hostage will give a random ring (iLvl 141).
Fourth hostage will give a random ring (iLvl 141)

Source : **https://wowwiki.fandom.com/wiki/Zul%27Aman_timed_event**

Merci de ne pas fermer le poste tant qu'il y est possible d'y répondre.

**Comment by joshwhedon** [comment]
Je reactive l'event, sans l'ours normalement.
