### ISSUE TITLE
[quete] redemption donnée par Tirion Fordrig 

### ISSUE THREAD

**Issue by Matiel88** [way-of-elendil/3.3.5#1019]
**Description**
La quête Redemption donnée par Tirion Fordring ne se lance pas lorsqu'on l'accepte.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Nord-ouest des maleterres de l'est
- Alliance / Humain / Paladin
- Redemption
- Tirion Fordring

**Comportement attendu**
Normalement lorsqu'on accepte la quete, Tirion parle automatiquement de son histoire avant de nous proposer la suite.

**Comment by Ischjgt** [comment]
Il faut s'asseoir pour pouvoir écouter l'histoir
