### ISSUE TITLE
Boss: Kologarn - Ulduar

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1020]
**Description**
Name: Kologarn
Entry: 32930.
Name: Right Arm
Entry: 32934.
Name: Left Arm
Entry: 32933.

J'avais mentionné ici https://github.com/way-of-elendil/3.3.5/issues/722

> Le boss a respawn après avoir été tué, vu de mes yeux vus mais pas réussi à reproduire 

J'avais fait un ticket il y a longtemps sur le reset des gobs à Mortemines, Terrasse des Magistères, etc ... Cela arrivait quand le joueur restait longtemps dans l'instance, puis après un wipe, toutes les portes étaient réouvertes. C'était pas évident à reproduire, mais j'y arrivais
J'arrive plus à mettre la main dessus :(

J'ai l'impression que c'est la même chose ici ? le pont est là, puis après un wipe, le gob disparait et le boss est revenu

**Comment by joshwhedon** [comment]
Ouai mais comment reproduire ... Si je peux pas reproduire, je peux pas corriger.

**Comment by joshwhedon** [comment]
A reouvrir si des moyens de reproduire sont fournis. Dans l'immediat y'en a pas.
