### ISSUE TITLE
NPC: Molten Colossus - Ulduar

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1022]
**Description**
Pas l'impression que le NPC utilise ce spell : 
https://woehead.way-of-elendil.fr/?spell=64699

De plus, https://woehead.way-of-elendil.fr/?spell=64698 doit être lancé aléatoirement dans le groupe et pas seulement sur le tank
https://www.youtube.com/watch?v=Do-mItr_dts
Dès le début on voit le joueur prendre le spell alors qu'il ne tank pas

**Comment by joshwhedon** [comment]
Le lancement aleatoire fonctionne deja a premiere vue. L'autre sort sera corrige.
