### ISSUE TITLE
Le Rodeur d'en bas SSC 

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1023]
**Description**
Le rodeur d'en bas à partir d'un timer de 2 minutes lors du lancement du combat, rentre dans ce qui ressemble à sa P2 où il replonge dans l'eau, sauf que rien ne se passe il disparaît juste.

**Étapes de reproduction**
- Caverne du Sanctuaire du Serpent en 25 sur le  Boss Le rodeur d'en bas à la Phase  2 du boss en question en ayant une  Composition de groupe allant de 1 à 25 joueurs 

**Comportement attendu**
Submerge/Emerge: Toutes les 2 minutes, The Lurker va plonger, laissant le raid en compagnie de 9 adds parsemés sur les différentes plates-formes (3 au centre, 2 sur chaque plate-forme extérieure). 1 minute plus tard, The Lurker émerge et le combat continue (les adds cependant ne disparaissent pas)

source  : http://wow.elsi.free.fr/?page_id=11

**Comment by joshwhedon** [comment]
Corrige prochaine maj
