### ISSUE TITLE
Bug combat Zul Aman

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1025]
**Description**
Dans Zul Aman lorsque l'on tue les premiers mobs présent après l'ouverture de la porte principale ainsi que les petits mobs non élites en bas des escaliers juste après ces derniers le groupe de raid se retrouve en bug combat jusqu'à la fin du raid ou alors la sortie du raid par l'ensemble des joueurs avant de rentrer à nouveau dans Zul Aman
**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
Dans Zul Aman en 10 joueurs après l'ouverture de la porte en tuant les mobs en face de la porte et ceux en bas de l'escalier avec un groupe de joueurs composé de 3 à 10 personnes. 

**Comportement attendu**
Ne pas être en bug combat après cela.

**Comment by joshwhedon** [comment]
Pas reussi a reproduire. Merci de faire appel a un mj quand ca arrive a nouveau, afin qu'il obtienne plus d'information en utilisant les commandes mj. En attendant je clos ce bug, je le reouvrirai quand plus d'information seront fournies.
