### ISSUE TITLE
Summon Gargoyle health scaling

### ISSUE THREAD

**Issue by SnapiDk** [way-of-elendil/3.3.5#1026]
**Description**
Depuis la dernière merge, les hp de la gargouille, pet des DK impie (talent du lvl 51), se sont vus nerf.

**Étapes de reproduction**
Afin de constater le bug, c'est très simple, il suffit simplement de cibler la gargouille pour constater qu'elle n'a que 9k hp, faisant de celle-ci une cible facile, surtout en pvp (domaine où ce problème est le plus handicapant), rendant ce talent du niveau 51 quasiment inutile, puisque toutes les classes dps peuvent OS, one shot, cette dernière et ne s'en privent pas bien évidemment puisque cela reste le jeu malheureusement.

**Comportement attendu**
Comme chacun des pets, la gargouille scale les hp du maître. Le pourcentage semble être d'environ 80% des hp dans ce que j'ai pu calculer dans plusieurs séquences vidéos de 2v2. La gargouille snapshot l'AP du DK et je ne sais pas s'il en est de même pour les HP. Par là, je veux dire que la gargouille inflige des dégats "modifiés par la puissance d'attaque du chevalier de la mort": c-à-d que les procs AP (Attack Power) de type bijou ou via enchantements d'arme influent à la définition des dégats qu'aura la gargouille pendant les 30 sec, donc pendant l'entièreté de son apparition, rappelant que c'est un pet temporaire considéré comme le burst du DK impie.

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?v=jA5I7jCqyfg --> Vidéo d'un dk qui boost la hâte de cast de sa Gargouille, il cible sa gargouille donc on peut voir ses hp. L'upload date d'avril 2010 et si on est attentif le chaman a le bouclier et le stuff s8, donc le Wrathful, qui concerne la version 3.3 de wotlk offi, sachant que Cata est sortie en décembre 2010. Si l'on calcule le ratio HP gargouille/HP DK ça nous donne du 83%. Je rappelle que je ne sais toujours pas si ce ratio est une valeur fixe ou une valeur calculée sur l'endurance. Mais est à constater qu'elle bénéficie de 27k hp et pas 9k.

**Ressources additionnelles**
J'avoue, j'ai trouvé très peu d'indices provenants de sources officielles, pourtant j'ai fouiné dans les forums et autres sections commentaires de wowhead ou wowpedia/ wowwiki.Mmais la plupart parlent des dégats de la gargouille et de patchs concernant la 3.0. Je peux aussi amener mon expérience perso ayant joué sur d'autres serveurs privés que WoE, je n'ai jamais rencontré ce bug d'hp de la gargouille auparavant.

J'espère en tout cas que cette demande sera prise en compte et non refoulée, de la part d'un joueur qui aime sa classe ainsi que le PvP. <3
Perso in game: Sanpitie,
Merci.

**Comment by joshwhedon** [comment]
Voir les discussions precedentes sur la gargouille. A moins de fournir une formule exacte, rien ne sera modifie.
