### ISSUE TITLE
Totem de glèbe n'arrête pas les sorts à 'projectiles'

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#1027]
**Description**
Totem de glèbe ne prend pas les sorts à projectiles (cf projectile des arcanes/pénitences), le sort part directement sur le chaman.

**Étapes de reproduction**
Prenez un mage arcane ou un prêtre discipline, faites un duel contre chaman, posez un glèbe et lancez le sort projectile des arcanes ou pénitence et regardez.

**Comportement attendu**
Le totem de glèbe prend l'intégralité de la projection (projectile des arcanes/pénitence) avant de disparaître

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=8177
https://woehead.way-of-elendil.fr/?spell=42846
https://woehead.way-of-elendil.fr/?spell=53007

**Comment by joshwhedon** [comment]
Va falloir fournir des preuves du fonctionnement normal. Les sorts canalises ne sont generalement pas possible a renvoyer / detourner.

**Comment by Justforsoloq** [comment]
https://wowwiki.fandom.com/wiki/Grounding_Totem
(Spells with a travel time do not damage the target until the projectile hits; the totem will redirect any of these types of spells until it takes damage and summarily is destroyed. )

https://fr.wowhead.com/spell=23920/renvoi-de-sort#english-comments (renvoi de sort et glèbe marchent de façon similaire sous 3.3.5)
"Par mixter (14,336 –  4·22·89)  le 2010-06-28 (Mise à jour 3.3.5) |   
When penance is reflected , does it heal or dmg the caster?
hunter44 le 2010-08-13 (Mise à jour 3.3.5)
It damages the caster. Same goes for Holy Shock and any other Heal friendlies/Hurt enemies."

Par 165325 (500 – 4·8) le 2010-04-04 (Mise à jour 3.3.3)
Think I readsomewhere that channeled spells only reflect the first tic, but from my 3.3.3 experience with it, it reflects the whole thing. I killed around 4 mages with reflecting their whole arcane missiles in one reflect, really useful (worked with arcane missiles and penance). 

(Il parle d'un comment datant de la 2.4.3 donc le commentaire sur le first tick est daté)

**Comment by joshwhedon** [comment]
Le totem de glebe n'est pas un renvoi de sort, les commentaires ici concernent le renvoi de sort. Les 2 derniers posts concernent le renvoi de sort, qui lui renvoie bien les sorts en vol (exemple : Mage lance trait de givre => Guerrier utilise renvoi de sort => Trait de givre touche guerrier et est renvoye). 
Le fonctionnement du totem de glebe est different. Dans le cas du totem de glebe, la cible est selectionnee au moment du lancement du sort (le projectile ne se dirige jamais sur la cible d'origine, il va directement vers le totem). Si vous placez un totem de gleble pendant que le projectile est en vol, le projectile ne changera pas de direction, il a deja sa cible.  Par contre si vous placez un totem de glebe, et que plusieurs missiles sont lance avant que le premier missile ne touche, tous les missiles lances toucheront le totem de glebe.

J'ai teste, les sorts a projectile fonctionnent parfaitement bien avec le totem de glebe. Les seuls cas qui ne fonctionnent pas, ce sont les sorts a canalisation.

Maintenant pour en revenir aux canalisations, aucune de ces sources n'indiquent que les canalisations (que ce soit le sort d'origine ou les projectiles de la canalisation) peuvent etre devies vers le totem de glebe.

**Comment by Justforsoloq** [comment]
"Le fonctionnement du totem de glebe est different. Par contre si vous placez un totem de glebe, et que plusieurs missiles sont lance avant que le premier missile ne touche, tous les missiles lances toucheront le totem de glebe."
Non justement c'est le soucis. Si l'on pose le totem de glèbe AVANT (ça n'a jamais été une question de quand) les projectiles ceux ci ignorent le totem et vont directement sur le joueur sur way of elendil

**Comment by Justforsoloq** [comment]
https://drive.google.com/file/d/1cvJCGGsGsfrhlvzw9EKhPnusZh4XueKI/view?usp=sharing

**Comment by joshwhedon** [comment]
Non. J'ai teste, les missiles vont sur le totem. Ce dont vous parlez, penitence et projectile des arcanes, c'est pas un probleme de missile, c'est un probleme de canalisation. Essayez avec n'importe quel missile classique (trait de givre par exemple), il est redirige.
Une canalisation ne peut pas etre redirigee, et ses missiles, etant donne que la cible est deja decidee par la canalisation elle meme, ne peuvent pas etre rediriges non plus.
Le probleme ne concerne pas les missiles, mais les canalisations.

**Comment by Justforsoloq** [comment]
Ok on avait une différente définitions de missiles 
Je parlais des missiles du projectile des arcanes qui est une canalisation.

**Comment by joshwhedon** [comment]
Oui, et j'arrive pas a trouver d'information sur le comportement normal dans le cas des canalisations. Generalement les canalisations ne peuvent pas etre redirignee / renvoyees. Par contre les projectiles d'une canalisation dans le cas du renvoi de sort le sont. 
Mais dans le cas du totem de glebe, aucune idee et j'ai pas trouve d'information sur le sujet.

**Comment by Justforsoloq** [comment]
De plus la règle cités sur les canalisations sur woe n'est pas non plus normale, vu que le totem de glèbe prend bien en compte certaines canalisations (cf fouet mental, drain d'âme, et autres canalisations qui n'ont pas de "projectiles").

**Comment by joshwhedon** [comment]
Oui pour ca que je dis generalement. Il y a des flags sur les sorts cote client qui definissent si ils sont renvoyables / redirigeables / etc.

**Comment by Justforsoloq** [comment]
https://www.youtube.com/watch?v=4R6QNalP-5E

**Comment by joshwhedon** [comment]
Merci, a premiere vue donc ca redirige les projectiles, pas la canalisation, comme pour les renvois.

**Comment by Justforsoloq** [comment]
Bah oui mais sur woe ça ne redirige rien

**Comment by Justforsoloq** [comment]
(cf la vidéo que j'ai link google drive, je l'ai mise accès all)

**Comment by joshwhedon** [comment]
Corrige prochaine maj merci pour la video.

**Comment by Satarians** [comment]
Le totem de glebe ne prend plus la main de rétribution du paladiiiiin svp

**Comment by joshwhedon** [comment]
La maj a meme pas encore ete passee hein.

**Comment by Justforsoloq** [comment]
Attention para contre précision par rapport à la main de rétribution, c'est le composant dégâts qui casse, pas le composant taunt (le seul taunt marchant sur tlk sur le glèbe étant le taunt du pet chasseur)

**Comment by Justforsoloq** [comment]
En fait je tombe sur ça donc faut scrap tout x) : 
https://wowwiki.fandom.com/wiki/Hand_of_Reckoning
 Hotfix (2009-08-08): "Hand of Reckoning is no longer able to be used on targets that are immune to taunt, including players."

**Comment by Justforsoloq** [comment]
Fixes bug 3.3.5 en plus : Reckoning: Tooltip clarified to indicate taunt immune targets will not take damage from this ability (donc quoi qu'il arrive le taunt casse pas le glèbe)

**Comment by Justforsoloq** [comment]
Après recherche, le totalement immune en pvp c'était seulement sur PTR, sur 3.3.5 tu peux bien HoR (taunt) les joueurs mais sans leur mettre de dégâts. Par contre ça ne fait rien sur les totems
