### ISSUE TITLE
Zul Aman Timer Event aucune interaction avec les coffres de butin des prisonniers sauvé dans le temps imparti

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1028]
**Description**
Zul Aman Timer Event aucune interaction avec les coffres de butin des prisonniers sauvé dans le temps imparti.
Une fois un boss tué le timer évolue bien jusqu'au suivant et ainsi de suite jusqu'à l'élimination des 4 boss necéssaire à la validation du timer. Une fois l'évènement validé les prisonniers apparaissent bien sur les différents spot des boss correspondant où il est possible de leurs parler et ainsi lancer l'apparition des coffres de butin. Sauf qu'une fois l'interaction faite avec les PNJs, l'objet apparaît bien visuellement mais il est impossible d'avoir une quelconque interaction avec pour les coffres correspondant aux boss Akil'Zon, Jan'Alai et Halazzi quant à Nalorakk un coffre apparaît avec une intéraction possible mais il est alors verouillé et aucun mécanisme présent dans le jeu permet son ouverture.
Nous avons fait nos test avec 3 niveau 80 (tank, heal et dps) où un temps moyen de 2 à 3 minutes par boss se sont écoulé nous permettant de voir toutes leurs phases. 
Et avec un raid complet de niveaux 70 avec un temps moyen légèrement plus rapide. 

**Étapes de reproduction**
Zul Aman 10 joueurs avec un groupe de 3 personnes minimum en effectuant l'évènement du timer. 

**Comportement attendu**
Une interaction devrait être possible avec les coffres afin d'obtenir le butin des prisonniers ( Sans l'Ours qui n'est plus disponible a Wotlk, mais les autres récompenses le sont toujours)
Enter the instance and talk to Harrison Jones to start the event and open the doors. You will now have 20 minutes to defeat the first animal-boss of your choice. Any of the loa spirit bosses will do and there is no required order, but two of them will add extra time to the timer.

Killing Nalorakk (bear) will add 15 minutes to your timer.
Killing Akil'zon (eagle) will add 10 minutes to your timer.
Other bosses will not grant additional time.
Therefore you have exactly 45 minutes to kill the first four bosses, which is a challenging task! Guilds that are doing Serpentshrine Cavern and The Eye will likely get three bosses down within 45 minutes, whereas guilds doing Hyjal and Black Temple content are the only ones likely to get all four. Karazhan / Tier 4 equipped raids should be able to get at least the first two chests, until they gear up with Zul'Aman and heroic badge equipment. Note that you must kill the boss before the timer expires. Unlike the Baron timed quest, engaging a boss before the timer expires is not sufficient.

The loot from the event is dependent on the number of hostages you rescue. All loot is from the Zul'Aman timed event loot table (see below).

First hostage will give a random piece of armor (iLvl 128).
Second hostage will give a random weapon (iLvl 132).
Third hostage will give a random ring (iLvl 141).
Fourth hostage will give a random ring (iLvl 141)

Source : https://wowwiki.fandom.com/wiki/Zul%27Aman_timed_event

Je joins des screens où mont cursus montre les interactions / Non interactions présente devant les coffres 
![WoWScrnShot_092120_195856](https://user-images.githubusercontent.com/71186829/93804562-ca4a5200-fc46-11ea-9e81-ef5d73d6a775.jpg)
![WoWScrnShot_092120_200946](https://user-images.githubusercontent.com/71186829/93804566-cb7b7f00-fc46-11ea-981c-02b5ac606c6f.jpg)
![WoWScrnShot_092120_201136](https://user-images.githubusercontent.com/71186829/93804567-cb7b7f00-fc46-11ea-8e89-3f7717dbdc2d.jpg)
![WoWScrnShot_092120_201221](https://user-images.githubusercontent.com/71186829/93804568-cc141580-fc46-11ea-81c1-cf67fec80c43.jpg)

Si il est possible de laisser l'issue up avec la possibilité de répondre si le problème n'est pas compris / reproductible afin de pouvoir apporter des renseignement sans avoir a recréer le topic sans arrêt s'il vous plait, et aussi avoir des renseignement sur la possible correction de ce bug en vous remerciant.

**Comment by Foncegrive** [comment]
Nous avons refait un test avec notre guilde de lvl 70 et en tuant Halazzi dans un ordre différent de celui où on le tue en dernier c'est à dire en le tuant en premier / deuxième / troisième / quatrième cela a pour cause de terminer l'évènement et les récompenses sont toujours indisponibles

**Comment by joshwhedon** [comment]
Corrige prochaine maj

**Comment by Ischjgt** [comment]
Tout pareil

**Comment by Ischjgt** [comment]
Les coffres de
Harkor Entry: 23999.
Ashli Entry: 24001.
Kraz Entry: 24024.
spawn mais aucune interaction possible

seul celui de Tanzar Entry: 23790. marche correctement

(dit moi si tu as besoin des IDs des gobs)

**Comment by Zaralbahk** [comment]
je confirme 3 coffre buggé et un qui marche testé aujourd'huis
