### ISSUE TITLE
Haut fait Démineur

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1029]
https://woehead.way-of-elendil.fr/?achievement=1428
Pour ce haut fait il nous faut aller dans les Pics foudroyés, au champ de mines de Grilledouille 
Map: 571 (Norfendre) Zone: 67 (Les pics Foudroyés) Area: 4458 (Champ de mines de Grilledouille) Phase: 1
14:12:21 X: 6035.054688 Y: -654.714844 Z: 370.618134 Orientation: 0.593978
14:12:21 grid[43,30]cell[2,6] InstanceID: 0
14:12:21  ZoneX: 35.098511 ZoneY: 87.793221
14:12:21 GroundZ: 370.014832 FloorZ: 370.014832 Have height data (Map: 1 VMap: 1 MMap: 1)

Il nous faut ensuite "exploser" sur les mines et être projeté avant de reprendre une ou plusieurs mines jusqu'à avoir totalisé 10 explosions consécutives. 
Actuellement, les mines explosent bien mais malgré le nombre d'explosion requis, le haut fait ne se valide pas.

Mines en question : 
 [Land Mine] GUID: 55478 ID: 191502
14:09:41 X: 6012.970215 Y: -671.945984 Z: 370.260010 MapId: 571
14:09:41 Orientation: -2.897240
14:09:41 Phasemask 1
14:09:41 SpawnTime: Full:10s Remaining:0s

Cf vidéos WowHead : https://www.wowhead.com/achievement=1428/mine-sweeper#videos
ou encore https://www.youtube.com/watch?v=CDzJYQy38rA

**Comment by joshwhedon** [comment]
" without landing." j'ai teste et ca a l'air de fonctionner, meme si tres difficile. Il faut mettre moins de 3,5 secondes pour prendre la mine suivante (donnees client du sort) sinon le compte se reset. J'ai aussi regarde en db et pas mal de joueurs ont le haut fait.
