### ISSUE TITLE
Talent Douleur et souffrance

### ISSUE THREAD

**Issue by dirsang** [way-of-elendil/3.3.5#1030]
Bonsoir,

J'ai passé ma soirée à tester le refresh du fouet mental sur le mot de l'ombre : douleur.
En effet grâce au talent Douleur et Souffrance, le TEMPS du mot de l'ombre est ré initialisé, sauf que là il ne ré initialise pas que le temps, mais aussi la puissance des sorts en temps réel. Normalement l’intérêt est de poser le mot de l'ombre au moment où la ps est la plus haute, mais là en faite ça sert à rien car lorsque notre puissance des sorts redescend, le mot de l'ombre est réinitialisé avec le fouet mental avec une puissance des sorts plus faible.

**Étapes de reproduction**

- Prêtre
- Troll
- Ombre
- Talent : Douleur et Souffrance / Sort : fouet mental et mot de l'ombre:douleur
- tester sur poteau et en icc10n

**Comportement attendu**
Le fouet mentale ne ré initialise que la durée du mot de l'ombre : douleur et non les stats.

**Comment by Justforsoloq** [comment]
Non ça me marche pas comme ça.

**Comment by dirsang** [comment]
tu es sur ?

**Comment by Justforsoloq** [comment]
Yep c'est la même mécanique que la rolling corruption.
Les caract snapshot sont les % modifier (pour ça qu'on conseille au sp d'attendre le 5/5 shadow weaving avant de poser un SWP) et le crit. 
Tu as un snapshot de la PS mais il est refresh sur la ps actuelle quand le SWP est refresh via le fouet mental

**Comment by dirsang** [comment]
Mais dans ce cas le talent est inutile, il vaut mieux le reposer manuellement afin de profiter du up de ps ?

**Comment by Justforsoloq** [comment]
Tu profites pas de up ps sans le talent.

**Comment by joshwhedon** [comment]
Y'a un bug ou pas ?

**Comment by Justforsoloq** [comment]
Pas dans ce qui est report dans ce bug report en tout cas.
