### ISSUE TITLE
Baisse de dégâts sur l'attaque circulaire.

### ISSUE THREAD

**Issue by Goudronn** [way-of-elendil/3.3.5#1031]
**Description**
L'attaque circulaire, talents du 5e palier du guerrier Arme, ayant pour but de reproduire les dégâts sur une cible principale a une secondaire proche, jusqu'à 5 attaque.

**Étapes de reproduction**
Utilisation de 2 poteau/Mannequin d'entraînement, utiliser l'attaque circulaire, s'approcher en sorte que vous soyez entre les deux mannequin pour que la capacité puisse proc puis faites soit une attaque basiques(coup blanc), une frappe mortelle, Exécution ou Fulgurance
- Classe :  Guerrier
- Race : peut important mais orque.
- Spécialisation : Arme
- Sort / Talent / Etc : Attaque circulaire (talents)
- Circonstances (Donjon, Raid, PvP, autre) Incovéniant en PvE comme PvP
- Equipement  https://way-of-elendil.fr/armory/character/539954-gudrunn
- Buffs / Debuffs / Enchaînement de sort / Etc : Buff -> Attaque circulaire.

**Comportement attendu**
la capacité doit reproduire les même dégâts fait sur la cible secondaire, CàD 5 000 de dégâts sur cible principale et secondaire.

**Captures d’écran / Vidéos**
Screen avec une seul attaque (pourfendre et blessures profonde ne sont pas a prendre en compte).
![image](https://user-images.githubusercontent.com/71974550/94366504-111dc900-00d9-11eb-908e-48465d98cfd9.png)

![image](https://user-images.githubusercontent.com/71974550/94366522-285cb680-00d9-11eb-8f39-d6443ff84661.png)

Ici plusieurs attaque, exactement 3 dont 2 coup blanc (crit) et une fulgurance (crit) : 
![image](https://user-images.githubusercontent.com/71974550/94366635-e2542280-00d9-11eb-8027-ca28579885bd.png)
Pour connaitre les dégâts normalement exact de l'attaque circulaire, on doit additionner les dégâts de l'"attaque" soit 11.5k avec les dégâts de la fulgurance de 8.3k qui donne normalement 19.8k mais sur le screen, l'attaque circulaire a fait 12.6k soit 63% seulement ont été reproduis. A savoir que sur ce dernier, les cibles ont été affaiblies par le talents frénésie Sanglante, augmentant les dégâts physique de 4%

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides :
https://woehead.way-of-elendil.fr/?spell=12328 avec https://woehead.way-of-elendil.fr/?item=43428.

sorts utilisé :
https://woehead.way-of-elendil.fr/?spell=12328
https://woehead.way-of-elendil.fr/?spell=7384
https://woehead.way-of-elendil.fr/?spell=47486
https://woehead.way-of-elendil.fr/?spell=29859

**Comment by Goudronn** [comment]
A noter qu'il est aussi possible de le reproduire avec Enchaînement,les tics de tempête de lames soit les tourbillons(mais ils sont tout deux difficile a reproduire car elle consommeront par deux les stack d'attaque circulaire), frappe héroïque, même lancer héroïque si vous vous trouvez au corps a corps.

**Comment by Ischjgt** [comment]
https://hilbert.wordpress.com/sweeping-strikes-guide/

**Comment by Goudronn** [comment]
C'est pas plutot le SS de vanilla cque ta sorti ?

**Comment by Goudronn** [comment]
car la sweeping strikes est utilisable aussi en posture berserker, or sur ton lien, il n'est dit que en combat

**Comment by Ischjgt** [comment]
Ça change rien aux méthodes de calculs

**Comment by Goudronn** [comment]
Pardon ? Vous nous bassiner de sortir des sources officiel de la 3.3.5, ici en me basant uniquement sur la lecture du spell et les dégats produit sur votre serveur, et vous vous permettez de sortir un thread basé sur la 1.11 et me dire que c'est la même choses ? Il doit avoir un problème dans vos valeurs. Soit vous vous basez uniquement sur les 3.3.5, soit vous faites un autre jeux.

**Comment by Ischjgt** [comment]
Ok bye

**Comment by Goudronn** [comment]
Vous savez, il suffit de le dire si vous n'avez pas envie de traiter correctement le topic.

**Comment by Ischjgt** [comment]
En fait, c'est toi qui n'a toujours pas compris comment marche le bugtracker.
La méthode de calcul est la bonne et il n'y a pas d'erreur dans le calcul.
Si il s'avère qu'un tooltip a été oublié lors d'une mise à jour quelconque, c'est à toi de venir le prouver. Les tickets sans preuve ça a jamais été notre délire

**Comment by Goudronn** [comment]
Tu te bases sur des sources de vanilla, je te sors des sources sur votre realm et du fait qu'un aucun moment c'est censé être écrit sur le spell que les dmg sont réduits. Je n'ai pas la possibilité de trouver des calcul exact de la 3 3 5.  Tu sors comme une fleur en sortant des sources basés sur VANILLA et non WOTLK. A un moment, dire que c'est moi qui suis en tord est de la mauvaise foi pur. Alors que tu es le premier a dire qu'il faut donner des sources tlk. Donc, se baser sur un script de vanilla sur un serv tlk est une erreur de votre part.

**Comment by Goudronn** [comment]
1.11 =/ 3.3.5 hein

**Comment by Ischjgt** [comment]
J'ai pris ce lien au hasard, pour te montrer que si t'as pas de preuves, Josh changera rien.

**Comment by joshwhedon** [comment]
J'ai aussi cherche de mon cote, pas pu trouver la moindre information pour la 3.3.5 indiquant que les calculs sont supposes etre differents. Du coup si de votre cote vous trouvez quelque chose, je changerai, mais jusqu'a preuve du contraire, le comportement actuel est le comportement attendu.
