### ISSUE TITLE
paladin/ bouclier saint vehicule

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1032]
Le bouclier saint ne proc pas quand on subi des degats de vehicules

Se faire tapé par un vehicules avec le buff bouclier saint

Joug rivage

Un degats de vehicules sur un joueur avec le buff bouclier sant entraine le buff qui absorbe

**Comment by joshwhedon** [comment]
Il y a que le lancer de cailloux qui fait pas proc, tous les autres sorts de vehicule font proc.
Corrige prochaine maj.
