### ISSUE TITLE
Quest: Vaillant de Darnassus - Changement de faction

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1033]
**Description**
Un joueur n'a pas accès aux dernières suites de quête pour l'intendant de l'Exodar,
il a accès aux 4 autres intendants de l'alliance

J'ai pas eu le temps de demander quand est-ce qu'il avait changefaction

<img width="387" alt="Capture d’écran 2020-09-28 à 17 35 44" src="https://user-images.githubusercontent.com/60295792/94455290-2cf59d80-01b3-11eb-9fd8-1b780bc35e0b.png">

Mais j'ai remarqué ça, il est Elfe de la nuit et il avait les 2 quêtes Vaillant de Darnassus en rewarded, sachant que l'une est strictement pour les elfes de la nuit et l'autres pour le reste de l'alliance

J'ai enlevé la 13706 pour voir, mais toujours pas d'accès aux quêtes pour les draeneis

Mitsuha pour le nom du joueur

Si tu as une piste je suis preneur

**Comment by joshwhedon** [comment]
Tu as tente de regarde les conditions sur woehead pour la quete suivante ?

**Comment by Ischjgt** [comment]
Pour moi tout est ok pour les quêtes.
De plus, le joueur a https://woehead.way-of-elendil.fr/?achievement=2778 
Il est exalté à Exodar, mais il n'a pas 
https://woehead.way-of-elendil.fr/?achievement=2761
La condition pour le Champion de l'exodar n'est pas remplie 

<img width="256" alt="Capture d’écran 2020-09-29 à 11 25 18" src="https://user-images.githubusercontent.com/60295792/94540232-8064fb80-0246-11eb-900b-da583633f32b.png">
<img width="353" alt="Capture d’écran 2020-09-29 à 11 25 23" src="https://user-images.githubusercontent.com/60295792/94540234-81962880-0246-11eb-921a-a402f01c3766.png">

Pour info les changefaction ont eu lieu il y a quelques années, donc c'est spécifique au joueur je pense

**Comment by joshwhedon** [comment]
Va me falloir un peu plus de details niveau des quetes completees ou pas pour ce joueur, parce que la de tete, je sais pas ... faudrait quasiment regarder toute la chaine de quete pour voir ou ca merde dans les quetes completees pour lui.

**Comment by Ischjgt** [comment]
Voici la suite a faire pour sa faction du début
https://woehead.way-of-elendil.fr/?quest=13667 le tournoi d’argent
 - 
https://woehead.way-of-elendil.fr/?quest=13828 la maitrise de la mêlée
https://woehead.way-of-elendil.fr/?quest=13835 brise-bouclier
https://woehead.way-of-elendil.fr/?quest=13837 la maitrise de la charge
-
https://woehead.way-of-elendil.fr/?quest=13672 prêt pour le défi
https://woehead.way-of-elendil.fr/?quest=13679 le défi de l’aspirant

Elfe de la nuit
https://woehead.way-of-elendil.fr/?quest=13689 Un vaillant de darnassus
-
https://woehead.way-of-elendil.fr/?quest=13717 Les devoirs du vaillants
https://woehead.way-of-elendil.fr/?quest=13725 le défi du vaillant
-
https://woehead.way-of-elendil.fr/?quest=13735 La naissance d’un champion

Toute en rewarded, la suite débloque les quêtes pour les autres factions

**Comment by Ischjgt** [comment]
Quand la quête la naissance d'un champion est terminée pour sa propre faction, il est ensuite proposé aux joueurs de représenter les autres Capitales,
À savoir pour l'alliance et pour un elfe de la nuit qui a déjà fait 13689
13705 - [Vaillant de l'Exodar] 
13704 - [Vaillant de Gnomeregan]  [rewarded]
13703 - [Vaillant de Forgefer]  [rewarded]
13593 - [Vaillant de Hurlevent]  [rewarded]

**A noter que 13706 - [Vaillant de Darnassus] était rewarded pour le joueur alors qu'elle ne l'aurait pas du, je lui ai remove mais il ne s'est rien passé**

Ensuite
13718 - [Les devoirs du vaillant]  [rewarded]
13716 - [Les devoirs du vaillant] 
13715 - [Les devoirs du vaillant]  [rewarded]
13714 - [Les devoirs du vaillant]  [rewarded]

13699 - [Le défi du vaillant]  [rewarded]
13713 - [Le défi du vaillant]  [rewarded]
13723 - [Le défi du vaillant]  [rewarded]
13724 - [Le défi du vaillant]

Je rédige le ticket en même temps que je regarde,
Il manque https://woehead.way-of-elendil.fr/?quest=13732 au joueur mais Lana ne lui propose rien, mais il a bien 13713 - [Le défi du vaillant]  en rewarded comme dit plus tot, je lui ajoute ?

**Comment by joshwhedon** [comment]
C'est possible oui, honnetement j'ai beau regarder je sais pas trop ce qui se passe. 13732 n'a pas de prerequis particuliers, aucune conditions additionelles. Du coup je sais pas.
