### ISSUE TITLE
NPC: Ram Master Ray

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1034]
**Description**
Name: Ram Master Ray
Entry: 24497.

Après avoir fini 11409 et 11412, le NPC propose un dialogue où le joueur peut gagner quelques jetons en plus avec le bélier.
Si le joueur est en monture alors qu'il reçoit le spell https://woehead.way-of-elendil.fr/?spell=43880, rien ne se passe et le joueur doit attendre le lendemain pour pouvoir refaire la manip'

(C'est ok pour le spell avec les 2 quêtes)

**Comment by joshwhedon** [comment]
Corrige prochaine maj
