### ISSUE TITLE
Boss: Reliquary of the Lost - Black Temple

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1035]
**Description**
Les joueurs qui s'approchent trop du boss en prenant le couloir pour monter vers Teron font sortir 23418 - [Essence de la souffrance]  du Reliquaire des perdus (22856) et reçoivent les auras 41292 - [Aura de la souffrance, rank 1 frFR] et 
42017 - [Aura de la souffrance, rank 1 frFR]

**Étapes de reproduction**
- .tele blacktemple
- .go c id 22882
- s'approcher ici 
<img width="884" alt="Capture d’écran 2020-10-02 à 22 42 29" src="https://user-images.githubusercontent.com/60295792/94968133-ab7a7400-0500-11eb-92c8-19518fdba870.png">
Le boss sort du reliquaire (quelques secondes d'animations) et les joueurs reçoivent les auras 41292 et 42017

**Comportement attendu**
Le boss reste dans le reliquaire si hors champ ?

**Comment by joshwhedon** [comment]
Corrige prochaine maj
