### ISSUE TITLE
Quest: Objet de quête

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1036]
**Description**
Problème légèrement différent que celui habituel rencontré par le passé avec les objets de quête (est-ce que t'as fait une modif ?)
C'est arrivé 2 fois pour l'instant, le premier 29/09 ticket 17788 :
> J'ai un souci avec la quête "prêt pour le défi". Il me demande 15 Sceau d'aspirant, or je n'en ai que 12 , il me propose de valider la quete.... Et les pnj ne me redonnent plus de quetes pour en obtenir.. Et je ne me souviens pas les avoir delete

Et aujourd'hui ticket 17813 :
> la quête un accueuil chaleureux au refuge cénarien.. . Quand j'ai looté la 30eme griffe de naga celle si na pas été prise en compte mais cela à valider la quête sans que je puisse la rendre

Pour le 2ème, la quete était marquée complete avec 29 griffes, j'ai demandé au joueur de mettre les objets en banque et de les enlever, la quête était de nouveau marquée en active, mais le joueur ne pouvait toujours pas récupérer la 30ème griffe (il m'a montré le spot où il allait, c'était sur un spot de mobs qui loot à 95% https://woehead.way-of-elendil.fr/?item=24280)

Je ne sais pas comment mais la quête est repassé à "complete", le joueur est retourné voir le PNJ et il y avait toujours un point d'interrogation jaune sur sa tête

_J'ai pas trouvé le ticket initial qui mentionne juste le soucis avec les items tags "objet de quête"_

**Comment by joshwhedon** [comment]
Y'a un moyen de reproduire ?

**Comment by joshwhedon** [comment]
Impossible de reproduire le probleme, merci de reouvrir une fois des moyens de reproduction trouves.
