### ISSUE TITLE
Spell: Nova de feu - Sombre chaman

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1037]
**Description**
https://woehead.way-of-elendil.fr/?spell=46551
utilisé par https://woehead.way-of-elendil.fr/?spell=32062
invoqué par https://woehead.way-of-elendil.fr/?npc=16873

![WoWScrnShot_100520_183122](https://user-images.githubusercontent.com/60295792/95109866-76a73080-073d-11eb-80f1-d53bbed2b342.jpg)

On m'a signalé ça, je trouve pas d'infos (un joueur de ce niveau a environ 3kpv)

Sur Wowhead, ce spell est utilisé par des level 70 non élite à sunwell (ça colle un peu plus déjà)
https://fr.wowhead.com/spell=46551/nova-de-feu
Pas trouvé quel spell pourrait être le bon :(

**Comment by joshwhedon** [comment]
Je trouve pas de sources indiquant qu'il doit lancer ce sort, du coup je le retire.
https://www.wowhead.com/npc=16873/bleeding-hollow-dark-shaman#comments
