### ISSUE TITLE
Quel'Delar plus disponible dans mon inventaire pour la quête "Les salles des Reflets"

### ISSUE THREAD

**Issue by Grahaams** [way-of-elendil/3.3.5#1038]
**Description**
Pour la quête "Les salles des Reflets", je suis rentré seul dans le donjon en mode héroïque (par erreur) et suis mort face à l'épée Quel'Delar. je suis sorti et ai passé la difficulté du donjon en mode normal. Je me suis ensuite rendu compte que je n'avais plus Quel'Delar dans mon inventaire et l'évènement avec Uther ne se déclenchait plus. Impossible de terminer la quête. 

J'ai essayé de repasser le donjon en mode héroïque mais même constat, plus d'évènement et plus d'épée.

Comment puis-je relancer l'évènement ? Si j'abandonne la quête et que je la reprend auprès du PNJ, est-ce que l'objet Quel'Delar réapparaitra dans mon inventaire ?

**Étapes de reproduction**
- Emplacement : Donjon salles des reflets
- Faction / Race / Classe du personnage utilise : Draeneï Paladin
- Nom de la quête : Les Salles des Reflets
- PNJ qui donne la quête : Caladis Brillelance, Le concordat argenté

**Comportement attendu**
L'objet Quel'Delar est de nouveau dans mon inventaire, pour me permettre de relancer l'évènement dans la salles des reflets.

Merci à vous !

**Comment by Ischjgt** [comment]
Abandonne et reprends la quête
