### ISSUE TITLE
Quest: Enfumez-les

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1040]
**Description**
https://woehead.way-of-elendil.fr/?quest=12324
https://woehead.way-of-elendil.fr/?quest=12323

37621 - [Bombe fumigène]  marche, les 27570 - [Venture Co. Straggler] sont bien apeurés mais quand ils disparaissent, le compteur reste à 0

**Comment by joshwhedon** [comment]
J'arrive pas a reproduire, je mets une modif au cas ou mais pour moi tout marche.
