### ISSUE TITLE
 Donjon de la tempête [Al'ar]

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1041]
**Description**
Lors de la P2 d'alar quand il renaît au centre, si sa précédente cible avant son envol meurt, lors de sa redescente après sa phase en l'air, il ne redescend plus.

**Étapes de reproduction**
 Donjon de la tempête [Al'ar] raid 25 joueurs TBC être suffisamment de joueurs pour arriver en p2 et que la cible d'alar avant son envol meurt pour observer qu'il ne redescend pas

**Comportement attendu**
Que le boss redescende bien après son envol malgré sa précédente cible morte.

Phase II
Phase II begins right after Al'ar reaches 0%. At this point it will explode for ~5000 fire damage with AoE knockback and reappear roughly at the center of the room, where it will cast a powerful AoE knockback with fire damage. After this, it must be immediately tanked or it will start casting its flame buffets once again. Phase II is not an aggro wipe and Al'ar should fly to the top threat person. But it may decide to stay put and cast flame buffet if not picked up immediately. In case there are still some adds up from phase I, raid should focus on getting them down as soon as possible, preferably before Al'ar casts the first Dive Bomb. Other than that, phase II is all about survivability. Melee DPS should focus on the boss while ranged DPS focuses on the adds and then Al'ar if no adds exist.

While being on the ground, it will occasionally spawn flame patches on random people that work in a similar fashion to void zones. People need to be aware and move away from the fire trails as soon as possible. Al'ar can charge people for 5000 damage leaving them momentarily stunned. It usually flies back to its previous target but can sometimes remain next to the charged target and cast flame buffet until taunted.

It also casts a Melt Armor debuff on the current MT every 60 seconds. The other tank must taunt immediately when this happens. Having both tanks wear a high amount of +hit helps a lot. Al'ar's melee damage is fairly weak, so reaching the hit cap is more important than damage mitigation. Note that the current MT can use Inv misc pocketwatch 02 [Moroes' Lucky Pocket Watch] every time the debuff is applied. After Dive Bomb, Al'ar sometimes targets the tank having Melt Armor, so the current MT should be ready to taunt, and never move too far away from the other tank. A Warrior MT can also Intervene. While most boss mods will announce when Melt Armor is cast and its duration, it will be beneficial to many to announce this over Vent or Teamspeak. Healers must be ready to change targets when needed.

Last but not least, while airborne, it will cast Dive Bomb on a seemingly random target. The Meteor does about ~5000 fire damage on a single target and should be survivable or avoided by running from the area. Using consumables/abilities that can mitigate this sort of damage (fire protection potions, ice barrier, mana shield, barkskin etc) is also recommended. People should be aware of the fact that Al'ar spawns with an AoE fire knockback where the meteor hits the ground as well as with two ember adds, so your raid should move away from that spot as soon as possible. The adds spawn immediately when the meteor hits the ground, whereas Al'ar spawns roughly 2 seconds afterwards, giving a small window to pull the adds out without accidentally hitting or taunting Al'ar. Failure to do so will result in them being knocked across the room taking both fire damage and potentially some falling damage. Also be sure to NOT kill adds during a meteor or Al'ar won't take the 2% damage from its death.

Note: Everyone should stay off the ramps and in the room completely, if Al'ar targets a person for Dive Bomb while they are on the ramps, Al'ar will evade glitch and go back to full health.

source ; https://wowwiki.fandom.com/wiki/Al%27ar

**Comment by joshwhedon** [comment]
JE vais galerer a reproduire je pense. Vous pouvez me dire ce qu'il a fait ? Il s'est envole au milieu ? Il a invoque ses adds ou pas ? Il a fait toutes ses actions et n'est pas retourne en combat apres ?

**Comment by Foncegrive** [comment]
Oui je me doute bien en voyons les conditions de reproduction :/. Alors on arrive très bien en P2 c'est à dire quand il meurt et qu'il renaît au milieu de la salle. A partir de là il va il réapparaître normalement avec les degats de feu au raid si il est pas tank, le debuffs degats de feu sur le MT,  jusqu'à sont tourbillon où à la fin de celui ci son aggro est reset et il se dirige vers une des personnes ayant generé le plus d'aggro avant son reset (généralement les caster) à partir de là, si il arrive vers cette personne et qu'il la tue avant de s'envoler, lors du moment où il est supposé redescendre il va rester en l'air et du coup on va avoir les degats de feu en permanence comme si il n'était pas tanké ! Sinon il fait bien son météore et redescend dessus quand tout va bien, les adds quant à eux pop bien aussi et les zones au sol sont aussi présente.

**Comment by joshwhedon** [comment]
Corrige prochaine maj normalement.
