### ISSUE TITLE
La Caverne du Sanctuaire du Serpent: Leotheras l'Aveugle

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1043]
**Description**
Les dégats lors de sa forme humaine sont beaucoup trop hauts comparé a ce qu'ils devraient être. 

**Étapes de reproduction**
La Caverne du Sanctuaire du Serpent raid 25 joueurs TBC sur Leotheras l'Aveugle juste à tanker sa forme humaine où l'ont remarque les dégats très élevé comparé a ce qui est annoncé normalement. 

**Comportement attendu**
Dans la première phase, le boss est en forme humanoïde et il sera tanké tranquillement par le MT. Il tape comme une mauviette et les heals seront franchement faciles. 
Source : https://worldofwarcraft.judgehype.com/strat-instances-glisseroc9/

https://www.youtube.com/watch?v=1kZx-oO2ako
Le tank est en haut à gauche on peut voir plus ou moins comment il encaisse les dégats de base.

**Comment by joshwhedon** [comment]
Corrige prochaine maj
