### ISSUE TITLE
Bug onyxia P3

### ISSUE THREAD

**Issue by Bleuphonix** [way-of-elendil/3.3.5#1044]
**Description**
Sur onyxia 25 On se retrouve ou le boss passe en P3 elle se met e regen vie et se met a regen vie 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Raid onyxia
- 25
- Onyxia
- En p3 sur 2 try de suite le boss a regen des sa début de P3 (regen jusqu'a 65% on pue avoir sur l'un d'eux (je rappel on etait en P3) )
- 1 tank 3 heal environ 9 cat 5 cac

**Comportement attendu**
Pas de regen du boss

**Captures d’écran / Vidéos**
pas de video dsl 

**Ressources additionnelles**
Au niveau ressource additionnelle j'ai rien qui peux être pertinent 
Peu être cela mais je sais pas https://www.youtube.com/watch?v=27k7dLkAjvc&t=482s

De plus j'y ajoute a se rapport la porter des jets de lave sur la P3 qui fear tous le monde dans le raid sur ce serveur même ceux qui ne sont pas sur les failles 

je garantie pas que le bug remarche mais je préfère faire ce rapport au cas ou

**Comment by joshwhedon** [comment]
Je mets un correctif prochaine maj, je sais pas si ca va corriger le probleme j'arrive pas a reproduire.

**Comment by Bleuphonix** [comment]
Re je suis pas revenu la semaine dernière car on l'a tomber avec un groupe un poil plus puissant mais même si le groupe était assez puissant elle avais quand même ça regen 
Ce soir nouveau try de la moche avec moins de puissance de feu mais arriver en P3 toujours un belle regen du boss 30 sec de fight 35% -> 74% de vie

**Comment by Shotsx** [comment]
De souvenir il me semble avoir tester avec jugement de lumière du paladin elle regen au moment ou la lave sort du sol , sans le spell actif sur elle ça vie ne remonte pas

**Comment by Bleuphonix** [comment]
Effectivement j ai remarquer quelle regen suivant le nb de personne qui se prennent la lave mais si c est le jugement de lumière qui proc sur elle c est juste péter xD

**Comment by Shotsx** [comment]
Je pense que en gros quand la lave sort du sol elle inflige des dégâts a Onyxia mais cette même lave est considérer comme un sort du boss 
https://woehead.way-of-elendil.fr/?spell=20185
"conférer aux attaques contre la cible jugée une chance de rendre 2% de son maximum de points de vie à l'attaquant."

L'attaquant est Onyxia dans ce cas précis et également la victime de https://woehead.way-of-elendil.fr/?spell=17731#used-by-object vu ça taille je suppose que elle subit les dégâts de plusieurs éruptions et regen donc l'équivalent de 3-4 hit voir plus (+2% par hit) 

10% (5 hit de éruption) sur 5M de pv elle regen 500K par exemple mais ça reste a confirmer que c'est bien de la que vient le soucis

**Comment by joshwhedon** [comment]
Ca expliquerait ca, je vais regarder. Mais normalement les erruptions sont pas supposees faire de degats a Onyxia, si ?

**Comment by Bleuphonix** [comment]
Ba étant sont propre sort par logique non

**Comment by Shotsx** [comment]
https://woehead.way-of-elendil.fr/?object=176513#.
Je sait pas d'après le site c'est un objet/monstre invisible au joueur qui lance le sort mais je connait pas le déclencheur ni même si il est considérer comme un allié de Onyxia , par exemple si tu fait ".learn 17731" (le sort de la crevasse) sur le serveur dev et que tu le lance a proximité d'un joueur de ta faction logiquement ça lui inflige pas de dégât mais si il est de la faction adverse il prend des dégâts.

Après sur le site quand on regarde la description de Onyxia https://woehead.way-of-elendil.fr/?npc=10184 elle est de la faction "Vol noir" et la crevasse de la faction "Monstre" peut-être que le problème est lié 

La crevasse est un simple item au sol invisible donc pas considérer comme un pnj donc si Onyxia est le déclencheur du sort de l'objet (crevasse) ça signifie que le sort est considérer comme lancer par le déclencheur mais la crevasse étant d'une faction opposer a Onyxia ça la tape 

AAAAA mon cerveau...

**Comment by Bleuphonix** [comment]
Bonsoir se Soir on a tenter avec 0 paladin soit pas de jugement de vie et elle a regen 0 ( ou alors tres minim que je n'ai rien vue ) comme j'ai pas vue le maj passez je préfère faire ce message et confirmée l’hypothèse que l'on avais exposer juste avant @joshwhedon
