### ISSUE TITLE
Zul Aman bug combat 

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1045]
**Description**
Je me permet de relancer comme tu n'arrivais pas à reproduire en essayant d'être plus précis.
En faisant l'évent du gong à l'entrée après que le pnj soit mort par les gardes, il faut tuer les deux mobs à l'entrée ainsi que les petits non-élite en bas des escalier juste après la porte. Après cela il sera impossible de sortir de combat à part en sortant du raid.

**Étapes de reproduction**
Zul Aman raid 10 joueurs TBC, de 1 à 10 joueurs faire l'évènement du gong et tuer les premiers mobs qui apparaissent à l'ouverture de la porte ainsi que ceux non-élite juste en bas des escaliers juste après les deux premiers élites.

**Comportement attendu**
Ne pas être en combat

**Comment by joshwhedon** [comment]
Corrige prochaine maj
