### ISSUE TITLE
Le sort Connexion des démonistes aux rangs inférieurs

### ISSUE THREAD

**Issue by Foncegrive** [way-of-elendil/3.3.5#1046]
**Description**
Le sort Connexion des démonistes aux rangs inférieurs ne rend pas la mana qu'il devrait indiquer. 

**Étapes de reproduction**
Un démoniste de niveau 80 avec le sorts connexion à tout ses rangs  et avec un minimum de puissance des sorts (3000 ne serait pas mal) 
**Comportement attendu**
La connexion devrait aux rangs plus bas rendre un montant de mana correspondant au tooltip et prenant en compte la puissance des sorts 

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?v=Wnltb2pZYCQ

**Comment by joshwhedon** [comment]
Donc, le fonctionnement de beaucoup de sorts est base sur le niveau du lanceur de sort. C'est le cas de connexion. Hors, pour les sorts de rang inferieur, leur efficacite est reduite lorsque le niveau maximum du sort est depasse (le bonus de niveau n'est pris en compte que jusqu'a ce niveau maximum). Pour connexion rang 1 par exemple, le niveau maximum est 16. Donc pour un demoniste de niveau 20 ou de niveau 16, Connexion donnera la meme quantite de mana. Ca a ete mis en place pour blizzard afin d'encourager les joueurs a utiliser les sorts de rang maximum, afin que les joueurs ne jonglent pas entre les rangs selon la situation (par exemple, pour eviter d'utiliser trop de mana). Les tooltips ne refletent par cette limite de niveau.
