### ISSUE TITLE
Arme runique dansante

### ISSUE THREAD

**Issue by Elahpascriptelaspeblood** [way-of-elendil/3.3.5#1047]
**Description**
Les dégats de l'arme runique sont extrêmement bas, je met des 18k crit à la frappe de mort et la DRW pose un 2k5, je pense que ya un soucis pare ce que avant ça mettait bien 50% de dmg infligé style : ~18k = ~9k drw et ça me parait plus légit que des frappes au coeur à 1k4 sur des 15k crit.
Je reviens aussi vers vous histoire de bien comprendre et de régler les anomalies dans la spé ou m^me sur le dk, les bonus T10 semble bien buggé aussi, je souligne que la frappe au coeur fait 10% de moins donc peut être que le 2 t10 est pas pris en compte? 
Enfin bref voilà je pense qu'on veut tous avoir des classes scriptées sur ce serveur ! 
**Étapes de reproduction**
- Classe : Chevalier de la mort
- Race : Orque
- Spécialisation : Sang
- 51/0/20
- Poteau de Achérus
- DRW + sort spéciaux type frappe au coeur/ frappe de mort /touché de glace / frappe de peste / voile mortel 

**Comportement attendu**
La DRW doit bien faire 50% de mes damages sur mes sort spéciaux. Genre si je crit elle doit crit ainsi de suite, c'est un burst c'est sensé apporté du dps pas le plomber, je comprend pas d'ailleur parce que lors de la merge ça avait était fixé et ajd ça ne l'est plus, pourquoi ?

**Captures d’écran / Vidéos**
Frappe au coeur : 
![image](https://user-images.githubusercontent.com/72766795/95791465-b5129180-0ce1-11eb-927b-3f85b6670a39.png)
![image](https://user-images.githubusercontent.com/72766795/95791540-e0957c00-0ce1-11eb-9d81-157c1e9b2578.png)
Frappe de mort : 
![image](https://user-images.githubusercontent.com/72766795/95791592-fefb7780-0ce1-11eb-931b-3fad0d0e7cd3.png)
![image](https://user-images.githubusercontent.com/72766795/95791618-0b7fd000-0ce2-11eb-80aa-e864b4691dd2.png)
Voile mortel : 
![image](https://user-images.githubusercontent.com/72766795/95791675-26524480-0ce2-11eb-8d04-c9da7ee10418.png)
![image](https://user-images.githubusercontent.com/72766795/95791694-310cd980-0ce2-11eb-9ab7-d1824972f2d6.png)

**Ressources additionnelles**
je n'ai pas de source offi mais littéralement elle doit faire 50% de mes dmg en faisant les même technique que moi c'est marqué sur le spell.

**Comment by Elahpascriptelaspeblood** [comment]
recount de la drw sur ony 25 avec opti cac présente
![image](https://user-images.githubusercontent.com/72766795/95795104-db3c2f80-0ce9-11eb-8402-621fe922a48c.png)

**Comment by Elahpascriptelaspeblood** [comment]
ca représente 2 drw sur le combat
la première sous hystérie plu full proc

**Comment by Justforsoloq** [comment]
Par contre Elah pour la drw c'est pas censé faire 50% de tes dégâts :
No, it makes attacks with exactly your stats and skills, but with a -50% modifier. Even says so in the tooltip: "Summons a second rune weapon that fights on its own for 12 sec, doing the same attacks as the Death Knight but for 50% reduced damage.", not 'does half of your damage'.  

Par exemple sur ce WoL : 
http://www.worldoflogs.com/reports/0abwf6ft1azn5ney/details/10/?s=5906&e=6158 (BDK)
http://www.worldoflogs.com/reports/0abwf6ft1azn5ney/details/73/?s=5906&e=6158 (DRW du BDK)
Pour les mélées on voit effectivement que c'est du 50% (normal), mais pour les techniques pas du tout.
Heart strike du dk normal/crit : 7880.7/19283.2
Heart strike de la drw normal/crit : 1053.1/2565.5

Death strike du dk normal/crit : 8954.2/23809.9
Death strike de la drw normal/crit : 1200/3113.7

**Comment by Elahpascriptelaspeblood** [comment]
ok mais je vois qu'elle crit bien et là le soucis c'est que ellle crit pas la drw et elle prend des dodge et des miss alors que je suis bien capé

je refait des screen un peu plus tard

**Comment by joshwhedon** [comment]
L'arme runique dansante prend un snapshot des stats du DK au moment ou elle est invoquee. Elle reproduit ensuite les attaques du DK, avec ses propres stats. Donc elle ne fera pas forcement les memes critiques que le dk, au meme moment que le dk. Elle peut tres bien ne faire aucun critique alors que le dk en aura fait.

**Comment by joshwhedon** [comment]
Quant a la frappe au coeur ca a deja ete verifie il y a un moment et elle fait les degats qu'elle doit faire.

**Comment by joshwhedon** [comment]
Soit dit en passant, avant le merge l'arme runique dansante ne marchait justement pas comme elle devrait, elle faisait la moitie des degats du DK, chose qui etait incorrect.

**Comment by Elahpascriptelaspeblood** [comment]
yep ok ça roule merci des réponses !

**Comment by Elahpascriptelaspeblood** [comment]
et pour la frappe au coeur je voulais juste avoir une confirmation que le 2part du set t10 augmente bien de 7% les dmg infligé par celle ci merci
le reste je pense qu'on a déjà fait le tour, j'aimerai juste savoir si ya moyen de corrigé le bug du proc 4 part t10?

**Comment by joshwhedon** [comment]
Le modificateur de degats pour la frappe au coeur est bien la. Pour le T10, normalement ca marche, y'a un bug de signale pour ?

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/51
