### ISSUE TITLE
Piège explosif / Piège à serpent

### ISSUE THREAD

**Issue by Renarza** [way-of-elendil/3.3.5#1048]
-Description-
Problème avec l'activation du Piège explosif Ainsi que Piège à serpent,, lorsqu'on pose les deux piège soit elle proc ,soit elle ne proc pas donc n’apparaît donc pas dans le recount ou soit elle disparaît littéralement du sol.  

-Étapes de reproduction

- Classe : Chasseur
- Spécialisation Précision / Survie
- https://woehead.way-of-elendil.fr/?spell=49067#modified-by / https://woehead.way-of-elendil.fr/?spell=34600
- Circonstances : PVE / PvP 

-Comportement attendu
Lorsqu'on pose les pièges elle doivent reste au sol et s'active à une distance pré-définis étant de 2m. ( à voir )

**Comment by joshwhedon** [comment]
Impossible a reproduire de mon cote, faites un ticket en jeu pour voir avec un mj.
