### ISSUE TITLE
Spell: Dark Reckoning

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#105]
**Description**
Le spell id: 69483 [Dark Reckoning]  est considéré comme buff et peut donc être dispel par un clique
https://woehead.way-of-elendil.fr/?spell=69483
C'est un bug qui affecte plusieurs spells, sur TC ils forcent 'attribue negative spell, mais je pense que c'est un hack, et choppé tout les cas similaire est impossible.

**Étapes de reproduction**

- Donjon ICC
- Niveau de difficulté: toute
- creature: https://woehead.way-of-elendil.fr/?npc=36829
- Sort en question https://woehead.way-of-elendil.fr/?spell=69483

**Comment by joshwhedon** [comment]
SPELL_AURA_PERIODIC_DUMMY ces auras on est oblige malheureusement, parce que y'a pas de moyen simple de savoir si c'est positif ou pas.
