### ISSUE TITLE
[Monture du cavalier sans tête] Taux de loot normal?

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1050]
Le taux de loot dans la citrouille est affiché à 0.1% sur la db woe ce qui me parait bas : https://woehead.way-of-elendil.fr/?item=37012#contained-in-item
Par exemple 0.4% affiché sur wowhead pour la version actuelle:
https://www.wowhead.com/item=37012/the-horsemans-reins#contained-in-item

Je ne trouve pas de données d'époque mais il me semble que ça devrai drop aux alentours de 0.4-0.5% 

D'autre part, la citrouille drop l'épée et le haume level 70 et le boss les même item mais au level 80 (+les anneaux), ce qui me parait étrange. Je ne sait pas si les item 70 sont censé être encore obtenables. 
https://woehead.way-of-elendil.fr/?search=The+Horseman%27s+Blade

**Comment by joshwhedon** [comment]
Le taux de loot a ete modifie hier mais woehead a pas encore et mis a jour.

**Comment by Endalaust** [comment]
Suite au passage des fix, woehead a été mis à jour
La liste est plus cohérente et pour info la monture est à 0.5%
