### ISSUE TITLE
[Quest] [Les Fils de Hodir] [Les pics Foudroyés] Le permagivre

### ISSUE THREAD

**Issue by Triscuiterie** [way-of-elendil/3.3.5#1052]
Le contenant [Morceau de permagivre](https://fr.wowhead.com/object=193997/morceau-de-permagivre) ne donne jamais l'objet [Morceau de permagivre](https://fr.wowhead.com/item=44725/morceau-de-permagivre), objet qui permet de démarrer la quête [Le permagivre](https://fr.wowhead.com/quest=13420/le-permagivre).

En étant honorée chez les Fils de Hodir, je devrais être en mesure d'obtenir l'objet (20 % de chances de l'obtenir), mais après près d'une trentaine de tentatives je ne récupère que la [Poudre de permagivre](https://fr.wowhead.com/item=44729/poudre-de-permagivre).

**Étapes de reproduction**
– Emplacement : Les pics Foudroyés (55,97 62,83) : le seul contenant Morceau de permagivre que j'ai trouvé jusqu'à présent. Il s'agit peut-être aussi d'un bug qui a été évoqué précédemment (https://github.com/way-of-elendil/3.3.5/issues/571).
– Fils de Hodir : Honoré

Le contenant Morceau de permagivre a 20 % de chances de donner l'objet Morceau de permagivre permettant de lancer la quête Le permagivre.

**Comment by joshwhedon** [comment]
Impossible de reproduire le probleme de mon cote. Merci de faire un ticket en jeu pour voir avec un mj. Soit il y a pas de soucis, soit c'est specifique a votre personnage.
