### ISSUE TITLE
[Mission de site] Missions qui ne marchent pas

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#1055]
- 5 : Vaincre Le prophète Tharon'ja
- 17 : Vaincre un boss de raid
- 24 : Monter de niveau au dela du niveau 1
- 25 : Monter de niveau au dela du niveau 10
- 32 : Participer a un Bassin d'Arathi
- 33 : Gagner un Bassin d'Arathi

Tous les boss de raid

N'a pas été testé : 

- 34 à 39 (arena)
- 28 à 29 (joug d'hiver)

**Comment by Gyllo** [comment]
40 : 5 Votes quotidiens ne fonctionnent pas depuis 2 jours

**Comment by Endalaust** [comment]
Suite à la maj reste buggé: 

- 5 : Vaincre Le prophète Tharon'ja
- 34 à 39 (arena)

**Comment by Endalaust** [comment]
Suite à la maj, la mission "Vaincre Le prophète Tharon'ja" a été remplacée par "Vaincre le roi Dred"
Les missions arena n'ont pas été testées mais devraient être fonctionnelles

**Comment by Wizzzz00** [comment]
Mission vote, ne fonctionne pas

**Comment by Endalaust** [comment]
Pas d'accord. Fait ce matin et parfaitement fonctionnel

**Comment by Wizzzz00** [comment]
Ah mince ça n'a pas fonctionné pour moi...

**Comment by Endalaust** [comment]
Il faut rafraichir la page oui :( 
Changer de page ne suffit pas

**Comment by Wizzzz00** [comment]
J'avais rafraîchi justement, bon bref ça marche ! C'est une super idée pour
fidéliser en tout cas !!

**Comment by Reveillark** [comment]
Bonjour, le mission "Vaincre Seigneur du Fléau Tyrannus" semble avoir un souci. Malgré un rafraîchissement de la page après 2-3 minutes après avoir tué le boss en HM, elle n'est pas validée.

**Comment by Endalaust** [comment]
Testé de mon côté, validée sans soucis 
Un cas peut exister : Si on met à jour le service en même temps que le down (rare mais possible), la comptabilisation sera KO (pour tout le monde durant la tranche de 120s que nous prend une maj de service)

**Comment by Mortekouye** [comment]
Bonjour , j'ai un soucis avec vaincre le dévoreur d'âmes boss de "la forge des âmes" . 
La mission ne s'est pas validé .

**Comment by Ertha92** [comment]
Bonsoir, la mission "vaincre le Héraut Volazj" ne s'est pas validé alors que je viens de le kill en donjon HM il y a + ou - 1h.

**Comment by Endalaust** [comment]
<img width="574" alt="screenshot_2670" src="https://user-images.githubusercontent.com/1420867/100550770-842ff100-327c-11eb-84ce-6e4e51a5705c.png">

**Comment by Ferro3** [comment]
Salut.
La quête raid LK x 3 fonctionne

La quête instance **Vaincre Roi Ymiron** ne fonctionne pas (faite ce jour 29/11 en héro)
La quête instance **Vaincre Dévoreur d'âmes** ne fonctionne pas (faite ce jour 29/11 en héro)

Bon courage
+

**Comment by joshwhedon** [comment]
Elles fonctionnent toutes, je sais pas comment vous faites pour les faire echouer. Prochaine fois voyez avec un mj pour qu'il note l'heure et la date exacte, et on pourra peut etre verifier.
