### ISSUE TITLE
Champions edc 5

### ISSUE THREAD

**Issue by FBuet** [way-of-elendil/3.3.5#1057]
Bonjour, 

Dans le donjon l'épreuve du champion, en mode héroïque ou normal, le combat monté comporte plusieurs bug.

Le premier est que le sort de "charge" n'enlève pas de couche de protection comme c'est marqué dans la définition du sort. Du moins les joueurs n'enlèvent pas de protection aux pnj, mais les pnj eux enlèvent bien la protection lorsqu'ils chargent un joueur.

Le second bug est le fait qu'une fois mort, les grand champions se déplacent librement pour reprendre une monture.
Normalement, lorsqu'un joueur passe dessus son cadavre, le grand champion piétiné est stun pendant 15 secondes avant de pouvoir rebouger, actuellement, sur le serveur, il peuvent bouger après 3 secondes.

Sources pour cette mécanique : https://fr.wowhead.com/trial-of-the-champion#english-comments

On peut voir : "Once one has been defeated they'll occasionally attempt to slowly walk towards a Warhorse and remount. You can prevent this by "running" over them on your mount. In turn the victim will be Trampled stunning them for 15 seconds"

Message posté le 15/07/2009 sous extension 3.1.3

Cordialement

**Comment by joshwhedon** [comment]
La charge enleve bien la protection des pnjs j'ai teste.
Le second bug sera corrige.
