### ISSUE TITLE
Quest=2681 The stones that bind us

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/3.3.5#1059]
**Description**
Certains cristaux ne peuvent être activés

**Étapes de reproduction**
damage un des mobs à proximité d'un cristal, puis utiliser le cristal quand un message apparait sur l'écran. Certains cristaux peuvent être activés, d'autres ne sont pas cliquables

**Comportement attendu**
Une fois le cristal activé, le npc n'est plus immune, le joueur peut alors lui faire des dégats

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?quest=2681

**Comment by joshwhedon** [comment]
Va me falloir plus d'info j'en ai teste quelques un et ils pouvaient tous etre actives.
