### ISSUE TITLE
Spell: Snake Trap

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1060]
**Description**
https://woehead.way-of-elendil.fr/?spell=34600

Si le joueur n'est pas en combat, les serpents ne vont pas attaquer la cible la plus proche à l'activation du piège, même si l'ennemi est en mouvement

"When the trap is activated, snakes start to attack the nearest targets."
https://wowwiki.fandom.com/wiki/Snake_Trap

**Comment by joshwhedon** [comment]
Corrige prochaine maj
