### ISSUE TITLE
Spell: Invocation d'un ami

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1062]
**Description**
L'invocation d'un ami peut se faire à travers continents

<img width="535" alt="Capture d’écran 2020-10-26 à 20 28 57" src="https://user-images.githubusercontent.com/60295792/97219772-c15f1a00-17ca-11eb-9c1e-f348617abc63.png">

https://woehead.way-of-elendil.fr/?spell=45927

(Avant, c'était restreint à la même "instance" à savoir Kalimdor/Royaume de l'est/Terres fantomes + Bois des chants éternels/Ile de brume azur + brume sang séparés)

**Comment by joshwhedon** [comment]
On y peut rien c'est une limitation technique de trinitycore.
