### ISSUE TITLE
Métier mineur minerais volant

### ISSUE THREAD

**Issue by HopeKellytm** [way-of-elendil/3.3.5#1063]
Il y a un minerai d'étain qui vole

- Métier / Mineur / Etain / Les Tarides

**Comportement attendu**
Un minerai au sol et non possédé par satan

**Captures d’écran / Vidéos**
https://prnt.sc/vb80x9
https://prnt.sc/vb815k

**Comment by Babyface-187** [comment]
Map : 1 
Zone : 17 
X: -1306.678955 Y: -1730.972778 Z: 101.693108

**Comment by joshwhedon** [comment]
Corrige prochaine maj
