### ISSUE TITLE
Druide : Esquives et parades sur techniques générant des points de combo

### ISSUE THREAD

**Issue by Belore** [way-of-elendil/3.3.5#1064]
**Description**
Lorsqu'un druide féral rate ou se fait esquiver/parer une technique générant des points de combo (CPG), l'intégralité de son coût en énergie est retirée.

**Étapes de reproduction**
Créer un druide féral sans expertise ni toucher, puis attaquer un poteau de face pour constater le coût en énergie des CPG ratés/esquivés/parés.

**Comportement attendu**
De la même façon que pour le ticket concernant les rogues, les seules techniques du druide féral qui devraient coûter l'intégralité de leur coût si ratées/parées/esquivées sont les coups de grâce sans le talent Précision primale.

**Captures d’écran / Vidéos**
Sur cette vidéo datant de 2010, à 2:14 (passer en vitesse x0.25), le druide se fait esquiver une Griffure (coût en énergie : 35) et perd très peu d'énergie. Le montant exact n'est pas visible, mais devrait être le même que pour les voleurs.
https://youtu.be/YIQ87kjVDUk?t=130

**Ressources additionnelles**
Ticket sur la mécanique de remboursement d'énergie concernant les rogues : https://github.com/way-of-elendil/3.3.5/issues/482
Patch de 2004 dans lequel la mécanique a été implantée au jeu : https://worldofwarcraft.judgehype.com/betawow-13avril2004/

(PS : Merci à vous pour la correction appliquée concernant les rogues !)

**Comment by joshwhedon** [comment]
C'est corrige auussi normalement.

**Comment by Belore** [comment]
J'ai testé sur poteau avant d'écrire le ticket, c'est effectivement corrigé sur voleurs mais pas sur druides, les techniques esquivées, parées et ratées coûtent toujours le prix total.

**Comment by Belore** [comment]
J'ai fait des tests un peu plus spécifiques, et effectivement le problème est résolu pour la plupart des techniques du druide, il n'y a que la technique Mutilation(félin) dont le coût n'est pas correctement remboursé en cas d'esquive/parade/raté.
