### ISSUE TITLE
NPC: Barnes - changer Event

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1066]
**Description**
Name: Barnes
Les Gossip proposés aux personnages MJs pour changer le type de l'event pour Roméo et Juliete et le Magicien d'Oz sont inversés

Actuellement cliquer sur :
EVENT_OZ _donne_ Roméo et Juliette **(pas OK)**
EVENT_HOOD _donne_ le petit chaperon rouge (OK)
EVENT_RAJ _donne_ le Magicien d'Oz **(pas OK)**

**Comment by joshwhedon** [comment]
Corrige prochaine maj. C'est pas vraiment inverse, ils marchent juste pas correctement.
