### ISSUE TITLE
Boss: Opera Event - Magicien d'Oz

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1067]
**Description**

Event Magicien d'Oz

17543 - [Homme de paille] 
17546 - [Graou] 
17547 - [Tête de fer-blanc] 

Les NPCs ne despawn pas s'il y a eu wipe lorsqu'ils étaient encore inattaquable

**Comment by joshwhedon** [comment]
Corrige prochaine maj
