### ISSUE TITLE
[Monture] Animation de la Monture du cavalier sans tête (bug mineur)

### ISSUE THREAD

**Issue by Belore** [way-of-elendil/3.3.5#1068]
**Description**
La monture du cavalier sans tête (https://woehead.way-of-elendil.fr/?spell=48025) a une animation beaucoup trop rapide lorsqu'elle est utilisée en vol. La version volante est animée comme la version terrestre qui irait à 280%.

**Étapes de reproduction**
- Utiliser la monture dans une région volante avec la compétence 280%

**Comportement attendu**
La vitesse d'animation en vol à 150% et 280% devrait être la même que pour la version terrestre à 60%.

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?v=romuOBmDZUI

**Comment by joshwhedon** [comment]
On y peut rien c'est cote client. Ou alors c'est a cause du patch hd si vous l'utilisez.

**Comment by Belore** [comment]
Mince, OK ! Je n'utilise pas le patch HD. Merci d'y avoir prêté attention !
