### ISSUE TITLE
Quest: Spécialisation Ingénierie Gnomes après changefaction

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1069]
**Description**
Un joueur a changefaction Alliance => Horde après avoir rendu 3632 - [Ingénierie des gnomes] 

Il devrait pouvoir avoir accès à https://woehead.way-of-elendil.fr/?quest=3642

Je pense qu'il faut juste changé les prérequis plutot que de convertir les quêtes ? 
C'est ok dans l'autre sens
Ça également l'air ok pour les gobelins https://woehead.way-of-elendil.fr/?quest=3638

**Comment by joshwhedon** [comment]
Non, changer les prerequis foutra plus la merde qu'autre chose. J'ai ajoute une conversion prochaine mise a jour pour les futures personnages.
