### ISSUE TITLE
Gob: Pêche Marécage de Zangar

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1072]
**Description**
https://woehead.way-of-elendil.fr/?object=182952
https://woehead.way-of-elendil.fr/?object=182953
https://woehead.way-of-elendil.fr/?object=182954

Beaucoup de ces gobs se chevauchent sur toute la map du Marécage de Zangar

.go gameobject  64712

**Comment by joshwhedon** [comment]
C'est les pools qui sont mal faites. Beaucoup trop de travail de corriger ces spawns.
