### ISSUE TITLE
Enchantement armes switch

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1073]
- DESCRIPTION :

Les Enchantement de doivent pas disparaitre quand on change d'armes losqu'ils ont le meme Enchantement !

- ÉTAPES DE REPRODUCTION  :

Prendre deux armes 2 mains pour simplifier,
Mettre le meme Enchantement sur les deux armes !
Attendre le proc de l'Enchantement puis échnager avec la deuxième armes enchnaté du meme Enchantement = le proc disparaît..

- COMPORTEMENT ATTENDU :

Lorsque l'on switch d'armes enchanté du meme Enchantement le proc reste et ne fade pas.

- CAPTURES D'ÉCRAN / VIDÉO :

https://www.youtube.com/watch?v=MgmooQsclrs

Proc berserk sur la 2mains et la 1main
Switch d'armes à 1m50 et 2m50 flagrant le proc ne disparaît pas.

Merci la bise

**Comment by joshwhedon** [comment]
Corrige prochaine maj.

**Comment by Satarians** [comment]
Merci bcp ca marche mtnt que l'on switch d'arme seulement, maintenant on peut Faire un proc d'un enchant switch d'armes avec un autre enchant, ne pas pedre le 1er enchant et faire proc le deuxieme, du coup avoir un proc berserk + bourreu actif en meme temps :)
![WoWScrnShot_120720_134316](https://user-images.githubusercontent.com/63306263/101352416-66711600-3892-11eb-8a1a-7cc1a16fd3fd.jpg)
![WoWScrnShot_120720_134318](https://user-images.githubusercontent.com/63306263/101352420-6709ac80-3892-11eb-9cdb-fb45ceeb66ad.jpg)

**Comment by Satarians** [comment]
Alors 
![WoWScrnShot_120720_134316](https://user-images.githubusercontent.com/63306263/101353168-789f8400-3893-11eb-8bfd-541e2ce49670.jpg)
![WoWScrnShot_120720_135130](https://user-images.githubusercontent.com/63306263/101353237-8bb25400-3893-11eb-9206-c27b0acadd67.jpg)

**Comment by Satarians** [comment]
![WoWScrnShot_120720_135129](https://user-images.githubusercontent.com/63306263/101353270-979e1600-3893-11eb-812f-33ab9bbfe5d8.jpg)
![WoWScrnShot_120720_134318](https://user-images.githubusercontent.com/63306263/101353284-9a990680-3893-11eb-9452-8a55dd9632dc.jpg)
Changez d'arme avec le meme enchant devrais refresh le buff plutot que de double stack
Changez avec un autre enchant ne devrais pas cumulez les deux, on va voir des pull à 60k en pve bientot

**Comment by joshwhedon** [comment]
Un correctif sera mis prochaine maj.

**Comment by gtschanz** [comment]
je suis pas aussi catégorique que toi sata sur le ''Changez avec un autre enchant ne devrais pas cumulez les deux, on va voir des pull à 60k en pve bientot'' il y avait une mécanique sur offi si je me rappel de l'époque ou justement les gens mettait une magie noir sur une arme pour le faire proc et reswitchais direct sur une arme avec un berserk derrière

**Comment by Justforsoloq** [comment]
Sauf qu'en faisant ça gtschanz tu trigger l'ICD de l'enchant (mis en place par Blizzar durant BC si je me souviens). Donc t'attends 45s (l'icd de berserk ?) avant que ton zerk proc.

**Comment by Satarians** [comment]
Toujours bug
