### ISSUE TITLE
quest=10588 : The Cipher of Damnation

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/3.3.5#1074]
**Description**
Cyrukh the Firelord ne peut pas être attaqué

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : The Altar of Damnation, Shadowmoon Valley
- Nom du donneur de quête : Earthmender Torlok

**Comportement attendu**
Après le cast de l'item "The Cipher of Damnation" Cyrukh apparait et le joueur peut l'attaquer

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?quest=10588

**Comment by Shotsx** [comment]
Enfaîte si il peut être attaquer après environ 5 minute il commence a bouger vers la droite quand tu est face a lui et s'attaque au pnj qui sont monter sur la colline de souvenir , j'ai fait la quête il y a quelque semaine c'est pas le boss qui bug juste l'event qui prend beaucoup plus de temps que la normale a être lancer

**Comment by Ischjgt** [comment]
Il faut parler au PNJ
