### ISSUE TITLE
Transmo: Ranged

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1075]
**Description**

On peut transmo les arcs/arbalètes/armes à feu

(Ce sont 2 compétences différentes, et la transmo est possible même quand la compétence est en rouge)

**Comment by Shotsx** [comment]
C'est pas un bug c'est présent sur tout les serveurs TLK donc c'est sans doute volontaire de blizzard

**Comment by gtschanz** [comment]
Alors en soit shotsx ça m'étonnerait que ça existe sur les serveurs TLK CAR la transmog N'EXISTAIT PAS sur tlk.

Cependant..

Le fait de pouvoir transmog des arcs en arbalètes ou en armes à feu EXISTE sur Offi et vu que le serveur d'ici à copier le système transmog d'offi des extensions suivantes donc le fait de transmog des arcs en arba ou en arme à feu est blizzlike vu que le modèle transmog d'offi à été repris.

Je tiens tout de suite à apporter une seconde éclairci, le système des transmog est très populaire sur WOE, donc si on suit la logique si on voudrait retirer le système transmog arcs en arba ou en armes à feu il faudrait pour être blizzlike, il faudrait  également retirer la transmog dans tout son ensemble; Ce que je pense sera TOTALEMENT contre-productif !

De plus je ne connais pas un chasseur qui n'a pas transmog son arbalète (souvent ils ont ça car à ICC tu loot que des arba) en arc ou arme à feu; REVENIR sur cette mesure serait totalement IMPOPULAIRE auprès de la communauté WOE et se distinguerais du blizz d'offi ou cela est POSSIBLE. Si le Staff d'élendil abonde dans ce sens, je serais le premier à râler et à venir signaler l'incohérence et ce, de manière journalière! Et je pense ne pas être le seul joueur qui irait faire ça.

Résultat si cette modification à lieu cela changera 2 chose; de 1 le temps que vous allez perdre à corriger ça et de 2 l'immense impopularité de cette mesure, car c'est un changement qui est apprécié de la communauté !
