### ISSUE TITLE
Spell: Asphyxie - Puissance absorbée

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1076]
**Description**
71665 fait proc 
71605 - [Puissance absorbée, rank 1 frFR] 
71636 - [Puissance absorbée, rank 1 frFR]

50360 - [Phylactère de la liche sans nom] 
50365 - [Phylactère de la liche sans nom]

**Comment by joshwhedon** [comment]
Devrait etre corrige prochaine mise a jour.
