### ISSUE TITLE
Piège dans Le Repaire de l'Aile Noire

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#1077]
**Description**
Les pièges qui ce situe avant le boss Seigneur des couvées Lanistaire ( https://woehead.way-of-elendil.fr/?npc=12017 ) ne sont pas désactivable avec un voleur. Lorsque l'on essaye, ils s'activent, reste actif, et ne sont plus ciblable.

**Comment by joshwhedon** [comment]
Corrige prochaine mise a jour.
