### ISSUE TITLE
Grille non script après la mort du boss Seigneur des couvées Lanistaire

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#1078]
Dans la salle en 3 étages où ce trouve le boss Seigneur des couvées Lanistaire ( https://woehead.way-of-elendil.fr/?npc=12017 ), ce situe une grille entre le 2eme et le 1er étage, qui devrait s'ouvrir une fois le boss mort pour revenir plus facilement à la suite du raid en cas d'aller retour.

**Comment by joshwhedon** [comment]
J'ai regarde, Blizzard vous a trolle . C'est pas une vrai grille, elle fait partie de la map (meme en GM il y a aucun moyen de la cibler / ouvrir).  Juste pour confirmer on parle bien de la grille juste a gauche apres le boss ?
