### ISSUE TITLE
Quest: L’équilibre de la Lumière et de l’Ombre

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1079]
**Description**
7622 - [L’équilibre de la Lumière et de l’Ombre]
Aucun mort (ou 1-2), l'event s'arrête à la 4ème vague et après les 3 spawns de Fantassins du fléau
La quête n'est pas marquée en échec (elle l'est quand les 15 villageois meurent)

https://github.com/way-of-elendil/3.3.5/issues/22

**Comment by Kaasss-woe** [comment]
Un correctif a été apporté
