### ISSUE TITLE
Boss: Profanation en phase 2

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#108]
**Description**
Durant la phase des Val'kyr on a eu 0 profa, pas sure si c'est lié au nombre des joueurs (2) ou pas.
En phase 3 y'en a eu correctement.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs)
- Boss LK
- Sort en question: Profanation

**Comment by joshwhedon** [comment]
Non, c'est lie au nombre de joueurs. Il faut etre minimum 3. C'est aussi le cas actuellement sur le serveur (ca a deja ete signale). En gros en phase 2 il peut pas cibler les gens cibles par certains autres sorts (dont les valkyr).

**Comment by Killyana** [comment]
Ceci explique les profas manquantes durant la phase des val'kyrs, je parle pas des tests qu'on a fait mais ce que les joueurs ont rapporté depuis toujours, serait il possible d'exclure des cibles possibles que les joueurs qui sont dans une val'kyr.

**Comment by joshwhedon** [comment]
C'est le cas deja
return unit->GetTypeId() == TYPEID_PLAYER && !unit->HasAura(SPELL_VALKYR_TARGET_SEARCH) && !unit->HasAura(SPELL_HARVEST_SOUL_VALKYR) && !unit->HasAura(SPELL_HARVESTED_SOUL) && _me->GetDistance2d(unit) < 80.0f;

**Comment by Endalaust** [comment]
Pareil en prod dans un raid 25, pas de profa en p2.

**Comment by joshwhedon** [comment]
A reouvrir si ce changement cause des problemes.

**Comment by klemmm** [comment]
Bonjour, a priori le bug existe toujours au soir du 7/04/2020 (23h00). Il y a aucune profa pendant la phase 2 (celle avec les valkyrs), en 10NM. 

Ceci a l'air reproductible: même comportement sur les 3 trys que nous avons fait.

En phase 3 (la phase avec les esprits), par contre il y a bien les profas.
