### ISSUE TITLE
NPC: Gardien/Tréant Crochebois

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1080]
**Description**
11462 - [Tréant Crochebois] 
11461 - [Gardien Crochebois] 

C'est toujours une formation de 3 Tréants qui patrouille à l'entrée de Hache-Tripes Est (il y a plusieurs groupes)

**Comportement attendu**
2 gardiens 1 tréant

**Captures d’écran / Vidéos**
0:53
https://www.youtube.com/watch?v=a3IYssAyBIQ
Bon c'est classic, dit moi si tu veux autre chose

**Comment by joshwhedon** [comment]
Fixe prochaine maj
