### ISSUE TITLE
NPC: Earthbinder Galandria Nightbreeze

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1081]
**Description**
Earthbinder Galandria Nightbreeze 19294.
Lured Colossus 20599.
Thiah Redmane 16991.

Earthbinder Galandria Nightbreeze bloquée

**Étapes de reproduction**

- .q a 10349
- .go c id 19294, rendre la quête
- l'event se lance, laisser la lieuse mourir
- (sortir du combat)
=> le colosse va ensuite aller tuer Thiah Redmane à coté
- **attendre que le Colosse despawn (c'est la condition clé)**
- .q rem 10349, .q a 10349
=> le colosse va directement aller sur Thiah Redmane pendant que la lieuse parle
- prendre l'aggro sans que le Colosse ait prit l'aggro de la lieuse
- tuer le colosse soit hors champ (derrière la colline sur lequel se tient la lieuse normalement) soit super loin (j'ai reussi à reproduire en faisant les 2, donc je sais pas lequel c'est :p)
=> NPC bloqué

**Comment by joshwhedon** [comment]
Je pense pas que les premieres etapes soient requises a causer le probleme.  Fixe prochaine maj.

**Comment by Ischjgt** [comment]
Il arrive encore que le NPC soit bloqué mais je saurais pas dire comment pour le moment.
