### ISSUE TITLE
Dame Vashj raid caverne du sanctuaire du serpent

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1082]
Le boss à une phase ou il faut désactiver les noyaux pour le tapper après 70 % hors certaines classe arrive à le tapper et à le descendre malgré ses shields ''insensible''
=> corruption / immolation démo
=> mage arcane
=> chasseur qui pose marque du chasseur
=> surement d'autres (en dk bien insensible)

résultat le boss à été tuer mais vu qu'il est pas supposé être tué ainsi cela le fait ''bug'' résultat les loot sont inaccessible (ce qui parait normal vu que insensible en p2) néanmoins il faudrait corriger ce boss avec les spells qui passent malgré les shields d'insensibiliter pour le down de manière légit

**Comment by joshwhedon** [comment]
Corrige prochaine maj
