### ISSUE TITLE
HF La bière de l'année

### ISSUE THREAD

**Issue by Myster79** [way-of-elendil/3.3.5#1086]
**Description**
Pendant l'évènement de la fête des brasseurs, je me suis abonné à "La bière du mois" et eu le HF le 24/09/20. Et donc en octobre, novembre et décembre, j'aurai dû recevoir une bière le 1er du mois pour le HF "La bière de l'année" Mais je ne reçois rien du tout

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Evénement la fête des brasseurs HF "La bière de l'année"
- Horde / Elfe de sang/ Paladin

**Comportement attendu**
Je devrait recevoir chaque début de mois une bière suite à mon abonnement à la bière du mois le 24/09/20 mais je ne reçois rien

**Captures d’écran / Vidéos**

**Ressources additionnelles**
La bière de l'année avec les commentaires français : https://fr.wowhead.com/achievement=1183/la-bi%C3%A8re-de-lann%C3%A9e#comments
La vendeuse de bière à orgri, n'existe pas dans l'extension woltk

**Comment by Endalaust** [comment]
Le vendeur existe bel et bien : https://woehead.way-of-elendil.fr/?npc=27806 (possible de cliquer sur Ogrimmar pour avoir sa position à Orgri)

Ca remplace pas un beau courrier tout beau, mais ca a le mérite d'exister pour compléter le HF

**Comment by joshwhedon** [comment]
Trop complique a implementer, a deja ete tente il y a quelques annees sans succes.
