### ISSUE TITLE
Item: Charge d'hydroglycérine massive

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1088]
**Description**
https://woehead.way-of-elendil.fr/?item=39213

L'item n'a pas l'air de faire des dégats aux portes dans le Rivage des anciens.
Les HFs sont comptés, la bombe est bien posée quand activée et il est possible de la désamorcer

**Comment by joshwhedon** [comment]
Corrige prochaine maj.
