### ISSUE TITLE
bug lucioles farouche

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1089]
![BUG LUCIOLE](https://user-images.githubusercontent.com/63243193/100966085-625c9580-352c-11eb-94bb-2488a5e7c46a.PNG)
![bugluciole2](https://user-images.githubusercontent.com/63243193/100966091-62f52c00-352c-11eb-8b75-fc3b24167351.PNG)

Quand on est en forme d'ours et qu'il n'y a pas de lucioles de druid équi on arrive à poser la notre en druid ours ET ELLE FAIT des dégâts (voir description du sort). Or si on pose une en premier avec un druid équi et qu'on essaye ensuite d'en poser une avec le druid ours on ne peut pas sous prétexte qu'une plus puissante est active. En soit je suis d'accord qu'on n'écrase pas le buff du druid équi car il apporte les 3% toucher en plus avec sa lucioles (cf spé du druid équi) MAIS les dégâts doivent se déclencher comme c'est mentionné dans le descriptif de sort ! Je ne sais plus si cela concerne également la forme de féral (chat) mais ça affecte à coup sûr la forme d'ours !

**Comment by gtschanz** [comment]
et en plus ce sort doit génerer de l'aggro de part les dégâts si on est en forme d'ours

**Comment by joshwhedon** [comment]
Deja signale https://github.com/way-of-elendil/3.3.5/issues/913
