### ISSUE TITLE
Problème quete voie du forgeron d'armes [Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by korhill1981** [way-of-elendil/3.3.5#109]
**Description**
Malgré la forge en qualité des armes demandées, impossible de rendre la quête.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Forgefer
- Alliance / Nain/ Paladin
- La voie du forgeron d'armes
- Ferronus Acier Froid

**Comportement attendu**
Rendre la quête est impossible malgré les objectifs remplis (forge de plusieurs éléments)

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Killyana** [comment]
Places les items  dans la banque et reprends les ou abandonnes et reprends la quêtes
