### ISSUE TITLE
NPC: Thrall - Contreforts de Hautebrande d'antan

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1090]
**Description**
Name: Thrall Entry: 17876.

Cas où le NPC ne fait plus aucune interaction

**Étapes de reproduction**
- 1 joueur, faire les étapes nécessaires pour spawn le premier boss et le vaincre
- Aller voir Thrall dans sa cellule, le libérer
- **Lui parler et lancer l'event en étant déjà en combat**
=> NPC bloqué

**Comment by joshwhedon** [comment]
Fixe prochaine maj. Le npc ne pourra pas lancer son event pendant un combat.
