### ISSUE TITLE
[Divers] Impossible de ressusciter un joueur dans un donjon/raid si le joueur mort a libéré son âme

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#1091]
**Description**
Impossible de ressusciter un joueur dans un donjon/raid si le joueur mort a libéré son âme

**Étapes de reproduction**
- Joueur 1 et joueur 2 dans un raid
- Joueur 2 meurt
- Joueur 2 libère son âme
- Joueur 1 incante un sort de résurrection sur son cadavre dans le raid
- Joueur 2 ne reçoit pas la proposition de revenir à la vie

**Comportement attendu**
Joueur 2 devrait pouvoir revenir à la vie

Ce comportement est "nouveau", peut être depuis le merge
Il est spécifique à une zone instanciée, en open world le comportement est correct

**Comment by joshwhedon** [comment]
Corrige prochaine mise a jour.
