### ISSUE TITLE
Crash jeu quête Récupérer la cargaison

### ISSUE THREAD

**Issue by Lakira16** [way-of-elendil/3.3.5#1092]
**Description**
Dans le marécage d'Aprefange, pour la quête Récupérer la cargaison.
Quand on se retrouve à côté des morceaux d'épaves et qu'on clique sur la Trousse de récupération pour récupérer les morceaux d'épaves, à la fin du chargement, le jeu crashe et affiche des messages d'erreur.
On doit redémarrer le jeu complètement et comme il y a des ennemis autour on se reconnecte en étant mort.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Rivage de Troubleffroi dans le Marécage d'Aprefange.
- Alliance /Elfe de la nuit/ Druide
- Récupérer la cargaison
- Donneur de quête: Renn McBranchie

**Comportement attendu**
On devrait pouvoir récupérer les objets normalement, sans crashe du jeu.

**Captures d’écran / Vidéos**

![Capture d’écran 2020-12-04 141020](https://user-images.githubusercontent.com/75484016/101167708-a3db6680-363a-11eb-8b98-066897943e79.png)
![Sans titre](https://user-images.githubusercontent.com/75484016/101167710-a473fd00-363a-11eb-81d9-aa50c1d7380d.png)

**Comment by Endalaust** [comment]
Un bug lié au patch HD
Ramasser un objet en forma aquatique fait crash le jeu

Solutions : 

- Enlever la forme aquatique pour ramasser
- Enlever le patch HD

Fait écho à la F.A.Q : https://way-of-elendil.fr/game/faq
