### ISSUE TITLE
Tour de force Thori'dal

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1094]
Bonjour,
J'ai obtenu l'arc légendaire Thori'dal, mais pas le tour de force associé sur le personnage Arkannor
![WoWScrnShot_120520_023837](https://user-images.githubusercontent.com/73133549/101233176-0a05cf00-36b7-11eb-90e6-3a8b5a476c86.jpg)
C'est possible d'ajouter le tour de force?
Merci

**Comment by joshwhedon** [comment]
Impossible de reproduire le probleme, probablement pas un bug. Merci de faire un ticket en jeu pour qu'un gm regarde votre probleme.
