### ISSUE TITLE
Bug Peste nécrotique du Roi Liche

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#1095]
Actuellement :
- Peste nécrotique est lancée initialement par le Roi Liche avec 2 stacks
- Peste nécrotique disparaît et ne saute pas sur la cible la plus proche si elle est dispell avec une seule stack

Comportement attendu : 
- Peste nécrotique est lancée initialement par le Roi Liche avec 1 stack
- Peste nécrotique ne disparaît et saute sur la cible la plus proche si elle est dispell avec une seule stack. La peste perd bien une stack de manière général quand elle est dispell, mais quand il n'y a qu'une stack, elle reste à 1.

Source : 
https://youtu.be/vGF1VQ-R1Hc?t=126 à 2:08 : Notre ami nous dit que si on dispell dans les joueurs, "it will last for ever" donc la peste ne disparaît pas à 1 stack !
https://youtu.be/8ybTns292Qk?t=43 à 0:45 : Le joueur subit Peste nécrotique du Lk et il n'y a qu'une stack

**Comment by Ischjgt** [comment]
```
Actuellement :

    Peste nécrotique est lancée initialement par le Roi Liche avec 2 stacks
```
Non.

`Peste nécrotique disparaît et ne saute pas sur la cible la plus proche si elle est dispell avec une seule stack`

Non.

**Comment by gtschanz** [comment]
je suis d'accord avec toitit; ça doit faire longtemps que tu n'as plus fais de lk sur le serveur ischjgt car ce qu'il a décrit est le comportement normal sur way of elendil (pour l'avoir encore fait y'a 3 jours)

**Comment by Ischjgt** [comment]
Je suis allé voir avant de répondre.
Chez moi, la peste est apparue à 1 stack.
Je l'ai dispell et elle a sauté vers quelqu'un d'autre.

Va falloir décrire ça un peu mieux.

**Comment by toitit** [comment]
@Ischjgt Tu es sûr qu'elle avait bien 1 seule stack ? Actuellement comme il y a 2 stacks au début, le premier dispell permet bien à la peste de sauter, et elle disparaît au dispell d'après, ce qui nous permet de tuer le boss en allant directement dispell sur un add.
C'est certain que ça marche comme ça en 25h (je pense aussi pour les autres modes, mais ça fait trop longtemps que j'y suis pas allé)
Prochaine fois que je vais en raid je te fais un screen de la peste qui pop à 2 stacks.

**Comment by Ischjgt** [comment]
Je viens de RE test en 10N et 25H, ça le fait pas chez moi.
