### ISSUE TITLE
Skill: Ranged et mannequin d'entrainement

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1096]
**Description**
Il est possible de monter de compétences avec les armes à distances en tapant sur des mannequins d'entrainement.

Testé avec Arc et baguette sur mannequin 80

**Comment by joshwhedon** [comment]
Je vois difficilement pourquoi ce serait different entre arme de melee et armes a distance.

**Comment by joshwhedon** [comment]
Corrige prochaine maj
