### ISSUE TITLE
Bug d'id 

### ISSUE THREAD

**Issue by achcyk** [way-of-elendil/3.3.5#1097]
Description:
-lorsque on récupère une id ou on rentre avec un personnage non inscrit à une ID icc ou halion, au lieu d'afficher le nombre des boss tuer sur l'id, ça affiche 0/0. ce qui donne que sur le site ça nous affiche 0/12 aussi.
-Sur le screen j'ai pris une id qu'on a clean 12/12 sur un autre personnage.
![WoWScrnShot_120820_095305](https://user-images.githubusercontent.com/66109317/101461503-46e1f800-393b-11eb-9efc-df7648ee7b80.jpg)

**Comment by joshwhedon** [comment]
Je peux pas corriger parce que je peux pas reproduire chez mois desole. Essaye plusieurs fois sans succes. Je ne doute pas qu'il y ait un bug, mais je ne peux pas le reproduire.
