### ISSUE TITLE
Boss: Glace-hurlante - Décalage stun-charge

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1098]
**Description**
34797 - [Glace-hurlante] 
(testé à poil sans talent)
Toutes difficultés

Le joueur dispose d'~ une seconde supplémentaire pour éviter la charge 
Il y a un léger décalage entre la fin du stun et le saut vers un bord qui précède la charge

6:50 https://www.youtube.com/watch?v=xHL_T-PYH3Y On voit le joueur sortir de son stun **en même temps** que le yéti saute pour se mettre contre le mur et faire sa charge

**Comment by joshwhedon** [comment]
Corrige prochaine maj
