### ISSUE TITLE
Boss: Glace-Hurlante - Vitesse

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1099]
**Description**
34797 - [Glace-hurlante] 
10nm et 25Nm,
Le buff de vitesse n'apparait pas sur les joueurs à la fin du stun

https://woehead.way-of-elendil.fr/?spell=68667

**Comment by joshwhedon** [comment]
C'est que en heroique. Tu as une preuve que c'est suppose arriver en normal ?

**Comment by Ischjgt** [comment]
ça n'arrive pas en normal

**Comment by joshwhedon** [comment]
J'ai compris ca, mais le script specifiquement donne le buff en heroique uniquement. Est-ce que tu as une source qui indique que ca doit arriver en normal ?

**Comment by Ischjgt** [comment]
6:50 NM https://www.youtube.com/watch?v=LRA97x3nK90&t=410s buff
6:50 HM https://www.youtube.com/watch?v=po9k71NjnE4 pas de buff

**Comment by joshwhedon** [comment]
Merci donc c'est inverse. Corrige prochaine maj

**Comment by Ischjgt** [comment]
Je viens de regarder, le buff n'est pas présent en 10HM et 25HM actuellement non plus :p
