### ISSUE TITLE
 Interaction entre Disarm Rogue et Wall/Shield Mastery 

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1100]
Description
Lorsque j'ai vu vos changelog et que j'ai lu "Remove shield dependant auras when nothing is present in off-hand.", j'ai immédiatement su qu'il y aurait cette régression et après test c'est bien le cas.
Le Dismantle du Rogue est le seul disarm qui vire les 2 mains, cependant le Wall et Shield Mastery (et même le Spell Reflect) ne doivent pas disparaître lorsqu'on est disarm (même des 2 mains). Ils ne peuvent pas être lancés une fois disarm par contre.

Étapes de reproduction

    Prenez un Guerrier
    Lancez un duel contre un Voleur
    Le Guerrier lance Mur Protecteur/Maîtrise du blocage/Renvoi de sort
    Le Voleur, se mettant dans son dos pour éviter un dodge/parade/block, lance Démantèlement
    Regardez les buffs du Guerrier

Comportement attendu
Le Guerrier est bien disarm mais les buffs Mur Protecteur/Maîtrise du blocage/Renvoi de sort restent.

**Comment by joshwhedon** [comment]
Honnetement, je trouve aucune source qui indique que le guerrier devrait garder son buff. Si tu es desarme, tu perds les avantages de ton equipement. Pour Shield wall / Shield Mastery, il faut avoir un bouclier d'equipe (outre la situation avec le port de deux armes, qui est un bug blizzlike). Hors, quand tu es desarme, tu n'as rien d'equipe, donc ... tu perds ton Shield Wall / Shield Mastery.
CQFD.
Je reouvrirai ce ticket et je le corrigerai si tu peux me prouver que se faire desarmer avec un buff qui requiert un bouclier, ca ne retire pas ce buff.

**Comment by Justforsoloq** [comment]
https://www.mmo-champion.com/threads/698163-Dismantling-during-shield-wall

**Comment by Justforsoloq** [comment]
En gros si le war unequip de lui même son shield il perd le buff (sauf si il est fury comme vu par un précédent BT via le "bug" titan grip présent sur offi). Mais si il est disarm par un rogue le buff 60% dmg n'est pas cancel, il ne peut juste pas utiliser de skill.

**Comment by joshwhedon** [comment]
Merci
