### ISSUE TITLE
Quest = 1957 : Mana Surges (quête mage)

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/3.3.5#1101]
**Description**
Le pnj Tabetha (https://woehead.way-of-elendil.fr/?npc=6546) ne sort pas de sa maison pour débuter la quête. À la place elle fait pop 3 éruption de mana (https://woehead.way-of-elendil.fr/?npc=6550), puis plus rien

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Tabetha's Farm / Dustwallow Marsh
- Alliance / Gnome / mage
- Mana Surges
- Tabetha

**Comportement attendu**
Une fois la quête prise auprès de Tabetha (https://woehead.way-of-elendil.fr/?npc=6546), elle sort de sa maison, elle incante un sort, puis retourne à son point de spawn. Le sort Création d'une faille (https://woehead.way-of-elendil.fr/?spell=9079) va faire pop des pnj éruption de mana (https://woehead.way-of-elendil.fr/?npc=6550), le joueur a alors 10 minutes pour en tuer 12.

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?quest=1957
https://www.youtube.com/watch?v=EH19pe3l3lM

**Comment by Babyface-187** [comment]
La quête est néanmoins réalisable

**Comment by Babyface-187** [comment]
edit : Tabetha n'incante plus https://woehead.way-of-elendil.fr/?spell=9079

**Comment by joshwhedon** [comment]
Corrige prochaine maj
