### ISSUE TITLE
Boss: Kalecgos - TP royaume spectral

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1102]
**Description**
https://woehead.way-of-elendil.fr/?npc=24850

Les TPs amènent le joueur dans le sol et il arrive qu'il y ait undermap
Constaté dans le sens Royaume spectral => Réalité

<img width="1207" alt="Capture d’écran 2020-12-12 à 02 07 25" src="https://user-images.githubusercontent.com/60295792/101968424-66b93a80-3c1f-11eb-98d8-1e27797d2695.png">

**Comment by joshwhedon** [comment]
Corrige prochaine maj
