### ISSUE TITLE
Boss: Kalecgos - Loot

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1103]
**Description**
https://woehead.way-of-elendil.fr/?npc=24892 Sathrovarr
https://woehead.way-of-elendil.fr/?npc=24850 Kalecgos

À la fin du fight, le cadavre de Sathrovarr est TP sur la position de Kalecgos, permettant aux joueurs de pouvoir loot

https://www.youtube.com/watch?v=K9mfONlbrTg 9:10

**Comment by joshwhedon** [comment]
Corrige prochaine maj
