### ISSUE TITLE
https://woehead.way-of-elendil.fr/?achievement=1685

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1107]
Soucis dans ce haut fait au niveau du https://woehead.way-of-elendil.fr/?npc=31261
L'un des hauts faits du voile d'hiver
Ce pnj se trouve à la couronne de glace, sur le marteau d'orgrim (Bateau volant de la horde).
Il est impossible de lui tirer du gui (Item : 21519) 
Lorsque l'on clique sur le gui et qu'on essaie de le mettre sur le npc, la souris reste en surbrillance mais ne pose pas le gui dessus.
J'ai testé de faire pop le pnj hors du bateau et la pose de gui fonctionne bien, surement un soucis avec le bateau.
J'ai attendu que le bateau fasse tout son trajet jusqu'au moment où il s'arrête mais même là le soucis est toujours présent.

**Comment by Ferro3** [comment]
[Un Voile d'hiver en famille]
Réalisé le 16/12/2020 pour ma part, donc aucun problème.
Tu t'y prends mal, ou tu as un addon qui interfère, je pense.

**Comment by Ischjgt** [comment]
Si tu as réussi le Haut-fait c'est parce que je vous rend le NPC dispo régulièrement :'(, le bug est avéré et connu depuis plusieurs années .
