### ISSUE TITLE
[Quete] L'appel

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1111]
Bonjour, je n'arrive pas a trouver le trigger pour activer l'item de quête (glyphes d'appel). J'ai pourtant l'impression d'être au bon endroit :
![image](https://user-images.githubusercontent.com/73133549/102688175-2a747400-41f5-11eb-96b9-6a8fa6bc988d.png)

https://woehead.way-of-elendil.fr/?object=180505

https://woehead.way-of-elendil.fr/?quest=8315

**Comment by joshwhedon** [comment]
J'ai teste et aucun probleme de mon cote. Et c'est a peu pres le bon endroit oui.
