### ISSUE TITLE
[quête] les effets de bijou       /       	 Message à Maxwell

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1112]
J'ai accès a ces quêtes en étant H2 alors qu'elles sont normalement réservées a l'alliance

La première quête est donc faisable en étant h2 vu que le pnj est neutre (mais il ne devrai pas nous la donner).
La 2ieme doit être rendu a un pnj allianceux (donc pas faisable pour les h2)

https://fr.classic.wowhead.com/quest=5001/les-effets-de-bijou
https://fr.classic.wowhead.com/quest=5002/message-%C3%A0-maxwell

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?quest=4982
Il y a deux version, horde et alliance.

**Comment by Zaralbahk** [comment]
On est bien d'accord qu'il y a deux version, mais il m'a filé celle de l'alliance.
J'ai surement deja fait celle de la hors il y a longtemps mais je ne sait pas comment le vérifier

**Comment by joshwhedon** [comment]
Tu as change de faction a un moment ? Parceque cote base de donnee, https://woehead.way-of-elendil.fr/?quest=5001 est la version alliance, avec la faction correctement mise a alliance, https://fr.classic.wowhead.com/quest=4982/les-effets-de-bijou estla version horde avec la faction correctement mise a horde.

**Comment by Zaralbahk** [comment]
Non je n'ai jamais changé de faction => par contre mon perso date du RDD et d'une époque ou les quêtes étaient beaucoup moins bien script donc c'est peu être lié à ça
