### ISSUE TITLE
Oculus - bug abuse

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1113]
Bonjour.

Il est possible d'aggro le **seigneur-mage urom** sur les 3 plateformes en chevauchant les drakes et donc d'éviter de faire les trash.
Cependant on entre en combat tout le long et ça fait tout planter lorsqu'on fait le boss au centre : une partie des add viennent au centre.

seigneur-mage urom : https://woehead.way-of-elendil.fr/?npc=27655

Aujourd'hui je me suis retrouvé dans un groupe qui a fait ça, j'avoue que ça casse la mécanique voulue.
La solution est peut-être de rendre l'aggro en monture impossible par le mage, je ne sais pas trop.

Bon courage, et bonnes fêtes de fin d'année.
+

**Comment by joshwhedon** [comment]
Corrige prochaine maj.
