### ISSUE TITLE
4T10 elem ne marche pas

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#1114]
**Description**
Le bonus 4T10 elem ne marche pas entièrement, il rallonge la durée de l'horion mais les 2 ticks supplémentaires rajoutées ne font pas de dégâts 

**Étapes de reproduction**
Prenez un chaman elem allez sur poteau, posez votre horion de flamme, laissez le tick entièrement (observer 6 ticks, des fois 7).
Maintenant posez votre horion et envoyez une explo de lave, la durée du buff augmente mais il n'y aura toujours que 6 (des fois 7) ticks.

**Comportement attendu**
Chaque explosion de lave posée durant la durée de l'horion de flamme rallonge ce dernier (okay) de 2 ticks qui doivent faire des dégâts (pas okay) 

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?itemset=-268
https://i.goopics.net/JbRjO.jpg
https://i.goopics.net/plAnm.jpg

**Comment by joshwhedon** [comment]
Corrige prochaine maj
