### ISSUE TITLE
Oculus - Drake Ambre

### ISSUE THREAD

**Issue by rindra-lutz** [way-of-elendil/3.3.5#1115]
**Description**
Le sort Faille Temporelle (touche 3) des Drake d'Ambre ne fonctionne pas bien. Il me semble qu'avant la merge il fonctionnait, et maintenant on a bien les stacks des charges qui s'accumulent jusqu'à 10, mais le sort de la touche 1 (Javelot de choc) ne les fait pas exploser et ne fait donc pas de surplus de dégâts comme il devrait en faire. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon : Oculus
- Niveau de difficulté : héroïque, non testé en normal mais j'imagine que ça doit être le même soucis
- Boss : Gardien Tellurique Eregos
- Sorts : Faille Temporelle (touche 3) et Javelot de Choc (touche 1)
- Monter un Drake Ambre dans l'Oculus

**Comportement attendu**
Le Javelot de Choc correspondant à la touche 1 est censé faire exploser les charges que l'on accumule avec le sort de la touche 3 (Faille Temporelle, maximum de 10 charges), ce qui est censé produire un surplus de dégâts par charge sur le boss.

**Captures d’écran / Vidéos**
Désolé, non disponible.

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?npc=27755

**Comment by joshwhedon** [comment]
Corrige prochaine maj
