### ISSUE TITLE
Boss: Gangrebrume - Loots

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1117]
**Description**
Name: Felmyst
Entry: 25038.

Il arrive que le cadavre soit inatteignable, quand il meurt juste après les nuages qui CM

<img width="1023" alt="Capture d’écran 2020-12-27 à 19 48 06" src="https://user-images.githubusercontent.com/60295792/103177649-a1a4aa80-487c-11eb-8f97-48b09831abae.png">

**Comment by joshwhedon** [comment]
Corrige prochaine maj
