### ISSUE TITLE
Repop à l'ange Darnassus coté horde

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1118]
Bonsoir.
En voulant faire  [La Foire des trônes]
https://woehead.way-of-elendil.fr/?achievement=4437

Je suis mort dans Darnassus dans la maison où se trouve Tyrande.
Je libère et je me retrouve à l'ange tout en bas de Sombrerivage en 43-92.
https://woehead.way-of-elendil.fr/?npc=6491

Il me semble que ça n'est pas le bon ange, ça me parait vraiment loin.
Pouvez vous vérifier, d'avance merci.

**Comment by joshwhedon** [comment]
De ce que j'ai pu trouver (pas enormement de sources) il s'agit du bon ange. Les anges sont toujours loin de la capitale pour la faction opposee, parce que sinon c'est trop facile pour les raids. Donc ca a l'air correct (vous pouvez regarder pour les autres capitales c'est plus ou moins pareil).

**Comment by Ferro3** [comment]
merci d'avoir vérifié.
