### ISSUE TITLE
Loot du coffre à EDC

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1119]
Dans l'instance 5 Épreuve du champion
Lors du second boss, une fois vaincu, le coffre disparait avant la distribution des objets si la suite est lancée (3ème boss) via le PNJ avant la fin des tirages.

Un bloqueur sur le lancement de la suite (3ème boss), ou bien l'absence de suppression du coffre peut résoudre le problème.

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/801
