### ISSUE TITLE
glyphe de Blocage (war)

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1120]
**Description**
Décrivez le problème de façon claire, précise et concise.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: war
- Race: undead
- Spécialisation: prot
- Sort / Talent / Etc: heurt de bouclier
- Circonstances (Donjon, Raid, PvP, autre): testé vs cerfs en bas de dala
- Equipement: shield forge ilvl200
- Buffs / Debuffs / Enchaînement de sort / Etc: glyphe de blocage

**Comportement attendu**

Lorsque le buff se déclenche après après fait un heurt de bouclier (comportement à ce moment normal) on ne voit pas de changement dans les % si on ouvre l'info personnage; est-ce normal ? sachant que la valeur de blocage augmenté devrait y figuré avec l'augmentation dès qu'on a le buff ou c'est uniquement un bug visuel ? car actuellement j'ai l'impression que j'ai 0 changement et quand j'utilise la formule de calcul je n'apperçois AUCUN changement dans la valeur avoidance alors que j'ai le buff de la glyph
![capture valeur avoidance](https://user-images.githubusercontent.com/63243193/103314976-8d9bad00-4a24-11eb-9317-25dfcd3f6a3c.PNG)

**Comment by joshwhedon** [comment]
Tu confonds la valeur de blocage et les chances de bloquer. Si tu regarde la page de personnage, la stat de blocage y'a 2 choses : les degats bloques et le % de chance de bloquer. Ce glyphe influe sur les degats bloques, et la valeur est bien mise a jour dans les stats quand il proc.
