### ISSUE TITLE
Talent Bénédiction Retribution Paladin

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1121]
Wessh l'équipe
-Le Talent Bénédiction de Paladin dans l'abre Retribution ne marche pas correctement

-Étapes de reproduction: 
Incanter un spell de type éclair lumineux ou exorcisme, et regardez le cout en mana, incantez le ensuite sous Proc Art de la guerre une fois le sort devenue incantation instantanée.

Le cout en mana du sort Eclair lumineux sous Art de la guerre ne coute que 11 de mana en moin , et exorcisme 0 de moin, cela est bien inférieur à 10% voir nul

- RET
- RET
- RET
- Bénédiction ( talent ) / Éclair lumineux / Exorcisme / Art de la Guerre
- Circonstances PARTOUT

**Comportement attendu**
Incanter Eclair lumineux ou exorcisme en instantané devrait couter 10% de mana en moin que en l'incantant

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?spell=20105
Voir la liste des sorts affectes. Ce talent ne concerne que les sorts qui sont reellement instantannes, par les sorts qui sont rendus instantannes par des circonstances exterieures. Si vous trouvez des sources indiquant le contraire merci de les fournir, mais jusqu'a preuve du contraire les donnees client sont la source de verite (et j'ai rien trouve d'autre les contredisant).

**Comment by Ischjgt** [comment]
_This talent is also useful to Holy Paladins, as it will reduce the mana cost of Holy Shock, instant Flash of Lights, Seals, Blessings and Judgements._
https://wowwiki.fandom.com/wiki/Benediction_(paladin_talent)

**Comment by joshwhedon** [comment]
Je viens de tester et le bug est le contraire de ce que tu dis. Pour exorcisme, c'est tout le temps applique, alors que ca devrait pas. Pour eclair lumineux c'est jamais applique, alors que ca devrait.

**Comment by Justforsoloq** [comment]
https://www.wowhead.com/forums&topic=141098

**Comment by Justforsoloq** [comment]
Mais je tombe en effet sur le wiki de https://wowwiki.fandom.com/wiki/Benediction_(paladin_talent) qui contredit la discussion wowhead ci dessus donc :<
