### ISSUE TITLE
Ecureuil à dalaran

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1122]
On arrive plus à tuer les écureuil à dalaran; ceci est problématique pour le hf des nuisibles merci de corriger cela 👍 

voici un screen du hf en question: 
![capture hf](https://user-images.githubusercontent.com/63243193/103445295-84078480-4c72-11eb-8d9a-086211c35a53.PNG)

**Comment by Ferro3** [comment]
Désinsectisation :
https://woehead.way-of-elendil.fr/?achievement=2556

Les écureuils dans Dalaran sont effectivement bug de temps en temps, mais y a tellement d'écureuils dans le monde...

**Comment by joshwhedon** [comment]
Ouai ...honnetement je sais pas comment ca arrive, j'airrve pas a reproduire en local, je pense qu'ils buggent parce qu'ils se bloquent dans le puit. Faudra faire avec desole.
