### ISSUE TITLE
Armure tranchante

### ISSUE THREAD

**Issue by Elahpascriptelaspeblood** [way-of-elendil/3.3.5#1124]
**Description**
L'Armure tranchante ne fonctionne pas comme il faudrait, je dirai m^me qu'elle ne fonctionne pas du tout ou bizarrement, c'est à dire qu'elle prend en compte l'armure du personnage au moment ou il change de spécialisation. Elle ne prend pas en compte la présence de givre, c'est à dire que quand le dk passe en présence de givre, grâce au talent en question sa PA doit augmenter grâce au up d'armure que donne la présence de givre ce qui n'est pas le cas ici.

**Étapes de reproduction**
Faite une spé avec armure tranchante et une spé sans pour comparé la pa et changer d'équipement pour faire varier l'armure et changer aussi de présence pour constater le bug.
- Classe : DK
- Race: Orque
- Spécialisation: peu importe tant que le talent "Armure tranchante" 5/5 est pris dans la spé
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
On attend de l'armure tranchante qu'elle fasse évoluer la PA sur les switch présence et stuff à tout moment. L'aura de dévotion du paladin aussi n'est pas prise en compte ce qui devrai être le cas.

**Captures d’écran / Vidéos**
Talents + PA sans le talent "Armure tranchante" et sans présence.
![image](https://user-images.githubusercontent.com/72766795/103490410-d932ca00-4e1b-11eb-9d1f-84ba944b23b3.png)
Talents + PA avec le talent "Armure tranchante" et sans présence.
![image](https://user-images.githubusercontent.com/72766795/103490464-2f077200-4e1c-11eb-9dd4-e6e2b56b8ed5.png)
Talent + PA avec le talent "Armure trachante" et avec présence de givre.
![image](https://user-images.githubusercontent.com/72766795/103490485-6118d400-4e1c-11eb-82fc-83c1f333e08a.png)

je possède aucune source offi pour appuyer le BT mais je pense que cela vas de soit que la PA doit évoluer en permanence en fonction de l'armure et de la présence du DK.

**Comment by Justforsoloq** [comment]
https://classic.wowhead.com/forums&topic=54276

**Comment by Justforsoloq** [comment]
2009-06-15, 09:10 PM #4
harky
harky is offline
Scarab Lord

Join Date
    Jul 2008
Posts
    4,274

Re: importance of bladed armour for tanks.

    Yes, Bladed Armor is in nearly every cookie-cutter tanking spec. Since it now scales with Frost Presence it's a much larger AP gain for tanks than it is for DPS.

**Comment by joshwhedon** [comment]
Elle marche tres bien, le seul bug c'est que la puissance d'attaque est pas recalculee a chaque fois que l'armure change. Je corrige ca.

**Comment by Ischjgt** [comment]
@joshwhedon  fait fgaffe https://github.com/way-of-elendil/3.3.5/issues/608

Elle doit pas être recalculée quand l'armure change mais toutes les 30 secondes ou quand le joueur reçoit un buff PA

**Comment by joshwhedon** [comment]
Ha merde t'as raison et ca marche deja je crois. Je vais retester.
