### ISSUE TITLE
Frappe de mort en DK Spé givre Ambi

### ISSUE THREAD

**Issue by Elahpascriptelaspeblood** [way-of-elendil/3.3.5#1125]
**Description**
La frappe de mort en spécialisation ambidextre tape 2 fois grâce au talent : "Menace de Thassarian" 3/3. Étant donné que une frappe de mort rend 5% HP par maladie et par hit, la logique voudrai que en spé givre ambi une frappe de mort rende 20% HP vue qu'elle tape 2 fois en même temps donc 2x(5% x 2 maladies) = 20% ce qui n'est pas le cas. Actuellement la frappe de mort du dk givre ambi tape 2 fois mais rend que 10% HP.

**Étapes de reproduction**
- Classe: DK
- Race: Orque
- Spécialisation: Givre Ambidextre
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
La frappe de mort est sensé rendre 20% HP en spé Givre Ambi avec le talent "Menace de Thassarian".
**Captures d’écran / Vidéos**
2 frappe de morts
![image](https://user-images.githubusercontent.com/72766795/103490982-eb166c00-4e1f-11eb-9779-7dfd6cc94a80.png)
10% heal pour 2 frappe de mort 
![image](https://user-images.githubusercontent.com/72766795/103490969-d6d26f00-4e1f-11eb-8087-4f1b377fcac2.png)

**Comment by joshwhedon** [comment]
La "logique" n'est pas un argument suffisant. Blizzard n'est pas logique. Merci de fournir une preuve que le comportement actuel n'est pas normal.

**Comment by Justforsoloq** [comment]
https://www.youtube.com/watch?t=6m9s&v=77B8XGBXarw&feature=youtu.be
6mn10-6mn11 dk (avec frappe de thassarian) frappe de mort et est heal (avec 2 disease sur la tar) de 3k4 soit 10% de sa vie et non 20%.
La frappe de thassarian n'applique pas le double 10% healing.

**Comment by joshwhedon** [comment]
Merci @Justforsoloq . Je ferme ce ticket, merci de commenter si des informations contradictoires sont trouvées.

**Comment by Kalblack-Atin** [comment]
Bonjour,
J'interviens un petit peu en retard mais je pense que ce n'est jamais tard pour bien faire.
Alors Fune @Justforsoloq, je pense que la vidéo a été faite sous une extension qui précèdait la 3.3.3.

En effet arrivé à la 3.3.3, le healing donné par la frappe de mort a été unifié pour toutes les spés du DK, à savoir 15% de la vie du DK, et cela comme suit  : 

- En spé givre : les deux maladies sont appliquées et le talent (menace de thassarian) est prit ;
- En spé impie : les deux maladies + peste d'ébène sont appliquées ;
- En spé sand : le talent frappe de mort amélioré augmente le healing de 50%, soit 15% encore.

**Source :** 
Hotfix (2009-04-21): "Death Strike will now heal the Death Knight for 5% of his or her maximum health per disease on the target, up to a maximum of 15%
https://wowwiki.fandom.com/wiki/Death_Strike
**Etat actuelle en spé givre :**
Que 10% de healing via la frappe de mort même si on l'applique en présence des deux maladies du dk sur la cible et le talent menace de thassarian qui est prit , ce qui est pénalisant.

**Comment by Justforsoloq** [comment]
Non t'as pas compris kal, le 15% c'est un nerf pour la spé blood et impie qui se healait plus avant.
