### ISSUE TITLE
Achievement: Froid Intense - Keristrasza - Nexus HM

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1126]
**Description**
Name: Keristrasza Entry: 26723.
https://woehead.way-of-elendil.fr/?achievement=2036
48095 - [Froid intense, rank 1 frFR] 

Le haut-fait s'obtient quelque soit le nombre de stacks que l'on possède

**Comment by joshwhedon** [comment]
Corrige prochaine maj
