### ISSUE TITLE
[ Druide / L'épreuve du lion de mer / Quête] Position pendentif éronnée

### ISSUE THREAD

**Issue by DirtyRecords** [way-of-elendil/3.3.5#1127]
**Description**
La position (point d'interrogation jaune) du Demi-pendentif d'endurance aquatique est signalée sur la carte au large de la zone Forêt des Pins Argentés, alors qu'il devrait se trouver au large de la zone Marche de l'Ouest.

**Étapes de reproduction**
- La Marche de l'Ouest
- Alliance / elfe de la nuit / Druide
- L'épreuve du lion
- Tajarri

**Comportement attendu**
Mauvais emplacement du demi pendentif d'endurance aquatique

**Captures d’écran / Vidéos**
Capture_1 = mauvais emplacement
Capture_2 = bon emplacement
![Capture_1](https://user-images.githubusercontent.com/77007177/103654111-c1675d00-4f65-11eb-9eae-c5bf1b5c818f.PNG)
![Capture_2](https://user-images.githubusercontent.com/77007177/103654128-c6c4a780-4f65-11eb-8fea-3520a09df203.PNG)

**Ressources additionnelles**
https://fr.classic.wowhead.com/quest=272/l%C3%A9preuve-du-lion-de-mer
https://fr.classic.wowhead.com/item=15882/demi-pendentif-dendurance-aquatique

**Comment by joshwhedon** [comment]
Comme indique sur woehead et wowhead, il y a deux coffrets.
https://woehead.way-of-elendil.fr/?item=15882
https://fr.classic.wowhead.com/item=15882/demi-pendentif-dendurance-aquatique#contained-in-object
Le fonctionnement et les emplacements semblent correspondre.

**Comment by joshwhedon** [comment]
Ha pardon mal compris tu parle juste de l'indicateur de quete.

**Comment by DirtyRecords** [comment]
Oui le point d'interrogation jaune indiquant l'emplacement du coffre est mal positionné.
