### ISSUE TITLE
Spell: Disengage

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1128]
**Description**
781 - [Désengagement, rank 1 frFR] 
49576 - [Poigne de la mort, rank 1 frFR] 

Je trouve plus les tickets à propos du Death Grip et j'ai pas trouvé de preuves non plus
Mais je pense que le hunt doit pouvoir disengage quand il est en mouvement lors du death grip du DK (l'inverse est possible)

Le problème étant que le cooldown est quand même activé lorsque le chasseur le fait alors qu'il finit dans tous les cas au corps à corps du DK

**Comment by joshwhedon** [comment]
Va falloir le prouver, dans un sens ou dans l'autre. 
Tout ce que je trouve c'est : https://www.mmo-champion.com/threads/642003-Diminishing-Returns-on-Death-Grip
"Hunters can disengage after landing"
C'est le comportement actuel non ?

**Comment by Ischjgt** [comment]
Oui,
Mais le CD est utilisé si le chasseur disengage pendant le grab, et ça je pense vraiment que c'est un soucis,
j'attends une réponse pour savoir ce qui se passe sur offi actuellement mais j'aurais pas plus d'infos

**Comment by joshwhedon** [comment]
Je doute que ce soit un soucis.

**Comment by Ischjgt** [comment]
Apparemment, sur offi actuellement il existe un talent pour les chasseurs qui leur permettrait de pouvoir Disengage pendant l'entrave du grab. Le CD serait quand même consommé si le chasseur ne possède pas le talent.
