### ISSUE TITLE
NPC: Grel'borg l'Avare

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1129]
**Description**

https://woehead.way-of-elendil.fr/?npc=2417

Il a un parcours étrange et passe à travers les murs quand il est prêt du fort (lors du chemin [cave/prison]=>exterieur)

**Comment by joshwhedon** [comment]
Il aime pas les mmaps :(. J'y peux pas grand chose, j'ai teste en local avec les mmaps desactivees il a pas de soucis.
