### ISSUE TITLE
[drop] Taux de loot Figurine perdue dans le temps

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1130]
Le taux de loot de la figurine sur terokk semble trop faible par rapport a ce qu'il devrai être : 
WOE : 2 %
https://woehead.way-of-elendil.fr/?item=32782#dropped-by

Offi : 9%
https://fr.wowhead.com/item=32782/figurine-perdue-dans-le-temps

Un guide d'époque qui mentionne un taux de drop de 8% :
 https://forums.jeuxonline.info/sujet/1072898/guide-figurine-perdue-dans-le-temps

**Comment by Ischjgt** [comment]
Ces 2 sources ne sont pas des sources fiables.

**Comment by joshwhedon** [comment]
La plupart des taux de drop d'objets ont ete obtenu a partir des donnees wowhead de l'epoque, de ce fait ont plus de chances d'etre valides que des donnees plus recentes.
