### ISSUE TITLE
Chances de coup critique après avoir été désarmé

### ISSUE THREAD

**Issue by Gde01** [way-of-elendil/3.3.5#1131]
**Description**
Bug récurent avec le guerrier et avec le paladin (et probablement avec toutes les classes qui se battent principalement avec des armes). Après avoir été désarmé, les chances de coups critiques diminuent, même après avoir récupéré son arme. Pas toujours mais très souvent. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe
- Race
- Spécialisation
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Ischjgt** [comment]
Merci beaucoup pour ton report, je ferme le ticket j'en fais un plus général.
