### ISSUE TITLE
% coups critiques en mélée

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1132]
**Description**
Cela fait suite à https://github.com/way-of-elendil/3.3.5/issues/1131

Il y a des soucis avec le % de cc, j'ai pas encore regardé si ce n'était qu'affichage
C'est présent sur toutes les classes et sans talents 

Je vois rien d'anormal avec .list aura

**Étapes de reproduction**
- On va prendre un perso level 80 qui peut manier les épées
- .add 886 - [Epée courte en métal noir] 
50732 - [Coup-de-sang, la lame d'agonie de Kel'Thuzad] 
(une avec du critique, l'autre non donc)
- porter l'épée courte en métal noir et noter le score de crit ET le % de critique
- porter coup de sang et et noter le score de crit ET le % de critique
- remettre l'épée courte en métal noir, le % de critique n'est plus le même qu'avant, le score reste le même
=> ce problème ne s'en va à la déco QUE si le joueur déco sans arme
OU, après un desarmement et un changement d'arme, comme l'a signalé le joueur dans le ticket que j'ai link plus haut

**Comment by Ischjgt** [comment]
Je te MP d'autres infos.

**Comment by Ischjgt** [comment]
Je suis pas très sur de ce que j'avance donc information à prendre avec des pincettes mais il semblerait que le soucis surviennent sur des persos créés à une date postérieure à juin 2017, c'est probablement pas du tout la bonne date mais je suis remonté jusque là pour le moment

**Comment by Ischjgt** [comment]
Sur certains persos qui ont été créé après cette date, j'ai ceci.
Je viens de test sur plusieurs centaines de AA, j'ai eu 0 crit
Le probleme a l'air légérement différent, c'était sur druide et pretre avec du stuff PS. Mais il se produit de la même façon : le 0 arrive après une déco reco en portant une arme sans critique par exemple

<img width="257" alt="Capture d’écran 2021-01-18 à 02 57 34" src="https://user-images.githubusercontent.com/60295792/104864334-f5188e80-5938-11eb-9005-ceb49ca5e80c.png">

**Comment by joshwhedon** [comment]
Je doute fortement que ca ait quoi que cesoit a voir avec une quelconque date.

**Comment by Ischjgt** [comment]
Je sais pas expliquer pourquoi sur de rares persos ça ne me le fait pas en tout cas

**Comment by joshwhedon** [comment]
Corrige prochaine maj, mais le soucis etait purement visuel au niveau de l'affichage du critique, ca concerne pas les vrai valeurs.
