### ISSUE TITLE
[Quête] Concours de pêche des Kalu'aks

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1133]
L'ancien clairdeleau ne propose aucune des 2 quêtes pendant le concours de pêche, ce qui rend le concours infaisable (J'ai slack devant le pnj entre 14h17 et 15h17 mais pas de quête qui pop, ensuite mon requin qui n'a une durée de vie que d'une heure a disparu):
https://woehead.way-of-elendil.fr/?npc=38294#starts

Il devrai en théorie proposer  ces quêtes entre 14h et 15h chaque samedi 
https://fr.millenium.gg/guide/8603.html

**Comment by joshwhedon** [comment]
On me confirme que l'event marche, mais les joueurs finissent la quete tres vite, dans les 5 minutes qui suivent le demarrage.

**Comment by Zaralbahk** [comment]
Dans ce cas la PNJ devrait a la rigueur proposer la quête https://woehead.way-of-elendil.fr/?quest=24806
Or la il n'en proposait aucune.

**Comment by Zaralbahk** [comment]
Même bugg cette semaine, J'ai fini le concours en 4 min, j'ai aussi laissé un 2ieme personnage devant le pnj pour voir si il proposait une quête (et accessoirement voir si il y avais un problème lié à l'heure du serveur) => Le pnj pop a 13 h, aucune quete proposé que ca soit a 13h, 13h15, 13h30, 13h45, ou rien non plus entre 13h55 et 14h10.

Pour rappel, les 2 quêtes (celle du vainqueur ou celle des perdants si il y a deja un vainqueur) sont censé être dispo de 14h jusqu'à 15h.
![peche2](https://user-images.githubusercontent.com/73133549/105579265-c4e04e00-5d85-11eb-9c93-2e629836db7d.jpg)

**Comment by Zaralbahk** [comment]
Si on regarde les heures des events sur la DB sur serveur, la quête aurai bien dû être disponible (les events qui ont leurs date en vert sont ceux qui sont "en cours"). Par contre il semble que l'event lié à la quête "looser" ai une date et une heure incorrecte.

![peche3](https://user-images.githubusercontent.com/73133549/105579878-7af96700-5d89-11eb-9e82-db11b92f37b0.jpg)

**Comment by Zaralbahk** [comment]
=>Ma supposition c'est que le concours de pêche marche (pnj et disponibilité du requin), par ce que l'event associé (2ieme ligne sur la capture d'écran ci-dessus) est dans la categorie "recuring".
Et par contre la quête qui est catégorisée "Uncategorized" n'a peu être pas droit à sa récurrence ttes les semaine du coup.

**Comment by Ischjgt** [comment]
<img width="337" alt="Capture d’écran 2021-01-23 à 14 55 40" src="https://user-images.githubusercontent.com/60295792/105580195-3a9ae880-5d8b-11eb-9044-4bf600f784c7.png">

**Comment by Zaralbahk** [comment]
Du coup je suis venu au pnj une min plus tard et j'ai eu droit a la quête du perdant, tout marche bien au final, simplement le pnj propose la quête a 14h55 au lieu de 14h apparemment

**Comment by Zaralbahk** [comment]
autre info intéressante : 
![image](https://user-images.githubusercontent.com/73133549/105580426-9d40b400-5d8c-11eb-9674-febdd13826d2.png)

**Comment by Ischjgt** [comment]
1. Quelqu'un a rendu la quête parce qu'il possédait la quête depuis plusieurs semaines
<img width="337" alt="Capture d’écran 2021-01-23 à 14 55 40" src="https://user-images.githubusercontent.com/60295792/105580343-18ee3100-5d8c-11eb-9e20-746ce99aaa65.png">
C'est à ce moment la qu'Arkannor a eu l'option pour pouvoir rendre l'autre quête, adressée à ceux qui ont perdu le tournoi

2. Sinon Chantétoile ne donne pas la quête

3. Ils manquent toutes les annonces associées exceptée celle qui annonce le gagnant
https://oldbugtracker.way-of-elendil.fr/index.php?do=details&task_id=5596

**Comment by Zaralbahk** [comment]
Bonjour, concours encore refait aujourd'hui, cette fois requin péché à 14h04, mais tjs absence de quête disponible pour rendre et pourtant cette fois je suis resté une heure entière devant le pnj^^ (jusqua la depop de mon requin dans l'inventaire. 
La quete n'a pas pop a 14h55 comme la semaine passée, donc comme précisé par Ischjgt le soucis doit etre lié a une personne avec la quete en sa possession qui du coup bloque toute les autres?
Comme on a pu le voir précédemment l'ancien fait une annonce dans tout norfendre quand quelqun gagne le concours et en plus une fois qu'une personne gagne la quete des perdants est dispo, donc je suis a peu pres sur que personne n'as encore gagné cette semaine. 
![WoWScrnShot_013021_140441](https://user-images.githubusercontent.com/73133549/106358554-359ae380-630d-11eb-8e5c-66774630c42e.jpg)
![WoWScrnShot_013021_140518](https://user-images.githubusercontent.com/73133549/106358556-392e6a80-630d-11eb-8134-dffb98f823aa.jpg)

thx

**Comment by Zaralbahk** [comment]
Concours re-testé ce jour, requin péché, mais tjs pas de quête proposée par le PNJ

**Comment by Zaralbahk** [comment]
Bonjour, tjs le même bugg sur le concours de pèche, seules les personnes ayant la quête dans leur journal depuis longtemps arrivent à la rendre, le pnj ne propose toujours pas la quête (testé avec 7 personnage différent, c'est un bon chiffre / j'ai croisé une personne qui a rendu la quête du concours la semaine dernier mais l'avais dans son journal depuis plusieurs mois).

Un petit reset de cette quête pour la supprimer du journal de tout les joueurs du serveur serai la solution? 
https://woehead.way-of-elendil.fr/?quest=24803

**Comment by gtschanz** [comment]
vu qu'il y d'autres joueurs qui se plaignent régulièrement et que ce bt à l'air d'être ouvert depuis le 20 janvier et qu'on est bientôt en avril; serait-il envisageable de faire quelque chose ? (à titre perso j'aimerais aussi pouvoir le faire rien que pour l'anneau +5 xp...)

**Comment by joshwhedon** [comment]
Je sias, je regarderai encore mais j'ai vraiment pas le temps a l'heure actuelle. Le soucis c'est que cette merde je peux la tester qu'une fois par semaine.

**Comment by delmelo** [comment]
Je confirme ce qu'a dit Zaralbahk : ce weekend (17/07) j'ai pêché le requin pointe-noir dans un banc de poissons vers 14h10 mais le PNJ ne propose pas de quête.

**Comment by gtschanz** [comment]
up ? fait bientôt 8 mois que ce bt est ouvert, il faudrait vérifier le truc ou limite mettre une remarque du genre : ne sera jamais corrigé au moins ça évitera que des joueurs se lance à l'aventure comme un gars cette après-midi à qui j'ai fait remarqué qu'il y a un bt ouvert depuis le 16 janvier....

**Comment by Kaasss-woe** [comment]
Correctif appliqué.
