### ISSUE TITLE
[TEXTURE HD] Bug de texture sur les sourcils des draeneis Femmes

### ISSUE THREAD

**Issue by jslevacque** [way-of-elendil/3.3.5#1134]
**Description**
La texture des sourcils des draeneis Femmes semble incorrect (Petit pointillé) sur le nouveau pack de texture. Je pense que ce bug n'arrive pas forcément sur tout le monde car un ami n'a pas eu ce problème. C'est à partir de l'utilisation du Wow texturé en HD que ce bug est arrivé sur mon jeu. 

**Étapes de reproduction**
- Il suffit de télécharger le WOW textures HD proposé sur le site https://way-of-elendil.fr/game/downloads
- Je suis donc sur Windows  et j'ai téléchargé la version '.zip'.
 ![image](https://user-images.githubusercontent.com/41906971/104844842-b51ec080-58d2-11eb-8d5e-9b1761e58155.png)
- Avoir un Draenei femme ou bien aller dans la création de personnage. 
- Peut importe le visage sélectionné, le résultat est le même

**Comportement attendu**
Je suis censé trouver des sourcils en pointillé sur mon personnage. 
**Captures d’écran / Vidéos**
Voici une image représentative d'une draenei femme : 
![image](https://user-images.githubusercontent.com/41906971/104845003-7b01ee80-58d3-11eb-8066-fabb5bcceb01.png)
Paramètre Video Résolution: 
![image](https://user-images.githubusercontent.com/41906971/104845163-3cb8ff00-58d4-11eb-991e-7d72b0372c84.png)
Paramètre Video Effet: 
![image](https://user-images.githubusercontent.com/41906971/104845134-1dba6d00-58d4-11eb-94df-437a60a3f78b.png)

**Comment by joshwhedon** [comment]
Desole ce ne sera probablement pas corrige, le patch hd a malheureusement ce genre de resultat.
