### ISSUE TITLE
[taux de loot] Fragment de val'anyr

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1135]
https://www.wowhead.com/item=46017/valanyr-hammer-of-ancient-kings
"Fragments are not guaranteed to drop off every boss, but the chance for a fragment to drop can be increased by doing a boss on hardmode (Note: Ignis, Razorscale, and Auriaya DO NOT have hardmodes)."

https://wow.gamepedia.com/Fragment_of_Val%27anyr
![image](https://user-images.githubusercontent.com/73133549/104850780-5c125500-58f1-11eb-9118-a39eaa226f33.png)

Je fait un ticket ici car je n'arrive pas a voir les données sur la db du serveur : 
Le taux de drop des fragment en raid ulduar 25 semble bon lorsque l'on lance les boss en NM;
Néanmoins quand les boss sont tué en "mode difficile" le taux de drop du fragment devrai être augmenté, ce qui n'est pas visualisable sur la db actuellement, est ce possible de vérifier que le taux de loot est bien augmenté?  
En pratique en tuant les boss Hm on on devrait être capable de doubler la vitesse d'obtention d'une val'anyr, ce qui fait une bonne carotte pour motiver des joueurs a faire du Uldu en 25 avec les boss en HM

https://woehead.way-of-elendil.fr/?item=45038#dropped-by 
On peu voir que le taux de loot du fragment sur Brise acier est de 18% comparé a 8 % sur les deux autres boss de l'assemblé, ce qui correspond plus ou moins a l'écart de taux de loot qu'il devrai y avoir entre chaque boss en NM et leur version en HM.
![image](https://user-images.githubusercontent.com/73133549/104850488-b1e5fd80-58ef-11eb-84e8-a691eabbf2fc.png)
        
https://woehead.way-of-elendil.fr/?item=45038#contained-in-object
Meme chose si on regarde la liste des coffres, le coffre de mimiron HM, freya HM et Thorim HM loot bien a 18%, par contre il semblerai que le coffre de Hodir HM ne loot pas de fragment ce qui fait que le taux de drop est le même pour Hodir nm et HM, est-ce normal?
![image](https://user-images.githubusercontent.com/73133549/104850501-bb6f6580-58ef-11eb-94a7-d837df10e833.png)

Pour résumer j'ai l'impression que sur le serveur il y a les pb suivants:
Leviathan : taux de drop pas augmenté en HM
XT : taux de drop pas augmenté en HM
Hodir : taux de drop pas augmenté en HM (pb lié au fait que les loot HM sont présent dans un 2ieme coffre séparé)
Freya : pourquoi un taux de loot a 5% uniquement dans le coffre NM au lieu des 8% habituels? Est ce qu'il faut pull freya avec 1 ou 2 anciens pour avoir le coffre a 7% qui est indiqué sur la DB?
Vezzax : taux de drop pas augmenté en HM

Voila! Si jamais ça aide a voir plus de val'anyr sur le serveur

**Comment by joshwhedon** [comment]
Donc j'ai regarde : Ignis, Leviathan, Razorscale, XT-002, Kologarn, Auriaya : meme loot, 8%, en normal et en hard pour ceux qui ont un mode hard (comme indique sur le wiki, meme pour XT le wiki dit qu'il y a pas d'augmentation)
Assemblee de fer, le mode hard c'est Steelbreaker en dernier, et comme indique, 8% les autres, 18% Steelbreaker
Hodir apparament le coffre additionel est suppose drop en hard, du coup je vais lui ajouter (avec les 2 coffres ca fera du 20 % en hard).
Mimiron drop 2 coffres differents, un a 8% en normal, un a 18% en hard, ca semble correcte.
Pareil pour Thorim, 2 coffres differents.
Pour Freya, plus y'a d'anciens, plus le taux de loot est eleve (different coffre pour chaque).
Algalon 20%, ca semble correct.
Vezaxx etant un boss de fin il a un taux legerement plus eleve que les autres boss, mais comme indique sur le wiki, le taux est pas vraiment different entre normal et hard.
Donc oui je vais corriger le coffre d'Hodir. Mais pour les autres taux ca semble plus ou moins corrects (ils sont d'ailleurs plus eleve que la moyenne des taux indiques sur le wiki).
