### ISSUE TITLE
[drop] AQ40 Empereurs Jumeaux

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1136]
Lorsqu'on tue les empereur jumeaux Vek'lor et Vek'nilash, seul un des 2 donne des loot, l'autre n'est pas lootable, le pb a été observé plusieurs fois et le boss lootable change selon les cas sans raison clairement identifiée.

https://woehead.way-of-elendil.fr/?npc=15275#drops
https://woehead.way-of-elendil.fr/?npc=15276#drops

*Idée si il est impossible de rendre les 2 boss lootables : fusionner la table de loot?

**Comment by joshwhedon** [comment]
Devrait etre corrige prochaine maj.
