### ISSUE TITLE
Spell: Buff critique et switch d'armes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1137]
**Description**
https://oldbugtracker.way-of-elendil.fr/index.php?do=details&task_id=5715

C'est ce que je t'ai MP et qui peut aussi être lié à https://github.com/way-of-elendil/3.3.5/issues/1132
Le bug est toujours présent, j'ai juste testé avec l'aura 12856 
Eridium a mentionné les autres sur le ticket de l'ancien BT dans les commentaires, dit moi si tu as besoin que je les test toutes

**Comment by joshwhedon** [comment]
Corrige prochaine maj avec l'autre soucis je crois (soit dit en passant 12856 marche pas a mains nues c'est normal)
