### ISSUE TITLE
Achievement: Démineurs

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1138]
**Description**
https://woehead.way-of-elendil.fr/?achievement=1428

Je crois bien qu'il est impossible d'obtenir le HF Démineurs 

De plus, les mines sont censées faire des dégats quand elles explosent sur le joueur ce qui n'est pas le cas actuellement

**Ressources additionnelles**
https://www.youtube.com/watch?v=wVr0iLYxRI0

**Comment by joshwhedon** [comment]
Il est faisable je l'ai reteste il y a quelques mois.

**Comment by Ischjgt** [comment]
Bin là j'y arrive pas et les mines font pas de dégats :c

**Comment by Endalaust** [comment]
Pour info le dernier joueur a avoir obtenu ce HF l'a eu en novembre 2019
J'ai un gros doute sur la faisabilité aussi, c'est un HF classique facile à faire quand on est dégourdi

**Comment by joshwhedon** [comment]
Corrige prochaine maj

**Comment by Endalaust** [comment]
Toujours aucun dégâts subits
