### ISSUE TITLE
[Quête] [71] [L'alpha des worgs] bug & suggestion

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1140]
Salut.

Voici plusieurs fois qu'en faisant [71] [L'alpha des worgs] https://woehead.way-of-elendil.fr/?quest=11324 Garwal https://woehead.way-of-elendil.fr/?npc=24277 est introuvable malgré le buff des yeux d'aigle https://woehead.way-of-elendil.fr/?spell=50102
Après un reset serveur Garwal est là, se qui me fait penser qu'il y a peut-être un problème de repop. Pouvez vous vérifier ?

De plus, si on s'éloigne trop de la zone de la quête, le buff des yeux d'aigle disparait. Il est fastidieux d'abandonner la quête, puis d'aller rechercher le [Déguisement de worg] https://woehead.way-of-elendil.fr/?item=33618#created-by founi par https://woehead.way-of-elendil.fr/?npc=24186
Serait-il possible d'ajouter une bulle sur Ulfang https://woehead.way-of-elendil.fr/?npc=24261 pour remettre le buff des yeux d'aigle https://woehead.way-of-elendil.fr/?spell=50102 ?

d'avance merci.

**Comment by joshwhedon** [comment]
Il est bien spawn mais il fait un chemin.
Pour la suggestion, est-ce que c'est le cas sur officiel ?

**Comment by Ferro3** [comment]
je ne pense pas que ça soit le cas sur officiel, en fait j'en sait rien du tout.

**Comment by joshwhedon** [comment]
J'ai verifie, il y a deja un script pour recuperer le deguisement si la quete https://woehead.way-of-elendil.fr/?quest=11317 est finie mais https://woehead.way-of-elendil.fr/?quest=11324 ne l'est pas (et que le joueur a pas le deguisement).

**Comment by Ferro3** [comment]
Lorsqu'on perd le buff des yeux d'aigle https://woehead.way-of-elendil.fr/?spell=50102 on ne peut plus faire la quête.
Il ne nous reste qu'a abandonner la quête et là on perd le  [Déguisement de worg] https://woehead.way-of-elendil.fr/?item=33618#created-by founi par https://woehead.way-of-elendil.fr/?npc=24186
Comme précisé dans le 1er post.

Donc oui le script est présent, la suggestion demandait juste soit de garder l'item en cas d'abandon de la quête, soit l'ajout d'une bulle/script sur le donneur de quête, ce qui a été refusé.
