### ISSUE TITLE
Quest: La guerre des boutons

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1141]
**Description**
10613 - [La guerre des boutons] 
10612 - [La guerre des boutons]  
Name: Fel Reaver Sentinel Entry: 21949.

1. Je pense pas qu'il soit possible de se déplacer comme bon nous semble avec le Fel Reaver Sentinel contrôlé, en effet ses spells sont insane et il est possible de se déplacer vraiment très loin en 5 minutes pour foutre un peu la merde dans une bonne partie de l'OT

Ça parle de phase sur WoWhead
`_I completed this quest within the time given for it (5 minutes) and when i returned, the quest giver and the guards nearby were gone, so i failed the quest. If this happens, run down the slope to the point when the sky turns purple and run back up. Theyll be there. Also, as a hunter, you can't have your pet out or the control panel will not work._`

`_To complete the quest you need to remove the buff from your character to give up control of the reaver._`

`_GREAT advice, I had the same problem and just went down the slope about 60 yards and poof, purple sky, NPCs and control panels are back._`

https://www.wowhead.com/quest=10612/the-fel-and-the-furious#comments
 

2. [Deathforged Infernal] GUID: 164277 ID: 184979
Les gobs sont activables et se détruisent lorsqu'on clique dessus

**Comment by joshwhedon** [comment]
Corrige prochaine maj
