### ISSUE TITLE
NPC: Vile Spirit

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1142]
**Description**
Name: Vile Spirit Entry: 37799.

Sensibles au roots, en particulier Flèche givrante, Sarments, le totem lien terrestre la nova de givre etc
J'ai du mal à trouver des infos dessus mais je pense pas que ce soit possible

**Comportement attendu**
Je pense que ces NPCs doivent agir de la même façon que les Val'kyrs, à savoir insensibles aux slows de 100%

https://www.mmo-champion.com/threads/745101-Vile-Spirits-in-LK-10-Man-HC
Ce lien donne vers une discussion faisant par de différentes techniques utilisées pour s'occuper des esprits vils, en 10HM, particulièrement.
Pour example, en ce qui concerne les chasseurs, les joueurs font mentions de frost trap (patinoire) mais jamais des piège de glace/flèche givrante/nova de givre/roots des droods/esham

https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)
`An effective strategy is to drag the Lich King to one edge of the room and then drag him all the way to the opposite side after Vile Spirits spawn, and kite them through Earthbind Totems and frost traps.`

**Comment by Bleuphonix** [comment]
Bonjour j'ai découvert se phénomène hier soir en faisant des teste perso et effectivement le toto de lien terrestre en cham elem avec le talent https://woehead.way-of-elendil.fr/?spell=51486 , les esprits sont bien ralenties par l'aura , se qui ne m'a pas surpris vue que la plaque de glace du chassou marche mais le faite que les esprits soir sarment dans mes airs m'a surpris

**Comment by joshwhedon** [comment]
Corrige prochaine maj
