### ISSUE TITLE
Boss: High Astromancer Solarian  

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1143]
**Description**
Name: High Astromancer Solarian
Entry: 18805.

Il est possible de balader le boss partout dans le donjon de la tempête

**Comportement attendu**
https://wowwiki.fandom.com/wiki/High_Astromancer_Solarian
`The boss can be reset by dragging her out of the room. Note that people may still be targeted by Wrath outside, which can potentially be a problem.`

**Comment by joshwhedon** [comment]
Corrige prochaine maj
