### ISSUE TITLE
Ardent défenseur ne s'active pas contre la Reine de Sang

### ISSUE THREAD

**Issue by TrucEtrange** [way-of-elendil/3.3.5#1144]
**Description**
Ardent défenseur ne s'active pas quand un pala tank MT2 meurt contre la Reine de Sang.

**Étapes de reproduction**
- ICC, n'importe quelle difficulté (bug constaté en 10h et 25n)
- Reine de Sang
- Être pala tank MT2, ciblé par le lien

**Comportement attendu**
Lorsque le paladin subit des dégâts mortels, le talent ardent défenseur doit s'activer, lui rendant 30% de sa vie max.

**Captures d’écran / Vidéos**
Report de recount sur les dégâts subis avant de mourir. Je passe de 23% à 0 sans savoir pourquoi. Le coup fatal a été causé par un voile de chagrin à 2k2. Ardent défenseur ne s'est pas activé pendant le combat (preuve : pas de débuff).

![ArdentDef](https://user-images.githubusercontent.com/45370942/105423937-b2abc600-5c46-11eb-960e-4bb3c734f33a.jpg)

**Ressources additionnelles**
Ardent défenseur
https://woehead.way-of-elendil.fr/?spell=31852

**Comment by joshwhedon** [comment]
Certains effets et degats passent outre les effets d'invulnerabilite en tout genre. C'est le cas de beaucoup de sorts de la Reine deSang (et a ICC en general).

**Comment by gtschanz** [comment]
![ardentdef](https://user-images.githubusercontent.com/63243193/105475759-05fe3280-5ca0-11eb-9230-d53a7ce6a7e7.PNG)
Bonjour josh; je ne sais pas si son truc à proc avant; MAIS ta réponse est très incorrect; l'ardent def en paladin n'est PAS un effet d'invulnérabilité, il te rend directement un % de vie dès que tes pv passe à 0% après cela ne t'empêche pas de remourrir si t'es PV repasse à 0% dans les 2 minutes qui suivent le proc de ce truc. Comme indiqué dans le talent; Il n'éxiste AUCUN sort ou autre qui permettent d'empêcher l'ardent def de proc en paladin c'est justement une force de ce tank; considérer que cela est inexistant reviendrait à dire que les points de talents mis dans cette partie de la branche protection ne servent à rien, à minima (je n'ai pas testé personellement de mourrir sur la reine de sang avec un paltank) mais si cela est vrai, cela doit être considéré comme un bug et réparé en tant que tel!

**Comment by joshwhedon** [comment]
C'est pas un effet d'invulnerabilite, mais le fonctionnement est similaire a une invulnerabilite / absorption. Et certains effets passent a travers / empeche les procs de ce genre.

**Comment by joshwhedon** [comment]
En gros, si ca a pas proc, c'est qu'il y a une bonne raison, et le log combat ne donne aucune info quant a ce qui a tue Truc Etrange non plus en passant, et si il etait mind control au moment d'un wipe, ce qui l'a tue peut tres bien etre la mechanique qui fait que les joueurs controles par un boss au reset sont tues par le boss automatiquement.

**Comment by gtschanz** [comment]
sur un mind contrôle ok car ça reset le boss si y'a plus de target hostile à la reine; pour ça il faudrait qu'il affiche le détail du recount pour voir la dernière source de dégât qu'il a mangé; @TrucEtrange

**Comment by TrucEtrange** [comment]
Bonjour, 
Pour plus de détails, je n'étais pas mind control. J'étais MT2 avec le miroir de sang sur moi. 
Sur la screen j'ai justement affiché le report de recount sur les dernières secondes de combat.
Ce n'est pas la 1re fois que ça m'arrive, et uniquement lorsque je suis MT2 (jamais en MT1), j'en déduis que les dégâts du miroir de sang n'activent pas ardent défenseur.

**Comment by joshwhedon** [comment]
OK, et le mirroir de sang c'est un cas particulier, et il inflige des degats directs, impossibles a diminuer. Les degats etant scripts, Ardent Defenseur est jamais declenche, tout comme tous les effets qui sont bases de pres ou de loin sur un proc / reduction de degats / etc. Aucun sort / talent / etc ne sera proc par le mirroir de sang.

**Comment by TrucEtrange** [comment]
Ok, merci pour les explications. Désolé pour le dérangement.

**Comment by joshwhedon** [comment]
Pas de soucis, c'est vrai que c'est un comportement bizarre, il y a que quelques sorts dans ce cas la (et la plupart sont pas utilise sur des joueurs mais sur les boss eux meme, genre les jumelle valkyr)
