### ISSUE TITLE
Dame murmemort

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1145]
**Description**
l'autre jour en ICC 10HM (je jouais druid équi) sur la dame murmemort; je fais une reprise d'aggro de 0.5 sec (le temps que le boss envoie un éclair de givre). Mais en aucun cas il me touche en mêlee comme tu pourras le voir dans le logs. Il me fait -39K dégâts et encore j'ai absorbé 8k car il y avait une RG active à ce moment; je trouve ça quand même trop élevé c'était un OS; quand je regarde les dégâts que ce sort devrait normalement faire c'est 7K5 d'après les logs wowhead. Entre 7K5 et 39K+8K absorb il y a un monde (les screen affirmeront mes dires)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): ICC 10 HM
- Boss: Dame murmemort
- Sort en question / Phase du boss en question / Emplacement : Eclair de givre du boss
- Composition du groupe

**Comportement attendu**

-7k5 environ sur l'éclair de givre; OS si mêlee

**Captures d’écran / Vidéos**

![DameHM](https://user-images.githubusercontent.com/63243193/105477813-a81f1a00-5ca2-11eb-99a3-187be18bb4d6.PNG)
![Eclair de givre dame murmemort](https://user-images.githubusercontent.com/63243193/105477838-b10feb80-5ca2-11eb-9308-0cf8e857388b.PNG)

**Comment by gtschanz** [comment]
10K même en absorb* ce qui fait quasi - 50K pv sur un spell boss indiqué à -7K5

**Comment by joshwhedon** [comment]
Les sorts sont pas des sorts script, c'est les donnees client, et le frostbolt : BasePoints = 40950 to 43051
Pour info les sorts de wowhead sont generalement incorrect.

**Comment by joshwhedon** [comment]
PS : celui que j'ai donne c'est le mode normal 10 jours.

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?spell=71420
