### ISSUE TITLE
[Quête] [18] [Jorn Œil-des-cieux] bug mineur

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1146]
La quête [18] [Jorn Œil-des-cieux] est donnée par **Sergra Sombreronce** mais est à priori périmée, la description de la quête donne [18] [[PÉRIMÉ 4].xJorn Œil-des-cieux] .
https://woehead.way-of-elendil.fr/?quest=3261
Elle se valide correctement sur **Jorn Oeil-des-Cieux** et permet de faire la suite, par contre cela fait planter **quest helper**, se qui oblige une déco reco.

**Comment by joshwhedon** [comment]
Elle est pas perimee c'est juste la traduction qui est mauvaise (certaines ont ete ajoutees a partir des donnees cataclysm)

**Comment by joshwhedon** [comment]
Texte corrige prochaine maj

**Comment by Ferro3** [comment]
merci
