### ISSUE TITLE
Rez après une mort dans le tram

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1147]
Bonjour.

Un joueur m'a tué dans la gare du tram coté Ironforge.
Je libère et me retrouve aux Tarides.

Pouvez vous changer l'ange de repop svp, qu'on ne doivent pas prendre le mal de rez.

_Au passage cela m'a couté 75po de réparation et 10mins de mal de rez._

Bon courage.

**Comment by joshwhedon** [comment]
D'apres les sources le point de respawn est suppose etre a la foret d'elwyn. Corrige prochaine maj.

**Comment by Ferro3** [comment]
merci
