### ISSUE TITLE
NPC: Présage

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1148]
**Description**
Omen Entry: 15467.
Moonglade Warden Entry: 11822.

Présage bloqué

**Étapes de reproduction**
- .q a 8868 - .add 21571 50
- .go gam 79997
- se mettre au niveau des gardes du reflet de lune et lancer les chapelets
- les gardes commencent à attaquer les souvenirs de présage
- Présage finit par apparaitre, si Présage tue les gardes avant qu'on joueur ne génère de la menace, celui ci sort du combat et devient inattaquable, juste ciblable

**Comment by joshwhedon** [comment]
Corrige prochaine maj
