### ISSUE TITLE
[Quête] [4] [Vêtements de la spiritualité]

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1149]
La quête ne se valide [4] [Vêtements de la spiritualité] https://woehead.way-of-elendil.fr/?quest=5648
Essayée ce jour avec Ferro (lv80) avec [Soins inférieurs] rang 2 sur **Grunt Kor'ja**, aucun résultat.

Bon courage.

**Comment by Ischjgt** [comment]
La quête est fonctionnelle, il y a 2 sorts à placés.

**Comment by Ferro3** [comment]
Vraiment dsl, j'aurai du mieux lire...
