### ISSUE TITLE
[Quête] [14] [Samophlange] bug

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1150]
La quête [14] [Samophlange], impossible d'actionner les 3 vannes même après un reset serveur
https://woehead.way-of-elendil.fr/?quest=900

Bon courage.

**Comment by Ischjgt** [comment]
La quête est fonctionnelle, vide ton cache stp.
Prefere une requête IG avant de faire un ticket BT pour des quêtes stp, toutes celles qui ont un soucis qui empeche de les réaliser sont à priori déjà repertoriées.

**Comment by Ferro3** [comment]
Suppression du cache, aucun effet, restauration du cache à l'identique, ça marche.
Du coup, surement un problème de cache en effet, désolé, j'aurai dû y penser.
