### ISSUE TITLE
NPC: Witch Doctor Unbagwa - La fièvre de strangleronce

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1151]
**Description**
https://woehead.way-of-elendil.fr/?quest=349
Name: Witch Doctor Unbagwa Entry: 1449.
Il existe un moyen de bloquer le NPC.

**Étapes de reproduction**
- .q a 348 - .add 2799
- .go c id 1449
- Lancer l'event
- Aller chercher les gorilles qui foncent vers le Docteur sans que ce dernier ne prenne l'aggro
- Quand les 3 sont spawns, .gm on/mourir...
=> Les gorilles despawns et le NPC est bloqué. Il continue de cast 12380 [Canalisation de l'ombre] et il est impossible de relancer l'event

**Comment by joshwhedon** [comment]
Fixe prochaine maj
