### ISSUE TITLE
ACCLIMATATION DK FROST

### ISSUE THREAD

**Issue by Elahpascriptelaspeblood** [way-of-elendil/3.3.5#1154]
**Description**
Le talent d'acclimatation augmentant la résistance de l'élément lorsque dk est touché par N'IMPORTE QUEL sort élémentaire (Même les sort du sacré sont sensés s'empiler). C'est l'un des principaux talents de tanking de Frost dk, donnant une diminution linéaire des dégâts pris. Hors ce n'est pas le cas, le talent actuellement marche uniquement sur les dégâts des sorts direct et non sur les DoT par exemple. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe
- Race
- Spécialisation
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
S'empile sur chaque dégât de sort élémentaire pris [y compris les effets d'aoe et d'aura comme la sauterelle sur anub et l'aura de givre sur saph ainsi que les dégâts du sacré pour pvp]

**Captures d’écran / Vidéos**

**Ressources additionnelles**
Je n'ai malheureusement aucune source offi pour appuyer mon BT seulement l'expérience de vieux joueurs jouant sur offi à l'époque. En espérant que ce soit fixé rapidement !

**Comment by Ischjgt** [comment]
C'est super mal dit et super mal écrit. 
Le seul soucis que je vois pour l'instant c'est que ça proc pas sur les Ground AoE Chocs de flammes (L'AoE qui reste au sol, ça proc au premier dégat quand le spell est lancé.) et Consécration.
Le talent proc correctement sur la Mort et décomposition.

Le lien parle des AoE et des Sorts canalisés (qui font proc correctement le talent, à part les 2 spells que j'ai mentionné plus haut), mais pas de DoTs
https://wowwiki.fandom.com/wiki/Acclimation

**Comment by Elahpascriptelaspeblood** [comment]
https://www.dalaran-wow.com/forums/classes/death-knight/topic/389/in-depth-comprehensive-dk-tanking-guide
The Frost tree has one other prominent survival tool: Acclimation. Frostâ€™s unique answer to magic damage is a special sort of buff. Acclimation gives you a 10/20/30% chance when hit by any sort of magic damage to receive a unique buff
any sort
donc les dots aussi

**Comment by Elahpascriptelaspeblood** [comment]
https://github.com/WoWManiaUK/Redemption/issues/2113
un forum aussi ou ils en parlent

**Comment by Elahpascriptelaspeblood** [comment]
euh bah le dot du mage feu le fait pas proc
et c'est aussi classé comme de la magie alors que le proc ne l'est pas, mais que sur l"école du feu

**Comment by Elahpascriptelaspeblood** [comment]
après l'orthographe tu m'excuseras mais c'est pas le sujet ^^

**Comment by Ischjgt** [comment]
Dans le lien github que tu as link  
<img width="945" alt="Capture d’écran 2021-01-26 à 20 33 56" src="https://user-images.githubusercontent.com/60295792/105895473-d93a7a00-6015-11eb-9241-2e5cf9a925af.png">

**Comment by Elahpascriptelaspeblood** [comment]
bah ca dit l'inverse aussi, le but c'est de trouver le bon script et de jouer avec, c'est sensé proc sur all spell sauf ceux indiqués avec les aoe mais les dot sont sensé empilé le talent avec 30% de chance par tick

**Comment by Elahpascriptelaspeblood** [comment]
avec un talent monté à 3/3

**Comment by joshwhedon** [comment]
When you are hit by a spell : la description est claire, c'est quand la cible est touchee par un sort, pas au moment des ticks. Ceci combine avec les donnees clients:   17 Taken magic spell damage , ca signifie donc que seul les sorts directs qui infligent des degats le font procs. Et jusqu'a preuve du contraire (et non ces postes partages ne specifient pas que les dots le proc, dire que c'est le cas c'est extrapoler), le fonctionnement actuel est normal.

**Comment by Elahpascriptelaspeblood** [comment]
lé DoT c pa dé spèl c vré, GO SCRIPT LÉ RED KLASIK VOUS AVÉ RÉZON LÉ MJI

**Comment by Elahpascriptelaspeblood** [comment]
il sert à quoi votre bt déjà?

**Comment by Elahpascriptelaspeblood** [comment]
awiiiiiiiiiiiiiiiiiiiiiiii fer dé remarque et puis apprendre à jouer avec les scripts de merde vue que rien est fixé

**Comment by Ischjgt** [comment]
Salut salut, ton comportement n'est pas innatendu mais n'en reste pas moins déplorable

Tu connais la règle, tu apportes une preuve, sinon c'est pas la peine, surtout que la tu fais fasses à des données clients. Ton ticket est bancal de A à Z, tu link des sources contradictoires et tu prends même pas la peine de faire des recherches, alors que je t'ai à plusieurs reprises rappelé que Josh n'était pas forcément disponible ces temps-ci. Pourquoi tant de hâte ? 

En gros tu nous bouffes du temps pour rien là, y'a déjà pas mal de bug avérés et on a vraiment pas besoin de post de ce genre.

**Comment by joshwhedon** [comment]
Je vois difficilement quel est ton problème. Les informations que je t'ai donné sont, je te signalerai, les mêmes que celles présentes dans le post (qui provient d'un pserv en passant) que tu as partagé, c'est a dire qu'uniquement les sorts qui infligent des dégâts directs proc acclimatation, et que c'est a première vue le comportement normal. Je n'ai pas fermé le bug justement en l'attente d'informations supplémentaires de ta part (vidéos, poste forum, etc) qui iraient dans le sens de ton hypothèse. Dans le cas présent la quasi-totalité des preuves ne vont pas dans le sens de ton hypothèse, qui a la base ne repose que sur un sentiment que "ça marche pas". On ne change pas les comportements des sorts, particulièrement quand ce comportement est basé sur des données client (donc correctes dans 99 pourcents des cas) juste parce que le ressenti est que ça bug désolé.
