### ISSUE TITLE
[Réputation Aile du Néant] Problème Oeufs de Drake

### ISSUE THREAD

**Issue by gomch** [way-of-elendil/3.3.5#1155]
**Description**
Bonjour, depuis quelques temps les oeufs de drake permettant de monter la réputation Aile du néant n'apparaissent plus à leurs emplacements habituels ni dans le délais de pop habituels.

**Étapes de reproduction**
- Campement des Gueules-de-dragon dans la vallée d'Ombrelune
- Quète "La ruée vers les œufs de l'Aile-du-Néant"
- Donnée par Yarzill le Mercenaire

**Comportement attendu**
Depuis mes débuts sur Way of Elendil (2015-2016), les oeufs de l'aile du néant apparaissent toutes les 20 minutes sur une douzaine d'emplacements en surface de la zone de quète, mais depuis quelques mois, il n'y a plus aucun oeuf.
J'ai moi-même farmé ces oeufs plusieurs fois de la même façon sans aucun problème jusqu'à maintenant.
Merci à vous.

**Ressources additionnelles**
https://fr.wowhead.com/item=32506/%C5%93uf-de-laile-du-n%C3%A9ant#comments

**Comment by Endalaust** [comment]
J'ai un doute sur le comportement avancé ici, qui est confirmé par les commentaires wowhead : Il y a un pool de pop (cf https://woehead.way-of-elendil.fr/?object=185915 ) et le repop d'un oeuf semble aléatoire dans la pool. 

Du coup revenir toujours aux mêmes endroits n'a aucun sens ? En revanche après un redémarrage serveur, il est vrai que l'emplacement des oeufs est toujours au même endroit dans la pool, laissant croire qu'il s'agit d'emplacements fixes. 

A mon humble avis, si un vrai bug il y a, c'est à ce niveau : Au redémarrage serveur l'emplacement des oeufs n'est pas aléatoire comme il devrait l'être.

Ce report fait écho à un comportement non fonctionnel de la pool comme presque tous les serveurs privés, et comme woe il y a encore un an avant que le système de pool soit correctement implémenté, impactant tout ce qui est lié aux pools (minerais, plantes, etc...).

**Comment by gomch** [comment]
Désolé d'insister, mais j'aimerai comprendre pourquoi une quète telle que celle du drake de néant, déjà bien longue, a été rendue encore plus fastidieuse ? Le farm des oeufs etait le seule chose positive incitant a monter cette réputation et obtenir une belle monture volante.
En effet, étant un joueur non acharné (j'ai 50 ans et père de famille) je n'ai pas le temps de faire de longs raids pour obtenir une monture hors du commun, et je ne pense pas être le seul dans ce cas.

> Toujours dans les commentaires est notifié une liste précisée "non exhaustive" avec une quantité de coordonnées bien supérieure à la quantité max d'oeufs à dispo (de mémoire 8).
Depuis mes débuts sur WoE j'ai toujours farmé ces oeufs (au nombre de 12 en surface inscrits sur ma map) aux mêmes endroits, et je ne suis pas le seul, j'ai souvent vu d'autres joueurs en faire de même.
Pourquoi ce changement soudain alors que ça n'avait aucun impact sur le reste du jeu ? Les meilleurs joueurs restent meilleurs et les joueurs occasionnels ont droit a une compensation (drake du néant).

> Du coup revenir toujours aux mêmes endroits n'a aucun sens. En revanche après un redémarrage serveur, il est vrai que l'emplacement des oeufs est toujours au même endroit dans la pool, laissant croire qu'il s'agit d'emplacements fixes.
Désolé de te contredire, mais je n'ai jamais attendu un redémarrage serveur pour farmer ces oeufs.

> Ce report fait écho à un comportement non fonctionnel de la pool comme on a l'habitude de le voir sur tous les serveurs privés, et comme woe il y a encore un an avant que le système de pool soit correctement implémenté par TrinityCore, impactant dans le bon sens tout ce qui est lié aux pools (minerais, plantes, etc...).
Je suis d'accord pour le repop aléatoir des plantes, mais depuis mes débuts a wow (2006) aussi bien sur serveur officiel que sur privé, le repop des minerais n'a jamais été aléatoire, l'addon Gatherer a souvent été utile dans ce sens pour se créer des boucles de farming et récupérer les ressources par des milliers de joueurs.

Maintenant, libre à vous de prendre en considération ma requète, juste pour info de nombreux joueurs dans le même cas que moi comptaient sur ces oeufs pour se démarquer un peu, faute de pouvoir accéder au contenu HL du jeu, et ils vont, comme moi, être extrèmement déçus.

Merci de votre attention.

**Comment by Endalaust** [comment]
Je me contente de dire comment c'est censé marcher hein. Si ca a fonctionné autrement pendant des années parque ce que les serveurs privés n'avait pas le niveau de debug suffisant pour avoir un comportement identique à l'officiel, j'y suis pour rien. Et way of elendil non plus, en particulier sur ton sentiment quant au fonctionnement des choses.

**Comment by gomch** [comment]
Mon sentiment est surtout celui qu'on a bridé un attrait du jeu désintéressé des joueurs assidus mais grandement attendu des joueurs comme moi. Le fait qu'il n'y ai pas eu de repport à ce sujet vient peut être que la plupart des joueurs ne convoitent pas cette monture, mais les plus discrets en rêvaient, et c'est dommage de les pénaliser.
J'ai déjà eu une conversation avec un MJ à ce sujet mais j'ai trouvé son comportement plus condescendant à mon égard que constructif.

Maintenant, je sais que ma parole ne compte pas et que je suis un joueur occasionnel insignifiant, mais j'ai effectivement trouvé des listes de coordonnées fixes des oeufs à l'époque de wotlk sur officiel. Malheureusement, les liens concernant ces listes sont morts depuis longtemps et je n'ai aucun moyen de le prouver. Pourtant je ne suis pas le seul a avoir eu ces listes, après, que vaut ma parole face à celle d'un dev ou d'un MJ ?

Je ne veux plus me battre pour ces oeufs, juste signaler que leur mode de repop et leurs emplacements ne dérangeaient personne et apportaient un attrait supplémentaire au jeu. Dommage de les avoir supprimés, parce que, oui, actuellement il n'y a plus rien, si on en trouve 1 toutes les deux heures on peut s'estimer chanceux.

Je crois que de toute façon je ne vous ferais pas changer d'avis, j'espère juste que vous ferez un tour dans la zone afin de vous rendre compte du problème.

Merci.

**Comment by gomch** [comment]
Bon, je viens de me rendre sur place et j'ai constaté que le plus gros du problème a été résolu, certains oeufs on repris leur place en surface (ce qui n'était pas le cas hier).

Merci de m'avoir entendu et bonne journée à vous.

**Comment by Endalaust** [comment]
Entre hier et aujourd'hui il n'y a eu qu'un redémarrage, rapport à ma théorie explicitée précédemment 
Cf la liste des mises à jour de woe : https://way-of-elendil.fr/game/updates 
Ce que tu signales, n'a pas changé entre hier et maintenant

**Comment by gomch** [comment]
Je pensais reporter un bug de quète, mais s'il s'agit d'une décision délibérée, je ne peux pas m'y opposer. Après tout c'est votre serveur, pas le mien.
C'est domage de pénaliser ainsi des joueurs, mais je suis contraint de respecter votre décision.
Comme rien ne changera je crois qu'on peux clore cette discussion stérile.

Merci.

**Comment by Endalaust** [comment]
Mais t'as conscience que je suis pas un dev ou un bugtracker? C'est pas moi qui décide ou qui tranche lol

**Comment by joshwhedon** [comment]
Je confirme les dires d'Endalaust. Pour ces oeufs, comme pour d'autres objets de ce genre, il y a un systeme de pool, c'est a dire que les oeufs spawn a des endroits au hasard. D'un reboot a l'autre, et meme apres qu'un joueur les ait ramasse, un oeuf ne respawnera pas de facon garantie au meme endroit. Il y a actuellement jusqu'a 10 oeufs spawn a la fois, et il y a une quarantaine de points de spawn.
J'ai fait quelques tests, il ne semble pas y avoir de problemes, et ce comportement etait aussi normal sur offi.
