### ISSUE TITLE
Spell : Eveil ancestral

### ISSUE THREAD

**Issue by Malyaa** [way-of-elendil/3.3.5#1158]
**Description**

51558 - [Eveil ancestral, rank 3 frFR]
51557 - [Eveil ancestral, rank 2 frFR]
51556 - [Eveil ancestral, rank 1 frFR]
Double dipping avec les buffs multiplicateurs de heal.
1x en prenant le % de heal soigné, une deuxième fois en fin de calcul

**Comment by joshwhedon** [comment]
Corrige prochaine maj. Notez bien que le correctif concerne les heal donne, pas recu. Les informations concernant le double dipping des heals recues sont peu claires, et rien de concret ne permet de conclure dans un sens ou un autre.
