### ISSUE TITLE
Gob: Nox Portal Plaguewood

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1159]
**Description**
[Nox Portal Plaguewood] GUID: 45739 ID: 181476

Léger problème esthétique avec le spell(?).
Sur les [screenshots](https://fr.wowhead.com/npc=10819/baron-sangreplaie#screenshots) d'un mob à coté, on dirait bien qu'il n'y a pas du tout le cercle vert d'ailleurs donc je sais pas

![Capture d’écran 2021-01-29 à 19 54 07](https://user-images.githubusercontent.com/60295792/106338968-748d5280-6295-11eb-8212-50a3f2805094.png)

**Comment by joshwhedon** [comment]
D'apres la video ca a rien a faire la non plus, je le supprime.
