### ISSUE TITLE
NPC: Croisade écarlate

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1161]
**Description**
Les morts-vivants des maleterres de l'ouest et les NPCs de la croisade écarlate n'ont aucune interaction

![Capture d’écran 2021-01-30 à 01 05 12](https://user-images.githubusercontent.com/60295792/106339551-3b55e200-6297-11eb-9e89-54cd7da2cab9.png)

https://www.youtube.com/watch?v=B0iVQIgX7hg
2:23 on les voit se battre (wow classic)

**Comment by joshwhedon** [comment]
Corrige prochaine maj
