### ISSUE TITLE
[Qête site] Loken

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1162]
Dans les missions journalières du site
**Vaincre Loken** ne fonctionne pas pour moi alors que les autres quêtes fonctionnent

**Comment by Ferro3** [comment]
Donjon fais ce jour en spécifique sur **Newt**

**Comment by joshwhedon** [comment]
Je vais retravailler le systeme de mission pour reduire ce genre de soucis. Plus tard du coup.

**Comment by Ferro3** [comment]
Pas de problème, je signalerai ici les missions journalières du site qui ne fonctionnent pas.

**Vaincre Héraut Volazj** ne fonctionnent pas

**Comment by Endalaust** [comment]
A vrai dire ca ne sert à rien : Toutes les missions marchent, mais parfois pour une raison X ou Y inconnue, la donnée ne remonte pas.

En revanche je profile du fil pour apposer un constat : Si côté site on a 2x la même mission dans notre liste de 3 missions, aucune ne se valide lors de l'accomplissement de la mission. Ce bug est reproductible à 100%
