### ISSUE TITLE
Quest: Les plaines de Nasam - Reservoir abandonné

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1163]
**Description**
Name: Horde Siege Tank Entry: 25334.
Name: Abandoned Fuel Tank Entry: 27064.
11652 - [Les plaines de Nasam] 

Les barils prennent les dégats mais ne donnent pas de mana au tank à leur "mort"

**Comportement attendu**
Je ne sais pas exactement dans quel mesure le tank reçoit le mana

https://www.youtube.com/watch?v=2_YqAxsZvYg&feature=youtu.be
2:50 le tank hit le réservoir mais rien ne se passe (sans le tuer, seul le spell 1 faisant des dégats sur les réservoirs)

https://fr.wowhead.com/quest=11652/les-plaines-de-nasam#english-comments
`Run over barrels to get more energy (mana). `
`Just figured it out... have to hit the fuel drums..`
`Or run over the drum barrels standing all over the field. These restore your mana to the Siege vehicle.`

**Comment by joshwhedon** [comment]
Corrige prochaine maj
