### ISSUE TITLE
Achievement: Panthère onyx

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1166]
**Description**
https://woehead.way-of-elendil.fr/?achievement=3896

Les joueurs ne semblent pas recevoir le tour de force lorsque l'item est envoyé par la poste
Il semble que cela n'arrive que pour cet item

**Étapes de reproduction**

- send items [] "La surprise du chef est servie" "Envoyé via le site internet de Way of Elendil" 48527:1
- utiliser l'item
=> pas de tour de force

//
- .add 48527
- utiliser l'item
=> tour de force

(j'ai essayé avec d'autres compagnons, je n'ai pas ce soucis)

**Comment by joshwhedon** [comment]
Je dirai pas un bug, depuis quand on vend des haut faits en boutique :D

**Comment by Endalaust** [comment]
On vent le pet, il est sur la boutique depuis ... Aussi loin que je m'en souvienne ca doit faire du 2009
