### ISSUE TITLE
Quest: Forger une Alliance

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1167]
**Description**

https://woehead.way-of-elendil.fr/?quest=12924
Actuellement, la quête se valide quand https://woehead.way-of-elendil.fr/?quest=12967 est validée
1. Si le joueur valide Affronter les éléments lorsqu'il est en groupe de raid, Forger une alliance ne se valide pas
2. Si le joueur abandonne et reprend Forger une alliance alors qu'Affronter les éléments est reward, Il ne peut plus valider Forger une alliance

**Comportement attendu**

Aucune idée du comportement attendu mais ils en parlent :
- https://fr.wowhead.com/quest=12924/forger-une-alliance
"idk if this is an known glitch but for me when I talked to him the ? above him was yellow but then the quest window showed it grey so it got me confused. I did the dailies that I had at the time with them and it didnt change it to yellow. Just for the heck of it I clicked on the grey ? and it showed me the rewards and I was able to finish it."

- https://github.com/TrinityCore/TrinityCore/issues/11169

**Comment by joshwhedon** [comment]
1 pas un bug, c'est le comportement normal, et la quete est pas supposee se finir en mode raid.
2 aucune info disponible sur le comportement attendu, donc ... pas un bug mais une feature jusqu'a preuve du contraire.
