### ISSUE TITLE
Boss: Hodir

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#117]
**Description**

Testé en 25,
Pas vu le buff Nuage d'orage apparaitre sur un joueur (testé à 2)
65123 Mode 10 joueurs et 65133 Mode 25 joueurs

**Comportement attendu**
"Used by the Shamans in the Hodir Encounter and crucial to doing hard mode, this move will be cast on an individual and they give the 135% critical damage to up to 4/6 nearby players. It's best to give this to casters as they are generally better at unloading damage onto the boss. Note the individual who gets the Storm Cloud buff WILL NOT get Storm Power."

**Comment by joshwhedon** [comment]
Ok j'ai matte le code et teste, en fait a deux ce sera pas testable. Le serveur utilise de l'aleatoire pour selectionner des joueurs parmis les 10 / 25 joueurs de l'instance, et a 2 ... peu de chance que ca marche :D .
