### ISSUE TITLE
Bug icc Dame et Canonnière

### ISSUE THREAD

**Issue by Speat-Fire** [way-of-elendil/3.3.5#1170]
**Description**
Problème sur les barres d’actions et sors suite à un contrôle mentale (emprise) lancée par la Dame Murmemort durant le combat contre cette dernière. Certains sors des barres d’actions deviennent inutilisables suite a l’emprise.
Problème avec les goules du DK durant le combat sur la cano. Les goules sont inutilisables durant ce « boss » car elle ne peuvent pas rester sur le bateau.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème.
- RAID : ICC
- Niveau de difficulté : Tous
- Boss : Dame murmemort et Bataille de la canonnière
- Sort en question : Emprise

**Comment by joshwhedon** [comment]
Deja signale.
https://github.com/way-of-elendil/3.3.5/issues
