### ISSUE TITLE
Professeur Putricide bug table abomination 

### ISSUE THREAD

**Issue by Briznuits** [way-of-elendil/3.3.5#1171]
Le joueur boit le poison sur la table du professeur chauve  , l'abomination pop mais le joueur n'est pas dedans. 
A noter que comme le joueur n'est pas dedans on ne peut pas le dissipé , en revanche il est possible de dissipé manuellement l'abomination qui est allié cependant elle perd uniquement le buff qui inflige des dégâts au raid et ne disparait pas. 
J'étais également libre de tout mouvement pendant le bug.

Etape de reproduction
Attaque le chauve alors que tu est pas encore dans l'abo tu doit avoir le buff de la table appliquer sur ton perso quand tu le cogne (celui que tu obtient en buvant la table et qui te morph en abo après 5s) 
Perso j'ai claquer un éclat lunaire un peut moin d'une seconde avant la transformation.

![image](https://user-images.githubusercontent.com/69255311/107583270-f5840c80-6bfa-11eb-8258-a24110965e86.png)

**Comment by Ischjgt** [comment]
Il nous faut un moyen pour reproduire à 100%.

**Comment by Briznuits** [comment]
Le bug est survenue en 25hm , 2eme fois que je voit le bug ce produire aucune idée de si le bug arrive dans les autres difficultés , désoler mais je ne peut pas fournir plus d'information et je préfère éviter de reproduire le bug sur le serveur original (je doute que mon raid apprécie le fait de les faires wype)

**Comment by joshwhedon** [comment]
Desole, ce bug ne sera pas corrige a moins de trouver un moyen de le reproduire. Merci de commenter et de demander une reouverture si plus d'information sont trouvees.
