### ISSUE TITLE
Dungeon Finder: Tag en étant déja dans une instance

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1172]
**Description**
Lorsqu'un joueur est dans un donjon, quelque soit le niveau du donjon et qu'il entre dans une instance avec la fonction Dungeon Finder :

1. Si le donjon dans lequel il est, fait parti de la liste des donjons dans lequel il peut rentrer avec l'outil Donjon, il rentrera de nouveau dans l'instance, au début, mais les autres joueurs seront dans une nouvelle ID, lui dans la même. Il sera donc séparé du reste du groupe et dans l'impossibilité de les rejoindre sans chopper le débuff déserteur.
Aussi, je suis pas sur mais j'ai l'impression qu'il y a 100% de chance de retag dans le même donjon où le joueur se situe

2. Dans tous les cas, à la fin de l'instance ou n'importe quel moment en fait, lorsque le joueur quitte le groupe de l'outil donjon, il revient soit je sais pas où (peut etre Tarides/Marche de l'ouest) soit (dans tous les cas où j'ai testé, c'était cette option là), à la position où il était en tagant avec l'outil une fois précédente.

Je vais être plus clair dans les étapes de reproduction

**Étapes de reproduction**
- Joueur A tag avec l'outil donjon à la position A, il finit l'instance et revient à la position A
_______
- Joueur A rentre dans une instance de son niveau à pied, et avance jusqu'à tuer un boss ou quelques mobs histoire de
- Joueur A tag donjon et ça proc direct, il se retrouve groupé avec un groupe sur une nouvelle ID dans la même instance et lui même tout seul dans son instance, revenu au début
- Joueur A quitte le groupe parce qu'il est deg se retrouve à la position A (Quid de s'il n'avait pas fait d'instance au début ? je pense que ça aurait été Marche de l'ouest ou tarides)

**Comportement attendu**
J'ai rien trouvé héhé

1. Ce problème n'arriverait donc que en NM si je ne m'abuse, ou en début des HMs, sans avoir tuer de boss. Reset ID au moment d'entrer ?
Ça réglerait également le soucis des joueurs qui retag direct pour relancer une aléa (pas sur que ce soit toujours là en fait je suis plus à jour de ce côté)

2. Le joueur se fait TP à l'entrée de l'instance (juste avant de prendre le portail pour y être, côté dehors/non instancié on dira) ?

**Comment by joshwhedon** [comment]
Je corrigerai pas ca, surtout sans connaitre le comportement attendu. Si ca se trouve t'es meme pas suppose pouvoir rentrer dans un donjon / tag quand dans un donjon.
