### ISSUE TITLE
Achievement: Appel aux armes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1173]
**Description**
https://woehead.way-of-elendil.fr/?achievement=909
https://woehead.way-of-elendil.fr/?achievement=908

1. Les conditions se valident même s'il n'y a pas assez de joueur. (Il faut qu'une équipe finisse à 1600 ou 3 flags ou boss mort)
EDIT: https://woehead.way-of-elendil.fr/?achievement=783 a également été obtenu de cette façon, est ce que ce serait lié au fait que le tag soit en spécifique ? j'essaie de te dire ça rapidement

2. `You can now simply do random battlegrounds to get this achievement`
_
`We are aware of the situation you reported with the Call to Arms achievement, and our development team is currently working on a solution. There is currently an issue preventing players from receiving credit for this while using the Looking For Battleground feature.`
https://fr.wowhead.com/achievement=908/appel-aux-armes#english-comments

**Comment by Zaralbahk** [comment]
pour avoir testé justement, si le bg ferme, la team en tête ne valide pas le HF,
Par contre on a réussi a la valider en gagnant 1600 vs 50, en allant suffisamment vite pour que le bg ne ferme pas malgré le manque de joueurs (moins de 5 min)

**Comment by Ischjgt** [comment]
J'ai édité le ticket original pour ajouter un second point qui marchait pas bien sur Elendil.

**Comment by joshwhedon** [comment]
Pas compris, ca se valide si y'a pas assez de joueurs ou ca se valide pas ?

**Comment by joshwhedon** [comment]
En fait je comprends pas le bug en general.
