### ISSUE TITLE
Dungeon Finder: Random Lich King Heroic

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1174]
**Description**
Copy/pasta
https://github.com/SunwellTracker/issues/issues/1659 Cc

`Once all lockouts have been obtained, players are no longer able to queue for heroics, either by queuing for Specific Heroic Dungeons or Random Lich King Heroic.`

Sur Elendil, après avoir été tag sur toutes les instances, j'ai le message "Vous ne remplissez pas les conditions d'accès aux donjons sélectionnés." quand je veux lancer l'outil aléa.

**Comportement attendu**

`When queuing for a Specific Heroic Dungeons or Random Lich King Heroic, players should receive a lockout the first time a dungeon is completed each day. Once all lockouts for available heroic dungeons have been obtained, players should no longer be able to queue for Specific Heroic Dungeons but players should remain eligible to queue for Random Lich King Heroic.
`

**Ressources additionnelles**

https://www.tentonhammer.com/guides/instance-guides
`Heroic 5-mans have a 24 hour reset timer that resets at your server reset time each day. So you can only do one of each regular heroic per day, unless you use the LFG random system introduced in 3.3.`

https://www.engadget.com/2009-12-08-patch-3-3-the-dungeon-finder-guide-page-2.html?guce_referrer=aHR0cHM6Ly9naXRodWIuY29tL1N1bndlbGxUcmFja2VyL2lzc3Vlcy9pc3N1ZXMvMTY1OQ&guce_referrer_sig=AQAAALG5wzn4_1LU2IMBCHOb1UWibTIj6S9JPImZ2esTKgyZvEbqj9KezcjmMXS4Jwr2TuRhoHD-hXgBWB3uOAAPUQn_7ws60ee_vizwJ222xjBDpgLtQKQ3zSFXE_uRaxSCugOdJYvQJTbV75aALcZ0gHjCjGofkf3z0HoEWJ9cRcrm
`With random mode on, it will allow you to bypass your normal heroic lockouts. This means if the dice gods are against you, that random dungeon could be one you really don't like. However, the system tries really hard not to do that.`

https://www.bluetracker.gg/wow/topic/eu-en/11824373363-07-12-dungeon-finder-tool-mini-faq/
```
Is it true that players will no longer be saved to heroics? Does this mean players can chain farm heroics for Champion's Seals?
The Heroic lockouts still exist, however the difference is that the random heroic option will ignore any potential lockouts a player might have. 
This means that even if you run every single WotLK heroic dungeon in a day, you can still choose the random heroic option to continue running WotLK heroics that day. 
As mentioned above though, the heroic dungeons you have run the most that day will be the least likely to be randomly selected for your continued play by the dungeon finder system.
```

**Comment by joshwhedon** [comment]
Sera pas corrige, c'est pas un bug que je considere critique, je ne peux pas tester en local, et je veux pas toucher a l'outil donjon a moins que quelque chose de reellement critique soit trouve.
