### ISSUE TITLE
chromaggus BWL (repaire de l'aile noir)

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1175]
Sur chromaggus j'ai constaté 2 choses qui me semblait anormale.

> 1èrement plus ont était, plus ont accumulait de débuff quand on a été 6 joueurs sur chromaggus on a stack 3 débuff d'un coup sur certaines personnes (3 perso étaient entre 60 et 63) quand au 2eme try on les a tué on accumulait plus autant de débuff d'un coup; on accumulait ensuite 1 à la fois et pas 3 à la fois. (génant car dès qu'on a les 5 = CM)

>2èmement par moment on avait un stun de 8à 10 sec sur chaque personne (je ne parle ici pas du débuff jaune qu'on peut cancel avec un sable) mais bien d'un stun de 8 à 10 sec sur chaque joueurs en même temps et souvent sur un enrage du boss; je n'avais pas de souvenir qu'il y avait un 2ème type de stun sur ce boss n'ayant pas trouvé de mention de celui-ci dans les capacités du boss en question

**Comment by Zaralbahk** [comment]
pour le 2iemement, c'est un stun quil fait a chaque changement de couleur, choisi entre 4 habiletés : 
![image](https://user-images.githubusercontent.com/73133549/108596738-3b716b00-7387-11eb-8caf-a88ea813ecde.png)
https://wowclassic.judgehype.com/article/guide-de-chromaggus-au-repaire-de-l-aile-noire/

**Comment by gtschanz** [comment]
certes mais pour revenir à mon propos  " ** stun de 8à 10 sec ** "

**Comment by joshwhedon** [comment]
J'ai eu beau essayer 5 ou 6 fois, et aucun soucis. Et le stun de 8secondes et bel est bien normal. https://woehead.way-of-elendil.fr/?spell=23310

**Comment by joshwhedon** [comment]
Bon je peux pas reproduire, faudra voir si quelqu'un arrive a reproduire.
