### ISSUE TITLE
aura de vindicte

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1177]
**Description**
L'aura de vindicte du paladin proc seulement sur les attaques auto

**Étapes de reproduction**
- ret
- ret
- ret
- aura de vindicte
- pvp pve

**Comportement attendu**
L'Aura de vindicte dois infliger des degats pour chaque degats/techniques  physiques recu  : joueurs, familliers

**Comment by Satarians** [comment]
!

**Comment by Ischjgt** [comment]
Alors juste tu as une preuve ?

**Comment by joshwhedon** [comment]
J'ai trouve aucune info sur le sujet, allant dans un sens ou dans un autre. Mais cela dit il serait assez abuse que ca touche aussi les techniques, parce que par exemple, si une aoe en melee touche toute l'equipe, l'attaquant se prendrait 5 fois (25 fois en raid ?) les degats.
Sans preuve que le comportement actuel est anormal, il est considere comme etant le comportement normal.

**Comment by Satarians** [comment]
** About "Retribution Aura":
https://youtu.be/EMNNNMnRaEg?t=10
0:11 Judgement  fait 192 "Retribution Aura" dmg sur le Hpala (tu peux le voir via les addons)
 
 https://youtu.be/nD2stcm4W8M
3:18 admire le tourbi dans la vindticte, il prend masse dégats, 

 Jt'en met une autre  6:13 gros tourbi sur un ret la tu vois bien les degats de l'aura
 https://www.youtube.com/watch?v=MgmooQsclrs

TADAAA 

attendez j'ai pas fini pck ya le mm bug avec bouclier de  feu et l'épines du drood good luck, si faut des preuves les voici:

** About "Thorns":
1. https://youtu.be/MbCi1xbU-uk?t=59
at 0:58 Judement  135 "Thorns" dmg sur le Hpala (showed by addon)

2. https://youtu.be/OP63cb5cHf0?t=310 (Klinda)
at 14:13 Judgement  150 "Thorns" dmg sur le Hpala

3. https://www.warcraftmovies.com/movieview.php?id=154129
at 14:12 Judgement  54 "Thorns" dmg sur le Hpala (SS: https://i.imgur.com/giL43eH.jpg )

Bouclier de feu
https://youtu.be/rqGBx_lWD_M?t=16
at 0:17 Judgement 26 "Fire Shield" dmg sur le Hpala (showed by addon)

**Comment by Satarians** [comment]
et c'est le but quand un war tourbi sur une gargouille à 9k pv, mon mate, et sa goule, bah le war prend tarifs

**Comment by Satarians** [comment]
https://wowwiki.fandom.com/wiki/Damage_shield 
 
 La ta tout les Damage shield

**Comment by Satarians** [comment]
Damage shields: These have a 100% chance to proc, but can only be triggered by melee attacks. The damage is not considered spell damage.
Reactive procs: These do not necessarily trigger off every attack. However, they are not limited to melee attacks (unless specifically mentioned otherwise). The damage inflicted is considered spell damage.

### **_The damage inflicted is considered spell damage._**

**Comment by joshwhedon** [comment]
Merci. Corrige prochaine maj normalement.
