### ISSUE TITLE
Boss: Hungarfen - Basse-tourbière

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1178]
**Description**

17770 - [Hungarfen] 
31673 - [Spores nauséabondes, rank 1 frFR]

Hungarfen canalise Spores nauséabondes sur lui même et non sur un ennemi

**Comment by joshwhedon** [comment]
https://wow.gamepedia.com/Hungarfen
C'est normal, il se root lui meme, et fait un drain de vie de zone, la strategie c'est que les joueurs doivent s'eloigner pendant le root.
