### ISSUE TITLE
Quest: La purification de l'Orbe d'Orahil et L'exorcisme

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1179]
**Description**
4961 - [La purification de l'Orbe d'Orahil]  
1955 - [L'Exorcisme]  
6546 - [Tabetha] 

Il ne se passe rien après avoir lancé une des quête

**Comportement attendu**
Tabetha sort en disant un dialogue, va dans le potager à sa droite
https://woehead.way-of-elendil.fr/?npc=6549 invoqué
une fois l'invocation faite elle retourne en courant à sa place originelle

https://www.youtube.com/watch?v=MjqzTDQjSWw (classic) - La purification de l'Orbe d'Orahil
Pas trouvé de vidéo pour L'Exorcisme

**Comment by Babyface-187** [comment]
Un peu comme https://github.com/way-of-elendil/3.3.5/issues/1101 ?

**Comment by tomebuddy** [comment]
Bonjour ! J'ai rencontré ce bug hier également.

> Un peu comme #1101 ?

Non, pour le coup il ne se passe vraiment rien. Le compte à rebours de 3 minutes démarre, Tabetha ne fait rien, ne dit rien, ne bouge pas et on ne peut plus interagir avec elle (autrement que pour voir les quêtes déjà en cours). Aucun démon n'est invoqué dans la zone (pourtant on a cherché).

Ce qui fait qu'au bout du compte à rebours la quête échoue.

**Comment by Diubi** [comment]
Bonjour, la quête est toujours buguée.
Dans votre lien, vous indiquez qu'elle est tout de même réalisable, pouvez vous expliquer comment s'il vous plaît?
Merci d'avance

**Comment by Kaasss-woe** [comment]
Correctif appliqué ce jour.
