### ISSUE TITLE
Boss: Hadronox

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1180]
**Description**
28922 - [Ecraseur anub'ar] 
28921 - [Hadronox] 

NM ET HM.

Cas où l'araignée ne remonte pas.
Quand la manip casse le script, je crois qu'elle se remet à grab en envoyant des adds dans le vide comme elle le faisait pour https://github.com/way-of-elendil/3.3.5/issues/692

![Capture d’écran 2021-02-21 à 22 01 14](https://user-images.githubusercontent.com/60295792/108638657-92af3280-7490-11eb-82a9-cf18c8f9ee5a.png)

En tout cas je sais pas si on voit bien mais sur le premier screen, mais le pointeur avec l'épée montre l'araignée en train de voler, elle essaie d'aller chercher des démons des cryptes undermap, qui finissent par la tuer parce qu'elle bouffe pas celui qu'elle a en target

<img width="472" alt="Capture d’écran 2021-02-21 à 22 03 36" src="https://user-images.githubusercontent.com/60295792/108638710-bb372c80-7490-11eb-85d9-407b491754cf.png">

Bref, je m'éparpille un peu.

**Étapes de reproduction**
- Joueur avec familier
- Taper un écraseur anubar
- Envoyer le familier sur Hadronox (attention si le familier meurt, l'anti-cheat proc)
- Quand il a fait un dégat sur Hadronox, tuer un Ecraseur Nérubar
=> Done.

**Comment by joshwhedon** [comment]
On y peut rien faut faire avec.
