### ISSUE TITLE
Quest: La grande aventure de monsieur Toumou

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1182]
**Description**
https://woehead.way-of-elendil.fr/?quest=12027
26588 - [Emilie] 
26589 - [Monsieur Toumou] 

1. Peu de temps après avoir lancé la quête, parfois Monsieur Toumou ne suit plus la fille et reste coincé dans la batisse en bois.
2. Après s'être fait attaquer, Monsieur Toumou ne bouge plus et la fille continue son chemin.
- En restant avec Monsieur Toumou, la fille finit par disparaitre (Pas le lapin, les 2 ne sont d'ailleurs pas synchronisés)
- En restant avec Emilie, Monsieur Toumou finit par mourir. Au moment où la quête devrait finir, Emilie refait demi-tour vers Monsieur Toumou (c'est pas tres clair pour l'instant donc il y aura surement un second ticket)

**Comment by Briznuits** [comment]
https://github.com/way-of-elendil/3.3.5/issues/977
