### ISSUE TITLE
Calcul d'armure incomplet avec le talent résitance (+10% armure) ?

### ISSUE THREAD

**Issue by TrucEtrange** [way-of-elendil/3.3.5#1183]
Bonjour,
Je suis incapable de trouver suffisamment d'informations sur ce sujet pour savoir si c'est bien un bug, mais j'ai remarqué le comportement suivant qui me semble étonnant :

**Description**
L'augmentation d'armure du talent résistance du paladin (+10% d'armure des objets) n'augmente pas la part d'armure bonus des objets avec un bonus d'armure (piliers de puissance, gants et torse t10 pal, etc). 

**Étapes de reproduction**
Une paladin humaine avec Résistance 5/5, et une paladin humaine sans Résistance 5/5, sans buff d'armure ni objets.
Être nu, et regarder son armure (180 grâce à l'agilité en humaine paladin).
Equiper une pièce torse ilvl 264 (donc avec 2641 d'armure)
On a bien 180 + 2641 + 0.1\*2641 = 3085 d'armure.
(Fonctionne avec n'importe quel objet qui n'a pas de bonus à l'armure)
Equiper une pièce torse ilvl 264 avec un bonus d'armure (donc 3831 d'armure)
On a 4275 (180+3831+ 0.1\*2641) d'armure au lieu des 4394 (180 + 3831 + 0.1\*3831) attendus.
(La part bonus d'armure est ignorée par le talent)

**Comportement attendu**
On devrait avoir 4394 d'armure.
Pourquoi le jeu considère-t-il différemment la part d'armure de l'objet, et la part d'armure bonus ? C'est comme si c'était traité comme un enchantement d'armure séparé de l'objet. Exemple avec les gants enchantés +885 armure, le calcul correspond à :
2658 (armure des gants t10 ilvl264) + 0.1\*1650 (10% de l'armure d'un item plaque 264) + 885 (enchant ingé) + 180 (agilité) = 3888

Au lieu de 2658 + 0.1*2658 + 885 + 180 = 3988

**Captures d’écran / Vidéos**
Armure du torse, et tooltip du talent
![image](https://user-images.githubusercontent.com/45370942/108942262-f6835800-7656-11eb-90be-86bd35e15f4e.png)
![image](https://user-images.githubusercontent.com/45370942/108943245-b3c27f80-7658-11eb-966c-0564fe3c5f6a.png)
![image](https://user-images.githubusercontent.com/45370942/108942314-0e5adc00-7657-11eb-9974-ab63306b7507.png)
Armure des gants
![image](https://user-images.githubusercontent.com/45370942/108943213-a73e2700-7658-11eb-8d15-c26b4bf8ddf7.png)

**Comment by joshwhedon** [comment]
Je ne crois pas que les bonus d'armure sont suppose etre pris en compte par ce talent, seul la valeur d'armure des objets, c'est a dire la valeur de base, est supposee etre prise en compte. Merci de fournir des sources indiquant que c'est incorrect.

**Comment by TrucEtrange** [comment]
C'était ma question, je n'arrive pas à trouver d'informations ni dans un sens ni dans l'autre, et le comportement me semblait étonnant.

Merci pour la réponse

**Comment by joshwhedon** [comment]
Bon j'ai continue a chercher, rien trouve allant dans un sens ou un autre (que ce soit a la version actuelle ou en 3,3,5), donc par defaut, a moins que des infos additionnelles soient obtenues, le comportement actuel est le comportement normal. N'hesitez pas a demander une reouverture si des infos supplementaires sont trouvees.
