### ISSUE TITLE
Bug braise vivante halion 25hm

### ISSUE THREAD

**Issue by Briznuits** [way-of-elendil/3.3.5#1184]
Sur Woehead l'inferno ainsi que les braises vivante sont un des rares cas voir unique cas ou le monstre est décris entre parenthèse dans la ligne des dégâts de melée comme faisant des dégâts élémentaire de feu et non physique 

Ce n'est pas le cas en jeux. 

![image](https://user-images.githubusercontent.com/69255311/109396205-c8409980-7930-11eb-93f5-4eeeef28e017.png)
![image](https://user-images.githubusercontent.com/69255311/109396212-cc6cb700-7930-11eb-8c73-55afc968492a.png)

Je trouve pas de source officiel sur internet en parlant et je sait pas ou avoir de source fiable mais si WOEHEAD le dit c'est que ça a déja du être vérifié non?

**Comment by Justforsoloq** [comment]
Après vérification sources offi, les mélées font bien des dégâts de feu 
http://www.worldoflogs.com/reports/az8prrg6r7eii18d/xe/?x=sourceName%3D+%22Living+Ember%22+AND+school+%3D+FIRE

Le "and school = fire" montre bien que toutes les mélées sont comprises dedans, sans compter le fait qu'elles aient des résists quasi chaque coup

**Comment by joshwhedon** [comment]
J'ai verifie et c'est deja le cas.
