### ISSUE TITLE
Dégats de Lana'thel qui ne sont pas sur le journal

### ISSUE THREAD

**Issue by LLPPAA** [way-of-elendil/3.3.5#1185]
Les dégâts du miroir de sang ne sont pas affiché sur le journal de combat, en 25, que ce soit en nm ou hm.

![image](https://user-images.githubusercontent.com/14274351/109718622-d8ae7980-7ba7-11eb-9b94-770e7e466209.png)

(D'ailleurs, c'est aussi le cas des dégâts reçu lors de la mort d'un effondrement d'étoile sur Algalon.)

**Comment by joshwhedon** [comment]
Corrige prochaine maj
