### ISSUE TITLE
Spell: Bombe à sort - Cyclone de plumes - Anzu

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1186]
**Description**
23035 - [Anzu] 

40321 - [Cyclone de plumes] 
40303 - [Bombe à sort, rank 1 frFR]

Les 2 spells en buff au lieu de débuff

0:49 pour la bombe à sort
https://www.youtube.com/watch?v=TdpvoPo69gQ

**Comment by joshwhedon** [comment]
Corrige prochaine maj
