### ISSUE TITLE
Démoniste : sort de captation de vie

### ISSUE THREAD

**Issue by Gde01** [way-of-elendil/3.3.5#1187]
**Description**
Le sort de captation de vie décompte 3x plus de points de vie qu'il ne le devrait à mon démoniste. Au niveau 2, il est censé coûter 10 pv par seconde et je voit bien les 10 qui défilent mais sur la barre de vie, on voit qu'il en décompte 30 à chaque seconde.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe Démonsite
- Race
- Spécialisation
- Sort / Talent / Etc Captation de vie
- Circonstances (Donjon, Raid, PvP, autre) Toujours
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Ischjgt** [comment]
J'ai peut-etre mal compris mais non c'est bien 10. Je fais un autre ticket pour 2 autres soucis que j'ai constaté.
<img width="306" alt="Capture d’écran 2021-03-05 à 11 01 10" src="https://user-images.githubusercontent.com/60295792/110100025-3e665580-7da2-11eb-8687-09357f14fde8.png">
