### ISSUE TITLE
Spell: Captation de vie

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1188]
**Description**
755 - [Captation de vie, rank 1 frFR] 
3698 - [Captation de vie, rank 2 frFR]
3699 - [Captation de vie, rank 3 frFR] 
3700 - [Captation de vie, rank 4 frFR] 
11693 - [Captation de vie, rank 5 frFR]
11694 - [Captation de vie, rank 6 frFR] 
11695 - [Captation de vie, rank 7 frFR] 
27259 - [Captation de vie, rank 8 frFR]
47856 - [Captation de vie, rank 9 frFR]

Dans l'intitulé du spell il est écrit "X Vie, plus Y par seconde". Au lancement du sort, il n'y a pas de pénalité de point de vie subit, le X n'est pas présent.

**Comment by joshwhedon** [comment]
Hein ?

**Comment by Ischjgt** [comment]
https://woehead.way-of-elendil.fr/?spell=47856
Sur le tooltip il y a marqué 

"277 Vie, plus 182 par seconde"

il n'y a pas le 277 actuellement

**Comment by joshwhedon** [comment]
Si, ca apparait pas dans le log mais les degats sont bien subis.
