### ISSUE TITLE
Spell: Captation de vie améliorée

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1189]
**Description**
18703 - [Captation de vie améliorée, rank 1 frFR] 
18704 - [Captation de vie améliorée, rank 2 frFR] 

Le talent n'augmente pas correctement les soins sur le démon
=> Diablotin lvl 80 Rang max du sort
0/2 1962 PV rendus
1/2 2014 PV rendus
2/2 2064 PV rendus (ça devrait être 2354)

**Comment by joshwhedon** [comment]
L'amelioration s'applique sur les soins de base du sort, pas sur les soins totaux. Du coup pour le cas du sort rang 9, les soints de base etant 520 
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 520  Multiple = 2.50
On ajoute 10% ou 20% a ca, et ensuite on applique les bonus supplementaires. De ce fait, c'est pas 1962 + 20% de 1962.
