### ISSUE TITLE
[PNJ movement Dalaran] Visiteur de dalaran vole en marchant

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#119]
**Description**
https://woehead.way-of-elendil.fr/?search=Visiteur+de+dalaran

Les PNJs arrivent sur l'aire de Krasus en monture, quand la monture depop et qu'ils marchent vers l'entrée, ils se retrouvent à voler au lieu de marcher

Bug cosmétique.

**Comportement attendu**
Le PNJ doit marcher

**Captures d’écran / Vidéos**

<img width="1500" alt="screenshot_598" src="https://user-images.githubusercontent.com/1420867/78425064-47badf80-7672-11ea-836f-6fd7348fc2a0.png">

**Comment by Killyana** [comment]
Je peux rien faire pour ca, SMART_ACTION_SET_CAN_FLY et SMART_ACTION_SET_DISABLE_GRAVITY ne fonctionne pas correctement

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19921

**Comment by joshwhedon** [comment]
Heu je pense pas que ce soit l'action qui marche pas. Le npc a UNIT_FLAG_SWIMMING, c'est ce qui donne le visuel. Si dans le smart_script tu retire ce flag a l'arrivee, ca marchera.

**Comment by Killyana** [comment]
J'ai retiré le flag mais sa change rien, ce flag n'a d'effet quand dans l'eau.

**Comment by Killyana** [comment]
@joshwhedon Il faut peut être ajouter bool needsFalling=true quand SMART_ACTION_SET_CAN_FLY=0 ou SMART_ACTION_SET_DISABLE_GRAVITY=0  ?

**Comment by Killyana** [comment]
Fixé prochaine maj.
