### ISSUE TITLE
Event: Foire de sombrelune

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1190]
**Description**
Au jour d'aujourd'hui la foire de sombrelune n'est plus présente
https://woehead.way-of-elendil.fr/?event=4

Et au jour d'aujourd'hui d'après Woehead elle était censé l'être
<img width="281" alt="Capture d’écran 2021-03-05 à 15 40 56" src="https://user-images.githubusercontent.com/60295792/110131373-5eaa0a80-7dca-11eb-983d-6daaeebe5fd6.png">

https://wowwiki-archive.fandom.com/wiki/Darkmoon_Faire
Sur le lien, les events commençaient le dimanche à 00h et finissaient le Samedi d'après à 23h59

**Comment by joshwhedon** [comment]
Tu peux verifier si le probleme est pas juste une question d'heure d'ete ?
