### ISSUE TITLE
Quête, bug mineur : [75] [Une puissance latente] utilisation de l'objet de quête

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1192]
[75] [Une puissance latente] https://woehead.way-of-elendil.fr/?quest=12094
L'objet [Eclat de Gavrock] https://woehead.way-of-elendil.fr/?item=36787

L'objectif de quête est validé au début de la canalisation de l'objet de quête sur les pierres et non à la fin de la canalisation.

Bon courage.

**Comment by joshwhedon** [comment]
Trop chiant a corriger pour le peu de valeur que ca apporte.
