### ISSUE TITLE
Donjon Ahn'kahet : l'Ancien royaume boss Jedoga Cherchelombre

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1194]
Ahn'kahet : l'Ancien royaume https://woehead.way-of-elendil.fr/?zone=4494
Lors du boss Jedoga Cherchelombre (la dame aux adds) https://woehead.way-of-elendil.fr/?npc=29310 en **version normale** des packs de mobs sont pull aux envols, se qui complique _un peu_ le déroulement du combat :D

Le contre consiste à nettoyer toutes les packs avant de faire ce boss.

Pouvez vous vérifier, ou fixer ce problème svp

D'avance merci.

**Comment by joshwhedon** [comment]
De ceque je vois dans les videos que je trouve, les joueurs tuent les packs avant d'engager le boss. Donc ca a l'air d'etre le comportement normal.

**Comment by Ferro3** [comment]
je vais reformuler, il y a confusion entre les mobs qui apparaissent pour le boss et les packs de mobs qui sont au pied des escaliers.

lors de l'envol pull du boss (en normal) un ou plusieurs des packs, qui initialement se trouvent au pied de l'escalier (et non ceux de la plateforme), qui n'ont rien a voir avec le boss sont pull.
ces mobs traversent le décor et en général tuent le healer.

donc rien à voir avec les mobs invoqué pour l'event du sur la plateforme.

**Comment by Ferro3** [comment]
donjon refait plusieurs fois, sans le soucis

je pense au pass finding d'un pet qui a du nous aggro une partie des mobs, vu qu'il y a un escalier ça ne serait pas surprenant que un pet passe par un détour pour monter et du coup ramasse des mobs sur le chemin
