### ISSUE TITLE
!

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1197]
!

**Comment by joshwhedon** [comment]
A supprimer ?

**Comment by Satarians** [comment]
on peut la lancer sous strangu, les coils de dk sur reflect heal le lanceur aussi sans changeliche

**Comment by Ischjgt** [comment]
Refait un ticket clair et précis stp.
Avec un titre clair et précis.
Avec un descriptif clair et précis.

Je ne doute en rien de tes capacités à nous révéler un bug, le but du jeu est de facilité la tâche pour Josh. Pas qu'il est à essayer de deviner tes énigmes.

**Comment by Satarians** [comment]
Ok Pardon


La marque desang du dk sang
Peut se lancer en étant silence

Le Voiles mortel du dk toutes spé, envoyé dans un renvoie de sort, Heal le dk ( le lanceur qui se renvoie le voile, sans etre sous changeliche se heal)

**Comment by Ischjgt** [comment]
Il faut refaire un ticket pour chaque soucis rencontré, et besoin d'une preuve pour la marque de sang.

**Comment by Ischjgt** [comment]
Me charge du coil.

**Comment by joshwhedon** [comment]
C'est pas un sort donc pourquoi en etant silence ca marcherait pas ?
Quant au voile mortel, une preuve du comportement normal ?

**Comment by joshwhedon** [comment]
Dans le cas d'un renvoi de sort, le lanceur de sort reste le meme, donc il y a aucune raison que le lanceur de sort ne se soigne pas.

**Comment by joshwhedon** [comment]
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)

Marque de sang, cote client, le silence l'empeche pas.

**Comment by Satarians** [comment]
le soirt ne soigne que les mort vivant, et via un reflect le dk est considéré comme tel

**Comment by joshwhedon** [comment]
Ha pardon je lisais le voile mortel du demoniste.
