### ISSUE TITLE
Spell: Voile mortel et Renvoi de sort

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1198]
**Description**

47541 - [Voile mortel, rank 1 frFR] 
49892 - [Voile mortel, rank 2 frFR] 
49893 - [Voile mortel, rank 3 frFR] 
49894 - [Voile mortel, rank 4 frFR] 
49895 - [Voile mortel, rank 5 frFR] 

Les voiles mortels renvoyés (par joueur ou NPC) rendent de la vie au DK comme s'il était un mort-vivant.

**Comportement attendu**

Rend de la vie que s'il est mort-vivant
https://github.com/WoWManiaUK/Redemption/issues/3011

**Comment by joshwhedon** [comment]
Corrige prochaine maj

**Comment by Satarians** [comment]
super mais mtnt le dk ne peux plus se heal sous changeliche

**Comment by Satarians** [comment]
et le reflect du voile mortel ne marche pas :')

**Comment by Satarians** [comment]
ca fait rien du tout
