### ISSUE TITLE
Spell: Insanité - Héraut Volazj

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1199]
**Description**
57508 - [Insanité, rank 1 frFR] 

29311 - [Héraut Volazj] 

1. Il semblerait que les joueurs puissent actuellement résister au sort Insanité, je me suis retrouvé plusieurs fois sans le débuff après son incantation. 
Pas trop trouver d'infos là dessus, mais ça peut faire bloquer le boss.

2. Insanité aurait une durée d'1 minute 30 normalement, il dure indéfiniment ici
```
That's true what some people said, insanity has a certain time before it's removed. the first time i did it i Freaked out as i was attacked by my group but if you can survive 1:30 minutes, the clones will Despawn and the fight will continue ...
I was a DK with 31k health so surviving was not an issue really
```
`Insanity can time out. If you can live long enough, the shades will disappear on their own, allowing you to get back on the boss. Difficult for a non-healing class though, as it does take a while.`
https://fr.wowhead.com/npc=29311/h%C3%A9raut-volazj#english-comments

Ce sont des commentaires de la 3.0.X

3. Les clones reçoivent l'arme des joueurs, si les joueurs enlèvent leur armes avant l'insanité, les clones n'ont pas d'armes.
https://www.youtube.com/watch?v=7rGiqUQwPUY
On peut voir facilement que l'arme du chaman à 35 secondes est la meme que le clone a à 1:23
`One thing, I think unequipping your weapons does create much less powerful clones. Most of the clones abilities require weapons in the main or ranged weapon slot, a rogue without his daggers is just another sissy slapfighting you.`
https://fr.wowhead.com/npc=29311/h%C3%A9raut-volazj#english-comments
commentaire de la 3.0.3

**Comment by joshwhedon** [comment]
Corrige prochaine maj
