### ISSUE TITLE
[PNJ movement] Garde-paix d'argents volent en marchant

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#120]
**Description**
Le trio garde paix + Arelas Brillétoile sont sur des griffons et volent dans Dalaran
Problème : Les griffons marchent en volant

https://woehead.way-of-elendil.fr/?npc=35587
https://woehead.way-of-elendil.fr/?npc=35604

Bug cosmétique

**Comment by Killyana** [comment]
Je peux pas reproduire tous volent, j'ai corrigé le fait qu'ils ne sont pas linké à leur events.
Sur le serveur prod j'ai delete le mouvement de vole donc il faut peut être vider le cache du client.
