### ISSUE TITLE
disarm piège de chasseur en fufu

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1201]
![PIEGE DISARM ALED](https://user-images.githubusercontent.com/63243193/110879944-229d0b00-82de-11eb-8aa7-6e4c08057797.PNG)
on arrive plus à disarm les pièges de chasseur en voleur en étant camouflé et proche du piège existe-t-il une raison à ça ? c'est pas un comportement blizzlike normal ça

**Comment by joshwhedon** [comment]
T'as le skill pour ?

**Comment by gtschanz** [comment]
bah si le serveur d'ici me le permet pas de base ça n'a rien à voir avec du skill alors; c'est juste que ça devrait être possible à faire

**Comment by joshwhedon** [comment]
Il y a que les voleurs qui peuvent si je me souviens bien, vu que ce sont les seuls qui ont l'aptitude de desarmement de piege.

**Comment by gtschanz** [comment]
sur le screen je suis sur un voleur et je te dis que actuellement c'est impossible pour preuve prend un fufu duel toi sur un chasseur go vanish avec le fufu pose le piège avec le chasseur et ... TADAAA tu pourras pas le disarm

**Comment by gtschanz** [comment]
on est 2 fufu à avoir ce problème et on l'a testé sur 2 chasseur différent

**Comment by gtschanz** [comment]
en pve bizarrement ça marche les traps de icc; mais c'est nouveau que ça ne marche plus dans une situation pvp

**Comment by joshwhedon** [comment]
Et t'as teste en dehors de duels ? Dans une vrai situation pvp ?

**Comment by gtschanz** [comment]
en arène j'ai pas testé et en bg j'ai vu le même soucis

**Comment by gtschanz** [comment]
et puis même le duel est une vrai situation pvp malgré tout hein xd

**Comment by joshwhedon** [comment]
Non ca l'est pas, parce que c'est une situation pvp entre deux joueurs de la meme faction. Donc le fonctionnement est different

**Comment by joshwhedon** [comment]
Je viens de tester et meme en duel je l'ai. Donc je te demanderai, dans tes techniques, estque que tu as la technique subtilite : desarmer un piege.

**Comment by gtschanz** [comment]
je viens de tester il faut cliquer sur la compétence puis sur le piège pour que ça marche; avant cliquer sur le piège ça suffisait du coup c'est un comportement normal ? (vu que dans des instances il suffit de cliquer sur le piège pour le disarmer) style icc / bwl /...

**Comment by gtschanz** [comment]
on vient de test dans une situation avec un fufu de la faction opposé et chasseur de la faction opposé

**Comment by joshwhedon** [comment]
Heu, je peux cliquer sur le piege moi et ca marche, et ca affiche desarmer en vert. J'ai teste avec 2 joueurs de la meme faction parce que c'est generalement ce qui pose probleme. Tu as des addons foireux ? Ou peut etre la version HD ?
Pour les donjons, tous les pieges ne requierent pas la competences (mais certains oui)

**Comment by gtschanz** [comment]
j'ai pas d'addon foireux à ma connaissance (j'ai pris pr ce que j'ai sur le site); je joue pas en hd; et 2 autres fufu ont le même soucis que moi; ça marche au final le spell mais on doit chaque fois cliquer sur le spell puis sélectionner le piège sinon il reste affiché en rouge (on vient de test au joug d'hiver avec un chasseur a2 qui est venu nous poser les pièges on est h2 sur les fufus

**Comment by joshwhedon** [comment]
Ouai mais ca devrait pas etre necessaire. Ca le fait pour tous les pieges ? Vous pouvez faire un sondage parmis les autres joueurs pour voir si ca concerne tout le monde ? Parce que moi ca me laisse bien cliquer dessus.

**Comment by gtschanz** [comment]
ça le fait avec tout les traps pour moi; je vais mp tout ceux qui ont un fufu demain pour qu'ils aillent test avec moi

**Comment by joshwhedon** [comment]
C'est vraiment bizarre. Ca te l'a toujours fait ? Ou ca a commence recemment ?

**Comment by gtschanz** [comment]
commencé récemment; bah on était vocal quand il me l'a dit, je lui ai dis c'est pas possible ça me le fait pas; j'suis allé testé et bah au final si..

**Comment by Justforsoloq** [comment]
Perso ayant un rogue je n'ai pas ce bug. Après j'ai déjà entendu le fait qu'un rogue avait ce soucis, mais je peux pas relate :x

**Comment by Ischjgt** [comment]
Coucou, @joshwhedon 
https://github.com/way-of-elendil/3.3.5/issues/812 Je t'avais donné quelques infos ici et sur Discord mais je retrouve plus la conv B) .

**Comment by joshwhedon** [comment]
Je mets un correctif a voir si ca regle le probleme.
