### ISSUE TITLE
Bug quête de vote Halion

### ISSUE THREAD

**Issue by Mortekouye** [way-of-elendil/3.3.5#1202]
Bonjour , dans mes missions hebdo j'ai "vaincre Halion". 
Je l'ai fait hier en 25 nm et ça n'a pas été validé sur le site. 
Bonne journée 
![Capture d’écran 2021-03-16 073119](https://user-images.githubusercontent.com/66107384/111272091-68d1d180-8632-11eb-96bb-692318165c2d.png)
![Capture d’écran 2021-03-16 083352](https://user-images.githubusercontent.com/66107384/111272103-6bccc200-8632-11eb-8c8b-ebdcc1a7a0e0.png)

**Comment by Belore** [comment]
Bonjour, pour appuyer ce ticket j'ai eu le même souci il y a deux semaines mentionné ici :
https://discord.com/channels/280446236035776512/488586498942173194/816341271358472212
Et je l'ai à nouveau cette semaine, où le premier Halion fait mercredi 10 à 19h25 a bien été compté dans la quête de site, mais les deux suivants (dimanche 14 à 17h55 et lundi 15 à 20h45) n'ont pas été pris en compte.

**Comment by joshwhedon** [comment]
Ca arrive, malheureusement ca ne sera pas corrige dans l'immediat.
