### ISSUE TITLE
Phase de Deuillegivre sur Le roi liche en Heroïque 

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1203]
**Description**
Lors de la phase de deuillegivre, certaines classes sont suceptibles de passer sous la map pour cause de changement d'êtat (ice block, demorph (druid)), empechant donc les équi/druid feral d'assist heal ou meme d'innervation lors de cette phase qui y est pourtant propice.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Citadelle de la couronne de glace
- Heroïque 10 et 25
- Roi liche
- Deuillegivre
- Avoir un druide dans le groupe

**Comportement attendu**
Le druide devrait rester sur le sol et pouvoir demorph/remorph comme il veut sans passer sous la carte.

**Ressources additionnelles**
https://www.youtube.com/watch?v=PWIvZQxUrHc

Vidéo d'officiel de 3.3.5, à 2minutes et 40secondes le druide en deuillegivre passe de la forme de félin à sa forme de tauren et reste avec ton raid. (on le voit sur son portrait qu'il demorph)

**Comment by joshwhedon** [comment]
Deja signale, on y peut malheureusement rien.

**Comment by Ferro3** [comment]
lien vidéo à 2mins 31sec https://www.youtube.com/watch?v=PWIvZQxUrHc&t=151s (entrée en deuille)
