### ISSUE TITLE
Peste Déliée / Putricide

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1206]
**Description**
La peste déliée ne fait pas dé dégats, ou très infimes, également la résistance à l'ombre est appliqué à la peste alors qu'elle ne devrait pas

**Étapes de reproduction**
- Citadelle de la couronne de glace
- Heroique 10 et 25 et normal 25
- Professeur Putricide
- Peste déliée

**Comportement attendu**
La peste est un sort qui est censé faire beaucoup de dégats que l'on doit transmettre à ses teammates différents car cela applique un débuff qui augmente les dégats de cette dernière également.

**Captures d’écran / Vidéos**
![image](https://user-images.githubusercontent.com/65713751/111635159-800dec00-87f7-11eb-9aef-d3f117bc0634.png)
(Officiel en 25 NORMAL MODE (avec un prêtre dans le groupe pour la resistance, voyez qu'il n'y a aucune resistance)

![image](https://user-images.githubusercontent.com/65713751/111635300-a6cc2280-87f7-11eb-9922-91a804412080.png)
(Elendil en 10 HEROIQUE MODE (avec des resistances, des degats très négligeables au début (sur le screen karuz comme a prendre des degats au bout du 8eme stack avec le debuff (vu qu'il avait déjà été contaminé avant))

Liens des logs en question : http://www.worldoflogs.com/reports/dcw8kaumkt53n8j6/log/ Officiel
http://www.worldoflogs.com/reports/li4fd7jabtswxtk8/log/  Elendil

**Ressources additionnelles**
https://fr.wowhead.com/spell=70911/peste-d%C3%A9li%C3%A9e#english-comments

**Comment by Ischjgt** [comment]
J'avais vérifié de mon coté. Les dégats sont corrects et la peste peut se faire résister, va falloir des preuves stp.

**Comment by Wilpok** [comment]
Eh bien il suffit re regarder les logs, en nm sur officiel  les dégats commencent à 960, et en hm sur elendil cela commence à 136, je ne sais pas ce qu'il vous faut comme preuves supplémentaires, on voit également que sur certains ticks il n'y a pas de scaling.

**Comment by gtschanz** [comment]
bah ça dépend si t'avais déjà un spell de rési nature actif ça me paraitrait pas si choquant au final dans ce cas

**Comment by Wilpok** [comment]
Non pas de rési nature de posés

![image](https://user-images.githubusercontent.com/65713751/111637377-a6cd2200-87f9-11eb-911c-b1b68b43df53.png)
log 10h sur retail, mb pour les dégats initiaux ils sont juste plus bas sur elendil et le scaling foire mais btw toujours pas de résist

**Comment by Ischjgt** [comment]
10h premier tick à 230 https://www.youtube.com/watch?v=MyXBFH0jm1s
ce qui correspond à Elendil, avec la resist

J'avais trouvé semblable à Elendil également en 25Hm sur cette vidéo mais flemme là
https://www.youtube.com/watch?v=CXl5DozLhi0

**Comment by Wilpok** [comment]
Bah regarde la vidéo par toi même et les dégats pris en suivant le 1er tick, tu ne vois pas le problème? au bout de 4ticks il est à 2k+, sur elendil a 400. ça rend ridicule l'abilité non?

**Comment by Ischjgt** [comment]
10hm
Ischjgt reçoit 129 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(55 résisté)
Ischjgt reçoit 129 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(55 résisté)
Ischjgt reçoit 148 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(36 résisté)
Ischjgt reçoit 295 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(73 résisté)
Ischjgt reçoit 442 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(110 résisté)
Ischjgt reçoit 497 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(55 résisté)
Ischjgt reçoit 516 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(220 résisté)
Ischjgt reçoit 736 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(184 résisté)
Ischjgt reçoit 902 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(386 résisté)
Ischjgt reçoit 1160 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(496 résisté)
Ischjgt reçoit 1417 (Ombre) de dégâts |2 Peste déliée |2 Professeur Putricide.(607 résisté)

OK my bad, les ticks n°2 et 3 ont un soucis, pour le reste le scaling est relativement ok (2K au 9eme tick, si on ignore les 2 premiers et 1k5 sur ton log retail)

le même probleme du tick n°2 et 3 est présent en 25Hm également

**Comment by Wilpok** [comment]
Tu avais une rési nature ou ombre sur le pull?

**Comment by gtschanz** [comment]
la rési nature doit être pris en compte, pas la rési ombre

**Comment by joshwhedon** [comment]
Je confirme c'est resistance a l'ombre.

**Comment by joshwhedon** [comment]
Corrige prochaine maj

**Comment by Wilpok** [comment]
Possible de réouvrir le ticket pour enlever la résist ombre stp Josh? ^^

![image](https://user-images.githubusercontent.com/65713751/111755703-ad12db00-8899-11eb-8954-57d1239a4435.png)

Sur offi ils étaient sous aura de rési ombre du paladin et aucun resist comptée dans les logs, (peut être d'ailleurs cela influe sur le scaling ? sachant que la plague est censé prendre 25% degats à chaque tick)

**Comment by joshwhedon** [comment]
Oui oui la resi ombre sera enlevee aussi, j'ai corrige les 2 en meme temps,
