### ISSUE TITLE
Bouclier D'eau proc pas sur les spells/aoe

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1208]
**Description**
Le bouclier d'eau proc pas sur les spells/aoe

**Étapes de reproduction**

- Chaman
- Bouclier d'eau

**Comportement attendu**
1stack de bouclier d'eau devrait être consommé lors de sorts lancés sur le shama (comme l'infester du roi liche par exemple, ça le fait pas sur elendil) ce qui rend le rsham bien nerf sur la regen mana

**Ressources additionnelles**
https://www.youtube.com/watch?v=z5N9WWfMP-E

16sec 1er infest 1 stack du shield part.

En lien avec : https://github.com/way-of-elendil/3.3.5/issues/1207

**Comment by Wilpok** [comment]
![image](https://user-images.githubusercontent.com/65713751/111663541-3500d280-8811-11eb-9ecb-2779fcd91fa0.png)

Ne proc pas sur tous les infest (1 sur tous ), alors que c'est censé être le cas, pareil pour la transi sur douleur et souffrance etc...

Edit : Proc bien sur les sorts mono lancés (en pvp du moins)

**Comment by joshwhedon** [comment]
Comme beaucoup de sorts, le bouclier d'eau a un cooldown et du coup ne proc pas sur tous les sorts / attaques.
Dasn el cas du bouclier d'eau, le cooldown est de 3secondes.

https://wowwiki-archive.fandom.com/wiki/Water_Shield
Water Shield can only proc every few seconds and has three charges.

**Comment by Wilpok** [comment]
Oui je sais sauf que la c'est pas le cas il ne proc jamais, les proc que tu vois sur les logs sont les procs du talent quand tu crit sur les heals et non sur des proc de water shield (qui n'enclenche pas cet icd d'ailleurs)

**Comment by Wilpok** [comment]
Aucun rapport donc, et aucune raison de fermer le ticket

**Comment by joshwhedon** [comment]
Je regarde avec plus de details ce soir en rentrant.

**Comment by Wilpok** [comment]
(comme tu peux voir des procs a moins d'1sec d'intervalle à 22:14:30 et 22:15:50

**Comment by joshwhedon** [comment]
Corrige prochaine maj
