### ISSUE TITLE
Les Gardes de l'ombre Valkyr en l'air target des mauvaises cibles

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1209]
**Description**
sur le roi liche heroique les valkyr en l'air (après 50%) se focus sur les totems des shaman alors qu'ils ne sont pas censés être focus

**Étapes de reproduction**
- ICC
- 10HM / 25HM
- Roi Liche
- Siphon de vie

**Comportement attendu**
Les valkyr focus les joueurs et non les totems (qui les focus dès leur pose et donc fait consommer ENORMEMENT de mana aux chamans pour les reposer)

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.
![image](https://user-images.githubusercontent.com/65713751/111666482-0afcdf80-8814-11eb-97bf-366367f032dd.png)

Log elendil

**Ressources additionnelles**
https://www.youtube.com/watch?v=vEnvIwb3wYw

Vidéo 3.3.5 les Totems ne se font pas focus 1 seule fois

**Comment by joshwhedon** [comment]
Corrige prochaine maj
