### ISSUE TITLE
[ICC] PNJs amicaux qui n'attaquent pas

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#121]
**Description**
https://woehead.way-of-elendil.fr/?npc=37123
https://woehead.way-of-elendil.fr/?npc=37122
https://woehead.way-of-elendil.fr/?npc=37124
https://woehead.way-of-elendil.fr/?npc=37125

Ces 4 PNJs suivent Crok (https://woehead.way-of-elendil.fr/?npc=37129) dans l'aile de givre. Cependant ces 4 PNJs se contentent de le suivre et n'attaquent personne (contrairement à Crok)

**Comment by Killyana** [comment]
Ceci fix l'assiste, par contre Crock n'attaque pas Svalna quand elle devient attaquable:
``` sql
DELETE FROM `creature_formations` WHERE `memberGUID` IN (151767,151761,151762,151763,151764);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES 
(151767,151767,0, 0, 3, 0, 0),
(151767,151761,0, 0, 3, 0, 0),
(151767,151762,0, 0, 3, 0, 0),
(151767,151763,0, 0, 3, 0, 0),
(151767,151764,0, 0, 3, 0, 0);
