### ISSUE TITLE
Le bonus de Glyphe de totem de courroux persiste après un changement de spé

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#1210]
**Description**
Le bonus de Glyphe de totem de courroux persiste après un changement de spé (le bonus qui dure 5min)

**Étapes de reproduction**
- En spé élèm avec le glyphe de totem de courroux, poser un totem de courroux.
- Changer de spécialisation
- Le buff reste et donne un bonus de 84ps
- On peut enlever le buff, et on perd les 84ps

Pas trouvé de preuves que c'est un bug, mais vu que personne ne le mentionne comme une astuce, je me suis dis que c'était pas normal

**Comment by joshwhedon** [comment]
Ce serait un buff de quelques secondes, ce serait probablement pas retire. Mais c'est un buff de 5 minutes, et dans les autres glyphe il est retire. Donc je retire aussi.
