### ISSUE TITLE
Les Aoe sur les Betes de Sang de Saurcroc

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1211]
**Description**
Les Bêtes de Sang sur saurcroc prennent trop de degats des "coups d'allonge" qui sont normalement des AoE et donc devraient être réduits de 95% via https://www.wowhead.com/spell=72723/resistant-skin

**Étapes de reproduction**

- ICC
- 10N/HC 25N/HC
- Porte Mort Saurcroc
- Bêtes de sang

**Comportement attendu**
Le Cleave des guerriers, le sceau d'autorité des paladins

**Captures d’écran / Vidéos**

SUR ELENDIL JOSH CE REPORT >>>>>>

![image](https://user-images.githubusercontent.com/65713751/111769180-2e259e80-88a9-11eb-8f25-dcbed655f44b.png)

Les wars cleavent fort, le sceau d'autorité (pas présent sur ce report car ils l'ont pas fait) tape egalement, les degats sont bien réduits pour consecration et tempete divine, pluie de feu...

**Ressources additionnelles**
J'peux montrer que aucun war sur retail ne cleave, aucun druide ne balayage aucun paladin de sceau d'auto, sinon y'a ça également,
"Cleave is an Arms Warrior AoE ability learned at level 22 and improves at level 55 to increase [Whirlwind]'s damage. "
https://wowwiki-archive.fandom.com/wiki/Cleave

![image](https://user-images.githubusercontent.com/65713751/111769387-780e8480-88a9-11eb-9d9a-e0420f0dd1a5.png)
SACHANT QUE sur offi le heart strike était confirmé ne pas fonctionner cf : https://www.mmo-champion.com/threads/691109-Saurfang-s-blood-beasts-and-your-ability-to-cleave  (que je peux pas citer en source officielle)
D'ailleurs la peau resistante des betes reduit les degats des maladies de 70% car la pestilence n'est pas considérée comme aoe
Attention juste la météores n'est pas une aoe également c'est considéré comme beaucoup de petits sorts lancés en mono (genre la frostbolt volley de lady ou l'infest de lk)

Je pense que tous les sorts de catégorie "cleave effect" ne prennent pas cette réduction dans le script actuel (peut-être je me trompe)

https://wowwiki-archive.fandom.com/wiki/Deathbringer_Saurfang

**Comment by Justforsoloq** [comment]
Pour la météore c'est plus complexe que ça, tu as deux parties sur le sort, une partie aoe et une partie "mono splashing" et la partie mono splashing n'est en effet pas réduite (la partie aoe l'est), on peut le voir d'ailleurs sur les logs offi avec deux logs de starfall différents 
Et il me semble bien qu'en effet toutes les sorts de catégories cleave doivent prendre la réduction de saurcroc (les seuls sorts multi n'étant pas réellement réduits étant le starfall splashing et la chaîne d'éclair)

**Comment by Wilpok** [comment]
Oui ^^ c'est bien cela, je voulais dire les degats initiaux de la starfall pas le spread my bad,

**Comment by joshwhedon** [comment]
Corrige prochaine maj
