### ISSUE TITLE
La hitbox de sindragosa et hallions sont bug sur la tempête divine

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1212]
**Description**
La tempete divine ne touche pas le boss sindragosa/hallion / tous les dragons je pense, alors  que nous sommes en range d'auto attaques (sachant que le DS a une range supérieure à celle de l'auto, DS = tempete divine)

**Étapes de reproduction**

- Dragon
- Un monstre avec une queue et qui souffle
- Tempete Divine
- 
**Comportement attendu**
La tempete divine est censée faire des degats si nous somme dans la capacité d'autoattaque vu que la range est la même

**Captures d’écran / Vidéos**
https://clips.twitch.tv/BoredSquareRutabagaRuleFive-i6Xo6z8X6KM-5ctL

Ce clip d'elendil m'a été envoyé ou on voit bien les degats non existants de la tempete.

pour appuyer ceci j'ai des logs d'un ret sur sindra egalement

![image](https://user-images.githubusercontent.com/65713751/111778746-73e86400-88b5-11eb-8f05-652c67c7f1c1.png)
On voit que les tempetes divines ne touchent pas mais que le paladin peut inquisition / Autoattaque quand meme (a des timing differents de 1sec, voire moins

Exemple : "[23:38:36.667] Sindragosa Frost Aura Lasagnes Absorb (3056)
[23:38:36.790] Lasagnes Righteous Vengeance Sindragosa 376
[23:38:37.495] Lasagnes crits Sindragosa *6830*"
80centiemes de secondes de différence

**Ressources additionnelles**
![image](https://user-images.githubusercontent.com/65713751/111778999-d3df0a80-88b5-11eb-9d49-1478489a2840.png)
https://wotlk.evowow.com/?spell=53385

Plus dérangeant sur hallion ou on ne peut pas forcement toujours se positionner sous son ongle pour causer laser.

(Affecte peut-être/surement d'autres sorts du même type, mais aucune info dessus.)

**Comment by joshwhedon** [comment]
Ce sera pas corrige. Ca a deja ete signale et discute dans le passe, aucune solution blizzlike n'a ete trouvee, et aucune donnee ne permet de corriger le probleme.

**Comment by MJ-Vyr** [comment]
Le souci est le même au niveau de la tourbi du war.
