### ISSUE TITLE
Oeuf de phénix [donjon de la tempete]

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1217]
Pendant le combat contre Kael'thas, les phénix invoqués qu'on tuent se transforment en œuf, et ensuite on tue l'œuf. Le pb est que même si l'œuf meurt le phénix repop quand même après 15 sec. D'autre part les phénix ne depop pas après un wipe.

https://woehead.way-of-elendil.fr/?npc=21364#summoned-by

"Phoenix handling
After its birth, the phoenix can either be kited by a ranged damage dealer, or simply be tanked by the fire resist tank (it melees for ~800 on plate). It continually uses a hellfire ability which damages itself (5% HP) and everybody around it for ~5,000 fire damage per 2s tic, resulting in an (at most) 40 second life span. Upon its death, it will do an Ember Blast (4,500 fire damage melee range knockback, binary resist) and then turn into a Phoenix egg. This egg has ~70k HP and must quickly be killed, else it spawns a new Phoenix after 15 seconds."
https://wowwiki-archive.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics)

**Comment by Zaralbahk** [comment]
Issue déja présentée dans ce ticket https://github.com/way-of-elendil/3.3.5/issues/1042

**Comment by joshwhedon** [comment]
J'arrive pas a reproduire ce probleme, quand je tue l'oeuf le phoenix repop pas (meme si Kaelthas peut en invoquer un autre). Je regarderai peut etre plus en detail un jour si je jette un oeil a l'autre ticket.
