### ISSUE TITLE
Les dégats des auto attaques des boss d'ICC sont inexactes

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1218]
**Description**
Les boss d'ICC (entre autres) ne frappent pas assez forts sur les dégats de mélée sur Elendil

**Étapes de reproduction**

- ICC
- Tous
- Tous
- Les Auto attaques

**Comportement attendu**
La tranche de degats est erronée sur la DB déjà, les dégats sont réduits

**Captures d’écran / Vidéos**
LOG ELENDIL : TANK 261 ILVL SUR PUTRICIDE 10HM (SANS LE CRI DEMORALISANT (reduction de PA sur le boss) avec le 10% degats physiques en moins (rsham/pretre, constamment dessus) sous buff 30%

![image](https://user-images.githubusercontent.com/65713751/111871891-ba5cc200-898c-11eb-918b-fa280cf512b2.png)
https://way-of-elendil.fr/armory/character/666037-karjack

Log d'officiel (je n'ai pas le gear exact) : 

![image](https://user-images.githubusercontent.com/65713751/111871916-d6606380-898c-11eb-8be8-04a25e24109e.png)

Vidéo d'un war avec buff 5% d'icc (cf la date), qui prend des 15k, il a 58k hp hors icc en full buff + flask ce qui represente ilvl d'environs 264 en gemmage et opti full endu, (cf rawr que j'ai sim ci dessous), avec le 10% degats physique et égalment il met le cri demoralisant (ce qui reduit encore les degats du boss de manière significative  ( et donc normalement devrait prendre des degats + hauts ce qui appuie ce ticket)
https://www.youtube.com/watch?v=GYwe5vSbpAc

Rawr simulé : 

![image](https://user-images.githubusercontent.com/65713751/111871960-19223b80-898d-11eb-9333-e420c534ab20.png)
![image](https://user-images.githubusercontent.com/65713751/111871969-250dfd80-898d-11eb-9655-b6076390d981.png)
![image](https://user-images.githubusercontent.com/65713751/111871983-2dfecf00-898d-11eb-81cd-a05fcb2a7ab6.png)
 
(J'ai bien mis tous les buff possible et imaginables de disponibles sur le pallier etc...)

Avec la date de la vidéo nous savons que c'est uniquement un buff 5% cf : https://wowwiki-archive.fandom.com/wiki/Hellscream%27s_Warsong

World of Warcraft Hotfix (2010-03-30): Hellscream's Warsong increased to 10%.   (la vidéo date du 13mars soit 17jours avant l'application du patch de 10%)
La simulation est faite de ma part, c'est pour donner un ordre d'idée du stuff de guerrier (comparable a celui de notre tank sur elendil sur ce run)

**Ressources additionnelles**
Egalement, les fourchettes de degats sur woehead et une DB d'officiel cf : 

https://wotlkdb.com/?npc=36626
https://woehead.way-of-elendil.fr/?npc=36626#drops-4

Enfin sur https://wow.gamepedia.com/Festergut 
Je copie colle
![image](https://user-images.githubusercontent.com/65713751/111872060-b5e4d900-898d-11eb-9da9-e1ef0eb9abef.png)

Je ne peux pas donner exactement les différences, je ne sais pas si cela suffit ou je doit faire des calculs encore + poussées prenant en compte l'armure du tank + tous les talents + toutes les réductions de degats.

(On peut retrouver le meme problème sur tous les boss, je sais pas également si vous voulez que je fasse 12tickets, 1 par boss sachant que le problème doit être le meme sur chaque boss je pense (peut être que je me trompe fort egalement)

**Comment by gtschanz** [comment]
ça me semble fort quand même quand je regarde les timer entre 21h38:07 et 21h38:12 il prend 60k en mêlee en cumulé sur 5 sec (logs venant d'offi?) alors que tu dis qu'il pose la réduc dégâts et est en 261 avec des pots; j'trouve c'est quand meme très fort pour un tank à 36K5 armor (il devrait donc encore prendre plus chère (vu qu'il n'y a pas tjr la réduction pa); je veux même pas imaginer sur des boss style halion / lk HM ou même saurfang hm; je conteste pas forcément le fond, mais l'exemple que tu donnes me semble vraiment énorme en diff pour appuyer après, sachant que s'il y a un upgrade de 5K à 7k sur les melee (comparaison de tes screens)j'suis pas sûr que sur certains fight le tankfull stuff est encore en vie sur certaines claques

**Comment by Wilpok** [comment]
Oui c'est là le but du report, un boss en hm est censé faire des dégats comme tu peux bien le voir sur la vidéo et sur les logs que tu décris, environs 15k a chaque auto, car le tank est censé être rémonté entre chaque auto attaque par le heal, je n'ai pas dit qu'il était en gea 261, c'est sur elendil que le tanké tait en 261 (cf son armurerie, j'ai mis le lien) et il n'y avait pas de shout sur le boss (réduction PA), et oui la diff est énorme, c'est bien là le probleme, je comprends pas trop le commentaire du coup ? 

Les logs link sont bien d'officiel:

Si tu veux une autre preuve si des logs + une vidéo d'officiels n'arrivent pas à te convaincre 👍 
![image](https://user-images.githubusercontent.com/65713751/111898011-8f717d00-8a23-11eb-98cd-8b6caa0aee17.png)

http://www.worldoflogs.com/reports/sx2li1pj0ahvbws4/log/?s=3237&e=3413

Et oui si les plages de dégats sont rescript et deviennent ce qu'elle doivent être les tanks devront jouer pour de vrai et les heals également, c'est le but du pve quand même, de secouder un peu les bras.

**Comment by Subimase** [comment]
Bonjour, 

C'est top que tu apportes des chiffres à ce que certains affirment depuis plus d'un an. 

Est-ce que tu peux me dire où tu peux  trouver les logs elendil et ceux d'officiel ? Car j'ai trouvé que les boss, notamment Roi Liche, Putricide, Lanathel et Garga, ne faisaient pas forcément les dégâts qu'ils devraient faire. 

Si je peux t'aider dans le reporting ! N'hésite pas ! :) 

On avait déjà eu une discussion sur ce sujet avec la merge sur ICC avant que Sthanks ne parte du serveur. Seule lui et son équipe avait pu passer LK 30% avec des bonnes rota CD palouf, DP, rota tank, etc... Aujourd'hui, les tanks ont des optimisations surprenantes sans se prendre des 72k dans la tête. 

Subimase

**Comment by Wilpok** [comment]
et la liste de mes recents reports : http://www.worldoflogs.com/guilds/352275/

10nm 10hm et 25nm

Et oui pour faire un ticket il faut des preuves pas des "je crois et il me semble", pour les report d'offi il faut en prendre des antérieurs au patch 4.0, et non merci je n'ai pas besoin d'aide pour mes reports. j'y arrive solo

**Comment by Subimase** [comment]
Merci

**Comment by Wilpok** [comment]
Tant qu'à faire, hallion également : 

Logs nm sur elendil : 
![image](https://user-images.githubusercontent.com/65713751/111981782-6d9df600-8b08-11eb-8eea-09150dee3e5b.png)
17k par auto toujours notre dk tank 261, sans cri démoralisant ( réduction de PA)

Logs hallino nm sur offi : 
![image](https://user-images.githubusercontent.com/65713751/111982180-f026b580-8b08-11eb-8daf-54bc3ebdb6d6.png)
24k par swing, avec cri demoralisant, 60% d'uptime (les 40% restant doivent surement être quand hallion était dans le monde de l'ombre)

les 2 tanks ici tankaient en lumière (que des flame breath)

Logs utilisés : Elendil : http://www.worldoflogs.com/reports/q1ixid8rc9478uc2/details/3/?enc=bosses&boss=39863
Offi : http://www.worldoflogs.com/reports/dc7bgvwgmbl3u8g1/details/31/?s=11672&e=12122

**Comment by Unleashedzer** [comment]
arrête les boss vont être tro dur après
