### ISSUE TITLE
La combustion proc sur les renvois de degats de l'armure de la fournaise alors que ce n'est pas censé être le cas

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1221]
**Description**
Les stacks de combu sont consommés lors du renvoi des degats par l'amrure de la fournaise alors que c'est pas censé être le cas

**Étapes de reproduction**
Aller sur un mage feu, mettre l'armure de la fournaise claquer la combu, pull un mob, les stacks de combu augmentent et disparaissent quand l'armure a crit 3fois
- Mage
- Feu
- Combustion / Armure de la Fournaise

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Les stacks de combu ne sont pas censés être consommés par cette abilité

cf log elendil : 

![image](https://user-images.githubusercontent.com/65713751/111884856-89987f00-89c4-11eb-962d-c7e2af0f75e1.png)

**Ressources additionnelles**
https://www.youtube.com/watch?v=RIsabfXpRNM&t=72s

Voyez le mage sous combu qui se fait fracasser par un dk, sa goule et un feral et aucun proc combu sur le renvoi d'armure de la fournaise.

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/927
A premiere vue ce bug est pas valide, a moins que tu puisse apporter des preuves que le rapport de bug precedent est incorrect et que la video n'est pas correcte. Si c'est le cas commente pour demander une reouverture.

**Comment by Wilpok** [comment]
c'est la bombe vivante qui la fait passer de 3 à 4 pas le coup du pet

**Comment by joshwhedon** [comment]
OK peut etre

**Comment by Wilpok** [comment]
Plutot la pyro qui a proc sans crit vu qu'il a eu le stack à ce moment*

**Comment by Wilpok** [comment]
et surtout on voit l'armure crit sur la vidéo sur le pet, donc si elle crit et que ça prenait en compte la combu, la combustion disparaitrait (vu qu'elle fade quand 3 spells ont crit) en l'occurence dans la vidéo link de l'autre ticket et la mienne, la combu ne disparait pas donc ne se fait pas appliquer sur la molten armor
alors que sur elendil si
