### ISSUE TITLE
[Quête] Le gambit de Tirion

### ISSUE THREAD

**Issue by Brisboo** [way-of-elendil/3.3.5#1224]
**Description**
Le PNJ à qui parler est couché au sol, non mort, mais impossible de lui parler.

**Étapes de reproduction**
- looter un Chaperon d'acolyte du culte
- équiper le chaperon
- se diriger vers le PNJ à droite de l'entrée de la cathédrale près du feu

**Comportement attendu**
Je devrais trouver un PNJ debout à qui je peux parler.

**Ressources additionnelles**
Vidéo de la quête :
https://www.youtube.com/watch?v=dlWNHPpKB00&ab_channel=GameGuidesChannel

**Comment by joshwhedon** [comment]
Faire appel a un mj en jeu, le npc a du se bloquer. Ca arrive.
