### ISSUE TITLE
L'ICD et le proc clearcasting fonctionnent mal

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1226]
**Description**
Idées claires proc sur des buffs et n'a pas d'icd (normalement 10secondes) et je pense (rien de sur atm) qu'il proc sur les ticks de hot 

**Étapes de reproduction**
Faire un druide, spam don du fauve (cela proc bcp + en raid car le proc est demultiplié par le nombre de joueurs dans le raid j'ai l'impression), idéées claires va proc alors que c'pas censé arriver
- Druide
- Augure de clarté

**Comportement attendu**
Il est censé y avoir 10sec de délai entre chaque proc et ne proc que sur les sorts de dégats de soins ou les autoattaques.

**Captures d’écran / Vidéos**
Log d'un druide heal sur Elendil : 
![image](https://user-images.githubusercontent.com/65713751/111901518-06654080-8a39-11eb-9fbd-4e3887be3cf4.png)

**Ressources additionnelles**
https://wow.gamepedia.com/Omen_of_Clarity

"Wrath of the Lich King Patch 3.0.2 (2008-10-14): Now a passive spell. Now also procs on damage and healing spells, yet no longer procs on feral abilities(only auto-attacks proc it). Proc rate is roughly 6% with a 10 second internal cooldown. "

**Comment by Wilpok** [comment]
Edit : Ne proc pas sur les ticks après test, mais toujours un proc rate haut, l'icd non respecté et proc sur des sorts qui ne sont pas censés le faire.

**Comment by TrucEtrange** [comment]
Nouvelles informations (Merci Wilpok) : 

![image](https://user-images.githubusercontent.com/45370942/181250391-452062b9-b42e-4f1c-aef8-373dff4ef99d.png)

https://www.mmo-champion.com/threads/611021-WotLK-Beta-Patch-Notes-Update

Le BT intial était donc une erreur, au vu des nouelles informations que Wilpok a trouvé. Désolé pour le dérangement.

**Comment by TrucEtrange** [comment]
Pas sûr que le commentaire soit vu, puique le ticket est fermé. Dans le doute je tag @joshwhedon
