### ISSUE TITLE
Rune du croisé déchu ne proc pas assez

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1227]
**Description**
La rune du croisé déchu ne proc pas assez

**Étapes de reproduction**
Mettez la rune sur votre arme, tapez pendant 10minutes un poteau, regardez l'uptime de force impie, il est trop bas
- Chevalier de la mort
- Rune du croisé déchu

**Comportement attendu**
La rune devrait proc bcp plus souvent 

**Captures d’écran / Vidéos**
Logs sur ELENDIL sur fester 25n (donc boss poteau, pas de mouvement etc...) 
![image](https://user-images.githubusercontent.com/65713751/111905400-b6dc4000-8a4b-11eb-881b-7ec01624f94e.png)
25% d'uptime

LOG OFFI (fester 25n)  75% uptime : 
![image](https://user-images.githubusercontent.com/65713751/111905575-a4aed180-8a4c-11eb-81a8-53a70c26f860.png)

Logs complets : Offi : http://www.worldoflogs.com/reports/rt-lh19x9zq94wcoo9s/details/31/?s=7819&e=7983
Elendil : http://www.worldoflogs.com/reports/1wx0ym9lrw770aai/details/9/?s=2456&e=2683

**Ressources additionnelles**
https://wow.gamepedia.com/Rune_of_the_Fallen_Crusader
https://wotlk.evowow.com/?spell=53365
https://www.mmo-champion.com/threads/1345790-Rune-of-the-fallen-crusader-and-it-s-procs-uptime
![image](https://user-images.githubusercontent.com/65713751/111905525-64e7ea00-8a4c-11eb-9d0f-8aa77e4891e5.png)

**Comment by Justforsoloq** [comment]
Kalblack m'a fait la même remarque, il va être content que ça soit testé

**Comment by Wilpok** [comment]
ça vient de lui, enfin j'lavais mp pour un truc et il m'a dit ça

**Comment by joshwhedon** [comment]
Pas d'accord. Le post de mmo-champion date de 2013, donc bien apres wotlk. d'un autre cote, tous les commentaires de wowhead concernant wotlk parlent bel et bien de 1ppm, et les commentaires en question datent d'apres le patch 3.1.0 qui a double le proc.

**Comment by Wilpok** [comment]
Les logs datent de wotlk sous 3.3.5

**Comment by Justforsoloq** [comment]
https://www.mmo-champion.com/threads/720880-Rune-of-the-fallen-crusader-vs-beserker (2010)
 If you factor in the fact that fallen crusader is 2 ppm and berserking is 1 ppm

**Comment by Wilpok** [comment]
(Et peut on prendre les commentaires wowhead comme source exacte? Sur beaucoup de spell les mecs dans les commentaires se contredisent, la j'te sors des logs de 3.3.5 sur le même boss, même patch btw j'ai mis en ressources additionnelles 2/3trucs que j'ai trouvé, j'ai toujours trouvé les logs + fiables qu'autre chose)

**Comment by joshwhedon** [comment]
Non on peut rien prendre comme source exacte, mais les infos sont contradictoires partout, et les ppm ca reste de l'aleatoire, du coup les logs ... c'est qu'a moitie valide pour les taux de proc (sachant que les ppm prennent pas les buffs en compte il me semble, donc ca proc forcement plus souvent en raid).

**Comment by joshwhedon** [comment]
En plus meme si on met les ppm a 2, ca fera toujours que du 50% d'uptime, donc ca reste incorrect si on se base uniquement sur les logs.
Bref je regarderai avec plus de details quand j'aurai le temps, ce sera surement pas avant quelques semaines.

**Comment by Wilpok** [comment]
(les 2 logs sont en raid sur le même boss juste 1minute change, pas d'aléatoire y'a pas de malléable sur fester en 25n donc pas de slow d'attaque speed. j'peux te chercher d'autres log d'retail pour l'uptime si tu veux + de données 

(et j'cale aussi les formules de ppm si ça peux t'éviter d'chercher, https://wowwiki-archive.fandom.com/wiki/Procs_per_minute )

**Comment by joshwhedon** [comment]
Oui mais tu comprends bien que 75% d'uptime ... pour un sort qui a 15secondes, ca fait pas du 2 ppm. Donc non c'est pas aussi simple que ca. Et merci je connais la formule du ppm.

**Comment by joshwhedon** [comment]
J'ai regarde d'autres sources et l'historique de changement sur TC, ca a l'air d'etre suppose etre 2ppm, et la premiere implementation sur TC semble dater de la 3.0 et a pas change depuis (donc le patch qui le double n'a pas ete applique a premiere vue)
