### ISSUE TITLE
Frappe de Givre ne prend pas en compte le 13% dégats des sorts

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1229]
**Description**
La Frappe de Givre ne prend pas en compte le 13% dégats de Malédiction des elements / Peste d'ébène / Terre et Lune

**Étapes de reproduction**
Prenez un dk, mettez des points dans la peste d'ébène en impie, faites de frappe de givre sans psoer de maladies, faites en avec, les degats sont sensiblement les mêmes
- Chevalier de la mort
- Givre
- Frappe de Givre

**Comportement attendu**
La frappe de givre devrait infliger 13% de dégats supplémentaire car considérée comme dégats de givre

**Captures d’écran / Vidéos**
Logs sur le PTR d'elendil : 
![image](https://user-images.githubusercontent.com/65713751/112039606-82987a80-8b44-11eb-9cf0-e6363e514d20.png)
(J'ai donc bien appliqué le 13% dégats de  19:09:28 à 19:10:19 

Sort en question : 
![image](https://user-images.githubusercontent.com/65713751/112039733-a78ced80-8b44-11eb-81fb-f43be53786c4.png)

Frappes de givre : 
SANS LE 13%
![image](https://user-images.githubusercontent.com/65713751/112039782-b5db0980-8b44-11eb-8fb0-dd4880b67cff.png)
![image](https://user-images.githubusercontent.com/65713751/112039840-c7241600-8b44-11eb-9d41-08f5aac3b615.png)

AVEC LE 13% 
![image](https://user-images.githubusercontent.com/65713751/112039912-d73bf580-8b44-11eb-8a65-c94426601dda.png)
![image](https://user-images.githubusercontent.com/65713751/112039958-e622a800-8b44-11eb-8a77-a4d99b0e2ac9.png)

Moyenne des FS sans 13% : 
![image](https://user-images.githubusercontent.com/65713751/112040285-53363d80-8b45-11eb-9bac-87bff7f3c695.png)

Moyenne des FS avec 13% : 
![image](https://user-images.githubusercontent.com/65713751/112040536-9ee8e700-8b45-11eb-8a2f-865c34895c1b.png)

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=55268
https://woehead.way-of-elendil.fr/?spell=51161

J'peux le simuler sur un échantillon plus large au besoin

**Comment by Ischjgt** [comment]
Preuve stp,
À priori c'est le même comportement que la frappe du fléau (shadow)

`Glace noire augmente les dégâts d'ombre (donc ça l'affecte), mais porte peste d'ébène augmente les dégâts magiques reçus (hors frappe du fléau n'est pas une attaque magique). Pareil pour toutes les frappes, elles ont l'air de toute être de mélée. En gros il faut bien comprendre qu'un sort peut avoir une école de magie, sans pour autant être magique. Par exemple, si tu as une arme élémentaire (il y a en quelques une en jeu), l'école de magie de tes attaques changera, mais ça restera des attaques physiques (il y a 4 types, magique, mélée, distance, et aucun).`

**Comment by Wilpok** [comment]
![image](https://user-images.githubusercontent.com/65713751/112046778-c1323300-8b4c-11eb-8521-deffafe3e8bc.png)

https://woehead.way-of-elendil.fr/?spell=55271

???

**Comment by Wilpok** [comment]
Le 13% proc sur le sceau de vengeance, (bien script) sceau d'autorité, tir de la chimère et frappe de givre

**Comment by Justforsoloq** [comment]
Possibilité de double dipping sur ces sorts d'ailleurs donc à faire attention

**Comment by joshwhedon** [comment]
Frost strike, comme la plupart des techniques de DK, n'est pas une attaque magique, mais physique.
DamageClass = 2 (SPELL_DAMAGE_CLASS_MELEE)
Donc aucun bonus de degats magique ne s'applique.
Degats elementaux ne signifie pas necessairement degats magiques.

**Comment by joshwhedon** [comment]
Soit dit en passant, Chimera shot : DamageClass = 3 (SPELL_DAMAGE_CLASS_RANGED)
Pas magique non plus.

**Comment by Justforsoloq** [comment]
En fait tu as une liste de spells qui font des dégâts de l'arme en dégâts magiques : 
 Sceau de vengeance, Sceau de corruption, Tir de la chimère, Carquois Sauvage, Frappe de Givre, Rune de Trancheglace, Fouet de lave
Et ces spells prennent généralement en compte le CoE 13% dmg magique (le gros bug des privés c'est que souvent ils font double Dip ces spells qui gagnent 2x les buffs % dmg (dont le CoE) sur leur partie physique ET magique ce qui n'est pas censé être le cas).

Par rapport à frost strike : 
https://www.wowhead.com/spell=49143/frost-strike#comments 
on 2010/08/05 (Patch 3.3.5)
55% base
66.00%--20% Glacier Rot
74.25%--15% Tundra Stalker
82.50%--15% Blood Presence
88.00%--10% Blood of the North
93.50%--10% Black Ice
99.00%--10% Razorice Debuff
106.15%--13% Curse of Elements/Ebon Plague (ils parlent bien de CoE)

**Comment by Wilpok** [comment]
(Fonctionne comme le reaper sur lk, prouvé sur les logs par le "R" donc resist, pas de résist sur les dégats physiques)

**Comment by joshwhedon** [comment]
Encore une fois, il y a une difference entre resistance et type d'attaque.
Une attaque peut etre une attaque magique ... sans element. Par exemple, Cri demoralisant de certains pet chasseurs.
Une attaque peut etre une attaque de melee ... avec element, par exemple le reaper du LK. Ce n'est pas une attaque magique, c'est une attaque de melee avec element.
A cote de ca, j'ai fait les tests et les verifications, Maledictions des elements n'augmente pas les degats magiques, comme indique dans le tooltip, mais les degats elementaux (vu le nom, ca se tient). Et j'ai aussi verifie, Malediction des elements est bel et bien applique.

**Comment by joshwhedon** [comment]
Et pareil pour Ebon plague, ca augmente les degats elementaires, et dans le cas present, ca s'applique aussi (j'ai debug cote serveur pour verifier les calculs).

**Comment by Wilpok** [comment]
Du coup j'ai pas exactement compris tes réponses, ça va rester comme ça ou pas? car là j'vois pas ou ça s'applique actuellement

**Comment by joshwhedon** [comment]
Bah je sais pas comment t'as teste, mais j'ai fait les tests de mon cote, a la fois malediction des elements et peste d'ebene (pas teste terre et lune), et c'est bien pris en compte. Par contre je pense pas que les 3 se stack (si c'estce que tu as teste).

**Comment by Wilpok** [comment]
Bah j'ai testé sur poteau, 20coups avec le 13% et 20coups sans et la moyenne des coups est exactement la même, les 3 ne se stackent pas non c'est comme la lucioles et le VT du sp, c'pour ça que je trouvais bizarre que ça s'applique alors que ça sort exactement la meme moyenne (après j'suis d'accord que j'ai testé vraiment sur un petit echantillonage

**Comment by joshwhedon** [comment]
Y'a moyen de tester avec un equipement qui reduise la variance de degats aux maximum ?
Sinon tu peux aussi regarder le dot. Si tu applique le debuff (peu importe lequel) apres le premier tick, tu peux voir que le dot est augmente.

**Comment by Wilpok** [comment]
J'étais en stuff de départ de dk donc 0 proc avec une arme sans proc également (une arme a 2mains, la r2 pvp),

Je suis d'accord que le 13% fonctionne sur les dots etc... je te dis juste qu'il ne s'applique pas aux dégats magiques de la frappe de givre ^^

**Comment by joshwhedon** [comment]
Sur le coup je sais pas quoi te dire, je sais pas comment je peux le prouver.
Perso ce que je viens de faire c'est me foutre absolument tout nu, avec une epee niveau 10. Resultat la variance de degats est d'environ 10 points (environ 300 avec frappe de givre), avec la peste, ca monte a 334 environ. Il y a peut etre des armes qui ont une variance encore plus faible pour ce genre de test.

**Comment by Wilpok** [comment]
Ok ok alors si ça marche pour toi pas d'souci ^^ j'te fais confiance, sorry pour l'ticket

**Comment by joshwhedon** [comment]
Pas de soucis, Tu as pas a me faire confiance non plus :D . Si tu veux tester ce que je donne plus haut c'est le moyen le plus simple, parce que vu que la variance est super faible, 13% de bonus ca se voit direct. Dis moi si les tests sont pas concluants.

**Comment by Wilpok** [comment]
Toujours le même souci chez moi sur le PTR d'elendil

![image](https://user-images.githubusercontent.com/65713751/112145235-66dfb380-8bda-11eb-9f92-c84212d1e293.png)

![image](https://user-images.githubusercontent.com/65713751/112145264-6d6e2b00-8bda-11eb-8f75-a0288ca065c8.png)

249 avec ou sans 13%

**Comment by Ischjgt** [comment]
Y'a le 13% sur le prod chez moi.

**Comment by Wilpok** [comment]
T'as une preuve stp? ^^ car vraiment soit j'suis naze soit j'ai un souci

**Comment by Ischjgt** [comment]
<img width="260" alt="Capture d’écran 2021-03-23 à 17 51 43" src="https://user-images.githubusercontent.com/60295792/112203727-1df82100-8c13-11eb-9cc0-1cf02a5caebc.png">
<img width="277" alt="Capture d’écran 2021-03-23 à 17 55 52" src="https://user-images.githubusercontent.com/60295792/112203736-1f294e00-8c13-11eb-8863-a8ce4dd9fd2f.png">

**Comment by Wilpok** [comment]
Avec quel stuff? Sous formes de logs c'est plus simple que un random recount

**Comment by Ischjgt** [comment]
C'est pas un random recount, 853 sans le debuff, 967 avec en mini hit, ce qui correspond au 13%
ça va merci j'ai pas vraiment besoin de me justifier pour ça

**Comment by Wilpok** [comment]
Ma foi si c'est vrai np mdr,

@joshwhedon voilà, mes résultats sont pas concluants comparés aux tiens et ceux d'isgjt, j'sais pas pourquoi mais pas d'souci si ça s'apply

**Comment by Ischjgt** [comment]
@joshwhedon , si c'est un autre joueur qui met le débuff 13%, la frappe de givre voit pas ses dégats augmentés
