### ISSUE TITLE
Spell: Main de liberté

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#123]
**Description**
Il est possible de lancer main de liberté en étant stun (sans aucun talent et sur une autre cible également)

**Comment by joshwhedon** [comment]
https://www.mmo-champion.com/threads/1779192-Hand-of-Freedom-is-no-longer-usable-while-stunned-REALLY
Je trouve pas d'autres sources, mais les donnees client ont : AttributesEx5: 0x00000008 (SPELL_ATTR5_USABLE_WHILE_STUNNED)
