### ISSUE TITLE
Toute puissance de combat ne proc pas pendant la killing spree

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1231]
**Description**
Toute puissance de combat ne proc pas pendant la série meurtrière alors que c'est censé être le cas, ce qui rend l'open des rogues en pve beaucoup plus faible étant donné que l'on doit ks justement pour regen l'énergie grâce à ça

**Étapes de reproduction**
Faites un rogue, mettez vous tous les buff de vitesse d'attaque possible, tapez un mannequin, faites serie meurtiere,  il n'y aura jamais de proc durant sa durée
- Voleur
- Combat
- toute puissance de combat / Série meurtrière

**Comportement attendu**
Il est possible de proc toute puissance de combat pendant la série meurtrière

**Ressources additionnelles**
https://www.youtube.com/watch?v=LYe_1qmCeRM
1:25, proc 2fois
4:13 proc 1fois
https://woehead.way-of-elendil.fr/?spell=35553
![image](https://user-images.githubusercontent.com/65713751/112164976-a0bab500-8bee-11eb-997e-01eec454e4a5.png)
2.4.3 mais pas de patchnote entre 3.3.5 et 2.4.3 concernant le point de talent 
![image](https://user-images.githubusercontent.com/65713751/112165042-ad3f0d80-8bee-11eb-862c-a21bfc8b92a4.png)
https://wowwiki-archive.fandom.com/wiki/Combat_Potency

**Comment by joshwhedon** [comment]
Bah ... 3.0.3 : Ne fonctionne qu'avec les auto attaques, Killing spree c'est pas des auto attaques si ?

**Comment by Justforsoloq** [comment]
En gros durant la Killing Spree tes coups blancs continuent de se déclencher normalement. Donc j'imagine qu'il veut dire que durant la KS les coups blancs qui partent (si il y en a sur woe pas vérifié) ne déclenchent pas combat potency

**Comment by joshwhedon** [comment]
Si c'est des vrais coups blancs ils declencheront. Mais la killing spree, c'est pas des coups blancs, c'est des techniques, donc la killing spree elle meme ne declenchera rien.

**Comment by Justforsoloq** [comment]
Alors j'ai ptet pas été clair, mais DURANT la killing spree, le sort qui tape, les coups blancs du rogue normaux white hit sont censés partir aussi. Donc c'est de ça dont il parle j'imagine. Pas de la Killing spree, mais des white hit censés partir DURANT la Killing Spree (qui ne sont pas DE la killing spree)
https://wowwiki-archive.fandom.com/wiki/Killing_Spree
During Killing Spree, you continue to melee. [Slice and Dice] and/or Blade Flurry should be used in conjunction with Killing Spree because of this and the 20% damage bonus of Killing Spree.

**Comment by Wilpok** [comment]
Pour les preuves : 

https://youtu.be/Om11XNKq4EA
Vidéo sur Elendil (Sans débiter ni condition de raid, les auto sont encore plus rapides en conditions réelles)

+ Les logs attachés 

http://www.worldoflogs.com/reports/yl1i2atl14blqsw9/log/

La toute puissance du combat (Combat Potency) ne proc QUE sur les auto attaques hors série meurtrière (comme le montre ma vidéo à contrario de la vidéo d'officiel, sur le post initial)

**Comment by Traesh** [comment]
Le problème est corrigé à l'heure actuelle, j'ai artificiellement augmenté la durée de Killing Spree à 2 minutes pour tester plus facilement mais rien d'autre n'a été touché :

https://streamable.com/y6kyd4

A la limite le taux de proc me semble assez faible (même si au final 20% de l'arme gauche ça revient à 10% de chance sur la totalité des coups blancs réussis donc pas très élevé), c'est plutôt de ce côté là qu'il faudrait regarder mais il faudra dans ce cas ouvrir un autre ticket
