### ISSUE TITLE
donjon Azjol -Nérub combat à partir du second boss

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1232]
Pour la version Azjol -Nérub version normale (la version héroïque n'a pas été vérifiée)

Lorsque le second boss est tué (Hadronox: https://woehead.way-of-elendil.fr/?npc=28921) le groupe reste en mode combat jusqu'à la fin du donjon. Surement un mob coincé avec l'event, mais en fait, je n'en sais rien du tout.

je propose l'ajout d'un déclencheur situé dans le lac qui reseterait le mode combat, ça réglerait le problème facilement.

Azjol -Nérub: https://woehead.way-of-elendil.fr/?zone=4277

Bon courage.

**Comment by joshwhedon** [comment]
Ce sera pas corrige desole.
