### ISSUE TITLE
Quête [78]  [Un départ amer] escorte

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1234]
[78]  [Un départ amer] https://woehead.way-of-elendil.fr/?quest=12832

Le pnj ne se fait pas attaquer par les mobs.
De plus, le pnj escorté n'attaque pas les mobs qui ont été aggro par les joueurs.

D'avance merci.

**Comment by Babyface-187** [comment]
La quête est réalisable, mais effectivement, le https://woehead.way-of-elendil.fr/?npc=29434 devrait normalement s'arrêter pour aider le joueur à cogner les mobs.

**Comment by Ferro3** [comment]
vérifié
fix ok
