### ISSUE TITLE
Mauvais nombre de token T7 à Naxx 25

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1235]
Bonjour, le taux de loot des token T7 ilevel213 sur certain boss de naxx 25 me semble anormal:

Taux constaté en raid la semaine dernière:
thaddius : https://woehead.way-of-elendil.fr/?npc=15928#drops-2    =>1seul token
kel thuzad : https://woehead.way-of-elendil.fr/?npc=15990#drops-2   =>1seul token
Horreb : https://woehead.way-of-elendil.fr/?npc=16011#drops-2    => 1 seul token
4  cavaliers :  https://woehead.way-of-elendil.fr/?npc=16011#drops-2   => 1 seul token (à vérifier je me rapelle plus si ca a loot un seul ou 2 token au dernier raid)
Gluth : https://woehead.way-of-elendil.fr/?npc=15932#drops-2  =>2 tokens (a verifier je me rapelle plus si ca a loot 2 ou 3 token au dernier raid)

Si on regarde les données de altlas loot in game (bien que les taux de drop indiqués sont rarement fiables), il y a une réelle différence entre le taux de loot de token en 10 et en 25 (en gros *2). 
Si on compare ça aux videos trouvé sur youtube: 
offi 2017 : https://www.youtube.com/watch?v=0bEeTI31w2s    => 2 token sur tout les boss (gluth compris)
thaddius 2009 : https://www.youtube.com/watch?v=vIys0aZ57j8    => 2 token
KT 2009 : https://www.youtube.com/watch?v=Ptq5iXaYUJs    => 2 token
Naxx full (Method 2011) : https://www.youtube.com/watch?v=fAi3cr2uo1E  =>2token par boss (gluth compris

**Comment by Kaasss-woe** [comment]
Corrigé (appliqué demain).
L'évolution de la quantité de drop des tokens en mode 25 joueurs est la suivante :
Avant -> après
1 → 2 : Thaddius
1 → 2 : Horreb
1 → 2 : Coffre des quatre cavaliers
3 → 2 : Gluth
1 → 2 : Kel'Thuzad
