### ISSUE TITLE
Boss: Porte-mort Saurcroc reset

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#1236]
**Description**
https://woehead.way-of-elendil.fr/?npc=37813 Saurcroc
https://woehead.way-of-elendil.fr/?spell=4511 changement de phase

Je sais pas exactement dans quelle mesure mais le spell changement de phase du diablotin a fait reset Saurcroc de façon répétée dans la soirée en ICC10NM

(Le boss partait en evade de façon répétée et après avoir demandé au joueur d'arrêter de mettre le spell en automatique, le combat s'est bien passé)

J'ai une vidéo où le boss reset 2x, la première fois, y'a trop d'infos en même temps la vidéo même a 60fps c'est galere
La seconde fois :
<img width="472" alt="Capture d’écran 2021-03-24 à 23 03 54" src="https://user-images.githubusercontent.com/60295792/112389802-9e8f4e00-8cf5-11eb-9a9b-9beba7d0e5e3.png">

Rien de particulier ne se passe à propos de cette seconde fois, aucun ciblage étrange etc, juste une fois que le diablotin gagne l'aura du changement de phase - soulignée en rouge, le boss reset

Pas réussi à reproduire et c'est la première fois que ça arrive au joueur et que je vois ça

**Comment by joshwhedon** [comment]
Si aucun moyen de reproduire n'est fourni ca ne sera pas corrige. Et y'a aucune raison que ca n'arrive que sur saurcroc.
