### ISSUE TITLE
Rez goule à icc hit 700k

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1238]
**Description**
Je n'arrive pas à reproduire le bug, peut-être est ce du aux buffs dans icc ou c'est juste un bug isolé, mais après un rez goule, un des joueurs tapait a 700k sur lk 25h

**Étapes de reproduction**

- ICC
- 25h
- Roi liche
- https://woehead.way-of-elendil.fr/?spell=61999

**Comportement attendu**
La goule ne devrait pas faire aussi mal

**Captures d’écran / Vidéos**
![image](https://user-images.githubusercontent.com/65713751/112717640-59823c00-8eee-11eb-8578-716c39cb08a6.png)
![image](https://user-images.githubusercontent.com/65713751/112717662-79196480-8eee-11eb-9ec3-1f5734161e79.png)

en 1 coup

**Comment by Traesh** [comment]
Impossible à reproduire de mon côté

Un log des dégâts trop importants de la goule a été ajouté, nous serons alertés en cas de nouveau problème et pourront tenter de comprendre ce qui se passe

**Comment by Endalaust** [comment]
Normalement fixé. Merci de nous tenir au courant sur ce ticket si le cas se reproduit.
