### ISSUE TITLE
Skettis, Enragé des forêts lige-griffe non élite

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1244]
Dans la zone **Skettis** dans la **Forêt de Terokkar** un **Enragé des forêts lige-griffe** n'est pas élite
De plus dans la base de donnée il manque 2 points de position, il y a 4 **Enragé des forêts lige-griffe** aux coordonnées 67.4, 74.0 / 62.8, 76.6 / 66.9, 86.2 / 71.6, 83.2

- changer l' **Enragé des forêts lige-griffe** avec sa table de loot
- ajouter 2 points sur la carte dans la base de donnée 67.4, 74.0 et 71.6, 83.2

**Forêt de Terokkar** https://woehead.way-of-elendil.fr/?zone=3519
**Enragé des forêts lige-griffe** https://woehead.way-of-elendil.fr/?npc=23029
Screen : https://i.postimg.cc/SQwTsWyy/skettis-enragedesforets.png

Bon courage

**Comment by KreatorWoE** [comment]
Après vérification et vu en mp avec Ferro, RAS. Je ferme le ticket.
