### ISSUE TITLE
pet chasseur perma dead halion hc

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#1245]
Halion 25hc

une des strat possible du halion hc (et celle qui est appliqué actu sur woe) c'est que le tank côté lumière (mt1) du dragon tank en plus l'inferno et du coup lorsqu'on envoie le pet attaquer l'inferno alors qu'il est au même niveau que le dragon (sur la même ligne), le jeu considère que le pet est derrière l'inferno mais devant la gueule du dragon, résultat le pet se mange chaque fois le souffle et die perma sur ça (du moins c'est l'hypothèse que j'en ai tiré ce soir après avoir try halion hc) ou qu'il die perma sur les tics de flamme aussi rapidement qu'un joueur; alors que les vidéo que j'ai pu voir d'offi ou cette strat est appliqué les pets ne meurent jamais ou très rarement je sais pas pk ils sont ''considéré'' devant le dragon chaque fois alors qu'il tappe dans le dos de l'inferno ou du dragon. Ce qui rend le fight extrêment pénible pour les classes à pet qui doivent switch sur l'inferno (demono / chasseur / affli (dans une moindre mesure). Sur 7 ou 8 try qu'on a fait mon pet n'a survécue qu'à 1 try au passage p2 (puis il était aussi mort au passage des cutter p2 qui l'ont explosé..

**Comment by Briznuits** [comment]
C'est pas le souffle car le souffle est une attaque de zone magique donc 30K -90% ça peut pas le shot ça doit être le cleave que il fait avec sont sort enchainement qui le oneshot

**Comment by joshwhedon** [comment]
Les cleaves sont / seront considere comme des aoe et reduits pour les pets (je sais pas si cette maj est passee encore)

**Comment by gtschanz** [comment]
concernant ce bt josh; j'ai fais des test plusieurs fois sur halion en soigneur et j'ai capté ce qui tuait les pets en permanence (en halion hm) les flammes du pop de la météor explose les pet vu que la direct se fait souvent en croix avec un segment atteignant la queue du dragon et les pets tappant de dos le boss (ils die souvent en 1 à 2 sec impossible à tenir sauf à spam le soin sur le pet...
