### ISSUE TITLE
Haut fait "Un marteau pour les pwner tous"

### ISSUE THREAD

**Issue by Adjae** [way-of-elendil/3.3.5#1246]
Haut fait non réalisable 
https://woehead.way-of-elendil.fr/?achievement=3803

Réalisé dans le dj EDC 5 HM (tag en aléatoire h2 + a2) : DK Tank, Feral + War + Fufu dps, Hpal Heal. 

Eadric le Pur : https://woehead.way-of-elendil.fr/?npc=35119
Le boss a été descendu à 2% pv (environ 20k vie) puis nous avons stop dps le temps de le voir cast son marteau. 
Spell offi : https://fr.wowhead.com/spell=66867/marteau-du-vertueux
Spell woe : https://woehead.way-of-elendil.fr/?spell=53595
ou : https://woehead.way-of-elendil.fr/?spell=54423

Nous avons passé une quinzaine de cast du marteau sans pouvoir l'utiliser contre lui, certaines tentatives avec dispel du stun, d'autres non. 

Comportement attendu : 
" Marteau du vertueux -> Il vous l'envoie et vous avez une barre de sort qui apparait avec la possibilité de lui renvoyer le marteau dans les 5 secondes où vous le récupérez. Si, lorsque vous lui renvoyez, il est tué, alors le HF est réalisé. "
https://fr.wowhead.com/achievement=3803/un-marteau-pour-les-pwner-tous#comments

Comportement rencontré : le cast se lance bien, le joueur ciblé et stun, mais aucun changement de barre de sort ne s'applique. 

Bisous bisous

**Comment by Endalaust** [comment]
Testé de mon côté, et j'ai pu le faire sans trop d'efforts
