### ISSUE TITLE
Les talents [58410]Maître empoisonneur et [20337]Coeur du croisé ne semblent pas fonctionner

### ISSUE THREAD

**Issue by Belore** [way-of-elendil/3.3.5#1250]
**Description**
Après une heure de test sur poteau (3000 auto-attaques + 2000 poisons en voleur assa et 500 en paladin ret), j'ai constaté que la part de coups critiques infligés est identique à celle indiquée sur ma fiche de personnage, alors qu'elle devrait être plus haute de 3 points grâce aux talents en lien plus bas.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Voleur et paladin
- n'importe quelle race
- Assassinat et vindicte
- talents Maître empoisonneur, Coeur du croisé
- taper du poteau
- armes rapides pour avoir plus vite un nombre représentatif d'auto-attaques

**Comportement attendu**
Ces talents devraient permettre d'augmenter les chances de critique (physique et spell) de 3% contre les cibles empoisonnées et/ou jugées.

**Captures d’écran / Vidéos**
![WoWScrnShot_041021_132652](https://user-images.githubusercontent.com/8245888/114268343-e524be00-9a00-11eb-84ca-da28350ca850.jpg)
![WoWScrnShot_041021_132723](https://user-images.githubusercontent.com/8245888/114268355-f2da4380-9a00-11eb-8afe-5ab26b41d7a1.jpg)

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=58410
https://woehead.way-of-elendil.fr/?spell=20337
Note : je n'ai pas pu vérifier si l'effet similaire du totem du courroux en chamélem fonctionnait.

**Comment by joshwhedon** [comment]
Deja teste il y a un moment, les deux fonctionnent correctement.

**Comment by Belore** [comment]
Dans ce cas le problème doit être dans le calcul de la répartition des coups blancs. Par exemple dans la capture d'écran ci-dessous, je me suis arrangé pour être overcap crit :
3,5% d'expertise, 7,29%+5% (talent [Précision](https://woehead.way-of-elendil.fr/?spell=13845)) de toucher physique, soit un cap crit à 100-24-(6,5-3,5)-(27-12,29)=58,29%.
J'ai 58,08% + 3% (maître empoisonneur) soit 61,08% de chances de crit. D'après la feuille de calcul des dégâts en coups blancs présentée [ici](https://wowwiki-archive.fandom.com/wiki/Hit), mes dégâts devraient être répartis comme suit :
58,29% de crit,
24% d'érafle,
14,71% de ratés,
3% d'esquives,
0% de touche.
Notamment, 100% de mes attaques qui touchent et ne sont pas érafles devraient être des critiques (principe du cap crit comme expliqué [ici](https://wowpedia.fandom.com/wiki/Critical_strike)), or j'arrive quand même à avoir des touches non critiques :
![WoWScrnShot_041021_144339](https://user-images.githubusercontent.com/8245888/114270173-3b96fa00-9a0b-11eb-9985-21d391a45692.jpg)

**Comment by Belore** [comment]
(NB : j'ai ouvert avec un kriss pour m'assurer que la cible soit constamment empoisonnée, c'était le cas quand les touches non crit sont arrivées.)

**Comment by Belore** [comment]
Update : après plusieurs tests en raid j'ai vu que le cap crit était bien scripté sur les boss de raid, je suppose que ce sont les mannequins d'entraînement qui ne prennent pas en compte les talents mentionnés dans mon ticket.
