### ISSUE TITLE
Sauvegarde du Gestionnaire d'équipement

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1253]
Il est nécessaire de déco/reco à chaque fois pour sauvegarder les nouvelles configurations.

Par exemple si on créé 3 nouvelles configurations et qu'on déco, seule la première est sauvegardée, alors que les deux suivantes ne le sont pas.
Cela impose de déco/reco pour chaque nouvelle création.

_Dans mon cas j'en avais créé 5, du coup un peules nerfs de constater que 4 avaient sautés_ :D

Bon courage.

**Comment by joshwhedon** [comment]
Le gestionnaire d'equipement il est pas gere cote client ?

**Comment by joshwhedon** [comment]
Par exemple si tu change de pc, tu as les memes infos dans le gestionnaire ou c'est reset ?

**Comment by Ferro3** [comment]
_si tu change de pc, tu as les mêmes infos dans le gestionnaire ou c'est reset ?_
aucune idée, il faudrait faire le test.

si le bug ne peut pas être fixé, je propose à minima d'informer qu'une déco/reco est nécessaire avant de pouvoir ajouter une nouvelle configuration.
je sais pas trop, je lance des idées, rien de plus.
