### ISSUE TITLE
Remboursement impossible des pièces achetées avec des emblèmes

### ISSUE THREAD

**Issue by Belore** [way-of-elendil/3.3.5#1255]
**Description**
Les pièces achetées chez les marchands d'emblèmes ne peuvent pas être remboursées.

**Étapes de reproduction**
- Acheter une pièce d'équipement chez un marchand d'emblèmes
- faire un clic droit sur la pièce achetée (ou un glisser-déposer sur l'onglet de revente)

**Comportement attendu**
Un timer permet normalement de se faire rembourser la pièce pendant 120 minutes.

**Comment by Belore** [comment]
J'ai un peu généralisé sans en être sûr, pour être plus précis j'ai rencontré ce problème trois fois, toujours avec des pièces T10 cuir dans le magasin à côté de la banque alliance de Dalaran.

**Comment by joshwhedon** [comment]
La condition c'est pas qu'il faut pas les avoir equipes ou un truc du genre ?

**Comment by Belore** [comment]
Normalement même en les ayant équipées on peut se les faire rembourser, il faut juste ne les avoir ni gemmées ni enchantées !

**Comment by Ferro3** [comment]
j'ai jamais eu le soucis, j'ai toujours pu me faire remboursé les items
du coup je comprends pas, à moins que tu ai gemmé et/ou enchanté le stuff, mais là une fenêtre te précise que tu ne seras pas remboursé

**Comment by Endalaust** [comment]
Lié à https://discord.com/channels/280446236035776512/383201863379582978/902845090609889282 
Il suffit de retélécharger la nouvelle version de l'addon
![screenshot_1674](https://user-images.githubusercontent.com/1420867/151705639-5dc283cb-3e36-4ff3-8cb3-58eca163588a.jpg)
