### ISSUE TITLE
Bug Mot de pouvoir : Robustesse ( Rang 2 ) 

### ISSUE THREAD

**Issue by Erwan-sky** [way-of-elendil/3.3.5#1257]
Le Mot de pouvoir Robustesse rang 2 ne donne que +8 d'endurance au lieu de 10 comme l'indique sa description

**Comment by joshwhedon** [comment]
La description est fixe, elle ne prend pas en compte les valeurs variables par niveau. Dans le cas du mot de pouvoir, le bonus change en fonction du niveau de l'utilisateur (ce sont les donnees cote client en passant, donc correctes par defaut).
