### ISSUE TITLE
Cumul des avantages métiers après oubli

### ISSUE THREAD

**Issue by Subimase** [way-of-elendil/3.3.5#1260]
**Description**
https://www.youtube.com/watch?v=Hu8tJF0wHPU 
en date du 16 avril 2021

**Étapes de reproduction**
Enchantez votre stuff avec le métier d'ingénieur. 

Oubliez votre métier d'ingénieur

Utilisez vos bottes fusées. 

A voir si reproductible avec les enchantements des autres metiers

**Comportement attendu**
Les avantages des métiers ne s'activent plus une fois le métier oublié

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?v=Hu8tJF0wHPU 
en date du 16 avril 2021

**Comment by joshwhedon** [comment]
Faut prouver que c'est un bug. Parce que appliquer enchantements et autres, oui on peut pas, mais il n'y a rien sur les enchantements eux meme qui sert de prerequis.

**Comment by Endalaust** [comment]
Offle: I think it's enough since they means already enchanted cloak > The cloak can only be used once a minute and requires an Engineering skill of at least 350.

 Offle: you can check https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?enchantments&filter=cr=4;crs=1;crv=0 to be sure

 Offle: same story https://www.wowhead.com/spell=55016/nitro-boosts#comments

=> On voit que les enchantements ont un requirement sur le skill + le niveau du skill

**Comment by joshwhedon** [comment]
Rien a voir, ces conditions c'est pour appliquer les enchantements. Il faut encore prouver que les enchantements ne doivent pas etre actifs / utilisables si le joueur n'a plus la profession.

**Comment by Justforsoloq** [comment]
Alors j'ai pas encore fait de recherches, mais dans le cas de la forge c'est pareil (sauf que ça marche sur woe, si t'oublies forge t'as encore les slots mais ils ne sont plus comptés me semble non ?). J'imagine qu'ingé ça devrait être pareil ? Pas sûr de ça c'est le genre de truc un peu niche qu'il faudrait que je check

**Comment by Justforsoloq** [comment]
J'ai pas vu de topics offi parlant de stack métier (ce qui ferait sens sinon, tu prends ingé tu prends les enchant ingé puis swap métiers). Quasiment sûr que c'est pas normal et que comme TOUS les autres métiers tu es censé perdre l'effet/effet inutilisable même si il est posé sur le stuff

**Comment by Justforsoloq** [comment]
https://wowwiki-archive.fandom.com/wiki/Engineering
Note that these cannot be put onto items presented in a trade window. While they can be put on BoE items, they offer no benefit to non-engineers (or Engineers who have not met the required skill level), so the market for them is limited.

**Comment by joshwhedon** [comment]
Non rien a voir, ils ne peuvent pas etre applique sur un objet possede par quelqu'un qui n'a pas la profession (tu peux tester c'est le cas sur woe aussi).

**Comment by Satarians** [comment]
tu l'applique puis tu oublie le metier ,l'enchant reste, pyro botte fusée ceinture ingé cape parachute, par contre les bonus partent pour le crit ect apres les autres metier i dont know

**Comment by Subimase** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Profession 

"You can drop primary professions, freeing up the profession slot, but you lose the knowledge and experience within the profession; if you take it again later, you will start over from scratch. Secondary professions cannot be dropped, and there would be little point in doing so"

**Pour enchanter, effectivement, il faut le pré requis d'avoir le niveau dans le métier.** 

Pour le use, faut-il avoir le niveau du skills ? C'est une autre histoire. 
https://www.mmo-champion.com/threads/621171-WotLK-Profession-List-w-passive-buffs! : "Only Engineers can use these activated abilities, and they replace the traditional enchants." 

https://wowwiki-archive.fandom.com/wiki/Profession 
"The downside is that you lose all of your built up skill and recipe knowledge"

**Comment by Subimase** [comment]
https://www.mmo-champion.com/threads/621171-WotLK-Profession-List-w-passive-buffs! : "Only Engineers can use these activated abilities, and they replace the traditional enchants." 

Je ne trouve que ce lien pour le moment. Mais à étayer... 
Quoi qu'il en soit, si le cumul des métiers sont dispos et n'est pas considéré comme du BA, je vais me faire un plaisir d'aller chercher des opti plus poussées pour taper 25K sur roi liche en stuff full 264 nm et je vais peut-être me mettre au PvP aussi. J'aurai un avantage certains face à mes concurrents. 

Merci à tous ! 🥇

**Comment by Wilpok** [comment]
![image](https://user-images.githubusercontent.com/65713751/115389306-35f49d80-a1dd-11eb-8e42-a1e462799b98.png)

un autre exemple et ce qu'a link subimase ci dessus est suffisant normalement cf 
![image](https://user-images.githubusercontent.com/65713751/115389588-8e2b9f80-a1dd-11eb-9a29-1223d28962ee.png)
Sachant que justement sur l'item il est bien indiqué que la compétence est nécessaire à son utilisation 
![image](https://user-images.githubusercontent.com/65713751/115389818-d945b280-a1dd-11eb-8de1-6b53ccfd39f0.png)

**Comment by joshwhedon** [comment]
Vous etes pas en train de m'emmerder pour rien ? Je viens de tester 3 enchantements. dont nitro boost, et ca marche parfaitement. Si j'oublie ces metiers, je peux plus utiliser l'enchantement de l'objet.

**Comment by Subimase** [comment]
La video date dil y a 4 jours. Si je voulais me moquer, je ne ferai pas ce post.

Moi ce que je vois c'est que droodquipeu est herbo et forgeron IG et sur le site way of elendil
https://way-of-elendil.fr/armory/character/565585-droodquipeu

Et que sur la vidéo qui date d il y a 4 jours, il utilise les bottes fusées et la cape ingénieur.

**Comment by joshwhedon** [comment]
Bah je sais pas comment tu as fait ca, mais moi si j'oublie un metier, quel qu'il soit, j'ai la meme chose que Wilpok, tout est en rouge et innutilisable.

**Comment by Subimase** [comment]
Il s'appelle @titan sur le discord.

Je peux pas te donner plus d'informations sur la manière dont il utilise ses bottes car il ne me l'a pas expliqué.

**Comment by Satarians** [comment]
bah il les use

**Comment by Satarians** [comment]
jpeux montrer ingame l bug si vous voulez

**Comment by Satarians** [comment]
tu click sur l'item ca botte fusée pyro veinture, ya que les bonus crit et les gant hate qui marche pas

**Comment by Satarians** [comment]
![WoWScrnShot_042021_141142](https://user-images.githubusercontent.com/63306263/115393869-74408b80-a1e2-11eb-86dc-23049794c714.jpg)
![WoWScrnShot_042021_141124](https://user-images.githubusercontent.com/63306263/115393873-7571b880-a1e2-11eb-9c7a-8795c9e800ed.jpg)

**Comment by Briznuits** [comment]
> Bah je sais pas comment tu as fait ca, mais moi si j'oublie un metier, quel qu'il soit, j'ai la meme chose que Wilpok, tout est en rouge et innutilisable.

Ta essayer sur le vrai serveur ? Le bug est peut-être pas présent sur le dev.

**Comment by Endalaust** [comment]
Testé en production sur un personnage de test, ce bug n'existe pas.

En revanche des interventions manuelles de maître de jeu dans le passé ont provoquées des anomalies sur des anciens joueurs dont celui cité en exemple. Une intervention spéciale a été effectuée sur lui pour corriger le tir.

**Comment by Subimase** [comment]
Merci ! :)
