### ISSUE TITLE
[Chasseur] Bug de l'utilisation de "Salve" en combinaison avec "Détournement"

### ISSUE THREAD

**Issue by Freyahh** [way-of-elendil/3.3.5#1261]
**Édité le 20/04/2021 en réponse à la demande de josswhedon.**

**Description**

Au cours de mes aventures avec mon chasseur, j'ai pu voir à plusieurs reprises et depuis plusieurs années que l'utilisation du sort "Salve" du chasseur est buguée en combinaison avec le lancement du sort "Détournement". En effet, lorsque l'on lance "Détournement" sur un personnage ou un familier, puis que l'on lance "Salve" par la suite, **le renvoi de l'aggro de "Détournement" s'exécute directement au tout début de "Salve" et non au moment où les premiers dégâts sont générés, ce qui n'est absolument pas normal**. Cela représente une perte de génération d'aggro par "Détournement" considérable. Je pense que le script de l'utilisation du sort "Salve" considère l'exécution comme une attaque alors que **cela devrait être les premiers dégâts générés par "Salve"**. Ce bug est présent sur le serveur depuis de nombreuses années.

**Étapes de reproduction**

1. Être en groupe avec une ou plusieurs personnes ou bien posséder un familier ;
2. Lancer le sort "Détournement" sur une personne du groupe ou sur un familier ;
3. Lancer le sort "Salve" sur un mob ou un groupe de mobs ;
4. Se rendre compte de l'apparition du renvoi de l'aggro de "Détournement" (aura) directement au tout de début de l'exécution de "Salve" alors que **cela ne devrait se produire QUE lorsque les premiers dégâts de "Salve" sont générés**.

**Comportement attendu**

En temps normal, lorsque l'on utilise le sort "Salve" après avoir lancé le sort "Détournement", le renvoi de l'aggro devrait s'exécuter SEULEMENT lorsque les premiers dégâts de "Salve" sont générés, et non au tout de l'exécution, ce qui représente une perte de génération d'aggro par "Détournement" considérable.

**Captures d’écran / Vidéos**

- Icecrown AoE Grinding - Hunter (14 déc. 2009) : https://www.youtube.com/watch?v=Rzbl_2uyuUc

**Ressources additionnelles**

Sort "Salve" :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=58434
- WoW Head : https://fr.wowhead.com/spell=58434

Sort "Détournement" (sort à lancer) :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=34477
- WoW Head : https://fr.wowhead.com/spell=34477

Aura "Détournement" (aura qui apparaît après lancement du sort "Détournement" en lançant ensuite le sort "Salve") :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=35079
- WoW Head : https://fr.wowhead.com/spell=35079

**Comment by joshwhedon** [comment]
Va falloir prouver qu'il s'agit d'un bug. La salve, comme la plupart des sorts, genere un agro initial des que le sort est lance sur la cible, meme si ce sort ne fait pas de degats immediatement. Tout comme les dots en gros. Donc si la salve est lance, un agro de base sera genere.
De la meme facon que, si vous attaquez une cible avec la salve, il me semble que la cible vous attaquera immediatement avant meme que les degats n'aient lieu. Est-ce que c'est un bug ? Je sais pas il va falloir le prouver.

**Comment by Freyahh** [comment]
Bonjour joshwehdon ! Merci beaucoup pour votre réponse :-)

Comme vous l'avez demandé, j'ai donc recherché une preuve qui démontre que le sort "Détournement" ne se déclenche avec le sort "Salve" QUE lorsque "Salve"commence à faire du dégât.

Voici donc **une vidéo datée du 14 Décembre 2009 que j'ai trouvé sur Youtube**, et qui montre parfaitement le fonctionnement que j'ai décrit dans ce ticket : 

**Icecrown AoE Grinding - Hunter (14 déc. 2009) : https://www.youtube.com/watch?v=Rzbl_2uyuUc**

Et logiquement, les cibles ne devraient pas attaquer le chasseur à l'exécution de la "Salve", mais seulement lorsque cette dernière commence à faire des dégâts.

Ainsi, il s'agit bel et bien  d'un bug présent sur le serveur, et doit donc être corrigé ;-)

Merci pour votre compréhension !

**Comment by Ferro3** [comment]
vérifié, fix ok
