### ISSUE TITLE
Le Trigger dans l'échoppe des héros ne me capte pas en tant que h² et me laisse entrer dans la taverne

### ISSUE THREAD

**Issue by ggdusetsett** [way-of-elendil/3.3.5#1262]
Bonjour,
Je viens de m'apercevoir que le trigger sensé ne pas me laisser rentrer en tant que h² dans l'échoppe des héros ne me capte que dans le sens retour mais plus dans le sens aller 
Je peux donc rentrer dans un endroit que je ne devrais pas 
![image](https://user-images.githubusercontent.com/82815282/115231414-d1224000-a115-11eb-93d1-3f4c752a772d.png)

**Comment by Endalaust** [comment]
Suite à la release embarquant le fix :
Way Of Elendil: Goune(A:80): je ne peut pas aller chercher la cruche de vin a la fromagerie il me tp comme si je passais dans la zone h2

https://cdn.discordapp.com/attachments/488586498942173194/942646816271368242/Capture_decran_53.png 
J'ai revert le commit et réouvert le ticket

**Comment by Endalaust** [comment]
Pas sur de piger le fix, c'était des a2 qui ne pouvaient plus rentrer dans certaines zones comme celles mentionnées ci dessus

**Comment by Ferro3** [comment]
le bug déclaré est : les hordeux peuvent entrer dans l'auberge des alliancieux, ça c'est pas normal
_du coup je ne comprends pas vraiment pourquoi l'autre coté de Dalaran a eu des problèmes (y a surement une bonne raison)_

**Comment by Ferro3** [comment]
vérifié, fix à revoir :
https://i.postimg.cc/L4J59hrd/Wo-WScrn-Shot-021622-172935.jpg
