### ISSUE TITLE
Ténacité en champ de bataille

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#1263]
**Description**
Il est possible d'avoir le buff ténacité même en étant en champ de bataille ( en goulet / arathi etc .... )

**Étapes de reproduction**
1 ) Entrer dans le joug et avoir un buff ténacité ( qu'importe le nombre de stacks )
2 ) Tag en champ de bataille pendant le joug et rentrer dans le bg quand ça proc
3 ) Lorsqu'un changement de stacks de ténacité se produit au joug ( par exemple la ténacité passe de 3 stacks à 4 ) le joueur qui est en bg reçoit la ténacité également ( je pense qu'il est encore considéré comme étant inscrit et participant au joug car il à accès au chat de l'équipe du joug et de celui du bg en même temps ( /raid pour le joug et /bg pour l'équipe en bg ))

**Captures d’écran / Vidéos**
Exemple là où j'étais en bg et au joug un changement de téna à eu lieu au joug et je me suis retrouvé avec 6 stacks en bg 
https://ibb.co/FqPGjdP

**Ressources additionnelles**
A noté que le fait de déco/reco permet d'enveler les stacks de téna en bg mais si un autre changement de téna se produit au joug alors le joueur reçoit à nouveau la téna. Il est obligé d'attendre soit que le joug se termine , soit il est obligé de quitter le bg

**Comment by Endalaust** [comment]
Fixé prochain redémarrage.
