### ISSUE TITLE
Perte de caractéristique en changeant d'arme sur war

### ISSUE THREAD

**Issue by Oradruine** [way-of-elendil/3.3.5#1264]
**Description**
En switchant d'une arme à une autre, certaines caractéristique descendent grandement. Au début j'ai cru que ce n'était que visuel, mais après test, ce n'est pas le cas.
**Étapes de reproduction**
J'ai remarqué la chose sur mon war arme, avec spé pve 55, 8, 8. En faite, il suffit simplement de passer d'une arme à une autre. La caractéristique de dégâts va diminuer, elle changera de couleur également. Normalement, elle devrait être augmenté à 106% due au talent spécialisation arme à 2 mains, mais ce n'est plus le cas. De plus, on peut remarqué une chute énorme de critique (environ 10%). Cette baisse n'est pas que visuelle, j'ai plus de 50% critique, avec le talent fulgurance améliorée, mes fulgurance devrait être toujours critique, mais avec cette baisse de 10% (qui me fait passer dessous des 50), j'ai des coups non critique. 
J'ai l'impression que le problème est encore plus important que ça, car vraiment chaque attaque fait vraiment moins mal et si on trouve la différence des 10% de crit, il semblerait que le talent hache d'hast ne fonctionne tout simplement pas, mais sans la correction des dégâts et crit actuelle, impossible de confirmer ma crainte.

**Comportement attendu**
Les caractéristiques devraient être maintenue

**Captures d’écran / Vidéos**
![image](https://user-images.githubusercontent.com/82836101/115283176-507e3680-a14b-11eb-81e9-ee34bacbfc8c.png)

![image](https://user-images.githubusercontent.com/82836101/115283288-73104f80-a14b-11eb-8216-a154c389d82d.png)

**Comment by Goudronaide** [comment]
il ne faut pas que tu switch en passant par le alt via la fiche personnage, sinon le truc ne prend pas en compte tes bonus de crit via les talents. C'est la depuis un moment que c'est présent.

**Comment by joshwhedon** [comment]
Jamais entendu parler de ce bug :D . Et je dirai ... je savais meme pas qu'on peut appuyer sur alt pour changer d'equipement.

**Comment by joshwhedon** [comment]
Corrige prochaine maj
