### ISSUE TITLE
Colère divine: fonctionnement incorrect

### ISSUE THREAD

**Issue by Krunkss** [way-of-elendil/3.3.5#1265]
Description :

La colère divine est sensée infliger des dégâts sans appliquer de stun sur les Draconiens, ce n'est pas le cas sur WOE.

Étapes de reproduction :

Prendre un paladin, aller a halion et pull l'un des draconiens présents sur place, lancer une colère divine. Les ennemis ne subiront pas de dégats.

Comportement attendu :

Les draconiens sont supposés subir des dégats sans prendre le stun, qui ne s'appliquera que sur les morts-vivants et les démons.

Captures d’écran / Vidéos :

https://youtu.be/dZvWfZ5W9XE
un testeur PTR faisant le test sur Saviana. 

Ressources additionnelles :

Log offi de 2010 où halion et certains adds présents dans l'instance subissent des dégâts de Colère Divine : 
http://www.worldoflogs.com/reports/hzc74vjkdkeuty5h/spell/2812/?enc=wipes&boss=39863
http://www.worldoflogs.com/reports/nto52cqkkomxtajp/spell/2812/?s=1927&e=2290
http://www.worldoflogs.com/reports/udxwv9mvwyldzwjl/spell/2812/?s=6145&e=6440

logs à Onyxia :
http://www.worldoflogs.com/reports/lr6bybaf7wsj1lh2/spell/2812/?s=6570&e=7320

à L'Oeil de l'Eternité :
http://www.worldoflogs.com/reports/ea5l9ef84cy2egqj/spell/2812/?s=813&e=1175
les adds de Malygos prennent aussi des dégâts de Colère mal grès le fait qu'ils soient humanoïdes ( https://woehead.way-of-elendil.fr/?npc=30249 )

à Sartharion : 
http://www.worldoflogs.com/reports/6e8xi9aufe25owl6/spell/2812/?s=5420&e=5496

--
Le général Vezax a Ulduar semble également prendre des dégats de la colère divine 
http://www.worldoflogs.com/reports/rt-l7taotzd4qeo25bx/spell/2812/?s=3196&e=3501 
ainsi que ses adds qui sont pourtant de classe humanoide https://woehead.way-of-elendil.fr/?npc=33818 

autre log Vezax : http://www.worldoflogs.com/reports/vacgagz6aavzy3iy/spell/2812/?s=8895&e=9245

Vezax : https://woehead.way-of-elendil.fr/?npc=33271 (classe non spécifiée)

Yogg-Saron et ses adds : http://www.worldoflogs.com/reports/esx32f7nw1y54e1y/spell/2812/?s=9487&e=9630
autre log Yogg : http://www.worldoflogs.com/reports/rt-eefs3bfxqdjust5i/spell/2812/?s=7811&e=7941

Yogg : https://woehead.way-of-elendil.fr/?npc=33288 (classe non spécifiée)

Freya et ses adds : http://www.worldoflogs.com/reports/rt-paayf0uxq32lpnfd/spell/2812/?s=3974&e=4114
http://www.worldoflogs.com/reports/o3ctb9yir5fwe988/spell/2812/?s=4591&e=4716
http://www.worldoflogs.com/reports/rt-vwefzb0ppk38d1qd/spell/2812/?s=3684&e=3939

Freya : https://woehead.way-of-elendil.fr/?npc=32906 (classe Géants)
adds de Freya : https://woehead.way-of-elendil.fr/?npc=32919 
https://woehead.way-of-elendil.fr/?npc=32918
https://woehead.way-of-elendil.fr/?npc=33203
https://woehead.way-of-elendil.fr/?npc=33202
(classe Elémentaires)

Thorim et ses add : http://www.worldoflogs.com/reports/rt-w6iatnqxn2m9jde0/spell/2812/?s=1589&e=1695
http://www.worldoflogs.com/reports/rt-cp7zy1hd0yhhlaln/spell/2812/?s=1825&e=1929
http://www.worldoflogs.com/reports/dhrj1ahi0hrzybdm/spell/2812/?s=4932&e=5037

Thorim : https://woehead.way-of-elendil.fr/?npc=32865 (classe Géants)
Champion Sombre-rune : https://woehead.way-of-elendil.fr/?npc=32922 (classe Humanoïde)
Evocateur Sombre-rune : https://woehead.way-of-elendil.fr/?npc=32924 (classe Humanoïde)

Hodir : http://www.worldoflogs.com/reports/tokf9hm2xt1d1n0c/spell/2812/?s=1696&e=1801
http://www.worldoflogs.com/reports/9q27m55capm65erw/spell/2812/?s=2545&e=2649
http://www.worldoflogs.com/reports/rt-9c5jlf1r35gsiujy/spell/2812/?s=2257&e=2361

Hodir : https://woehead.way-of-elendil.fr/?npc=32845 (classe géants)

Mimiron et ses adds: http://www.worldoflogs.com/reports/rt-t0fl8dhof93fcbe4/spell/2812/?s=1955&e=2332
http://www.worldoflogs.com/reports/9rd7icolhwrsno85/spell/2812/?s=5188&e=5581
http://www.worldoflogs.com/reports/ntz9527xka5f7zop/spell/2812/?s=9268&e=9663

Mimiron : https://woehead.way-of-elendil.fr/?npc=33350 (classe Mécaniques)
Robot d'assaut : https://woehead.way-of-elendil.fr/?npc=34057 (classe Mécaniques)
Robot-ferailleur : https://woehead.way-of-elendil.fr/?npc=33343 (classe Mécaniques)

Algalon : http://www.worldoflogs.com/reports/n5wi9hfo8nipfo3t/spell/2812/?s=11227&e=11484
http://www.worldoflogs.com/reports/5syzeod64ps12uv8/spell/2812/?s=10969&e=11227
http://www.worldoflogs.com/reports/n1tie8c2x9ahy9fx/spell/2812/?s=2558&e=2816

Algalon : https://woehead.way-of-elendil.fr/?npc=32871 (classe Elémentaires)

En conclusion contrairement à ce que je croyais au début du ticket et après un long moment a disséquer des logs, la Colère Divine infligeait bien sur offi des dégats a d'autres classes d'ennemis que les mort-vivants, les démons et les draconiens. 

Pour en faire la liste de manière plus concise, Draconiens, Géants, Elémentaires, Mécaniques, Humanoïdes et (je suppose) Aberrations étant donné que je n'ai pas pu déterminer la classe de créatures de Yogg Saron et Vezax.

Cette liste concerne bien sûr les personnages non-joueurs. 
Les personnages-joueurs ne devraient pas être impactés par ce fonctionnement incorrect.

Je précise que tout les logs link ici sont d'officiel, en 2010.

Merci d'avoir pris le temps de lire et d'examiner les preuves présentées, ce qui était au départ un ticket relativement simple fait maintenant 800 lignes.

**Comment by joshwhedon** [comment]
Desole mais non, ca ca ne sera pas change. Ces logs sont definitivement incorrects. Je ne sais pas d'ou viennent ces logs, mais il est impossible que ce sort touche quoi que ce soit d'autre que demons et mort vivants. Non seulement les donnees clients sont claires la dessus : Creature Type Mask = 0x00000024 (DEMON, UNDEAD), mais en plus la description du sort, que ce soit en anglais ou en francais, ne pose aucun doute sur les cibles valides. Et aucune discussion n'encourage l'utilisation de ce sort dans des donjons tels que ceux ci.
Desole pour tous les efforts qui ont ete fait pour recolter ces donnees, j'ai aucune idee de comment ca a pu arriver, mais ces logs sont definitivement foireux.

**Comment by Wilpok** [comment]
Pour le coup ce sont des logs d'officiel, je prendrai le 1er de No chicks Allowed sur Crushridge qui a fait au moins top 50 sur tous les palliers de wotlk, https://www.wowprogress.com/guild/us/crushridge/No+Chicks+Allowed . Le bug est présent sur l'entièreté des Pserv que j'ai pu faire, alors p-e que la base est erronée (je ne sais absolument pas comment ça marche), de plus le tooltip est justement douteux en se fiant a woehead : 

![image](https://user-images.githubusercontent.com/65713751/116782203-0fa9ea00-aa88-11eb-8202-07fe34648408.png)
il y a bien un "." qui note les deux fonctionnements différents de la colère divine. ils fait des dégâts en aoe, et également stun les morts vivants et demons. 

https://woehead.way-of-elendil.fr/?spell=48817

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?spell=2812#see-also je remarque que le rang 1 a une description differente. Donc ca se peut que ca ait change avec les patchs ? Je reouvre et je rechercherai des truc en plus.

**Comment by Krunkss** [comment]
Donc tu pense que tout les logs que j'ai link, sur une grande partie des boss de plusieurs tiers de raid, avec minimum deux logs pour chaque exemple, tous datés de 2010 sur wol
sont tous foireux

j'ai justement fait gaffe a ce que chaque guilde dont les logs sont tirés avaient bien une présence sur retail a l'époque sur tlk

j'ai passé une aprem a faire ça ça serait vraiment cool de pousser la recherche jvois si y'a pas un truc sur les patch logs

**Comment by joshwhedon** [comment]
Je pense que c'est pas impossible oui. Par exemple, si le parser gerait mal ce sort en particulier due justement a son mechanisme de ciblage. Ce serait pas la premiere fois. Quant aux patch notes, j'ai deja fouille et rien trouve du tout concernant un changement, et a vanilla le sort ciblait uniquement les demons / undead et etait canalyse.

**Comment by Wilpok** [comment]
Tooltip sur WoE : 
Rang 1 : 
![image](https://user-images.githubusercontent.com/65713751/116782953-57cb0b80-aa8c-11eb-95bb-8760e362df4c.png) 

Rang 5 : 
![image](https://user-images.githubusercontent.com/65713751/116782968-66192780-aa8c-11eb-8411-d7ac104ce787.png)

Les memes (sur un client anglais en tout cas j'ai pas pour le français)

Et pour les patchs, y'a juste ceci : 
![image](https://user-images.githubusercontent.com/65713751/116783015-b09aa400-aa8c-11eb-8f75-a9debc1240ab.png)

**Comment by Wilpok** [comment]
![image](https://user-images.githubusercontent.com/65713751/116783048-eb9cd780-aa8c-11eb-85c2-40cd92855d05.png)
Tooltip de BC, il a bien changé de tbc à wotlk il y a une différenciation entre stun et dégâts à partir de wotlk

**Comment by joshwhedon** [comment]
Pourquoi avoir refermé alors que j'ai réouvert ?
