### ISSUE TITLE
La cape d'ombre n'enlève pas la "web" du pet araignée

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#1270]
**Description**
La cape d'ombre n'enlève pas la toile de l'araignée (pet) du chasseur.

**Étapes de reproduction**
Prenez un chasseur avec l'araignée, utilisez le sort "toile" sur un rogue, utilisez cape d'ombre, et observez.

**Comportement attendu**
La cape d'ombre vire la toile.

**Ressources additionnelles**
https://wowwiki-archive.fandom.com/wiki/Web

**Comment by Freyahh** [comment]
Voici quelques ressources additionnelles pour aider à la résolution de ce bug :

**Ressources additionnelles :**

Sort "Cape d'ombre" :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=31224
- WoW Head : https://fr.wowhead.com/spell=31224

Sort "Serverside - Cloak of Shadows" (sort d'activation de "Cape d'ombre") :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=35729
- WoW Head : https://fr.wowhead.com/spell=35729

Sort "Rets" (sort de l'araignée en tant que familier) :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=745
- WoW Head : https://fr.wowhead.com/spell=745

**Comment by Justforsoloq** [comment]
J'aurais pu effectivement mettre les liens pour la CoS en plus.

**Comment by Justforsoloq** [comment]
Par contre les liens que tu as mis pour le sort de l'araignée n'est pas bon je pense :x 
Tu as mis "rets" alors que le sort se nomme "web"
https://wowpedia.fandom.com/wiki/Web_Spray
https://wowpedia.fandom.com/wiki/Web

**Comment by Freyahh** [comment]
Bonsoir Justforsoloq :-)

Oui c'est bien le même sort ;-)

Voici le lien en anglais : 
- WoW Head (anglais) : https://www.wowhead.com/spell=745/web

**Comment by Justforsoloq** [comment]
Ouais donc en attendant que j'trouve plus d'info, si le web est sur le même modèle exact que le pin du crabe on peut fermer ce BT pour faute de preuves plus concrètes :x

**Comment by joshwhedon** [comment]
Oui ce "bug"a deja ete signale, et la comparaison a ete donne.
