### ISSUE TITLE
Ulduar / Thorim / activation du levier 

### ISSUE THREAD

**Issue by Lirae** [way-of-elendil/3.3.5#1274]
**Description**
Le levier du couloir sur Thorim est activable dès l'engagement des mobs au milieu de l'arène au lieu d'être activable lorsque le dernier mob meurt. Cette activation n'est possible que lors du premier try sur Thorim.

**Étapes de reproduction**
- Ulduar / Thorim en 10 ou 25
- Lors du premier try, le levier est accessible au clic dès l'engagement des mobs dans l'arène

**Comportement attendu**
Le levier devrait être activable uniquement à la mort du dernier mob présent dans l'arène.

**Captures d’écran / Vidéos**
Vidéo de l'époque montrant que le levier n'est pas activable avant la mort du dernier trash :
https://www.youtube.com/watch?v=o4__jtI--N0

Au besoin, nous allons à Ulduar 25 tous les vendredi à 21h si un test sur le terrain est nécessaire.

**Comment by Freyahh** [comment]
Voici quelques ressources additionnelles pour aider à la résolution de ce bug :

**Ressources additionnelles :**

Entité "Levier" :
- WoE Head : https://woehead.way-of-elendil.fr/?object=194264
- WoW Head : https://fr.wowhead.com/object=194264

PNJ "Thorim" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=32865
- WoW Head : https://fr.wowhead.com/npc=32865
