### ISSUE TITLE
Piège explosif ne se déclenche pas (disparaît)

### ISSUE THREAD

**Issue by Sephistos** [way-of-elendil/3.3.5#1275]
**Description**
Lorsqu'on pose le Piège Explosif ( https://woehead.way-of-elendil.fr/?spell=49067 ), le piège se pose normalement (trace de la pose dans le journal de combat) et lorsqu'il doit se déclencher il disparaît sans raison de façon plus ou moins aléatoire.

**Étapes de reproduction**
https://woehead.way-of-elendil.fr/?spell=49067

Posez simplement le piège et priez pour qu'il se déclenche normalement. 

J'ai remarqué que le bug se répète à 100% si on pose le piège au même endroit. Le bug semble apparaître beaucoup plus souvent en donjon/grotte qu'en open world. Le piège se pose bien sur le sol (visuel + journal de combat) avant le bug, c'est lors du déclenchement qu'il disparaît (sur le journal il n'y a rien de marqué comme quoi le sort est "raté"/"résiste"/"esquive" ou autre). 

**Comportement attendu**
Le piège se déclenche et créé une zone de dégât de feu

**Captures d’écran / Vidéos**
 https://youtu.be/LekjEOrFF0M Premier test réalisé dans la _Marche de l'Ouest_ (Mine Veine de Jango) 10 pièges posés, 9 pièges bugués

https://youtu.be/Q3HLHPehzxQ Deuxième test dans la _Marche de l'Ouest_ (entrée Mine Veine de Jango) 6 pièges posés (3 dans la mine, 3 à l’extérieur, 3 bugs dans la mine, 0 bug à l’extérieur)

https://youtu.be/d4WY-3lt46I Troisième test sur des mannequins à _Hurlevent_ 10 pièges posés, 5 bugs
 
https://youtu.be/6Yng2PBQi94 Quatrième test dans un donjon (Souilles de tranchebauge), j'ai dis en /s "echec du piège" à chaque fois que le bug est présent. On peut également constater qu'il n'est du coup pas affiché sur Skada

**Comment by joshwhedon** [comment]
Ouai malheureusement c'est des soucis au niveau des maps, on y peut rien,

**Comment by Traesh** [comment]
Je n'ai malheureusement jamais réussi à reproduire malgré les vidéos, serait-il possible de retester à ce jour pour voir si quelque chose à changer sur cette issue ?

Sinon, me refaire une vidéo avec l'emplacement et toutes les infos du perso (level + stats + talents)

**Comment by Ferro3** [comment]
vérifié ce jour : toujours actif
test sur "mannequin entraînement de grand maître" à lune d'argent
10 posés 5 échecs

**Comment by Sephistos** [comment]
Pour l'avoir rejoué aujourd'hui, j'ai remarqué que ça arrivait tout le temps lorsque qu'il y a une "texture rajouté" au sol, style les sols rocheux dans des cavernes, tous les sols à ICC, sur un sol "normal" le piège fonctionne correctement. (d'après ce qu'on m'a expliqué dans le premier cas, le piège semble traverser le sol au moment du déclenchement)

**Comment by Sephistos** [comment]
https://youtu.be/ZKvKu8zEjWk 

Comme écrit dans la description, le premier cas le piège fonctionne, le deuxième non, exactement comme je l'ai décrit plus tôt

> Pour l'avoir rejoué aujourd'hui, j'ai remarqué que ça arrivait tout le temps lorsque qu'il y a une "texture rajouté" au sol, style les sols rocheux dans des cavernes, tous les sols à ICC, sur un sol "normal" le piège fonctionne correctement. (d'après ce qu'on m'a expliqué dans le premier cas, le piège semble traverser le sol au moment du déclenchement)

**Comment by Traesh** [comment]
Un grand merci à vous deux pour les infos, j'ai réussi à reproduire à 100% au spot de Fléaulme :)

Corrigé au prochain patch après validation par Josh

**Comment by Ferro3** [comment]
vérifié
fix ok
