### ISSUE TITLE
Gardien des âmes manquant

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1276]
Le soucis se situe à la Toundra Boréenne
You are outdoors.
15:53:52 Map: 571 (Norfendre) Zone: 3537 (Toundra Boréenne) Area: 3537 (Toundra Boréenne) Phase: 1
15:53:52 X: 2006.869141 Y: 5934.063965 Z: 37.258095 Orientation: 2.423271
15:53:52 grid[35,43]cell[6,1] InstanceID: 0
15:53:52  ZoneX: 45.740849 ZoneY: 75.214241
15:53:52 GroundZ: 37.259369 FloorZ: 37.259369 Have height data (Map: 1 VMap: 1 MMap: 1)
Lorsque l'on meurt à proximité de cette zone, après avoir libéré nous nous retrouvons aux coordonnées ci-dessus. Une icône montre la présence d'un gardien des âmes sur la mini map. En réalité il n'y en a aucun. J'ai check en gm on et off rien n'y change.
Sur woehead voici l'emplacement des gardiens des âmes https://woehead.way-of-elendil.fr/?npc=6491
On remarque en effet l'absence de gardien ici : (croix rouge)
![image](https://user-images.githubusercontent.com/60304524/115996683-94a48780-a5e0-11eb-862c-dcb153d696db.png)
Voici à titre d'information ce qu'indique wowhead; On voit bien ici la présence du gardien.
![image](https://user-images.githubusercontent.com/60304524/115996721-c3baf900-a5e0-11eb-8a40-03fdae6cfbb1.png)

**Comment by Endalaust** [comment]
Fixé prochain redémarrage.
