### ISSUE TITLE
Bug [Nerfs d'acier glacé] Dk givre

### ISSUE THREAD

**Issue by Unleashedzer** [way-of-elendil/3.3.5#1277]
**Description**
Le talent Nerf d'acier glacé : https://woehead.way-of-elendil.fr/?spell=50138 ne semble pas fonctionner correctement en ce qui concerne l'augmentation des dégats de l'arme en main gauche de 25%.

Sur l'anéantissement : a priori inactif ; les dégats de la OH sont à hauteur d'environ 50% de la MH, alors qu'ils devraient atteindre les 75%

**Étapes de reproduction**
Utiliser un DK givre de niveau 80  avec 3/3 dans Nerfs d'acier glacé, et copmparer les dégats d'anéantissement entre les deux mains (idéalement ; utiliser des logs)

**Comportement attendu**
Le talent doit augmenter les dégats de l'anéantissement sur l'OH de 25%

**Captures d’écran / Vidéos**
Je vous mets ci-joints des captures de logs enregistrés.

L'un étant tiré d'un de mes combats sur Halion 25h sur Elendil, les deux autres provenant d'un DK givre d'officiel (datant de 2010)
Mes logs : 
![Unleash](https://user-images.githubusercontent.com/83283078/116233281-64352880-a75b-11eb-97f3-e1b625cb1b48.PNG)

Logs de Mca, dk givre sur officiel à l'époque :
![mca1](https://user-images.githubusercontent.com/83283078/116233249-5b445700-a75b-11eb-8f5c-d74e9f22cd31.PNG)

![mca2](https://user-images.githubusercontent.com/83283078/116233304-69927300-a75b-11eb-8a03-a13b1651c506.PNG)

Nous voyons bien sur ces logs que mes dégâts d'anéantissement en OH sont à hauteur d'environ 50% de la MH (ou à peine plus, alors que mes deux armes sont identiques), comparativement à ceux de Mca où on est bien aux alentours de 75% des dégats de la MH.
L'idéal ici serait donc de faire en sorte que les dégats de l'anéantissement prennent en compte ce talent.

Voilà ce sera tout, merci !

**Comment by Unleashedzer** [comment]
svp

**Comment by Unleashedzer** [comment]
svp

**Comment by Zaralbahk** [comment]
up, tjs d'actualité

**Comment by Dkux-Holux** [comment]
UP

Les dégâts d'Anéantissement de la main gauche sont plus proche des 55% de l'Anéantissement main droite que des 75%. (Halion 25h du 09/02/2022, avec 2 Lame de la Vénéneuse héroîque)

Moyenne main droite : 12 798
Moyenne main gauche : 7 012 (12 798*0.55 = 7 038)

Moyenne main gauche (théorique) : 12 798*0.75 = 9598

![WoWScrnShot_021022_160539](https://user-images.githubusercontent.com/99414787/153435614-d096cc48-b37f-4cd3-9f3e-a1ebb83f79b1.jpg)
![WoWScrnShot_021022_160545](https://user-images.githubusercontent.com/99414787/153435619-56eb3249-64e7-44e5-8682-0c4632440194.jpg)

**Comment by Justforsoloq** [comment]
Petite précision (d'ailleurs la preuve est aussi dans les screen d'Unleash), le nerf d'acier sur WoE up la frost strike (probablement double dipping dessus)
(cf les deux WoL : woe FS MH 7.6%, FS OH : 7.3%, Wotlk retail : FS MH 8.2% FS OH 5.2%)

**Comment by Traesh** [comment]
Bonjour,

Ce talent ne doit pas augmenter les dégats de 25% mais de 12.5%. Cela augmente en fait vos dégats déjà reduits de 50%, donc 50 * 1.25 = 62.5.

Il fonctionne en ce sens exactement comme la Spécialisation Ambidextrie des Voleurs & War (ces 3 sorts ont tous exactement le même effet, seuls les valeurs changent)

https://fr.tbc.wowhead.com/spell=13852/sp%C3%A9cialisation-ambidextrie#english-comments
https://fr.tbc.wowhead.com/spell=23588/sp%C3%A9cialisation-ambidextrie#english-comments

Si vous n'arrivez pas à atteindre les 62.5% cela vient sans doute d'autre part, par exemple un talent qui ne s'applique qu'à la main droite. Je ne dis pas que ce n'est pas un bug, juste que cela ne vient pas du calcul de "Nerfs d'Acier Givré", il faudrait réussir à trouver la cause et si c'est un bug, ré-ouvrir un ticket.
