### ISSUE TITLE
( Quête Pretre ) : L'équilibre de la Lumière et de l'Ombre.

### ISSUE THREAD

**Issue by Raton094** [way-of-elendil/3.3.5#1278]
**Description**
Bonjour, je suis actuellement en train de faire la quête pour prêtre suite à l'obtention de l'œil de la divinité, une fois passé les vagues de pnj à escorter, plus rien ne se passe, pas de validation de quête ^^"
( P.S : petite information supplémentaire, les pnjs prennent beaucoup trop de dégâts, et les squelettes ne spawn pas tous à l'endroit où cela devrait se produire ) 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Pestebois ( Maleterre de l'est ) 
- Alliance - Humain - Prêtresse 
- L'équilibre de la Lumière et de l'Ombre
- Eris Havrefeu

**Comportement attendu**
Une fois les vague d'escorte réussite, je m'attendais à la validation de la quête :p

**Captures d’écran / Vidéos**
...

**Ressources additionnelles**
https://www.youtube.com/watch?v=Dz8E08xGJzs

**Comment by Amilgaull** [comment]
Bonjour, soucis déjà reporté :
https://github.com/way-of-elendil/3.3.5/issues/22
https://github.com/way-of-elendil/3.3.5/issues/1079

**Comment by Kaasss-woe** [comment]
Un correctif a été apporté
