### ISSUE TITLE
[Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1279]
RAlentissement sous main de lib / tempete de lames

Selon la RNG par moment on peut se retrouver slow sous main de lib / tempete de lames, dans les slow du mage violation ect

**Comment by Satarians** [comment]
svp ca pu vraimnt ce bug

**Comment by Justforsoloq** [comment]
Après en vrai je crois que c'est que les FB du mages qui ont ce bug (fin jamais vu ce bug avec d'autres spells que la FB du mage).
Et je crois qu'il y a un BT à ce sujet déjà :(

**Comment by Satarians** [comment]
up svp

**Comment by Endalaust** [comment]
Ce ticket manque d'informations pour être traité correctement
Merci de l'éditer ou il sera cloturé automatiquement
