### ISSUE TITLE
Boss: Anub'Arak

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#128]
**Description**
Des plaques apparaissent en hauteur après voir détruit un orbe :
Eridium "le bug actuel est lié au model qui doit faire une emote state death pour que la plaque apparait bien au sol"
"Le fix est déjà sur la prod"
"En espérant que c'est pas lié au hoverhigh"

**Comment by Sungis18** [comment]
Ce bug semble ne plus être d'actualité. Je clôture.
