### ISSUE TITLE
Bug attaque auto

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1280]
Par moment quand je joue mon fufu ( level 40) mes auto attaque ne marche plus
on put avoir le mm probleme sur le 2eme boss à icc aussi apparament et pareil avec les spel qui reste en surbrillance lorsque use via le cm

**Comment by joshwhedon** [comment]
Le cas d'icc est connu et deja signale. Pour le cas de ton fufu, vois avec un gm. T'es sur que c'est pas juste que tu utilise Sap (qui interrompt les auto attaques il me semble).
