### ISSUE TITLE
Passage de givre retiré par Marque du chasseur

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1282]
Le fait d'utiliser la marque du chasseur sur un dk qui a passage de givre retire au bout de quelques secondes le passage de givre, sans qu'il y ai eu de dégâts de subis.
Passage de givre : https://woehead.way-of-elendil.fr/?spell=3714
Marque du chasseur : https://woehead.way-of-elendil.fr/?spell=53338
Exemple sur un test ou j'ai mis simplement un dk avec le passage de givre tout seul au milieu de l'eau et je lui ai apposé la marque du chasseur, au bout de quelques secondes le passage se retire sans aucun dégât subis
![image](https://user-images.githubusercontent.com/60304524/116793657-4b64a400-aac8-11eb-88a4-e84efa57e1a9.png)
Comportement normal : La marque du chasseur est un simple débuff qui n'apporte aucun dégât et ne devrait donc pas retirer le passage de givre du dk.

**Comment by joshwhedon** [comment]
Pas un bug de ce que j'ai pu voir. Par exemple, dispel le retire (alors que c'est pas un sort qui se dispel) d'apres certaines sources offi, ensuite les donnees client ont le flag d'interruption sort recu, donc l'aura se retire quand un debuff (meme qui fait pas de degats) est recu.
Si vous avez une video ou quoi que ce soit qui infirme ca merci de fournir (en passant avant la 3.1, l'entree en combat suffisait a retirer, ca a ete change en 3.1)
