### ISSUE TITLE
Souffle Halion 10H Phase ombre

### ISSUE THREAD

**Issue by Solatrap** [way-of-elendil/3.3.5#1283]
**Description**
Lors de la deuxième phase de halion 10h (phase ombre) dans le sanctum rubis,
Halion souffle normalement sur le tank. mais parfois, le reste du raid placé sur le flanc se fait toucher par le souffle noir. 
J'ai ajouté des vidéos décrivant cela en bas de page.

-Sur le premier lien, une majorité du groupe n'est pas bien placée mais le hunt prend le souffle avec un bon placement. On remarque que le tank ombre d'halion ne prend pas de dégats du souffle. 

-Sur le second, tout le monde prend le souffle avec un bon placement. On remarque également deux choses : Halion souffle deux fois simultanément alors qu'il devrait souffler toutes les 10 secondes; le tank se prend le premier souffle mais pas le second.

Peut-être que son souffle cible la personne avec le débuff de consomption d'âmes, présent à chaque fois lors de l'anomalie ou la latence serveur fait que le cone est décalé.

**Étapes de reproduction**
- Sanctum Rubis (Zone=4987)
- Héroïque, 10 joueurs
- Halion (npc=39863)
- Souffle noir (spell=75955) / Phase d'ombre
-    Groupe 1 :  TANK Dk sang, HEAL Drood, HEAL Chaman, DPS War, DPS Hunt
     Groupe 2 : DPS Distant drood, DPS Mage,  TANK Drood, DPS prêtre, HEAL Paladin

**Comportement attendu**
Le souffle noire est normalement sur la cible du boss. Les dégats sont présents sur une zone en cône d'un rayon de 60° partant de Halion vers sa cible et cela toute les 10 secondes.

**Captures d’écran / Vidéos**
Première vidéo : https://www.youtube.com/watch?v=sA-NM0nIcyk&t=100s      2min24sec
Deuxième vidéo : https://www.youtube.com/watch?v=A7gb_thboPo      2m33sec

**Ressources additionnelles**
lien du sort souffle noir
https://wotlkdb.com/?spell=74806

Merci à vous et en espérant avoir été clair dans mes explications ;)

**Comment by Zaralbahk** [comment]
Je confirme que les souffles latéraux sans reprise d'agro sont assez fréquents (bizarrement plus en 10 qu'en 25 ou ça n'arrive quasiment jamais)

**Comment by Briznuits** [comment]
Up , 2 souffle raid sur halion 25h ce soir a moin de 10% il serait temps de script le boss de fin du jeux Josh stp ou au moin nous donner une réponse
