### ISSUE TITLE
[Quest] "Love Song for Narain" non lancable.

### ISSUE THREAD

**Issue by Shendraxqt** [way-of-elendil/3.3.5#1288]
**Description**
la quête "Love Song for Narain"  (https://woehead.way-of-elendil.fr/?quest=8599) n'est pas lançable (pas de point d'exclamation au dessus du pnj lanceur de quête, pas de possibilité de dialogue qui amènerai a une quête).

**Étapes de reproduction**
Fait avec un Paladin Humain(e) de niveau 80.

Prérequis pour la quete : 
avoir en cours (ou fini) la quete "Draconic for Dummies" (https://woehead.way-of-elendil.fr/?quest=8597)

aller au pnj "Meridith the Mermaiden" (https://woehead.way-of-elendil.fr/?npc=15526)
parler au pnj pour lancer la quete "Love Song for Narain" (https://woehead.way-of-elendil.fr/?quest=8599)

**Comportement attendu**
Le pnj "Meridith the Mermaiden"  est censé proposer la quête évoquée ci haut lorsqu'on lui parle.

**Ressources additionnelles**
Lien vers le guide utilisé, qui décris le comportement théorique du pnj ainsi que le prérequis au lancement de la quête : 
https://wowwiki-archive.fandom.com/wiki/Quest:Love_Song_for_Narain

**Comment by Ferro3** [comment]
Testée ce jour sur PTR, fonctionne parfaitement.
La quête [[60] [Une chanson d'amour pour Narain]](https://woehead.way-of-elendil.fr/?quest=8599) est disponible à partir du moment où on a [[60] [Le draconique pour les nuls]](https://woehead.way-of-elendil.fr/?quest=8597) dans son journal de quête.
Le PnJ [Meridith la Vierge de mer](https://woehead.way-of-elendil.fr/?npc=15526) propose bien cette quête à cette condition, une fois celle-ci validée, elle propose bien l'amélioration [Chant de la sirène](https://woehead.way-of-elendil.fr/?spell=25678) via une bulle de dialogue.
A clôturer
