### ISSUE TITLE
VOLEUR- Bug Coût Attaque pernicieuse améliorée

### ISSUE THREAD

**Issue by Mabrenda** [way-of-elendil/3.3.5#1289]
Bonjour, 

Je fais suite à un problème de compétence avec le Voleur. Etant expériementé avec cette classe, j'ai constaté une erreur concernant l'Attaque pernicieuse.

L'attaque de Base coûte 45 Energie sans le talent

Le Talent " Attaque pernicieuse améliorée "  octroie -5 energie pour l'attaque pernicieuse par point de compétence.

Ceci dit une fois les deux points mis, L'attaque pernicieuse doit coûter 35 points en énergie non pas 40points d'énergie!

Une erreur qui fragilise le gameplay

**Comment by Justforsoloq** [comment]
Non.
J'te conseille de relire ton talent ça va t'aider

**Comment by Mabrenda** [comment]
Merde ^^

**Comment by Mabrenda** [comment]
Mabrenda à mal lu.
