### ISSUE TITLE
[Marchand] Le vendeur d'arène de Nagran ne vend pas tout ses item

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1290]
Le vendeur d'arène situé a Nagrand ne propose que les gants du set S4 (au lieu du set complet) pour les voleur/sham/pretre/mage; Les autre classes ont accès à tous leurs items :
https://woehead.way-of-elendil.fr/?search=Grikkin      (cliquer sur le pnj situé a Nagran)
=>Il existe un 2ieme Grikkin dans la DB, qui propose les bon objets  (cliquer sur le grikkin qui n'as pas de zone définie)   , il faudrait donc spawn ce pnj à la place de l'autre

**Comment by Zaralbahk** [comment]
Up, le pnj ne propose tjs que les gant S4 pour les voleur/sham/pretre/mage; Les autre classes ont accès à tous leurs items.

**Comment by Endalaust** [comment]
Passé avec https://discord.com/channels/280446236035776512/697715145325150268/903777508355342366
