### ISSUE TITLE
bug skill mage arcane

### ISSUE THREAD

**Issue by jas42** [way-of-elendil/3.3.5#1291]
bonjour, je voudrais signaler de gros bug sur le mage arcane, des sort "continues" comme le projectiles des arcanes se cancel instantanément au lancement (comme lorsque l'on se déplace) entrainant le cooldown ainsi que la consommation de mana alors que le sort ne s'est finalement pas lancé.

**Comment by Justforsoloq** [comment]
Bizarre ça semble similaire au bug de l'évoc qui a été réglé mais le mage arcane que je connais (Icebones) n'a pas ce soucis.

**Comment by Ferro3** [comment]
j'ai ce problème de temps en temps, avec mon mage arcane 80 5k gs
https://way-of-elendil.fr/armory/character/558023-spunkmeyer

je n'ai pas pu identifier comment reproduire ce cancel, à suivre

**Comment by Belore** [comment]
J'ai parfois le même problème avec ma mage level 30, déjà rencontré aussi avec ma 80 quand je lui avais fait une spé arcane. Généralement c'est quand je viens de me déplacer et que je m'arrête pour cast. J'ai soupçonné un problème lié à la latence.

**Comment by Traesh** [comment]
Corrigé en même temps que #905
