### ISSUE TITLE
Le postier détourne toutes mes ventes depuis 2 jours...

### ISSUE THREAD

**Issue by falagar-fr** [way-of-elendil/3.3.5#1294]
Bonsoir.
Depuis hier dans l'après-midi, je ne perçois plus l'argent des ventes de l'HV : lorsque le courrier arrive, il est mis en attente 1H (normal). Puis le délai expire, mais je ne peux pas récupérer les fonds. Et le lendemain, la lettre disparaît sans que j'ai rien touché...

Kreator dispose des screens pris hier soir, je peux les remettre ici au besoin... Nous avions convenu d'attendre aujourd'hui, mais le souci persiste, et j'ai de nouveau perdu 4 nouvelles ventes. Au total j'ai perdu autant que le peu que j'ai pu amasser depuis que je joue... 168 po...

Merci d'avance pour votre aide,

**Comment by falagar-fr** [comment]
(personnage Antema en jeu)

**Comment by Ferro3** [comment]
pour avoir une industrie à l'ah (2000 3000 enchères) j'ai toujours récupéré les po
du coup je sais pas comment tu fais, pour ne pas les avoir

**Comment by Endalaust** [comment]
Ca vaut le coup de désactiver tous tes addons pour voir si tu constates une différence (non je blague absolument pas)
Un soucis isolé à un seul joueur n'est pas le fait d'un problème serveur, pour rappel
