### ISSUE TITLE
Dark Nucleus

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#1296]
**Description**
Problème sur l'aggro des nucleus (semble inexistant), et sur leur focus.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- ICC 25 (de mémoire en 10 il y a le même problème).
- Princes de sang
- Dark Nucelus

**Comportement attendu**
Le tank prend l'aggro sur les nucleus, et génère de l'aggro dessus. Le tank peut se déplacer dans la salle du combat sans perdre les nucleus. Les nucleus ciblent le premier à l'aggro.

De plus, les nucleus doivent appliquées le buff de résistance à leur cible. Il arrive parfois que les nucleus n'appliquent plus le buff (apres l'explosion d'une bombe cinétique).

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**

vidéo sur laquelle on voit que les nucleus ont une aggro : https://www.youtube.com/watch?v=ARa8oI1HFaY
video "guide" ou il est précisé que le nucleus focus le plus haut à l'aggro : https://youtu.be/nH0ao8VfTzM?t=180

Dans toutes les vidéos des princes sur wow officiel, le tank avec les nucleus peut se promener dans la salle pour aller chercher d'autres nucleus. Il passe completement dans le raid sans perdre l'aggro. Sur WoE, c'est impossible, il semble que les nucleus partent sur le joueur le plus proche. (elle seront à un moment plus proche d'un autre joueur que du tank si celui ci passe sur un autre joueur). Passer dans le raid fait systématiquement perdre les nucleus.

**Comment by Zaralbahk** [comment]
Les nucléus ciblent la dernière personne qui leur a infligé des dégâts en théorie, si on les perd en traversant le raid c simplement la faute aux gens qui aoe ou cleave sans réfléchir. Si l'agro comptait les nucléus cibleraient directement les heal^^

=> pour le nucléus que tu perd pendant la video je serai curieux de savoir avec quel sort tu l'as pull : si tu pull avec mot de l'ombre douleur par ex les degats mettent 3 sec à arriver, donc le nucléus se baladera  vers les heal tant qu'il n'a pas subit le 1er tick de degats
=>pour le perte du buff de resi ombre apres un bump, effectivement les nucleus ont une "portée", si tu te retrouve a 50 m d'eux après un bump il faudra quelques secondes pour récupérer le buff le temps que les nucleus arrivent suffisamment près pour te buffer
