### ISSUE TITLE
[Potion] CD problems

### ISSUE THREAD

**Issue by Atemoss** [way-of-elendil/3.3.5#1297]
**Description**
Le CD de la Potion d'invisibilité inférieur applique un CD  de 10 minutes sur les autres potions .

**Étapes de reproduction**
Depuis mon perso mage gnome.
- Utilisation de la potion d'invisibilité inférieur.

**Comportement attendu**
Le CD de la potion d’invisibilité doit  durée  10 minutes et 1 minute (ou 3 je ne sais plus) de CD sur les autres potions.

**Captures d’écran / Vidéos**
- screens

**Ressources additionnelles**
- https://fr.wowhead.com/item=3823/potion-dinvisibilit%C3%A9-inf%C3%A9rieure
- https://ibb.co/qMNMXHD
-  https://ibb.co/sbsfWJC

**Comment by joshwhedon** [comment]
RecoveryTime: 0 ms, CategoryRecoveryTime: 600000 ms
Il s'agit des donnees clients du client 3.3.5, qui sont par defaut correctes.
D'ailleurs les commentaires, jusqu'a la 4.3, en parlent comme ayant un cooldown de 10 minutes, donc probablement change plus tard (voire les commentaires du lien fourni).
