### ISSUE TITLE
Pet: Gestion des auras d'invisibilité et de vision de l'invisibilité

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/3.3.5#13]
**Description**
Tous les mobs de la zone "La Cote Oubliée" (Désolation des dragons) semblent avoir un gros souci d'aggro vis-à-vis des pets (testé sur hunt).

**Étapes de reproduction**
Sortir le pet quand dans la zone La cote oubliee, attaquer les mobs
Ces mobs ne semblent pas prendre en compte l'aggro des pets :

- si le pet du hunt attaque, le mob attaque son propriétaire

- si un hunt utilise détournement sur son pet, il prend quand meme l'aggro

- si un hunt feint la mort, le mob reinit( meme si le pet du hunt est en train d'attaque le mob).

**Comportement attendu**

**Captures d’écran / Vidéos**

**Ressources additionnelles**

**Comment by joshwhedon** [comment]
Le probleme a ete regle par Trinity il semblerait.

**Comment by Killyana** [comment]
j'en doute

**Comment by joshwhedon** [comment]
Je sais pas j'ai teste le probleme et ca avait l'air bon. Peut etre qu'ils ont regle ca indirectement

**Comment by Killyana** [comment]
Non le npc n'attaque toujours pas le pet même si le pet peut attaqué le pnj, du coup le pnj evade à chaque coup

**Comment by joshwhedon** [comment]
Ajout d'un mechanisme pour que les pets "heritent" de la visibilite du proprietaire .
