### ISSUE TITLE
( Guerrier ) Blessure Profonde qui ne proc pas après critique

### ISSUE THREAD

**Issue by Raton094** [way-of-elendil/3.3.5#1304]
Bonjour, je rédige se petit topic car il semblerait qu'il y ai un petit soucis avec mon guerrier ( je précise mon guerrier car j'ai posé la question à d'autre guerriers qui n'ont visiblement pas se soucis ). Il semblerait, en effet, que ma Blessure profonde ne fait pas son apparition suite à une attaque critique. Je suis obligé de faire une " deco, reco " pour que le problème se règle mais dès lors où j'ai un chargement ( exemple après quoi se bug est apparu : chargement pour apparaitre en donjon / téléportation sur les différente zone du raid ICC / après avoir " pdf " / ect..., dès lors ou il y a un chargement ), cependant il m'arrive aussi qu'a certain moment en plein donjon/raid le bug se fasse, par exemple sur Gargamoelle j'ai le proc de blessure profonde, et sur la dame non, sans chargement entre-deux.

Est-ce la race Gnome qui fait se bug, comme pour le bug de monture des mecanotrotteur, même si il n'y a aucun lien ? 
Avez-vous déjà eu des rapports de se bug, ne serait-ce donc pas le seul ? 

si cela peut aider, le bug se fait sur le guerrier nommé Tournelame.

Cordialement,

**Comment by Amilgaull** [comment]
Soucis lié au personnage, réglé ig directement.
