### ISSUE TITLE
Invocation de l'Avatar d'Hakkar

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1309]
Une fois la quête https://classic.wowhead.com/quest=3528/the-god-hakkar terminée, le pnj Yeh'kinya est censé nous donner un parchemin ( https://woehead.way-of-elendil.fr/?item=10818#created-by ) si on lui parle, permettant d'invoquer l'Avatar d'Hakkar au temple englouti. Le pnj ne propose pas cet item, rendant l'invocation du boss une fois la quête validée impossible (il est marqué "This item is not available to players." sur woehead).

Sources (désolé j'ai pas mieux) : https://tbc.wowhead.com/item=10818/yehkinyas-scroll#comments
![image](https://user-images.githubusercontent.com/73133549/128605232-74f27bcf-e53f-4e79-b4ea-45e992d7e548.png)

**Comment by Ferro3** [comment]
ressources: https://fr.classic.wowhead.com/spell=12998/cr%C3%A9er-le-parchemin-de-yehkinya

**Comment by Ferro3** [comment]
vérifié ce jour, le parchemin n'est pas implanté

il est demandé dans la requête d'ajouter l'obtention du parchemin https://fr.classic.wowhead.com/spell=12998/cr%C3%A9er-le-parchemin-de-yehkinya une fois la quête [53] [Le dieu Hakkar] https://woehead.way-of-elendil.fr/?quest=3528 réalisée par le joueur

**Comment by Traesh** [comment]
Le patch ne semble pas avoir été appliqué, je vérifie avec Amandil

**Comment by Endalaust** [comment]
Visiblement lorsqu'il y a plusieurs commits dans une MR seul le dernier est interprété pour le SQL
Je corrige ça pour les fois prochaines
