### ISSUE TITLE
[donjon] Terrasse des magistères normale

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1317]
**Prêtresse Delrissa**
Après avoir affronté la **Prêtresse Delrissa** et ces adds
https://woehead.way-of-elendil.fr/?npc=24560

si on ne tue pas la **Prêtresse Delrissa** en dernier la porte qui donne accès à la suite ne s'ouvre pas
_je rappel que la strat est de la tuer en premier afin d'éviter les heal et rez des adds_

**Télépoteur**
Derrière le boss **Kael'thas Haut-Soleil** se trouve un téléporteur qui doit nous envoyer hors du donjon devant **Exarque Larethor** https://woehead.way-of-elendil.fr/?npc=24813
Cela permet (entre autre) de valider la quête [70d] [La terrasse des Magistères] https://woehead.way-of-elendil.fr/?quest=11488
La téléportation ne fonctionne pas

**Comment by Kaasss-woe** [comment]
J'ai testé ces deux éléments aujourd'hui et n'ai constaté aucun des deux problèmes mentionnés.
Testé directement avec un personnage non-mj en mode normal.

**Comment by Ferro3** [comment]
vérifié ce jour, en effet, plus de problèmes.
ça a du être fix sans clôture, je ne fais pas de requêtes sans raison, j'avais même fais le donjon plusieurs fois pour être sur de la répétabilité du bug.
