### ISSUE TITLE
Soucis de npc amicaux, quête un travail inachevé

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1324]
https://woehead.way-of-elendil.fr/?quest=6004
Dans cette quête accessible aux deux factions, il faut tuer 

https://woehead.way-of-elendil.fr/?npc=1833
https://woehead.way-of-elendil.fr/?npc=1826
https://woehead.way-of-elendil.fr/?npc=1831
https://woehead.way-of-elendil.fr/?npc=10605

Que l'on soit ally ou hordeux les : 
https://woehead.way-of-elendil.fr/?npc=1826 
https://woehead.way-of-elendil.fr/?npc=1833
sont hostiles et attaquables avec la faction 67

NPC currently selected by player:
23:14:02 Name: Scarlet Mage
23:14:02 SpawnID: 47145, current GUID low: 280489.
23:14:02 Entry: 1826.
23:14:02 Faction: 67.
23:14:02 NPC Flags: 0.
23:14:02 DisplayID: 10288 (Native: 10288).
23:14:02 Spawn group: Dynamic Scaling (Quest objectives) (ID: 2, Flags: 9, Active: 1)
23:14:02 Compatibility Mode: 0
23:14:02 Level: 56.
23:14:02 EquipmentId: 1 (Original: 1).
23:14:02 Health (base): 2551. (max): 2551. (current): 2551.
23:14:02 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
23:14:02 Unit Flags: 557056
23:14:02 * UNIT_FLAG_SWIMMING (0x8000)
23:14:02 * UNIT_FLAG_IN_COMBAT (0x80000)
23:14:02 Unit Flags 2: 2048.
23:14:02 Dynamic Flags: 0.
23:14:02 Faction Template: 67.
23:14:02 SpawnTime: Full:5m Remaining:0s
23:14:02 Loot: 1826 Pickpocket: 1826 Skinning: 0
23:14:02 InstanceID: 0
23:14:02 Phasemask: 1

Par contre les npcs suivants ne sont attaquables que lorsque l'on est hordeux
Les : 
https://woehead.way-of-elendil.fr/?npc=1831
https://woehead.way-of-elendil.fr/?npc=10605
https://woehead.way-of-elendil.fr/?npc=1835
https://woehead.way-of-elendil.fr/?npc=10979
sont en faction 56 

Pour exemple : 

Name: Scarlet Hunter
23:34:15 SpawnID: 45364, current GUID low: 249544.
23:34:15 Entry: 1831.
23:34:15 Faction: 56.
23:34:15 NPC Flags: 0.
23:34:15 DisplayID: 10281 (Native: 10281).
23:34:15 Spawn group: Dynamic Scaling (Quest objectives) (ID: 2, Flags: 9, Active: 1)
23:34:15 Compatibility Mode: 0
23:34:15 Level: 52.
23:34:15 EquipmentId: 1 (Original: 1).
23:34:15 Health (base): 3083. (max): 3083. (current): 3083.
23:34:15 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
23:34:15 Unit Flags: 32768
23:34:15 * UNIT_FLAG_SWIMMING (0x8000)
23:34:15 Unit Flags 2: 2048.
23:34:15 Dynamic Flags: 0.
23:34:15 Faction Template: 56.
23:34:15 SpawnTime: Full:5m Remaining:0s
23:34:15 Loot: 1831 Pickpocket: 1831 Skinning: 0
23:34:15 InstanceID: 0
23:34:15 Phasemask: 1
23:34:15 Armor: 3074
23:34:15 Position: 2088.637451 -1829.661621 59.709225.
23:34:15 AIName: SmartAI ScriptName: 
23:34:15 React state: AGGRESSIVE
23:34:15 Active AI: SmartAI
23:34:15 Flags Extra: 0
23:34:15 MechanicImmuneMask: 0
23:34:15 dmg_multiplier: 1.000000

Je n'ai trouvé aucune information parlant de ces mobs amicaux pour une faction. 
Pour info :
 https://fr.classic.wowhead.com/npc=1831/chasseur-%C3%A9carlate
https://fr.classic.wowhead.com/npc=10605/m%C3%A9decin-%C3%A9carlate
sont bien affichés en hostile Horde et alliance

**Comment by Babyface-187** [comment]
https://github.com/way-of-elendil/3.3.5/issues/1299

**Comment by Kaasss-woe** [comment]
Un correctif a été appliqué
