### ISSUE TITLE
[HF] Titre d'arène reset

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1327]
Les titres d'arène datant de la saison d'arène N-1 sont utilisable pendant la saison N et sont reset à la saison N+1. 
Les HF liés sont normalement **permanents** : (source sujette à discussion bien entendu, on notera qu'il est écrit que les titres ne sont plus distribués en v2 à la 3.3.5, vrai ou faux?)
![image](https://user-images.githubusercontent.com/73133549/135698786-3af9ac0e-c81a-44cd-9278-69b95095c62a.png)
https://www.wowhead.com/title=44/rival#comments

Le changement de saison d'hier à bien reset les titres, mais aussi les HF par la même occasion => choix délibéré ou dommage collatéral? Normalement sur WOTLK aucun HF ne peux être perdu.

https://woehead.way-of-elendil.fr/?achievement=2090
https://woehead.way-of-elendil.fr/?achievement=2093
https://woehead.way-of-elendil.fr/?achievement=2092
https://woehead.way-of-elendil.fr/?achievement=2091

**Comment by Justforsoloq** [comment]
Me semble c'est délibéré.

**Comment by Endalaust** [comment]
Délibéré
L'un va avec l'autre, on ne peut pas purger l'un sans l'autre.. Si tu as le HF, à ta reco tu récupères automatiquement le titre (mais l'inverse n'est pas vrai). 
Normalement sur offi avec les saisons qui changent, les HFs changent aussi, nous on est coincé :(
