### ISSUE TITLE
[Quête\Event] Caravane de Gizelton se bloque

### ISSUE THREAD

**Issue by TrucEtrange** [way-of-elendil/3.3.5#1331]
**Description**
J'ai constaté que la caravane était plantée au même endroit plusieurs jours d'affilée.
J'ai finalement demandé à un MJ pour la débloquer, et Amigaul s'en est occupé. Il a tué et repop la caravane, qui a repris sa route.
J'ai suivi la caravane depuis le point de reprise jusqu'à son arrêt nord. Tout va bien, elle y reste environ 10 minutes, puis pars vers le sud.
La caravane s'arrête un peu avant le village centaure pour proposer la quête d'escorte, que j'accepte. La caravane reprend sa route, Les embuscades centaures apparaissent, tout se déroule sans encombre. La quête se valide, la caravane continue sa route jusqu'à son arrêt sud.
La caravane y reste 10 minutes environ, puis repars vers le nord. S'arrête avant le convent de Mannoroc, propose la 2e quête d'escorte que j'accepte, puis repars. Les démons apparaissent, la caravane continue, la quête se valide, tout va bien.
La caravane continue vers le nord, arrive au point où je l'avais trouvée bloquée initialement, et s'arrête.

**Étapes de reproduction**
Suivre la caravane pendant ses trajets

**Comportement attendu**
La caravane ne devrait pas s'arrêter là où elle le fait, elle devrait continuer vers son arrêt nord.

**Captures d’écran / Vidéos**
La caravane bloque à cet endroit :
![caravane](https://user-images.githubusercontent.com/45370942/137307343-0766fc89-e217-4b83-b704-17b251b67afb.png)

**Comment by Ferro3** [comment]
https://woehead.way-of-elendil.fr/?quest=5943
je crois que ce point et l'emplacement d’arrêt pour l'escorte du nord vers le sud, donc [Garde du corps à recruter]

il y a 2 escortes 
1. une du sud vers le nord [La caravane de Gizelton] https://fr.classic.wowhead.com/quest=5943/la-caravane-de-gizelton _attention la carte de wowhead n'indique pas les bons emplacements_
2. et une autre du nord vers le sud [Garde du corps à recruter] https://fr.classic.wowhead.com/quest=5821/garde-du-corps-%C3%A0-recruter

de plus les pnj vendeurs aux arrêts ne sont pas les mêmes
Vendeur-o-tron au nord 1000 https://woehead.way-of-elendil.fr/?npc=12245 https://fr.classic.wowhead.com/npc=12245/vendeur-tron-1000
et Super-Vendeur 680 au sud https://woehead.way-of-elendil.fr/?npc=12246 https://fr.classic.wowhead.com/npc=12246/super-vendeur-680

ressources: https://fr.classic.wowhead.com/quest=5943/la-caravane-de-gizelton#english-comments

**Comment by TrucEtrange** [comment]
Le reste de l'évènement a l'air de fonctionner correctement.
Je n'ai pas essayé d'attendre aux points d'arrêts pour les quêtes d'escortes, voir si la caravane partait sans moi, mais la caravane s'arrête bien aux points que tu spécifies @Ferro3 
Les vendeurs sont bien les deux robots différents à chaque point d'arrêt
En revanche, la caravane finit par s'arrêter sans raison apparente au point de la carte de mon 1er post, et ne semble pas vouloir repartir

**Comment by Amilgaull** [comment]
Déjà reporté : #505  et #773

**Comment by Endalaust** [comment]
Fixé prochain redémarrage.

**Comment by Ferro3** [comment]
vérifiée le 7/2/22

* il est possible de prendre la quête [38] [La caravane de Gizelton] https://woehead.way-of-elendil.fr/?quest=5943 à partir de 66-59 alors qu'il ne le faudrait qu'à partir de la pause de la caravane avant le "convent de Mannoroc" en gros en 44-75 là où la pause est programmée (et actuellement effective)

* la vitesse de la caravane est toujours la même alors qu'elle devrait être accélérée en dehors des escortes, par contre je n'ai pas la vitesse

les 2 quêtes sont malgré tout, toutes les 2 fonctionnelles et fonctionnent parfaitement

biz
