### ISSUE TITLE
[loot] gangrebrume

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1334]
Après moulte raids au plateau du puit de soleil (31 down de Kil Jaeden d'après mes stats), je n'ai encore jamais vu loot les [Jambières de la nuit immortelle]    https://woehead.way-of-elendil.fr/?item=34188 
Ce loot est marqué a 16.7% dans la db du serveur, peut-on vérifier qu'il drop effectivement sur le boss? (je n'ai pas trop d'idée mais .kill 20 fois le boss ig peux déjà donner une bonne idée de si le problème est réel ou pas)

La probabilité de ne pas loot ces jambes apres 31 down est de p=(1-0.167)^31=0.34%
Ca peut donc arriver mais une petite vérif me permettrait d'être sûr que je ne farm pas pour rien, merci!

(après consultation auprès d'autres joueurs je n'ai trouvé personne qui ait la mémoire d'avoir vu ce pantalon, alors que j'ai vu dans l'intervalle tomber 3 fois l'arc légendaire a 4% de taux de drop)

Ps: il semblerait que les [Poignes de la forteresse frontalière]   https://woehead.way-of-elendil.fr/?item=34352   ne drop jamais non plus

**Comment by Zaralbahk** [comment]
=> loot today donc pas de bugg juste unlucky

**Comment by Endalaust** [comment]
Pour info je viens de regarder les possesseurs de l'item et j'ai cette liste :
![players](https://user-images.githubusercontent.com/1420867/142024609-59452983-dfa2-4fed-a4a3-23e0b0192e6d.PNG)

Entre l'obtenu et le tombé puis vendu/jeté, je ne peux que confirmer qu'il n'y a pas de soucis sur ce loot ;)
