### ISSUE TITLE
[quete] Une abondance de générosité

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1335]
https://fr.wowhead.com/quest=13146/une-abondance-de-g%C3%A9n%C3%A9rosit%C3%A9

Il est impossible de saisir les bombes avec le sort numero 2 du traqueur agile.

**Comment by Ferro3** [comment]
https://woehead.way-of-elendil.fr/?quest=13146
curieux, la dernière fois que j'ai fais la quête, moi j'y suis arrivé, à vérifier

**Comment by Ferro3** [comment]
vérifié ce jour
la prise de bombe se fait normalement (avec la touche 2) la quête fonctionne parfaitement, il n'y a donc pas de fix à dépployer

requête à clôturer avec **status-invalid**

**Comment by Zaralbahk** [comment]
Testé ce jour=> pas possible  d'utiliser le sort 2, jamais, même si je suis a coté des bombes.
Est ce que tu cibles les bombes pour les ramasser? on ne peux pas les cibler chez moi. Est-on dans la même phase? la même faction (horde)? Au même endroit sur la map?
![WoWScrnShot_022322_104415](https://user-images.githubusercontent.com/73133549/155294792-801dcec3-e1d3-4039-8fd0-e6ac98939dad.jpg)

**Comment by Ferro3** [comment]
j'ai testé avec un druide horde 80

une fois transformé (vu ton screen c'est le cas) il faut :
* se rapprocher des bombes
* les sélectionner
* les agripper avec le sort 2
* se diriger vers une abomination en marchant
* au contact de l'abomination la bombe explose
 
je vois que tu as des addons actifs (mini carte, recount, chat) essai de refaire la quête sans ces addons actifs
je te conseils de sauvegarder ton répertoire wtf avant ce test

**Comment by Zaralbahk** [comment]
Retesté a l'instant avec aucun addon, pas mieux

Il y a un pb avec ce que tu dit : "les sélectionner" --> j'ai bien précisé que je ne peux pas sélectionner les bombes, c'est juste un élément du décors chez moi (cf la fin de la vidéo) https://youtu.be/ifKLK7CtfpU

Comment les sélectionne tu? As tu un screen pour me montrer ce que je suis censé voir quand la bombe est sélectionnée?

Ca revient à ce que je proposait plus haut , on est probablement pas dans la même phase, ou autre problèmes du même genre

**Comment by Ferro3** [comment]
je crois que tu essais sur des bombes du décor

voilà un screen d'une sélection qui fonctionne https://i.postimg.cc/xjwpcKsM/Wo-WScrn-Shot-022322-145758.jpg
balade de la bombe https://i.postimg.cc/15YtG3qG/Wo-WScrn-Shot-022322-145832.jpg
explosion avec objectif validé https://i.postimg.cc/8cX1mZjp/Wo-WScrn-Shot-022322-145913.jpg

tu as les coordonnées en bas de mon interface

**Comment by Zaralbahk** [comment]
On est définitivement pas dans la même phase, ces pnj "bombe" n'existent pas chez moi: 
![image](https://user-images.githubusercontent.com/73133549/155337142-22389277-ccbf-4be1-8dc0-40e238dccdc7.png)

**Comment by Ferro3** [comment]
abandonne la quête, reprends là, si ça ne change rien tu as une autre quête qui te déphases comme celles du tournoi par exemple

comme tu peux le constater avec mes screens, chez moi ça fonctionne sans aucun problème

**Comment by Zaralbahk** [comment]
Quête abandonnée et reprise a de multiple reprises^^ aucune autre quête dans mon journal en Norfendre
![image](https://user-images.githubusercontent.com/73133549/155338704-e238f781-8999-40de-8af4-322b2e8db3b2.png)

**Comment by Ferro3** [comment]
Après un long échange et de multiples essais avec le joueur **Arkannor** https://way-of-elendil.fr/armory/character/346292-arkannor il semble qu'il ai déjà effectué la suite de ces quêtes se qui normalement est impossible

nous supposons que cela doit être lié à ancienneté du personnage où les "phasing" n'était pas encore en place

du coup pour qu'il puisse terminer ces 2 quêtes ( https://woehead.way-of-elendil.fr/?quest=13146 et https://woehead.way-of-elendil.fr/?quest=13147 ) il faudrait soit le mettre manuellement dans la phase, donc avec un MJ présent, soit clean sont historique de quête des suites donc :
[80g5] [Le cavalier de l'impie] https://woehead.way-of-elendil.fr/?quest=13161
[80g5] [La cavalière du Givre] https://woehead.way-of-elendil.fr/?quest=13162
[80g5] [Le cavalier du Sang] https://woehead.way-of-elendil.fr/?quest=13163
et [80g5] [Le destin de Sangreplaie] https://woehead.way-of-elendil.fr/?quest=13164

quoi qu'il en soit ces quêtes fonctionnent correctement, il n'y a donc pas de fix à déployer
conclusion identique pour https://github.com/way-of-elendil/3.3.5/issues/1336

**Comment by Amilgaull** [comment]
Merci de retester et de nous dire ce qu'il en est.

**Comment by Zaralbahk** [comment]
C'est bon avec le reset des quête j'ai pu faire l'ensemble de la suite de quêtes sans pb
