### ISSUE TITLE
[quete] Affrontements en vue

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1336]
https://fr.wowhead.com/quest=13147/affrontements-en-vue

Lancer un rocher sur les Brutes ombreuses qui sont proches des squelette ne provoque pas de bagarre=> impossible d'incrémenter le trigger de l'objectif de quete

**Comment by Ferro3** [comment]
[80] [Affrontements en vue] https://woehead.way-of-elendil.fr/?quest=13147

**Comment by Ferro3** [comment]
vérifié ce jour
le [Lancer de rocher] https://woehead.way-of-elendil.fr/?spell=58283 se fait normalement (avec la touche 4) la quête fonctionne parfaitement, il n'y a donc pas de fix à dépployer

requête à clôturer avec status-invalid

**Comment by Ferro3** [comment]
j'ai testé avec un druide horde 80

oui c'est bien en sélectionnant les "brutes ombreuses"

il n'y a pas d'animation de bagarre, et il faut trouver 4 "brutes ombreuses" différentes pour effectuer la quête, les cibles ne fonctionnent pas 2 fois de suite

même remarque que pour https://github.com/way-of-elendil/3.3.5/issues/1335 tu as surement un addon qui t'empêche de progresser

**Comment by Zaralbahk** [comment]
Retesté à l'instant sans aucun addon, pas mieux pour autant;

As tu regardé la vidéo que j'ai mis? est ce que je fait les mêmes actions que toi? Si oui il y a bien un bugg, de quelque nature qu'il soit (probablement un truc lié a l'historique du personnage qui a plus de 10 ans et quêtait déjà dans la région avant que le phasing ou les prérequis de quête soient implémenté correctement)

**Comment by Ferro3** [comment]
il y a une distance minimale et maximale entre toi et le mob (un peu comme un charge) et elle est pas grande
tu peux le voir avec le chiffre en rouge sur mon 1er screen

https://i.postimg.cc/vTsPSyxX/Wo-WScrn-Shot-022322-145932.jpg
https://i.postimg.cc/8z5ZYts8/Wo-WScrn-Shot-022322-145950.jpg
https://i.postimg.cc/k5SvrZmH/Wo-WScrn-Shot-022322-150011.jpg

**Comment by Zaralbahk** [comment]
Fait avec la distance indiquée sur les screen, pas mieux => pb de phase (cf https://github.com/way-of-elendil/3.3.5/issues/1335 )

**Comment by Zaralbahk** [comment]
C'est bon avec le reset des quête j'ai pu faire l'ensemble de la suite de quêtes sans pb
