### ISSUE TITLE
[quete] Le gambit de Tirion 

### ISSUE THREAD

**Issue by haykalox** [way-of-elendil/3.3.5#1340]
https://fr.wowhead.com/quest=13403/le-gambit-de-tirion#see-also

je doit récupère le "Chaperon d'acolyte du culte" pour parle avec "Generalissime Tirion Fordring" pour lance la quête, mais il est mort , impossible de communique avec lui 
https://ibb.co/zNBqJjb

**Comment by Zaralbahk** [comment]
Il va respawn au bout d'un moment normalement
