### ISSUE TITLE
Cutter Halion prend en compte les Immunes alors que ça ne devrait pas être le cas

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1344]
**Description**
Sous Iceblock le cutter de halion ne fait pas de dégats alors que c'est censé être le cas (pas d'info pour la bulle/DI mais je pense que ça devrait être pareil (au moins pour la bulle)

**Étapes de reproduction**

- Sanctum Rubis
- Halion
- Tranchant crépuculaire https://woehead.way-of-elendil.fr/?spell=74769

**Comportement attendu**
Le cutter devrait passer outre les immunes

**Captures d’écran / Vidéos**
Sur PTR : https://youtu.be/Kj8x0uTLedg

**Ressources additionnelles**
Vidéos du Paragon (la guilde, pas le serveur), https://youtu.be/cpbIWfLwp-8?t=199

3:23 le mage ib, meurt, et 3:30 on peut lire "btw iceblock doesn't work with the beam"

**Comment by Traesh** [comment]
Bonjour,

après vérification dans les fichiers du jeu, seules les versions héroïques du sort "Tranchant crépusculaire" ont l'attribut leur permettant de passer outre les invulnérabilités.

La vidéo de Paragon montrant du 25hm cela me paraît cohérent

Je ferme le ticket pour l'instant, n'hésitez pas à mettre un commentaire en cas de besoin
