### ISSUE TITLE
[Proposition] Statut [Assemblage d'engrenages néo-dynamiques]

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1345]
[Assemblage d'engrenages néo-dynamiques] est actuellement tag en blanc 
https://woehead.way-of-elendil.fr/?item=39686#dropped-by

je suggère de le basculer cet item en gris puisque ces items ne sont pas utilisés, mais ça n'est pas biz-like.
cela facilite le tri pour les joueurs.

référence : https://fr.wowhead.com/item=39686/assemblage-dengrenages-n%C3%A9o-dynamiques#english-comments

**Comment by Traesh** [comment]
Malheureusement ce n'est pas blizzlike comme vous dites, cela ne sera donc pas fait.
