### ISSUE TITLE
[quête] [56] [Rédemption]

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1349]
[56] [Rédemption] https://woehead.way-of-elendil.fr/?quest=5742
impossible d'écouter le compte de Tirion, pas d'histoire disponible, pas de bulle de dialogue

cache vidé, reset serveur checké, impossible de passer la quête

**Comment by KreatorWoE** [comment]
Cette quête n'est pas bug, il suffit tout simplement de faire l'emote /sit pour s'asseoir et Tirion commencera le dialogue. Je clos !

**Comment by Ferro3** [comment]
exact, vérifié ce jour.
peut-être ajouter dans la bulle de dialogue la commande /sit comme pour la quête [1] [Des ordres simples] https://woehead.way-of-elendil.fr/?quest=25199
