### ISSUE TITLE
BG: Flag Warsong

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#135]
**Description**
On ne voit plus le flag sur le porteur une fois qu'il est morph, même après être revenu à sa forme normale(seulement Warsong)

**Comment by joshwhedon** [comment]
Aucune idee si c'est normal ou pas.

**Comment by Amilgaull** [comment]
J'ai pas de texte qui le dit de façon claire mais ce qui est sur c'est que sur offi, même en étant morph le flag a toujours été visible sur le joueur

**Comment by joshwhedon** [comment]
Teste, aucun soucis de mon cote. J'ai essaye toutes les formes, j'ai toujours le drapeau visible. Possible que ce soit un bug avec la version HD.

**Comment by Ischjgt** [comment]
(je n'utilise pas la version HD :p)

**Comment by Killyana** [comment]
Il est possible que se soit un update qui foire coté client, il faut prendre le flag est morph en ayant un autre perso prêt de l'autre flag (pour avoir une distance supérieur à 530) et voir si le visuel de l'aura est envoyé au client ou pas dans ce cas.

**Comment by Killyana** [comment]
Enfaîte, non j'ai pas réussi à reproduire.
