### ISSUE TITLE
[DK] Armure bijoux non convertie en puissance

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1359]
Je remonte une demande d'une joueuse sur **DK tank** (Arshess https://way-of-elendil.fr/armory/character/466970-arshess)

Le talent **Armure tranchante** https://woehead.way-of-elendil.fr/?spell=49393
devrait convertir l'armure de l'**Ecaille du Crépuscule pétrifiée** https://woehead.way-of-elendil.fr/?item=54571
en puissance d'attaque, à priori ça n'est pas le cas

sans bijou : https://cdn.discordapp.com/attachments/875142438325465138/913805883165790228/sans_scale.PNG
avec bijou : https://cdn.discordapp.com/attachments/875142438325465138/913805908776214548/avec_scale.PNG
la puissance affichée ne change pas, et elle devrait augmenter
C'est aussi la cas pour l'**Organe non identifiable** https://woehead.way-of-elendil.fr/?item=50344

C'est le cas pour tous les bijoux avec de l'armure, et pour les 2 emplacements de bijoux. Nous avons regardé.

Bon courage, biz

**Comment by Traesh** [comment]
Bonjour,

Le talent fonctionne, par contre pour des soucis de performance le check de l'armure ne se fait que toutes les 30 secondes. Essayez donc de mettre le bijou et d'attendre au maximum 30 secondes, votre PA devrait se mettre à jour :)

**Comment by Ferro3** [comment]
en effet, après 20 sec environ 5661 <-> 5592
vérifié ce jour
