### ISSUE TITLE
BG: Rivage des Anciens

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#136]
**Description**
Les joueurs qui rejoignent le BG en cours sont bien placés mais ils ne voient pas les bateaux( ils sont à leur point de départ comme si le BG commençait, puis ils arrivent, comme si le BG commençait)
Les joueurs qui sont déjà les voient toujours et peuvent marcher dessus (alors que ceux qui rejoignent le BG tomberont dans l'eau)

**Comment by joshwhedon** [comment]
Impossible a corriger malheureusement, c'est un bug existant en rapport avec le temps de chargement cote serveur et client des bateaux :(
