### ISSUE TITLE
[boss] [ICC] Princes 4 cinétiques au lieu de 2

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1360]
Salut.

**Description**
Le 1er décembre 2021 en faisant un ICC 10 normal en soirée, nous avons eu la surprise d'avoir 4 cinétiques au lieu de 2 sur les princes. Du coup le combat a été assez tendu avec un caster de moins, mais nous avons tout de même tombé les boss malgré ça.
Cela s'est produit après un wipe.

**Reproduction**
Je sais pas trop comment reproduire le bug, peut être un problème de reset après le wipe.

**Copies d'écran**
4 cinétiques à l'écran :
https://i.postimg.cc/50nbQ32R/1-d-cembre-cin-en-double-1.png
https://i.postimg.cc/bJDdPWTR/1-d-cembre-cin-en-double-2.jpg

biz.

**Comment by MJ-Vyr** [comment]
Après vérification, impossible a isoler/reproduire.

**Comment by Ferro-woe** [comment]
Faut regarder dans le code comment ces cinétiques sont reset, pour reproduire c'est compliqué voir impossible puisqu'il faut wipe et tomber sur le bon moment.
