### ISSUE TITLE
quête "Le Calice spectral"

### ISSUE THREAD

**Issue by Jackspe** [way-of-elendil/3.3.5#1365]
Dans le donjon les profondeurs de rochenoire la quête qui permet d'apprendre la fonte du minerai de sombrefer ne fournit pas la compétence malgré la validation de la quêtes qui demande d'apporter des composants (10 barres de vrai argent / 20 barres d'or et 2 rubis étoilée)

**Comment by Ferro3** [comment]
Nouvelle vérification ce jour sur PTR

Une fois la [quête du calice](https://woehead.way-of-elendil.fr/?quest=4083) validée, il faut reparler au Nain qui propose d'apprendre la recette.

Tout est fonctionnel,
A clôturer en status-invalid
