### ISSUE TITLE
Proc du poison instantané en Spé Venom

### ISSUE THREAD

**Issue by RiDDicKGaeris** [way-of-elendil/3.3.5#1366]
**Description**
Le proc rate du poison instantané est modifié par divers buff dans la spé assassinat et il semble que ses procs rate constatés ne correspondent pas à ceux calculés théoriquement. Nous allons voir pas à pas dans la catégorie suivante la partie qui pose problème.

**Étapes de reproduction**
Pour l'entièreté de ce test j'ai utilisé deux dagues de vitesse 1.8 avec du poison instantané sur chacune d'elle. Je donne 500 coups blancs sur un mannequin et je constate le ratio Nombre de hit de poison/(Nombre de coup blanc - Nombre de miss). Ce nombre nous donne donc le pourcentage de hit du poison instantané.

1 - Sans spécialisation

D'après cette source : https://wowwiki-archive.fandom.com/wiki/Instant_Poison
**En coup blanc nous sommes censé trouver 25.71%. > Je constate en jeu 24.75%** (On pourrait disserter sur l'intervalle de confiance acceptable mais cela me parait cohérant)

![chrome_1hC5BtGGGZ](https://user-images.githubusercontent.com/2164176/152854414-97e8a026-3b4a-4887-b2ce-8a5d4483c5d2.png)

2 - Avec le talent Poisons Améliorés 5/5

Ici le talent nous mentionne : Augmente la fréquence à laquelle vous appliquez poison instantané de 50%.
**On devrait donc obtenir le résultat théorique 25.71 x 1.5 = 38.56% > Je constate en jeu  39.05%**  (On pourrait disserter sur l'intervalle de confiance acceptable mais cela me parait cohérant)

![chrome_HJrdwAqQTP](https://user-images.githubusercontent.com/2164176/152855340-ca2a77ed-ee0a-48fe-996b-ec21bb4ce7da.png)

3 - Avec le talent Poisons Améliorés 5/5 ET sous l'effet du sort Envenimer pendant la durée du test

C'est ici que ça se complique, le sort Envenimer ajoute un effet qui donne "Augmente la fréquence d'application de poison instantané de 75%".
**On devrait donc obtenir le résultat théorique 25.71x1.5x1.75=67.48% > Je constate en jeu 53% > Je juge donc cet écart suffisamment grand pour justifier la présence d'un potentiel problème.**

![chrome_kJO0j39FRD](https://user-images.githubusercontent.com/2164176/152855607-0a9a50dc-998a-48b9-80ec-9f838a4c608e.png)

**Comportement attendu**
Avec le talent Poisons Améliorés 5/5 ET sous l'effet du sort Envenimer pendant la durée du test je devrais avoir 67.5% de proc OR je constate 53% en jeu.

Je reste bien évidemment à la disposition du staff pour tout complément.

**Comment by RiDDicKGaeris** [comment]
Deux petits suppléments : 
1 - Pour permettre d'etre sous venom H24 sur le PTR j'ai fait une macro que je spam
2 - J'ai refait le test "3" sur 1000 coups et ça semble converger vers 57%

![Wow_KR202W64yd](https://user-images.githubusercontent.com/2164176/152860080-d2d24a2a-c8ff-478d-b80d-e4db47cff07a.png)

**Comment by Zaralbahk** [comment]
il ne faut pas faire  25.71x1.5x1.75=67.48%  mais  25.71x(1+0.5+0.75)=57.84%
Et du coup on est tout pile sur ton résultat
Les amélioration de même type ne se multiplient pas mais s'additionnent

 (exemple plus parlant : le score de toucher -> prend un talent + 3% toucher par ex et rajoute le buff équi par ex, + 3 % toucher aussi; le résultat est 6 % de toucher et non 1.03*1.03=6.09% )
