### ISSUE TITLE
bug en forme marine druide

### ISSUE THREAD

**Issue by tydry** [way-of-elendil/3.3.5#137]
**Description**
lorsque je suis en forme marine avec mon druide lors de la quete [La nouvelle peste] quand je recupere les toneau les polygone de mon personnage font n'inporte quoi et le jeux fini par crasher

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- bateau sud est de l'accostage de la vengeance 
- Horde / Tauren / Druide
- [la nouvelle peste]
- Appothicaire lysander

**Comportement attendu**
juste récuperer le tonneau

**Comment by Killyana** [comment]
Désactives le patch HD, ou enlève la forme de aquatique avant de looter l'objet

**Comment by tydry** [comment]
j'ai rendu la quete merci
