### ISSUE TITLE
[Donjon BC] [Glissecroc : la Basse-tourbière] géant avec un mauvais skin

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1374]
Glissecroc : la Basse-tourbière https://woehead.way-of-elendil.fr/?zone=3716
à l'avant  dernier virage avant **La Traqueuse noire** l'un des géant n'a pas le bon skin 

Seigneur de Basse-tourbière https://woehead.way-of-elendil.fr/?npc=17734

screen : https://i.postimg.cc/D0QX57wr/Wo-WScrn-Shot-120921-193948.jpg
ressource : https://fr.tbc.wowhead.com/npc=17734/seigneur-de-basse-tourbi%C3%A8re

**Comment by Endalaust** [comment]
A vérifier si tu as client HD ou original.
S'il s'agit de l'HD, il y a peut être une confusion entre 2 pnjs, mais ce ne sera pas corrigé. Et à vrai dire, je ne vois que cette possibilité.

**Comment by Ferro3** [comment]
client normal

**Comment by Traesh** [comment]
Kreator — Aujourd’hui à 01:28
@Amandil Basse tourbière l'apparence c'est bien un problème serveur
je l'avais corrigé pour les excursions temporelles parce que j'avais le soucis aussi du coup
en gros dans la table creature le mob a un modelid différent du template et du coup aléatoirement ça génère l'un ou l'autre
y'a un délire comme ça de souvenir
Amandil — Aujourd’hui à 01:33
Go mettre les infos dans le ticket :3
Kreator — Aujourd’hui à 01:35
J'suis pas full sûr donc non
de mémoire c'est un truc comme ça, ça c'trouve c'est exactement ça, ça c'trouve c'est ça mais avec des variantes
@Traesh il le verra ici au pire 😄

**Comment by Ferro3** [comment]
nouveau screen ce jour
https://i.postimg.cc/mgn923wK/Wo-WScrn-Shot-021022-190338.jpg
