### ISSUE TITLE
Affichage item torse tissus hotel des vente

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#1375]
![image](https://user-images.githubusercontent.com/60304524/153160309-d7b102dc-d139-46e0-83dd-b61634b3be20.png)

![image](https://user-images.githubusercontent.com/60304524/153160353-9f295c3a-f7ab-4559-83bb-7c6c05ad20b3.png)

Soucis au niveau de l'affichage a l’hôtel des ventes d'item de type "torse". Ils apparaissent bien en ne filtrant que les items tissus mais sans filtrer davantage 
Soucis constaté uniquement avec les armures en tissu

Une fois le filtre "Torse" appliqué dans la recherche sur la gauche
![image](https://user-images.githubusercontent.com/60304524/153160426-32f57861-c23e-464a-ab9c-e4ef83a2827a.png)
N'apparaissent que les 3 items de qualité inhabituelle.

**Comment by Joebarfr** [comment]
Bug toujours pas corrigé et donc actuellement je mets en vente un objet qui ne s'affiche pas comme les autres et donc perd de l'argent 😕😕😕.

Sa serai cool de si plonger car je ne suis pas seul a vendre se produit


Merci d'avance

**Comment by Endalaust** [comment]
Y'a vraiment une demande de hotfix en moins de 48h après le report?
Ca t'empêches de jouer? Le serveur chain crash à cause de ça? La majeure partie de la population est impactée? 

Il y a un fix de prêt, qui n'a pas encore été validé ni déployé
Ca prendra quelques jours. Quoi qu'il en soit, ce report et le fait explicité, n'est pas une urgence nécessitant un hotfix. Le temps de, tu peux temporiser tes ventes.

**Comment by Ferro3** [comment]
vérifié partiellement, le fix à l'air ok
18/2/22 19h19 qualité inhabituel ok, qualité rare ok
https://i.postimg.cc/0yfkKS7V/Wo-WScrn-Shot-021822-191723.jpg
19/2/22 19h19 qualité blanc ok
> reste qualité épique

**Comment by Ferro3** [comment]
vérifié, fix ok
22/2/22 17h11 qualité épique ok
