### ISSUE TITLE
Bug hotel des ventes

### ISSUE THREAD

**Issue by Joebarfr** [way-of-elendil/3.3.5#1376]
Bonjour, j'ai mis en vente 2 " robe des magi" a l'hotel des ventes et quand on fais une recherche avec le nom de la robe, elles apparaissent, mais quand on va dans ARMURE / TISSU / TORSE  et que la on ne rentre aucun nom de la robe, elle ne figure pas dans la liste des objets en vente.

Le bug a été signalé a un MJ ( requete)  qui lui aussi de son coté a constater le bug et donc ma dit de venir ici pour signaler le bug

Voici la description de l'objet
Robe des magi
Lié quand equipé
Torse                tissu
Armure  58
+6 intelligence
+5 esprit
Niveau 35 requis
Niveau d'objet 40 
Equipé : augmente la puissance des sorts de 22

**Comment by Joebarfr** [comment]
Voir bug signaler par amigaull #1375

**Comment by Traesh** [comment]
> Voir bug signaler par amilgaull #1375

Je clôture donc celui-ci
