### ISSUE TITLE
[HF] "Flirter avec le désastre" qui ne se valide pas.

### ISSUE THREAD

**Issue by Apochryphos** [way-of-elendil/3.3.5#1378]
A cloturer Svp, raison trouvé, il faut un parfum qui s'achete avec des gages d'amour et pas celui acheté à l'aubergiste qui fait pourtant parti de l'event.

**Description**
Bonjour Le HF Flirter avec le désastre ne se valide pas.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Ironforge
- Alliance / Démoniste Humain
- Haut Fait Flirter avec le désastre
Je Saoule mon personnage jusqu'à vomir, je me parfume avec Flacon de parfum (et non pas l'eau de Cologne), j'envoie une poignée de pétale de roses sur le gnome Sraaz qui tourne au centre de IronForge puis je lui envoie un /kiss. Et le HF ne se valide pas.

**Comportement attendu**
Validation de flirter avec le Désastre.

**Captures d’écran / Vidéos**
/

**Ressources additionnelles**
/

**Comment by Endalaust** [comment]
Je pige pas, c'est un bug ou non du coup cette histoire de parfum achetable au bon endroit?

**Comment by Apochryphos** [comment]
Le HF demande à être parfumer avec un parfum de l'evenement sans préciser lequel, et apparemment celui acheté chez l'aubergiste ne compte pas pour valider ce HF. Il faut en acheter un à la gobeline avec des gages.

**Comment by Apochryphos** [comment]
Oui cette description est correcte mais pour le valider sur Woe il faut un des parfum acheté avec des gages d'amour mais ceux achetés chez l'aubergiste n'ont pas fonctionnés (pour moi en tout cas)

**Comment by Endalaust** [comment]
Effectivement, ca fait sens d'acheter les items de l'event et non les items globaux pour valider le hf d'event
Je ferme
Merci pour le feedback

**Comment by Ferro3** [comment]
pour faire [Flirter avec le désastre] https://woehead.way-of-elendil.fr/?search=Flirter+avec+le+d%C3%A9sastre
* il faut aussi se souler au maximum (cuite est totale)
* il faut acheter [Parfum « Enchanteresse »] https://woehead.way-of-elendil.fr/?item=49857 et non [Flacon de parfum] https://woehead.way-of-elendil.fr/?item=21829 et l'utiliser
* vérifier en faisant le /kiss
* il faut acheter [Poignée de pétales de rose] https://woehead.way-of-elendil.fr/?item=22218#contained-in-item et le lancer

le HF fonctionne parfaitement

**Comment by Apochryphos** [comment]
Dans ma requête MJ le MJ de woe m'a juste dit de mettre du parfum et non pas de l'eau de Cologne. Sachant que le parfum à acheter chez l'aubergiste [flacon de parfum] est celui qui a l'origine faisait fonctionner le HF sur offi ce n'est pas si évident.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Endalaust** [comment]
S'il y a un comportement différent de l'offi, merci de fournir une preuve qui va en ce sens pour qu'on corrige ;)

**Comment by Apochryphos** [comment]
Ton lien wowhead à était clair. Une maj sur l'offi à aussi engendré ce changement donc c'est blizzlike. C'est l'intitulé du HF  qui laisse à interprétation ^^

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________
