### ISSUE TITLE
[Mascotte] Marchand d'âme Éthérien, impossible de vendre à ce marchand.

### ISSUE THREAD

**Issue by KokirisWoe** [way-of-elendil/3.3.5#138]
**Description**
Il est maintenant impossible de vendre tout objet à ce marchand
npc=27914
.learn 49964 (Rajouter le familier dans sa collection)

Le Gossip du vendeur s'ouvre toujours. Je ne sais pas si le marchand peut nous vendre les objets, je n'ai pas les crédits disponibles pour vérifier. Par contre, lorsque tu veux vendre, tu as le beau petit message indiquant qu'il est impossible de vendre à ce marchand.

**Comment by joshwhedon** [comment]
https://www.wowhead.com/npc=27914/ethereal-soul-trader#comments
D'apres les commentaires il n'est pas possible de vendre des objets a ce vendeur.
