### ISSUE TITLE
[ICC] [Prof] Position de départ du boss

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1382]
Le prof n'est pas à sa place habituelle avant le lancement du combat

une image vaut tous les discours
https://i.postimg.cc/VkB1GKC8/Wo-WScrn-Shot-020922-221622.jpg

raid25hm fait le 9/2/22, wipe au 1er try, position identique au start du second try

c'est pas vraiment bloquant, juste gênant

**Comment by Ferro3** [comment]
est-il possible de forcer sa position à la fin du combat des 2 choses ?

lorsque le boss tombe, le prof est tp à la bonne position

**Comment by Sungis18** [comment]
Ce problème a-t-il été observé récemment ?

**Comment by Ferro-woe** [comment]
Pas vu depuis un moment (3 mois au mini).

**Comment by Sungis18** [comment]
Je l'ai reproduit hier en testant autre chose, ce qui peut produire le bug semble être le fait d'aggro (Pulentraille ou Trognepus) et mourrir vite ou aggro et sortir de la salle de sorte à ne pas laisser le temps à Putricide de reset son positionnement.

**Comment by Ferro-woe** [comment]
Bon la rédaction n'étant pas super, je viens préciser que ce problème a été vu en Hard Mode, 10 et 25 à plusieurs reprises et non en Normal Mode.
La mécanique viens des allers retours du [Professeur Putricide](https://woehead.way-of-elendil.fr/?npc=36678) qui lance des capacités en mode Hard Mode lors des affrontements de [Trognepus](https://woehead.way-of-elendil.fr/?npc=36627) ou [Pulentraille](https://woehead.way-of-elendil.fr/?npc=36626).
Si on tue le boss [Trognepus](https://woehead.way-of-elendil.fr/?npc=36627) ou [Pulentraille](https://woehead.way-of-elendil.fr/?npc=36626) alors que le [Professeur Putricide](https://woehead.way-of-elendil.fr/?npc=36678) est en mouvement on obtient alors une position erronée.

**Comment by Sungis18** [comment]
Bonjour @Ferro-woe, merci pour ces rapports détaillés, nous avons identifié la cause et proposé un correctif.

Bonne soirée
