### ISSUE TITLE
[ICC] [Prof Putricide] Bombe de gaz asphyxiant placement

### ISSUE THREAD

**Issue by Yoki-Gaou** [way-of-elendil/3.3.5#1384]
Les bombes de gaz asphyxiant (Les choking, les oranginas) posés par le Prof sont mal placés.

Il y a 5 jours: https://clips.twitch.tv/HedonisticSpunkySpindleMikeHogu-xhwKfEzRnPKTIUwc => Placement très éloigné
Il y a 5 jours: https://clips.twitch.tv/UglyMushyPistachioGivePLZ-Uz7AtDGHg7V4qxSe => Placement très éloigné + Décalage de placement par rapport à l'endroit où Prof envoie les bombes
Il y a 12jours: https://clips.twitch.tv/CheerfulCrunchyPineappleTBTacoRight-NHWgJCQZX52qMgj1 => Placement proche
Sur Offi à l'époque (Date / Patch inconnu): https://www.youtube.com/watch?v=0BwK4dNymmQ&t=140s => Placement encore plus proche

Les choking devraient se trouver derrière les jambes du professeur comme présenté par la dernière vidéo

Sort: https://woehead.way-of-elendil.fr/?spell=71255
Choking physique: https://woehead.way-of-elendil.fr/?npc=38159

**Comment by Ferro3** [comment]
placement des gaz asphyxiant (Les choking, les oranginas) ce jour 21/2/22 en icc25hm

https://i.postimg.cc/4NTNJj6T/Wo-WScrn-Shot-022122-220124.jpg
https://i.postimg.cc/Nf7GLbD2/Wo-WScrn-Shot-022122-220128.jpg

l'écartement à grandement changé par rapport à d'habitude

**Comment by Ferro3** [comment]
rappel des sorts pour mémoire :
[Summon Bombe de gaz asphyxiant](https://woehead.way-of-elendil.fr/?spell=71273)
[Bombe de gaz asphyxiant](https://woehead.way-of-elendil.fr/?spell=71255)
[Gaz asphyxiant](https://woehead.way-of-elendil.fr/?spell=71278)
