### ISSUE TITLE
[Pierre d'Élune] Cooldown avec un bijou

### ISSUE THREAD

**Issue by KokirisWoe** [way-of-elendil/3.3.5#139]
**Description**
Le Cooldown de [Lampe torche surpuissante] empêche l'utilisation de [Pierre d’Élune]
Réciproquement, la pierre empêche aussi l'utilisation de la lampe. 

**Étapes de reproduction**
Après avoir cast l'un des deux objets, le second ne peut tout simplement pas être lancé durant tout le cooldown de l'objet utilisé.  

https://woehead.way-of-elendil.fr/?spell=25823

item=21536
item=45631

**Comment by joshwhedon** [comment]
Desole, j'ai cherche un peu, j'ai rien trouve indiquant que c'est possible d'utiliser les deux. Les donnees client ont le meme groupe pour les cooldown, donc ca a ete voulu par blizzard a premiere vue.
