### ISSUE TITLE
[bug] Navire dans le Tram coté Ironforge

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#1393]
je remonte un screen pour le joueur **Helium** https://way-of-elendil.fr/armory/character/727734-helium

voici un beau bateau dans le Tram
https://i.postimg.cc/XJJ8HzZm/Wo-WScrn-Shot-022022-212624.jpg

bon courage pour répliquer ce bug, aucune idée de comment faire

il doit s'agit du coté **Ironforge**, à part le coté visuel, il n'y a pas d'impact pour les joueurs, ils peuvent traverser le bateau
pack **normal**

2 joueurs de plus me confirment le bug, et il date pas d'hier, 1 an et 2 ans (en gros)

**Comment by Zaralbahk** [comment]
J'ai deja vu ce bateau bloquer un couloir dans les enclos aux esclaves^^ ce bugg est assez mythique

**Comment by Zaralbahk** [comment]
![WoWScrnShot_030621_142625](https://user-images.githubusercontent.com/73133549/164554686-bb9c7ea0-7596-43b8-9b4e-a0b51033e474.jpg)
