### ISSUE TITLE
[ICC] [Prof] Transformation de la créature mutée raté (Abomination mutée)

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1395]
lors du pull du **Professeur Putricide** https://woehead.way-of-elendil.fr/?npc=36678, le MT2 doit boire la potion pour se transformer en **Abomination mutée**

au moment de boire, **lorsque le joueur bouge**, la transformation peut ne pas se faire correctement, et soit :
* il n'est pas transformé, s'il n'est pas bloqué, il peut re-cliquer sur la potion (normal) pour être à nouveau transformé
* la transformation se fait tout de même, mais sans le joueur, qui est bloqué de tous mouvements (pas normal), le dispel maladie est impossible (faute de cible), ça force donc le raid à wipe

arrivé le 13/2/22 en ICC25HM

ressource:
Transformation de la créature mutée https://woehead.way-of-elendil.fr/?spell=70311
Abomination mutée https://woehead.way-of-elendil.fr/?npc=37672
Transformation de la créature mutée https://woehead.way-of-elendil.fr/?spell=71503
Abomination mutée https://woehead.way-of-elendil.fr/?npc=38285
Preparation Professeur Putricide https://wowpedia.fandom.com/wiki/Professor_Putricide#Preparation

**Comment by Zaralbahk** [comment]
De ce que j'ai remarqué c'est surtout si je lance un sort entre le moment où je clique et le moment de la transformation que ca bugg, je n'ai jamais eu le pb en bougeant (par ex clic potion, lancer hystérie sur un allié durant les 3 sec qui suivent, => transformé mais incapable de bouger ou lancer de sort, pas possible a dispell)

**Comment by JeremyIsVersioning** [comment]
J'ai essayé de reproduire en vain (avec même sort pour être sûr). Toujours d'actualité ?

**Comment by Wilpok** [comment]
https://www.twitch.tv/trimano1/clip/AltruisticNurturingDiamondNomNom-_X-hOAY05ag5lvtV

Date de Mardi

Le druid tank boit la potion, l'abom pop, le druide tank n'est pas dedans (on ne sait pas si le bug est dû au fait qu'il soit morph, qu'il ait bougé, qu'il ait lancé un sort) normalement aucune de ces conditions n'affecte le bon fonctionnement, le druide tank peut bouger et l'abo est spawn inutilisable, indispellable, entrainant un wipe.
