### ISSUE TITLE
[mage] Combustion et bonus au dégâts des coups critiques

### ISSUE THREAD

**Issue by Zaralbahk** [way-of-elendil/3.3.5#1396]
Le sort combustion n'augmente pas le bonus aux degats des coups critiques de 50% comme indiqué sur le sort
https://woehead.way-of-elendil.fr/?spell=11129

Testé de jour, 100 boules de feu (aucun proc utilisé, les degats sont très stables: 
Hit: 5525 +/-2.5%
Crit: 10049 +/-2.5%

Première constatation, les dégâts critiques sont égaux à 180 % des dégâts normaux et non 200%  (je ne trouve pas de source sur le comportement attendu mais je m'attendais à 200%)

![WoWScrnShot_022322_115422](https://user-images.githubusercontent.com/73133549/155306278-66aeaf11-afd4-403d-b16f-30121662dc7b.jpg)

Ensuite avec combustion 3 coups critiques réalisés: 
Crit sous combustion: 11555 +/-2.5%

Les dégâts des critiques sous combustion sont égaux à 210% des dégâts normaux => ils devraient être égaux à :  
Dégâts de base + Bonus au dégâts critiques + Bonus combustion
100% + (80% comme observé plus haut ou 100% comme le comportement normal attendu?) + 50% (buff combustion) = 230% ou 250%

![WoWScrnShot_022322_121019](https://user-images.githubusercontent.com/73133549/155308590-d3c35162-62de-4b2a-9315-033e9484e236.jpg)

**Comment by Justforsoloq** [comment]
Me semble que le spell crit sur wotlk est de 150% (pas totalement sûr mais voilà les hotpatch wow) : 
[Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): All healing spells now crit for 200% instead of 150%.
https://wowpedia.fandom.com/wiki/Spell_critical_strike
[Patch 4.0.1](https://wowpedia.fandom.com/wiki/Patch_4.0.1) (2010-10-12):

    All mage and warlock spells now crit for 200% damage.
    Balance druids, shadow priests and elemental shamans receive a specialization bonus allowing their spells to crit for 200% damage.

**Comment by Justforsoloq** [comment]
https://wowwiki-archive.fandom.com/wiki/Spell_Power_(mage_talent)
ça peut t'aider dans les calculs avec les formules en dessous et l'explication

**Comment by Zaralbahk** [comment]
Ok donc ça ferait pour les crits :
bonus dégâts crit = bonus de base 50% + ardeur*bonus de base (50%*50%) = +75%   (pas loin du +80% que j'ai observé)

Et avec combu : 
bonus dégâts crit  = bonus de base 50% + ardeur*bonus de base (50%*50%)  + combustion*(ardeur*bonus de base+bonus de base) (50%*(50%*50%+50%)) = 212.5%  (ce qui n'est pas loin non plus de ce que j'ai observé)

En gros les amélioration de bonus au dégâts critiques s'appliqueraient l'une après l'autre en multipliant le bonus existant et non en s'additionnant. C'est surement faire comme ça actuellement mais est ce que c'est normal? Ca rend le bonus de la combustion égal à seulement +37.5% au final
