### ISSUE TITLE
4491 : Quête d'escorte où le PNJ "Ringo" ne se déplace pas. 

### ISSUE THREAD

**Issue by Yakshawoe** [way-of-elendil/3.3.5#1401]
**Description**
Ringo doit se déplacer dans la quête "Un peu d'aide de mes amis". Mais il ne se déplace pas. Il reste ancré à sa place d'origine. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Un'Goro (Crête de la fournaise)
- Faction / Race / Classe
- Un peu d'aide de mes amis
- Ringo

**Comportement attendu**
Ringo devrait se déplacer et effectuer son path jusqu'à la fin de sa quête d'escorte. 

**Captures d’écran / Vidéos**
Suffit d'y aller pour voir qu'il ne bouge pas mais dit son texte normalement.

**Ressources additionnelles**
(https://www.youtube.com/watch?v=QYhzH7wm2ww)

**Comment by Ferro3** [comment]
Il faut tout de même vérifier, mais cette quête devrait fonctionner parfaitement, en tout cas elle a toujours fonctionnée pour moi
[55] [Perdu !] https://woehead.way-of-elendil.fr/?quest=4492
'l'escorte" est un "accompagnement" et non une "escorte" comme on l'entend habituellement, le PnJ suit le joueur

du coup si on ne bouge pas, le PnJ ne bouge pas non plus, ça se voit très bien dans la vidéo

la "difficulté" consiste à arroser **Ringo**(https://woehead.way-of-elendil.fr/?npc=9999) lorsqu'il s’effondre, si on y prend pas garde, on le perd

**Comment by Yakshawoe** [comment]
J'irai check un peu plus tard dans la journée alors pour vérifier ça. Merci !

**Comment by Ferro3** [comment]
vérifié, fonctionne parfaitement
à cloturer

**Comment by Babyface-187** [comment]
Ça dépend, il y a de rares fois où Ringo reste bloqué au sol. Je n'en connais pas la raison. Une intervention in game d'un maître du jeu permet au joueur de finir sa quête.
