### ISSUE TITLE
https://woehead.way-of-elendil.fr/?quest=4492 

### ISSUE THREAD

**Issue by Yakshawoe** [way-of-elendil/3.3.5#1402]
**Description**
Je dois .die et .respawn Ringo pour que les joueurs puissent rendre la quête "Perdu !"
**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Un'goro (Crête de la fournaise)
- Faction / Race / Classe du personnage utilise
- Perdu !
- [Spraggle Frock](https://woehead.way-of-elendil.fr/?npc=9997)

**Comportement attendu**
Selon la vidéo que j'ai trouvé, on ne dois pas trouver Ringo mais trouver sa bouteille. Je crois que la superposition des deux quêtes sur Ringo n'a pas arrangé les choses. (4491 / 4492 bug lié)
**Captures d’écran / Vidéos**
[Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.]
https://www.youtube.com/watch?v=cgvZmfhc0SI

**Ressources additionnelles**
https://fr.wowhead.com/quest=4492/perdu#comments

**Comment by Ferro3** [comment]
tant que l'"accompagnement" n'est pas terminé le PnJ est en effet inaccessible par les autres joueurs, c'est tout à fait normal

https://fr.wowhead.com/quest=4492/perdu#comments : cette vidéo est sur l'extension cataclysme ou plus, donc hors de propos

**Comment by Ferro3** [comment]
https://github.com/way-of-elendil/3.3.5/issues/1401

**Comment by Ferro3** [comment]
vérifié, fonctionne parfaitement
à cloturer
