### ISSUE TITLE
[Quête] La grande aventure de M. Toumou

### ISSUE THREAD

**Issue by TrucEtrange** [way-of-elendil/3.3.5#1403]
**Description**
M. Toumou reste coincé dans le batiment de départ

**Étapes de reproduction**
Prendre la quête "La grande aventure de M. Toumou" auprès de Emilie dans les Grisonnes. Emilie sort du bâtiment mais M. Toumou reste bloqué. En conséquence, quand le loup qui doit blesser M. Toumou apparaît, le loup cours jusqu'au bâtiment, et Emilie aussi, avant de reprendre l'escorte.

**Comportement attendu**
M. Toumou suit Emilie

**Captures d’écran / Vidéos**
![image](https://user-images.githubusercontent.com/45370942/157227413-00a4eda2-97c1-4fd8-b6eb-0559dfe86c13.png)

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?quest=12027

**Comment by Babyface-187** [comment]
#977
