### ISSUE TITLE
https://woehead.way-of-elendil.fr/?object=2044

### ISSUE THREAD

**Issue by Yakshawoe** [way-of-elendil/3.3.5#1405]
**Description**
Les hivernales devraient pop dans la montagne d'alterac comme n'importe quel plante avec l'herboristerie. Malheureusement, ça ne pop pas dans cette zone. Le seul moyen de pouvoir les looter, ce sont en les lootant dans des conteneurs.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Any classes
- WORLD
- NO
- NO
- NO

**Comportement attendu**
Normalement, nous devrions pouvoir les trouver dans la montagne d'alterac. 

**Captures d’écran / Vidéos**

**Ressources additionnelles**
https://fr.classic.wowhead.com/object=2044/hivernale#herbalism -> lien wowclassic car en appuyant sur le bouton 'wowhead' sur woehead, ça nous redirige vers un autre objet qui n'est pas du tout le même.

https://woehead.way-of-elendil.fr/?object=2044

**Comment by Kaasss-woe** [comment]
Les hivernales apparaissent bien.
Il y a en tout 364 emplacements de plantes dans Alterac.
Sur ces 364, m4 concernent de l'hivernale.
A un même instant, il peut y avoir 17 plantes présentes en même temps sur ces 364, avec un temps de respawn de 1 minute.
Si toutes les 17 plantes sont présentes à un moment donné, il y a donc, d'après mes calculs, environ 43.5% de chances qu'aucune hivernale n'en fasse partie.
