### ISSUE TITLE
https://woehead.way-of-elendil.fr/?npc=33916 : problème "recommandation de Bravoure"

### ISSUE THREAD

**Issue by Yakshawoe** [way-of-elendil/3.3.5#1406]
**Description**
Le cout in game de la recommandation de Bravoure est de = 13200 points d'honneur et de 770 points d'arènes. Sur woehead, l'item est donné pour 100 points d'arènes. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe / Spécialisation : any
- Donjon / Mode de difficulté : WORLD
- Champ de bataille / Arène 
- Sort / Objet / Quête : no 
- Boss / PNJ / Monstre : https://woehead.way-of-elendil.fr/?npc=33916

**Comportement attendu**
Normalement, l'item devrait être achetable pour 100 points d'arènes

**Captures d’écran / Vidéos**
https://screens.way-of-elendil.fr/TesYARco.png

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?npc=33916

**Comment by Endalaust** [comment]
Il ne s'agit pas d'un bug, mais d'une notion de saison. Selon les saisons actives (actuellement courroucée) certains objets se vendent à un coût ou un autre. Or woehead affiche toutes les possibilités. Dans le cas présent, si tu regardes l'objet et non le pnj : https://woehead.way-of-elendil.fr/?item=45706#sold-by-npc 
On constate 2x le même PNJ :
![screenshot_1818](https://user-images.githubusercontent.com/1420867/160298245-01195d14-c38b-4fd1-bf3c-9b1ae0173bb0.jpg)

Si on clique sur chaque PNJ on constate en haut à droite une condition : 
https://woehead.way-of-elendil.fr/?npc=33933
Évènement : [Arena Season 8](https://woehead.way-of-elendil.fr/?event=60)
https://woehead.way-of-elendil.fr/?npc=33916
Évènement : [Arena Season 6](https://woehead.way-of-elendil.fr/?event=58)

Durant la S8 ce PNJ le vend bien au montant affiché, durant la v6, le prix change pour 100 pt et pour cause, ce PNJ était actif en S6... 
Ne me demande pas la logique qui se cache derrière tout cela, ca m'échappe moi même un peu. En revanche le comportement est normal. Enfin, il y a d'autres PNJs actifs sur cette saison, à Dala, qui vendent le même item à 100 pt.
