### ISSUE TITLE
Arme Runique Dansante

### ISSUE THREAD

**Issue by HurricaN** [way-of-elendil/3.3.5#1410]
Arme runique dansante ne tape pas assez, probablement un problème de stats transférées

- DK
- Toutes races
- Spécialisation
- Sang, Arme runique dansante
- Toutes circonstances

**Comportement attendu**
Reproduit les sort pour 50% des degats. Stat fixées sur celle du DK lors de l'invocation

**Comportement actuel**
- Pour des frappes de sang en moyenne a 10k avec le dk, celles de la l'arme dansante sont en moyenne a 1,6k
- L'arme runique subit des parés alors qu'elle devrai etre cap expertise si le DK est cap expertise
- Taux de crit de l'arme runique ridicule, pas de transfert du critique du dk non plus
- Pas essayé pour le toucher, hate, arpen, PA, force, %degat; possiblement pas de transfert non plus au vu l'état actuel de l'arme runique

**Comment by Justforsoloq** [comment]
ça marche pas comme ça t'as déjà des posts qui ont été fait sur la DRW avec les réponses.

**Comment by HurricaN** [comment]
Oui la pas de snapshot crit ou expertise et techniques nerf aussi

**Comment by Justforsoloq** [comment]
Non les techniques sont pas nerf

**Comment by Justforsoloq** [comment]
Suffit de lire ce que j'ai mis, c'est de l'anglais mais c'est clair :). 
Et même si actuellement et depuis 2021 le WoL ne marche plus, ce que j'avais link à l'époque était clair. Et tu peux voir les chiffres link de toute façon,

**Comment by HurricaN** [comment]
Donc normal que ca tape que a 1k2??

**Comment by Justforsoloq** [comment]
Oui.

**Comment by HurricaN** [comment]
Donc ya juste le snapshot des stat qui est pas script?

**Comment by Justforsoloq** [comment]
Pas des stats, du crit et de l'expertise (expertise à test), crit c'est sûr

**Comment by Justforsoloq** [comment]
Encore une fois, les damage sont bons, donc de ce côté c'est pas un soucis. Le soucis vient du fait que la drw ne crit pas assez sur woe en effet, et que selon ce que tu dis potentiellement elle se fait parry de dos ?

**Comment by HurricaN** [comment]
yes expertise et crit pas snapshot dapres ce que j'ai vu

**Comment by HurricaN** [comment]
Mais meme la PA et les %damage et la hate je suis pas sur que ca soit snapshot hein

**Comment by HurricaN** [comment]
Bah nan le principe cest de la claquer full proc pour qu'elle snapshot tout.. Comme pour tout les cd du genre

**Comment by Justforsoloq** [comment]
Non. 
Encore une fois j'ai la flemme de me re pencher dessus car je l'ai fait 3 fois sur les anciens BT et j'ai déjà prouvé 3 fois que les dmg étaient bons x). 
Les seules sources de trouble sur la drw woe ça peut être 1) le crit, 2) les parry qu'elle se prend. Pas de source sur la 2ème partie donc pas sûr si c'est normal, et vu que WoL n'est plus fonctionnel j'peux pas aller vérifier

**Comment by HurricaN** [comment]
Si c'etait juste un 50% modif elle taperai pas a 1k, la elle lance le meme sort mais avec ses stat et -50%

**Comment by HurricaN** [comment]
oui mais le truc est plus up on peu pas savoir quel proc le mec avais

**Comment by Justforsoloq** [comment]
Tu peux voir les dmg average de sa DS et les dmg average de la DRW DS. Donc clairement quand tu me dis que pour une DS 10k tu average DRW DS 1k6 c'est totalement normal.

**Comment by HurricaN** [comment]
Donc d'apres toi elle devrai pas snapshot les stat du moment de l'invocation?

**Comment by Justforsoloq** [comment]
Encore une fois, le crit si. Et c'est pas le cas sur woe, d'où le fait qu'elle crit très peu. Et l'expertise possiblement mais ça pas sûr à 100%

**Comment by HurricaN** [comment]
et les hate et les %degat? 
genre ta popo se fini la DRW garde la hate
tes ficelles fade la DRW garde les 15%

**Comment by TrucEtrange** [comment]
Pour les dégâts des frappes de l'arme runique dansante, les commentaires wowhead indiquent que l'arme pose ses propres maladies, et donc si tu ne reposes pas tes maladies une fois que tu as pop ta DRW, c'est normal que ça tape peu

**Comment by MJ-Vyr** [comment]
Cette question à déjà été abordée auparavant, elle l'est ici sans sources et visiblement sans compréhension du fonctionnement réel du sort en question.
N'hésitez pas à ouvrir un ticket si vous avez des informations sur l'application correcte du critique sur ce sort, puisque d'après les tickets précédents c'est le seul problème avéré.

Bonne soirée
