### ISSUE TITLE
[Champignons fantômes] Taux de réapparition... ils réapparaissent en vrai?

### ISSUE THREAD

**Issue by Biloup** [way-of-elendil/3.3.5#1412]
**Description**
Je suis allé essayer de farmer quelques champignons fantômes aujourd'hui. 
C'est une plante qui ne pousse que dans quelques zones ciblées, mais en quantité "normale" et avec une réapparition qui permet en théorie de faire le tour de la zone et de recommencer en faisant le ménage des mobs.
J'en ai trouvé en tout 4 sur les 3 spots les plus connues (Un'Goro + marécages de Zangar(2) ) dont 0 à Un'Goro. J'ai laissé mon perso connecté presque toute la journée sur une des zones et aucun champignon n'est réapparu.
lien : 
https://fr.wowhead.com/object=142144/champignon-fantôme

**Étapes de reproduction**
La plante ne réapparait pas après cueillette (sur 1 journée)

**Comportement attendu**
Elle devrait avoir une vitesse de réapparition "normale" et devrait apparaitre en plus grande quantité (sans excès évidemment)

**Captures d’écran / Vidéos**
Si besoin je pourrais en faire, mais la description wowhead (et les commentaires sur le farming) sont clairs je pense.

**Ressources additionnelles**
https://fr.wowhead.com/object=142144/champignon-fantôme
![image](https://user-images.githubusercontent.com/103538462/163060352-635796d0-be6e-495c-823b-e09e3f8d48f0.png)

**Comment by Ferro3** [comment]
je suis pas sur à 100%, il faudra donc une validation par quelqu'un ayant accès au code

les plantes repop sur une zone entière, et pas par entité (type de plante), donc si tu veux farmer des plantes spécifiques il faut farmer toutes les plantes de la zone, et pas seulement les plantes que tu désir (particulièrement vrai en norfendre)

il me semble qu'il y a un nombre fixe de spot pop en même temps (vrai en norfendre), lorsqu'on ramasse un spot, un autre le remplace (après le timer, 5 ou 10 mins je sais plus) au hazard sur un spot disponible sur la zone, cela dit je crois que sur vanilla le nombre fixe de spot pop n'est pas actif, du coup tous les spot peuvent être actifs

pour le spot des champignons fantômes essai aux hinterlands dans la grotte, ça devrait régler tes problèmes
https://woehead.way-of-elendil.fr/?object=142144

**Comment by Biloup** [comment]
Merci beaucoup de ta réponse.
Je n'avais pas pensé que cela fonctionnerait de cette façon. Ce n'est pas pratique pour ce genre de plante qui ne poussent que dans des zones très localisées.. 
Merci pour ton conseil, effectivement c'était un peu mieux dans les Hinterlands. Il me semble qu'il y avait au moins 1 joueur à farmer des plantes dans la zone, peut-être cela aidait aussi, ce qui confirmerais ce que tu dis.

Je laisse le post ouvert pour que quelqu'un puisse vérifier et/ou signaler si quelque chose peut être modifié ou si le fonctionnement actuel ne changera pas.

Merci encore! :)

**Comment by Ferro3** [comment]
**explication 2017** _merci à **Kreator** pour sa recherche_

source : https://forum.way-of-elendil.fr/viewtopic.php?id=2044
aller sur le post #7 rédiger par **Amandil**

je recopie ici le post source pour plus de facilité

**Amandil** a écrit :
Je crois qu'une explication du système de pool de plantes s'impose, non pas pour justifier la situation, mais au moins pour la clarifier. Et aussi pour envoyer un coup de coude dans les reins de Paragon qui est complètement buggé et qui propose les ressources sans aucun système de pool parce que leur core n'a pas été mis à jour sur Trinity Core depuis plus de 5 ans. On avait la même chose sous Burning Crusade après tout, quand c'était encore un bug smile

Une version qui circule souvent sur Elendil : Le nombre de plantes et de minerais est en fonction de la population, c'est partiellement vrai et je vais tenter de l'expliquer.

### L'exemple de l'aveuglette

Prenons au hasard [url=https://woehead.way-of-elendil.fr/?object=142143]l'aveuglette[/url] (sans jeu de mot) et gardons la zone [url=https://screens.way-of-elendil.fr/MMEAXsa7.jpg]du Marais du chagrin comme référence[/url] avec ses 159 spots. Le marais des chagrins se dit "Swamp of Sorrows" en anglais. Maintenant prenons la chose la plus significative, la liste des pools du serveur : [url]https://pastebin.com/0XCbTY1p[/url]

Ligne 43 nous avons ceci : [b][i](996, 40, 'MASTER Herbs Swamp of Sorrows zone 8'),[/i][/b]
Cette ligne indique que la pool de la zone Marais des chagrins contient [b]40 plantes au total[/b], dont l'aveuglette qui dispose elle de 159 spots.

Éclairage sur ce fait curieux : L'aveuglette peut pop dans 159 endroits différents, mais ne pourra jamais dépasser les 40 spots présent dans la zone. Pour être exact, c'est même beaucoup moins car la pool de 40 spawns est partagée avec les autres plantes locales comme la [url=https://woehead.way-of-elendil.fr/?object=2046]Dorépine[/url], la [url=https://woehead.way-of-elendil.fr/?object=2043]Moustache de Khadgar[/url], [url=https://woehead.way-of-elendil.fr/?object=1624]le Sang-royal[/url], la [url=https://woehead.way-of-elendil.fr/?object=2041]Vietérule[/url] et enfin quelques rares [url=https://woehead.way-of-elendil.fr/?object=2045]étouffantes[/url]. Donc parmi toutes ces plantes, il n'y aura que 40 spawns.

### La gestion de la pool

Chaque fois que vous récoltez une plante (ou un minerai), la pool passe instantanément de 40 à 39, mais la pool reste toujours à 40 donc pour se faire, elle va spawn une autre plante de sa pool pour revenir à 40 spaws simultanés. De ce fait dans une zone (et vous avez via le lien pastebin plus haut toutes les informations nécessaires pour identifier les zones que vous accusez de dépérissement naturel par Monsanto) vous aurez toujours le nombre de spawns de la pool présents, répartis sur chaque emplacement possible de spawn de chacune des plantes de cette pool.

[b]Maintenant intégrons la variable qui dérange [/b]: Dans le marais des chagrins nous avons identifiés [b]5 plantes différentes [/b]pour un total de 40 plantes disponibles. Nous avons aussi remarqué que les étouffantes et les sangs royal n'étaient pas bien nombreux contrairement aux autres, cf la liste classée par nombre des plantes dans la zone :

[url=https://woehead.way-of-elendil.fr/?object=142143]Aveuglette[/url] : [b]159[/b]
[url=https://woehead.way-of-elendil.fr/?object=2046]Dorépine[/url] : [b]91[/b]
[url=https://woehead.way-of-elendil.fr/?object=2043]Moustache de Khadgar[/url] : [b]60[/b]
[url=https://woehead.way-of-elendil.fr/?object=2041]Vietérule[/url] : [b]19[/b]
[url=https://woehead.way-of-elendil.fr/?object=1624]Sang-royal[/url] : [b]9[/b]
[url=https://woehead.way-of-elendil.fr/?object=2045]Etouffantes[/url] : [b]5[/b]

([i]N'hésitez pas à cliquer sur les liens pour voir les emplacements des plantes sur la map[/i])

De par un piètre savant calcul permettant un dispatch, nous arrivons à cette répartition sur les 40 spawns disponibles :
343 plantes au total, répartie dans 40 slots, avec le pourcentage qui suit

[url=https://forum.way-of-elendil.fr/upload/44786/1513065130_pool.jpg][img]https://forum.way-of-elendil.fr/upload/44786/1513065130_pool.jpg[/img][/url]
[i][url=https://forum.way-of-elendil.fr/upload/44786/1513065130_pool.jpg]Si tu cliques là, ca agrandi l'image, MAGIC[/url][/i]

Ce qui nous donne pour 40 spawns :

[url=https://woehead.way-of-elendil.fr/?object=142143]Aveuglette[/url] : [b]18.4[/b] plantes
[url=https://woehead.way-of-elendil.fr/?object=2046]Dorépine[/url] : [b]10.8[/b] plantes
[url=https://woehead.way-of-elendil.fr/?object=2043]Moustache de Khadgar[/url] : [b]6.8[/b] plantes
[url=https://woehead.way-of-elendil.fr/?object=2041]Vietérule[/url] : [b]2.4[/b] plantes
[url=https://woehead.way-of-elendil.fr/?object=1624]Sang-royal[/url] : [b]1.2[/b] plantes
[url=https://woehead.way-of-elendil.fr/?object=2045]Etouffantes[/url] : [b]0.4[/b] plantes

Maintenant partons du principe (parce que c'est codé comme ça) que si vous prenez une aveuglette, [b]vous avez [color=red]X%[/color] de chance que la plante qui va spawn pour remplacer celle que vous venez de cueillir soit une aveuglette.[/b]

Ce X dépend du nombre de plantes présentes dans la zone et du nombre de spaws disponible, ici 6 plantes différentes, ce qui nous donne ceci :

[url=https://woehead.way-of-elendil.fr/?object=142143]Aveuglette[/url] : [b]46%[/b]
[url=https://woehead.way-of-elendil.fr/?object=2046]Dorépine[/url] : [b]27%[/b]
[url=https://woehead.way-of-elendil.fr/?object=2043]Moustache de Khadgar[/url] : [b]17%[/b]
[url=https://woehead.way-of-elendil.fr/?object=2041]Vietérule[/url] : [b]6%[/b]
[url=https://woehead.way-of-elendil.fr/?object=1624]Sang-royal[/url] : [b]3%[/b]
[url=https://woehead.way-of-elendil.fr/?object=2045]Etouffantes[/url] : [b]1%[/b]

Ainsi vous avez 46% de chance en cueillant une [url=https://woehead.way-of-elendil.fr/?object=142143]Aveuglette[/url] d'en faire pousser une autre, [b]et inversement 54% de chance de faire pousser une autre type de plante ![/b] Si vous voyez où je vais en venir ... Sinon, next chapter.

[h]Pourquoi certaines zones sont remplies de plantes qui ne m'intéressent pas et désertes de celles qui m'intéressent ?[/h]

Pour la démonstration suivante, je vais être un peu plus réducteur. Admettons une personne cherche à cueillir des [u]Aveuglettes[/u] dans une zone contenant [b]2 plantes uniquement[/b] : des aveuglettes et des Etouffantes

Ce joueur va se retrouver à récolter toutes les aveuglettes qu'il croisera, et laissera les étouffantes. Du coup tout ce qu'il restera sera de l'étouffante. Supposons qu'on démarre avec un redémarrage serveur du petit matin, sur 50 spawns dans la pool de la région qu'il farm avec autant de spawns d'aveuglettes que d'étouffantes. On aura donc [b]50 spawws[/b] contenant [b]25 aveuglettes[/b] et [b]25 étouffantes[/b].

Or la variable X défini 50% de respawn une aveuglette (sinon une étouffante). Du coup sur un farming des 50 spawns, il a pris 25 aveuglettes, et a laissé 25 étouffantes. [b]Les 25 plantes qui auront repop[/b] seront à [b]50% aveuglette[/b] et [b]50% étouffantes[/b], du coup la pool définie sur le second passage de ce joueur la zone comme suit :

[url=https://woehead.way-of-elendil.fr/?object=142143]Aveuglette[/url] : [b]12.5[/b] plantes à dispo
[url=https://woehead.way-of-elendil.fr/?object=2045]Etouffantes[/url] : [b]35.4[/b] plantes à dispo

De ce fait, plus il va farmer de l'aveuglette en laissant le reste, moins il y aura d'aveuglette. S'il refait un tour des 50 spawns malgré tout, on passe à la pool suivante dans la zone :

[url=https://woehead.way-of-elendil.fr/?object=142143]Aveuglette[/url] : [b]6.25[/b] plantes à dispo
[url=https://woehead.way-of-elendil.fr/?object=2045]Etouffantes[/url] : [b]43.75[/b] plantes à dispo

Et ainsi de suite ...

### What to conclude ?

Déjà voici un bon éclairage du fonctionnement des plantes et des minerais. Ce lien magique ( [url]https://pastebin.com/0XCbTY1p[/url]  ) vous permet de savoir la quantité d’éléments par pool et par régions pour tout royaume TLK sous Trinity Core dernière version (Paralol n'est pas concernée, désolé, là bas les plantes ont été pop à la main pour contenter la communauté).

Cette démonstration justifie les écarts trouvés en jeu sur certaines zones (et aussi le comportement de certains farmeurs qui dénaturent les régions et qu'on doit balancer par des reboots réguliers), cependant ça ne justifie pas tout. Il est probable qu'il y ait des problèmes sur des pools templates (la confiance en Trinity Core étant toute relative, on peut se permettre de douter du bon fonctionnement de l'ensemble).

Pour pouvoir investiguer dessus (investiguer = vérifier la pool template et la corriger si nécessaire), il faudrait le GUID d'une plante que vous estimez comme "introuvable". Vous ne serez pas en capacité de fournir un GUID, mais si vous nous donnez un screenshot de votre personnage sur la carte, et qu'à vos pieds trône une plante que vous estimez introuvable (oui je sais ca peut paraitre curieux de demander d'aller trouver les plantes introuvables), on pourra y jeter un oeil en nous servant de votre position sur la map pour aller récupérer le GUID de la plante.

En attendant deux points n'aident pas à trouver les plantes et les minerais de son choix :

[list=1]
[*]Les farmeurs mono compo[/*]
[*]La stabilité serveur[/*]
[/list]

Dans le premier cas, ces farmeurs qui ne visent qu'un type de plante pour craft un flacon particulier, réduisent la biodiversité du jeu, c'est un fait avéré, il y a toutes les nuits des mecs qui passent leur temps à ça au lieu de dormir. Quant au second cas, le meilleur moyen de faire table rase d'une pool et de la réinitialiser, c'est de redémarrer le serveur. Sur officiel il y a une maintenance/reboot tous les mercredis (je crois) pendant la nuit, afin de passer des correctifs s'il y en a, mais aussi pour  réinitialiser tout un tas de choses. De notre côté on n'a pas forcément la même fréquence et parfois le serveur s'étale sur la dizaine de jours (quand ca crash pas et qu'on passe pas de maj), ce qui réduit là aussi la biodiversité environnementale.  Piste de réflexion : Programmer un reboot auto 1x par semaine dans la nuit ? Why not.

En attendant, mea culpa...
Et vive Paragon smile

**Comment by Biloup** [comment]
Okaaaaay, merci beaucoup pour cet éclaircissement! La réponse était très détaillée, merci de l'avoir retrouvée (Je n'avais pas trouvé de sujets similaires en cherchant seul..). Le fonctionnement est clair maintenant.

Du coup j'ai une question : 
**Ne serait-il pas possible de créer un Pool par espèce dans chaque zone plutôt qu'un seul Pool global? Ce qui assurerait la présence de chaque espèce dans des proportions définies justement par ces Pools et indépendamment des autres espèces.** Ou bien n'est-ce pas faisable pour des raisons techniques Trinity Core tout ça?
(Je vois que la réponse datait de 2017, peut-être est-il possible depuis d' "améliorer" le système sans dénaturer le jeu et sans tricher en les faisant pop manuellement comme.... enfin voilà quoi ^^ )

Une référence à wofficiel laisse sous-entendre que le problème était le même, mais vu la commu ça aurait chouiné sec si le farm était si dépendant des farmeurs mono-compo. Même avec des reset hebdomadaires... nan? ^^" (je n'ai pas expérimenté à l'époque donc je n'en sais rien)

Merci beaucoup pour vos réponses claires et rapides! 👍 

(Du coup ce n'est pas un bug, mais dois-je fermer le sujet et poser ma question ailleurs?)

**Comment by Ferro3** [comment]
Les modifications se font sur la base de preuves Blizlike de l'époque à fournir.
Du coup si tu as des arguments à apporter vas y.
Sinon s'il s'agit d'une simple suggestions, elle est donc hors sujet et ne sera pas traitée.
Biz
