### ISSUE TITLE
AQ40 - Loot coffre de scarabées

### ISSUE THREAD

**Issue by Lirae** [way-of-elendil/3.3.5#1414]
Raid : Temple d'Ahn'Qiraj

**Description** :
Les [Grand coffre de scarabées] devraient contenir un [Sac de scarabées] à 100% mais ce n'est pas le cas.
L'anomalie avait été communiquée par requête IG voilà plusieurs mois mais l'information n'a pas due être remontée.

[Grand coffre de scarabées] : https://woehead.way-of-elendil.fr/?object=180690
[Sac de scarabées] : https://woehead.way-of-elendil.fr/?item=21156

**Comment by Ferro3** [comment]
wowhead classic dit 97% et pas 100%, bon disons 100%
voici les comparaisons avec la bd de woe :

[Grand coffre de scarabées](https://fr.classic.wowhead.com/object=180690/grand-coffre-de-scarab%C3%A9es) (wowhead)
* 100% pour [Sac de scarabées]
* 25% pour les idoles _au lieu de 12,5% sur [woe](https://woehead.way-of-elendil.fr/?object=180690)_ **(taux à corriger)**

du coup, je pense qu'en même temps il faudrait vérifier le [Sac de scarabées](https://woehead.way-of-elendil.fr/?item=21156)

[Sac de scarabées](https://fr.classic.wowhead.com/item=21156/sac-de-scarab%C3%A9es#contains) (wowhead)
* 50% pour les scarabés _les taux correspondent sur [woe](https://woehead.way-of-elendil.fr/?item=21156)_

le taux de drop du [Sac de scarabées](https://woehead.way-of-elendil.fr/?item=21156) signalé étant déjà à 100% dans le [Grand coffre de scarabées](https://woehead.way-of-elendil.fr/?object=180690) sur woe, **il y a un autre problème que la table de loot**

**sources :**
[Grand coffre de scarabées] [classic](https://fr.classic.wowhead.com/object=180690/grand-coffre-de-scarab%C3%A9es) [BC](https://fr.tbc.wowhead.com/object=180690/grand-coffre-de-scarab%C3%A9es)
[Sac de scarabées] [classic](https://fr.classic.wowhead.com/item=21156/sac-de-scarab%C3%A9es#contains) [BC](https://fr.tbc.wowhead.com/item=21156/sac-de-scarab%C3%A9es#contains)
_les tables wowhead classic et BC sont identiques, j'ai vérifié_
