### ISSUE TITLE
Entité : 123462 | Le joyau des mers du Sud

### ISSUE THREAD

**Issue by Yakshawoe** [way-of-elendil/3.3.5#1417]
**Description**
Le coffre crochetable ne l'est pas. (Non ciblable)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Voleur
- Cabestan  (64.94, 45.44)
----------------------------
- crochetage du voleur
----------------------------

**Comportement attendu**
Le coffre est crochetable est permet de monter jusqu'au niveau 120. 

**Captures d’écran / Vidéos**
https://screens.way-of-elendil.fr/Y8R29ehk.png

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?object=123462
https://fr.wowhead.com/object=123462/le-joyau-des-mers-du-sud
https://wolfendonkane.pagesperso-orange.fr/crochetage.html (ici, c'est bien écrit qu'on peut monter jusqu'à 120 avec ce coffre.)

**Comment by Ysya555** [comment]
Les coffres qui servent à monter le crochetage sont à l'étage au dessus.
https://screens.way-of-elendil.fr/bnaSdbB3.png
