### ISSUE TITLE
Quest: Les salles des reflets

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#142]
**Description**
En entrant dans la salle l'animation est bien là, Uther arrive mais l'épée a vaincre n'est pas là

**Comment by joshwhedon** [comment]
Impossible a reproduire de mon cote. Peut etre que les mises a jour recentes ont regle le probleme.
Tu entre, tu avance, Uther pop, tu avance un peu plus, l'epee saute et vole autour de la salle, et ensuite t'attaque.
