### ISSUE TITLE
[ Mailbox ] Vue sur la vente réussie

### ISSUE THREAD

**Issue by virgo77** [way-of-elendil/3.3.5#1423]
**Description**
La Boîte aux Lettres présente les 2 états de la vente d'un objet, acheté à l'Hôtel des Ventes
En gros, on voit ce que seul un admin/gm est capable de voir. C'est un peu gênant car elle contient alors 2x plus de données que nécessaire

**Étapes de reproduction**
Aucune en particulier
Simplement constater sur la PJ ci-dessous

**Comportement attendu**
Que la partie "vente en suspens" n'apparaisse pas pour tout joueur lambda

**Captures d’écran / Vidéos**
PJ '[MailBox1](https://mega.nz/file/RLoxgbqY#yoet5gSyHmLNHKqgIBV-LaQ9KBNWO-j4JEnWyVcxUxQ)'
PJ '[MailBox2](https://mega.nz/file/QChXzQ7b#vFHUb5yrIt96k9d_LKc6uhXjTgO8O8Xrno-z2AEuKDQ)'

**Ressources additionnelles**
-Néant-

**Comment by Endalaust** [comment]
Le concept de vente en suspens est blizzlike et a été implémenté par Blizzard en 2007. A l'origine l'idée était de contrôler via 1h de temps de modération, les vendeurs d'or massif sur l'officiel. Exemple : Je vends une tisse givre à 10000po, x100, et un vendeur d'or contre des $ sur une marketplace douteuse vient me les acheter massivement. Le délai d'une heure permet un check côté Blizzard pour intervenir et bloquer ces transactions virtuelles s'ils l'estiment frauduleuse. 

Sur woe, nous héritons du concept mais pas de la modération manuelle sur les transactions. Le fait de voir un courrier "en suspens" est on ne peut plus normal, et en principe, aucune transaction n'aboutit pas passé le délai, au réel paiement en monnaie virtuelle.

**Comment by virgo77** [comment]
Ah ! parce que je sais qu'il y a un délai d'1h entre l'achat réalisé et la remise en monnaie virtuelle. Mais je pensais que c'était le mode de fonctionnement normal sur les serveurs officiels. Et je n'ai pas souvenir que dans nos Boîtes aux Lettres, sur ces mêmes serveurs Officiels à l'époque - et encore plus aujourdh'ui-, on avait ce "message" de 'vente en suspens' supplémentaire.
En tout cas c'est intéressant de voir comment ça fonctionne :)
Merci pour ton retour. Je clos le ticket du coup

Au plaisir et bon jeu !

V.
