### ISSUE TITLE
bug de transmo des Masse à 1 main (PA/PS) 

### ISSUE THREAD

**Issue by woxhot** [way-of-elendil/3.3.5#1426]
**Description**

bug transmo : une masse PS ne peux pas ce transmo sur une masse PA et vice versa (le tout a 1 mains)
(ce qui est viable sur les épée PS / PA 1 main )

**Étapes de reproduction**

avoir une masse PS 1 main
avoir une masse PA 1 main

tenter une transmo sur l'une en cherchant a mettre l'autre dessus

**Comportement attendu**
possibilité de voir Tout les masse a 1 main sur la liste des possibilités + transmo

**Comment by MJ-Vyr** [comment]
Bonjour, après vérification ingame, aucun rapport avec les stats mais très probablement avec le fait que la plupart des masses une main PS sont "main droite" alors que l'équivalent PA n'est pas restreint à une main. 
Un scénario semblable est présent avec les épées une main comme la Vénéneuse et les épées main droite comme la KT sur Roi Liche.

Je clôture.
