### ISSUE TITLE
Les pnj à sauver d'une quête à Zul'Drak ne savent pas monter les escaliers alors que leur temps est limité

### ISSUE THREAD

**Issue by John361** [way-of-elendil/3.3.5#1427]
**Description**
Les pnj à sauver d'une quête à Zul'Drak ne savent pas monter les escaliers alors que leur temps est limité

**Étapes de reproduction**
- Zul'Drak (Norfendre)
- 58.7, 72.5 environ
- Fait avec un hordeux mais à voir si les ally l'ont aussi
- [76] Ne laissez personne derrière vous
- Donneur de quête : Dr Rogers

**Comportement actuel*
Les pnj parcourent les escaliers sur la longueur pour y monter et ils n'y arrivent pas tout le temps
Problème eu avec "Croisée Joséphine", la plus éloignée, qui est morte à cause de ça

**Comportement attendu**
Que les pnj montent normalement les escaliers

**Comment by Ferro3** [comment]
https://github.com/way-of-elendil/3.3.5/issues/1315
