### ISSUE TITLE
[Cinématique] Valider la quête "Retour à Angrathar" ne lance pas la vidéo

### ISSUE THREAD

**Issue by Belore** [way-of-elendil/3.3.5#1428]
La validation de la quête [12499] Retour à Angrathar devrait lancer une cinématique, mais elle opère seulement le changement de phase. La vidéo se lançait correctement il y a quelques mois.

https://woehead.way-of-elendil.fr/?quest=12499

**Comment by Ferro3** [comment]
[coté alliance 12499](https://woehead.way-of-elendil.fr/?quest=12499) fonctionne, vérifié sur PTR ce jour
[coté horde 12500](https://woehead.way-of-elendil.fr/?quest=12500) fonctionne, vérifié sur PTR ce jour

à clore, avec status invalide

**Comment by Belore** [comment]
Effectivement, avec mes excuses, il semble que ce soit un de mes add-ons récents qui fasse sauter les cinématiques. Désolé du dérangement !
