### ISSUE TITLE
quete

### ISSUE THREAD

**Issue by impietoyable** [way-of-elendil/3.3.5#1429]
la quete " la malédictions des marées" est bugué, en effet en cliquant sur l'autel le mob n'apparait pas; et impossible de recliquer sur l'autel.

- Emplacement: vallée de strangleronce
- Faction: alliance, Race: humain, Classe: dk
- Nom de la quête: la malédiction des marées

.

**Comment by Amilgaull** [comment]
Testé à l'instant, en cliquant sur l'autel, le pnj Gazban apparait bien sous l'arche à quelques mètres de l'autel. Fonctionnel sans problème du coup. J'ai même tenté de cliquer plusieurs fois sur l'autel, pour que l'autel fonctionne, il faut que le mob soit mort, si c'est le cas, l'autel en invoque un autre. Aucun problème pour cette quête du coup. Peut être que lorsque vous avez fait la quête un autre joueur était en train de tapper sur le mob à l'écart.
