### ISSUE TITLE
Bug quête: [Répandre la bonne nouvelle]

### ISSUE THREAD

**Issue by Erzer59** [way-of-elendil/3.3.5#1431]
Le 16/07/2022

**Description**
    Le pnj "Porte-peste en chef Mideton" nous demande de prendre un engin de siège pour aller larguer des bombes chancreuses sur des morts-vivants. Les véhicules sont disponibles, on peut monter dedans et les manoeuvrer. 
    Par contre, dès que je dépasse le premier arbre à la sortie du village, le personnage est automatiquement éjecté. Lorsque je remonte dans le véhicule, je suis de nouveau sorti immédiatement. J'ai essayé avec plusieurs véhicules et de passer à plusieurs endroits différents, mais il n'y a rien à faire, il y a une limite fixe qui me sort automatiquement du véhicule. J'ai vidé le cache mais cela ne change rien.

**Étapes de reproduction**
Lieu: Désolation des dragons, Vexevenin.
Coordonnées: 78,4 / 60,6
Personnage joué: Horde, Tauren guerrier niveau 76
Quête: Répandre la bonne nouvelle
Pnj: Porte-peste en chef Mideton

**Comportement attendu**
Le véhicule devrait pouvoir manoeuvrer et se déplacer librement sans la moindre éjection.

**Captures d’écran / Vidéos**

https://user-images.githubusercontent.com/109001178/179367153-d1de8b93-c82a-4180-9e2f-e22635e96389.mp4

**Comment by Ferro3** [comment]
le comportement est normal, tu as un autre chemin à prendre
Il faut passer par la gauche en prenant l'engin
c'est au nord sur ta mini carte, si je ne me trompe pas
biz

**Comment by Erzer59** [comment]
Effectivement, en prenant la route plus au sud il n'y a plus de problèmes.
