### ISSUE TITLE
Bug de masque

### ISSUE THREAD

**Issue by Primetime92** [way-of-elendil/3.3.5#1435]
Problème de clip au niveau de la barbe avec le masque

https://ibb.co/DQVxR7N

**Comment by Ferro3** [comment]
Pour info ce screen a été réalisé sur l'interface du barbier de SW
https://woehead.way-of-elendil.fr/?npc=29142

du coup, j'imagine que le problème a été vite réglé via une coupe

**Comment by Kaasss-woe** [comment]
Cet écart d'affichage vient directement du jeu lui-même.
Ce n'est pas quelque chose qui peut se régler au niveau du serveur.
