### ISSUE TITLE
Veine de titane et gisement de saronite

### ISSUE THREAD

**Issue by Nougouw** [way-of-elendil/3.3.5#1439]
Au joug les veines de titane disparaissent devant mes yeux avant de pouvoir miner, parfois au lieu de disparaître, un gisement de saronite apparaît à la place de la veine de titane.
Certains joueurs m'ont dis que c'était un problème de "phase" ????

Étapes de reproduction
J'ai miné pendant 2h seul au joug. Difficile de reproduire le problème, car il semble aléatoire.

Comportement attendu
Tout simplement que les veines/gisements arrêtent de se prendre pour Houdini et de disparaître !

**Comment by Nougouw** [comment]
Après avoir discuté avec d'autre mineurs du joug, le problème est apparu il y a à peu près 1 mois

**Comment by Ysya555** [comment]
Les veines de titane disparaissent quand vous laissez un item dedans. Il y avait avant un bug abuse sur les veines. Celui-ci a été corrigé et désormais même si vous voulez forcer le repop en titane, vous ne pouvez plus. La veine depop et repop en aléatoire si vous ne la videz pas entièrement, comme cela aurait toujours dû être.
