### ISSUE TITLE
[Magie Noire] ne fonctionne pas sur les sorts du druide féral

### ISSUE THREAD

**Issue by Fianso26** [way-of-elendil/3.3.5#144]
### Description 
L'enchantement Magie noire ne proc pas sur les spells du druide féral.

Druide
Night Elf
Spécialisation Combat farouche
Sorts utilisés : Mutiler, lambeau, griffure ...
Mannequin Hurlevent
Spell ID : 59625 [Magie noire]

### Comportement attendu 

L'enchantement Magie Noire devrait proc sur les sorts offensifs du druide féral ( Lambeau, Mutiler ..) et le talent Blessures infectées. Actuellement il fonctionne seulement sur la lucioles

**Comment by Killyana** [comment]
C'est fixé sur tc normalement: https://github.com/TrinityCore/TrinityCore/pull/24002/fileshttps://github.com/TrinityCore/TrinityCore/pull/24002/files

**Comment by Fianso26** [comment]
Donc c'est censé être effectif ?

**Comment by Killyana** [comment]
Non pas encore

**Comment by joshwhedon** [comment]
Ca sera merge chez TC un jour ? Ou vaut mieux qu'on le prenne ?

**Comment by Killyana** [comment]
C'est déjà merge, et sa fonctionne correctement sur TC
