### ISSUE TITLE
Personnage bloqué en fantôme quand déconnecté dans un raid en-dehors d'un groupe. 

### ISSUE THREAD

**Issue by Crepuscule4463** [way-of-elendil/3.3.5#1442]
**Description**
Quand je suis déconnecté et enlevé d'un groupe de raid, je ne peux plus trouver mon corps, même si je rejoins le même groupe de raid.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Caveau d'Archavon et Sanctum Rubis.
- Niveau de difficulté 10 et 25 normal

**Comment by Ferro3** [comment]
Salut

Tu es imprécis dans ta description
Le cas s'est présenté sur **Caveau d'Archavon** 10nm et **Sanctum Rubis** 25nm ?
_pour le **Caveau d'Archavon** il y a des contraintes supplémentaire avec le timer du joug et la faction le contrôlant _
tu es mort dans l'instance du raid ou à l’extérieur ? où exactement ?

Du coup, je comprends pas trop ton soucis, alors je ai du faire des suppositions

Voilà comment ça devrait se passer :
Pour ressusciter son personnage **si**, (1) on est mort dans l'instance d'un raid (2) et qu'on a été kick du même raid
> il faut re-franchir le portail de ce même raid en fantôme, à ce moment là, le personnage ressuscite à l'extérieur du raid dans le portail

si rien ne marche, il te reste le rez à l'ange du cimetière, voici un lien vers les anges du jeu :
https://woehead.way-of-elendil.fr/?npc=6491
+

**Comment by Crepuscule4463** [comment]
Bonjour, dans le cas présent, je suis resté en fantôme même en étant rentré
dans l'instance. Il y a en effet le fantôme mais c'est problématique si on
utilises plusieurs personnages dans le raid car le perso sera inutilisable
pendant 10min.

Cdt

**Comment by Ferro3** [comment]
Description du problème imprécis, non reproductible
Aucune précision supplémentaire apporté dans la réponse

à clore en invalide
