### ISSUE TITLE
Objectif de quête disparaissent de la map

### ISSUE THREAD

**Issue by graundzy** [way-of-elendil/3.3.5#1443]
**Description**
les objectifs de quêtes les zone ou je dois aller récupérer les items et etc disparaissent de ma carte au bout de quelque seconde après ma connexion j'ai essayé plusieurs deco reco sans succès il m'est don tres compliqué de suivre mes quêtes ce qui rend l'expérience de jeu moins agréable  

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement les croisées dans les tarides 
- Faction / Race / Classe du personnage utilise la horde tauren druide de niveau 12
- Nom de la quête toutes les quêtes que j'accepte 
- Nom du donneur de quête

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Ferro3** [comment]
Aucunes précisions permettant de reproduire, pas de quêtes citées.
Joueur niveau 12, probablement un nouveau joueur.

Un soucis de configuration d'addon ?
Réponse par défaut, voici un addon permettant d'avoir les objectifs des quêtes en jeu : https://addons.way-of-elendil.fr/quetes-and-leveling#quest-helper

A clore en status-invalid

**Comment by Ysya555** [comment]
Certains joueurs se plaignent de ne plus voir leurs quêtes sur la map ou bien de les voir mais à des emplacements inadaptés.
C'est un bug connu qui est lié aux Tarides, il suffit d'avancer dans les quêtes pour que tout redevienne normal.
(Il y a une quête aux Tarides qui, lorsque tu la prends, affecte le visuel des autres sur la map)

**Comment by MJ-Vyr** [comment]
Je ferme ici, pas d'info pas de source pas de retour du joueur.
