### ISSUE TITLE
SINDRA transi jusqu'au OS 

### ISSUE THREAD

**Issue by woxhot** [way-of-elendil/3.3.5#1445]
Description

Étapes de reproduction

    Donjon : ICC
    Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc) : tous
    Boss : Sindragosa
    Sort en question / Phase du boss en question / Emplacement : Froid envahissant / Transi jusqu'aux os

Les attaques en mêlée et à distance contre Sindragosa peuvent appliquer des charges de Transi jusqu'aux os coup sur coup.

Comportement attendu

Les charges de Transi jusqu'aux os ne doivent pas pouvoir être gagnées à moins de 2 secondes d'intervalle. Chaque coup doit avoir 20% de chance de gagner une charge du débuff, avec un temps de recharge de 2s.

Cette hypothèse est supportée par les indications sur Froid envahissant, l'aura qui cause le gain de stacks (source : wowhead). On voit clairement les chances de proc (20%), et la mention de l'ICD (2s). Sur woehead, seul les 20% de chances d'application sont indiquées, et nulle mention n'est faite de l'ICD.

De plus, sur cette vidéo datant du premier down Sindragosa, on peut avoir à plusieurs reprises le point de vue d'un voleur, et on voit qu'un temps est bien respecté entre chaque gain de charge de Transi jusqu'aux os. Deux charges ne sont jamais acquises à moins de 2s d'intervalle.

Captures d’écran / Vidéos
https://www.youtube.com/watch?v=LVcWZ5hfhis

Ressources additionnelles
https://www.wowhead.com/fr/spell=70106/transi-jusquaux-os
https://www.wowhead.com/fr/spell=70107/froid-envahissant

**Comment by woxhot** [comment]
Il fait sens que cette limite de 2 secs ICD est là pour protéger les différentes classes qui ne fonctionne pas tous à le même hit speed rate.


Certaines classes sont automatiquement plus l'aisé que d'autres là où tout les cac auraient du faire face à la même difficulté en plus d'augmenter automatiquement les Degats subies par le groupe CAC.

**Comment by woxhot** [comment]
![Uploading 201538491-4d97295c-a8aa-4252-82a0-93d28a510c6f.png…]()

**Comment by Killyana** [comment]
Le client wotlk classic a dévoilé des données qui n'étaient pas accessible dans le client 3.3.5.
Par exemple pour ce sort c'est possible de vérifier le GCD ici:
https://wow.tools/dbc/?dbc=spellauraoptions&build=3.4.0.46368#page=1&search=70107%20
C'est bien 2 secs

**Comment by woxhot** [comment]
https://user-images.githubusercontent.com/29866050/202759069-9388ad2b-3c00-49fb-9b92-55ccf1d3872e.mp4


Pour appuyer mon point précédent, je vous joins cette vidéo.
Sur cette vidéo qui fait 4.5 sec environ, j'ai le temps de prendre 5 stacks.
