### ISSUE TITLE
[Gestionnaire d'équipement] Expertise des classes spécialisées pas prise en compte

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1454]
Je fais cette requête pour [Nainbozo](https://way-of-elendil.fr/armory/character/728958-nainbozo)

**Description**
- Lorsqu'on est nain, qu'on utilise le gestionnaire d'équipement pour changer son arme, qui est une masse à l'origine, par une autre masse, l'expertise raciale (+5) n'est pas prise en compte.
- Si on change d'arme SANS utiliser le gestionnaire d'équipement le bonus est pris en compte.

_ouais c'est fourbe !_

**Étapes de reproduction**
- Nain, n'importe quelle classe pouvant équiper des masses 1M ou 2M 
- Créer 2 équipements avec le gestionnaire du jeu avec des masses 1M ou 2M
- Équiper une masse, puis utiliser le raccourcis du gestionnaire pour changer de masse

**Comportement attendu**
[L'expertise du raciale (+5)](https://woehead.way-of-elendil.fr/?spell=59224) devrait être pris en compte lors de l'utilisation du raccourci du gestionnaire d'équipement

**Captures d’écran**
Tests effectués ce jour sur PTR avec [Crève-tripes](https://woehead.way-of-elendil.fr/?item=51893), [Mithrios, héritage de Barbe-de-bronze](https://woehead.way-of-elendil.fr/?item=49997) et [Creuse-crypte](https://woehead.way-of-elendil.fr/?item=49919)
[![Wow-wolk-scr.jpg](https://i.postimg.cc/vTjZmGwG/Wow-wolk-scr.jpg)](https://postimg.cc/QKQ34GMz)
Les tests ont consisté à équiper la masse en manuel (arme à gauche), pour une expertise de référence (personnage au centre) puis d'équiper une autre masse, puis d'utiliser le raccourcis du gestionnaire d'équipement (personnage à droite)

**Ressources additionnelles**
[Spécialisation Masse](https://woehead.way-of-elendil.fr/?spell=59224)

**Comment by Ferro-woe** [comment]
Même chose sur :
- masses pour les humains _vérifié sur PTR ce jour_
- épée pour les humains _vérifié sur PTR ce jour_
- haches pour les orcs _vérifié sur PTR ce jour_

Donc en fait, tous les bonus d'expertise sont concernés.

Je rappel, que si vous voulez créer plusieurs sets d'équipement, il vous faut vous déconnecter entre chaque création, sinon au prochain chargement, uniquement la première sera sauvegardée et vous perdrez les suivantes.

**Comment by Belore** [comment]
Précision : à moins que ça ait changé (j'avais testé il y a des années), c'est un bug d'affichage, le bonus d'expertise est bien pris en compte même s'il n'est pas affiché sur la feuille de personnage.

**Comment by Ferro-woe** [comment]
Ha !
Ben tant mieux si ça n'est qu'un bug d'affichage.
Il faudrait, tout de même, une confirmation que ce n'est que de l'affichage, et voir si c'est "fixable".
ça sent le bug client, une intuition.

**Comment by Justforsoloq** [comment]
C'est pas un bug d'affichage, c'est de base comme ça sur Wotlk vanilla (et c'est encore le cas comme ça sur classic).
C'est comme le cap toucher avec les talents.
Tu fais ton calcul toi même

**Comment by Belore** [comment]
L'expertise conférée par les talents et raciaux est prise en compte sur la feuille de perso, contrairement au toucher. Enfin, sauf dans ce cas particulier où on active le bonus via le gestionnaire d'équipement !

**Comment by Justforsoloq** [comment]
En effet, au temps pour moi, effectivement l'expertise c'est pas comme le hit je viens de faire le test
