### ISSUE TITLE
Bug totem de glèbe

### ISSUE THREAD

**Issue by Ananas44** [way-of-elendil/3.3.5#1457]
Malgré la présence du totem de glèbe à proximité du chaman un chasseur peut le trap (flèche givrante)

Étapes de reproduction :
-Prendre un chasseur
-Prendre un chaman
-Invoquer un totem de glèbe (chaman)
-Lancer flèche givrante (chasseur)

Comportement attendu :
Le totem de glèbe devrait depop au lieu de trap le chaman

Captures d’écran / Vidéos
![WoWScrnShot_010423_173858](https://user-images.githubusercontent.com/121964207/210604911-0af9c462-fb96-486e-858f-61086fd00573.jpg)

Ressources additionnelles
Pas de ressource additionnelle, 
Description totem de glèbe : Il dispose de  points de vie et redirige sur lui même un sort offensif lancé sur un membre du groupe proche.

**Comment by Ferro-woe** [comment]
Les 2 techniques citées : [Totem de glèbe](https://woehead.way-of-elendil.fr/?spell=8177) [Flèche givrante](https://woehead.way-of-elendil.fr/?spell=60192)

**Comment by MJ-Vyr** [comment]
Pas de source donnée, je close

**Comment by sithis2a** [comment]
Le bug est avéré et le totem de glèbe ground le freezing trap depuis Vanilla et encore actuellement sur Retail. Avec un peu de recherche sur Google tu as bien des sources:

> it DOES eat Freezing Trap as well...which confuses the crap out of most Hunters =)

[MMO Champion](https://www.mmo-champion.com/threads/957821-Grounding-Totem)

> It did in Classic and TBC, should continue to do so.

[Can You Use Grounding Totem On Ice Trap In WotLK](https://us.forums.blizzard.com/en/wow/t/can-you-use-grounding-totem-on-ice-trap-in-wotlk/1246064)

Et en bonus une ancienne issue sur Trinity Core sur le même soucis:

> @Rushor Yes, i tested it with Freezing Arrow and confirm

[[Core/Spell][Shaman] Grounding Totem - Missing Grounding #15108](https://github.com/TrinityCore/TrinityCore/issues/15108)

**Comment by Ferro-woe** [comment]
Comme tu peux le constater, y a une ou deux requêtes en attente de traitement, 173 en fait.
Il revient donc à la personne qui rédige la requête de démontrer le problème avec des sources, et surtout si c'est à la portée de tous.
Ce n'est pas aux développeurs de le faire, même si de temps en temps y a des exceptions, par exemple le placement du professeur récemment fixé (1382).
Et enfin, si le problème est présent sur l'officiel, le souci ne sera pas traité, puisque le serveur se veut fidèle le plus possible à l'original, ça va même jusqu'à reproduire les problèmes de l'époque.

**Comment by Ferro-woe** [comment]
du coup à ré-ouvrir, maintenant que c'est sourcé.
rappel de la source: https://github.com/TrinityCore/TrinityCore/issues/15108

**Comment by sithis2a** [comment]
Comme tu peux le constater Vyr n'est pas dev et donc je ne demande pas aux devs de le faire (même si comme tu le dis c'est à la portée de tous).
De plus la personne qui a rédigée le ticket ne savait ptet pas où/comment chercher, ou qu'il fallait fournir des preuves avec (suffisait de demander derrière). Je t'avoue que pour certains, ce bug (et d'autres) est tellement obvious.
D'ailleurs, je ne suis pas la personne qui a rédigé le ticket mais pourtant j'ai rajouté des sources :> 

Par contre mea culpa, j'avais mal lu le message de Vyr et pensais qu'il disait ne pas avoir trouvé de sources.

Le ticket que j'ai link c'est sur du Trinity Core (l'émulateur du serveur si tu préfères) donc n'étant pas un bug présent sur offi il faut le fix.
Du coup à réouvrir en effet :)

**Comment by Ferro-woe** [comment]
Pour commencer, ici on n'attaque pas les personnes, mais les arguments.

> est tellement obvious

Ensuite, l'évidence qui est la vôtre ne l'est pas forcément pour le ou les développeurs.
Certains développeurs ne jouent pas du tout à Wow, du coup ça complique la compréhension du ou des problèmes.
C'est pour ça qu'il y a une demande d'une rédaction **très détaillée**, **explicite** pour la compréhension et **sourcée** pour que les modifications soient légitimes et non contestables.

Pour en revenir au sujet du [Totem de glèbe](https://woehead.way-of-elendil.fr/?spell=8177).
Une idée, le problème vient peut-être du fait que le [Piège givrant](https://woehead.way-of-elendil.fr/?spell=14311) ou la [Flèche givrante](https://woehead.way-of-elendil.fr/?spell=60192) ne font pas du tout de dégâts. Du coup, la redirection fonctionne surement, mais comme le totem n'est pas détruit alors le piège s'active tout de même.
Il faudrait regarder en détail, tester le [Totem de glèbe](https://woehead.way-of-elendil.fr/?spell=8177) avec un autre piège comme le [Piège d'immolation](https://woehead.way-of-elendil.fr/?spell=49056) par exemple, et savoir s'il est absorbé ou non.

**Comment by Ferro-woe** [comment]
Pour en revenir au sujet du [Totem de glèbe](https://woehead.way-of-elendil.fr/?spell=8177).
Une idée, le problème vient **peut-être** du fait que le [Piège givrant](https://woehead.way-of-elendil.fr/?spell=14311) ou la [Flèche givrante](https://woehead.way-of-elendil.fr/?spell=60192) ne font pas du tout de dégâts. Du coup, la redirection fonctionne surement, mais comme le totem n'est pas détruit alors le piège s'active tout de même.
Il faudrait regarder en détail, tester le [Totem de glèbe](https://woehead.way-of-elendil.fr/?spell=8177) avec un autre piège comme le [Piège d'immolation](https://woehead.way-of-elendil.fr/?spell=49056) par exemple, et savoir s'il est absorbé ou non.

**Comment by Justforsoloq** [comment]
Tu peux pas tester avec d'autres pièges, vu que le comportement du totem de glèbe est spécifique au piège givrant/flèche givrante (les autres pièges ne sont pas censés être pris par le glèbe).
Par contre tu peux tester avec la dissipation de la magie des priest qui fait pas de dégats aussi et qui est censé être prise en compte par le totem de glèbe (ça casse le glèbe)

**Comment by sithis2a** [comment]
> Pour commencer, ici on n'attaque pas les personnes, mais les arguments.
Hum d'accord, donc:
> Comme tu peux le constater, y a une ou deux requêtes en attente de traitement, 173 en fait.
Il revient donc à la personne qui rédige la requête de démontrer le problème avec des sources, et surtout si c'est à la portée de tous.
c'était s'attaquer à un argument ? :)

> Une idée, le problème vient peut-être du fait que le [Piège givrant](https://woehead.way-of-elendil.fr/?spell=14311) ou la [Flèche givrante](https://woehead.way-of-elendil.fr/?spell=60192) ne font pas du tout de dégâts. Du coup, la redirection fonctionne surement, mais comme le totem n'est pas détruit alors le piège s'active tout de même.
Il faudrait regarder en détail, tester le [Totem de glèbe](https://woehead.way-of-elendil.fr/?spell=8177) avec un autre piège comme le [Piège d'immolation](https://woehead.way-of-elendil.fr/?spell=49056) par exemple, et savoir s'il est absorbé ou non.
Le totem de glèbe est sensé, je cite, "redirige sur lui-même un sort offensif lancé sur un membre du groupe proche. Il ne redirige pas les sorts de zone". Pas besoin que le sort fasse des dégâts. Par contre tant qu'on y est le glèbe atm sur WoE se casse (dans le sens ou le glèbe "ground" le sort) sur les [Météores](https://woehead.way-of-elendil.fr/?spell=53201) des équis, c'est une AoE donc ça ne devrait pas être le cas.

Anyway toujours à réouvrir @MJ-Vyr stp, les sources sont là.

**Comment by Justforsoloq** [comment]
Par contre pour la météore c'est normal, t'avais Epinard qui l'avait démontré dans un ancien poste, en gros t'as deux partie dans la météore, la partie AOE et la partie splash damage, la partie splash damage est bien sensée cassée le glèbe (pour ça aussi que sur les beast saurfang starfall t'as une partie du spell qui les tapent full)

**Comment by Ferro-woe** [comment]
> > Pour commencer, ici on n'attaque pas les personnes, mais les arguments.
> 
> Hum d'accord, donc:
> 
> > Comme tu peux le constater, y a une ou deux requêtes en attente de traitement, 173 en fait.
> > Il revient donc **à la personne** qui rédige la requête de démontrer le problème avec des sources, et surtout si c'est à la portée de tous.
> 
> c'était s'attaquer à un argument ? :)

si tu veux une guerre, t'es mal tombé.

**Comment by sithis2a** [comment]
> Par contre pour la météore c'est normal, t'avais Epinard qui l'avait démontré dans un ancien poste, en gros t'as deux partie dans la météore, la partie AOE et la partie splash damage, la partie splash damage est bien sensée cassée le glèbe (pour ça aussi que sur les beast saurfang starfall t'as une partie du spell qui les tapent full)

Autant pour moi, si tu as un link vers ça je suis chaud, je ne savais pas pour le coup (si tu n'as pas ça sous la main je chercherai plus tard)

> si tu veux une guerre, t'es mal tombé.

![spider-man-j-jonah-jameson](https://user-images.githubusercontent.com/2728272/224512337-52cd6b28-bee8-4736-b29e-af15105e83ba.gif)
