### ISSUE TITLE
[Outil donjon] Tag à répétition

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1462]
**Description**
Il est possible de tag et dé-tag en boucle à l'infinie dans l'outil donjon.
Est-il possible de mettre une limitation ? par exemple limiter à 5 tags avant 2 mins écoulées.

**Captures d’écran**
Certains on l'humour de répétition assez tenace, on compte 35 occurrences en moins de 5 mins

[![1-3-33-5-38-Wo-WScrn-Shot-122922-170721.jpg](https://i.postimg.cc/qRtWsCNH/1-3-33-5-38-Wo-WScrn-Shot-122922-170721.jpg)](https://postimg.cc/R6BP9h1g)
[![2-5-46-6-58-Wo-WScrn-Shot-122922-170751.jpg](https://i.postimg.cc/5ydK8Kc8/2-5-46-6-58-Wo-WScrn-Shot-122922-170751.jpg)](https://postimg.cc/nj21JkhL)
[![3-7-22-8-07-Wo-WScrn-Shot-122922-170853.jpg](https://i.postimg.cc/0jsZz6mf/3-7-22-8-07-Wo-WScrn-Shot-122922-170853.jpg)](https://postimg.cc/62MCSpM2)

**Comment by Sungis18** [comment]
Vu sur Warmane : 2 min de déserteur de donjon lors du refus de rejoindre le donjon, je trouve que c'est un bon compromis.

Sinon, si quelqu'un peut voir ce qui se passe sur Wotlk Classic quand on spam, je suis preneur.

**Comment by Sungis18** [comment]
Sur offi : pas de contrainte, les joueurs peuvent lancer et quitter à volonté. Il ne s'agit donc pas d'un bug, nous comprenons l'enjeu mais cela intègre désormais la liste des demandes en attente d'aribitrage.

**Comment by Babyface-187** [comment]
Si c’est pas un but, ça a plus sa place ici : https://way-of-elendil.fr/suggestions

**Comment by Ferro-woe** [comment]
https://way-of-elendil.fr/suggestions/1577-%5Boutil-donjon%5D-tag-a-repetition
