### ISSUE TITLE
Impossible d'enchanter un item ilvl 61 avec un enchant ilvl 60 mini

### ISSUE THREAD

**Issue by CatUnderInfluence** [way-of-elendil/3.3.5#1469]
**Description**
Impossible d'enchanter un item ilvl 61 avec un enchant ilvl 60 mini

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe : Prêtre lvl 74 h² enchant 370
- Race : Réprouvé
- Spécialisation : Ombre
- Sort / Talent / Etc : Enchantement de plastron (pts mana exceptionnel)
- Circonstances (Donjon, Raid, PvP, autre) : Dalaran
- Equipement : équipement cible : Tunique céleste de courroux ténébreux https://woehead.way-of-elendil.fr?item=14308

**Comportement attendu**
Enchantement qui proc, mais non.

**Comment by Belore** [comment]
Ce n'est pas un bug, même si c'est vrai que ce n'est pas clair dans le jeu (la faute à l'officiel) : contrairement à ce que le tooltip de l'enchantement laisse entendre, c'est le "niveau requis" (ici 56) qui est concerné, pas le "niveau d'objet" (ici 61). Il n'y a pas toujours de niveau requis, mais à Vanilla la différence entre les deux est toujours de 5, donc pour un enchantement qui requiert "niveau 35 minimum" il faut un ilevel de 40 ou plus, et pour un enchantement qui requiert "niveau 60 minimum" il faut un ilevel de 65 ou plus.

**Comment by Ferro-woe** [comment]
Pour afficher l'item level :
Menu - Interface - Affichage - Afficher niveau d'objet (en bas à droite)

[[Tunique céleste]](https://woehead.way-of-elendil.fr/?item=14308) donc item level est de 61
[Ench. de plastron (Pts mana exceptionnels)](https://woehead.way-of-elendil.fr/?spell=27958) requière un item level de 60

Du coup, oui c'est normal que tu ne puisses pas le faire.
Biz

**Comment by Ferro-woe** [comment]
à cloturer

**Comment by Sungis18** [comment]
Je clôture, merci.
