### ISSUE TITLE
[Débuff] Durée du [Mal de la résurrection] hors ligne

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1475]
**Description**
La durée du [[Mal de la résurrection]](https://woehead.way-of-elendil.fr/?spell=15007) ne s'écoule pas lorsque le personnage est hors ligne.

**Comportement attendu**
La durée du [[Mal de la résurrection]](https://woehead.way-of-elendil.fr/?spell=15007) devrait s'écouler lorsque le personnage est hors ligne.

**Captures d’écran**
[![Wo-WScrn-Shot-012123-161123.jpg](https://i.postimg.cc/W3fkQxbh/Wo-WScrn-Shot-012123-161123.jpg)](https://postimg.cc/WFgzZWZv) [![Wo-WScrn-Shot-012123-161615.jpg](https://i.postimg.cc/xjhxw1Cy/Wo-WScrn-Shot-012123-161615.jpg)](https://postimg.cc/bd09b81s)

**Ressources additionnelles**
source : [wowhead](https://www.wowhead.com/fr/spell=15007/mal-de-la-r%C3%A9surrection) tagué **[Continue après la déconnexion]**

**Vérifications additionnelles**
Vérifiées et pas de problème avec [[Déserteur]](https://woehead.way-of-elendil.fr/?spell=26013) et [[Déserteur de donjon]](https://woehead.way-of-elendil.fr/?spell=71041) qui continuent bien après la déconnexion.

**Comment by Kaasss-woe** [comment]
Sur wohead il est aussi écrit ça, dans les commentaires :

> Good news: As of patch 7.3.5 the resurrection debuff counts down when you are logged out. So no longer do you have to spend 10 minutes online with the debuffed character, but can do something else on one of your other toons until the debuff is gone.

Je clos donc

**Comment by Ferro-woe** [comment]
Je disais bien aussi que c'était bizarre que ça ne soit pas conforme, maintenant j'ai la réponse.
Désolé pour le temps perdu.
