### ISSUE TITLE
ICC - Princes de sang - Sequence break lors de cinétiques dans le plafond

### ISSUE THREAD

**Issue by Sungis18** [way-of-elendil/3.3.5#1480]
**Description**
Lors du combat contre les princes de sang, certaines cinétiques spawn trop haut (dans le plafond) et aggro Lana'thel ce qui créé un sequence break et tp tout le monde au début du raid.

**Étapes de reproduction**
Arrive aléatoirement lors de la rencontre avec les Princes de sang.

**Comportement attendu**
Les cinétiques ne doivent pas être dans le plafond et ne doivent pas aggro Lana'thel.

**Captures d’écran / Vidéos**
On ne peut pas vraiment en avoir car les joueurs se tp.

**Ressources additionnelles**
Aucune.

**Comment by Ferro-woe** [comment]
sur les cinétiques au cas où :
[boss] [ICC 10nm] Princes 4 cinétiques au lieu de 2 https://github.com/way-of-elendil/3.3.5/issues/1360
