### ISSUE TITLE
Recousu 25nm - Frappe Haineuse

### ISSUE THREAD

**Issue by Motordead** [way-of-elendil/3.3.5#1481]
**Description**
Voilà, on a fait Naxx 25 à 20 joueurs pour le HF, et on s'est heurté à un problème : les dégâts de la **Frappe Haineuse** du _Recousu_.
Pour le coup on a testé à 3 tanks au cas où, et on connait très bien la strat (les dps cac se baignent régulièrement dans la flaque pour réduire leur PV en pourcentage, très peu de healraid pour que les dps soient pas full life etc...)

Le problème qui s'est posé c'est que sur le 1er try les tanks on pas fait long feu, genre 10 sec de survie maximum. Et oui, au cas où vous vous poseriez la question : nos tanks ont bel et bien été les 1ers à mourir.
Le total de dégâts subis figure dans le screenshot.
2ème try on change 1 tank sur les 3. On a constaté que les MT2 n'ont pris AUCUN dégâts de la Frappe Haineuse. Le MT1 lui n'a pas pris que les auto-hit, rien de plus.
J'ai pas pu avoir le rapport de dégâts subis du 2ème try (allez savoir pk avec Skada... pourtant je l'ai paramétré) cependant j'ai confirmation de la part des MT2 et des healers qu'ils n'ont rien subis en dégâts.

Je soupçonne 2 choses :
- Premièrement que le **Recousu inflige des dégâts bien plus élevés avec la Frappe Haineuse que la normale**, largement plus prévu en phase normal en 25. Mais PAS de manière permanente. Cela semble être de manière aléatoire car nous n'avons pas eu de problème sur le 2ème try (euphémisme)
- Deuxièmement, sur ces fameux try où le script est foireux, **il ne balance pas la Frappe Haineuse sur les MT2**, pourtant c'est bien noté qu'il doit le faire sur celui ayant le + de PV actuel (en pourcentage).
- Troisièmement j'ai vérifié la compétence Frappe Haineuse sur WoEhead, et j'ai comparé les chiffres en 10 et 25. Pour le peu de temps que nos tanks soient restés en vie pdt le fight, cela ne semble pas correspondre, surtout si cette compétence de boss n'a pas de GCD, La compétence figure en 4 exemplaire sur WoEhead, peut-être 2 exemplaires sont les dégâts en mode enragé ? (supposition)
- Quatrièmement, nous avions fait le raid en 25 a 20 joueurs également la semaine dernière, et nous avons ce problème sur plusieurs try aussi, Par-contre au dernier try y'a pas eu de problème, tout comme hier soir.

**Étapes de reproduction**
- Donjon : Naxxramas
- Niveau de difficulté : 25 normal (il n'existe pas de mode Héro)
- Boss : Recousu
- Sort en question / Phase du boss en question : Frappe Haineuse, 15 sec après le pull (dont 5sec pour placer le boss)

**Comportement attendu**
Le boss est sensé être tanké par 2 tanks : 1 MT1 qui prend les attaques de base et le MT2 qui prend la Frappe Haineuse.
On privilégie le plus gros tank en poste MT2 pour mieux encaisser.
La Frappe Haineuse doit aller sur le MT2 et non-pas uniquement sur le MT1, et les dégâts doivent être conforme à la phase non-enragé en 25.

**Captures d’écran / Vidéos**
Lien des strat Naxxramas, je précise qu'il est impossible que ce soit calqué sur Classic WOTK vu que ce topic existait bien avant la sortie de Classic WOTLK.
https://wow-tactiques.fr.gd/Naxxramas.htm

Les dégâts subis sur le Recousu des 3 tanks
![Degâts subis Recousu 25 - 1er try](https://user-images.githubusercontent.com/116766346/216478819-69678b24-70ea-4fff-8cd5-d58b925e81b1.PNG)

Les 4 exemplaires de la Frappe Haineuse du Recousu, sur WoEhead
![FP - 5k7 max](https://user-images.githubusercontent.com/116766346/216478878-e97f28b9-5060-4ed1-be6a-d091a230861f.PNG)
![FP - 27k max](https://user-images.githubusercontent.com/116766346/216478880-8cd5f15e-31de-41f8-8c0b-adb44caeb1f1.PNG)
![FP - 32k max](https://user-images.githubusercontent.com/116766346/216478882-5ef64718-a89e-4603-b88c-0110c87328d1.PNG)
![FP - 81k max](https://user-images.githubusercontent.com/116766346/216478884-bbca8a9a-d4da-4b4c-974e-2a0e72524732.PNG)

Voilà

**Comment by Ferro-woe** [comment]
sources pour Naxxramas
[Naxxramas](https://wowpedia.fandom.com/wiki/Naxxramas?so=search), Boss [Patchwerk](https://wowpedia.fandom.com/wiki/Patchwerk)

Pour les screens, vous n'apportez aucune précision sur une attaque reçue par un tank via le journal de combat ou autre chose, qui ne correspondrait pas aux dégâts attendus.
Les 3 screens sont inutiles puisqu'il manque la précision du nombre d'attaques faites par le boss.

Pour moi, là a vu de nez, y a pas de problème, mais **je n'ai pas encore vérifié les dégâts du boss** sur le PTR.
Il faudrait voir les stuffs des tanks aussi, pour mieux comprendre le problème.
Je rappelle que ce boss est un "raidcheckeer" si vous n'avez pas le stuff, vous ne passez pas le boss. Ce boss est compliqué à tomber si vous le faites au stuff requis du pallier, faut BL à 5% et tout envoyer.

je rappel la stratégie éprouvée, au cas où :
> source : http://arthion.fr/aldea/2008/11/07/strategie-naxxramas-le-recousu/
>
> Le recousu a 4,325,000 HP (10joueurs) ou 13,000,000 HP (25 joueurs), que vous allez devoir descendre en moins de 6mn.
>
> Capacités :
>
> Frappe haineuse : Cette capacité tape le personnage à portée de mêlée qui a le plus de points de vie. Il l’utilise toutes les 1.2secondes. Cette capacité génère beaucoup d’aggro.
> Requiert deux tanks (ou plus à 25) pour encaisser les coups.
>Les soigneurs devront être réactifs sur les soins des tanks afin qu’aucun dps de subisse la capacité frappe haineuse. Les dps peuvent se tremper de temps en temps dans la gelée pour réduire leurs points de vie. Attention à ne pas rester dedans !
>
>Enrager à 5%
>les tanks gardent leur mur protecteur pour ce moment là.
>
>Enrager au bout de 6 mn : wipe du raid
>DPS MAXIMAL
>
>Ce combat ne nécessite aucune gestion d’aggro : en effet la capacité Frappe haineuse génère énormément d’aggro sur sa cible et a elle seule, permet aux tanks de rester confortablement à l’avance sur ce combat.
>
>Concernant le placement nous le plaçons à proximité de la rivière de gelée. Concernant les tanks nous mettons en palatank en MT : frappes rapides et faibles, toutes bloquées, et privilégions les druides en offtank qui pourront encaisser les frappes haineuses sans broncher. Ce combat est avant tout un énorme stress test des soigneurs à 25. Il suffit de perdre un offtank et le wipe va vite arriver. A 10 le combat est une triste blague pour peu que vous ayez un peu de stuff héroique.
>
>Stratégie
>
> 2 Tanks face au boss à heal dès que possible : les tanks sont ceux avec le plus de PV.
> Ne pas heal les cacs.
>Tanké dos au raid.

**Comment by Motordead** [comment]
Nous connaissons très bien la strat, c'est la même qu'en 10 et comment fonctionne la compétence Frappe Haineuse. 
Et oui nous savons très bien que c'est un gearcheck tout comme Saurcroc.
Je n'ai pas pu fournir plus de détails car Skada limite les informations (d'ailleurs je vais repasser sur Recount, là au moins j'aurai un graphique détaillé).
Mais tout ça n'explique pas le dernier try. Comme je l'ai dis, et cela fut confimé par les 2 MT2 ainsi que les healers, sur le dernier try les MT2 n'ont subis aucuns dégâts de la Frappe Haineuse.
Donc ça n'a rien a voir avec le respect de strat ou le gear du raid.

**Comment by Motordead** [comment]
Je reviens vers vous suite à nos 2 try (wype au 1er) de ce soir.

**1er try** : le MT1 s'est fait désosser, les MT2 aussi dès la reprise d'aggro. Wype du raid

Le MT1 :
![Recount dégâts subis](https://user-images.githubusercontent.com/116766346/217953580-a3fc7219-5244-4187-abe4-14a8846f69d4.PNG)
![Recount MT1 sur Recousu](https://user-images.githubusercontent.com/116766346/217953621-2ac83d0a-dbce-4ab8-b365-13e4199d1343.PNG)

Le 1er MT2 :
![1er MT2](https://user-images.githubusercontent.com/116766346/217953647-6012e5a2-7f16-4f98-9f06-01602ab24c11.PNG)

Le 2eme MT2
![2eme MT2](https://user-images.githubusercontent.com/116766346/217953670-94a5c073-e087-4e85-b147-a82529e4772d.PNG)


**2ème try** : le MT1 s'est fait down, puis rez par un BR de drood. On a réussi a down le boss

Le MT1 :
![MT1 2eme try](https://user-images.githubusercontent.com/116766346/217953996-137e6198-b3f2-4db2-8bc4-36ca31fd7b30.PNG)
![MT1 2eme try détaillé](https://user-images.githubusercontent.com/116766346/217954014-d72e2a19-2b49-4693-bd5f-f59f39f8f2a9.PNG)
![MT1 2eme try graphique](https://user-images.githubusercontent.com/116766346/217954029-ff29c072-9847-4e17-a579-9bfc70ca4f74.PNG)

Pour les MT2 c'est comme pour le 1er try.

Enfin bref, tout ça prouve que la mécanique Frappe Haineuse du Recousu est bugée, tant que les MT2 sont en vie, jamais le MT1 ne doit subis de Frappe Haineuse de manière constante.
Car même si les heals sont a fond sur le MT1, ils ne sera pas tjrs a 100% de vie, et toutes les 1,5sec la Frappe Haineuse _doit mécaniquement_ toucher celui ayant le plus de PV en % (donc les MT2 vu qu'ils étaient full life).

**Comment by MJ-Vyr** [comment]
Bonjour, votre ticket ne présente pas de source d'officiel (vidéo ou screenshots) confirmant vos dires. 
De plus, les recount "dégats totaux" ne nous donnent aucune indication sur le montant des dégats subis par le tank, s'il est normal ou non.
Votre description de  "tant que les MT2 sont en vie, jamais le MT1 ne doit subir de Frappe Haineuse de manière constante." n'est pas correcte.
 Si le MT1 possède plus de points de vie et d'aggro que les autres tanks, il subira des frappes haineuses.


Je suis désolé mais vous n'avez visiblement pas une compréhension suffisante des mécaniques de jeu pour ouvrir un ticket valable. 

Je clôture.

**Comment by Motordead** [comment]
` Si le MT1 possède plus de points de vie et d'aggro que les autres tanks, il subira des frappes haineuses.`

Sauf que le MT1 n'est presque jamais au-dessus des MT2 en % de PV vu qu'il se prend les auto-hit du boss.

Alors, comment dire... Les MT2 sont en permanence full life et ne prennent aucunes Frappe Haineuse (hormis quand le MT1 meurt), par-contre le MT1 se prend un ÉCRASANT montant de dégâts de la technique et vous savez toujours pas si c'est normal ou pas ?
C'est une blague ? C'est logique que la mécanique bug ! Le MT1 prend tout dans les dents ! Mêmes nos healers ont affirmé ne pas avoir eu besoin de heal les MT2 ! Les chiffres sont suffisamment aberrants en terme d'écart MT1<->MT2 pour que ce soit limpide !

Encore une fois c'est en POURCENTAGE ! Donc si le MT1 prend ne serait-ce qu'une petite baffe, même minime, l'écart fait que ce sera l'un des MT2 qui prendra la Frappe Haineuse.

**Comment by Ferro-woe** [comment]
> le MT1 se prend un ÉCRASANT
C'est impossible de prendre un écrasant si le tank a son cap défense de 550 ou -6% et pas 541 comme on peut le voir dans certains guides.

Le problème vient peut-être de là.

Tu parles de pourcentage, ou de statistique, ben vas-y démontres le problème de façon explicite. Nous on voit rien de pas normal, on se trompe peut-être, à toi de le démontrer.
En tout cas les screens que tu fournis sont insuffisant comme démonstration, ça prouve rien à par que les tanks prennent des baffes.

Tu as accès au PTR (comme tous les joueurs) si ça peut t'aider :
PTR public https://way-of-elendil.fr/account/ptr
commandes MJ https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130065/GM+Commands
auras MJ https://woehead.way-of-elendil.fr/?spells=-9

**Comment by Motordead** [comment]
Vyr est passé nous voir et a prit le temps de nous expliquer pas mal de choses.
Donc je prendrais des vidéos de nos prochains try et nous verrons de ce qu'il en découle.

Si j'ai le temps je passerai sur le PTR et je ferai des tests.
