### ISSUE TITLE
LK : Valkyr en transi

### ISSUE THREAD

**Issue by Belore** [way-of-elendil/3.3.5#1483]
**Description**
Pendant un LK 25h, une valkyr a pop à l'instant où on passait en 2ème transi et n'a pas disparu. Elle a lâché la personne une fois à 50% de vie, comme pendant la P2.

**Étapes de reproduction**
- Combat contre LK
- (Je suppose) passage à 40% à l'instant où il invoque les valkyrs. Ça doit se jouer à une seconde, car généralement elles disparaissent correctement au passage en transi.

**Comportement attendu**
La valkyr devrait disparaître en lâchant la personne au moment où la transi est lancée.

**Comment by MJ-Vyr** [comment]
Pas réussi a reproduire le cas de figure.
