### ISSUE TITLE
[Interface] Outil de recherche de groupe

### ISSUE THREAD

**Issue by JuDBav** [way-of-elendil/3.3.5#1485]
Salut

L'outil de recherche de groupe n'affiche pas le donjon d'Ombrecroc dans la catégorie "Donjons spécifiques" quand il le devrai.

Je suis un personnage de lvl28
Le donjon est lvl22-30 (https://www.wowhead.com/wotlk/fr/search?q=donjon+d%27ombrecroc)

![image](https://user-images.githubusercontent.com/127012639/222949259-382cbbf5-bfad-41e3-a0d7-37f053b7388b.png)

Je peux accéder à Brassenoire, qui est plus bas lvl
Je peux accéder à Mona Cim qui est plus haut.

J'ai des quêtes de niveau "vert" et "jaune pour ce donjon.

Le donjon devrait être dans la liste.

Merci !

**Comment by Ferro-woe** [comment]
Salut
J'ai le regret de t'informer que pour tag en spécifique le donjon d'Ombrecroc il faut être dans la plage 17-25.
Tu es 28, du coup, tu ne peux plus via l'outil donjon, tout est normal.

Pour information, voici la liste des [donjons classique](https://woehead.way-of-elendil.fr/?zones=2.0), et leurs restrictions :
1 Ragefeu (outil 13-20 - lv requis 8)
2 Cavernes des lamentations (outil 16-24 - lv requis 10)
3 Les Mortemines (outil 16-24 - lv requis 10)
4 Donjon d'Ombrecroc (outil 17-25 - lv requis 14)
5 Profondeurs de Brassenoire (outil 20-28 - lv requis 15)
6 La Prison (outil 21-29 - lv requis 15)
7 Kraal de Tranchebauge (outil 23-31 - lv requis 19)
8 Gnomeregan (outil 24-35 - lv requis 19)
9 Monastère écarlate (outil 28-44 - lv requis 21)
10 Souilles de Tranchebauge (outil 33-41 - lv requis 25)
11 Uldaman (outil 36-44 - lv requis 30)
12 Zul'Farrak (outil 42-50 - lv requis 35)
13 Maraudon (outil 40-52 - lv requis 35)
14 Temple englouti (outil 45-54 - lv requis 35)
15 Profondeurs de Rochenoire (outil 48-60 - lv requis 40)
16 Hache-Tripes (outil 56-65 - lv requis 45)
17 Scholomance (outil 56-65 - lv requis 45)
18 Stratholme (outil 56-65 - lv requis 45)
19 Pic Rochenoire (outil 53-62 - lv requis 45)

voici une [source](https://wow.fandom.com/fr/wiki/Instances_par_continent) qui fait foi ; mais attention les niveaux indiqués sont liés aux extensions, le Donjon d'Ombrecroc listé dans ce lien est pour la version cataclysme.

**Comment by Ferro-woe** [comment]
à clôturer en invalid

**Comment by JuDBav** [comment]
Salut


Merci pour ta réponse.

Du coup pas moyen d'aller en donjon par l'outil alors que les quetes du 
donjon sont en jaune.

Domage, on pourrai penser qu'il y a une incohérence du coup.


Le 05/03/2023 à 18:33, Ferro a écrit :

**Comment by Ferro-woe** [comment]
en effet :
[[25d] [Des nécrotraqueurs à Ombrecroc]](https://woehead.way-of-elendil.fr/?quest=1098) au Sépulcre se valide dans le donjon
[[26d] [Le Livre d'Ur]](https://woehead.way-of-elendil.fr/?quest=1013) à Fossoyeuse
[[27d] [Arugal doit mourir]](https://woehead.way-of-elendil.fr/?quest=1014) au Sépulcre

malgré tout ces quêtes sont disponibles bien avant le niveau indiqué 16, 18 et 18, pour le donjon 17-25 c'est cohérent.

**Comment by Ferro-woe** [comment]
à clôturer en invalid
