### ISSUE TITLE
Doublure en toile flexible (Ingéniérie) ne donne pas + 23 hâte 

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#149]
**Description**
Il n'y a pas de bonus permanent + 23 hâte, sur l'amélioration "Doublure en toile flexible".

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Druide/ féral/ tauren
- Cape
- Ingéniérie : "doublure en toile flexible"

**Comportement attendu**
L'amélioration donne +23 hâte de manière permanente

**Comment by joshwhedon** [comment]
C'est pas la hate qui est augmente c'est l'agilite. J'ai verifie ca fonctionne correctement et ajoute de l'agilite.
Permanently attaches a flexweave underlay to a cloak, increasing Agility by 23
