### ISSUE TITLE
[Quête] L'orbe d'Avruu (Péninsule des Flammes infernales) - Mob Aeranas insensible

### ISSUE THREAD

**Issue by Erasilia** [way-of-elendil/3.3.5#1492]
**Description**
Lorsqu'on utilise l'**Orbe d'Avruu** sur l'**Autel haal'eshi**, le monstre "**Aeranas**" apparait bien correctement, mais il est **insensible**.
La quête est de fait impossible à terminer.

**De plus, le monstre ne semble pas avoir la bonne apparence.**

**Étapes de reproduction**
Démarrer la quête **L'orbe d'Avruu** avec l'objet "**Orbe d'Avruu**"
Se rendre à l'**Autel haal'eshi** et utiliser l'**Obre d'Avruu** dessus
**Aeranas** apparait, est amical pendant quelques secondes, puis passe en hostile mais est **insensible**

Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Péninsule des Flammes infernales - **Avruu** => **25.5-76.1** - **Autel haal'eshi** => **29.0-81.4**
- Faction : Les deux
- Nom de la quête : L'orbe d'Avruu
- Nom du donneur de quête : Donné par l'objet "**Orbre d'Avruu**", droppé sur le mob "**Avruu**"

**Comportement attendu**
Utiliser l'**Orbe d'Avruu** sur l'**Autel haal'esh**
Placer l'orbe sur "**Aeranas**" grâce à la bulle de dialogue => Le combat démarre
Combattre le "**Aeranas**" jusqu'à **35-40%** de ses PV => Le monstre devient amical à nouveau
Terminer la quête

**Captures d’écran / Vidéos**
![image](https://user-images.githubusercontent.com/9977660/233832791-9185ddd9-c5ab-469c-9e7f-8bd2f705d210.png)

![image](https://user-images.githubusercontent.com/9977660/233832843-f9fb6846-043f-4afe-b221-ece0026c950b.png)

**Ressources additionnelles**
https://www.youtube.com/watch?v=pGJ_bxkkc8c
https://www.wowhead.com/wotlk/fr/quest=9418/lorbe-davruu#screenshots

**Comment by Ferro-woe** [comment]
La quête [[63][L'orbe d'Avruu]](https://woehead.way-of-elendil.fr/?quest=9418) via l'item [[Orbe d'Avruu]](https://woehead.way-of-elendil.fr/?item=23580)

Testée ce jour sur sur PTR : fonctionne parfaitement et comme attendue.

**comportement actuel :**
- Utiliser l'Orbe d'Avruu sur l'Autel haal'esh
- ~~Placer l'orbe sur "Aeranas" grâce à la bulle de dialogue => Le combat démarre~~ Le combat démarre automatiquement après 2 à 3 secondes
- Combattre le "Aeranas" jusqu'à 35-40% de ses PV => Le monstre devient amical à nouveau
- Terminer la quête 

à clôturer en statut invalid.
