### ISSUE TITLE
[mob] pnj AGGRO INFINIE

### ISSUE THREAD

**Issue by loganxd57** [way-of-elendil/3.3.5#1493]
**Description**

Les gardes de la ville d'Halaa en Nagrand n'ont pas de limite d'aggro. Une fois qu'ils vous ont vu, ils ne vous lachent plus, en plus d'avoir énormément de vie. 

**Étapes de reproduction**

Pnj : Garde halaani de l'alliance / Horde . ID : 18256 / 18192
Condition : être aggro par un garde, il ne vous lâche plus.

**Comportement attendu**
En temps normal, le mob arrête de vous suivre à partir d'une distance définie.

**Captures d’écran / Vidéos**
![image_2023-04-23_193038211](https://user-images.githubusercontent.com/131611339/233855251-4c8ebc3d-52e2-42e0-8304-b7d76aaf8054.png)
![image_2023-04-23_193104776](https://user-images.githubusercontent.com/131611339/233855271-9677f5e4-9264-4b5c-98c2-6d28d0efdcfd.png)

**Ressources additionnelles**
https://www.wowhead.com/tbc/fr/npc=18192/garde-halaani-de-la-horde
https://www.wowhead.com/tbc/fr/npc=18256/garde-halaani-de-lalliance

**Comment by MJ-Vyr** [comment]
Bonjour, après vérification les gardes de Halaa semblent se reset correctement.
