### ISSUE TITLE
ZG - Hakkar - le CM n'est pas correct

### ISSUE THREAD

**Issue by Evaexe117** [way-of-elendil/3.3.5#1495]
Description
A ZG sur le boss de fin de Hakkar, le boss utilise un sort de CM qui CM plusieurs joueurs.
Si le joueur est seul Hakkar le CM quand meme

Étapes de reproduction
Démarer un combat contre le boss de fin de ZG : Hakkar

Comportement attendu

"Rendre fou : Un contrôle mental impossible à dissiper qui frappera la personne la plus haute sur la liste d'aggro. Cela augmente la vitesse de déplacement de 150% et la vitesse d'attaque de 100%, mais a surtout pour effet de retourner le joueur contre ses coéquipiers. Pendant le contrôle, le joueur perd évidemment l'aggro, mais il le reprendra à l'expiration du debuff. Vous devez donc avoir des Off Tanks pour reprendre Hakkar pendant que le Main Tank est contrôlé."

https://www.youtube.com/watch?v=UeAcmpCUJyk

**Comment by Ferro-woe** [comment]
Le boss [Hakkar](https://woehead.way-of-elendil.fr/?npc=14834)

Il manque la source du commentaire.
La vidéo montre un Paltank soloter [Hakkar](https://woehead.way-of-elendil.fr/?npc=14834) du coup, elle est peu pertinente : Il est impossible de vérifier les deux points mentionnés (un seul Contrôle Mental et uniquement le joueur le plus haut à l'aggro).

Par contre ces remarques, sont juste. Source [capacités et tactiques](https://wowpedia.fandom.com/wiki/Hakkar_(tactics)) ; passage sur le Contrôle Mental (CM) :
> Spell shadow shadowworddominate.png [Cause Insanity](https://www.wowhead.com/?spell=24327) Important — Drives an enemy target temporarily insane, speeding its attacks by 100% and its movement by 150%, as well as causing it to attack its own allies for 10 sec. A 10 seconds non-dispellable mind control with an 80% movement and 50% attack speed increase, this is cast approximately every 10 to 15 seconds on the person currently highest on the aggro list. While mind controlled, the person temporarily loses aggro - however, he will re-gain aggro once mind control expires.
(...)
> Spell shadow shadowworddominate.png [Will of Hakkar](https://www.wowhead.com/?spell=24178) Important — Takes control of a humanoid enemy up to level 65 for 20 sec.

Donc un seul Contrôle Mental à la fois et toujours le joueur ayant le plus d'aggro.
+

**Comment by MJ-Vyr** [comment]
Bonjour, après vérification il est normal de se faire contrôle mental lorsque vous êtes seul contre le boss. 
De plus, la source que vous donnez est une vidéo d'un joueur faisant le boss sous Shadowlands.

Je ferme.
