### ISSUE TITLE
[Quête Motivés, motivés, il faut les motiver…] PNJ Capitaine Chape Etincetuyère absent

### ISSUE THREAD

**Issue by Sebpredator** [way-of-elendil/3.3.5#1498]
Dans la quête "Motivés, motivés, il faut les motiver…", une fois les 5 citoyens/citoyennes gnomes motivés, il est impossible de trouver le PNJ Capitaine Chape Etincetuyère au dépôt de Grillacier.
Ce bug a également été constaté par d'autres joueurs.
Merci d'avance pour vos actions !

**Comment by Kaasss-woe** [comment]
Cette quête ne devrait plus être proposée.
Elle fait partie de l'event pré-cata, que nous avons retiré.
Il s'agit donc de faire en sorte qu'elle ne soit plus disponible en jeu.

**Comment by Kaasss-woe** [comment]
La quête a été désactivée.
