### ISSUE TITLE
Diablotin du démoniste

### ISSUE THREAD

**Issue by Ishtanu** [way-of-elendil/3.3.5#1499]
**Description**
Je joue démoniste avec une elfe de sang niveau 8 jusqu'à maintenant, et le diablotin a un pathfinding totalement erratique, notamment en attaque. Je l'ai mis en défensif, et il attaque les mobs dès que je fais un clic droit sur eux. Jusque là pas de problèmes, c'est plutôt pratique, même si ce n'est pas le comportement normal du familier.
Le problème c'est que quand il est trop éloigné, il va décider de prendre des trajectoires parfois étranges pour atteindre l'ennemi, notamment une fois au quai des saccage-soleil, il est parti dans l'eau, puis en est ressorti et a décidé de pull quatre ou cinq mobs différents avant d'attaquer un autre mob que celui que j'avais sélectionné. Et une vingtaine de minutes plus tard, quand j'ai sélectionné un lynx, il est à nouveau parti loin en arrière plutôt que vers le lynx.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Démoniste
- Elfe de Sang
- Diablotin
- Circonstances (levelling bas niveau)

**Comment by MJ-Vyr** [comment]
"Je l'ai mis en défensif, et il attaque les mobs dès que je fais un clic droit sur eux. Jusque là pas de problèmes, c'est plutôt pratique, même si ce n'est pas le comportement normal du familier." 
Ceci est le comportement normal du famillier, je ne sais pas sur quoi vous vous basez pour affirmer que ce n'est pas le cas.

Pour les soucis de pathfinding des familliers, ils sont connus, et malheureusement étant liés au core utilisé par le serveur, peu de chances que cela change.
