### ISSUE TITLE
[Démoniste / Diablotin] aucune attaque de mêlée du familier 

### ISSUE THREAD

**Issue by Wolkrym** [way-of-elendil/3.3.5#1500]
Bonjour, je suis un mort-vivant démoniste de niveau 5 et mon diablotin n'effectue aucune attaque de mêlée. 
Il ne réagi pas qu'il soit en mode agressif ou défensif. Je peux lui faire faire seulement son éclair de feu.
Si vous pouvez régler ce problème se serait super.
En vous remerciant par avance.
--------------------------
Sombrâme
Mort-vivant
Démoniste
Niveau 5
Zone de départ (Le Glas, Brill)

**Comment by Amilgaul-woe** [comment]
Bonsoir, cela est le comportement normal, le diablotin ne réalise qu'une seule attaque qui est l'éclair de feu, il n'attaque pas en mêlée. Il ne s'agit donc pas d'un bug. Voici un lien dans lequel cela est évoqué : https://www.wowhead.com/fr/spell=688/invocation-de-diablotin#english-comments
