### ISSUE TITLE
[QUETE - Le preneur d'images FX] Objectif ne se valide pas

### ISSUE THREAD

**Issue by Byobx** [way-of-elendil/3.3.5#1503]
Bonjour,

L'objectif de cette quête est de prendre en photo le monstre "Gammerita" à l'aide de l'objet "Le preneur d'images FX".

Lors de l'utilisation de l'objet sur le monstre la quête ne se valide pas.

J'ai essayé en combat, hors combat, en tuant le monstre. j'ai également attendu le repop mais le problème persiste.

Merci

**Comment by Ferro-woe** [comment]
à vérifier : [[48] [Le Preneur d'images FX]](https://woehead.way-of-elendil.fr/?quest=2944) #2944
pnj : [Gammerita](https://woehead.way-of-elendil.fr/?npc=7977) #7977

**Comment by Ferro-woe** [comment]
Quête testée ce jour sur PTR.
Parfaitement fonctionnelle : sélectionner [Gammerita](https://woehead.way-of-elendil.fr/?npc=7977) vivant ou mort, puis activer [[Le Preneur d'images FX]](https://woehead.way-of-elendil.fr/?item=9328)
à **clôturer** en **status invalid**
