### ISSUE TITLE
Glyphe Mot de l'ombre : douleur

### ISSUE THREAD

**Issue by Faka0340** [way-of-elendil/3.3.5#1504]
La Glyphe Mot de l'ombre : douleur rend normalement 1% de la mana du prêtre.
Un prêtre lvl 80 possède 6583 PM et 1% est 65.83 PM.
Actuellement, la glyphe rend 38 PM

Pour tester cela, il m'a suffi de mettre mon personnage sans équipement, et d'utiliser le sort ( Mot de l'ombre : Douleur ) sur mannequin en regardant ce que mon addon m'envois comme information sur le regen PM fourni par cette glyphe ( J'utilise Details )
Mon personnage est :
Prêtre
Humain
( Je n'avais aucun buff actif )

**Comment by MJ-Vyr** [comment]
Bonjour, la mana de base d'un prêtre niveau 80 est de 3863. 38 points de mana est donc le montant correct devant être rendu. 
Les montants considérés comme "de base" est le mana sans les talents, sans l'intelligence, sans les enchants et les objets équipés.
Ces valeurs sont consultable ici : https://wowwiki-archive.fandom.com/wiki/Base_mana
