### ISSUE TITLE
[Nourriture pet chasseur] Trop souvent affamé

### ISSUE THREAD

**Issue by Fortenpommess** [way-of-elendil/3.3.5#1508]
Bonjour , 

Nous avons constaté joueurs hunt que depuis quelques temps nous devons constamment nourrir notre pet bien plus qu'avant et surtout bien plus qu'à la normale . 

Je me suis renseigné auprès d'autres joueurs hunt qui ont constaté la même chose. Comme il n'y a rien dans les log il semble que ce soit un bug. J'ai l'impression que le pet se comporte comme si il venait d'être dressé quand on doit beaucoup le nourrir au début malgré la relation meilleur ami. 
Ça pose soucis en raid notamment , le dernier que j'ai fait j'ai utilisé pas loin d'un stack de viande juste pour le raid pour le pet c'est beaucoup et surtout faut constamment avoir l'oeil sur sa satisfaction car elle descend rapidement. 

Merci

**Comment by Gandrayda** [comment]
Bonjour ,

Alors j'ai réalisé 2 tests pour voir si effectivement il y avait un problème de perte de satisfaction chez nos amis loups ( car j'ai lu que ça posait des soucis en raid ) 

Avant toute chose je rappelle quelques règles sur le fonctionnement de la satisfaction:
- 3 paliers de 350 de satisfaction : rouge 0 - 350 , jaune 351 - 700 et vert 751 - 1050.
- Le familier perd continuellement 1 de satisfaction toutes les 7,3 secondes, ce qui prend donc un peu plus de 42 minutes 30 pour perdre un palier.
- Renvoyer un familier lui fait perdre 50 points.
- La mort du familier lui fait perdre instantanément 350 points ( et donc 1 palier ). 

Donc j'ai fait 2 tests : sur le premier j'ai simplement rien fait et j'ai attendu à dalaran pendant 42 minutes et demi et effectivement le familier perd bien un palier au bout de ce laps de temps.

Pour le 2e je me suis dit que peut être le familier perdait de la satisfaction en attaquant ( et sans le talent Assoiffé de sang ), j'ai donc laissé mon loup taper un mannequin pendant 42min 30 et là encore il perd un palier au bout de ce délai.

Donc pas de soucis au niveau de la perte native de satisfaction.

Après il est possible ( pour l'observer souvent en pvp et au joug ) que même si il meurt le niveau de satisfaction ne change pas " visuellement " ( l’icône ne change pas ) mais la perte est bien effective. Du coup en cas de nouvelle mort ou si il a perdu nativement suffisamment de points , il passe directement en palier rouge ( car même si le palier s'affiche en vert le familier est en palier jaune ).

En cas de mort donc , nourrissez votre familier 2 fois ( une fois pour le remettre dans le vert et une autre fois pour le remettre au max ) et ainsi vous n'aurez qu'à le nourrir que toutes les 30 / 35 minutes pour éviter une perte de palier en combat.
Bien sûr je dit ça si vous n'utilisez pas la glyphe de guérison du familier qui augmente la satisfaction avec les ticks de soins, et qui permet de se passer de nourriture pour les raids.

Pour finir j'ai relevé aucun soucis hormis le bug d'affichage mais la mécanique fonctionne comme attendu.

**Comment by Fortenpommess** [comment]
D'accord alors je ne sais pas peut-être un bug visuel effectivement, comme nous étions plusieurs à se dire la même chose j'ai même cru qu'il y avait eu un patch mais c'est peut être le déroulé du raid qui a induit en erreur. 
Merci pour le test serieux mes excuses pour ce temps du coup
