### ISSUE TITLE
[Potion] Impossibilités de consommer des potions

### ISSUE THREAD

**Issue by boujeum** [way-of-elendil/3.3.5#1509]
**Description**

Je reroll un voleur. Régulièrement je veux prendre une potion de soins lorsque je suis en combat et un message m'indique : "vous ne pouvez rien boire de plus pour l'instant" alors que le cd est passé depuis longtemps. Idem pour les elixirs. A certains moment ça fonctionne mais c'est incompréhensible.

**Comportement attendu**

Je devrais pouvoir consommer mes potions normalement.

**Comment by Melendder** [comment]
Tu es limité à 1 potion par combat, même si le cd est fini.
Sois sûr de quitter le combat entre 2 mobs si tu veux pouvoir use une nouvelle potion

**Comment by boujeum** [comment]
C'est bien justement le problème : je ne peux même pas consommer une seule potion par combat. Quelquefois ça fonctionne, et la plupart du temps pas du tout.
Idem pour les elixirs, que je ne peux parfois pas prendre pour les mêmes raisons.
Du coup je crève régulièrement. Je vais finir par abandonner ce perso...

**Comment by Endalaust** [comment]
Je ne reproduis pas. Je peux consommer une potion lorsque je rentre en combat. Le reset du CD se fait dés que je passe hors combat.
