### ISSUE TITLE
Bug Feu intérieur + Mot de pouvoir : Bouclier

### ISSUE THREAD

**Issue by CGBone** [way-of-elendil/3.3.5#151]
**Description**
Feu Intérieur perd des stacks alors que Mot de pouvoir : Bouclier est actif et absorbe les dégats.

**Étapes de reproduction**

- Prêtre
- Troll
- Discipline & Sacré
- Feu Intérieur & Mot de Pouvoir : Bouclier
- PvE & PVP
- 4T10 NM
- Feu Intérieur & Mot de Pouvoir : Bouclier

**Comportement attendu**
Les dégats absorbés ne devraient pas enlever de stack sur Feu Intérieur

**Captures d’écran / Vidéos**
Pas de quoi capturer en vidéo, impossible à capturer en screenshot, mais le bug est facilement reproductible en duel ou sur un pack de monstre

**Ressources additionnelles**
idem qu'au dessus

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21398

**Comment by joshwhedon** [comment]
C'est nouveau comme bug ou c'est existant ?

**Comment by Killyana** [comment]
Nouveau sur woe ancien sur TC

**Comment by joshwhedon** [comment]
Pas le bon ticket chez TC, c'est Inner fire pas Inner focus

**Comment by Killyana** [comment]
oui sa a été fermé mais pas corrigé https://github.com/TrinityCore/TrinityCore/issues/22074

**Comment by CGBone** [comment]
Je plussoie Killyana, https://github.com/TrinityCore/TrinityCore/issues/22074 correspond à ce bug, mais pas l'issue qui a été utilisée pour fermer le post. Le bug existe toujours.

**Comment by joshwhedon** [comment]
Hey @CGBone . J'ai mis en place des correctifs sur les procs en general sur absorb. Tu peux me dire si le probleme est regle pour celui la ?

**Comment by joshwhedon** [comment]
Ouai en fait j'ai teste c'est regle.
