### ISSUE TITLE
[Libram de résilience] impossible de looter une Essence ardente et de valider la quête

### ISSUE THREAD

**Issue by JuDBav** [way-of-elendil/3.3.5#1514]
Bonjour

Je ne parviens pas à rendre la quête du [Libram de résilience](https://woehead.way-of-elendil.fr/?quest=4483)
Le PNJ [Mathredis Brasétoile](https://woehead.way-of-elendil.fr/?npc=9836) propose une quête avec un "?" bleu.
C'est une quête où on doit rendre des composants pour obtenir un enchantement [Arcanum inférieur de résilience](https://woehead.way-of-elendil.fr/?item=11644) de résistance au feu.

L'un des composant est l'[Essence ardente](https://woehead.way-of-elendil.fr/?item=11751) qui se loot dans le [Coffre sombre](https://woehead.way-of-elendil.fr/?object=160845) à BRD.

J'ai fait plusieurs dizaines de run et le coffre ne donne jamais aucune des compos de libram
- [Essence ardente](https://woehead.way-of-elendil.fr/?item=11751)
- [Oeil de Kajal](https://woehead.way-of-elendil.fr/?item=11753)
- [Sang noir du Tourmenté](https://woehead.way-of-elendil.fr/?item=11752)

J'ai ouvert le coffre avec le personnage qui a dans ses sac le libram
J'ai parlé au pnj [Mathredis Brasétoile](https://woehead.way-of-elendil.fr/?npc=9836), qui propose qu'on lui rende les compos, mais il ne donne pas de quête avec laquelle aller à BRD pour obtenir un objet de quête.
Quand on lui parle on peut lui présenter le libram, mais là encore il nous dit qu'on a pas toutes les compos.

Je suis donc dans l'incapacité d'obtenir l'Essence ardente et donc l'[Arcanum inférieur de résilience](https://woehead.way-of-elendil.fr/?item=11644)

Il est important car je suis le MT1 d'une guilde lvl60 et nous faisons régulièrement MC. J'ai donc un stuff entièrement basé sur la résistance au feu et j'ai besoin d'augmenter cette résistance.

Je penses que le problème est le même sur tous les librams.

Comment faire ?

Merci

**Comment by Ferro-woe** [comment]
En effet, les drops de ces 3 objets sont conditionnés par la présence de quête dans le journal des quêtes du joueur.

Il faut soit remettre les quêtes répétables sur le PnJ, soit retirer le filtre sur les objets.
La source [woehead](https://www.wowhead.com/wotlk/fr/npc=9836/mathredis-bras%C3%A9toile#starts) dit de remettre les quêtes répétables sur le PnJ pour être conforme à l'original.

**Comment by JuDBav** [comment]
On ne peut pas avoir les quêtes dans le journal. donc on fait comment pour aller a BRD avec la quête dans le journal ?

De quel filtre parlez-vous ?

**Comment by JuDBav** [comment]
Est-ce un com pour les dev ?

**Comment by Ferro-woe** [comment]
Oui le précédent commentaire est pour les dévs.

Si vous voulez effectuer les quêtes des librams pour augmenter votre réputation [Shen'dralar](https://woehead.way-of-elendil.fr/?faction=809), vous devez vous rendre dans la bibliothèque de Hache-Tripe :
[Gardien du savoir Lydros](https://woehead.way-of-elendil.fr/?npc=14368) qui lance [[60][Libram de rapidité]](https://woehead.way-of-elendil.fr/?quest=7483), [[60][Libram de focalisation]](https://woehead.way-of-elendil.fr/?quest=7484) et [[60][Libram de protection]](https://woehead.way-of-elendil.fr/?quest=7485)
Celles-là devraient fonctionner.
