### ISSUE TITLE
Totem courroux de l'air 

### ISSUE THREAD

**Issue by SorgrosProd** [way-of-elendil/3.3.5#1518]
**Description**
Bonjour,
Après avoir essayé plusieurs fois, le totem de courroux de l'air du chaman n'apporte pas le buff de 5% de hâte de sort au joueur.
Aucune statistique ne change après avoir posé le totem.

**Étapes de reproduction**
- Chaman
- Draenei
- Elementaire / Réstauration
- Totem du courroux de l'air
- Toutes circonstances 

**Comportement attendu**
- Il est sensé apporter 5% d'hâte de sorts alors qu'une statistique ne bouge lorsqu'il est posé.

**Captures d’écran / Vidéos**
![WoWScrnShot_112623_044228](https://github.com/way-of-elendil/3.3.5/assets/152046550/f34f9358-2a48-4109-a33b-d39ad9818db6)
Ici on peut voir que je n'ai aucun Totem et 1031 de hâte soit 31.44%
![WoWScrnShot_112623_044238](https://github.com/way-of-elendil/3.3.5/assets/152046550/ef7d7210-4a2b-4a4e-a1ae-f45c14e2cbd4)
Ici on peut voir que j'ai posé le Totem et 1031 de hâte soit 31.44% donc aucun changement
![WoWScrnShot_112623_044247](https://github.com/way-of-elendil/3.3.5/assets/152046550/b035f537-5e4e-4d40-b1a1-30bb975047f2)
Ici c'est juste pour montrer le buff de 5% actif.

**Ressources additionnelles**
-https://www.wowhead.com/wotlk/fr/spell=3738/totem-de-courroux-de-lair

Pas mal de sites en parlent dans des guides etc...
Je vous invite à aller visiter cet exemple de guide qui explique que le totem est bien sensé vous apporter 5% de hâte.
https://ombreux.forumactif.com/t764-le-chaman-heal

**Comment by Satarians** [comment]
Jje pense que ca manque d'info, tu peux regarder dans ton grimmoir le temps d'incantation des sort qui devrait lui changer (ex: 1.5 à 1.3 ect )
Tout simplement tester de cast un spell avec/sans
Certainnes statts de la fiche perso change apres 30 sec

**Comment by SorgrosProd** [comment]
Merci pour vos commentaires, je n'avais pas pensé à aller voir dans le grimoire. Effectivement, je passe de 1.9s à 1.81s avec le totem.
