### ISSUE TITLE
[Libram de jugement divin] Ne proc pas

### ISSUE THREAD

**Issue by JuDBav** [way-of-elendil/3.3.5#1520]
Bonjour

Le Libram de jugement divin (https://woehead.way-of-elendil.fr/?item=33503) indique :
Équipé : [Votre Jugement d'autorité a une chance de conférer un bonus de 200 à la puissance d'attaque pendant 10 sec..](https://woehead.way-of-elendil.fr/?spell=43745)
Après pas mal de test sur poteau ou sur mobs, le libram ne semble pas proc.

C'est fort dommage :)
Merci

**Comment by XVoscar** [comment]
https://www.youtube.com/watch?v=fCkvcedqPuU

On voit bien que son proc idée claire est bien consumé a chaque sort, alors que cela n'est pas toujours la cas sur le serveur.

**Comment by JuDBav** [comment]
Salut
Quelqu'un lit nos report bug ou ca sert a rien d'en faire ?
Bonnes fêtes

**Comment by MJ-Vyr** [comment]
Salut, c'est lu mais comme tu peux le voir il existe plusieurs centaines de tickets ouverts, en conséquence les chances d'avoir une réponse rapide sont faibles, surtout pour une histoire de libram niveau 70.

**Comment by MJ-Vyr** [comment]
Bonjour, le sort "jugement d'autorité" n'existe plus sous Wotlk. En conséquence il est relativement logique que cet objet ne soit plus fonctionnel.
Le libram de la puissance vertueuse fonctionne correctement après tests, il augmente correctement d'environ 25 les dégâts d'inquisition.

Je ferme le ticket.
