### ISSUE TITLE
[Quête] Questionner Reethe

### ISSUE THREAD

**Issue by silverlays** [way-of-elendil/3.3.5#1521]
**Description**
La quête ne se valide pas alors que tous est terminé et que les dialogues sont passés. L'ogre se dirige vers son emplacement d'origine mais s'arrête dans un trou. (voir screenshot ci-dessous)

**Étapes de reproduction**
- Parler à l'ogre pour lancer la quête
- L'escorter jusqu'à Reethe
- Attendre la fin du dialogue
- Battre les gardes (un garde ne semble pas passer en agressif, si ca peut aider)
- Attendre la fin du dialogue
- Escorter l'ogre

**Comportement attendu**
La quête est censée se valider après la fin du dialogue entre l'ogre et Reethe

**Captures d’écran / Vidéos**
![WoWScrnShot_121523_144426](https://github.com/way-of-elendil/3.3.5/assets/17464661/ae4456da-9c56-4b0c-aba3-6d9a0a34279d)

**Ressources additionnelles**
[Lien Woehead](https://woehead.way-of-elendil.fr/?quest=1273)

**Comment by MJ-Vyr** [comment]
Impossible a reproduire de mon coté, la quête se valide correctement une fois les soldats de theramore tués.

**Comment by silverlays** [comment]
J'ai en effet refais la quête et cette fois, tout s'est passé comme convenu. Je peux donc fermer cette issue. Merci
