### ISSUE TITLE
[WoW Client HD] Crash du jeu si on récolte une plante en forme aquatique

### ISSUE THREAD

**Issue by silverlays** [way-of-elendil/3.3.5#1522]
**Description**
C'est un bug très spécifique: (Uniquement sur le client HD) Lorsque je veux cueillir une plante dans l'eau en forme aquatique, la plante glitch 1/2sec et ensuite WoW Error. J'ai demandé sur le /world et visiblement, je ne suis pas le seul dans ce cas.

Ci-joint, une série de CrashLogs au format ZIP, si cela peut vous aider à trouver la source du problème.
[Errors.zip](https://github.com/way-of-elendil/3.3.5/files/14024333/Errors.zip)

**Comment by Ferro-woe** [comment]
Aux dernières nouvelles, le pack HD ne peut pas être debug. Voir la réponse [#624](https://github.com/way-of-elendil/3.3.5/issues/624).
Je te conseils de passer avec le pack normal, là le ramassage en forme aquatique fonctionne très bien.
Biz

**Comment by Kaasss-woe** [comment]
Tout a été dit.
On ne réalise pas de débugs sur le pack HD, désolé.

**Comment by silverlays** [comment]
Bien, merci quand même pour ces réponses, je suis repassé sur le client original du coup.
