### ISSUE TITLE
Paladin prot: le talent rétribution ne proc pas sur les blocages au bouclier

### ISSUE THREAD

**Issue by Mortglase** [way-of-elendil/3.3.5#1523]
Paladin prot: le talent rétribution ne proc pas sur les blocages au bouclier.

Rétribution 5/5
Confère 10% de chances lorsque vous êtes victime d'un attaque qui vous inflige des dégâts **ou que vous l'avez bloquée** de bénéficier d'une attaque supplémentaire avec les 4 frappes suivantes dans les 8 sec.

Voici une vidéo:
[https://youtu.be/VpnkpjhpeCA]

Commentaire:
Aucun proc du talent rétribution sur blocages au bouclier. Elle fonctionne bien quand je prend des coups.
Aussi après 1 min 13, les blocages s'arrêtent.

**Comment by TrucEtrange** [comment]
Tu continues de faire des blocages après 1:13, comme visible à 1:32.

En revanche les rater/esquive/parade sont prioritaires sur le blocage dans la table d'attaque, donc c'est normal de ne pas voir de blocages si tu réussis à parer, esquiver ou si tu es raté. Ce qui serait anormal, c'est de ne voir aucun blocage alors que tu prends des coups.

Le talent ne proc pas si le coup est entièrement bloqué, source :   ["As long as you take damage from any source, partial  block/resist, then you run the chance of Reckoning activating"](https://www.wowhead.com/wotlk/fr/spell=20182/r%C3%A9tribution#english-comments)

Ton test ne permet pas de vérifier si le talent fonctionne correctement, puisque tu bloques l'intégralité des dégâts.

En l'absence de sources indiquant que le talent doit proc sur les coups entièrement bloqués, le talent semble fonctionner correctement

**Comment by Mortglase** [comment]
![Opera Instantané_2024-02-24_233745_www wowhead com](https://github.com/way-of-elendil/3.3.5/assets/159694530/eed5f6eb-91ee-4f14-9628-cc9003baea3d)

Il y a écrit:
"ou que un coup est bloquer" 

ça n'exclu pas les blocages complet.

**Comment by TrucEtrange** [comment]
"It does not proc from full blocks or dodges", toujours la même source.

Les tooltips de blizzard sont généralement imprécis et ne suffisent pas à décrire un comportement attendu. Au vu des commentaires wowhead de l'époque, Rétribution ne proc que quand des dégâts sont subis, pas quand le blocage arrête l'entièreté des dégâts

**Comment by Mortglase** [comment]
![image_2024-02-27_115845686](https://github.com/way-of-elendil/3.3.5/assets/159694530/ca718364-2a8c-4113-a51a-4d9e5001702f)

voila un capture pris dans le jeux.

Rank 4:
Confère 8% de chances lorsque vous êtes victime d'une attaque de bénéficier d'une attaque supplaimentaire avec les 4 frappes suivantes dans les 8 sec.

Le tooltip est claire, les dégâts reçus procs Rétribution. Cela inclut les dégâts physiques, magiques et **mêmes les blocages partielle.**
Ce n'est pas la partie qui me pause problème.

Rank 5:
Confère 10% de chances lorsque vous êtes victime d'une attaque qui vous inflige des dégâts **ou vous l'avez bloquée de bénéficier** d'une attaque supplémentaire avec les 4 frappes suivantes dans les 8 sec.

Ici nous un effets supplémentaire qui s'ajoute (et ce n'est pas le blocage partielle déjà présent dans le rang 4).
"ou vous l'avez bloquée de bénéficier": il faut comprendre que en plus d'avoir une chance d'avoir Rétribution en prennent des dégâts nous avons en plus une chance au blocage. (complet ou pas).

Les blocages (complet ou non) doivent avoir une chance de provoquer Rétribution, c'est l'effet supplémentaire. Et on voit clairement dans la première video que ce n'est pas le cas.

Le tooltip présent dans ton lien est exactement le même que celui présent dans le jeu.
["As long as you take damage from any source, partial block/resist, then you run the chance of Reckoning activating"](https://www.wowhead.com/wotlk/fr/spell=20182/r%C3%A9tribution#english-comments)
Dans ce cas là on revient sur la première partie du talent qui consiste à prendre des dégâts. Deuxièmement c'est la réponse d'un random qui ne prend pas en compte la l'ajout du blocage au rank 5.

**Comment by MJ-Vyr** [comment]
Bonjour, malheureusement les preuves apportées sont insuffisantes pour attester d'un fonctionnement anormal.
Se baser uniquement sur la compréhension d'un tooltip et des commentaires wowhead ne suffit pas comme preuve pour justifier une modification du comportement actuel.

A moins que vous ayez une preuve définitive du fonctionnement correct (vidéo de l'époque où on peut voir un blocage complet provoquer un proc Retribution, ou au pire un thread EJ.), je ferme pour le moment ce ticket et le marque comme invalide.
