### ISSUE TITLE
[Quête] objet [Torche de vindicte] non détruit

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1524]
**Description**
L'objet [[Torche de vindicte]](https://woehead.way-of-elendil.fr/?item=10515) reste dans les sacs du joueur malgré la validation de la quête [[52][Allumer le feu !]](https://woehead.way-of-elendil.fr/?quest=3463)

**Étapes de reproduction**
Effectuer la suite de neuf quêtes lancée par [Kalaran Lamevent](https://woehead.way-of-elendil.fr/?npc=8479) :
[[48][Châtiment divin]](https://woehead.way-of-elendil.fr/?quest=3441)
[[48][La flamme parfaite]](https://woehead.way-of-elendil.fr/?quest=3442)
[[48][Forger le manche]](https://woehead.way-of-elendil.fr/?quest=3443)
[[48][L'enveloppe de la flamme]](https://woehead.way-of-elendil.fr/?quest=3452)
[[50][La Torche de vindicte]](https://woehead.way-of-elendil.fr/?quest=3453)
[[50][La Torche de vindicte]](https://woehead.way-of-elendil.fr/?quest=3454)
[[50][L'écuyer Maltrake]](https://woehead.way-of-elendil.fr/?quest=3462)
[[50][Allumer le feu !]](https://woehead.way-of-elendil.fr/?quest=3463)
[[50][Bibelots...]](https://woehead.way-of-elendil.fr/?quest=3481)

La [[Torche de vindicte]](https://woehead.way-of-elendil.fr/?item=10515) se prend à [[50][La Torche de vindicte]](https://woehead.way-of-elendil.fr/?quest=3454) et permet d'effectuer [[50][Allumer le feu !]](https://woehead.way-of-elendil.fr/?quest=3463).

**Comportement attendu**
Cet objet devrait être détruit lors de la validation de [[52][Allumer le feu !]](https://woehead.way-of-elendil.fr/?quest=3463).

Biz.

**Comment by Kaasss-woe** [comment]
D'après les commentaires wowhead, la torche n'est pas censée être détruite à la fin de la quête, même si elle est en effet complètement inutile.
cf [Allumer le feu !](https://www.wowhead.com/fr/quest=3463/allumer-le-feu#english-comments)
> "I think it's safe to destroy the torch after you completed the quest."
ou encore
[Torche de vindicte](https://www.wowhead.com/fr/item=10515/torche-de-vindicte#english-comments)
(trop de commentaires pour tous les citer, notamment des joueurs qui l'ont gardée pour du RP, up une compétence d'arme, ou encore qui l'ont perdu et aimeraient pouvoir refaire la quête)
