### ISSUE TITLE
Quête : mise en place

### ISSUE THREAD

**Issue by Raelhyn** [way-of-elendil/3.3.5#1525]
Lors de la quête Mise en place (quest=12672), les monstres de l'autel de Quetz'Lun où doit se dérouler la quête ne sont pas tuables et reste à 1 point de vie. On peut leur envoyer des dégâts mais leur compteur de points de vie reste bloqué à 1 PV. La quête consiste à récolter des cristaux mais le temps de récolte est systématiquement interrompu par l'attaque des monstres qui ne sont donc pas éliminables.

Essais de les tuer avec mes addons habituels et en les désactivant.

Quête réalisée par un chevalier de la mort elfe de sang de niveau 75

![WoWScrnShot_022824_153027](https://github.com/way-of-elendil/3.3.5/assets/161612162/eeff4369-2a36-406e-a086-e3d4ed1cca9d)

**Comment by Zone04** [comment]
C'est normal. La quête suivante de la série demande d'en tuer un certains nombre et donne un détail sur comment les tuer, sans qu'ils restent à 1 PV.

**Comment by r0m1ntik** [comment]
Corrigé
