### ISSUE TITLE
War - Scale du toucher des sorts spécifiques par rapport à la compétences de l'arme main droite équipée

### ISSUE THREAD

**Issue by WoEGetschwifty** [way-of-elendil/3.3.5#1529]
**Description**
Premièrement, la compétence ciblée est "Heurt de bouclier" du war, d'autres compétences sont peut être concernées.
Je joue war tank, j'ai donc 1 main droite équipée et un bouclier.
Lorsque je suis en combat contre des mobs normaux, aucun problème. La compétence "Heurt de bouclier" fonctionne "normalement" à mon sens, c'est-à-dire qu'elle touche la cible comme le ferait mon épée équipée en main droite. Aucun problème de raté/parade/esquive etc. 
Cependant, lorsqu'un mob me désarme, "Heurt de bouclier" ne touche plus, ou très très peu de l'ordre du pourcentage que j'aurai en main nue pour toucher la cible. J'ai trouvé cela très bizarre au début, mais je me suis rendu compte que c'est systématique. Je n'ai pas pris le temps de faire des pourcentage, mais le ressenti est réel et la reproductivité est assez simple à mon sens.
"Heurt de bouclier" ne devrait pas être, en termes de toucher, scalé sur la compétence d'arme actuellement équipée (qui serait main nue dans le cas évoqué du désarmement), du moins à mon sens. Je n'ai pas pu tester cela sur WOTLK Classic et je ne jouais pas war à l'époque de WOTLK, donc je ne peux pas confirmer ma vision.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Guerrier
- Toutes races
- Toutes spé (Protection à privilégier, un talent peut être lié mais je ne vois pas lequel)
- Compétences : Heurt de bouclier (peut être d'autres)
- Dans toutes circonstances
- Aucun équipement spécifiquement
- Effet de reproduction : niveau de compétence très bas en main droite, qui s'appliquera sur "Heurt de bouclier"

**Comportement attendu**
"Heurt de bouclier" est une utilisation du bouclier, et non pas de la main droite, donc la compétence de la main droite ne doit pas avoir de liaison avec cette technique. "Heurt de bouclier" devrait avoir un toucher maximal par rapport au niveau à mon sens (un genre de niveau de compétence virtuel qui serait maxé sur le niveau du personnage) et comme le reste des armes au prorata de % de toucher pour avoir des raté/esquive/parade toujours lié à ce % de toucher. Mais le tout sans être impacté par l'arme main droite courante.

**Captures d’écran / Vidéos**
Je n'ai pas vraiment de chose à montrer à ce niveau, je reste disponible au besoin.

**Comment by WoEGetschwifty** [comment]
Je viens de vérifier et le problème est également le même avec "Dévaster".
Cette technique est encore disponible lorsqu'un guerrier est désarmé. Celle-ci est plutôt liée à l'arme courante donc ça ne me choque pas qu'elle soit basé sur le niveau de compétence de l'arme équipée.

**Comment by TrucEtrange** [comment]
Il n'y a pas de compétence de "bouclier" que tu peux monter. Il me semble donc parfaitement logique que dévaster et heurt de bouclier dépendent de la compétence d'arme en cours d'utilisation. Donc main nue si tu es désarmé.

Logiquement, au vu du fonctionnement des compétences d'armes, je ne vois pas de problème avec la situation actuelle. Si tu veux soutenir ton opinion il te faudrait une source d'époque, ou de wotlk classic à la limite, qui confirme que le bouclier ne dépend pas de la compétence d'arme. Autrement le fait que le script colle au jeu d'époque prime sur la logique générale.

**Comment by WoEGetschwifty** [comment]
En cherchant un peu dans les archives de wowhead j'ai effectivement retrouvé un témoignage allant dans le sens que ce qui est actuellement en place sur le serveur :
![Temoignage_ShieldSlam_Wowhead](https://github.com/way-of-elendil/3.3.5/assets/163915353/88d9be9c-a1f9-4080-a2af-bcb8f7ba9927)
Source : https://www.wowhead.com/spell=23922/shield-slam#comments

Je n'ai pourtant jamais eu cette sensation de miss à ce point, mais c'est surement juste de mon côté dans ce cas.
Donc si le fait que le script actuel colle au script d'époque soit considéré comme ce qui doit être en place, alors je clôture cette Issue.

Merci pour le retour :)
