### ISSUE TITLE
[Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by Hainouk-WOE** [way-of-elendil/3.3.5#1530]
**Description**
Lors je me déconnecte en monture volante et que je me reconnecte dans la même situation, ma monture volante tombe et se comporte comme un cheval lambda. Avec de la chance, je tombe dans l'eau, mais il m'est impossible de voler avec, la monture volante devient une monture non volante. Il faut sortir et revenir en volante pour avoir de nouveau la fonctionnalité.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Se déconnecter en monture volante, se reconnecter en monture volante.

**Comportement attendu**
Lorsque je me reconnecte, la monture volante devrait normalement rester en l'air

**Captures d’écran / Vidéos**
https://youtu.be/f-6ceiTEFmI?si=7U5Zg_TQcUQKGBCy

**Ressources additionnelles**
Surement en lien avec la visu du gnome, car j'ai le bug depuis sont activation

**Comment by Endalaust** [comment]
Bonjour ce bug est lié au spectateur d'arène, nous en avons eu connaissance hier soir
@r0m1ntik est en train de préparer un patch qui sera sans doute appliqué au prochain redémarrage 
Merci pour ce signalement complémentaire
