### ISSUE TITLE
WeakAuras

### ISSUE THREAD

**Issue by ssimna** [way-of-elendil/3.3.5#1531]
Salut a tous, ici petit problème sur l'addons WeakAuras.

L'addons est bien afficher dans le jeu via la petite icon, cependant je ne peut pas ouvrir celui ci.
J'ai bien sur désinstaller et réinstaller mais rien ne marche j'arrive toujours pas a ouvrir l'interface.

Voici le message Lua in-game : 

ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\GenericTrigger.lua line 221:
   attempt to concatenate a table value
..\AddOns\WeakAuras\GenericTrigger.lua line 221:
   in function <..\AddOns\WeakAuras\GenericTrigger.lua:188>
..\AddOns\WeakAuras\GenericTrigger.lua line 279:
   in function <..\AddOns\WeakAuras\GenericTrigger.lua:236>
..\AddOns\WeakAuras\GenericTrigger.lua line 1214:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 2424:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:2356>
..\AddOns\WeakAuras\WeakAuras.lua line 2502:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 1992:
   in function `load'
..\AddOns\WeakAuras\WeakAuras.lua line 1999:
   in function `AddMany'
..\AddOns\WeakAuras\WeakAuras.lua line 969:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:941>

Debug:
   WeakAuras\WeakAuras.lua:1007: Login()
   WeakAuras\WeakAuras.lua:1071:
      WeakAuras\WeakAuras.lua:1023

Si quelqu'un sait quoi faire je reste a disposition pour d'éventuel info sur le problème.

**Comment by Ferro-woe** [comment]
Addon téléchargé et testé ce jour, Aucun problème, fonctionne parfaitement.
A clôturer en invalid

**Comment by TrucEtrange** [comment]
Tu es sûr que tu n'as pas pris la version TLK Classic @ssimna ?

**Comment by Ferro-woe** [comment]
Je suis partis du principe que s'il a ouvert un ticket ici, il a téléchargé l'addon depuis le site Woe donc [weakauras-4.0.0](https://addons.way-of-elendil.fr/buffs-and-debuffs#weakauras-4.0.0) parmi les addons mis à disposition.
En effet les site curseforge ne propose plus d'addon de l'époque ils ont peut être fait du ménage.

**Comment by silverlays** [comment]
@ssimna J'ai eu un cas similaire après l'importation d'un WA à partir du site Wago.io (je soupçonne une incompatibilité entre Wotlk Classic et Wotlk Vanilla). Après l'importation, impossible de réouvrir mon WA malgré qu'il était bien chargé. Le résultat était une corruption du fichier WeakAuras.lua dans %WoW_DIR%\WTF\Account\XXXXXX\SavedVariables.

Si tu pense être confronté au même souci. Je t'invite à faire une sauvegarde de ce fichier et de le rennomer/supprimer du dossier en question. Cela te permettra de réouvrir WA, mais malheureusement tu devras réimporter tous tes WA.

L'autre solution (plus technique) est d'ouvrir ce fichier, de retrouver le WA qui pose problème, et de supprimer toute son arborescence (il faut bien faire attention à quel crochet { } correspond le WA, sinon cela ne fonctionnera pas).

J'ai personnellement utilisé la 2e solution en prenant bien soin de ne pas corrompre d'avantage mon fichier, et cela à fonctionner.

**Comment by Endalaust** [comment]
> Je suis partis du principe que s'il a ouvert un ticket ici, il a téléchargé l'addon depuis le site Woe donc [weakauras-4.0.0](https://addons.way-of-elendil.fr/buffs-and-debuffs#weakauras-4.0.0) parmi les addons mis à disposition. En effet le site curseforge ne propose plus d'addon de l'époque ; ils ont peut être fait du ménage.

Tout est dit

**Comment by Ferro-woe** [comment]
@silverlays @ssimna
Pour précision, histoire d'être bien clair, je vous confirme que les addons `Wotlk Classic` et `Wotlk Vanilla` ne sont pas du tout compatibles. Donc si vous téléchargez un addon `Wotlk Classic` pour essayer de le faire fonctionner sur Woe, l'addon sera non fonctionnel, et c'est tout à fait normal.
Une grande bibliothèque d'addon `Wotlk Vanilla` est [à votre disposition](https://addons.way-of-elendil.fr/) sur le site Woe.
Biz.
