### ISSUE TITLE
Quete Le guetteur solitaire.

### ISSUE THREAD

**Issue by Axsys33** [way-of-elendil/3.3.5#1537]
Lorsque l'on fait la quete en groupe, l observateur nain sombrefer loot la chevaliere de poignegivre mais seul le premier membre du groupe qui ramasse sur le cadavre obtient l'objet l'objet.

**Comment by MJ-Vyr** [comment]
Bonjour, c'est normal sous Wotlk les items de quête ne sont pas dupliqués pour les quêtes n'étant pas de groupe.
