### ISSUE TITLE
[Item] Item de quête obtenable en open-world

### ISSUE THREAD

**Issue by furiml** [way-of-elendil/3.3.5#1539]
## **Description**
L'item de quête [Glande à toxine](https://woehead.way-of-elendil.fr/?item=42927/toxin-gland) est obtenable sans avoir la quête [Remède de caverne](https://woehead.way-of-elendil.fr/?quest=13055)

## **Étapes de reproduction**

(Constaté sur elfe de la nuit guerrier)
- Se rendre dans la caverne des jormungars aux pics foudroyés (vers 46,55)
- Tuer des [Jormungars Infectieux](https://woehead.way-of-elendil.fr/?npc=30148)
- Sur environ 40 jormungars tués, j'ai pu obtenir 7 glandes à toxines

## **Comportement attendu**
L'item glande à toxine ne devrait pas être obtenable sans avoir la quête (au passage, la quête semble pour la horde uniquement et je suis alliance).

### **Captures d’écran / Vidéos**
Capture d'écran des glandes dans mon inventaire:
![](https://screens.way-of-elendil.fr/uD4tnPoc.png)

## **Ressources additionnelles**
cf. post

**Comment by MJ-Vyr** [comment]
#1397
