### ISSUE TITLE
Gain d'expérience après dégroupage

### ISSUE THREAD

**Issue by Valzul** [way-of-elendil/3.3.5#1544]
**Description**
Le comportement officiel a été décrit dans le bogue suivant : [https://github.com/way-of-elendil/3.3.5/issues/1039](url).
Théoriquement, il devrait être possible pour les personnages en leveling, d'obtenir tout l'XP lorsqu'ils ont touché un mob dans une instance après un dégroupage puis un kill du mob par un autre joueur.

**Étapes de reproduction**
Grouper par exemple un joueur de niveau 15 avec un personnage de niveau 80.
Entrer dans le donjon de Ragefeu par exemple.
Dégrouper, laisser le joueur de niveau 15 pull un moben lui faisant des dégats.
Tuer le mob avec le niveau 80, ne procure aucun XP pour le joueur de niveau 15.

**Comportement attendu**
Le comportement attendu est décrit dans le bogue mentionné dans la description. Théoriquement, le joueur en phase de leveling devrait obtenir tout l'XP du monstre, dans l'exemple de la reproduction en l’occurrence, cinq fois l'XP classique d'un mob non-élite du même niveau.

Je crois me rappeler que comportement était valable à une certaine époque du serveur sans pour autant pouvoir fournir de dates ( j'ai arrêté de jouer sur une longue période ) et je n'arrive pas à mettre la main sur une ressource qui indique que cela a été changé.

**Comment by Endalaust** [comment]
C'est effectivement un comportement assumé quant à l'impossibilité de gagner de l'expérience via ce biais, qui bien que blizzlike pendant un temps n'avait rien de normal.
Il s'agit d'une rare entorse du serveur à aller contre le côté "blizzlike" de la chose (bien que largement débattu).
