### ISSUE TITLE
Chaine de glace du DK

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#155]
**Description**
La chaine de glace du DK n'est pas dégressive, c'est à dire le slow de 95% dure toute la durée

**Étapes de reproduction**
Faites un duel avec un chevalier de la mort, il pose chaine de glace, bougez.

**Comportement attendu**
Slow l'ennemi de 95% puis réduit de 10% ce slow chaque seconde pendant 10s. (85% 75% 65% etc)

**Ressources additionnelles**
https://db.rising-gods.de/?spell=45524

**Comment by joshwhedon** [comment]
Deja signale.
