### ISSUE TITLE
Les pirates de Tanaris ne donne pas de réputation pour Gadgetzan

### ISSUE THREAD

**Issue by SeeYouh** [way-of-elendil/3.3.5#1557]
Dans la région de Tanaris, que se soit les pirates de Bat-le-désert ou des mers du sud, ou leur chef, aucun d'eux ne donne de réputation pour Gadgetzan lorsqu'on les tuent.
La seule manière que j'ai trouvé pour gagner de la réputation auprès de Gadgetzan est de valider la quête répétable  "Prime de la poche à eau" qui permet de rendre les Outre de Bat-le désert pour gagner 10points de réputation.
![image](https://github.com/user-attachments/assets/9888349f-92f7-4c2c-bc13-d51d5adf2c9b)
https://www.wowhead.com/classic/fr/faction=369/gadgetzan
Si l'on regarde ce qu'indique le site wowhead sur l'extension classic, on devrait gagner des points pour Gadgetzan.

**Comment by Zone04** [comment]
![image](https://github.com/user-attachments/assets/9fae0424-c457-4306-8a19-96b19da8a54e)
J'y farm régulièrement mes réput, testé encore à l'instant, ça fonctionne sans souci, j'ai bien des points de réputation avec les 4 factions du Cartel Gentepression.
A voir s'il n'y a pas des contraintes sur le gain de réputation selon le niveau actuel, ça ne m'étonnerait pas qu'ils ne donnent pas de réputation à partir de Révéré par exemple.
Pour information, je suis actuellement Haï par 3 des factions du Cartel et Amical uniquement avec Gadgetzan

**Comment by SeeYouh** [comment]
Pourquoi il n'y aurait que pour Gadgetzan ou l'on ne gagnerais pas de réputation avec les pirates qui sont à Tanaris ?
J'aurais compris pour Baie-du-butin ou une autre ville mais pas Gadgetzan.
En sachant que la quête répétable donne pour les 4 réput dont Gadgetzan qui récupère 10pts.

**Comment by MJ-Vyr** [comment]
Ces PNJ ne donnent plus de réputation passé Révéré, c'est normal.
Il existe beaucoup de guides sur internet expliquant comment fonctionne cette réputation, je vous invite a les consulter.
Je ferme.
