### ISSUE TITLE
Azjol Nerub - bug combat après Hadronox

### ISSUE THREAD

**Issue by leblackmetalmatuer** [way-of-elendil/3.3.5#1559]
**Description**
Un bug combat constant à Azjol Nerub.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Azjol Nerub
- Normal
- Après la mort de Hadronox
- Lors du passage où on doit sauter dans le vide, il semble y avoir un problème d'aggro avec les petites araignées qui met en bug combat, même lorsque je ne les approche pas ou que les autres ont aggro avant moi. Lorsque j'ai tp out/in pour enlever le bug combat, sur ma route, après avoir sauté dans le trou (chute dans l'eau), j'ai pu apercevoir une de ces petites araignées à côté des mobs jaunes. Elle ne m'a pas aggro malgré son statut agressif, elle semble être tombée de la map.
- J'ai constamment ce bug en tant que healer (prêtre), pas les autres personnes.
- Il semble que ce soit un problème de passage sous-map

**Comportement attendu**
On ne devrait pas avoir d'aggro/bug combat une fois les araignées tuées.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Ferro-woe** [comment]
Bonjour.
> *Lors du passage où on doit sauter dans le vide, il semble y avoir un problème d'aggro avec les petites araignées qui met en bug combat, même lorsque je ne les approche pas ou que les autres ont aggro avant moi. Lorsque j'ai tp out/in pour enlever le bug combat, sur ma route, après avoir sauté dans le trou (chute dans l'eau), j'ai pu apercevoir une de ces petites araignées à côté des mobs jaunes. Elle ne m'a pas aggro malgré son statut agressif, elle semble être tombée de la map.*

> *Lorsque j'ai tp out/in*
Pour reset le mode combat tout le groupe doit tp out/in, pas seulement vous.
> *après avoir sauté dans le trou (chute dans l'eau), j'ai pu apercevoir une de ces petites araignées à côté des mobs jaunes.*
En effet. La solution est de tuer ces petites bêtes **avant de sauter** dans le trou, et il n'y aura pas de bug combat.

Avec ces éléments, je ne suis pas sûr du tout que cette demande soit prise en compte, mais c'est bien tenté.
Biz.

**Comment by leblackmetalmatuer** [comment]
Bonjour, pourtant les autres essayent de tuer les petites araignées, mais
même après un usage d'aoe à répétition, le bug semble persister. Je n'ai
jamais eu ce bug sur Warmane par exemple.

**Comment by Ferro-woe** [comment]
Je n'ai rien à ajouter, un MJ tranchera :)

**Comment by leblackmetalmatuer** [comment]
> Je n'ai rien à ajouter, un MJ tranchera :)

Tu confonds peut-être avec le HM, je parle ici du NM. Une autre personne m'a confirmé constamment avoir ce bug en NM également avec suspicion des mobs rentrant sous les textures.

**Comment by MJ-Vyr** [comment]
Après vérification pas de souci de bug combat en tuant correctement tout les adds avant de sauter. Je close.
