### ISSUE TITLE
Tous les sorts de chaman ne passent pas en combat

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#156]
**Description**
Les horions (terre/feu/givre) et les totems (incendiaire, magma et talent elem "storm, earth and fire") ne passent pas en combat

**Étapes de reproduction**
Prenez un chaman elem, utilisez vos sorts cités sur un joueur

**Comportement attendu**
Les sorts horions et les totems magma/incendiaire doivent mettre en combat
Le root du chaman via le talent "Tempête, terre et feu" doit passer en combat (chaman et ses victimes)

**Ressources additionnelles**

**Comment by Justforsoloq** [comment]
Addendum : Aucun sorts du chaman ne passent en combat (offensif)

**Comment by joshwhedon** [comment]
Aucun sort en general en pvp :D . J'ai casse un truc.
