### ISSUE TITLE
Armure démoniaque

### ISSUE THREAD

**Issue by Debar57** [way-of-elendil/3.3.5#1560]
**Description**
L'augmentation de l'armure non correcte

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe   Demoniste
- Race      humaine
- Spécialisation  demontologie
- Sort / Talent / Etc  - Armure démonique

**Comportement attendu**
L'augmentiaton de l'armure doit être de 558 et 24% pour les points de vie et les sort
grâce  au talent Egide démoniaque 2/3
et elle n'est que de 465 et 20%

**Captures d’écran / Vidéos**
![image](https://github.com/user-attachments/assets/39893514-5fe3-4ebc-9770-3d2517288ac8)
![Capture d'écran 2024-07-29 181034](https://github.com/user-attachments/assets/9d3a71b7-5c41-4649-9831-a526995eab7e)
![Capture d'écran 2024-07-29 180926](https://github.com/user-attachments/assets/d04850d9-4413-4e07-814b-8f45440b0f8b)

**Comment by Debar57** [comment]
![Capture d'écran 2024-07-29 181112](https://github.com/user-attachments/assets/b9bb098a-a657-4a5b-acac-9a63fe00a3d2)

**Comment by MJ-Vyr** [comment]
Bonjour, c'est un bug de display mais ce talent fonctionne correctement en pratique. Je close.
