### ISSUE TITLE
Ingénieurs / Manque des spells au maitre des ingénieurs

### ISSUE THREAD

**Issue by Zeuh** [way-of-elendil/3.3.5#1563]
**Description**

Manque d'item ingénieur au maitre de métier ingénieur.

**Étapes de reproduction**

Plusieurs spells sont notés comme en vente par un maître de classe ingénieur sur wowhead mais ce n'est pas le cas sur WOE.

https://www.wowhead.com/wotlk/fr/spell=56480/lunettes-cuirass%C3%A9es-en-titane
https://www.wowhead.com/wotlk/fr/spell=56487/am%C3%A9liorateurs-de-vue-%C3%A0-%C3%A9lectroflux
https://www.wowhead.com/wotlk/fr/spell=56486/binocles-de-vision-verte
https://www.wowhead.com/wotlk/fr/spell=56483/b%C3%A9sicles-charg%C3%A9es-en-titane
https://www.wowhead.com/wotlk/fr/spell=41319/b%C3%A9sicles-lunaires-amplifi%C3%A9es
https://www.wowhead.com/wotlk/fr/spell=41311/b%C3%A9sicles-porte-justice-2000
https://www.wowhead.com/wotlk/fr/spell=41316/b%C3%A9sicles-vivantes-du-r%C3%A9plicateur
https://www.wowhead.com/wotlk/fr/spell=41317/lunettes-coup-de-gr%C3%A2ce-x11
https://www.wowhead.com/wotlk/fr/spell=41315/lunettes-de-gadget-orage
https://www.wowhead.com/wotlk/fr/spell=61481/lunettes-de-glacier-m%C3%A9canis%C3%A9es
https://www.wowhead.com/wotlk/fr/spell=61483/lunettes-de-glacier-m%C3%A9canis%C3%A9es
https://www.wowhead.com/wotlk/fr/spell=61482/lunettes-de-glacier-m%C3%A9canis%C3%A9es
https://www.wowhead.com/wotlk/fr/spell=56465/lunettes-de-glacier-m%C3%A9canis%C3%A9es
https://www.wowhead.com/wotlk/fr/spell=56574/orbi%C3%A8res-glac%C3%A9es-de-v%C3%A9rivision
https://www.wowhead.com/wotlk/fr/spell=41314/lunettes-vise-juste-v2-0
https://www.wowhead.com/wotlk/fr/spell=41312/lunettes-tankatroniques
https://www.wowhead.com/wotlk/fr/spell=56481/spectraliseuses-de-faiblesse

**Comportement attendu**

Le PNJ propose les spell à l'achat et ce n'est pas le cas 
(visible sur le woehead of elendil : https://woehead.way-of-elendil.fr/?item=42551

**Comment by Naryelle-WoE** [comment]
Le maitre des ingénieur ne proposera à ton personnage que les recettes des lunettes qui lui correspond en fonction de sa classe (je ne me souvient plus si la spécialisation est aussi prise en compte ou pas).

Il est normal de ne pas tous les avoir sur un personnage.

**Comment by Endalaust** [comment]
Je rajouterais que plusieurs liens ici montrent des ajouts propre à wotlk classic, et pas wotlk
![screenshot_5075](https://github.com/user-attachments/assets/524f9776-f993-4cb9-8b52-7ace3b1bf637)

**Comment by Naryelle-WoE** [comment]
> Je rajouterais que plusieurs liens ici montrent des ajouts propre à wotlk classic, et pas wotlk
> 
> ![screenshot_5075](https://private-user-images.githubusercontent.com/1420867/353925310-524f9776-f993-4cb9-8b52-7ace3b1bf637.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDY4MDksIm5iZiI6MTcyMjQ0NjUwOSwicGF0aCI6Ii8xNDIwODY3LzM1MzkyNTMxMC01MjRmOTc3Ni1mOTkzLTRjYjktOGI1Mi03YWNlM2IxYmY2MzcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTcyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUzZjJhOWQ1NjMzNzNlZTI1Mjg0MmE0OGE3NWZiMmY0MDcxMWY0MjQ2YjhmYjZjMTFlZjA2MjI3OTlhOTg2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WbWO53-kHR1f7ELOe9ldTHGpQHyOhQpwntfuGmTGaBg)

Non pertinent, cette mention est, par exemple, présente sur les barres de titane et viens du fait que la version wotlk de la  base wowhead a été refaite à la sortie de wotlk classic pour y intégrer les éventuels changements même lorsqu'il n'y en a pas eu, on peut par exemple voir des commentaires datant bien des extensions inférieures.

**Comment by Endalaust** [comment]
Pas de chance. Dans ce cas wowhead wotlk n'a aucune fiabilité pour comparaison avec la v3.3.5.

**Comment by Zeuh** [comment]
Plusieurs commentaires sur wowhead date de 2009 ou avant ..
