### ISSUE TITLE
Quête "Là-bas tout en bas"

### ISSUE THREAD

**Issue by StanleySQUIRELL** [way-of-elendil/3.3.5#1565]
Durant la quête "Là-bas tout en bas" donné à Zul'Drak par le PNJ Seigneur Drakuru.
Personnage utilisé: Druide tauren

Le PNJ nous donne l'objet Sceptre de suggestion qui permet de soumettre un geist chancreux qui va récupérer les cristaux chancreux nécessaires à la complétion de la quête. Ici, le sceptre soumet bien le geist mais ce dernier ne réagit à aucun cristal aux alentours, tous ont été testés. Aucun cristal n'est obtenu, même après avoir soumis d'autres geists également.

**Comment by MJ-Vyr** [comment]
Il faut utiliser la barre de sort du pet pour que le geist ramasse les cristaux Quête testée et fonctionnelle.
