### ISSUE TITLE
Dk sang drw

### ISSUE THREAD

**Issue by Kataakuma** [way-of-elendil/3.3.5#1566]
Le point de talent du dk sang >arme runique dansante< est buguer.

L'arme runique dansante ne prend pas en compte le taux de chance de coup critique du dk alors que normalement elle devrait avoir les mêmes chances de coup critique.

Par exemple j'ai constaté avec recount en bg alors que j'ai plus de 30% de chance de coup critique que sur 20 coups de la drw elle n'a mis que 1 coup critique ce qui fait que 5% de chance de crit.

J'espère que vous pourrez réparer ça si possible.

**Comment by Kataakuma** [comment]
Melendder ce n'est pas une histoire de mauvaise chance parcque ça n'arrive pas qu'à moi et ça arrive que sur 30, 40 coups toujours pas de coup critique donc au finale on est bien en dessous des 5% et des 1% je ferais quand même un test avec 100 coups je pense que ça devrait être suffisant

**Comment by Satarians** [comment]
En pvp la résillence reduit les chances de coup critique, entre 0% et 15% pour les joueurs stuff,
Il me semble qu'il y aussi deja un ticket ouvert ( ou fermé) sur ce sujet.

**Comment by MJ-Vyr** [comment]
Sujet déjà abordé maintes fois et clos a de nombreuses reprises. Je vous invite à chercher les tickets déjà fermés a ce sujet.
