### ISSUE TITLE
Problème avec le talent Subversion / Frappe au coeur

### ISSUE THREAD

**Issue by Apprentiyoyo** [way-of-elendil/3.3.5#1569]
On dirait que le talent Subversion fonctionne zéro avec la frappe au coeur, qui devrait avoir 9% de chances de crit en plus.
J'avais des doutes quand je regardais mes recounts en raids, j'ai donc décidé de taper un mannequin pendant 25min pour voir et ça à l'air de confirmer le bug.

![Frappe de sang](https://github.com/user-attachments/assets/8193c1a6-2e64-4a92-95a6-4c2aa94269c3)

On peut voir que j'ai 41.23%  de crit, et que mes 511 frappes au coeur n'ont crit qu'à 43.6% (au lieu de 50%).
Les 2% supplémentaires peuvent s'expliquer par les multiples proc nain de fer de la vpm durant les 25 minutes.

Voilà, il serait aussi intéressant de voir si il y a le même problème pour les autres techniques (notement frappe du fléau et anéantissement).

**Comment by Wilpok** [comment]
![image](https://github.com/user-attachments/assets/6dbbbe94-371b-4b0e-95ef-72f0444c69c8)

Pas de souci de mon côté après test après 100 itérations j'étais à 15.8% et j'ai poussé à 200 itérations ce qui m'a conduit à 13.2% pour une théorie a 15.29 et un score de critique de 6.29% sans talent. Prendre des données dans un environnement avec le moins de variables possible permet un rapport plus pertinent et correct.

Cependant en checkant (vraiment en survolant, rien de bien poussé) l'arbre de talent j'ai trouvé que y'avait 0.2% de gain de critique en trop sur le talent conviction (pour  le petit aparté) 
![image](https://github.com/user-attachments/assets/e875fc3a-fdc5-4cfe-b538-b95a53fcd398)
 ( 6.29 -> 11.49)
