### ISSUE TITLE
Instance: EDC 5

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#157]
**Description**
Tous les soucis ont été rencontré en mode héroïque

1er partie :

- Sans lance, le curseur change pour les montures de la faction opposée, il est possible de monter dessus mais le PJ se voit rejeté du véhicule.
Il ne se passe rien pour les montures de notre faction. Une fois la lance équipée et retirée, le curseur pour monter apparait mais rien ne se produit

- Les montures des boss ont 12k6 pv (au lieu de [je met à jour des que possible])

- Après un wipe, les grilles ne se réouvrent pas
- Après un wipe pendant le combat des boss à terre, ceux tués ne repop pas

2nde partie :

- Trashs: aggro un pack, ne rien faire, ça reinit tout seul (C'est arrivé sur les 2 packs sur le côte, pas celui pres du boss)
- Trashs: La pretresse 35307 ne pop pas le puit
- Trashs: 35303 Doit faire sa méditation quand il est low hp (je sais plus cb)
-Boss : Confesseur d'argent n'a pas fait les ombres du passées (me suis peut etre foiré sur ce coup là, je retest quand je reviens)
- Impossible de loot le coffre de cette partie, quel que soit le boss

-3eme partie
-P1 : Le boss ne rez pas NPC 35005 en goule
- pas de loot gold

**Comment by Killyana** [comment]
Les montures qui sont "rouge" agressives ne peuvent être monter, si vous essayez vous serez jeter par terre, seule les montures "verte" amicale peuvent être monter après avoir équiper une lance.

**Comment by Ischjgt** [comment]
Pour le wipe partie 1
Note: It is possible to phase out of the instance after the "1,5th" round starts, phasing out/wiping makes the 3 bosses run to the big gate and wait until you aggro them by yourself, this gives you lot of time to prepare for the fight.

**Comment by joshwhedon** [comment]
Eridium a verifie les pv des montures des boss sont en fait correctes.

**Comment by joshwhedon** [comment]
Bon on a trouve un script largement mieux. Je l'applique prochaine mise a jour.

**Comment by Malleksuken** [comment]
Pour la 3ème partie (faite ce jour vers 13h20) : 
Nous avion une compo 2 DK (dont tank), 1 rogue, 1 prêtre heal et 1 hunt. 

Phase 1 du boss : le pet du hunt continue à taper le cadavre du boss => pas de passage en phase 2.
Le hunt a reload (il ne parvenait pas à "pacifier" son pet) => début de la seconde phase du boss

Phase 2 du boss : le boss fait pop une multitude de goules qui explosent lorsqu'elles sont tuées, en faisant des dégâts en aoe. Je me demande s'il n'y a pas trop de goules qui pop, nos deux càc se sont fait ouvrir ^^'
N'ayant jamais joué sur offi, je ne puis comparer :-/

Phase 3 du boss : rien constaté de différent ou d'anormal

**Comment by joshwhedon** [comment]
Pour la phase 2, les goules explosent dans 3 situations : 
- le boss lance explosion de goule (il en fait exploser une)
- la goule tombe a 30% de vie
- le boss passe en phase 3 (il les explose toutes). 
Donc la strategie est de les tuer petit a petit, ou bien tres tres vite.
Merci pour le rapport, je vais mettre un fix pour le changement de phase.

**Comment by joshwhedon** [comment]
Quelques améliorations seront faites a la rencontre plus tard.
