### ISSUE TITLE
Bug PV Gargouille

### ISSUE THREAD

**Issue by Sthanks** [way-of-elendil/3.3.5#158]
**Description**
La Gargouille à 2428 pv alors quelle devrais en avoir environ 25 000

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- 
- Race
- Spécialisation
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Killyana** [comment]
Relativison un peut avec le 25k
[1] GUID: Full: 0x0 Type: Creature Entry: 24080 Low: 4681429
[1] UNIT_FIELD_HEALTH: 17885

**Comment by joshwhedon** [comment]
C'est base sur la stamina du dk. Je vais voir pour scripter ca.

**Comment by joshwhedon** [comment]
Bon, j'ai reutilise les memes valeur de stamina que la goule. Ca signifie qu'elle beneficie d'environ 0.3 points de stamina par stamina du joueur. Ensuite ca devient 10pv par point de stamina. De meme, impossible de trouver des sources valables nulle part donc ... si vous avez des infos elles sont les bienvenue.

**Comment by Sthanks** [comment]
Pour suite.

**Comment by Goudronaide** [comment]
Le problème hp de la gargouille n'est pas complètement régler, elle en possède actuellement dans les environ de 9000 mais sans dépasser les 10k hp, comme dit plus haut, la gargouille devrait avoir plus de 25 000 hp a 30 000hp max

**Comment by joshwhedon** [comment]
Comme indique plus haut, a moins de fournir des informations exactes quant a la formule utilisee pour les hps de la gargouille, rien ne sera change.

**Comment by gtschanz** [comment]
je vais apporter mon grain de sel, concernant la formule il me paraît très compliqué de la trouvé en tant que joueur si on a pas accès aux scripts d'époque, néanmoins si tu veux des preuve je pense sans difficulté pouvoir te sortir x vidéo ou les pv de la goil dépasse les 20K; pouvons-nous convenir d'un arrangement c'est à dire que tu adapte les pv de la goil sur l'équivalent des pv de la goil sur les vidéos offi ? histoire que le ''dk'' n'est pas pénalisé car actuellement si tu prends en pvp le joueur qui affronte un dk impie il n'a même pas besoin de ''contrôler'' la gargouille il suffit qu'il l'a focus ça prend ''moins longtemps ou le même temps sauf que ça permet de garder des cd de contrôle pour certaines classe au chaud - exemple le prêtre n'utilise plus l'entrave des morts vivant - le pala n'utilise plus sa colère divine / fear des mort vivant pour le contrôle (car il l'a garde quand le dk change liche (transformation en undead -> donc gros avantage) le druide ne cyclone plus la gargouille mais garde le ''clone pour le dk'' etc etc...

**Comment by Justforsoloq** [comment]
J'ai déjà sorti sur le précédent topic des vidéos avec des pvs de la gargouille affichés.

**Comment by Popeyeddd** [comment]
Coucou alors primo la goyl devrait pas pop instantanément, y a une animation qui l'a fait descendre du ciel et qui te laisse une bonne seconde pour la target et pour te préparer à la contrôle ([lien vidéo](https://www.warcraftmovies.com/movieview.php?id=149629&__cf_chl_jschl_tk__=97c44e70e940be309dcfca0a72ac773215341a85-1594290006-0-AZaNAFhZA1baacJ3d6rla78pc5TwNDjASKFHet__wkj-UDMtot5HGZERUv8AM9Xn-tcNed3BsIOsicfojsClmBs_61oieO3ggik_dToNmheS4fheoYO1e2lxHXP6dzdkghzDAHw3ZTAFC-AIU1Mrq3LA1cHu73TEbyZebrVhJT9UpyvxqdPUeYRsg-ALGHA0Deg11s3VUEFCsGUDKHE7d29N-aH1rlWRjXZViqXEAVLVKK6lbP7i5oaplHZpCc-HuTuOedVzzWW7hhHSQIROEnVizB650bhMOMuFwQhFfVKKIDDrS4upZ1YXyVt40PxiMA) - regarder les premières secondes)

Ensuite pour les PV de la goyl :
D'accord avec eux faut être réaliste c'est pas script, la formule on la retrouvera probablement jamais à 100% de certitude donc à partir de là faut un peu essayer de deviner.

Si tu regardes la data base :
https://woehead.way-of-elendil.fr/?spell=49206 (lien du sort)
https://woehead.way-of-elendil.fr/?npc=27829 (lien du npc lié au sort)

Tu vois déjà (ça vaut ce que ça vaut) que la vie de base de la bestiole est de 12,600

Ensuite quand tu regardes des vidéos, tu vois vite qu'il y a un scaling sur l'endu du dk, tu fais vite le rapprochement avec le pet du hunt qui a le même type de scaling.

Formule pour le pet hunt : (ué je connais des forum de pet tanlking jugez pas pls)
https://bigredrhino.forumotion.com/t6-pet-stamina-formula

En gros la formule est compliquée pour un débilos comme moi, mais elle prendre juste en compte le millier de points de talents hunt / pet qui affectent la vie du pet. Sauf que dans le cas du dk, y a aucun talent du genre (le seul qui existe coté impie ne concerne que les goules pas la goyl)

Donc en gros le pet en hunt profite de 45% du score d’endurance du hunt, si tu appliques le même truc à la goyl

Si tu fais ça disons qu'un dk implacable a environ 2200 d'endurance donc 990 de stamina pour le pet soit 9900 pv que tu additionnes aux 12600 pv de base ça te donne une goyl à 22500 pv

Franchement ça colle un peu j'dis pas c'est ça précisément sois audacieux, vaut mieux s'en rapprocher en étant prudent que laisser ça complétement bug, là imo c'est convenable.

**Comment by joshwhedon** [comment]
La vie de base de la db n'a rien a voir avec la vie des pets. Donc non, ce n'est pas la vie de base. Par contre si vous avez des videos d'un dk tout nu qui montre les pv de base de la gargouille, ca ca aiderait.

Le scaling de l'endu est deja present, j'ai mis le meme que pour la goule.

C'est pas audacieux, mais ca reste incorrect.

**Comment by Popeyeddd** [comment]
Ptdr bah j'sais pas dans ce cas ça indique quoi ?

Et ué j'ai bien compris ta position, tu veux le script retail, sauf que perso je trouve ça mieux d'accepter d'appliquer un script qui te fait te rapprocher du script retail (tout en ayant conscience si t'es jusqu'au-boutiste que c'est toujours bug car pas exactement le script de l'époque) que laisser un tel écart avec le script d'origine.
Je trouve ça pertinent de tenter de réduire le problème (tout en ayant conscience que c'est pas parfait) plutôt que de le laisser en place mème si c'est scandaleux.

Et pour ton script du coup qui reprend le scaling hp de la goule pour tenter de corriger celui de la goyl, tu sais qu'il y a le scaling de hp de base (celui que j'imagine tu as utilisé) mais il y en a également un en plus dans les talents ?

![Sans titre](https://user-images.githubusercontent.com/65403286/87041783-0565e900-c1f3-11ea-9135-3cf818a77e07.png)

Donc bon se baser sur le scaling hp de base d'une goule qui bénéficie également d'un gros boost scaling hp dans les talents pour corriger le scaling hp d'une goyl qui elle n'a aucun talent du même genre je trouve ça foireux ^^^

Fin bon j'voulais juste donner mon avis je joue pas dk et limite balek, mais t'avais eu le meme raisonnement pour un report des dégâts tréants de Epinard et j'trouve ça nul (qui au passage est normalement un must have en pve et qui ici n'est juste pas pris, ça laisse réfléchir, alors en pvp n'en parlons pas). 

Vaut mieux tenter de réparer que laisser le script à la rue parce que les formules, la data ça se retrouve de moins en moins, les sites de l'époque ferment, le forum battle.net a été purgé ect ect

Donc peu de chance qu'un jour t'ai la formule exacte, perso j'pense qu'il vaut mieux tenter de se rapprocher du script que de refuser de se mouiller et de penser qu'une goyl qui a la moitié, LA MOITIE des hp qu'elle devrait avoir est acceptable fin j'sais pas

No offense j'respecte le boulot et tout mais voilà, d'un point de vue de joueur, vouloir à tout prix le saint script retail, pour au final accepter des situations qui sont méga éloignées de ce dernier, perso j'comprend pas
