### ISSUE TITLE
bug enchantement Gants (erreur entre Niveau d'objet et Niveau nécessaire pour porter)

### ISSUE THREAD

**Issue by fredericwow** [way-of-elendil/3.3.5#1585]
**Description**
Décrivez le problème de façon claire, précise et concise.
Bonjour, j'essaie d'enchanter des gants de niveau d'objet 39 pour un personnage niveau 34
avec l'enchantement de gants explosion qui permet d'augmenter le score critique de 10 pour un niveau d'objet de 35 ou supérieur!
Lorsque je clique sur le gant, il me met que le niveau de la cible est trop bas!
Objet: **Gants de l'aurore** (Niveau 34 requis Niveau d'objet 39) Non lié bien sûr
Sort: Enchantements mains intitulé "**Ench. de gants (Explosion)**"
Bien entendu, ayant tous les ingrédients nécessaires (1 essence planaire 4 essences arcaniques)
Personnage "Drachman"  Niveau 66 Dranéï Chaman Enchanteur
Circonstance: Repos en ville (Hurlevent), j'enchante dans mon inventaire perso
Buffs: Rage libérée (je ne sais plus vraiment ce que fait ce buff précisément)
          Présence héroïque (c'est également un buff toujours actif)

J'espère que vous pourrez corriger ce dysfonctionnement, Merci.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe
- Race
- Spécialisation
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by MJ-Vyr** [comment]
Il est probable que le tooltip se réfère au niveau requis pour porter l'objet, et pas au niveau d'objet.
En l'absence de preuve du contraire, je clôture.
