### ISSUE TITLE
Arme Runique Dansante

### ISSUE THREAD

**Issue by Mlyndin** [way-of-elendil/3.3.5#1586]
Il semble y avoir un bug au niveau de la prise en compte de l'expertise lors de l'utilisation de la technique ou, le cas échéant, en ce qui concerne le placement de l'arme qui ce place toujours face à l'ennemie, car même si le chevalier de la mort a atteint son cap d'expertise, l'arme continue à se faire parer ou esquiver
**Étapes de reproduction**
- DK
- Sang 
- Arme runique dansante 
- Toute type de contenue 

**Comportement attendu**
Stat fixées sur celle du DK lors de l'invocation, ainsi qu'un positionnement similaire à celui du DK

**Captures d’écran / Vidéos**
![WoWScrnShot_102124_185747](https://github.com/user-attachments/assets/7f4a9aee-ad26-497f-b28b-1fb8bce8a9e3)
![WoWScrnShot_102124_185816](https://github.com/user-attachments/assets/7c6e4c74-32d7-4222-8471-0dc52b738ecc)
![WoWScrnShot_102124_185829](https://github.com/user-attachments/assets/96e0585f-e1f8-49fa-aff4-f79f193168b7)
![WoWScrnShot_102124_185834](https://github.com/user-attachments/assets/36f24149-d391-40e8-a223-e54abf996b2c)

**Comment by MJ-Vyr** [comment]
En l'absence de preuve du "fonctionnement normal", impossible d'attester de celui-ci.
Je clôture.

**Comment by Mlyndin** [comment]
> En l'absence de preuve du "fonctionnement normal", impossible d'attester de celui-ci. Je clôture.

https://youtu.be/my9wslCEfl8?t=247&si=rwbT9bOb1nO0lQ0A
Est-ce que cette vidéo constitue une preuve du fonctionnement normal de la capacité ?

**Comment by Wilpok** [comment]
Oui et idéalement tu rajoute des liens qui expliquent le comportement attendu ( je checkerais la vod en détails ce soir voir si la drw se fait parry. Sur une autre vidéo de l’époque l’arme avait pop devant la cible quand le dk était derrière ce qui pouvait expliquer potentiellement des parry

**Comment by Mlyndin** [comment]
https://youtu.be/221jtKbsWQA?t=35&si=uB3k8dguLzXLiBZF sur cette vidéo d'époque on peut constater que dans des conditions similaires à celle des screen que j'ai pris que la drw ce place au côté du dk (comme le dk est un tauren il faut bien faire attention mais on constate que la drw est à ses côtés)
