### ISSUE TITLE
Bug dégâts gargouille

### ISSUE THREAD

**Issue by Sthanks** [way-of-elendil/3.3.5#159]
**Description**
La gargouille tape que 1300 - 1500 en fonction des procs. EN s7 sur warname les dégâts sont de 2300 environ 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe
- Race
- Spécialisation
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Un autre serveur prive n'est pas considere une reference. Merci de fournir des sources proches de l'officiel en 3.3.5

**Comment by Sthanks** [comment]
https://www.youtube.com/watch?v=BYK6OkFwbv8
https://www.youtube.com/watch?v=jA5I7jCqyfg
Je t'ai trouvée 2 sources d'offi. La première vidéo est sur du NO RESI.
Je viens d'allez tester directement sur poto. Avec dots 2036 et sans dot 1834 (Sans proc bijoux)

**Comment by joshwhedon** [comment]
J'ai prepare un correctif qui prend en consideration la puissance d'attaque pour les bonus, a raison de 0.22 par point de puissance d'attaque (meme ratio que pour les chasseurs). Je n'ai trouve aucune donnees nulle part quant a la valeur sur officiel, donc si vous avez des infos plus precises, merci de les fournir.
J'attends le feedback sur le fix.

**Comment by Justforsoloq** [comment]
-scales with all physical haste benefits at the same rate as the player
-attack power coefficient is 0.4
-base damage per strike is 120
-does not inherit any crit from the player
-does not inherit any +damage % modifiers from the player, such as bone shield, desecration, or blood presence
-player stats are taken as a snapshot when the gargoyle is launched; that is, when you cast this spell, however much attack power and haste is the amount your gargoyle strikes will be basing themselves off of.
(patch 3.1.3, gargouille ayant reçu un nerf dans les fix au patch 3.1 et je ne vois pas d'indication de nerfs des stats après le 3.1 seulement des changements de PR/durée)

**Comment by joshwhedon** [comment]
Merci

**Comment by Sthanks** [comment]
Pour suite.

**Comment by Sthanks** [comment]
--- Comparatif dégâts de gargouille ----
(Full stuff s8 opti) Mon dk sous full proc : Scale 271 - Verdict 258 - Proc PA bague 480PA - 150 Force proc deuil
1k8 - 2k - sans dot
--- Vidéo OFFICIEL ---- 
(Stuff s8) Arme 264 --- Proc crane à croc 
2k1 à 2k6+ - Sans dot

Y'a quand même une différence de stuff qui est énorme et les dégâts sont moindre coté WOE, 
Je link plus une video d'offi d'un dk full s8, trinket pvp, arme s8 ou s7 258 
https://www.youtube.com/watch?v=mCCySuuk_hk
