### ISSUE TITLE
[Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#1590]
**Description**
La Caméra part en cacahouète sous Fear, sheep, ect

**Étapes de reproduction**

se faire sheep/fear

- Classe / Spécialisation : ALL
- Champ de bataille / Arène : any
- Sort : Peur, sheep ect

**Comportement attendu :
Comme indiquer dans les paramètre du jeu" ne jamais ajuster la caméra" devrait ne pas avoir d'exception.

**Comment by MJ-Vyr** [comment]
Impossible a reproduire de mon côté, semble être un souci côté utilisateur.
