### ISSUE TITLE
Quest: Entretien avec les profondeurs

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#160]
**Description**
Quest 12032
Impossible de cliquer sur [The Pearl of the Depths] GUID: 21195 ID: 188422 
(.gob act lance l'event)

**Comment by Killyana** [comment]
Groupe de raid?
Sa fonctionne pour moi

**Comment by Killyana** [comment]
Fixé par: https://github.com/TrinityCore/TrinityCore/commit/46d38526a975b656b03f4068a82714fabcb883d4

**Comment by joshwhedon** [comment]
Je vais pas merge mais je vais passer le sql.
