### ISSUE TITLE
Bug conflagration

### ISSUE THREAD

**Issue by Kyouky** [way-of-elendil/3.3.5#1602]
**Description**
Lorsque je commence le cycle dps, je pose immolation pour enchainer avec conflagration. Or celui si n'est pas immédiatement disponible (c'est comme si il fallait du temps avant que conflagration detection qu'il y a immolation sur la cible), il faut attendre au moins 0,5 ou 1 sec avant qu'on puisse le lancer conflagration, cela pose problème en raid.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Demoniste destruction
- Elfe de sang
- Destruction
- immolation suivit de conflagration
- Circonstances: N'importe quand sur n'importe quel mob
- Equipement: peut importe
- Buffs / Debuffs / Enchaînement de sort / Etc : peu importe

**Comportement attendu**
Il est attendu que quand on lance immolation (ex: il faut 1,5 sec pour l'incante), on doit pouvoir utiliser conflagration instantanément si l'immolation a reussi à toucher sa cible et non pas devoir attendre 0,5 ou 1 sec pour que cela détecte.

**Captures d’écran / Vidéos**
Pas disponible mais si besoin je peux essayer d'en faire

**Ressources additionnelles**
N/A

**Comment by Justforsoloq** [comment]
C'est normal.
https://github.com/way-of-elendil/3.3.5/issues/296
