### ISSUE TITLE
[trinket] protecteur d'âme

### ISSUE THREAD

**Issue by MissZay** [way-of-elendil/3.3.5#1606]
**Description**
Le trinket ne fonctionne pas

**Étapes de reproduction**
Équiper le trinket et lancer autant de sorts de soin que vous voulez

**Comportement attendu**
Le trinket devrait avoir 2% de chances de proc sur chaque soin direct

**Captures d’écran / Vidéos**
Pas de proc sur plus de 300 casts, testé avec et sans heal effectif, aucune différence
https://screens.way-of-elendil.fr/c0brYcKS.jpg
https://screens.way-of-elendil.fr/dJWko5MW.jpg

lorsqu'il fonctionne:
https://www.youtube.com/watch?v=9YcDfrsiWVA
1er proc après 42 sorts 2ème proc après 84 sorts. Le glyphe de lumière sacrée compte comme un sort de soin direct donc chaque cast = 6 soins directs au maximum, chacun ayant 2% de chance de proc le trinket

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?item=37111
https://woehead.way-of-elendil.fr/?spell=60510

https://classic.warcraftlogs.com/reports/d7BMacXCTGhJzRtp#fight=2&type=auras&target=32&ability=60513
https://classic.warcraftlogs.com/reports/d7BMacXCTGhJzRtp#fight=2&type=healing&source=32
le trinket proc 18 fois sur 846 soins (guide + lumière + glyphe + horion), avec 2% de chance de proc ça donnerait environ 17 proc sur le papier ce qui correspond assez bien au log

**Comment by Wilpok** [comment]
Doublon avec https://github.com/way-of-elendil/3.3.5/issues/1598

mais oui la transe guérisseuse ici ( si elle proc ( aura 42 )) ne réduit en plus que le holy shock comme on avait vu avec amandil. 

Sachant que c’est une aura cachée sur tlk vanilla donc tu vois pas le proc ( a la différence de classic )

**Comment by Justforsoloq** [comment]
De plus il faut savoir que wotlk classic n'est pas utilisable pour "preuves" de bugs (étant un client différent de wotlk vanilla et comportant des changements et des bugs propres à la 3.4.0)

**Comment by MissZay** [comment]
D'où vient l'info comme quoi ça serait une aura cachée? sur tous les serveurs où j'ai joué (qui utilisaient la même database bugée qui affiche uniquement l'horion comme sort affecté) le buff était visible et fonctionnait pour tous les sorts, et la vidéo que j'ai postée vient d'un serveur privé 3.3.5 pas de classic
J'ai aussi testé d'alterner lumière sacrée avec 5 cibles et horion sur plus de 100 casts et je n'ai pas eu un seul horion avec le coût de mana réduit donc je pense qu'on peut bien dire que le trinket ne fonctionne pas du tout

**Comment by Justforsoloq** [comment]
Les links que t'as postés viennent de classic (wcl)
Et de la même façon que wotlk classic ne constitue pas une preuve, les pserv le sont encore moins.
(Même si j'suis aussi d'accord que le soul protector bug, si tu trouves pas de preuves wotlk vanilla ça va pas bouger)

**Comment by Wilpok** [comment]
Oui avec justforsoloq on a regardé une vidéo de hpal sur algalon pendant 15/20minutes et voir combien coutait la holy light à chaque fois pour te dire, c'est Amandil/vyr qui avait parlé d'aura cachée, je me basais sur classic aussi personnellement aussi.

![image](https://github.com/user-attachments/assets/a4f9573a-68b2-4722-8b5c-78ddf557066f)

Cf on en parlait là, tu peux check l'historique sur le discord woe si ça t'intéresse

**Comment by Wilpok** [comment]
Et my bad je croyais que la vidéo datait de classic mdr je pensais pas de pserv, dcp rip la preuve oui

**Comment by Ekrevice** [comment]
up

**Comment by MJ-Vyr** [comment]
Inutile de up un sujet ayant un statut fermé.
