### ISSUE TITLE
Piège givrant

### ISSUE THREAD

**Issue by Taurehador** [way-of-elendil/3.3.5#161]
**Description**
Le sort piège givrant paraît avoir un problème. En effet,une fois le sort lancé, le piège est mis en place mais lorsqu'il se déclenche, celui si ne gèle pas l'autre personnage (personne, pnj,...).

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Chasseur
- Tauren
- Spécialisation précision
- Piège givrant
- Leveling
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Le comportement attendu de ce sort est le suivant, une fois le piège déclenché au passage d'une quelconque personne (mob,...) celui-ci est gelé pendant 10 secondes au maximum.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Taurehador** [comment]
Je comprends, malheureusement; le piège givrant justement ne depop lors du passage d'un mob. Celui-ci disparaît mais ne s'active pas.

**Comment by joshwhedon** [comment]
Oui merci, certains pieges ne fonctionnent pas, on y travail au plus vite.

**Comment by Taurehador** [comment]
Ha, désolé je ne voulais pas vous presse, je n'avais pas compris. Merci beaucoup pour votre travail

**Comment by joshwhedon** [comment]
Bah c'est un bug handicapant donc il a la priorite, il est juste pas si simple a regler malheureusement :) .
