### ISSUE TITLE
Bug de la salve de guérison

### ISSUE THREAD

**Issue by Angeldidi** [way-of-elendil/3.3.5#1610]
**Description**
![Capture d'écran 2024-12-10 092501](https://github.com/user-attachments/assets/40f622ed-b0c4-4f65-9ec4-01c030c9ac36)
La Salve de guérison du chaman Restauration est censée soigner uniquement les membres d'un seul groupe. Cependant, un bug sur Woe fait que la Salve soigne tous les membres du raid, en sautant de groupe en groupe.

- Chaman
- Réstauration
- Salve de guérison
- Raid

**Comportement attendu**
La Salve de guérison du chaman Restauration est censée soigner uniquement les membres d'un seul groupe. Le comportement attendu est qu'elle ne soigne pas les membres d'autres groupes et ne saute pas d'un groupe à l'autre.

**Comment by MJ-Vyr** [comment]
Bonjour, après un minium de recherches, c'est un comportement normal. La formulation du tooltip est équivoque, mais ce sort est bien sensé rebondir sur les membres du raid.
En attendant que vous apportiez la preuve du contraire, je ferme ce ticket.
