### ISSUE TITLE
BUG farm forme de vol druide

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#162]
Bonjour;

Bug vue dans la couronne de glace; en forme de vol rapide en druide on doit pouvoir farm certaines plantes en l'air sans être impacté par les attaques des mobs (attaque mêlée) (héros converti et ni par les porte manière du fléau et ni par les vargul errant) il y a une petite distance de sécurité qui doit permettre ce farm entre la range maximal de prospection et la distance ou les mobs peuvent mettre des attaques en mêlée. (je n'ai que vérifier dans cette zone (car je ne farm que ici mais je pense que tout les mobs à norfendre sont impactés par ce soucis

INFO 100% sûr car j'ai farm des centaines d'heures à l'époque d'offi sous WOLTK en druide et c'était aussi possible avant la merge.

**Comment by gtschanz** [comment]
j'ai encore une fois vérifier la range des mobs me semble correct c'est la range de prospection des druides qui a été baissé significativement; elle doit permettre un farm au-delà de la distance de mêlée de certains mobs (aussi constaté sur les cobra empereur (au bassin de scholzar)

**Comment by Killyana** [comment]
Not gonne happen, fixé le range d’interaction avec les gobs était un enfer.

**Comment by gtschanz** [comment]
problème non fixé par rapport à la range des Héros converti et des porte bannière du fléau et des saccageur squelettique à la couronne de glace

**Comment by gtschanz** [comment]
problème non fixé par rapport aux saccageur squelettique / héros converti et porte bannière du fléau à la couronne de glace

**Comment by Ischjgt** [comment]
C'est fixé, mais le correctif n'est pas passé, il faut attendre la mise à jour et la fermeture du ticket.

**Comment by Killyana** [comment]
Apparemment il faut atterrir avant de de cueillir les herbes: https://www.wowhead.com/forums&topic=226829#p3599246

**Comment by gtschanz** [comment]
(d'expérience personnel je n'ai jamais eu à atterrir à l'époque d'offi) et sur le lien que tu m'as donné 3 personne disent qu'on n'a pas besoin d'atterir et 3 autres que si dont 1 dans le même poste qui indique des gants 85; je pense que ça a été mis en place sous catas; voici le message en question dans le lien que tu as mis;


''No you didn't have to land in Wrath to Herb.''
That started in Cata.'' By Woodrun on 2014/01/20 at 5:42 AM (Patch 5.4.2)

By Adamsm on 2014/01/18 at 6:13 AM (Patch 5.4.2)
''You do since Cata I believe.''

By Mike on 2014/01/18 at 5:36 AM (Patch 5.4.2)

''Was this recent? ie after WotLK?
I had herbing on my druid during wotlk and I never had to land.
You don't need to land when you need to pick up objects off the ground for quests either.''

///

une des trois personnes qui dit qu'il faut atterrir à mis ce message:

''Definitely have to land to gather in Flight Form, which is only viable when Herbing or Skinning.

P.S. (in response to Zakkhar's reply)
Faster gathering times can also be achieved by using:  Forager's Gloves''



les forager's gloves sont des gants lvl 85 uniquement accessible à partir de cata; je ne sais pas comment ça a été par la suite (après woltk); mais je reste persuadé de ce que j'ai connu y'a de ça une dizaine d'année.

**Comment by gtschanz** [comment]
je pense que c'est une discussion assez tendu; car dans le poste auquel tu te réfère c'est un débat entre 6 joueurs, trois joueurs disent que oui; trois autres que non; qui a raison hum - mais vu les commentaires je suis quasi certains qu'il fallait atterrir sous catas; mais pas forcémment sous woltk; du moins l'article n'est pour moi pas une preuve suffisante pour clore le ticket définitivement; mais doit être recherché pour compléter et ainsi valider ou invalider de façon définitive
