### ISSUE TITLE
NPC: Proto-Drake perdu dans le temps

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#163]
**Description**
C'est le Proto-drake perdu dans le temps 32491 qui spawn systematiquement après un crash

Vyragosa : 32630

**Comment by Killyana** [comment]
Bug lié au pooling pas possible de fixer pour le moment

**Comment by joshwhedon** [comment]
Pas moyen de changer qui spawn en premier ? Faire que ce soit pas le proto ?

**Comment by Killyana** [comment]
Je vais voir

**Comment by joshwhedon** [comment]
J'ai verifie, et c'est bien aleatoire. Oui y'a des chances qu'il spawn, mais il y a plus de chances que ce soit Vyragosa. J'ai reboot 3 fois en local et j'ai eu que Vyra.

**Comment by Ischjgt** [comment]
Du coup je réouvre le ticket, j'avais pas mit que tu avais mit ce label.
Ce matin je suis allé voir jsute après le crash, Vyragosa ET le proto était spawn, sur des points de spawn différents

**Comment by joshwhedon** [comment]
On y peut rien. Il faut que Trinity corrige les pools.
