### ISSUE TITLE
Quest: Nettoyage à secte

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#165]
**Description**
L'event se lance et tout se passe bien mais ça ne s'arrete jamais
24556
20438

**Comment by Killyana** [comment]
A passer une seule fois pour restaurer le script TC d’origine, j'ai enlevé la mauvaise modif de nos sql
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`IN (3685607) AND `source_type`=9;
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, `comment`) VALUES
(3685607, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 78, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Shandy Glossgleam - Script 8 - Stop Current Scripts"),
(3685607, 9, 1, 0, 0, 0, 100, 0, 2000, 2000, 0, 0, 0, 1, 8, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Shandy Glossgleam - Script 8 - Say Line 8"),
(3685607, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 66, 0, 0, 0, 0, 0, 0, 19, 36851, 0, 0, 0, 0, 0, 0, 0, "Shandy Glossgleam - Script 8 - Face Aquanos"),
(3685607, 9, 3, 0, 0, 0, 100, 0, 8000, 8000, 0, 0, 0, 1, 9, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Shandy Glossgleam - Script 8 - Say Line 9"),
(3685607, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 50, 201384, 60, 0, 0, 0, 0, 8, 0, 0, 0, 0, 5797.15, 696.602, 657.949, 6.09085, "Shandy Glossgleam - Script 8 - Summon Clean Laundry"),
(3685607, 9, 5, 0, 0, 0, 100, 0, 3000, 3000, 0, 0, 0, 53, 0, 36856, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Shandy Glossgleam - Script 8 - Set Phase 4");

**Comment by joshwhedon** [comment]
Merci on passe ca demain.

**Comment by Ischjgt** [comment]
1. Ça à l'air d’être encore là
Souvent les joueurs se plaignent d'un probleme avec la quête : ça s’arrête jamais, ils abandonnent et reprennent et ça remarche,
mais là pour le coup j'ai pas réussi une seule fois à la valider

Je sais pas si c'est normal mais on peut cliquer sur ces différents gobs pour lancer les vêtements, par exemple les pantalons, il y a tous ces gobs et au moins 2 sont cliquables

56258 (Entry: 201934) - [Pants X:5806.020020 Y:694.627991 Z:657.948975 MapId:571]  
56250 (Entry: 201295) - [Pants X:5806.049805 Y:694.593994 Z:657.948975 MapId:571]  
56251 (Entry: 201931) - [Pants X:5806.069824 Y:694.580017 Z:658.456970 MapId:571]  
56257 (Entry: 201301) - [Pants X:5806.069824 Y:694.580017 Z:658.458008 MapId:571] 

 2. Je crois qu'il n'est pas possible de cliquer sur un gob qui n'est pas celui demander, ce qui fait échouer la quête

**Comment by Asterie-elendil** [comment]
Problème rencontré aujourd'hui 14/04/2021 par un joueur

**Comment by Asterie-elendil** [comment]
> Problème rencontré aujourd'hui 14/04/2021 par un joueur
> la quête ne fini jamais le linge encore du linge et toujours du linge :)

**Comment by Kaasss-woe** [comment]
Correctif appliqué
