### ISSUE TITLE
les pierres de tp et tp demo

### ISSUE THREAD

**Issue by Tontonsid** [way-of-elendil/3.3.5#166]
les pierres de tp des instances et le tp demo ne fonctionnent plus. Les portails sont bien présents mais la personne ne reçoit pas le tp

**Comment by Endalaust** [comment]
Si possible évitez de les utiliser ou d'utiliser un démo, ca provoque la plupart des crashs de cette aprem :)

**Comment by joshwhedon** [comment]
Le demo aussi cause les crashs :D

**Comment by Endalaust** [comment]
Correctif déployé, en cours de test car non assuré
Si des joueurs peuvent s'amuser avec les pierres d'invocation ce matin ca éviterait de découvrir un drame ce soir ;)
