### ISSUE TITLE
Téléporation+Portail Dalaran

### ISSUE THREAD

**Issue by Akuponkture** [way-of-elendil/3.3.5#167]
**Description**
Lorsque je me téléporte ou que je crée un portail à Dalaran pour Dalaran, cela me TP instantanément sans page de chargement.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: Mage
- Téléportation: Dalaran +Portail: Dalaran
- Circonstances: se TP depuis la ville. Sinon depuis ailleurs, ça fonctionne très bien

**Comportement attendu**
Normalement, même depuis Dalaran, cela devrait refaire un fond de chargement avant d'être TP.

**Comment by joshwhedon** [comment]
C'est normal, les pages de chargement c'est dans le cas ou tu te teleporte vers un zone hors de ton champ de vision actuel (loin, ou sur une autre map). Dans le cas ou tu te teleporte sur de courte distances, ca agit plus comme le transfert au final.
