### ISSUE TITLE
Mort et vol

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#169]
**Description**
En étant en fantôme (mort), je perds la capacité de vol en sortant de la zone ou se trouve mon cadavre. De la couronne de glace à la fôret du chant de cristal par exemple. Mon cadavre se trouvait dans une instance.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Drood/feral

**Comportement attendu**
Rester en vol.

**Comment by joshwhedon** [comment]
C'est normal, seules certaines zones sont des zones de "vol" en fantome. La couronne de glace est une exception, pas une regle. La raison de ce systeme est que la couronne a de nombreuses zone ou il est impossible d'aller sans voler (donc impossible de recuperer son cadavre). Dans le cas des autres zones, il est possible d'atteindre toutes les zones a pied.
