### ISSUE TITLE
Donjeon Azjol Nerub - Boss 2 (arraignée)

### ISSUE THREAD

**Issue by atm-arnaud** [way-of-elendil/3.3.5#170]
**Description**
On ne peut pas pull l'arraignée car les groupes arraignées ne s'arrêtent jamais de pop.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon : Azjol Nerub 71+
- Niveau : Normal
- Boss : Adronox
- Composition du groupe
2 druidre 1 chasser 1 war 1 heal pretre

**Comportement attendu**
les groupes de scarabés arraignés une fois tuées doivent rester morts et l 'arraignée remonter.

**Comment by joshwhedon** [comment]
J'ai reteste le donjon, si il est trop difficile avec les add il suffit d'attendre un petit peu oui, effectivement si vous n'attendez pas c'est plus dur. J'ai regarde les vitesses de spawn dans les videos, et j'ai ajuste un petit peu (ca semble un peu trop rapide actuellement).
