### ISSUE TITLE
bug dépôt hôtel des ventes

### ISSUE THREAD

**Issue by Dierckens** [way-of-elendil/3.3.5#171]
Bonjour, 
la somme du dépôt de l’hôtel des ventes n'est pas cinq fois inférieur à celui indiqué.
Je suis prélevé de la totalité de la somme.

**Comment by Endalaust** [comment]
Pour rappel @joshwhedon il s'agissait d'une conf custom qu'on avait mis en place lorsqu'on a démocratisé les commissaires priseurs à Dalaran pour cause de : 

Les hdv interfaction tenus par les gobelins ont une taxe très elevée contrairement aux hdvs de faction qui ont une taxe classique. 

Le patch mis à l'époque était factuel et pas visuel (on voyait 100% de la taxe mais on subissait 20% de la taxe)

Je suppose que cette conf a du sauter

**Comment by Endalaust** [comment]
https://wowwiki.fandom.com/wiki/Formulas:Auction_House
On est visiblement repassé sur la config neutral au lieu de la config factioned : 

     In factioned houses: 

`Cut = 0.05 * Winning Bid`

    In the neutral house: 

`Cut = 0.15 * Winning Bid`

**Comment by Dierckens** [comment]
c'est pas un bug alors ça va rester comme ça?

**Comment by Endalaust** [comment]
C'est pas un bug non.
En revanche sur l'ancien core on avait quand même fait la modification pour passer le cut sur x0.05, du coup ca porte à confusion ;) 

Cette valeur va être réappliquée sur le nouveau core dés qu'un dev aura pris en charge le ticket.

**Comment by Dierckens** [comment]
je comprend merci :)
