### ISSUE TITLE
Boss: Gormok l’Empaleur

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#172]
**Description**
À la fin du combat contre Gormok l’Empaleur, les vassaux qui sont restés sur son dos partent derrière les portes et disparaissent

**Comportement attendu**
S'ils sont encore en vie /sur le dos du boss, ils doivent continuer/rejoindre le combat 

https://www.youtube.com/watch?v=MMmLcQuxQfE

**Comment by Killyana** [comment]
Tu veux dire Gormok l’Empaleur ?
