### ISSUE TITLE
Chaîne de glaçe Dk Bug animation 

### ISSUE THREAD

**Issue by Shavokx** [way-of-elendil/3.3.5#173]
**Description**
- Le problème avant la chaîne de glace quand on la met sur l'ennemi y'avais pas l'effet dégressive.
-La cible rester slow à 95% pendant 10 seconde.
- Maintenant que le problème est soit disant régler on à trouver un problème d'affichage quand tu chaîne de glace la cible et elle bouge tu la vois bugé et faire des aller retour en dirais elle lag alors que c'est pas le cas.
 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe Chevalier de la mort
- Race Orc
- Spécialisation Impie
- Sort / Talent / Etc Chaîne de glaçe 
- Circonstances PvP
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**

-L'animation soit correct

**Captures d’écran / Vidéos**
https://youtu.be/I0goxjH2_CU

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Je sais pas si ca va etre corrigible :(

**Comment by Shavokx** [comment]
:'( en soit c'est pas vraiment un problème mais crois moi que en Aréna ça va être chiant :x 
Mais c'est grave si c'est pas corrigè t'on que le sort marche et fait le dégressive c nickel.

**Comment by joshwhedon** [comment]
A moins que Trinity corrige le probleme (lie a la mise a jour visuelle des mouvements) le probleme ne sera pas corrige.
