### ISSUE TITLE
Nexus : Bug aggro âme en peine de mana affolée

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#174]
**Description**
les âme en peine de mana affolée qui pop via les failles chaotiques nous aggro que que soit notre place dans la salle.

**Étapes de reproduction**
Aller dans le nexus dans la partie avant anomalus et attendre que les âmes vienne nous taper.

**Comment by Killyana** [comment]
Pas un bug, il faut détruire la faille qui spawn les âmes.
