### ISSUE TITLE
Boss: Anub'Rekhan

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#175]
**Description**
Entry: 15956.
Il est vers Stratholme (hors instance)
Position: 3308.590088 -3476.290039 287.161011.

Je l'ai tué, pas pu le respawn

**Comment by Killyana** [comment]
Avoir aprés le reboot
.go xyz 3308.049561, -3459.5214, 134.070084 0

**Comment by joshwhedon** [comment]
Il est plus la, peut etre a cause des grids :(.
