### ISSUE TITLE
Dk poing de la mort ou mage bloc de glaçe

### ISSUE THREAD

**Issue by Shavokx** [way-of-elendil/3.3.5#179]
**Description**
-En dk quand tu lance t'a poing de la mort sur un mage si il block instant il restera au cast et si il bloc un peu en retard il serra au CAC en gros (il serra placé au cac ce qui est logic).
-Le problème maintenant c quand tu grippe un mage (poing de la mort) et il bloc au milieux genre entre le cac et le cast y'a une animation chelou et il bouge pas de ça place  (cast) à la fin, alors que ça devrait pas faire ça , en gros résumé  si le mage à pas le reflex de bloc instantanément il restera jamais au cast  il serra placè instantanément au cac.
Bloc ==> Bloc de glaçe
Grippe ==> poing de la mort
-Je sais pas si le problème Vien du (poing de la mort) Du dk où (Bloc de glaçe) Du mage.
**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe Dk/Mage 
- Race Orc 
- Spécialisation Impie/Givre
- Sort / Talent / Etc  Bloc de glaçe ou poing de la mort.
- Circonstances PvP
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Si le mage bloc de glaçe instantanément il restera au cast et si il tard à lancé le sort il serra Bloc en cac.

**Captures d’écran / Vidéos**
Malheureusement j'ai chercher des vidéo pas trouver 

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Tu as des sources offi, video / guide / etc indiquant le comportement attendu ?

**Comment by joshwhedon** [comment]
Aucune information supplementaire n'a pu etre trouvee. Merci de reouvrir le bug avec le comportement sur officiel si vous en trouvez.
