### ISSUE TITLE
NPC: Hira Aubeneige

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#180]
**Description**
Il est dans la faction 35

**Comportement attendu**
faction 1090

**Ressources additionnelles**
https://fr.wowhead.com/npc=31238/hira-aubeneige

**Comment by Killyana** [comment]
Pas un bug, faction changer probablement sous cata+
https://fr.wowhead.com/npc=31238/hira-aubeneige#comments
sniffs: [29] UNIT_FIELD_FACTIONTEMPLATE: 35/4.904545E-44 (35)
