### ISSUE TITLE
Problème devant Ogrimmar

### ISSUE THREAD

**Issue by Morkoving** [way-of-elendil/3.3.5#181]
**Description**
Devant Ogrimmar ont trouve des Boissons et de la bouffe des moissons qui volent

**Étapes de reproduction**
Allez devant Ogrimmar

**Comportement attendu**
Que sa soit a la bonne période (généralement avec des tables et des chaises pour qu'ont puissent manger en étant bien installer)

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.
![20200406184425_1](https://user-images.githubusercontent.com/63253336/78583204-c8c2d400-7836-11ea-9d3b-e79313bd7b7a.jpg)

**Comment by Killyana** [comment]
C'est fixé, Merci
