### ISSUE TITLE
Quest: Une course contre la montre

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#182]
**Description**
Quest 11671
Lancer la bombe ne fait pas descendre le npc 25584.
Elle crie son dialogue mais reste inattaquable et continue ses affaires

Bonus : Le gob reste après avoir fouillé dedans (il partait après avoir fouillé sur la version précédente)

**Comment by Killyana** [comment]
A passé une fois, sql d'origine corrigé.
``` sql
UPDATE `smart_scripts` SET `action_param3`=1 WHERE `entryorguid`=25584 AND `source_type`=0 AND `id`=2;
```
On va probablement avoir d'autre cas similaires ou une action_list ne peut override une autre qui est en cours, dans ce cas il faut ajouter `action_param3`=1  à l'action_list qui doit interrompre la 1ere

**Comment by Killyana** [comment]
Pour le coffre oui il doit rester spawn pour la durée de l'invocation 1.25m: https://woehead.way-of-elendil.fr/?spell=45809

**Comment by Killyana** [comment]
Fixé
