### ISSUE TITLE
La porte de la Baronne Anastari (Stratholme)

### ISSUE THREAD

**Issue by Flocapa** [way-of-elendil/3.3.5#184]
**Description**
Dans stratholme (maleterres de l'est), la porte de la ziggourat derrière le boss "Baronne Anastari" ne s'ouvre pas après sa mort, et empêche donc l'ouverture de la grille de la dernière salle du donjon juste avant le baron vaillefendre. Les 2 autres ziggourat et leurs boss fonctionne normalement.

**Étapes de reproduction**
- Stratholme (maleterres de l'est, coté baron)
- mode normal
- Boss : Baronne Anastari
- A la mort du boss
- Peu importe la taille ou la constitution du groupe

**Comportement attendu**
A la mort du boss, la porte derrière lui est censée s'ouvrir. Et donc si les 3 boss sont morts (la baronne anastari, nerub'enkan et maleki le blafard) la grille finale devant la salle du baron devrait s'ouvrir.

**Comment by Flocapa** [comment]
je précise qu'on a tester plusieurs fois avec des persos différent et faisant des reset de donjon mais aussi en quittant et relançant le jeu

**Comment by Ischjgt** [comment]
Navré, j'ai report en premier B)
