### ISSUE TITLE
Jugement des sages paladin regen même sous absorb

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#185]
**Description**
Le talent "Jugement des sages" du paladin regen la mana du paladin même si le jugement est absorbé

**Étapes de reproduction**
Prenez un paladin ret et un priest discipline. Mettez un jugement sur le prêtre qui a son bouclier sur lui. 

**Comportement attendu**
Seulement les jugements faisant des dégâts permettent la regen du paladin, les absorbs ne le font pas proc.

**Ressources additionnelles**
https://wotlk-twinhead.twinstar.cz/?spell=31876
https://www.mmo-champion.com/threads/661051-Judgments-of-the-Wise-bugged
"One possible explanation is this, if your judgment is absorbed or does no damage to the darget, replenishment does not proc. so if your judgments are getting absorbed for some reason or just not doing any damage you will not gain the replenishment effect. This seems to happen frequently in PvP situations for instance. "

**Comment by Justforsoloq** [comment]
https://www.youtube.com/watch?v=YQyq2X7I2lM (vidéo retail tlk de l'époque)
10mn10s-10mn12s (tehseus juge un rogue sous shield, le shield ne casse pas et donc absorbe le jugement, aucun mana n'est rendu).

**Comment by joshwhedon** [comment]
Deux questions:
- Est-ce que c'est nouveau ?
- Le commentaire parle uniquement de replenishment. Donc c'est pas la regen du jugement des sages le probleme, c'est juste le proc de replenishment ?

**Comment by Justforsoloq** [comment]
Non ce n'est pas nouveau, le bug existait sur l'ancien core, mais vu qu'il y avait le merge je n'ai pas pris la peine de le report. 
J'ai link une vidéo montrant une preuve visuelle de l'époque.

**Comment by joshwhedon** [comment]
Bon ca m'aura pris 3 heures, mais c'est corrige prochaine maj normalement. Ca m'a permis de debug un peu le systeme de proc qui a d'autres problemes depuis le merge.
