### ISSUE TITLE
Spell: Salve de guérison

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#188]
**Description**
Spell ID 
1064
10622
10623
25422
25423
55458
55459

Actuellement, le sort ne rebondit pas sur d'autres alliés si la cible n'est pas dans le même groupe

Comportement attendu :
Rend 1055 - 1205 points de vie à la cible alliée, puis soigne d'autres alliés proches. Si le sort est lancé sur un membre du groupe, il ne soignera que des membres du groupe. Chaque nouveau soin perd 40% d'efficacité. Soigne 3 cibles au total.

La condition ne s'applique que si la target est dans le même groupe, elle ne s'applique pas dans un autre cas

**Comment by joshwhedon** [comment]
Le sort rebondit mais uniquement si les cible a des degats. Je corrige ca pour que le sort rebondisse sur une cible meme si perosnne n'a de degats.
