### ISSUE TITLE
tuyaux dans icc

### ISSUE THREAD

**Issue by zolkon369** [way-of-elendil/3.3.5#189]
Dans icc, je ne vois  les tuyaux pour activer l'event du prof putricide je peux donc accéder à la salle car la porte n’apparaît pas non plus sans pour autant pouvoir le pull .Je ne suis pas le seulà avoir ce bug cependant certains ne l'ont pas mon pseudo est Azelys si jamais ça a une utilité

**Comment by joshwhedon** [comment]
Desole ce n'est pas tout a fait clair. Tu parles de quels tuyaux ? Tu parle des valves dans les salles adjacentes qu'il faut ouvrir pour ouvrir la porte de putricide ?
