### ISSUE TITLE
Utility: Personnage coince

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/3.3.5#19]
**Description**

Soucis avec l'utilisation de Demande d'assitance => Personnage coincé en étant mort, en effet cette utilisation devrait pouvoir nous amener au gardien d'âme le plus proche afin de pouvoir faire le mal de rez si le corps est impossible à récupérer. Pour le moment, l'incantation se fait mais une fois terminée rien ne se passe.

En étant en vie, l'utilisation fonctionne et nous envoie à l'auberge où la pierre de foyer est mise.

**Étapes de reproduction**
Mourrir
Utiliser la fonction personnage coince

**Comportement attendu**
Devrait etre envoye au cimetiere.

**Captures d’écran / Vidéos**

**Ressources additionnelles**

**Comment by Killyana** [comment]
En étant fantôme le déblocage ne doit pas res ou appliqué une baisse de la durabilité du stuff, mais jute TP le joueur à la cimetière (toujours sous forme de fantôme).
Actuellement le tp après le débloquer nécessite une decoreco.

Et en étant vivant sa doit TP le joueur qq mètres en avant au lieu de l'envoyer à l'auberge.
