### ISSUE TITLE
proc flask multiple spé flask

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#191]
comme dans le titre l'annonce le fais de proc des potion supplémentaire en spécialisation potion semple marcher; par contre le proc de flacon supplémentaire en spécialisation flacon ne semble pas marcher -> j'ai fais + de 50/60 craft flacon et pas 1 seule fois ça à proc multiple en étant spécialisation flacon (ce qui est très rare sur + de 60 craft); j'ai demandé à d'autres sur l'inter je n'ai eu aucune réponse sauf d'une personne mais qui n'a pas craft de flacon aujourd'hui pourriez-vous vérifier ?

Craft des flask supplémentaire en spécialisation flask (métier alchimie)

Merci par avance

**Comment by joshwhedon** [comment]
Un membre de l'equipe a teste sur son joueur, sur 10 crafts il a eu 3 procs, t'as vraiment pas eu de chance (ou bien t'as pas la specialisation flacon et tu mens :D ).
