### ISSUE TITLE
Les princes icc

### ISSUE THREAD

**Issue by zolkon369** [way-of-elendil/3.3.5#192]
Rebonjour, c'est encore moi, juste pour signaler que sur les princes les 2 qui n'ont pas d'aggro  sont insensibles aux taunts et ont une aggro aléatoire qui fait que les 2 qui sont à 1 point de vie se promènent et tuent des gens au hasard dans la salle

**Comment by joshwhedon** [comment]
Duplication de https://github.com/way-of-elendil/3.3.5/issues/193
