### ISSUE TITLE
[CHASSEUR] Sort "détournement"

### ISSUE THREAD

**Issue by Subimase** [way-of-elendil/3.3.5#195]
**Description**
Il est arrivé qu'en raid le sort "détournement" soit demeuré inutilisable.
La case du sort s'est grisée, rendant le sort inutilisable. Seule une déco reco ou un /reload a permis de la dégriser et de rendre utilisable le sort. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe : CHASSEUR
- Race : DRANEI
- Spécialisation : PRECISION
- Sort / Talent / Etc : DETOURNEMENT
- Buffs / Debuffs / Enchaînement de sort / Etc : Détournement sur macro

**Comportement attendu**
La case est censée restée dégrisée et le sort disponible une fois le temps de rechargement terminé. 

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre : NON REALISE

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc : 
- ID SPELL : https://fr.wowhead.com/spell=34477/d%C3%A9tournement (SPELL ID : 34477).

A vérifier si le buff est reproductible avec la ficelle des métiers, certains consommables en plein combat, etc...

**Comment by joshwhedon** [comment]
Ca arrive souvent ? Est-ce que ca arrivait avant la mise a jour recente aussi ?

**Comment by Ischjgt** [comment]
Ça n'arrivait pas si je ne dis pas de bêtises

**Comment by Subimase** [comment]
Bonjour, ça n'arrivait pas sur WoE. Mais je l'ai perçue deux fois en raid hier soir (en 2 heures de jeu). C'est juste un détail de jeu. 

Je l'ai retesté à Dalaran sans être en raid, une trentaine de fois, cette situation ne s'est pas présentée.

**Comment by joshwhedon** [comment]
On dirait exactement le meme soucis qui est signale de temps en temps avec la forme d'ombre / ficelles du metier.

**Comment by joshwhedon** [comment]
Je mets un correctif pour la prochaine mise a jour, il faudra me dire si ca regle le probleme.

**Comment by Subimase** [comment]
https://www.zupimages.net/viewer.php?id=20/16/alrm.jpg

Bug reproduit le 10 avril 2020.

**Comment by joshwhedon** [comment]
En meme temps j'ai commente hier que je mettais un correctif donc oui le 10 avril ca arrivait probablement encore :D .
