### ISSUE TITLE
Quête Rallier les troupes

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#197]
L'utilisation de https://fr.wowhead.com/item=36764/%C3%A9clat-de-la-terre sur les Géant des grisonnes 26261 n'est pas comptabilisé pour la quête https://fr.wowhead.com/quest=12070/rallier-les-troupes

**Comment by Killyana** [comment]
Je ne sais pas pourquoi le target 7 ne fonctionne pas dans ce cas avec l'action 33
On a corrigé ça en 2016 avec:
``` sql
UPDATE `smart_scripts` SET `target_type`=18, `target_param1`=16 WHERE `entryorguid`=2626100 AND `source_type`=9 AND `id`=0;
