### ISSUE TITLE
Dévoreur d'âmes / Forge des âmes

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#199]
Le dernier boss de forge des âmes : Dévoreur d'âme https://fr.wowhead.com/npc=36502/d%C3%A9voreur-d%C3%A2mes#abilities 
Soucis au niveau du sort https://fr.wowhead.com/spell=69051/ame-r%C3%A9fl%C3%A9chie qui ne renvoie pas les dégât sur la cible.

**Comment by joshwhedon** [comment]
A ete teste, 45% des degats infliges sont renvoyes sur la cible.
