### ISSUE TITLE
[arène 2v2] Victoire non comptabilisées

### ISSUE THREAD

**Issue by dirsang** [way-of-elendil/3.3.5#200]
**Description**
Nous avons fait 2 matchs d'arène 2V2 : dirsang(moi) avec vaccumdias contre shaman et arzualem et les matchs n'ont pas été comptabilisés ni pour les vainqueurs ni pour les perdants.

**Étapes de reproduction**
- Arène, teste avec nagrand et une autre
- bug remarqué chez les hordeux et allianceux

**Comportement attendu**
Notre équipe aurait du avoir 2 victoires, et l'équipes de Shaman et Arzualem aurait du avoir 2 défaites

**Comment by Ischjgt** [comment]
2 teams ont tag à l'instant où je te parle et les gagnants ont bien reçus leur cote.
Vous partageriez pas la même IP par hasard?

**Comment by Ischjgt** [comment]
Je me suis permis de vérifier, c'est le cas, 2 adversaires ayant la même IP peuvent s'affronter en arène mais verront leurs matchs comptés "pour du beurre"
