### ISSUE TITLE
Bug flaque putri icc 25H

### ISSUE THREAD

**Issue by dirsang** [way-of-elendil/3.3.5#201]
**Description**
Nous avons essayés à 2 reprises de faire Putricide ce soir en 25H mais les personnes dans l'abomination n'arrivaient pas à boire les flaques, paltemps a essayé en premier il n'a pu en boire aucune, et une autre personne a pris l'abomination suivante, elle a bu boire quelques flaques puis impossible après.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Raid Citadelle de la Couronne de Glace
- 25 Héroique
- Putricide
- Phase 1 flaque qui pop au sol et qui sont à boire par l'abomination
- exemple : paltemps, vaccumdias, ankshunamon, zerkham et bien d'autres

**Comportement attendu**
L'abomination aurait du pouvoir boire toutes les flaques.

**Comment by Blackhorns-woe** [comment]
Nous avons eu le même soucis en ICC 25 NM.
Les flaques grossissaient plus vite qu'on ne pouvait les boire.

**Comment by joshwhedon** [comment]
Aujourd'hui ? Vous n'arrivez pas a utiliser les sorts de l'abomination ? Ou bien les flagues grossissent trop vite ?

**Comment by Mugiino** [comment]
J'ai testé le boss aujourd'hui en 10NM, on pouvait boire les flaques normalement, aucun bug rencontré, on a passé le boss tranquillement.
