### ISSUE TITLE
Un départ amer 12832

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#202]
La quête prise par https://fr.wowhead.com/npc=29434/mineur-gobelin-bless%C3%A9 
Le soucis vient du fait que si le pnj passe en premier et aggro les mobs tout va bien, on l'aide à tuer puis on poursuit. En revanche si l'aggro est fait par le joueur, le pnj ne vient pas aider et poursuit sa route tout seul, il est alors perdu pour la quête.

**Comment by Killyana** [comment]
C'est pas un nouveau bug, le pnj utilise FACTION_ESCORTEE_N_NEUTRAL_PASSIVE durant l'escorte se qui est faut, je vais récrire la quête en sai quand j'aurais du temps

**Comment by joshwhedon** [comment]
Corrige prochaine maj
