### ISSUE TITLE
EDC 25N Anub'arak

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#203]
**Description**
A la deuxième phase ou anub rentre dans le sol et poursuit qqn avec ses pics , il ne poursuis personne. On a eu uniquement les scarabées et pas les pointes d'anub.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- épreuve du croisé
- 25n
- anub'arak
- 2ème poursuite de anub'arak 

**Comportement attendu**
le boss est sensé target qqn et lui foncé dessus avec ses pics.

**Comment by Fairivier** [comment]
edit sur un 2eme try ca nous l'a pas refait donc jsp ce qu'il c'est passé tout a l'heure

**Comment by joshwhedon** [comment]
Merci je jette un oeil, on a pas pu reproduire non plus. Je vais mettre quelques changements pour voir si ca corrige.
Tu peux me dire si il y avait les pics (avec l'animation de sol) qui ne bougeaient pas ou bien rien du tout ?

**Comment by Fairivier** [comment]
On ne voyait pas du tout les pics

**Comment by joshwhedon** [comment]
Merci :) .

**Comment by joshwhedon** [comment]
Un correctif sera mis en place prochaine mise a jour, mais etant donne que je n'arrive pas a reproduire le soucis faudra voir si ca le corrige.
