### ISSUE TITLE
[Mammouth de Voyage] Impossible de transporter des joueurs

### ISSUE THREAD

**Issue by KokirisWoe** [way-of-elendil/3.3.5#204]
**Description**
https://www.wowhead.com/item=44235/reins-of-the-travelers-tundra-mammoth#sold-by
La monture devient une monture normale après avoir passé un voyage rapide ( Bateau Baie-du-butin ) Il est donc impossible de transporter des joueurs. Les vendeurs disparaissent aussi.
Toutefois, la monture redevient normal après un dismount 

**Étapes de reproduction**
Avoir deux personnages en même temps. Prendre le bateau du Baie-du butin en étant sur la monture ( Les deux joueurs )

**Comment by Killyana** [comment]
Il est possible que ce soit de même sur offi: https://github.com/TrinityCore/TrinityCore/issues/4903

**Comment by joshwhedon** [comment]
Bug blizzlike a premiere vue.
