### ISSUE TITLE
[Minage/Herboriste] Forcer l'incrémentation point de compétence

### ISSUE THREAD

**Issue by KokirisWoe** [way-of-elendil/3.3.5#205]
**Description**
Il est possible de forcer l'incrémentation d'un point de compétence après avoir pioché/cueillis un filon ou une plante. Il suffit de ne pas loot les plantes ou les minerais et de retenter la cueillette. 

**Étapes de reproduction**

-Avoir appris le métier Herboriste ou Minage
-Chercher une plante de son niveau 
-Cueillir la plante ou le filon ( Ouvrir seulement le Gameobject )
-Ne pas loot les objets
-Cueillir de nouveau 
-Refaire jusqu'a l'obtention du point de compétence

**Comment by joshwhedon** [comment]
Merci d'avoir signale, mais j'ai teste et pas pu reproduire le probleme. Peut etre que le probleme a ete regle depuis.
