### ISSUE TITLE
Vol

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#208]
**Description**
Démonter de sa monture volante en touchant l'eau. Impossible d'utiliser sa monture volante avec les pieds dans l'eau (sans être en nage).

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
Outreterre (non testé en northrend)

**Comportement attendu**
Pas de dismount. Possibilité d'utiliser sa monture volante avec les pieds dans l'eau.

**Comment by joshwhedon** [comment]
Ca depend des zones et des maps. J'ai teste dans les zones d'eau ou il y a peu d'eau, on peut marcher en monture volante. Par contre des que c'est un peu plus profond non.

**Comment by Killyana** [comment]
On essai de corriger ça sur TC ainsi que le comportement des mobs dans les eaux peut profonde.

**Comment by joshwhedon** [comment]
Cool merci bon a savoir.
