### ISSUE TITLE
Paladin, supplique divine

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#209]
**Description**
Les auto-attaques du paladin refresh le cooldown actif de la supplique divine. Si le paladin attaque pendant 3 min, la supplique divine durera 3 min.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Paladin
- Elfe de sang
- Protection
- Supplique divine
- Outreterre, bénédiction du sanctuaire, fureur vertueuse, sceau de sagesse. (non testé sans)

**Comportement attendu**
La supplique divine n'est pas refresh par les auto-attaques.

**Comment by Ischjgt** [comment]
Je suppose que tu as ce talent
https://woehead.way-of-elendil.fr/?spell=53585
