### ISSUE TITLE
Paladin, vol

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#210]
**Description**
Possible de lancer n'importe quel sort/bijou en vol. Ce qui fait dismout.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Paladin
- elfe de sang
- protection
- supplique divine, bijou activable, tempête divine
- outreterre
 
Le bug ne se produit pas sur mage

**Comportement attendu**
Pas de dismount, et sort non utilisable avec le message "vous êtes sur une monture".

**Comment by joshwhedon** [comment]
Heu, t'as pas un addon qui fait que tu dismount quand tu essaie d'utiliser un sort ? Moi tous les sorts ca me dit : Vous etes sur une monture. En paladin aussi.

**Comment by joshwhedon** [comment]
On me dit que c'est dans les configs d'interface :) .
