### ISSUE TITLE
Donjon fosse de Saron / quête "Le chemin de la citadelle" (quest=24507) coté Horde.

### ISSUE THREAD

**Issue by blizzwolf** [way-of-elendil/3.3.5#211]
le PNJ Gorkun crâne-de-fer est présent mais ne propose pas de rendre la quête [24507] =Le chemin de la citadelle. suite de quête cassée. 
dans tous les modes de jeu :  Hm et Nm

-lien wowhead de la quête :
https://fr.wowhead.com/quest=24507/le-chemin-de-la-citadelle
-lien wowhead du pnj : 
https://fr.wowhead.com/npc=37592/gorkun-cr%C3%A2ne-de-fer

**Comment by Killyana** [comment]
C'est pas celui qui est spawn mais celui qui apparaît quand le 1er boss Forgemaster Garfrost est tué.

**Comment by blizzwolf** [comment]
oui je sais bien j'ai 6 perso lvl 80 ^^ . mais il dit rien du tout celui en bas de l'escalier... pas normal, on devrait pouvoir lui rendre la quête.

**Comment by Killyana** [comment]
Il apparaît comme le pnj ally qu'on voit la https://youtu.be/DRDp9PQ_-0Y?t=858

**Comment by Killyana** [comment]
J'ai compris les quêtes ne sont assignés aux bon npcs, aussi les npc qui sont invoqués ne sont pas les bons.
Je corrigerais ca quand j'aurais du temps:
``` sql
SELECT * FROM `creature_template` WHERE `entry` IN (37581,37618,   37591, 37606,   37592,37607,  37580,37614);

**Comment by blizzwolf** [comment]
merci ^^

**Comment by joshwhedon** [comment]
Pas mal de joueurs se plaignent de ce bug Eridium :( .

**Comment by Killyana** [comment]
Il faut oublié l’interaction, si le joueur entre dans une instance qui n'est pas celle de sa faction il pourra pas rendre la quête, ça c'est pas nouveau.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/d0f9ace67970f51bd1e9fb153a0844555f2b1ca2

**Comment by blizzwolf** [comment]
Le pnj est présent mais au début de l instance pas ou il devrait se
trouver. Il se trouve à proximité de fosse au départ.
