### ISSUE TITLE
[NPC : 18484 -marchand-des-vents-lathrai] Patrons à vendre

### ISSUE THREAD

**Issue by Subimase** [way-of-elendil/3.3.5#212]
**Description**
Le marchand des vents Latrai à Shattrah ne semble pas vendre les patrons suivants : 
Schéma : Fumigène blanc : https://fr.wowhead.com/item=23811/sch%C3%A9ma-fumig%C3%A8ne-blanc (ID : 23811)
Schéma : Boîte à outils en gangrefer : https://fr.wowhead.com/item=23816/sch%C3%A9ma-bo%C3%AEte-%C3%A0-outils-en-gangrefer (ID : 23816)

**Comportement attendu**
Être 335 en ingénieurie (conformément au guide up ingé 1 à 450 suivant : https://esk.xooit.fr/t2286-Monter-l-ingenierie-de-1-a-450.htm 

**Captures d’écran / Vidéos**
https://www.zupimages.net/viewer.php?id=20/15/z4ii.jpg
https://www.zupimages.net/viewer.php?id=20/15/lh0e.jpg

**Ressources additionnelles**
Lien WoWhead du NPC : https://fr.wowhead.com/npc=18484/marchand-des-vents-lathrai (l'ensemble des schéma et compos vendus sont inscrites sur ce lien).
Schéma : Fumigène blanc : https://fr.wowhead.com/item=23811/sch%C3%A9ma-fumig%C3%A8ne-blanc (ID : 23811)
Schéma : Boîte à outils en gangrefer : https://fr.wowhead.com/item=23816/sch%C3%A9ma-bo%C3%AEte-%C3%A0-outils-en-gangrefer (ID : 23816)

**Comment by Endalaust** [comment]
Il les vend, en revanche c'est par lot de 1 dans le temps. 
Je te suggère de lire les commentaires sur le wowhead à propos de ce PNJ
Comportement ISO avec Elendil, un autre joueur est passé avant toi

**Comment by Subimase** [comment]
Effectivement ! My bad ! 

Je pensais que la recette devenait rouge mais restait affiché in game ! 

Merci pour ton retour Endalaust!
