### ISSUE TITLE
Instance: Pic rochenoire

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#213]
**Description**
Tuer Rend (10429) dans le stade n'ouvre pas 
[Doodad_PortcullisActive01] GUID: 87845 ID: 164726
et 
[Doodad_Portcullis_TOBOSSROOMS] GUID: 87844 ID: 175186

**Comment by Killyana** [comment]
Y'a un possible fix ici: https://github.com/TrinityCore/TrinityCore/issues/15583

**Comment by joshwhedon** [comment]
Le probleme c'est que Victor doit faire un speech et ouvrir les portes, mais pour une raison que j'ignore encore il le fait pas.
