### ISSUE TITLE
[Quête] Impossible de finir la quête "La lumière de l'aube" de dk pour sortir de la zone de départ

### ISSUE THREAD

**Issue by AliceAlbano** [way-of-elendil/3.3.5#214]
**Description**
J'ai pu lancer la quête "la lumière de l'aube", lancer la bataille. Mais une fois que Tyrion est apparu il a emprisonné les généraux, et puis plus rien. Je ne peux pas rendre la quête, et l'abandonner pour la recommencer ne change rien. Ce bug empêche de sortir de la zone de départ des death knight

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Dans la zone de départ des death knight
- Classe du personnage utilise : death knigth gnome femme
- Nom de la quête : la lumière de l'aube
- Nom du donneur de quête : le généralissime darion mograine

**Comportement attendu**
Une fois la bataille fini, impossible de rendre la quête à quelqu'un

**Captures d’écran / Vidéos**
![WoWScrnShot_040720_115419](https://user-images.githubusercontent.com/7228239/78655738-b4c6b300-78c6-11ea-8b1e-885696c23db6.jpg)
![WoWScrnShot_040720_115425](https://user-images.githubusercontent.com/7228239/78655740-b5f7e000-78c6-11ea-9ab2-b58d8607ffd5.jpg)

**Ressources additionnelles**
Il s'agit de cette quête : https://fr.wowhead.com/quest=12801/la-lumi%C3%A8re-de-l-aube#news

**Comment by Ischjgt** [comment]
Note: ça n'arrive pas tout le temps, quelqu'un a reussi à faire la quête hier

**Comment by joshwhedon** [comment]
Vous etiez loin de Darion ? Il faut participer a l'event en etant suffisament proche de lui pour que ca compte.

**Comment by Ischjgt** [comment]
Je pense que c'est parce qu'il est mort, aussi il se passe des trucs étranges pendant l'event mais c'est pas facile à voir

**Comment by joshwhedon** [comment]
Je pense pas qu'il puisse mourir.

**Comment by AliceAlbano** [comment]
La première fois que j'ai essayé, je suis restée très près de lui mais toutes les attaques me one shot donc j'ai du ressuciter plusieurs fois

**Comment by Ischjgt** [comment]
Je pense que le sort ne fait pas assez de dégats, comparé à ses AA
Chancre impie |2 Généralissime Darion Mograine touche Défenseur de la Lumière pour 860 (Ombre).

**Comment by Killyana** [comment]
Je pense pas que le joueur peut mourir dans cette quête

**Comment by ripredz** [comment]
Même constat ici. L'event se lance, se termine. Les PNJs se placent devant l'église, papotent, puis Darion Mograine disparaît, et l'event s'arrête.
J'ai essayé d'abandonner la quête, de recommencer, mais on est comme coincé dans la phase, le PNJ ne revient pas.

J'ai reco après plusieurs, et forcé de constaté que nous étions 3 bloqué devant l'église avec le même problème...

J'ai ouvert une requête IG si jamais une âme charitable veut bien me valider la quête (Cévé, Humain DK)

Merci !

**Comment by Ischjgt** [comment]
1. 29174 qui utilise 53643 sur les joueurs alors que ça ne devrait être que sur les morts-vivants.
2. Du coup ça m'a OS et la quête n'a pas été validée alors que je n'ai pas libéré, en fait dans ce cas où le joueur meurt, l'event s'arrête quand tous les morts vivants sont morts et le speech de fin n'apparait pas

**Comment by joshwhedon** [comment]
Ok je vais faire un script pour ce sort.

**Comment by Asterie-elendil** [comment]
je viens d'avoir des informations, d'après Ischjgt, il y aurai un soucis avec le buff de darion.
De plus, un joueur me dit qu'il y a un drapeau qui donne un buff mais dès que le joueur prend 1 point de dégât le drapeau dépop et du coup le joueur meure (souvent à cause du tauren)
La bataille malgrès tout continue. Et au bout d'un moment (peu importe le nombre de fois où tu meures) les mobs arrive devant la chapelle et puis plus rien.
Le chef de l'alliance dépop et le roi liche ne fait rien
