### ISSUE TITLE
Spell: Tranchant crépusculaire Halion

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#215]
**Description**
Testé en 25NM et 25HM

EDIT: L'animation du spell n'est pas correctement liée avec la  zone de dégats, la zone de dégats ne bouge pas du tout tandis que l'animation oui
dès la phase 2 jusqu'à la fin

**Comment by joshwhedon** [comment]
J'ai un fixe, c'est pas super joli niveau animation, mais ca marche.
