### ISSUE TITLE
Bug Aura "marché de lok' lira" bug lorsque l'on rend certaines quêtes de la zone.

### ISSUE THREAD

**Issue by blizzwolf** [way-of-elendil/3.3.5#216]
zone Brunnhildar, Suite de quêtes des fils d'Hodir : 

Lorsque l'on rend plusieurs quêtes dans la zone, l'aura "marché de lok'lira " (https://fr.wowhead.com/spell=72914/march%C3%A9-de-loklira) qui nous rend amical auprès des pnj de la zone,  se retire spontanément.
Notamment, celles relatives aux PNJ : 
- Brijana (https://fr.wowhead.com/npc=29592/brijana) et Cros de glace (https://fr.wowhead.com/npc=29598/croc-de-glace)
- lok'lira la mégère (https://fr.wowhead.com/npc=29975/loklira-la-m%C3%A9g%C3%A8re)

**Comment by Killyana** [comment]
Le fix doit être fait coté core: https://github.com/TrinityCore/TrinityCore/issues/24408

**Comment by blizzwolf** [comment]
ok. en attente de Trinity alors.. bon courage a vous.

**Comment by Killyana** [comment]
Y'a aucun blocage coté quêtes, il suffit de sortir et revenir à la zone pour chopper le déguisement et continué.

**Comment by joshwhedon** [comment]
C'est un nouveau bug ou c'est existant depuis avant ?

**Comment by Killyana** [comment]
Existant depuis des années

**Comment by Ischjgt** [comment]
Euh non, y'a eu une période avec mais me semble que c'est corrigé depuis pas mal de temps

**Comment by blizzwolf** [comment]
Attention je n'ai pas dit que la suite de quête était bugée, juste que maintenant (et ce n’était pas comme ça avant..) l'aura s'enlève quand on rend certaines quêtes de la zone on doit sortir de la zone et revenir pour que l'aura se remette. mais quand on se trouve au centre du village on a l'ensemble des mob sur la tête après avoir rendu une simple quête.

**Comment by joshwhedon** [comment]
J'arrive pas a le reproduire chez nous ce bug :(. C'est avec quelles quetes que c'est reproduisible ?

**Comment by Ischjgt** [comment]
Brisons la glace
