### ISSUE TITLE
[donjon EDC 5 / HM/ Horde] bug moine d'argent, prêtresse d'argent, manieur de lumière attaquent au CAC.

### ISSUE THREAD

**Issue by blizzwolf** [way-of-elendil/3.3.5#218]
[donjon EDC 5/HM/Horde]

Tous les mobs : 
moine d'argent : https://fr.wowhead.com/npc=35305/moine-dargent
prêtresse d'argent : https://fr.wowhead.com/npc=35307/pr%C3%AAtresse-dargent
manieur de lumière ;  https://fr.wowhead.com/npc=35309/manieur-de-lumi%C3%A8re-dargent
(le dernier c'est normal... :-) )
(Il me semble qu'il y a aussi un gnome mage, mais je l'ai pas trouvé sur wowhead.)

Attaquent au corps à corps.

**Comment by joshwhedon** [comment]
Ils sont suppose uniquement lancer des sorts a distance ?

**Comment by joshwhedon** [comment]
Le moine et le manieur doivent melee, la pretre non. Je corrige merci.

**Comment by blizzwolf** [comment]
Ils viennent au cac attaquer à-coup de bâton... 😁

**Comment by blizzwolf** [comment]
Il y avait aussi un mage gnome qui tapait au bâton.
