### ISSUE TITLE
Parrainage: Don de level

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#219]
**Description**
Il semblerait que le don de level de filleul vers parrain ne marche plus

(navré pas test mais j'ai bien vérifié les conditions)

**Comment by Berzerk34** [comment]
Je ne sais pas si cela aidera mais j'ai pu accorder des levels à mon parrain il y a quelques heures à peine.

**Comment by joshwhedon** [comment]
Merci Berzerk, j'ai fait quelques tests de mon cote pas reussi a reproduire le probleme. Il est possible que le parrain soit du meme niveau que le joueur, ou bien que le joueur n'ai plus de niveaux a donner.
