### ISSUE TITLE
Quest: Kaw le destructeur de mammouth

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#220]
**Description**
Ce cas arrive quand Kaw (25802) est vivant mais pas le mammouth (EDIT: et en fait ça arrive vachement souvent et j'ai pas forcément la raison)
S'approcher de Kaw déclenche alors l'event et le NPC reste bloqué au bout du perchoir

**Comment by Killyana** [comment]
Le reset de l'un respawn l'autre, mais y'a un bug qui fait que le respawn ne fonctionne plus, à part ça je vais améliorer le script un peut.

**Comment by joshwhedon** [comment]
Devrait maintenant etre corrige.

**Comment by Ischjgt** [comment]
Je pense que le soucis vient du mammouth

**Comment by Ischjgt** [comment]
Kaw se retrouve également dans cette position (près du ponton, près à sauter sur le mammouth) après un reset combat

**Comment by Killyana** [comment]
Fixé prochaine maj
