### ISSUE TITLE
ICC 25 NM - Sindragosa

### ISSUE THREAD

**Issue by Blackhorns-woe** [way-of-elendil/3.3.5#221]
**Description**
Le souffle de Sindragosa pose un débuff de mouvement sur le tank. Ce souffle se stack pour réduire les mouvements du tank.
Une main de liberté d'un paladin ou une intervention d'un guerrier l'enlève habituellement.
Hier soir, la main de liberté ou l'intervention enlevé le débuff mais ce dernier réapparaissait des que Syndragosa posait ses glaçons en phase d'envol.
Une seconde main de liberté étant nécéssaire pour l'enlever une nouvelle fois.
Malgré cela, le débuff revenait a chaque fois que Sindragosa lançait sa bolt de glace en phase d'envol.

Avant la première phase d'envol le main tank prend 2 souffles, donc 2 débuff de déplacement. Ce débuff est censé reset avec les sorts énoncés au dessus.
Hors hier soir, des le 1er souffle APRES la phase d'envol, le nombre de debuff était de 3. Les 2 de la phase précédente plus le nouveau posé.
Sur la 3eme phase d'envol, le main tank avait 6 debuff qui réduisait sa vitesse de déplacement de 90% (6 x 15%).
En P3, la phase au sol, les debuffs revenait sur le main tank pour le nombre maximum de debuff a chaque nouveau souffle malgré les interventions et main de liberté.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon : ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc) : 25 normal
- Boss Sindragosa
- Sort en question / Phase du boss en question / Emplacement : Souffle de Givre / Phase 1 (Sol et envol et Phase 2 ou elle reste tout le temps au sol.
- Composition du groupe : Main tank War Blackhorns, Tank 2 Saca paladin.

**Comportement attendu**
Le souffle de givre de Sindragosa se retire avec une intervention ou une main de liberté.

**Comment by joshwhedon** [comment]
Est-ce que c'est normal que le souffle se stack cela dit ?

**Comment by Killyana** [comment]
Oui

**Comment by Blackhorns-woe** [comment]
Oui il est normal que le souffle se stack.
Ce qu'il est moins c'est que le souffle de givre revienne sur la phase d'envol ou pendant un autre souffle au nombre de stack avant la béné de liberté ou intervention.

**Comment by joshwhedon** [comment]
A vrai dire, non, la main de liberte ne retire pas le debuff a premiere vue. Elle ne fait que donner que 6 secondes de pause sur le debuff. 
https://www.wowhead.com/forums&topic=173868
"also, when i used hand of freedom...i was only free of the movement impairing effect for the 6 secs of freedom(it doesnt get rid of the debuff for some reason, giving me time to get to the ice tomb to LoS...however when HoF dropped i went back to moving slow and it took forever to get back to sindy"
Donc a premiere vue, je dirai que c'est normal.
