### ISSUE TITLE
Quete le colosse de fer

### ISSUE THREAD

**Issue by zeus332** [way-of-elendil/3.3.5#223]
**Description**
Impossible d'utiliser normalement le mob véhicule pour attaqué le mob ennemi.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Pics foudroyés- plaines des congères
- Horde/Taurren/Chaman
- Nom de la quête : Le colosse de fer
- Nom du donneur de quête : Rochecombe le Sculpteroc

**Comportement attendu**
Nous devrions être capable d'attaquer le mob ennemi et de le battre pour valider la quête en question. 

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.
**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Merci :). Le bug a ete signale ici, je ferme celui ci en attendant que l'autre soit corrige.
https://github.com/way-of-elendil/3.3.5/issues/196
