### ISSUE TITLE
Quete le serment des terrestres

### ISSUE THREAD

**Issue by zeus332** [way-of-elendil/3.3.5#224]
**Description**
C est une quête où il faut tuer plusieurs mobs dans la meme zone. Le décompte ne se fait pas quand ils meurent. Objet de quete fonctionne et les adds aussi. Le noms des mobs à tuer est en anglais dans le journal ainsi que sur le suivi de la map.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Les pics foudroyés- Terrasses des faiseurs
- Horde/ Taurren/Chaman
- Nom de la quête : serment des terrestres
- Nom du donneur de quête : Thorim

**Comportement attendu**
Comme une quete de tuerie, le décompte et la validation d un mob de quête devrait se faire.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Killyana** [comment]
Bug général lié aux nuitées contrôlées:
Entry: 30270.
Active AI: class PetAI
* UNIT_FLAG_PLAYER_CONTROLLED (0x8)
le joueur n'a pas besoin d'entrer en concurrence avec ces pets/gardians pour infliger plus de 50% des dégâts et avoir le kill credit.
J'ai testé même avec un pet chasseur et j'ai pas reçu de crédit.
Le bug existe sur TC

A noté, le gain d’expérience et de reput via le kill nécessite que le joueur inflige au moins un coup à la créature, sa a été fait pour éviter l'xp en étant afk. (Valable en solo seulement)

**Comment by joshwhedon** [comment]
Ok c'est facile a regler ca alors si c'est general. Je mets un correctif demain.

**Comment by joshwhedon** [comment]
@Killyana  c'est pas une question d'unites controlles pour cette quete. Il faut scripter les creatures pour qu'elles donnent le credit (les creatures elles meme ne sont pas l'entry pour le credit).

**Comment by Killyana** [comment]
C'est le cas ils ont un kill Credit, TC utilise la target 7 est sa fonctionne que si le kill est fait par le joueur lui même.
On a fait une modif et mis all units in threat list =24 mais sa fonctionne plus
J'ai testé avec party invoker (target utilisé par blizzard) mais sa prend pas en compte les pets/gardians
``` 
ServerToClient: SMSG_PARTY_KILL_LOG (0x01F5) Length: 16 ConnIdx: 0 Time: 07/17/2010 01:58:33.000 Number: 151695
Player GUID: Full: 0x6000000xxx Type: Player Low: xxxx Name: xxxxxx
Victim GUID: Full: 0xF13000752015F3CA Type: Creature Entry: 29984 Low: 1438666
