### ISSUE TITLE
Boss: Putricide

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#225]
**Description**
Testé en 25HM

Si un rogue utilise disparition quand 37697 ou 37562 le cible, les spell du limon vert et rouge restent sur le rogue mais le limon se dirige vers un autre joueur,
arrivé à l'autre joueur le limon n'explose pas et ne change pas de cible (il le suit jusqu'à mourir ou reinit du boss)

**Comment by joshwhedon** [comment]
Un correctif sera mis, ca a l'air de marcher, mais faudra voir dans la realite, difficile a tester en multicompte.
