### ISSUE TITLE
Boss: Putricide

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#226]
**Description**
Testé en 25HM et seulement sur les limons verts 
"[Sur Putri 25HM le limon vert au lieu de charger sur sa cible a suvi la personne qui avait l'aggro sans jamais "exploser" (il suivait Edhreïn au lieu de la personne ciblée et annoncée par le dbm)] "

J'ai testé, pour ma part, le limon a brièvement continué dans la direction de sa cible précédente puis a changé vers sa nouvelle cible (ce qui pose tout de même soucis)

37697 vert et 37562 orange

**Comment by Mugiino** [comment]
On vient de faire le professeur Putricide en 10NM, les limons ont eu un comportement normal. On a passé le boss sans problème, aucun bug rencontré.

**Comment by joshwhedon** [comment]
Bon, j'ai des correctifs pour, mais c'est quasi impossible a reproduire en local en solo. Faudra me dire.
