### ISSUE TITLE
Quest: Formidable déconfiture dans l'arène

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#227]
**Description**

11300 - [Formidable déconfiture dans l'arène]  

"Je suis actuellement entrain de faire les quêtes du Fjord Hurlant et j'ai un soucis avec "Formidable déconfiture dans l'arène".
Les gladiateurs apparaissent bien mais il faut rapidement les taper pour ne pas qu'ils disparaissent.
Le problème étant que le dernier ne loot pas l'objet que l'on doit récupérer."

C'est un gob : 186640 - [Code antique]

**Comment by Killyana** [comment]
C'est à cause de l'invocation dans npc_daegarn , despawn aprés  3secs ooc
me->SummonCreature(uiEntry, afSummon[0], afSummon[1], afSummon[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30*IN_MILLISECONDS);

**Comment by joshwhedon** [comment]
C'est 30 secondes, normalement y'a le temps de les attaquer en 30 secondes.

**Comment by Killyana** [comment]
Le npc commence à courir vers le joueur puis despawn en 2 secs, il a pas le temps d'entrer en combat. sa se produit avec le 2eme.
Peut être qq chose lié à _summons.Despawn(summon);

**Comment by Ischjgt** [comment]
Hello,
"Le problème étant que le dernier ne loot pas l'objet que l'on doit récupérer.""
Toujours d'actualité

**Comment by joshwhedon** [comment]
@Killyana  j'ai corrige le cpp par contre le spawn du go c'est un sai si tu as le temps de jeter un oeil.

**Comment by Killyana** [comment]
Fixé prochaine maj
