### ISSUE TITLE
BG: Ile des conquérants

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#228]
Faut fermer :)

**Comment by joshwhedon** [comment]
On peut nous dire les bugs avant que je ferme ? Parce que sinon on ouvrira jamais.

**Comment by Ischjgt** [comment]
Les conditions des 3/4 des HFs se valident pas
Les engins de siège sont pas utilisables
La plateforme volante a des soucis
Les cimetières
et j'en passe j'ai pas tout en tête là

et Amandil a dit
"c'est pas la prio"
