### ISSUE TITLE
vers de sang

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#230]
**Description**
Les vers de sangs tapent à ~20.
**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Dk
- Orc
- Sang
- Vers de sang

**Comportement attendu**
Les vers de sangs devraient normalement taper à ~200.

**Comment by Ischjgt** [comment]
Déja notifié

**Comment by Elahbienscript** [comment]
Les vers de sang font tjrs ~20 de dmg à la place de ~200

**Comment by Elahbienscript** [comment]
Raid/PVP confondue se sont les même dmg

**Comment by joshwhedon** [comment]
Oui mais le bug a deja ete signale. Pour ca qu'il a ete ferme.
