### ISSUE TITLE
Instance: Haches-Tripes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#233]
**Description**
Ironbark the redeemed 14241 ne propose pas d'ouvrir la porte après avoir tué 11490 
[Conservatory Door] GUID: 351384 ID: 176907

**Comment by Killyana** [comment]
Gossip menu option manquant
``` sql
DELETE FROM `gossip_menu_option` WHERE `MenuID`=5602 AND `OptionID`=0;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES 
(5602, 0, 0, 'Thank you, Ironbark. We are ready for you to open the door.', 9103, 1, 1, 0, 0, 0, 0, NULL, 0, 0);
```
Dans le cpp l'option est ajouté via:
bool GossipHello(Player* player) override
{
      AddGossipItemFor

mais sa fonctionne pas.

**Comment by Ischjgt** [comment]
La bulle est apparue, mais il ne se passe rien ensuite (ça reste au menu avec la bulle)
