### ISSUE TITLE
Gardien des flammes, Caveau d'archavon

### ISSUE THREAD

**Issue by Mugiino** [way-of-elendil/3.3.5#235]
**Description**
Les gardiens des flammes (Trash mobs coté feu) au caveau d'archavon mettent des 42k au coup blanc au main tank, voilà voilà.
**Étapes de reproduction**
Aller à Archavon en 10, pull les "gardiens des flammes", mourir.
**Comportement attendu**
Ne pas oneshot les tanks.

**Captures d’écran / Vidéos**
Capture d'écran du recount mort du tank.
https://media.discordapp.net/attachments/549335605935603728/697118066202640475/WoWScrnShot_040720_181118.jpg?width=834&height=469

**Comment by Killyana** [comment]
Poings météoriques:
Les  attaques infligent des dégâts partagés également entre la cible  principale et une autre se trouvant à moins de 10 mètres d'elle.
