### ISSUE TITLE
Quête tolérance zéro 12686

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#236]
Il faut être transformé avec le déguisement du fléau pour voir le serviteur de drakuru en amical
L'utilisation du https://fr.wowhead.com/item=39206/sceptre-de-renforcement sur un serviteur de Drakuru (28802) le transforme bien en Main de Drakuru (28805). Le soucis étant qu'une fois contrôlé, le pnj en question n'attaque pas, il fait bien les attaques que l'on utilise dans sa barre de sort mais ensuite il n'attaque plus.
https://www.youtube.com/watch?v=5DMYXMDoQpI
Il en est de même pour la quête Trahison https://fr.wowhead.com/quest=12713/trahison
en utilisant https://fr.wowhead.com/item=39206/sceptre-de-renforcement sur Troll chancre-sang (28931)

**Comment by Killyana** [comment]
Tu parles des auto attaques?

**Comment by Amilgaull** [comment]
Oui le mob attaque via les attaques de la barre puis reste sanq mouvement

**Comment by Killyana** [comment]
Oui les auto attaques ne se font plus, on a déjà corrigé ce bug auparavant.

**Comment by joshwhedon** [comment]
Il faut faire au cas par cas pour ce genre de chose. En gros c'est un mob avec une smart AI, mais si tu le charme, il garde le comportement de smart ai. Donc faut un script pour lui assigner une autre ai.

**Comment by Aloawan** [comment]
Après avoir retenté la quête "Trahison" à deux reprises, le problème est toujours présent.
Le pet n'attaque pas, seules les attaques spéciales fonctionnent quand le pet est collé à Drakuru.

**Comment by joshwhedon** [comment]
Il est en aggressif ?

**Comment by Aloawan** [comment]
Oui je l'ai mis en agressif, je lui ai aussi demandé d'attaquer manuellement, rien à faire.

**Comment by joshwhedon** [comment]
JE viens de tester sur le serveur la maintenant, et il attaque nickel quand je lui dis. Tu as pas un pet de sorti qui pourrait causer des conflits ?

**Comment by Aloawan** [comment]
Non mon perso est mage, je n'ai aucun pet de sorti.

**Comment by Aloawan** [comment]
Je viens de réessayer après avoir relancé mon client mais c'est toujours pareil.

**Comment by Aloawan** [comment]
Je précise que c'est la quête "Trahison" qui me pose problème et non pas "Tolérance zéro" que j'ai déjà rendu.

**Comment by joshwhedon** [comment]
Haaaaa. Ok. Hum c'est pas les memes npcs pour Trahison correct ?

**Comment by Aloawan** [comment]
Oui sont sont des mobs différents.

**Comment by Ischjgt** [comment]
C'est encore là
