### ISSUE TITLE
[Donjon Ahn’kahet : l’Ancien royaume.] Boss héraut Volazj

### ISSUE THREAD

**Issue by AngelMasterBE** [way-of-elendil/3.3.5#237]
Bonjour

Lors de la phase qui pop après le cast de "insanity" ou on ce retrouve avec des add au images de nos personnage du groupe que on doit tuer, il a juste Une image de notre personnage qui apparait, ceux des autres présent dans le groupe ne pop pas

- Donjon : Donjon Ahn’kahet : l’Ancien royaume
- Niveau de difficulté : 5 HM
- Boss : Héraut volazy

**Comportement attendu**
Lors de la phase de "insanity" il devrait avoir 5 add qui pop au lieu de 1 seul sur le serveur live

**Comment by Ischjgt** [comment]
Déja notifié

**Comment by Ischjgt** [comment]
Navré, j'ai mal lu le ticket

**Comment by joshwhedon** [comment]
Il y a pas un add qui pop pour chaque joueur ?

**Comment by AngelMasterBE** [comment]
Actuellement non, ici sur les deux phase que j'ai eu avec mon paladin, j'ai juste eu ma doublure et pas celle des autres

J'ai refait l'instance avec mon priest, pareil j'ai juste eu ma doublure qui a pop

Donc manque les doublure des autres joueurs a chaque phase insanity

**Comment by joshwhedon** [comment]
Non mais je veux dire, chaque joueur doit combattre sa propre doublure non ? C'est pas le cas actuellement ? Il y a une seule doublure qui pop pour un seul joueur ?

**Comment by AngelMasterBE** [comment]
ah, Chaque joueurs doit DPS sa doublure dans leurs phase respective oui

**Comment by joshwhedon** [comment]
Ha en fait je viens de voir que c'est moi qui l'ai casse :D. Je pensais que chaque joueur devait combattre son double, pas tous les doubles. Je corrige
