### ISSUE TITLE
Emalon, caveau d'archavon

### ISSUE THREAD

**Issue by Mugiino** [way-of-elendil/3.3.5#238]
**Description**
Il y a un mob inciblable (un infernal)  à côté du boss, il pète la gueule au heal, ne le lâche pas, même après la mort du boss. Si la cible du mob sort de l'instance, il reste à l'entrée.

**Étapes de reproduction**
Aller au caveau d'archavon en mode 10, en face d'Emalon

**Comportement attendu**
Ce mob ne devrait même pas être là

**Captures d’écran / Vidéos**
https://cdn.discordapp.com/attachments/549335605935603728/697122372641226803/WoWScrnShot_040720_182047.jpg
https://cdn.discordapp.com/attachments/549335605935603728/697122411778408538/WoWScrnShot_040720_182429.jpg

**Comment by Killyana** [comment]
Fixé
