### ISSUE TITLE
Quête Les larmes de Dahlia 13078

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#239]
Je n'ai pas trouvé d'informations précises la dessus, le seul point que j'ai pu noter c'est que les Dahlia's Tears 192773 ont un temps de respawn qui ne bouge pas : SpawnTime: Full:16h40m Remaining:0s . J'ai vérifié sur plusieurs plantes à plusieurs minutes de décalage, rien ne change. Elles donc visible en gm on bien qu'en phase 1

**Comment by Killyana** [comment]
Y'a 3 dragons qui passent et respawn ces objects:

Guid 108330,-108329,-108202 chacun a un SAI par guid, j'ai vérifié IG  et ils respawn pas ces gobs. peut être l'action 70 ne fonctionne qu'avec les guid, je ne sais pas.

**Comment by Killyana** [comment]
Sera corrigé avec https://github.com/TrinityCore/TrinityCore/issues/24439
