### ISSUE TITLE
Utility: Renvoi de familier

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/3.3.5#24]
**Description**
lorsqu'on change de pet : loup pour ravageur par exemple le pet de l'écurie disparait (ça arrive environ 5 à 8% du temps - plusieurs joueurs ont déjà constatés ça) ; et ca fait déjà plusieurs fois que ça m'arrive, en soit si y'avait juste à le rechercher le pet ça irait; mais faut le re pex de 5 lvl .. ce qui est très chronophage; pourriez-vous voir pourquoi cela arrive trop souvent qu'on perd son pet sans l'avoir renvoyer mais juste en glissant un pet déjà dans l'inventaire sur l'autre ? 

**Étapes de reproduction**

**Comportement attendu**

**Captures d’écran / Vidéos**

**Ressources additionnelles**

**Comment by joshwhedon** [comment]
Il faudrait trouver les circonstances exactes pour reproduire le probleme.

**Comment by Killyana** [comment]
Pour la perte du pet y'a 3 situations connues:
1- changement du spé alors qu'un pet exotique est invoqué
2- tp vers la même map
3- get a beast mastery maxed talent to get beast mastery talent.
tame 2 exotic pets.
leave pet to die on combat.
use call stabled pet.
move stabled pet from stabled pets to current pet.

**Comment by Amilgaull** [comment]
La perte du pet peut survenir également dans les situations suivantes :
-Le pet invoqué est mort au moment ou le joueur change de pet
-Le joueur change de pet alors que son pet actuel n'est pas invoqué

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/859

**Comment by Ischjgt** [comment]
Mise à jour des situations pouvant faire perdre le familier :
- Le pet invoqué est mort au moment ou le joueur change de pet
- Le joueur change de pet/apprivoise un pet alors que son pet actuel n'est pas invoqué
- ~~changement du spé alors qu'un pet exotique est invoqué~~ => https://github.com/way-of-elendil/3.3.5/issues/859
- ~~tp vers la même map~~

**Comment by Ischjgt** [comment]
Patch 1.5.0 (2005-06-07): Unstabling dead pets no longer puts players into a degenerate state where their pet only partially exists. Unstabled dead pets can now be properly revived, and players can no longer train more pets than their stable can hold.

**Comment by Ferro3** [comment]
**Astuce**
L'une des astuce pour **ne jamais perdre son pet** est de toujours changer son pet avec l'actuel invoqué à coté de soit, attendre 1 à 2 secondes et changer.
Si la spécialisation bête est utilisée, toujours changer le pet exotique en pet non-exotique avant le changement de spécialisation.
Cela demande un peu de rigueur, mais ça évite de remonter les pet de 75 à 80 à répétition.

**Suggestion**
En plaçant une condition sur le changement de spécialisation (comme le mode combat) en testant la présence d'un pet exotique, cela peut éviter une partie du problème. Mais cela est-il faisable ? je ne sais pas.
