### ISSUE TITLE
[Donjon Épuration de Stratholme] Absence d 'Arthas.

### ISSUE THREAD

**Issue by blizzwolf** [way-of-elendil/3.3.5#244]
Dans le donjon" l'Epuration de Stratholme" HM,  impossible a faire car le PNJ d'Athas est absent de l'instance.
Arthas : https://fr.wowhead.com/npc=26499/arthas

**Comment by Killyana** [comment]
Concernant le Donjon Épuration de Stratholme, vous devez obligatoirement parler à Chromie pour utiliser [Disrupteur arcanique] sur les caisses, une fois que c'est fait elle apparaîtra juste avant le pont, il faut lui parler pour lancer l’évent.
Si vous avez fait la quête des caisse de Chromie une option va apparaître pour eviter de refaire ca, et vous serait téléporter au début de Stratholme avec Arthas déjà spawn.

**Comment by blizzwolf** [comment]
pas de Chromie non plu tout à l'heure.

**Comment by Killyana** [comment]
au début du donjon si

**Comment by Killyana** [comment]
Une fois les caisses marqués elle apparaîtra dans la colonne de lumière, de toute façon elle parle aux joueurs tout le temps pour vous dire se qu'il faut faire et ou la trouver.

![image](https://user-images.githubusercontent.com/6587064/78732376-d1083580-7942-11ea-80bf-def08eecc3e9.png)

**Comment by blizzwolf** [comment]
Mon perso venait juste de passer 80, j ai fait la quête de départ, comme de
de mes compagnon de DJ, on a rendu à chromi et pas d Arthas.

**Comment by blizzwolf** [comment]
Donc pour l avoir refait, mea culpa.. Chromi apparaît bien et lance le pnj
d Arthas... Par contre il faut faire la quête à chaque fois, même si tout
le groupe l'a déjà faite...
Dans mes souvenirs, sur offi, si la quête avait été faite par tous les
membres du groupe, il me semble bien qu il n y avait pas nécessité de la
faire... un peu comme EDC 5 et la salle des reflets avec la version courte
du scénario.

**Comment by Killyana** [comment]
Oui c'est correcte, il suffit de choisir l'option qui en gro dit, "Chromie on a déjà fait ça avant et il possible de passer aux chose sérieuses" et la vous serez tp sous le pont avec Arthas déjà spawn
