### ISSUE TITLE
Pet démo disparaît après pdf

### ISSUE THREAD

**Issue by Edhrein** [way-of-elendil/3.3.5#245]
**Description**
Le pet du démoniste ne suit pas le démoniste quand il pdf mais est désinvoqué avec gain de fragment d'âme.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Démoniste
- Elfe de sang
- Affliction
- Pierre de foyer à Dalaran

**Comportement attendu**
Le pet est invoqué au côté du démoniste à son arrivée à l'auberge de la pdf.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23325
Peut causer la perte du pet chasseur.
