### ISSUE TITLE
BG - Guide spirituel et familiers 

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#246]
**Description**
Le Guide spirituel de l'alliance ( 13116 ) et Le guide spirituel de la Horde ( 13117 )  ( les anges qui rez les joueurs en bg ) ne ressuscitent plus les familiers des chasseurs quand ceux-ci sont tués avant que le joueur soit tué 
Pas testé en démoniste et dk mais je pense qu'ils doivent être logés à la même enseigne

**Étapes de reproduction**
faites mourir votre familier en bg 
mourrez ensuite et attendez le rez
le pet reste mort et vous devez le rez et le soigner manuellement

**Comportement attendu**

Depuis le patch 1.5 jusqu'à celui çi 

    Spirit Guides in Battlegrounds will now summon/resurrect your current pet when the Hunter is resurrected. ( version pour les Hunts ) 

    Spirit Guides in Battlegrounds will now resurrect your last Imp, Voidwalker, Succubus or Felhunter. If the Doomguard or Infernal were the last active pet or the previous pet was killed before the Warlock, an Imp will be summoned. ( version démo ^^ )

**Comment by Gandrayda** [comment]
https://wowwiki.fandom.com/wiki/Patch_1.5.0 si besoin pour vérification

**Comment by joshwhedon** [comment]
Heu ils le faisaient avant ?

**Comment by Gandrayda** [comment]
Alors avant il y avait aussi un bug , lors du rez notre pet apparaissait mort mais il suffisait de prendre sa monture et de dismount pour le voir rez et full life ( alors qu'il avait été tué avant notre mort ) mais par contre si on restait à pied notre pet était comptabilisé comme mort ( d'ailleurs on ne pouvais pas le rez le cast se bloquait à la fin , le jeu devait considérer qu'il était en vie )

**Comment by Gandrayda** [comment]
le bug est réapparu de nouveau ( en goulet et je l'ai eu aussi en altérac ) , exactement le même soucis le pet apparait mort et doit etre rez manuellement

**Comment by Gandrayda** [comment]
Le soucis est toujours présent , il se produit pas à chaque fois , ça viens de le faire alors que le pet était visible et mort quand je l'ai été et une autre fois quand le pet mort à depop et que je meurt après .
https://ibb.co/KyPrwxz
