### ISSUE TITLE
Camouflage dans l'ombre ( racial elfe de la nuit )

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#247]
**Description**
Le racial camouflage dans l'ombre des elfes de la nuit ( 58984 ) ne permet plus de résister totalement à un sort ou à une attaque si il est lancé avant les 50 premiers pourcents du trajet du sort entre le lanceur est nous. On se prend l'attaque ou le sort de plein fouet

ex: avec une explosion de lave , si on lance le camouflage avant que l'explo fasse la moitié du chemin on se ne prend pas le sort  ( même principe que le vanish de rogue en sorte ) 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe : toutes classes
- Race : Elfe de la nuit

lancer un duel contre un caster ( ou un dps physique à distance ) 
votre adversaire initie une attaque ou un sort à distance
une fois le sort lancé , activez camouflage avant que la moitié du trajet du sort soit fait 
le sort vous atteint et inflige ses dégâts ( ses effets ) chose que normalement non

**Comportement attendu**
Annulation du sort si camouflage lancé dans les 50 premiers pourcents du trajet du sort , il nous " atteint " mais ne nous inflige ni dégats ni effets ( affecte tout les sorts et attaques qui sont dans la même situation si plusieurs sont en chemin )
Force le dé-target de la cible ( une fois le camouflage activé la cible ne nous cible plus )

**Captures d’écran / Vidéos**

https://www.youtube.com/watch?v=fLjTRifi6dE  à 28:36  ( vidéo offi de Danaik où on le voit bien annuler à la fois une mini boule de feu et un sort du mage arcane )

**Comment by Killyana** [comment]
Le résultat d'un cast est calculé au moment ou le cast se fait et non à l'impact.

**Comment by Gandrayda** [comment]
Si vous le dites , néanmoins avec le camouflage ( comme avec le vanish du rogue ) le sort à l'impact n'a plus d'effet ( faut rester en fufu jusqu'à l'arrivée du sort ) , avec la vidéo à 28:38 et en avançant image par image on voit bien les 2 sorts partir et le hunt est toujours visible ( donc en suivant votre raisonnement il est censé se prendre le sort ) et quelques images plus tard on voit le " leaving combat " signifiant l'activation du  camouflage ( les sorts arrivent mais il pert pas de hp ( les dégâts qu'il prends c'est des dégâts physiques du drood à coté )
Avant le merge ça fonctionnait parfaitement bien , on avait bien notre annulation de l'effet ( il nous touchait mais faisait rien )

**Comment by Killyana** [comment]
Avant la merge c'était pas le cas?

**Comment by Gandrayda** [comment]
Non avant la merge le sort fonctionnait parfaitement j'avais fait une vidéo pvp ( sur woe il y'a 4 mois ) où il y'a l'utilisation de ce sort : https://youtu.be/o2HSDRv7SOk   ( à partir de 6;45 il y en a plusieurs d'affilés sur plein de situations et le camouflage fonctionnait à merveille )

**Comment by sithis2a** [comment]
Par contre petites précisions, le Shadowmeld fonctionne comme le Vanish pour ce qui est des "annulations" d'effets des sorts.
Cette mécanique est due aux traitements par batch des events à l'époque sur offi et est simulé sur les privés par ce qui s'appelle le CCDelay.

Du coup le meld annule le spell même si tu le lances dès le lancement du sort en fait (d'ailleurs c'est le seul moyen de meld un hoj ou un fear de priest (et d'autres) qui n'ont pas de temps de trajet.
Donc 

> Annulation du sort si camouflage lancé dans les 50 premiers pourcents du trajet du sort
est partiellement faux, tant que le sort ne t'as pas touché tu peux le meld/vanish. Le seul risque étant que si tu meld trop tôt et que tu es dot, tu vas réapparaître avant et te manger le sort quand même.

**Comment by jackydit** [comment]
https://streamable.com/a3wfmj
Le shadowmeld est horrible.
Là sur le clip, non seulement ça ne vanish pas la lavaburst, et pourtant y a pas de tick d'horion à ce mmt et en plus le cleartarget chaine d'éclaire l'empeche pas d'aller jusqu'au bout du cast
C'est méga méga méga frustrant, de réussir à vanish une fois sur 10 dès qu'il y a un dot
Et le cleartarget meme combat...

**Comment by Ischjgt** [comment]
Réouvert à la demande de Frédéric

**Comment by joshwhedon** [comment]
J'ai teste et il marche tres bien. Si tu le lance pendant que le sort est en vol, il touche pas et le shadowmeld s'enleve pas.

**Comment by joshwhedon** [comment]
Donc soit tu as utilise trop tot, soit trop tard (au vue de la video je dirai trop tard).

**Comment by Endalaust** [comment]
> Là sur le clip, non seulement ça ne vanish pas la lavaburst, et pourtant y a pas de tick d'horion à ce mmt et en plus le cleartarget chaine d'éclaire l'empeche pas d'aller jusqu'au bout du cast

Je suis d'accord avec lui sur les 2 points remontés : 

-  vanish, il aurait du être effectif. Pas de dot avant de subir le lavaburst. Spell utilisé avant de subir le lavaburst, tout était aligné pour que ce soit OK.

- Pour le cleartarget chaine d'éclair idem, il y a eu le cleartarget et normalement l'incantation aurait du partir en échec, on voit clairement sur la vidéo que la target n'a pas été repositionnée avant la fin de l'incantation (le target peut se remettre en auto sur un dot, mais là ce n'est pas le cas)

Si cette vidéo représente les conditions de la prod, le spell est effectivement dénué de son utilité :(

**Comment by Kwyzard** [comment]
Que le vanish Lavaburst ne fonctionne pas ou fonctionne seulement dans une durée spécifique est une chose et ça cela dépend effectivement du **choix** que font les devs la dessus mais que le clear target pour la chaine d'éclair ne fonctionne pas la y a un gros problème quand même on voit clairement que le chaman perd le chasseur de target mais que la chaine d'éclair fini sont cast un bon gros 0.4 sec

**Comment by joshwhedon** [comment]
Non mais le vanish / shadowmeld sur un sort en vol fonctionne parfaitement, j'ai teste plusieurs fois, si le joueur n'est pas visible pour le lanceur de sort au moment ou le sort touche, le sort n'aura pas d'effet.

**Comment by Kwyzard** [comment]
fix pls

**Comment by jackydit** [comment]
https://streamable.com/qwibot

**Comment by joshwhedon** [comment]
C'est pas casse ca lag c'est comme ca. Tu vanish trop tard ou le vanish se retire.
Pour le clear target va falloir me prouver que si le joueur perd la cible de vue le sort doit etre interrompu, parce que actuellement il est normalerment interrompu a la fin du cast pas en cours de cast.

**Comment by Kwyzard** [comment]
Pas trouvé de preuve en 3.3.5, sur wowwiki pas d'update depuis la 3.1.0
https://wowwiki.fandom.com/wiki/Shadowmeld

Donc si on chope des vidéo d'offi actuelle ça devrait être scripter pareil ou pas?

**Comment by joshwhedon** [comment]
Nah, ca voudrait pas dire grand chose. Le soucis des patchnotes c'est que generalement les infos sont valides pour les patchs intermediaires, mais rarement pour les expansions parce que y'a trop de trucs qui changent pour etre mis dans un patchnote. Mais bon si vous trouvez quelque chose, j'aviserai si c'est suffisant ou pas.

**Comment by jackydit** [comment]
Si quelqu'un est chaud pour chercher pour le break cast hihi
Mais là regarde le mec continue le cast de son sort, va jusqu'à la fin, le sort part et il me reprend pas du tout en target donc bon ^^

**Comment by jackydit** [comment]
https://www.youtube.com/watch?v=I-V-zol2C2M
1min 20 (cata mais bon imo meme script)

**Comment by joshwhedon** [comment]
Ouai bah j'ai teste, et je peux rien faire de plus que ce qui est present maintenant. Si un joueur utilise shadowmeld pendant un cast sur lui, le cast est interrompu parce que le lanceur de sorts ne voit plus le joueur. Et ce tant que le cast  est en cours. Malheureusement, lags serveur et client jouent beaucoup dessus, et ca, j'y peux absolument rien.
Du coup sur woe vous aurez probablement pas mieux que ce qui est en place actuellement, a moins que Trinity retravaille tout le systeme de sorts.
