### ISSUE TITLE
Mobs de la Marche de l'Ouest Drop beaucoup trop de sac.

### ISSUE THREAD

**Issue by Tim1555** [way-of-elendil/3.3.5#249]
Tout les mobs ou presque de la marche de l'ouest drop chacun un sac, ce qui fait que l'inventaire est très vite plein dans une zone ou il l'était rapidement même sans ça. 

Voleur Combat Niveau 14, peut-être que le niveau influe sur les drops je n'ai pas testé.

Pour tester, simplement tuer un mob marche de l'ouest et constater que 95% du temps, il lâchera un sac.

![WoWScrnShot_040720_222954](https://user-images.githubusercontent.com/63318503/78717067-4dd5e800-7920-11ea-9ddb-176a3ea65fe0.jpg)

**Comment by Killyana** [comment]
Merci pour le signalement, corrigé prochaine Maj.
