### ISSUE TITLE
Nucléus princes de sang

### ISSUE THREAD

**Issue by Mugiino** [way-of-elendil/3.3.5#250]
**Description**
Les nucléus pop parfois sous map, donc impossible à récupérer pour le tank. Sur un coup de malchance plusieurs peuvent pop sous map à la suite, le tank se fait donc inévitablement oneshot quand ça passe sur Keleseth. Bug observé cet après midi en mode 10NM.

**Étapes de reproduction**
Pull les princes en 10NM et observer les pop de nucléus.

**Comportement attendu**
Les nucléus devraient pop au dessus du sol, pour qu'elles puissent être récupérées par le tank.

**Captures d’écran / Vidéos**
https://media.discordapp.net/attachments/697078854975488070/697080936935981156/WoWScrnShot_040720_154657.jpg?width=834&height=469

**Comment by Ischjgt** [comment]
Encore constaté

**Comment by joshwhedon** [comment]
On y peut rien, j'ai fait tout ce que je pouvais pour ce soucis, ca va malheureusement arriver de temps en temps.

**Comment by Killyana** [comment]
Corrigé avec les nouveaux mmaps
