### ISSUE TITLE
BUG LK insensible au pull

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#251]
**Description**
Le lk en 25HM au pull est insensible les 3 premières seconde (résultat si le groupe est trop proche le lk One shot une personne aléatoirement (le tank n'arrive pas à taunt; même les flèches en chasseur ne passent pas pour la détourne)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 jours Hard Mode
- Boss: LK
- Sort en question / Phase du boss en question / Emplacement: P1 début du pull
- Composition du groupe: Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
le lk est censé être attaquable 0.0sec au début du pull

**Captures d’écran / Vidéos**
[https://www.youtube.com/watch?v=RSeVCw3hVgQ&t=338s](url)

**Ressources additionnelles**
d'autres vidéo down lk

**Comment by joshwhedon** [comment]
Honnetement ... je vois pas de soucis. Votre tank laggait ? Parce que la, en local, le boss agro mon autre perso, je taunt, il est direct sur moi sans pouvoir attaquer mon autre perso une seule fois.

**Comment by gtschanz** [comment]
bah on perdait 1 personne à chaque pull quand on était dans la range des 10mètre; les 2 tank spammait leur spells il avait même poser une mort et décomposition au sol (spell dk) et je l'ai instant détournement + send des flèches et les 2 premières qui ont atterri sur le boss m'ont affiché : Insensible; je pense que le boss est insensible les 1/2 première sec après le début du pull à 00.00sec

**Comment by joshwhedon** [comment]
Hein ? Je vais tester avec des aoes au sol mais moi j'ai pas eu un seul insensible. Vraiment bizarre votre soucis.

**Comment by gtschanz** [comment]
on va recheck ça à titre perso mardi prochain; peut être que les EA vont rencontrer ce soucis jeudi soir quand ils iront sur lk (et ils pourront peut être voir si eux aussi ont rencontré ce soucis)

**Comment by joshwhedon** [comment]
Oki, tenez moi au courrant, parce que la je vois pas honnetement. En plus je suis vraiment pas bon donc si j'arrive a l'intercepter, vous devriez y arriver aussi lol.

**Comment by gtschanz** [comment]
UP ! idem saurcroc et ça nous l'a refait ce soir en ICC 25n

**Comment by gtschanz** [comment]
![Capture d'écran 2020-04-09 01 13 37](https://user-images.githubusercontent.com/63243193/78842109-6c5ee080-79ff-11ea-9596-f31baab46deb.png)
@joshwhedon  j'ai pris un screen au pull de saurcroc il semblerait qu'il ''évite'' la première attaque ce qui est très dangereux

**Comment by gtschanz** [comment]
ou du moins les premières attaques

**Comment by joshwhedon** [comment]
Ouai mais j'ai toujours pas le soucis ... la premiere seconde je peux le provoquer sans soucis et il vient bien vers moi.

**Comment by gtschanz** [comment]
on va stream mardi quand on y retourne; je t'enverrais les stream

**Comment by Ischjgt** [comment]
Ticket: 15671. Created by: [] Created: 13h39m44s ago Last change: 13h39m44s ago Ticket Message: [la génération d'aggro à l'air de se faire quelques instants après une capacité au lieu d'instant, du moins pour le toucher de glace il y a un léger délai entre le sort et l'aggro effective]

**Comment by joshwhedon** [comment]
Je mets un correctif mais aucune idee si ca reglera le probleme. Pour information, la liste d'agro se met a jour toutes les secondes (apparament sur offi aussi en 3.3.5). Je mets une exception pour les taunts.

**Comment by Endalaust** [comment]
Depuis deux jours, ce soucis a t il été reconstaté ?
