### ISSUE TITLE
BUG LK apparition des Shadowtrap - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#253]
**Description**
Sur LK25HM; les shadowstrap apparaissent directement au cac et prenne plus de temps à apparaitre au cast (au cac elles apparaissent entre 1 et 2 seconde; et si elle est sur le tank elle apparait au bout de 0.0sec)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25Hard Mode
- Boss: LK
- Sort en question / Phase du boss en question / Emplacement: spell shadow trap (piège que le lk place en P1)
- Composition du groupe: Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
Le pop normal des shadowtrap est compris entre 3 à 5 seconde normalement (délais + important) et il n'y a pas de différence de délais d'apparition entre le cac et le cast 

**Captures d’écran / Vidéos**

Vidéo du signalement en question (apparu ce soir lors du raid):
[https://www.twitch.tv/videos/585968905](url)

Vidéo du comportement attendu:
[https://www.youtube.com/watch?v=RSeVCw3hVgQ&t=338s](url)

**Ressources additionnelles**
autres vidéo de down

**Comment by joshwhedon** [comment]
A vrai dire, il y a des differences de delai, meme sur offi. Mais le visuel devrait effectivement prendre un peu plus de temps avant de disparaite. Je le passe de 3 secondes a 5 secondes base sur les videos.
