### ISSUE TITLE
BUG ICC DAME 25Hard Mode: Contrôle Mentale - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#254]
**Description**
Sur la Dame 2ème BOSS à ICC 25 Hard Mode lors d'un CM sur un wype les joueurs restant en vie ont eu les touches des spells utilisées pendant le CM de la dame comme en utilisation et activé en bug voir inutilisable pour d'autres - La seule solution pour régler ça avant le repull a été une déco reco pour les joueurs en question - je n'ai aucune idée si cela a aussi lieu en fight avec down et ou dans le cas d'un rb (n'ayant pas eu de recours au rb)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Dame Murmemort
- Sort en question / Phase du boss en question / Emplacement: en P2 sur le contrôle Mentale que le boss utilise sur les joueurs - emplacement mid salle et au sortir de la salle sur le wype
- Composition du groupe: Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
Les sorts utilisable après le wype du raid et pas de problème de spell sur les 3 joueurs en vie (qui était cm quand tout les autres étaient mort) et le fight du coup terminé

**Captures d’écran / Vidéos**
 
je n'ai pas fais de vidéo du fight en question

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Ils ont tente de faire un reload ?

**Comment by gtschanz** [comment]
pas test avec un reload on a déco reco pour enlever le soucis

**Comment by joshwhedon** [comment]
J'ai tente de reproduire sans succes. Je mets un correctif mais je doute que ca change grand chose. Tentez de /reload la prochaine fois pour voir.

**Comment by joshwhedon** [comment]
Autre question : c'est arrive que apres le wipe ? Ou bien c'est aussi arrive aux joueurs qui se sont fait controller pendant le combat et que le controle mental s'est ensuite retire ?

**Comment by gtschanz** [comment]
je n'ai pas eu de retour des gars du raid pendant le cm en p2; à voir par la suite; je parle uniquement d'un truc que j'ai vécu (vu que j'ai été CM avec satarians et un autre) tout les autres sont mort quand on a été cm il restait que nous 3 et quand le cm s'est fini le boss à reset mais nous on avait nos touche de spell comme enfoncé en mode cast (ceux qu'on a cast pendant le cm) et le seul moyen qu'on a eu d'enlever ça c'était de déco reco (après on a pas test le /reload)

**Comment by gtschanz** [comment]
![Capture d'écran 2020-04-09 01 00 45](https://user-images.githubusercontent.com/63243193/78841444-99aa8f00-79fd-11ea-8845-6641ab3fc8ba.png)
 @joshwhedon regarde j'ai été cm en 10HM les touches sont marqués comme en cours d'utilisation le /reload ne marche pas il faut déco reco (les spells ont peut les utiliser) mais ça fait un bug visuel assez pénible

**Comment by gtschanz** [comment]
et le problème on ne voit ainsi pas les timer de ses spells genre je sais pas quand l'écorce est ré-up à moins d'utiliser un weak aura

**Comment by joshwhedon** [comment]
Ca le fait a tout le monde ? Parce que je me demande si y'a pas un addon qui fait conflit.

**Comment by gtschanz** [comment]
@joshwhedon  le problème est persistant ici; trop de joueur sont encore obligé de faire des déco reco après la dame. et chaque fois les gars qui sont cm.. c'est très emmerdant
