### ISSUE TITLE
Interrogation Trash ICC après la dame Murmemort - Sévérité BASSE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#255]
**Description**
Lorsqu'on prend l'ascenceur après le down de la dame Murmemort en 25HM le premier pack d'ads devant nous = normal; ensuite nous sommes allés sur la droite (car on devait prendre le bateau H2) et là, il y a le double de trash sur ce pack - est-ce normal ?

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Trashs après la dame
- Sort en question / Phase du boss en question / Emplacement: 2ème pack de trashs après l'ascenceur lorsqu'on down la dame Murmemort 
- Composition du groupe: Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
est-ce normal qu'il y a le double de trash sur le second pack ? (aucune vidéo trouvé)

**Captures d’écran / Vidéos**

J'ai pas eu le temps (ils ont été explosé le temps que je relève le soucis de la dame; sorry)

**Ressources additionnelles**

-------

**Comment by joshwhedon** [comment]
Double = chaque mob est en double, a la meme position, ou bien y'a juste plus de mob ?

**Comment by Killyana** [comment]
J'ai pourtant spawn les remparts à partir de sniffs, et selon la faction du raid

**Comment by gtschanz** [comment]
il y en avait plus; pas en double

**Comment by Killyana** [comment]
C'est normal alors, il faut pas oublier la moitié des pnjs sont supposés être amicaux, mais il ne le sont pas à cause de l’interaction, et y'a aucune solution pour changer ca.

**Comment by joshwhedon** [comment]
Je peux changer la faction avec l'interfaction cote script si tu veux Eridium.

**Comment by Killyana** [comment]
Pas possible parce que les spawn sont mixés certain, sont dispo pour les 2 factions d'autres pour une seule, c'est un casse en plus il faut trouver une faction qui est amicale avec la horde et l'alliance, au pire laisses sa pour après quand le serveur est stabilisé.

**Comment by joshwhedon** [comment]
Oui mais les entrys sont pas mixees, si ? Genre si je fais que quand c'est un groupe interfaction, je passe tous les pnj horde inamicaux, tous les pnj alliance amicaux. C'est ce que je fais dans d'autres zones.

**Comment by gtschanz** [comment]
![Capture d'écran 2020-04-09 01 18 48](https://user-images.githubusercontent.com/63243193/78842374-163e6d00-7a00-11ea-8397-95af3f3335f1.png)
![Capture d'écran 2020-04-09 01 18 40](https://user-images.githubusercontent.com/63243193/78842378-19395d80-7a00-11ea-926e-44e1e5374578.png)
@joshwhedon du coup quelque chose sera fait à ce niveau ?

**Comment by joshwhedon** [comment]
Peut etre mais priorite basse.

**Comment by Killyana** [comment]
Les spawn sont correctes, pour le changement de faction, il faut le faire par guid et non par entry, vue que les même npc sont utilisés pour les 2 factions.
On essaiera ça, quand tout rentre dans les ordres.
