### ISSUE TITLE
Bataille de la canonnière à ICC 25 Hard Mode - pré-chauffage des canons - Sévérité BASSE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#256]
**Description**
On arrive toujours à préchauffer les canons alors que le fight n'est PAS encore lancé et sans avoir le bateau adverse en vue

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Bataille de la canonnière
- Sort en question / Phase du boss en question / Emplacement: Chauffage des canons sur le bateau
- Composition du groupe: Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
On NE peut utiliser les canons uniquement lorsque le fight démarre (du moins commencer à stock l'énergie)  - problème déjà signalé avant la merge

**Captures d’écran / Vidéos**

-----

**Ressources additionnelles**

-----

**Comment by Killyana** [comment]
C'est pas possible de préchauffer sur offi?

**Comment by gtschanz** [comment]
bah on peut monter dedans mais il est impossible de stack l'énergie déjà à 90+ avant le début du fight car cela permet déjà de claquer un 40-60K lorsque le bateau arrive sans avoir eu à stack dès le début du fight

**Comment by gtschanz** [comment]
et donc cela facilite le down du bateau avec 2 pop de sorcier et donc l'obtention du hf au passage aussi..

**Comment by Killyana** [comment]
C'est blizzlike: https://www.youtube.com/watch?v=v9upsc83rYI

**Comment by gtschanz** [comment]
question: dans ta vidéo en - de 10 seconde il est quasi full en énergie; les délais pour monter à une tel quantité d'énergie sur woe me semble beaucoup plus long est-ce normal ?

**Comment by Killyana** [comment]
L'energie sur wotlk: Value: 6 to 10 https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=70172
Aprés wotlk Valeur : 8 https://fr.wowhead.com/spell=70172/d%C3%A9flagration-de-canon

Sur la vidéo il semble que le gcd est plus rapide je ne sais pas pourquoi.
J'ai remarqué depuis toujours que les spells des canons font un sorte de glich qui fait revenir le GCD un peut en arrière avant de continuer
