### ISSUE TITLE
BUG CANNON à ICC 25 Hard Mode - Sévérité MOYEN

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#258]
**Description**
Overfire a prit un canon lors du fight mais il a crash pendant le fight dans un canon; résultat le canon était inutilisable sur tout le fight - malgré le POP du sorcier en face qui oblige les player à quitter le canon.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Bataille de la canonnière 
- Sort en question / Phase du boss en question / Emplacement: canon sur le bateau
- Composition du groupe: Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Les joueurs doivent quitter obligatoirement le canon après l'apparition du sorcier sur le bateau adverse; même s'il a crash étant dans le canon; il doit être au plus tard être rendu libre à la mort du sorcier adverse sur le bateau pour que quelqu'un puisse le reprendre.

**Captures d’écran / Vidéos**

---- : voir vidéo offi de ce fight.

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Vous trouvez pas que vous abusez un peu la ? :D . Evitez de crash pendant les combats. Desole mais celui la ce sera une priorite base.

**Comment by Killyana** [comment]
Lié à https://github.com/way-of-elendil/3.3.5/issues/298
