### ISSUE TITLE
PROC Magie noire sur DRUIDE féral - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#259]
**Description**

L'enchantement Magie noire DOIT proc sur le druide féral - le fait de ne pas PROC (bride considérablement le DPS de cette classe) - Fianso à fait un autre ticket à ce sujet plus précis avec une vidéo; se référer à son post pour la résolution est mieux

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: Druide
- Race: tauren / elfe de la nuit
- Spécialisation: Combat farouche
- Sort / Talent / Etc: proc sur lambeau et blessure infectée
- Circonstances (Donjon, Raid, PvP, autre): dans toute situation
- Equipement: arme 2 main
- Buffs / Debuffs / Enchaînement de sort / Etc: Buff Magie noire

**Comportement attendu**

l'enchantement DOIT proc sur les lambeau / blessures infectées

**Captures d’écran / Vidéos**

Se référer à la vidéo de Fianso (catsuni) et à son BT

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Merci, l'autre bug est toujours ouvert, inutile de faire un second. Ce bug est existant depuis avant la merge, et il n'y avait pas de solution claire pour le corriger a ce moment la.
