### ISSUE TITLE
Event avant Putricide ICC 25 Hard Mode

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#261]
**Description**

Le piège/ event avant putricide est INOFFENSIF sur le raid; on perdait maximum 200 pv all 1-2 sec ce qui est complètement RIDICULE - le piège doit faire des dégâts et qui doivent tuer le raid si les heals ne heal pas. De plus à la fin du piège nous avons gardé un BUG combat (qui doit obligatoirement s'arrêter à la fin de l'event / piège

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Event avant Putricide
- Sort en question / Phase du boss en question / Emplacement: Event avant putride
- Composition du groupe: 
Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Le piège doit faire des dégâts au raid qui doivent être remonté par les heals (ceux qui génèrent de l'aggro pendant cet event doivent obligatoirement être plus impactés car ils sont la cible des scarabées).

**Captures d’écran / Vidéos**

----: Bug déjà signalé (par le passé)

**Ressources additionnelles**

----

Je l'ai mis en sévérité IMPORTANTE car il ne fait pas sortir le raid du mode combat ce qui oblige de wype si les heals/ cast devait être OOM si l'event avait son effet normal

**Comment by Ewilanwoe** [comment]
Même problème constaté en 10H le mardi 07/04/2020. On voit également très peu de mobs apparaître en comparaison à avant.

Première minute de la vidéo : https://www.youtube.com/watch?v=0AXY9S_4xQc&feature=youtu.be

**Comment by joshwhedon** [comment]
Heu, le piege avant putricide les degats sont fonction des hps des joueurs. Donc je trouve bizarre que vous preniez si peu.

**Comment by joshwhedon** [comment]
Les bug combat sera corrige avec un autre ticket.
