### ISSUE TITLE
SORT - feindre la mort (chasseur) - Sévérité MOYEN

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#262]
**Description**

Lors d'un bug combat en chasseur si on fein la mort (sort de chasseur) on ne sort pas du mode combat; mais on reset uniquement l'aggro en cours - cela est très gênant car cela nous empêche de regen vie / mana par exemple (en pvp si on devait trap quelqu'un ou en pve après un event).

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: Chasseur
- Race: elfe de sang / troll / orc / tauren /elfe de la nuit / nain / dranéi
- Spécialisation: all spécialisation
- Sort / Talent / Etc: sort Feindre la mort
- Circonstances (Donjon, Raid, PvP, autre): constaté en raid après l'event de Putricide ou nous sommes restées en combat
- Equipement: avec ou sans cela ne change rien
- Buffs / Debuffs / Enchaînement de sort / Etc: Feindre la mort

**Comportement attendu**

Feindra la mort = disparition (sort de voleur) concernant la sortie de combat; cela annule directement tout combat

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by Killyana** [comment]
Feindra la mort = disparition (sort de voleur) concernant la sortie de combat; cela annule directement tout combat  (seulement en dehors des instance)
Dans une instance sa reset l'aggro à 0 mais ne sort pas le chasseur du combat, pareil pour disparition (sort de voleur)

**Comment by joshwhedon** [comment]
Oui a premiere vue c'est un debug celui la. Je sais qu'a BC il etait possible de sortir de combat et de manger boire grace a feindre la mort, mais pas apres.
https://github.com/TrinityCore/TrinityCore/issues/23874 pour plus d'info sur le fix,

**Comment by joshwhedon** [comment]
https://wow.gamepedia.com/Feign_Death
Voir la 2.3
