### ISSUE TITLE
Prise de double maléable sur putricide en 25 Hard Mode - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#263]
**Description**

lorsque nous avons constatée une réduction des dégâts suite à la prise de certains joueurs de la malléable sur putricide pendant le fight par rapport à d'habitude (ancienne version) - j'ai volontairement ''pris'' une double malléable sur le fight de putricide sans avoir de main de sacrifice / suppression de la douleur et j'ai survécue ! (certes avec 9% de pv mais c'est IMPOSSIBLE de survivre à une double prise de malléable en 25 HARD MODE - 1 malléable prise doit normalement être permise, mais une double prise DOIT OS le joueur; globalement les malléables sur putricide inflige des dégâts très réduit, ce qui facilite le down de ce boss.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Putricide
- Sort en question / Phase du boss en question / Emplacement: malléable que putricide lance sur les joueurs par 2 en ciblant deux joueurs quand lancée (si les 2 joueurs target sont au même endroit les 2 malléables vont au même endroit)
- Composition du groupe: 
Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Les malléables doivent infliger plus de dégâts et une double prise doit obligatoire OS (particulièrement en HARD MODE)

**Captures d’écran / Vidéos**

---- je n'ai pas trouvé de vidéo offi ou des gens prennent volontairement des malléables mais avec les singes ici cela facilite globalement les downs de CE boss

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Tu as une idee des degats qu'elle t'a inflige ? Les degats sont 23400 to 24601 (c'est les donnees client). Tu as combien de pv total ?

**Comment by gtschanz** [comment]
24K + all buff + buff 30% ça doit faire 35k à tout cassé même pas; et je suis certains de ne pas avoir eu de main de sacri / suppression de la douleur / shields / bouclier saint vu que c'était un mouvement délibéré de ma part et il me restait 10% et ce n'était pas sur une phase critique donc pas de sacri raid à ce moment

**Comment by joshwhedon** [comment]
OK, j'irai tester, peut etre que le boss lance une version normale du sort au lieu d'heroique.

**Comment by Ischjgt** [comment]
~19k8 25NM
23581 25HM chez moi

**Comment by joshwhedon** [comment]
A premiere vue, t'as juste eu de la chance de t'en sortir je pense, j'ai reteste les degats, et pas de soucis. C'est les bons sorts qui sont utilises (et les degats sont les donnees client).

**Comment by gtschanz** [comment]
je vais retest avec screen de mon côté mardi pro
