### ISSUE TITLE
utilisation du spell ICE block de mage sur putricide - Sévérité TRES TRES IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#264]
**Description**

Un mage de notre raid à été target en transition (2ème) par un limon vert il a ice block car il avait une piscine sous les pieds pour ne pas prendre de dégâts - ce qui c'est passé à ce moment; cela à fait faire un demi tour au limon qui est retourné à sa position d'origine; quand il a cancel le ice block le limon est revenue mais cela permet d'éviter l'impact des limons ce qui FACILITE grandement le down de ce boss car on peut dodge des impacts de limons...

Autres spells qui seraient à surveiller et qui pourraient causer la même chose: feindra la mort en chasseur + main de protection de paladin + bubulle de paladin + raciale elfe de la nuit qui pourrait avoir le même effet (même si nous n'avons pas été dans une tel situation.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Putricide
- Sort en question / Phase du boss en question / Emplacement: Ice block (mais faudrait également surveiller feindra la mort en chasseur + main de protection de paladin + bubulle de paladin + raciale elfe de la nuit -  Eventuellement la disparition de voleur (elle elle annule vraiment le target sur le voleur néanmoins le limon ne doit pas retourner sur sa position d'origine mais instantanément cibler un autre joueur).

- Composition du groupe: 
Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Le limon doit aller sur le mage est impact et déclencher le Bump; après le mage ne doit pas subir de dégâts s'il est encore dans le ice block au moment de l'impact

**Captures d’écran / Vidéos**

----: on a pas stream ce comportement mais je présume qu'il est réutilisable.

**Ressources additionnelles**

----

Cela est à corriger de toute urgence sinon les down de ce fight seront biaisé si on peut temporiser le limon vert particulièrement sur une transition - à check sur toute les classe / race mentionnées !

**Comment by joshwhedon** [comment]
Vous etes sur que sur offi le limon continue a suivre sa cible dans ces cas la ? Il est pas suppose changer de cible plutot ?

**Comment by gtschanz** [comment]
changer de cible peut être mais pas faire un demi tour à 180 degré pour retourner à sa position de départ

**Comment by gtschanz** [comment]
et si retarget il doit se faire instantanément on a tous été étonné par ce mouvement du limon

**Comment by joshwhedon** [comment]
Oui oui y'a defintiviement un bug, j'essaie juste de comprendre le comportement correct.

**Comment by Ischjgt** [comment]
Wowhead 
(Mise à jour 3.3.0)
Blink does NOT free you, however you DO jump forward the 20 yards. Use it right before the ooze touches you. Ice Block cancels the entire affect, forcing the slime to pick another target. Do NOT Ice Block, there will be melee close to the slime, and will probably explode.

**Comment by gtschanz** [comment]
nous hier avec le ib il a fait demi tour

**Comment by toitit** [comment]
Bug identique à https://github.com/way-of-elendil/3.3.5/issues/225, le limon part vers un autre joueur sans recibler et n'explose pas

**Comment by joshwhedon** [comment]
Oui pardon oublie de fermer celui la. Normalement c'est regle mais galere a tester donc on va voir a la prochaine mise a jour demain.
