### ISSUE TITLE
UP d'énergie abomination putricide 25 Hard Mode

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#265]
**Description**
Notre tank (Cutienight) à eu l'impression que l'énergie se stackait et augmentait beaucoup plus rapidement que d'habitude (facilité à slow les limons).
Je n'ai pas testé personnellement car dps. Est-ce un comportement normalement attendu ?

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Putricide
- Sort en question / Phase du boss en question / Emplacement: personne dans l'abomination sur putricide.
- Composition du groupe: 

Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

je ne connais pas le comportement normalement attendu ici donc est-ce normal ?

**Captures d’écran / Vidéos**

---- : je n'ai pas fais l'abo donc pas de focus sur la barre d'énergie.

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Ca a ete reconfirme par quelqu'un ? Ou alors c'est juste une sensation et en fait ca marche bien ?

**Comment by gtschanz** [comment]
j'ai testé à titre personnel (bon j'avais un rdrood; mais effectivement j'avais 100 d'énergie en temporisant un peu sur le premier limon genre dès que le premier limon a pop je l'ai slow et en 2 sec après j'étais quasi full énergie; j'avais l'impression que mon énergie remontait vraiment plus vite quand je buvais après je sais pas si c'est lié au bonus que t'apporte le rdrood dans la régénération d'énergie

**Comment by gtschanz** [comment]
j'irais test en hm sans rdrood et encore une fois avec pour voir si y'a une différence

**Comment by joshwhedon** [comment]
Hum le bonus de druide devrait pas avoir d'influence. L'energie se regenerait pas toute seule par hasard ? Sans rien boire ?

**Comment by gtschanz** [comment]
j'avais pas cette impression que ça se régénérait tout seul; après je l'ai fais qu'une fois depuis l'abo et j'avais cette impression quand je buvais moi même. faudrait que je refasse et stream pour ensuite analyser le fight

**Comment by gtschanz** [comment]
j'ai retesté l'abo il m'arrive d'avoir des proc anormal d'énergie; j'ai eu plusieurs fois +16 d'énergie alors que je ne buvais pas; (ok y'avait un rdrood) mais même si je bénéficie de son revitaliser ça serait +8 maximum (d'après la spécialisation) - je vais voir pour le testé en hm sans druide pour voir si y'a une différence

**Comment by joshwhedon** [comment]
Oui je crois que c'est le revitaliser :D . Je corrige prochaine maj. Probablement un bug existant qu'on a jamais remarque / signale.
