### ISSUE TITLE
problème d'intertaunt sur putricide 25 Hard Mode

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#266]
**Description**

Les tanks et les cacs qui ont pris des stack en p3 de putricide on eu des difficultés à l'aggro sur les intertaunt quand ils ont pris des stacks.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Putricide
- Sort en question / Phase du boss en question / Emplacement: P3 après la deuxième transition.
- Composition du groupe:
Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
on taunt, on prend une stack lorsque dbm affiche 0.0sec à la prochaine stack et puis le tank retaunt pour reprendre le boss

**Captures d’écran / Vidéos**

---- : aucun stream réalisé pendant le down (se référer au vidéo down sur off d'époque).

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
C'est quoi un intertaunt ? Quand vous echangez rapidement l'agro entre deux tanks avec un taunt ?

**Comment by gtschanz** [comment]
oui; après je peux me renseigner à ce sujet (je rapporte juste ce soucis vu qu'on me l'a signalé) mais je n'ai pas taunt à ce moment

**Comment by joshwhedon** [comment]
Je mets en place un correctif, je sais pas si ca va marcher mais ca devrait.
