### ISSUE TITLE
Ciblage aléatoire sur l'aile de sang pour avoir l'orbe - Sévérité BASSE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#267]
**Description**

Avant sur l'aile de sang on devait focus l'archimage pour récupérer l'orbe et permettre à un dps de la prendre et de d'avoir un dps plus important; maintenant c'est un mob aléatoirement qui cast l'orbe et on ne le sait qu'une fois le cast démarré pour le focus et le frapper. Est-ce un comportement normalement attendu ???

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: trashs avant les princes ET avant la reine ou il y a une orbe
- Sort en question / Phase du boss en question / Emplacement :  voir en haut
- Composition du groupe: 

Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Aucune idée; pouvez-vous nous dire si cela est un comportement normalement attendu ?

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by Killyana** [comment]
Oui c'est normal, avant je l'avait pas fait par paraisse.
