### ISSUE TITLE
déclenchement des pièges chasseur sur les trashs avant les boss de givre - Sévérité BASSE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#268]
**Description**

j'ai voulu poser un trap de givre au cac des trashs pour les ralentir et les slow pour les pack et les frapper; le fait que les trashs de givre passant dessus ne les déclenche pas N'EST PAS normal; les pièges doit AUTOMATIQUEMENT se déclencher si une target rouge (ennemi) passe dessus) ils n'ont pas d'insensibilité à avoir dessus comme les boss ! (je n'ai pas testé sur les autres ailes; ça doit probablement être la même

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: trash de givre (surement le raid)
- Sort en question / Phase du boss en question / Emplacement: trash début d'aile de givre avant Valithria
- Composition du groupe:
Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Les pièges doivent se déclencher se les trashs mobs.

**Captures d’écran / Vidéos**

---- : pas de vidéos d'offi trouver sur les trashs.

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Heu, c'etait avant ou apres la mise en place du fix sur les pieges chasseur ? Parce que les pieges chasseurs ne marchaient pas d'une maniere generale.

**Comment by gtschanz** [comment]
piège freezing (constaté ce soir entre 22H30 et 00H00)

**Comment by joshwhedon** [comment]
OK bien possible que la maj ait pas ete passee. Je vais demander.

**Comment by joshwhedon** [comment]
Les pieges de chasseur doivent etre regles maintenant.

**Comment by Endalaust** [comment]
Il faut faire attention aux états, actuellement le fait de fermer une issue sur le bt implique que : 
Le correctif a été développé. En revanche, il faut ensuite 2 autres étapes : 

1. Lancer une compilation du core
2. Redémarrer le core

Je suis en train de plancher sur une manière d'afficher ces différents états pour simplifier la compréhension et le suivi du bugtracker.
