### ISSUE TITLE
GROS BUG sur Valithria en ICC 25 Hard Mode - Sévérité TRES TRES IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#269]
**Description**

Les heals perdaient maximum 300 pv / sec avec stack x9 et très très peu d'adds arrivaient sur le raid.
Le raid sur ce fight était dans un fauteuil littéralement. je n'ai jamais vu Valithria se faire remonter si facilement pour un 25 HARD MODE.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 HM
- Boss: Valithria
- Sort en question / Phase du boss en question / Emplacement: prise de stack portails et heals en dehors + trashs pendant le boss
- Composition du groupe:

Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Les heals doivent prendrent des dégâts crescendo en fonction du nombre de stack - s'il monte à 9 stack ils doivent perdre beaucoup de points de vie -- ATTENTION on doit pouvoir stack jusqu'à 9 et heal valithria sans die. mais cela doit mettre la pression sans se mettre le guide en hpal ou avec la glyphe en cham qui nous rend 20% de notre vie par heal qu'on met sur vali ou de s'être full hot en druide on n'est pas supposé survire avec 9 stack.
De plus les ads doivent pop plus massivement et rapidement.

**Captures d’écran / Vidéos**

---- : voir vidéo down offi de valithria

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Personnellement the perds environ 200 pv par stack, donc a 9 stacks environ 1800.

**Comment by gtschanz** [comment]
c'est ridicule; avant la merge le boss était beaucoup plus compliqué je prenais des stack de -5/6K de mémoire; enlever 1K8 hps ça fait passer ce boss hm à un boss fauteuil; je vais voir si je trouve la vidéo offi lié à ça; car ça m'étonnerais qu'on perdu si peu de vie

**Comment by gtschanz** [comment]
en mode 25 Hard Mode

**Comment by Killyana** [comment]
Avant ID - 71940 Cauchemars tordus était bug est scale avec la PS du joueur, maintenant les valeurs concordent avec ceux d'offi: http://www.worldoflogs.com/reports/ax7c5fwljuvuuir1/xe/?s=14240&e=14579&x=spell+%3D+%22Twisted+Nightmares%22%0D%0AAND+type+%3D+TYPE_DAMAGE

**Comment by Killyana** [comment]
Je me suis trompé sur ce bug, le tick du debuff doit hériter de la ps du joueur et être affecté par les résistances:
[23:52:36.184] Nightmare Cloud Twisted Nightmares Galadedrid 1455 (R: 1500)

**Comment by joshwhedon** [comment]
Nah il se stack jusqu'a 100. Ignorer les resistances, ouai il le fait : (SPELL_ATTR4_IGNORE_RESISTANCES)
Mais du fait que les degats dans le log restent tres faibles, malgre la possibilite de stack, si la PS rentrait en consideration, ce serait pas du 1500 qu'il prendrait mais du 10000. Les guides indiquent aussi que tu peux aller jusqu'a 20 stack sans prendre trop trop de degats. 20 stacks ca fait du 4000 par tick, donc ca se tient.

**Comment by Killyana** [comment]
[23:50:57.673] Nightmare Cloud Twisted Nightmares Quaterstaff 291 (R: 700)
La on voit 991 dégâts infligé dont 700 résistance, avant la merge c'était pareil, plus le joueur a de la PS plus il prenait cher

**Comment by joshwhedon** [comment]
oui ca fait 1600, 8 stacks. Non ?

**Comment by Killyana** [comment]
Oui mais les logs indiquent des résistance et les valeurs ne sont pas exactement des multiples de 200

[23:52:33.586] Nightmare Cloud Twisted Nightmares Chiladas 1358 (R: 1400)=2758

http://www.worldoflogs.com/reports/ax7c5fwljuvuuir1/xe/?s=14240&e=14579&x=spell+%3D+%22Twisted+Nightmares%22%0D%0AAND+type+%3D+TYPE_DAMAGE

**Comment by Killyana** [comment]
Les flags niveau DBC ne sont pas fiables parce que coté blizzard ils utilisent pas les même dbc coté serveur et clients.
Durant le passe de l'alpha vers la beta, ptr et prod, ils font beaucoup de changements et ces changement ne finissent pas sur les DBC coté client.
La c'est une vidéo d'offi on voit un chaman qui entre dans les portails et choppe 6 stacks
et voit ensuite les dégâts qu'il prend: 2160, 2040, 2040, 1920
A 10 stacks : 3200 3000 3400

Peut être que sa prends pas les résistances en compte mais sa scale clairement avec la PS

**Comment by Killyana** [comment]
Oui je dis des conneries, le texte flottant groupe les ticks et n'affiche pas les resists
