### ISSUE TITLE
Event en bas de Valtithria = CASSé - Sévérité BASSE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#270]
**Description**

L'event en bas de Valithira (une fois le boss down) event avant syndragosa ne se déclenchait pas - résultat un mj est venu nous l'ouvrir mais cela n'a pas débloqué le TP (au wype = chemin à pieds..)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Event après Valithria
- Sort en question / Phase du boss en question / Emplacement: Event en bas
- Composition du groupe:

Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**
 
L'event doit se déclencher et le TP se débloquer une fois l'event fini sans avoir recours à un MJ.

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by Killyana** [comment]
Fixé demain matin
