### ISSUE TITLE
Guide de givre + grab sur froid cinglant - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#271]
**Description**

j'ai été guide de givre + grab sur un froid cinglant à 1 sec près je gelais le raid.... j'ai du botte fusée pour éviter le raid. Je ne connais pas le comportement normal; mais je doute que le gars guide de givre se fasse grab et 1 sec après le grab y'a l'impact de ce guide qui risque de geler le raid; 1 sec c'est très limite.. j'ai pu éviter la catastrophe mais c'est très rng (un gars sans les bottes fusée aurait tuer le raid).

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Hard Mode
- Boss: Sindragossa
- Sort en question / Phase du boss en question / Emplacement: P2 de sindragossa (- de 35%)
- Composition du groupe:

Tanks : Vaeren, Cutienight
DPS C : Bruxelles, Nojin, Gudrunn, pokerface, Zireal, Xyria, Lamenoire, Djah, Myko
CASTERS : Spitfire, Fairiver, Yorikaelle, zira, Gaea, Overfire, Almmina, Kelhrin, Truie, Maya
HEAL : Epsil, Kap, Margi, Roidelaforet, grossematou

**Comportement attendu**

Les timer sont soit en décalage entre les guide de givre / froid cinglant  // soit le gars guide n'est pas grab.

**Captures d’écran / Vidéos**

----: voir vidéo offi du down sindragossa.

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Je regarderai, probablement un bug existant cela dit, les timers ont pas change.

**Comment by toitit** [comment]
Avant la merge, les timings étaient identiques mais la personne ciblée n'était pas grab !

**Comment by joshwhedon** [comment]
Le grab il grab pas tout le monde ?

**Comment by joshwhedon** [comment]
https://www.wowhead.com/spell=70117/icy-grip on parle bien de ca ?

**Comment by Ischjgt** [comment]
Oui c'est ce spell pour toutes les difficultés,
En P2, Sindra cible un mec qui va choper le tombeau de givre, quand elle utilise sa poigne elle doit poigne tout le monde sauf le mec tombeau

https://www.youtube.com/watch?v=o89tT2o87r0 5minutes 5

**Comment by toitit** [comment]
J'ai regardé des vidéos d'offi (https://www.youtube.com/watch?v=O8NDBlSpM4g et https://www.youtube.com/watch?v=zopmjF3yUGs) et donc : sur offi le froid cinglant arrive APRES que le glaçon se soit posé sur se cible, et la personne glaçon n'est pas grab puisqu'elle est sous le glaçon. Sur woe, le froid cinglant arrive AVANT que le glaçon se soit posé sur sa cible (mais après que syndra ait choisi une cible). Avant la merge, cette personne ciblée n'était pas grab, mais maintenant elle l'est (ce qui est logique en soit puisqu'elle n'est pas encore en glaçon).

**Comment by Ischjgt** [comment]
Chips

**Comment by toitit** [comment]
c'est de la triche l'edit :p

**Comment by joshwhedon** [comment]
Donc c'est bien une question de timer.

**Comment by gtschanz** [comment]
UP! ça nous l'a refait ce soir en ICC 25 Normal Mode guide de givre sur quelqu'un et froid cinglant 1 sec après il a sprint féral pour éviter le raid (dans les 2 raids y'avait la malé langage) je sais pas si c'est ça qui change les timers pour le coup ; les 2 fois on a eu de la chance sur la personne ciblé !

**Comment by Killyana** [comment]
Pas sure que la maj a passé

**Comment by joshwhedon** [comment]
Il y a 4 heures la maj etait pas encore passee desole. Il y a eu un crash il y a 2 heures qui l'a passe normalement.

**Comment by gtschanz** [comment]
ok; met le en close ce bt; si jamais je le ré-open
