### ISSUE TITLE
[quete/mage] Enqueter dans le magasin de l'alchimiste

### ISSUE THREAD

**Issue by zanzlibar** [way-of-elendil/3.3.5#273]
**Description**
Les apparitions du vide ne peuvent être capturées dans la boite prévue à cet effet.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Fossoyeuse, quartier de la magie
- horde/mage
- enquêter dans le magasin de l'alchimiste questID=1960
- Anastasia Hartwell

**Comportement attendu**
Les caisses de stockage ( https://fr.classic.wowhead.com/item=7247/caisse-de-coffres-de-stockage ) requiert que les pnj soient "étourdi" mais ils deviennet amicaux, s'enfuient et disparaissent, avant qu'on puisse les capturer. Le sort se lance, mais impossible de capturer à temps les entités.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
https://fr.classic.wowhead.com/quest=1960/enqu%C3%AAter-dans-le-magasin-de-lalchimiste
je ne sais pas si ça peut aider, mais il y a en principe une quête équivalente côté alliance: https://fr.classic.wowhead.com/quest=1920/trouver-le-solitaire-bleu.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/1a1489d73e9b69b5c5465b2963080500fe050fa6
