### ISSUE TITLE
Spell: Tear Gas

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#274]
**Description**

Disparition du rogue et invisibilité du mage n'empeche pas le stun du gaz lacrymogène en transi

L'aura une fois invisible: 32612 [Invisibilité] 
L'aura après vanish: 1784 [Camouflage] 
Gaz lacrymo : https://woehead.way-of-elendil.fr/?spell=71617

** Comportement attendu**

Commentaire de la 3.3.2 sur wowhead
It is possible to use Invisibility as a mage, and Vanish as a rogue, just as he casts Tear Gas, and you can continue dealing damage as you completely avoid Tear Gas.

https://fr.wowhead.com/npc=36678/professeur-putricide#english-comments
(Désolé, c'était peut-etre déjà là avant)

**Comment by joshwhedon** [comment]
Oui c'etait definitivement la avant. Et je doute qu'on corrige.

**Comment by Killyana** [comment]
Vues les attributs du spell, je vois pas comment il peut rater  Invisibility ou Vanish
Attributes: 0xA0000000 (SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY, SPELL_ATTR0_CANT_CANCEL)
AttributesEx1: 0x00000088 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_CANT_BE_REFLECTED)
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
AttributesEx3: 0x00040000 (SPELL_ATTR3_IGNORE_HIT_RESULT)
AttributesEx5: 0x00000400 (SPELL_ATTR5_HIDE_DURATION)
AttributesEx6: 0x01000000 (SPELL_ATTR6_CAN_TARGET_UNTARGETABLE)

**Comment by Sungis18** [comment]
Les attributs sont en effets ceux mentionnés par @Killyana, il y a peut être eu un temps (dans une màj précédente) où il était possible de vanish/invis' (comme on peut le constater dans cette séquence : https://youtu.be/n4SUQ323mGs?t=106) mais étant donné que l'on constate ces attributs sur la version 3.3.5a des DBC cela n'aurait pu constituer qu'un ajout et donc un ajustement/correction volontaire.

Par conséquent, je clôture.
