### ISSUE TITLE
Quest: Problème pour rendre une quête 

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#275]
**Description**
Les joueurs peuvent encore rencontrer des problèmes avec les quêtes comme "Ils grandissent tellement vite", avec des items à rendre sans tag Objet de quête

(j'ai pas encore de retour pour les quêtes avec objet de quête et l'histoire de la banque)

=> Abandonner et reprendre la quête résout le problème

**Comment by joshwhedon** [comment]
Je sais pas comment reproduire. J'ai tente de garder cette quete pendant une semaine en local, mais elle est toujours complete pour moi.

**Comment by Ischjgt** [comment]
(J'ai enlevé le label cannot reproduce, je t'ai expliqué la démarche dans le ticket #961 )

**Comment by joshwhedon** [comment]
Je mets un correctif prochaine maj, j'ai teste un peu ca a l'air bon mais faudra voir si ca casse rien.
