### ISSUE TITLE
Quest:  Couper l'ennemi de ses renforts

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#276]
**Description**

"Quête [10144] Couper l'ennemi de ses renforts :
Le sort [34387] Détonation de pierres runiques ne valide pas l'objectif. Quand on finit de l'incanter, il indique « Vous n'avez pas de cible »."

**Comment by Killyana** [comment]
Pas un bug même sur offi il faut être dans le transporteur
