### ISSUE TITLE
Quest: Dur à avaler

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#279]
**Description**
12049 - [Dur à avaler] 
1. 36732 - [Charge explosive toute-puissante] se lance quand on voit écrit "Le jormungar trapu vacille brièvement, et ouvre grand la bouche." mais n'a aucun effet sur le NPC Entry: 26293.

2.a. Si plus d'un jormungar aggro, impossible de lancer la charge explosive
b. Pareil si le jormungar a reset combat

**Comment by Killyana** [comment]
Fixé par: https://github.com/TrinityCore/TrinityCore/commit/64246306678c12024f401c2c1934a8b452057452

**Comment by Killyana** [comment]
Fix prochaine maj
