### ISSUE TITLE
Quest: Il n'est pas nuisible

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#280]
**Description**
1. Possible de siphonner le même cadavre plusieurs fois
2. une fois le messager invoqué, la quête n'est pas validée

Quest:
13365 
13344 
13358
13342 

NPCs:
- Enslaved Minion Entry: 32260.
- 32316 - [Sombre messager] 

Item:
44433 - [Bâtonnet de siphonnage] 

Gob:
[Summoning Stone] GUID: 62569 ID: 193939

**Comment by Killyana** [comment]
L'utilisation de l'item est corrigé, mais sans le despawn du corps (comme sur offi)
La canalisation sur le cristal : Credit quest + check des reagents + suppression des reagents sera corrigé par Josh.

**Comment by MalOuKenji** [comment]
Testé ce matin la quête n'est toujours pas validée après l'invocation du messager.

**Comment by joshwhedon** [comment]
@Killyana Je devais faire plus que permettre au siphon de fonctionner ?

**Comment by MalOuKenji** [comment]
Siphonner le cristal fonctionnait déjà avant, et l'invocation du messager aussi, mais c'est juste la quête qui ne se valide pas

**Comment by Killyana** [comment]
Je crois que le spell auquel t'as linké lescript est incorrect: `spell_id`=38736
Ça doit être https://woehead.way-of-elendil.fr/?spell=60561 si je me trompe pas.

**Comment by joshwhedon** [comment]
Ha oui le con.
