### ISSUE TITLE
Guerrier / charge-interception 

### ISSUE THREAD

**Issue by JAGGERstark** [way-of-elendil/3.3.5#282]
Pa de coup blanc après une charge ou interception avent 4 sec
les technique charge et interception compte comme un auto-hit

- Guerrier 
- orc
- spé arme
- charge / interception
- pve / pvp

**Comportement attendu**
la charge et l'interception ne doive pas consommer des auto-hit
un coup blanc dois parvenir instantanément a la suite de l’arriver au cac

**Comment by joshwhedon** [comment]
Vous avez des preuves de ca pour la 3.3.5 ?

**Comment by JAGGERstark** [comment]
https://wotlkdb.com/?spell=11578
https://wotlkdb.com/?spell=20252

**Comment by JAGGERstark** [comment]
https://www.youtube.com/watch?v=v2peoyaNRkw
https://www.youtube.com/watch?v=7ztjPaUylr4
https://www.youtube.com/watch?v=0EsHTL8DKNc
https://www.youtube.com/watch?v=S0CIUY8ra64

**Comment by sithis2a** [comment]
Pour être plus précis, le coup blanc doit partir si le swing timer est ready.
Deux exemples pour illustrer:
- Début de duel donc pas encore de coup blanc lancé. Si je charge, le coup blanc doit partir dès que je suis à porté.
- Je suis en cours de duel, je viens de mettre un coup blanc avec une arme 3.60 par exemple. Mon prochain coup blanc ne doit pas partir avant 3.6 sec (modulé par la hate ofc), donc si je charge il n'y a pas de coup blanc qui doit partir en arrivant à portée.

Ici j'ai l'impression que la charge/interception reset le swing timer.

**Comment by joshwhedon** [comment]
Vous pensez que c'est un bug nouveau ? Ou ca a toujours ete le cas et jamais signale ?

**Comment by sithis2a** [comment]
J'ai l'impression que c'est un bug nouveau. Il ne me semble pas avoir eu ce soucis auparavant. Après peut être était-il moins flagrant.
Je vais faire un peu plus de test parce que j'ai aussi l'impression que cela dépend des mouvements de la cible. J'ai refait des duels entre temps et pour certains le coup blanc partait bien sur la charge (avec spam de macro /startattack sur la charge) et des fois non.

**Comment by joshwhedon** [comment]
Ok merci. Je regarderai a l'occasion quand les bugs avec une plus haute priorite seront regles.

**Comment by JAGGERstark** [comment]
oui c nouveau
