### ISSUE TITLE
Dps du pet BM esprit de bête aux Grisonnes

### ISSUE THREAD

**Issue by mvpii** [way-of-elendil/3.3.5#284]
Hello,
Après avoir dompté le spirit beast aux Grisonnes, on remarque rapidement qu'il a un soucis commun a quelques"pet", c'est a dire qu'il dps comme un bas lvl.

Merci pour le boulot déjà accompli et bon courage pour la suite !

Bye

**Comment by joshwhedon** [comment]
Question : apres l'avoir renvoye et reinvoque, il fait toujours des degats tres bas ?

**Comment by mvpii** [comment]
Ça fonctionne, merci pour l'astuce / info.

Good game !

**Comment by joshwhedon** [comment]
Un correctif sera applique pour que les pets aient les bons degats des leur obtention.
