### ISSUE TITLE
Boss: Ulduar-Kologarn 25 bras+rayon

### ISSUE THREAD

**Issue by Tontonsid** [way-of-elendil/3.3.5#285]
Testé en Ulduar 25 Kologarn grab 3 personnes par 3 au lieu d'une par une dans son bras droit et ses rayons oculaires ne pop pas

**Comment by Ewilanwoe** [comment]
Attraper 3 personnes en Raid 25 est le comportement normal de Kologarn. Le fait qu'il n'en attrapait qu'un seul auparavant était un bug.

**Comment by Tontonsid** [comment]
oui je me suis justement fait la réflexion en écrivant ^^' par contre reste toujours le souci des rayons absents

**Comment by joshwhedon** [comment]
Oh, il peut attraper 3 personnes ... ok c'est nouveau :D. J'essaie de corriger ca avant le prochain reset au plus tard. Merci de l'info.

**Comment by Limoustique** [comment]
Les dégâts dans le bras sont abusés par contre : autour de 20k le tic. Et il ne lâche pas les gens qu'il a tué (on ne sait pas s'il finit par lâcher les gens vivants, vu les tatanes il ne nous a pas laissé le tester :D)

**Comment by joshwhedon** [comment]
Les degats dans le bras sont surement du au fait que ca prend la ps du joueur :D. Je corrige ca.
