### ISSUE TITLE
Boss: Ulduar 25-Défenseur farouche d'Auriaya

### ISSUE THREAD

**Issue by Tontonsid** [way-of-elendil/3.3.5#286]
Les défenseurs farouches d'Auriaya one shot instantanément la personne sur laquelle ils pop. Un plaqueux stuff icc prend un os de 29k direct au pop

**Comment by Limoustique** [comment]
A rajouter sur Auriaya : ses adds (et les trash dans le même anneau) passent souvent sous le sol quand ils sont censés être en haut des escaliers. Auriaya ne nous l'a pas fait mais c'est pas improbable qu'elle soit concernée aussi.

**Comment by joshwhedon** [comment]
Vous avez une idee plus precises des degats normaux ?

**Comment by Killyana** [comment]
Le mob a 8 x https://woehead.way-of-elendil.fr/?spell=64455
Je pense qu'avant sa fonctionnait pas correctement, je vais nerf un peut les dégâts pour avoir un truc correcte avec 8 stacks

**Comment by Killyana** [comment]
En 25:
![image](https://user-images.githubusercontent.com/6587064/78940950-003fb380-7ab7-11ea-8e45-10885dea4c76.png)
En 10 c'est moins, par contre il pourra OS les tissues, il faut le garder sous contrôle quand il a beaucoup de stacks

**Comment by joshwhedon** [comment]
Ce qui est normal de toute facon. Merci
