### ISSUE TITLE
Boss:Ulduar 25- Yogg-Saron

### ISSUE THREAD

**Issue by Tontonsid** [way-of-elendil/3.3.5#288]
Rien n'a signaler pour la p1 et la p2 sur Yogg, c'est en p3 que ça se gâte pas mal. La hit box de Yogg est cassée: impossible pour les cac de le taper sans être bump car trop au cac. Même les jugements des paladins qui ont un minimum de range à distance ne l’atteignent pas. Pareil pour ce qui est de le loot, on a dû aller plein centre du boss pour prendre les item dessus.

**Comment by joshwhedon** [comment]
Merci pour ces rapports de bug, j'essaie de regler tout ca au plus vite.

**Comment by Tontonsid** [comment]
ah juste pour la p2, on ne sait pas si c'est normal mais les portails pour sortir des rêves Yogg ne sont pas tout de suite accessibles. Les gens hier ne pouvaient pas les prendre avant 5sec du sombrer dans la folie

**Comment by Killyana** [comment]
Hit box corrigé avec la prochaine maj.
Pour les portails faudra voir si la distance d’interraction n'est pas supérieur à la portée du spell ou une connerie du genre.
