### ISSUE TITLE
Salles de setthek (trashs mobs)

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#290]
**Description**
J'étais à la salle de setthek (donjon BC à auchidoun) y'a des ads à l'étage qui fear / stun; le hic c'est que lorsqu'on se mange un fear ou stun le prochain fear ou stun lancé par les ads doit être dégressif il ne doit pas avoir la même durée ! alors qu'actuellement on peut mangé des fear à la chain de 5 sec ; normalement c'est comme les fear démoniste ils doivent être dégressif + on se fait fear; - ils durent longtemps.
De plus le seigneur anzu (boss qu'on invoque en druide est bugué; il a une phase ou il peut normalement rien faire; c'est même marqué dans le descriptif sous lui et on peut pas le tapper - actuellement il peut cast durant cette période

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: salle de séthek (donjon bc)
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): testé en donjon HM (pas testé en nm)
- Boss (dans la salle du boss ANZU - celui qui drop la monture 100%
- Sort en question / Phase du boss en question / Emplacement - ads avant salle de ANZU / salle de ANZU et couloir après
- Composition du groupe: figaro, félindra

**Comportement attendu**

Les fears doivent être dégressif + le boss anzu ne doit pas pouvoir cast pendant sa phase d'invulnérabilité

**Captures d’écran / Vidéos**

----
**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Alors les retour degressifs en pve, j'aimerai savoir si c'est reel. Vous avez des infos la dessus ? Parce que j'ai entendu des trucs conflictuels sur le sujet.

**Comment by gtschanz** [comment]
je ne trouve pas de vidéo d'époque offi pour corroborer mes dires mais je sais que d'époque je l'avais farm sur offi sous bc en plus (concernant le dégressif il ne s'applique que sur les trashs de setthek) après ailleurs en pve de manière général je sais pas
