### ISSUE TITLE
Guerrier / Mort soudaine+Execution

### ISSUE THREAD

**Issue by JAGGERstark** [way-of-elendil/3.3.5#291]
je suis a 100pts de rage "Mort soudaine" proc j'utilise exécution je suis a 70pts de rage

- Guerrier
- orc
- arme
- Mort soudaine > https://wotlkdb.com/?spell=29724
- Execution > https://wotlkdb.com/?spell=47471
- Pve / Pvp

**Comportement attendu**
je suis a 100pts de rage "Mort soudaine" proc j'utilise exécution je suis a 70pts de rage + 10pts de rage rendu > a la suite de la technique je remonte a 80Pts de rage

"c la même chose que le glyphe frappe héroïque (https://wotlkdb.com/?spell=58403) ou je dois regagner de la rage instantanément après la technique, a ne pas confondre avec réduire le coup de la technique"

**Comment by joshwhedon** [comment]
Et je suppose que si tu es a 90 points de rages, tu utilise execution, et dans ce cas la ca marche ? Ca marche pas que quand t'es full rage ?

**Comment by JAGGERstark** [comment]
oui j'ai prie 100 pour exemple simple

**Comment by JAGGERstark** [comment]
en faite le sort use 15 de rage mes tu peux le fair augmenter jusque a 30 de rage maximum, plus il mange de rage plus il dps, qu'il me prenne 15 25 ou 30 de rage il dois m'en rendre 10 a la fin si j'ai la condition mort soudaine

**Comment by joshwhedon** [comment]
En fait je me demandais juste si le soucis est pas que la rage est rendue avant le lancement du sort, du coup si tu as 100, tu es deja au max donc rien de rendu. Pour ca que je demandais avec 90 plutot que 100,

**Comment by JAGGERstark** [comment]
suis pas arriver a le fair a 90 mes la viens de le refaire a 95 suis tomber a 65

**Comment by joshwhedon** [comment]
Hum, je viens de lire la description de l'aptitude. Ca dit pas que tu recupere 10 de rage. Ca dit que tu garde au moins 10 de rage. Ce qui veut dire que si tu as 15 de rage, que tu utilise execution, tu vas etre a 10 de rage, pas 0.
"In addition, you keep at least 10 rage after using Execute."

**Comment by joshwhedon** [comment]
Et j'ai teste, ca ca marche correctement.

**Comment by JAGGERstark** [comment]
je viens de compare la Fr et la Us et c pas expliquer exactement pareille " vous conservez 10 points de rage après avoir utilisé Exécution" "vous gardez au moins 10 points de rage après avoir utilisé Exécution"
si je comprend bien sa marche que si tu vas tomber a 0 

bn si tu dit sa marche temps mieux
merci pour d'avoir regarder en tous cas

**Comment by joshwhedon** [comment]
Bah en fait meme en anglais c'est pas super clair, j'ai surtout compris apres avoir matte le code qui a implemente comme ca. Et la ca a fait tilt : ouai en fait ... Blizzard est juste pas clair :D .
Et pas de soucis, je comprends bien que ca ait ressemble a un bug.
