### ISSUE TITLE
BUG repop des ads au joug - Sévérité BASSE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#292]
**Description**

Les élémentaires de feu au joug repop INSTANTANEMENT (les gros) résultat le farm des feux éternels peut être spam; il doit y avoir obligatoirement un temps de repop d'ad; ils ne sont pas supposé repop 10 sec après leurs mort pour certains quasi

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement / Zone / Arène / Champ de bataille: Au joug au pop des élémentaires de feu
- Faction / Race / Classe du personnage utilise

**Comportement attendu**

le temps de repop trash doit être plus conséquent (de manière général j'ai également farmé des trash mobs à la kapitalrisk (scholazar) et eux aussi repop trop rapidement; je me demande si le repop trashs n'est globalement pas cassé sur le serveur (ça repop plus vite) ou si c'est le comportement normalement attendu (concernant le joug ça repop INSTANTANEMENT)

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Globalement, les repop sont plus rapides, parce qu'ils ont ete corriges. Maintenant repop instant non c'est pas normal on regardera.

**Comment by gtschanz** [comment]
y'a pas tout les ads qui repop instantanément dans la zone précisé uniquement certains des gros; mais si tu fais un petit circuit de farm de 3 grands tu peux spam ce petit passage; si tu veux je peux te montrer leur emplacement ig

**Comment by gtschanz** [comment]
car du coup bcp de monde les farms en mode ub

**Comment by gtschanz** [comment]
(plus que d'habitude

**Comment by Killyana** [comment]
Corrigé
