### ISSUE TITLE
[Boss] Magus Telestra

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#293]
**Description**

testé hier (je sais pas si corrigé depuis) le 1er boss de la salle nexus HM (pas testé en nm) à plusieurs phase avec des TP au centre ce qui le fait bug; après le premier TP il disparait et on peut plus le tuer; résultat le dernier boss on peut pas le faire car il faut avoir fait les boss précédemment pour le libérer

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: Nexus
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): Nexus HM (pas testé en nm doit être pareil)
- Boss: premier 1 du donjon celui qui fait les tp
- Sort en question / Phase du boss en question / Emplacement: dans la salle du 1er boss
- Composition du groupe: félindra + 4 pick up (en tag hm)

**Comportement attendu**

le boss doit réaparaitre après chaque TP et doit être tuable

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Donc elle a disparu et pas fait pop ses doubles ?

**Comment by gtschanz** [comment]
c'est ça
