### ISSUE TITLE
"Vanish" (disparation) des voleurs sort aussi la cible de combat

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#294]
**Description**
Le sort "Disparation" du rogue qui est censé faire sortir le rogue de combat fait aussi sortir sa cible de combat, permettant des actions impossible

**Étapes de reproduction**
Prenez un rogue, faites un duel rentrez votre ennemi en combat, faites un vanish, il va sortir de combat.

**Comportement attendu**
Le sort disparition fait sortir le rogue de combat mais sa cible est toujours soumis à la durée de sortie de combat de 5s.

**Ressources additionnelles**
Nouveau bug depuis la merge, n'était pas présent avant
https://wotlk-twinhead.twinstar.cz/?spell=1857

**Comment by Killyana** [comment]
C'est impossible, l'autre joueur doit avoir une référence de combat, il peut pas être en combat avec rien du tout

**Comment by Justforsoloq** [comment]
Comment ça c'est impossible ? 
L'état de combat dure 5s. Donc si un joueur est en combat même si sa cible vanish il va rester en combat pendant 5s https://wowwiki.fandom.com/wiki/Combat
"In PvP, a player will leave combat if they have not attacked or been attacked for 5 seconds, or all the enemy characters that have attacked you are killed. "
Bref. 
Donc le bug ici est que si tu vanish, ta cible n'a pas cet état de "out of combat" de 5s et sort de combat instant.

**Comment by Killyana** [comment]
Le système de combat a été réécrit je ne sais pas si c'est possible de corriger ça.

**Comment by joshwhedon** [comment]
Hum, normalement le systeme de combat est code pour permettre specifiquement ca, mais de ce que je vois ca a l'air de bugger. Par contre je sais pas trop comment le nouveau systeme marche, donc ca va etre un peu galere. Je jeterai un oeil plus precisement plus tard.

**Comment by sithis2a** [comment]
Sur le coup j'ai l'impression que votre nouveau système de combat est basé sur du PvE et se comporte pareil en PvP. En effet même s'il on tue quelqu'un en PvP la fin de combat n'est pas immédiate car soit on est encore en combat avec d'autre personnes, soit la règle des 5 secondes doit s'appliquer.
Sur WoE, lors d'un bg, le fait de tuer un joueur nous sort directement de combat si personne d'autre n'est en train de nous taper (je parle de damages actifs, pas de dots qui traînent).

**Comment by joshwhedon** [comment]
Non, le nouveau systeme a le pvp de gere a part.

**Comment by joshwhedon** [comment]
C'etait a cause d'un changement mis chez nous il y a longtemps et incompatible avec le nouveau systeme.
