### ISSUE TITLE
[Quête] [Hodir] gains réput Une faible lueur d'espoir

### ISSUE THREAD

**Issue by rommni** [way-of-elendil/3.3.5#295]
**Description**
La quête une faible lueur d'espoir (12956), est censé depuis la 3.3.0 donner une fois réalisée
28 600 au lieu de 22 000 points de réputation envers les Fils d'Hodir, et ainsi faire passer directement honoré au lieu de neutre. 
Je n'ai pas pensé au moment du rendu de la quête à vérifier le nombre de points cependant je peux constater que je suis 2/3 quêtes plus loin dans la suite neutre et non honoré, j'en déduis que le soucis viens surement de là.

**Étapes de reproduction**
Effectuez la suite de quête des fils d'hodir jusqu'à cette quête et vérifier le gain en réputation à la fin de la quête

**Comportement attendu**
La quête doit donner 28 600 points de réputations et nous rendre honoré auprès des fils d'hodir

**Ressources additionnelles**
Wowhead de la quête: https://fr.wowhead.com/quest=12956/une-faible-lueur-despoir
Information sur le changement de la 3.3.0: https://wowwiki.fandom.com/wiki/Quest:A_Spark_of_Hope (l'info doit surement pouvoir être trouvé ailleurs aussi je l'ai vu plusieurs fois sur des commentaires sur divers site)
La suite de quête des fils d'hodir: https://wowwiki.fandom.com/wiki/The_Sons_of_Hodir_quest_chain

**Comment by jeremkid** [comment]
Bonjour j'ai aussi un probleme avec la quete  moi quand j'ai rendu  "Le feu du raffineur" j'ai tout de suite eu "Forger une alliance".Donc je n'ai pas eu  faible lueur d'espoir .J'ai donc abandonner  "Forger une alliance" Mais  la quete  "faible lueur d'espoir"  n'ai pas donner a"L’enclume de Fjorn" donc je suis bloquer  pour la suite de quete.
Merci d'avance.

**Comment by Killyana** [comment]
@jeremkid Il faut aller voir Thorim au temple de tempête.
Même si la réputation donné n'est pas correcte sa bloque pas la chaîne des quêtes.
Au pire demande un MJ IG.

Bug fixé avec la prochaine MAj

**Comment by jeremkid** [comment]
@Killyana Deja vue avec un MJ la quête ne mas pas était donner mémé avec thorim

**Comment by Ischjgt** [comment]
T'es co là ? Tu as vu ça avec qui ? Nom du pers IG ?

**Comment by jeremkid** [comment]
non c'est bon le probleme a etait regler avec la mage j'ai reussi a bidouiller xD meme ci j'ai pas eu la quete lueur d'espoir
