### ISSUE TITLE
Immo conflag instant

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#296]
**Description**
Le sort conflagration peut être lancé instantanément à la poste de l'immolation

**Étapes de reproduction**
Prenez un démo destru, faites immolation puis conflagration instant derrière. 

**Comportement attendu**
La conflagration n'est applicable qu'après l'attente d'un gcd après la pose de l'immolation.

**Ressources additionnelles**
https://www.youtube.com/watch?v=TJQn1OVFCjw&feature=youtu.be&t=8m39s
(8mn39-8mn41s) vidéo retail. Cobrak pose son immolation et il doit attendre un "GCD"  (delay) avant de pouvoir conflagration.

**Comment by joshwhedon** [comment]
Y'a pas de gcd, le client a l'air de mettre du temps a reagir de la presence de l'immolation sur la video, et je sais pas pourquoi. Honnetement, pas grand chose qu'on puisse faire pour ca de notre cote. Quand immolation est applique sur la cible, la cible pas en etat de recevoir la conflagration.

**Comment by Justforsoloq** [comment]
https://www.youtube.com/watch?v=KUizH_eVcuA&feature=youtu.be&t=209
C'est un delay qui existe sur l'immo conflag pour empêcher justement l'immo conflag instant.
C'est une mécanique de Blizzard

**Comment by joshwhedon** [comment]
Question bete, tu sais si c'est le cas avec d'autres trucs du meme genre ? Par exemple en mage les sorts qui requierent la cible d'etre gelee, ce genre de truc ?Ou c'est vraiment unique a Conflag.

**Comment by Justforsoloq** [comment]
C'est vraiment uniquement la conflag. D'ailleurs sur offi des joueurs se plaignaient de cette mécanique (t'as des postes MMO-champions dessus).

**Comment by Justforsoloq** [comment]
https://www.mmo-champion.com/threads/658368-What-to-cast-after-immolate/page2

**Comment by joshwhedon** [comment]
Non mais je demande pour savoir si c'est un truc general a tous les sorts de ce genre, ou bien unique.

**Comment by Justforsoloq** [comment]
C'est unique (je n'ai mémoire d'aucune mécanique similaire)

**Comment by joshwhedon** [comment]
Ok ... salete de blizzard. Ils auraient au moins pu faire la meme chose pour tout.

**Comment by joshwhedon** [comment]
Bon j'ai reregarde, je pensais avoir un moyen de l'implementer mais ca va causer plus de problemes qu'en regler malheureusement :(.

**Comment by Xblugs** [comment]
Le gcd s'enclenche au lancement d'un sort et est terminé à la fin de l'immolation sauf en cas de hâte extrêmement élevée de la même manière qu'un joueur peut lancer une bombe vivante à la fin d'une boule de feu sans gcd supplémentaire.

**Comment by Justforsoloq** [comment]
Non Xblugs tu n'as pas compris. C'est une mécanique unique à la conflagration. 
Quand j'ai parlé de "gcd" c'était pour faire plus simple. C'est plus un "delay" qu'un "gcd"
Regarde les vidéos et le topic que j'ai link.

**Comment by Endalaust** [comment]
Je réouvre, juste pour voir si @Traesh a une idée sur le sujet

**Comment by Justforsoloq** [comment]
Petit up, le delay est bien présent maintenant mais trop long (1s entière au lieu des 0.5s présente dans les videos link)
(une autre vidéo si jamais : https://www.youtube.com/watch?v=J5_UHUD9pPA 1mn51-52)

**Comment by Endalaust** [comment]
Le fix a été revert @Traesh 
Semble être la cause des 4 crashs du jour
Attention au prochain push, c'est toute la MR qui a été revert
