### ISSUE TITLE
[ICC] Valithria - 10nm & 25nm

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#297]
**Description**
Visiblement le timer d'enrage est fixé à 60s environ. Passé ce délai les vagues sont celles de l'enrage, ingérable pour tous les modes 10 et 25 en nm et hm.

Tous les types de PNJs sont démultipliés sans exception.

J'ajoute une hight priority, tous les raids sont actuellement coincés nécessitant une intervention manuelle (5 à 6 raids par soirs)

**Comment by Ewilanwoe** [comment]
Même problème constaté en 10 HM le mardi 07/04/2020 : 

Visible dans cette vidéo à partir de 9:05 et jusqu'à la fin : 

https://youtu.be/0AXY9S_4xQc
