### ISSUE TITLE
Coup blancs de certains pets buggés

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#299]
**Description**
Certains pets invoqués comme l'ombrefiel ou l'elem de feu supérieur ont des dégats de coup blancs vraiment nerf (64 no crit 128 crit)

**Étapes de reproduction**
Prenez un SP ou un elem faites pop l'ombrefiel ou l'elem de feu sur poteau et regardez les coups blancs

**Comportement attendu**
L'ombrefiel ET l'elem de feu supérieur (pas testé d'autres familiers invoqués) doivent avoir des mélées biens plus hautes.

**Ressources additionnelles**
https://www.wowhead.com/spell=34433/shadowfiend#comments
https://github.com/TrinityCore/TrinityCore/issues/16011 (sur l'elem de feu pour le calcul des swings)
https://wotlk-twinhead.twinstar.cz/?spell=32982
https://wotlk-twinhead.twinstar.cz/?npc=15438

**Comment by Justforsoloq** [comment]
(Ps: j'ai aussi l'impression que les spells fire nova et fire blast de l'elem de feu ne font pas assez de dégats, via des calculs selon les formules appliqués mais pas sûr donc pas de report dessus encore).
Il marchait bien avant le merge, donc moyen de se baser sur vos formules pre merge.

**Comment by Killyana** [comment]
Fixé prochaine Maj: https://github.com/way-of-elendil/3.3.5/issues/277#issuecomment-610789086
spirit wolf, shadowfiend and water elemental

**Comment by Killyana** [comment]
Je ré-ouvre pour l'elem de feu et de terre

**Comment by gtschanz** [comment]
petite question les pets chasseur (pve) ont-ils été nerf ?  mon loup hier dépasse hier péniblement les 600 dégâts sur ses attaques
