### ISSUE TITLE
Ralentissement du slow givrefeu après un trinket

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#300]
**Description**
Le ralentissement du givrefeu reste appliqué même après un trinket PvP

**Étapes de reproduction**
Faites un duel contre un mage, demandez lui d'appliquer une FFB, trinket et regardez.

**Comportement attendu**
Le trinket pvp est censé enlever les slows.

**Ressources additionnelles**
https://wotlk-twinhead.twinstar.cz/?spell=47610
https://wotlk-twinhead.twinstar.cz/?item=51378

**Comment by Justforsoloq** [comment]
Pour l'instant le seul slow qui se comporte de cette manière que j'ai observé est le celui du FFB

**Comment by joshwhedon** [comment]
Pas le seul a vrai dire. Frostbolt aussi semble affecte. Probablement parce que tous les deux ont a la fois l'effet de ralentissement et les degats.

**Comment by Justforsoloq** [comment]
En effet Frostbolt aussi est affecté, par contre il faut différencier les deux qui ne semblent pas marcher de la même façon
FFB trinket : le slow de la ffb reste et continue d'être appliqué
FB : le slow de la fb disparaît lors du trinket, et après un court instant est appliqué de nouveau. 
(FB semble avoir de nombreux soucis)

**Comment by joshwhedon** [comment]
Meme probleme que https://github.com/way-of-elendil/3.3.5/issues/317
