### ISSUE TITLE
Piège de givre du hunt garde le hunt et sa cible en combat pendant toute sa durée

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#302]
**Description**
Piège de givre du hunt tant qu'il est actif au sol garde le hunt et la cible dans la zone d'effet en combat.

**Étapes de reproduction**
Prenez un hunt et faites un duel posez un piège de givre et regardez le temps de sortie de combat (il n'arrivera qu'après la fin du piège de givre)

**Comportement attendu**
Le piège de givre passe en combat à la pose, mais la zone d'effet ne garde pas en combat, et il devrait suivre la règles des 5s de sortie de combat.

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Frost_Trap

**Comment by Justforsoloq** [comment]
Le même soucis existe sur le lien terrestre du chaman elem. Le slow du lien garde en combat durant toute sa durée alors que seulement le talent https://wowwiki.fandom.com/wiki/Storm,_Earth_and_Fire doit faire passer en combat.

**Comment by Justforsoloq** [comment]
https://wowwiki.fandom.com/wiki/Combat

**Comment by joshwhedon** [comment]
Desole, ou tu vois que c'est pas supposer garder en combat pour sa duree ?

**Comment by Justforsoloq** [comment]
C'est le même principe que que le totem de lien terrestre, les snare de zone gardent pas en combat, c'est comme la violation du dk. Être dedans n'est pas une raison d'être en combat.

**Comment by Justforsoloq** [comment]
J'essaye de trouver une vidéo retail montrant la chose, ceci dit c'est excessivement dur sachant que il faut donc des joueurs posant leur slow de zone et ne tapant pas/n'étant pas tapé pendant +de 5s
