### ISSUE TITLE
Le pet voleur 

### ISSUE THREAD

**Issue by Shavokx** [way-of-elendil/3.3.5#305]
**Description**
Pk le pet voleur ?
Tout les pets des classes ce met automatiquement au dos de la personne ce qui est pas normal , même si la personne bouge le pet la suit et ce met dans sont dos 
(J'espère que c'est bien expliquer)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe toute classe avec pet 
- Race toute race
- Spécialisation toute spés
- Sort / Talent / Etc
- Circonstances PvP (Pve pas encore test)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Que le pet à un déplacement normal et suit pas la personne automatiquement , Voir un comportement normal

**Captures d’écran / Vidéos**
Vous pouvez test juste en duel avec un dk où un chasseur.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Justforsoloq** [comment]
https://www.youtube.com/watch?v=umetTVtTb2A
1m17-1m21 (côté gauche de l'écran)

**Comment by Killyana** [comment]
C'était corrigé parce que les pets se plaçaient avant toujours face au boss et se font os.

**Comment by Shavokx** [comment]
Oui mais pour le PvP c'est pas normal ^^ pour ça j'ai signalé.

**Comment by joshwhedon** [comment]
Corrige pour le pvp prochaine mise a jour.
