### ISSUE TITLE
[ICC] Limon orange sur Putricide

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#306]
**Description**
Le limon orange change plusieurs fois de cible avant de poursuivre une personne correctement.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- ICC 10H
- Boss : Putricide
- Expérience instable -> Nuage de gaz
- Composition du groupe : 
Zelaya (Hunt), Apéral (Féral), Toxxo (Mage), Daeri (DK), Némée (Palret), Belikaot (SP), Argaiv (HolyPriest), Respect (War), Chyky (Démo), Phazz (Cham)

**Comportement attendu**
Le limon poursuit la première personne ciblée.

**Captures d’écran / Vidéos**

Extraits tirés d'un ICC 10h le mardi 07/04/2020

https://www.youtube.com/watch?v=0AXY9S_4xQc&feature=youtu.be (1:10 à 1:40)

**Comment by joshwhedon** [comment]
Un correctif a deja ete prepare pour ca normalement. Ca devrait etre passer dans la nuit.

**Comment by Ischjgt** [comment]
Le limon rouge dès sa sortie et de façon assez aléatoire recast souvent son sort, ça peut arriver plusieurs fois à la suite
https://woehead.way-of-elendil.fr/?search=ballonnement+gazeux
Je sais pas lequel est cast mais en 25HM j'ai ça sur moi https://woehead.way-of-elendil.fr/?spell=72833

Eridium
> si je me trompe pas le limon rouge quand il fait ca il n'arrive jamais à la fin du cast
il l'interrompe avant la fin, je ne sais pas s'il recible ou pas
s'il recible c'est qu'il check la validité de la cible durant le cast se qui ne oit pas se produire

**Comment by joshwhedon** [comment]
Impossible de reproduire le probleme. Je mets un truc mais aucune idee si ca changera quoi que ce soit.
