### ISSUE TITLE
[ICC] Orbe inciblable sur les trashs des Princes

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#307]
**Description**
Sur le premier pack de trashs, l'orbe n'a pas été utilisée par les mobs (aucun enrage visible) mais l'orbe reste inutilisable pour les joueurs, même après un wype et la mort de l'intégralité des trashs.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- ICC 10H
- Boss : trashs pré-Princes
- Composition du groupe : 
Zelaya (Hunt), Apéral (Féral), Toxxo (Mage), Daeri (DK), Némée (Palret), Belikaot (SP), Argaiv (HolyPriest), Respect (War), Chyky (Démo), Phazz (Cham)

**Comportement attendu**
L'orbe est utilisable si les trashs la canalisant sont tués à temps.

**Captures d’écran / Vidéos**

Extraits tirés d'un ICC 10h le mardi 07/04/2020

https://www.youtube.com/watch?v=0AXY9S_4xQc&feature=youtu.be (2:00 à 6:00)

**Comment by Killyana** [comment]
Vous avez interrompu l'archi-mage durant la canalisation il a probablement une immunité manquante.

**Comment by Killyana** [comment]
Si vous trouvez comment interrompre le mob qui canalise merci d'ouvrir un ticket.

**Comment by joshwhedon** [comment]
Death Grip DK ou bump ? Ils sont probablement pas immunises.

**Comment by Killyana** [comment]
Ils le sont, je viens de tester, se qui est bien c'est qu'en cas d'interruption l'orbe ne devient pas cliquable.
