### ISSUE TITLE
Vali ICC 25nm pop d'adds trop fréquent

### ISSUE THREAD

**Issue by Crotodur** [way-of-elendil/3.3.5#310]
Lors du combat contre valitria sur icc 25nm, au bout de deux ou trois minutes de combat à peine, le pop d'add devient bien supérieur à la normal comme si le boss avait enrage dès le début du combat. Nous avons wipe au bout de trois quatre minutes avec une vingtaines de suppresseurs sur le dos, 4 abominations, 4 mages etc. Les heals qui montaient dans les portails ne semblaient pas avoir de soucis de leur côté.

**Comment by Endalaust** [comment]
Je ferme pour faire un seul ticket sur le sujet :
https://github.com/way-of-elendil/3.3.5/issues/297
