### ISSUE TITLE
[Quête] Des montures fraîches

### ISSUE THREAD

**Issue by AngelMasterBE** [way-of-elendil/3.3.5#311]
Bonjour
La quête "Des montures fraîches" disponible dans la désolation des dragons ne fonctionne pas comme elle devrait

Le principe de la quête est de tuer un pnj sur le dos d'un cheval de guerre de l'assaut pour récupérer l'item "Cravache de l'assaut" sur le pnj qui tombe au sol une fois mort, mais actuellement sur le serveur, le PNJ meurt sur le dos du cheval et il n'est pas possible de loot son cadavre, Le cheval de guerre de l'assaut continue sont paterne de déplacement et le PNJ disparait

je me demande aussi si le cheval de guerre de l'assaut doit pas disparait au bout de un moment si le cheval n'est pas utiliser pour la quête, car il reste amical et on a pas la possibilité de le tuer afin de faire respawn le cheval avec le pnj

Actuellement sur le personnage ou je fait la quête, j'ai réussi a faire tomber une seul fois le pnj au sol afin de ramener le cheval

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Quête désolation des dragons
- Faction / Race / Classe du personnage utilise : Horde, Elfe de sang, Mage
- Nom de la quête : Des montures fraîches
- Nom du donneur de quête : Hansel Bauer

**Comportement attendu**
Lors de la mort du PNJ, le cadavre tombe de la monture et est lootable afin de récupérer l'item pour finir la quête (Voir vidéo dans ressouce additionnelles)

**Ressources additionnelles**
- > https://woehead.way-of-elendil.fr/?quest=12214 (Woehead -> DB Erreur)
- > https://fr.wowhead.com/quest=12214/des-montures-fra%C3%AEches (Liens Wowhead)
-> https://www.youtube.com/watch?v=Ry6p5JZl-XM&feature=youtu.be (Video disponible sur wowhead, Avec une music dégeulasse :D )
-> https://nsa40.casimages.com/img/2020/04/08/200408110947558934.png (image du pnj ou on voit les petites lueurs du cadavre de pnj à looté, Et qui nous reste plus que la possibilité de mettre le cheval de guerre de l'assaut en focus )

**Comment by Killyana** [comment]
Il faut corriger le bug qui fait que les accessoire ne sont pas éjectées une fois morts.
Restaure le script de despawn existant sur TC:
-- A passer une fois sans le conservé
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid` = 27213 AND `source_type` = 0 AND `id` = 3 AND `link` = 0; 
INSERT INTO `smart_scripts` (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, COMMENT) VALUES
(27213, 0, 3, 0, 1, 0, 100, 512, 30000, 30000, 30000, 30000, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Onslaught Warhorse - ooc - Despawn");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (22) AND `SourceEntry` IN (27213);
INSERT INTO `conditions`  (SourceTypeOrReferenceId, SourceGroup, SourceEntry, SourceId, ElseGroup, ConditionTypeOrReference, ConditionTarget, ConditionValue1, ConditionValue2, ConditionValue3, NegativeCondition, ErrorType, ErrorTextId, ScriptName, COMMENT) VALUES
(22, 4, 27213, 0, 0, 1, 1, 43671, 1, 0, 1, 0, 0, , "event will not trigger if the aura 43671 is missing"),
(22, 4, 27213, 0, 0, 1, 1, 48290, 0, 0, 1, 0, 0, , "event will not trigger if the aura 48290 is missing");
