### ISSUE TITLE
Boss : Léviathan 25 nm

### ISSUE THREAD

**Issue by Limoustique** [way-of-elendil/3.3.5#312]
**Description**
Il y a de la pyrite qui pop de partout, c'est le festival du baril !

**Comment by joshwhedon** [comment]
Pyrite partout = trop de spawn des mobs volants ?

**Comment by Limoustique** [comment]
Oui c'est ça.

**Comment by joshwhedon** [comment]
J'augmente un peu le temps d'interval entre les spawn mais a premiere vue, y'a jamais plus de 8 mechanolifts de spawn.
En attendant ca fera, de toute il faudrait que je passe un moment sur ce boss pour ameliorer certains events.
