### ISSUE TITLE
Boss : Mimiron 25 nm

### ISSUE THREAD

**Issue by Limoustique** [way-of-elendil/3.3.5#313]
Assez bizarrement aucun bug sur le boss en lui-même (j'étais un peu déçue), par contre le coffre a depop avant qu'on le loot.

**Comment by joshwhedon** [comment]
Avant que vous le lootiez, possible qu'il ait depop avec le boss lui meme ?

**Comment by Limoustique** [comment]
C'est possible mais honnêtement je n'en suis pas sure.

**Comment by Tontonsid** [comment]
c'est Arkannor qui l'a désosser en ingé x)

**Comment by joshwhedon** [comment]
Serieux ?  :D .
