### ISSUE TITLE
Mort des PETS quand on va dans la deuillgivre en P3 LK - Sévérité HAUTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#315]
**Description**
 En ICC 25 Normal Mode j'ai été grab dans la deuillgivre ou il y a 2 ad dont un qu'il faut décast quand j'ai été tp dans la deuillgivre je n'avais pas de pet et quand j'en suis ressorti non plus ! je ne connais pas le comportement en NM mais en Hard Mode les pets sont supposé rester sur la plateforme et quand on redescend on est supposé les avoirs encore on n'a pas à les réinvoquer; le problème c'est en tant que démono ce soir ça rekt le dps de tout les caster / heal qui reste en bas (vu que je perds le temps pour le réinvoquer; je sais pas si c'est la même en 25HM je n'ai pas encore fais de p3 en 25HM depuis la merge.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Normal Mode
- Boss: Linch King (LK)
- Sort en question / Phase du boss en question / Emplacement: invocation des pets (phase 3 du Boss après la 2 ème transition sur le grab en deuillgivre)
- Composition du groupe: je n'ai plus le nom des personnages en tête

**Comportement attendu**

En 25 Hard Mode les pets restent en bas quand le groupe monte dans la deuillgivre; je ne connais pas le comportement normal en 25 Normal Mode; mais je doute que les pets soit ''tué'' à la montée/redescente.

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Je regarderai pour reinvoquer les pets a la sortie.

**Comment by joshwhedon** [comment]
Le soucis devrait etre regle prochaine mise a jour.
