### ISSUE TITLE
Horreur enrage 25 Normal Mode - fight LK - interrogation - Sévérité (potentiellement) HAUTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#316]
**Description**

P1 du LK l'horreur qui a pop et enrage a mis - 70K à un tank 38k armure et capé deff (drood tank) qui était sous CD; est-ce un comportement normal sur une P1 d'un LK 25 Normal Mode

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC 
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Normal Mode
- Boss: Linch King (LK)
- Sort en question / Phase du boss en question / Emplacement: P1 - emplacement MT2
- Composition du groupe: 25 joueurs aléatoire (j'ai pas noté les noms)

**Comportement attendu**

----: aucune idée; c'est une question, car les dégâts me semble très très élevé pour avoir CD et 25 Normal Mode, même si enrage.

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
L'enrage augmente ses degats de 200%. Donc la seule possibilite c'est que les degats de base de l'horreur soit trop hauts. Si vous avez des sources indiquant ses degats fournissez.

**Comment by Killyana** [comment]
J'ai nerf un peut le 25 et 25h, par contre un coup sous l'enrage 200% = OS  à part si le tank et sous full CD
https://www.wowhead.com/npc=37698/shambling-horror#comments:id=1054827
