### ISSUE TITLE
Sindragossa 25 Normal Mode - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#317]
**Description**

Lorsque le tank demande une main de liberté d'un paladin pour annulé le débuff qu'il a après avoir été victime d'un souffle sindra (jusqu'à là rien d'anormal) la main de liberté fonctionne; mais ensuite un hit de sindra annule l'effet de la main de liberté et il subit encore une fois le ralentissement.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Normal Mode
- Boss: Sindragossa
- Sort en question / Phase du boss en question / Emplacement: P1/P2
- Composition du groupe: 25 joueurs aléatoire

**Comportement attendu**

La main de liberté annule chaque effet de ralentissement et à la fin de la main de liberté si nouveau souffle un nouveau ralentissement apparaît sur le tank.

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Un hit = souffle ou bien n'importe quelle attaque ?

**Comment by joshwhedon** [comment]
Implemente comme explique ici : https://www.wowhead.com/forums&topic=173868
