### ISSUE TITLE
tp démo marche pas - Sévérité HAUTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#318]
**Description**

tout est dans le titre

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: démo
- Race: all race de démo
- Spécialisation: all
- Sort / Talent / Etc: invocation
- Circonstances (Donjon, Raid, PvP, autre): raid
- Equipement: /
- Buffs / Debuffs / Enchaînement de sort / Etc: /

**Comportement attendu**

Le TP doit marcher

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
C'est connu, il faut crash il a ete desactive pour l'instant, on testera dans le week end pour voir si c'est corriger.
