### ISSUE TITLE
Bug combat après le kill des valkyr (après saurcroc) + event de putricide - Sévérité HAUTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#319]
**Description**

On est en permanence dans les 2 raid 25 que j'ai fais à ICC en Normal et Hard mode en combat à la fin de l'event ou à la mort des valkyr + leurs ads. et je tiens à préciser aucun bump n'a été fait qui aurait pu envoyer un ad dans le décor

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 Normal et Hard Mode
- Boss: après saurcroc et avant putricide
- Sort en question / Phase du boss en question / Emplacement: mid salle après tp supérieur + dans l'aile de peste.
- Composition du groupe: 25 players aléatoires

**Comportement attendu**

le bug combat doit s'estomper dans les 2 cas car cela empêche la regen des joueurs

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Apres le kill des valkyr ou avant ?

**Comment by Killyana** [comment]
Il faut demander un MJ pour qu'il check via une commande se qui vous maintient en combat.
commande: .deb combat

**Comment by gtschanz** [comment]
après le kill des valkyrs on est en combat (je vais check ça vendredi à nouveau en 25h) si c'est le cas je screen

**Comment by joshwhedon** [comment]
Nah c'est pas un screen qu'il faut, il faut qu'un mj vienne pour voir ce qui vous garde en combat.

**Comment by Killyana** [comment]
Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Putricide's Trap (SpawnID 201361)
[PvE] Putricide's Trap (SpawnID 201423)
[PvE] Puddle Stalker (SpawnID 201231)

**Comment by joshwhedon** [comment]
Merci

**Comment by joshwhedon** [comment]
J'arrive pas a reproduire ... J'ai fait les changement cote core qui empeche ces npcs de mettre en combat :( .

**Comment by joshwhedon** [comment]
Question bete, quand ca arrive, tout le monde est en mode combat ? Ou que certains joueurs ? C'est des classes specifiques ?

**Comment by Killyana** [comment]
Quand j'ai check c'était tous via la propagation par heal probablement
Mais je pense que sa commence par un seule qui est hit par un spell

**Comment by Killyana** [comment]
Puddle Stalker (GUID 1293) does not threaten any units.
Puddle Stalker (GUID 1293) is not currently engaged. (This unit cannot have a threat list.)

Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Baboüche (SpawnID 0)
[PvE] ?ßlast (SpawnID 0)
[PvE] Cella (SpawnID 0)
[PvE] Mamix (SpawnID 0)
[PvE] Devastore (SpawnID 0)
[PvE] Fülcrum (SpawnID 0)
[PvE] Gersiflexe (SpawnID 0)

**Comment by Ischjgt** [comment]
Name: Frost Freeze Trap
SpawnID: 137733, current GUID low: 986.
Entry: 37744.

avec ce flag 
* UNIT_FLAG_IN_COMBAT (0x80000)

C'est la même chose que https://github.com/way-of-elendil/3.3.5/issues/460
Tu as l'air d'avoir corrigé ça il y a 3 jours mais c'est toujours présent

**Comment by joshwhedon** [comment]
Non j'ai juste mis que c'etait le meme bug, pour le fermer vu que c'est une duplication.

**Comment by joshwhedon** [comment]
Je mets un autre correctif. A voir.

**Comment by Killyana** [comment]
Ce fix va casser toutes les rencontres ou un npc trigger doit géré l'entré/sortie du combat.

**Comment by Endalaust** [comment]
Euh pas cool, parce qu'il est passé dans la release de ce matin

**Comment by Endalaust** [comment]
Euh pas cool, parce qu'il est passé dans la release de ce matin
Possible de vérifier ou de me dire comment tester?

**Comment by Ischjgt** [comment]
Même comportement que mon commentaire précédent

**Comment by Ischjgt** [comment]
**Étapes pour reproduire**
- Classe avec familier controlable
- défensif/agressif
- Marcher dans les flammes lancées par Frost Freeze Trap 37744 (il faut avoir tuer Saurcroc pour qu'ils s'activent)
- Le pet va taper dessus
- mode combat activé

**Comment by Endalaust** [comment]
<img width="576" alt="screenshot_825" src="https://user-images.githubusercontent.com/1420867/80416339-42009480-88d4-11ea-9b97-f660ecbc887a.png">
Je réouvre pour les 2 dernières lignes

**Comment by joshwhedon** [comment]
Bon bah du coup il y a d'autres moyens que les pets pour rester bloque en combat.
