### ISSUE TITLE
Sartha 3D : bug arrivé des drake

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#320]
**Description**
Les drakes ne viennent pas tout seul lorsque l'on fait sartharion sans les tuer avant. La on est obligé de pull les drakes a la main pour qu'ils viennent.

**Étapes de reproduction**
- Sanctum obsidien
- 10N
- sartharion
- arrivé des drake 

**Comportement attendu**
les drake sont sensé arriver les uns a la suite des autres suivant un timer prédéfini.

**Ressources additionnelles**
https://www.youtube.com/watch?v=k6ZAuJIgHJc on voit que le 2em drake arrive tout seul vers 0:37

**Comment by Killyana** [comment]
J'ai pas compris le bug, quand vous engagez Sartharion les 3 drakes ne commencent à voler en dessous de vous puis venir un à un?
Ils restent à leur place?

**Comment by Fairivier** [comment]
en fait hier soir on a engagé le boss et les 3 drake volaient au dessus du boss sans descendre sur nous. Un mage a été obligé de les pull en leur lancant un sort.

**Comment by rommni** [comment]
Juste au cas où je ne sais pas si vous avez attendu pour voir ou pas, mais sur offi le fonctionnement normal du boss c'est que les 3 drakes volent au dessus (et ne sont pas pullable) en mettant une aura qui rend le combat plus difficile puis descendent à certains intervalles se joindre au combat.

J'ai pas trouvé bien mieux comme vidéo mais en cherchant plus on peut peut-être avoir mieux: https://www.youtube.com/watch?v=iJJ4hhL9DU0

**Comment by Fairivier** [comment]
on a attendu un pti moment, quand on a fait descendre le 1er drake notre DBM nous indiquait que les 3 aurait du descendre depuis un moment
