### ISSUE TITLE
[anti-venin] ne fonctionne pas

### ISSUE THREAD

**Issue by zanzlibar** [way-of-elendil/3.3.5#321]
**Description**
anti-venin itemID=6452 ne fonctionne pas

**Étapes de reproduction**
.additem 6452
Se laisser empoisonner par un mob de niveau inférieurà 25.
constater que l'anti-venin ne fonctionne pas.

**Comportement attendu**
L'élément devrait guérir des poisons bas niveaux. ( poison des mobs de niveau inférieur à 25)

**Captures d’écran / Vidéos**

**Ressources additionnelles**
https://wotlkdb.com/?item=6452
https://wotlkdb.com/?npc=4007 <== un mob qui utilise un poison de bas niveau

**Comment by joshwhedon** [comment]
Hum, vous etes sur qu'il s'agissait de ce mob ? Parce que ce mob ne semble pas avoir d'effet de poison sur woe. Son attaque ne fait que des degats direct et n'applique pas de poison.

**Comment by zanzlibar** [comment]
j'ai testé cet anti venin sur plusieurs mobs qui me lançaient du poison.  les crashes venins en faisaient partie, si elles ne sont pas supposées emoisonnées leur cible, alors c'est un autre bug...

**Comment by zanzlibar** [comment]
ALors il se peut que dans la bataille j'ai confondu les cache venin avec leurs voisines ^^ il y a plusieurs arraignées avec grosso modo le même skin. je viens de retester pour les dos-hirsute. là c'est 100% un ID de mob valide :)

**Comment by joshwhedon** [comment]
Merci :)
