### ISSUE TITLE
Quest: Au secours d'Evanor

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#322]
**Description**
Quest 11681
1. Après avoir libéré Dame Evanor, on est TP dans la tour d'Escarpement d'Ambre, mais personne à qui rendre la quête

La quête se rend à Dame Evanor 25785, elle a toujours id: 46076 [Archimage Evanor (Invis Quête)] quand on est TP sur elle

2. la quête est rewarded mais le point d'interrogation reste gris et on ne peut pas rendre la quête

**Comment by Killyana** [comment]
``` sql
-- A passer une seule fois sans le conservé (mauvais changement dans nos sql)
UPDATE `quest_template_addon` SET `SpecialFlags` =0 WHERE `id` = 11681;

**Comment by joshwhedon** [comment]
Corrige prochain reboot.
