### ISSUE TITLE
Instance: Ahn'kahet NM

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#323]
**Description**
31104 - [Guetteur ahn'kahar] à l'entrée de l'instance  niveau 79 dans l'instance NM

**Comportement attendu**
L'instance a des mobs du lvl 72-75, donc ils doivent etre 72 ou 73 je suppose, j'ai rien trouvé :(

**Comment by Killyana** [comment]
Fixé par: https://github.com/TrinityCore/TrinityCore/commit/2d72439b068093e6226ce74ca83747d85ab0327b

**Comment by Endalaust** [comment]
SQL appliqué à la demande de @Killyana
