### ISSUE TITLE
Quest: La bataille pour la cime des Croisés

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#326]
**Description**
Quest: 74388

1. Les mobs ne remontent pas vers la bannière, ils spawn et restent à leur place
2. Le buff 58026 n'augmente pas les dégats contre les morts vivants (quête pas faisable tout seul pour l'instant)

**Comportement attendu**

https://youtu.be/MjJ8sNPXdKk
80 Héritage il os tout le monde

**Comment by Killyana** [comment]
Les mobs invoqué attaque la bannière via: tempsum->AI()->AttackStart(GetClosestCreatureWithEntry(me, NPC_BLESSED_BANNER, 100));

Mais sa ne fonctionne plus apparent

**Comment by Ischjgt** [comment]
Les NPCs hostiles foncent maintenant vers la bannière sans s’arrêter, si un la touche, la quête est perdue

**Comment by Killyana** [comment]
Ils doivent foncer sur la bannière, elle a une aura d'aggro periodique

**Comment by rommni** [comment]
Je pense qu'il y a tout de même encore 1 ou 2 petits soucis sur cette quête même si elle est désormais réalisable.

Pour comparaison une vidéo de la quête: https://www.youtube.com/watch?v=MjJ8sNPXdKk
Et voici une vidéo sur le serveur: https://www.youtube.com/watch?v=DiazBKbKtQk

Peut-etre qu'une impression mais je crois qu'on a plus de porte peste hideux qui pop que sur officiel ou il y a l'air d'y avoir plus de "petits" mobs.
Surtout je pense que l'aura (58026)  n'est peut-être pas assez efficace, je ne sais pas le stuff de la première vidéo et je n'ai pas un stuff énorme sur mon personnage, mais il me semble que sur la première vidéo presque tous les mobs se font one-shot les dégâts semblent très fortement augmentés par l'aura, j'ai l'impression que c'est moins le cas sur le serveur, si possible de jeter un petit coup d'oeil.

Lien wowhead de l'aura en question : https://fr.wowhead.com/spell=58026/b%C3%A9n%C3%A9diction-de-la-croisade#used-by-npc

**Comment by Ischjgt** [comment]
Voir commentaire précédent

**Comment by Ischjgt** [comment]
Tout pareil

**Comment by Ischjgt** [comment]
Oups
