### ISSUE TITLE
Toujours pas de bonus pour les donjons aléa

### ISSUE THREAD

**Issue by Phaaj** [way-of-elendil/3.3.5#327]
**Description**
Cela fait plusieurs jours que je n'obtiens pas le bonus de donjon aléatoire.
Il n'est pas écrit, et je ne le reçoit pas quand je finis le donjon (5 ou 6 jours d'affilés).

**Étapes de reproduction**

- Druide / Feral
- Nexus, Azjol Nerub (bugé à Hadronox à chaque try), Ahn'Kahet, Donjon d'Utgarde / mode normal

**Comportement attendu**
Réception d'un bonus d'xp, de PO et d'emblèmes de Triomphe

**Comment by Ischjgt** [comment]
Désolé, mais je vais avoir du mal à te croire tant que j'aurais pas un screen ou que tu m'appelleras pas AVANT ton premier donjon. Pour moi, même si c'est pas affiché tu reçois bien et la monnaie est bien ajoutée.

**Comment by Phaaj** [comment]
Merci d'enfin proposer une solution au problème.
Comment je fais pour te contacter avant le donjon ?
Si tu constates le problème aurais-je une compensation pour les donjons précédent ?
Apparemment je ne suis pas le seul dans cette situation, il faudrait voir avec les autres joueurs aussi.

**Comment by Ischjgt** [comment]
Ticket In Game ou Discord.
Pas de compensation.

**Comment by Phaaj** [comment]
Je suis désolé d'apprendre cela ...
Je ne comprends pas vraiment ce choix, cela fait 4 ou 5 fois que je remonte cette info (afin que vous puissiez résoudre votre problème), on me dit qu'il n'y a pas de problème mais s'il n'y en avait pas je ne perdrai pas mon temps à faire toutes ces requêtes et à vous prendre la tête pour ça.
J'ai l'impression d'être traité de menteur pour 8 emblèmes et quelques PO  ... 
Si ma requête concernait du loot de raid j'aurai pu comprendre tant de méfiance et de réticence.

![WoWScrnShot_040920_123225](https://user-images.githubusercontent.com/63394389/78886289-3866d800-7a5e-11ea-8ac6-12da294aa3fb.jpg)

Voici un screenshot de mes emblèmes à 12h31 le 09/04/2020.

![WoWScrnShot_040920_132039](https://user-images.githubusercontent.com/63394389/78889932-f5f4c980-7a64-11ea-8f5b-d6872d244548.jpg)

Voici un screenshot réalisé à 13h20 de mes emblèmes suite à mon premier donjon du 09/04/2020.

J'espère que cela sera suffisant.
Merci de votre compréhension.

**Comment by Ischjgt** [comment]
Tu te méprends totalement sur l’interprétation de mon commentaire.
Tu remontes l'info, je test, j'arrive pas à reproduire. 
Si je te demande de m'appeler avant, c'est pour que je constate le soucis par moi-même sur ton perso, avec l'utilisation de mes commandes. Bien sur que je te crois, sinon j'aurais déjà fermé le ticket.
Du coup, non, c'est pas suffisant, parce que tes screens ne me donnent aucune info de comment reproduire le soucis.

**Comment by joshwhedon** [comment]
Le probleme a ete trouve. Il ne concerne que les joueursen dessous du niveau 78, des restrictions ont ete mises en place pour limiter ces recompenses. Apres plusieurs recherches, cette limite a ete baissee a 69. Desole pour le derangement.

**Comment by Phaaj** [comment]
Oui je viens de voir ça.
J'ai eu accès aux premiers emblèmes au lvl 68.
En fait le plus dommageable est de ne pas avoir de compensation dans toute cette affaire ...

**Comment by Endalaust** [comment]
On va dire que le dédommagement c'est le fait de ne pas vous faire payer l'accès au serveur privé contre les dizaines d'heure que nous y investissons chaque jour au détriment de nos vies personnelles et de notre temps sur nos jobs respectifs :)
Et vu qu'on vous octroie cette gratuité gratuitement, ne prenez pas la peine de nous remercier! De notre côté on va se contenter de la satisfaction procurée par le fait de fermer un bug 
De mon côté je remercie ce rapport qui nous a permis de voir le soucis qui était visible côté client 👍
