### ISSUE TITLE
Prb avec Mystère de l'infini après la mort de l'élite

### ISSUE THREAD

**Issue by Phaaj** [way-of-elendil/3.3.5#328]
**Description**
La quête ne se valide pas après la mort de l'élite (le dragon). Le sablier étant toujours en vie à la fin de la quête. Élite très puissant, peut être bug au niveau des dégâts ? 

**Étapes de reproduction**
- Désolation des Dragons / sanctuaire draconique Bronze
- Horde / Tauren / Druide, forme de félin au début puis forme d'ours après le pop du dragon

**Comportement attendu**
Validation de la quête après avoir protégé le sablier et tué l'élite.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/3621b1fd34f86ec06088f06fe38a7b1207b14e9a
