### ISSUE TITLE
Spell: Explosion morbide à Scholomance

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#329]
**Description**
Corpse Explosion 17616 est cast par Scholomance Necromancer 10477 et applique Corpse Explosion  61614

Le sort est incanté sans conditions et a pour cible n'importe quelle personne alliée/hostile avec le Nécromancien

**Comportement attendu**
Le nécromancien ne doit cibler que les cadavres quand il cast le sort

**Ressources additionnelles**
C'est apparu sur le serv il y a longtemps, corrigé puis c'est réapparu encore récemment, j'avais eu quelques tickets comme ça.
https://github.com/dalaranwow/dalaran-wow/issues/1971

**Comment by joshwhedon** [comment]
61614 est definitivement pas le bon sort c'est un sort wotlk. Il faut revoir le script un peu aussi

**Comment by Killyana** [comment]
61614  est trigger par 17616, c'est bien le  bon spell.
Corrigé prochaine maj
