### ISSUE TITLE
NPC: Traquépine

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#330]
**Description**

Les auto attaques de Traquépine stoppent la canalisation du Rugissement puissant  
NPC: 37534
36922 - [Rugissement puissant, rank 1 frFR] à toutes les difficultés

**Comment by joshwhedon** [comment]
C'est pas un sort canalise. T'es sur que c'est les auto attaques ? Parce que de ce que je vois il est pas suppose auto attaquer pendant les casts.
