### ISSUE TITLE
[Quête] Au secours d'Evanor - PNJ manquant

### ISSUE THREAD

**Issue by Baguetteftw** [way-of-elendil/3.3.5#331]
**Description**
Après avoir libéré dame Evanor de sa prison à la Halte de Béryl, celle-ci est censé se trouver dans la tour des mages de l'Escarpement d'Ambre (Toundra Boréenne), or après avoir effectué la quête pour la libérer la fameuse Evanor n'est pas dans la tour comme c'est stipulé dans la quête :

"Anzim, de l'Escarpement d'Ambre, vous demande de vous envoler avec ses mages de guerre pour libérer dame Evanor à la Halte de Béryl. Vous devrez ensuite lui faire votre rapport dans la tour des mages de l'Escarpement d'Ambre".

Quête nécessaire pour obtenir une transition en fly vers Frimarra !!

**Étapes de reproduction**

**Comportement attendu**

**Captures d’écran / Vidéos**

**Ressources additionnelles**

https://wotlk.evowow.com/?npc=25785

**Comment by joshwhedon** [comment]
Merci du signalement, ce bug a deja ete signale ici : https://github.com/way-of-elendil/3.3.5/issues/322
