### ISSUE TITLE
Quête "L'éradication des déviants" bug affichage sur carte

### ISSUE THREAD

**Issue by Drenaas** [way-of-elendil/3.3.5#332]
**Description**
Problème d'affichage de la quête "L’éradication des déviants" (donjon des Cavernes des Lamentations) sur la carte. Les mobs à éliminer sont dans le donjon mais l'affichage sur carte donne des zones à l'entrée des Serres Rocheuses (voir captures).

**Étapes de reproduction**
- Prendre la quête devant les cavernes des lamentations (pnj dans "l'oeil gauche" du rocher d'entrée)
- Horde / Ally ?
- Quête : L’éradication des déviants (donjon)
- Donneur : Ebru

**Comportement attendu**
Affichage d'un point de quête unique sur la carte au niveau des cavernes des lamentations.

**Captures d’écran / Vidéos**
![L'éradication des déviants](https://user-images.githubusercontent.com/63403129/78892352-846b4a00-7a69-11ea-82de-c9560cba3d37.png)
![L'éradication des déviants 2](https://user-images.githubusercontent.com/63403129/78892358-86350d80-7a69-11ea-81b9-1c1bd8ab1b40.png)

**Comment by Killyana** [comment]
Fixé prochaine maj
