### ISSUE TITLE
NPC: Apprentie Mirveda

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#333]
**Description**
Entry: 15402
Cas où le NPC ne reset pas correctement et où l'ont ne peut plus interagir avec elle.

C'est arrivée à l'instant sur un joueur tout de suite après un crash :
L'event se déroule bien, le joueur et le NPC tuent la vague de mobs qui spawn, puis quand les ennemis meurent, la quête n'est pas validée pour le joueur et l'Apprentie se bloque (dans cet ordre je pense)

La quête marche bien en temps normal, j'arrive pas à reproduire

Quest: 8488 - [Des résultats inattendus] 

EDIT 17h: ça arrive pas qu'après un crash, n'importe quand en fait

**Comment by Killyana** [comment]
Le SAI counter reset on evade...

**Comment by Killyana** [comment]
Sera corrigé avec https://github.com/TrinityCore/TrinityCore/issues/24436
