### ISSUE TITLE
Donjon d'Utgarde - Prince Keleseth

### ISSUE THREAD

**Issue by Margueriteuh** [way-of-elendil/3.3.5#334]
Bonjour

En recherche de donjon héroique donc niveau 80.

Normalement en entrant dans la salle de Keleseth, il y a un pack de mobs juste avant lui, ils sont relativement proche mais l'aggro est dissocié exprès pour ne pas avoir le pack à faire en même temps.

Sauf qu'ajourd'hui, en voulant faire le pack avant le début du fight keleseth a été pull juste en attaquant le pack de mobs juste avant lui, ce qui rend le combat très compliqué, déjà que le pack d'add juste avant fait déjà tres mal en soi.

Phase du boss en question / Emplacement
-1 war tank
-2 dk dps givre/impie
-1 mage dps
-1 heal pretre

**Comment by joshwhedon** [comment]
Ils ne sont pas lie, par contre, il faut les agro avec un certains timing, sinon oui Keleseth le voit et les aide. En gros il faut agro un cote au moment ou Keleseth se tourne pour marcher vers l'autre cote :) . Merci de l'avoir signale cela dit.
