### ISSUE TITLE
Démoniste/Impossible d'invoquer via Rituel d'invocation

### ISSUE THREAD

**Issue by Celdelbore** [way-of-elendil/3.3.5#336]
**Description**
La création de la porte d'invocation fonctionne sans problème. On peut cliquer sur la porte pour créer le portail d'invocation sans problème. Pour autant, lorsque les autres membres du groupe cliquent sur le portail crée par le démoniste (ou tout autre personnage du groupe) pour invoquer le dernier membre du groupe, le personnage cast dans le vide. Le portail disparait bien, mais les personnages continuent de caster. Le personnage invoqué ne reçoit jamais l'invocation. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe : Démoniste
- Race : Gnome
- Spécialisation : Destruction
- Sort : Rituel d'invocation
- Circonstances : Essai à la combe de Nigel, Désolace

**Comportement attendu**
Après le clique droit sur le portail, le cast devrait s'interrompre et le personnage invoqué devrait recevoir la demande d'invocation.

**Comment by Ischjgt** [comment]
Déjà notifié
