### ISSUE TITLE
Boss: Empereurs jumeaux AQ40

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#337]
**Description**
Name: Emperor Vek'nilash
Entry: 15275.
Name: Emperor Vek'lor
Entry: 15276.

Il n'y a que Ve'klor celui qui cast qui est TP sur vek'nilash, je crois que ça n'arrive que quand Ve'klor est à portée pour cast son Trait de l'ombre.

(J'ai pas le spell qui TP les boss)

**Comportement attendu**
Les 2 boss doivent switch de positions

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/29
Vieux bug, pas reussi a le corriger la derniere fois que j'ai regarde.
