### ISSUE TITLE
Récompenses de quète au level 80

### ISSUE THREAD

**Issue by Yunayu7** [way-of-elendil/3.3.5#338]
**Description**
Avant la màj lundi, les quètes donnaient au niveau 80 l'xp transformée en PO (ex une quète qui donnait 4po de base en donnait 15). Aujourd'hui j'ai rendu des quètes avec ma hunt 80 qui affichaient en récompense 4po70. J'ai rendu ces mêmes quètes avec ma drood 70 et elles donnaient 4po70 + 20100 xp. 

Blizzlike l'xp était-elle transformée en PO, était-ce un bug sur WOE avant la màj ou bien est-ce un bug actuel ?

**Comment by joshwhedon** [comment]
C'etait pas une quete journaliere par hasard ?

**Comment by Killyana** [comment]
Oui se sont des quête jouna: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=daily#quests

**Comment by Yunayu7** [comment]
Bonjour, non ce n'était pas des quètes journalières. Ce sont les quètes dans le bouclier jsaisplusquoi à Frimarra, à la Toundra Boréenne.

**Comment by joshwhedon** [comment]
J'ai verifie et ca fonctionne correctement 👍 
![image](https://user-images.githubusercontent.com/543699/79194311-b0bf0600-7e6f-11ea-9897-47a434897513.png)
