### ISSUE TITLE
Impossible de capturer les vers dans la quête Worm Wrangle

### ISSUE THREAD

**Issue by Phaaj** [way-of-elendil/3.3.5#339]
**Description**
Quand je place la boîte pour capturer les vers rien ne se passe.

**Étapes de reproduction**

- Ice Heart Cavern / Dragonblight
- Horde / Druide / Félin
- Worm Wrangle
- Zort

**Comportement attendu**
Capture des vers lors du déploiement de la boîte

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
https://www.youtube.com/watch?v=_is1bsp83o4&feature=youtu.be

**Comment by Killyana** [comment]
Nom de la quête: Ver querelleur

**Comment by Killyana** [comment]
Dup https://github.com/way-of-elendil/3.3.5/issues/395
Je garde la nouveau ticket qui contient plus d'info
