### ISSUE TITLE
Les fils de Hodir

### ISSUE THREAD

**Issue by Artael17** [way-of-elendil/3.3.5#340]
J'ai pris les quêtes chez les fils de Hodir (journa et quête normal) et en voulant les rendre, je ne pouvais plus parler aux pnj. J'ai déco / reco du jeu et toujours pareil je n'arrive pas a leurs parlés.  
Personnage qui a le beug => Artaël humain prêtre

**Comment by rommni** [comment]
Si jamais au lieu de leur parler tu les attaques verifient que tu as decoche l'option "en guerre" dans la réputation je me suis fait avoir une fois :)

**Comment by Artael17** [comment]
Merci l'ami !!! C'était tout à fait ça. Je n'avais pourtant rien touché dans ces options. Problème résolu, encore un grand merci.

**Comment by rommni** [comment]
Super je ne sais pas si en tant qu'auteur tu as les droits mais si c'est le cas tu peux fermer le ticket je pense :)

**Comment by Artael17** [comment]
Résolu
