### ISSUE TITLE
[Quête] Tombé en disgrâce

### ISSUE THREAD

**Issue by AngelMasterBE** [way-of-elendil/3.3.5#341]
Bonjour la quête tombé en disgrâce à un bug sur le costume

Sur le serveur actuel le costume de la prête du corbeau saute lors que on invoque une monture ou que on cast un spell

Lors que on parle au pnj "le Grand abbé", fait disparaite le costume aussi

Ajout : 09-04-2020 à 19:27
Le costume nous rend pas amical avec les pnjs de la croisade ecarlate, ont agro tous les mobs qui fait sauté le costume
Edit 19:30 : Après la reprise du costume (4eme fois), j'ai 2pnj qui sont resté inamical et le reste est devenu amical

Ajout : 19:44
Après la disparition du costome lors que ont parle au grand abbé langrain, j'ai été reprendre encore une fois le costome, le pnj est apparrue devant la porte (suite logique de la quête) et a continuer sont chemin vers sa zone ou le pnj saut pour ce suicidé (Quête accomplie)

Lien vidéo : https://www.youtube.com/watch?v=lq47dJK42Sc&feature=youtu.be

**Étapes de reproduction**
- Emplacement : Désolation des dragons
- Faction / Race / Classe du personnage utilise : Horde, elfe de sang, Mage
- Nom de la quête : Tombé en disgrâce
- Nom du donneur de quête : Agent skoulis

**Comportement attendu**
Le déguisement doit rester même lors que on invoque notre monture, ainsi que lors que ont parle au pnj "le Grand abbé"

**Ressources additionnelles**
https://fr.wowhead.com/quest=12274/tomb%C3%A9-en-disgr%C3%A2ce (Lien Wowhead)
https://www.youtube.com/watch?v=iCAnVB33RqU&feature=emb_title ( Video ) 

Scréen PNJ Amical
https://nsa40.casimages.com/img/2020/04/09/200409074200401757.jpg
Scréen PNJ non amical
https://nsa40.casimages.com/img/2020/04/09/200409074200808416.jpg

**Comment by Killyana** [comment]
@Josh les auras (48763,48761) sont dispell du joueur dés qu'il cast un spell, n'importe lequel, alors qu'il devrait pouvoir utiliser une monture, changer de posture de combat cast un spell de heal ect.. ou 48756 qui cast par le joueur sur lui même quand il parle au pnj.

Interrupt Flags: 0x00000000, AuraIF 0x0058B000, ChannelIF 0x00000000

Proc flag 0x00004400, chance = 100, charges - 1
=================================================
  1024 (0x400) - Successful positive spell hit
  16384 (0x4000) - Successful cast positive magic spell
