### ISSUE TITLE
Gain d'emblème de triomphe sur premier donjon NM du jour

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#343]
**Description**
Première fois que je reviens sur ce perso depuis la merge, je n'ai pas fait de donjon depuis dimanche.
Le personnage est niveau 76, donc accès aux donjons WotLK, et le premier de la journée doit donner des emblèmes de triomphes.
J'ouvre l'outil donjon et constate ceci : 

![WoWScrnShot_040920_192645](https://user-images.githubusercontent.com/63348105/78923416-797bde00-7a98-11ea-8191-1714058f6109.jpg)

**Comment by joshwhedon** [comment]
Les joueurs en dessous de 80 peuvent pas recevoir d'emblemes, si ?

**Comment by Killyana** [comment]
C'est géré via des quêtes:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=daily+random

**Comment by joshwhedon** [comment]
Apres plusieurs recherches, le niveau normal est suppose etre 69, pas 78. Le probleme a ete corrige.
