### ISSUE TITLE
Pnj ne lançant pas la quête "patrouille anti-troll"

### ISSUE THREAD

**Issue by Nynette** [way-of-elendil/3.3.5#344]
J'ai lancé la quête la première fois en lui parlant, tout semble normal, malheureusement pas assez rapide, ça me dit que c’est trop tard. Je relance en lui parlant je suis assez rapide pour trouver l'ingrédient mais rien ne se passe près du chaudron. J'abandonne et relance, impossibilité de relancer au pnj.

**Comment by Killyana** [comment]
la quête fonctionne correctement, j'ai pas ressui à reproduire, aussi il faut indiquer qu'elle quête, la journa https://woehead.way-of-elendil.fr/?quest=12541  ou https://woehead.way-of-elendil.fr/?quest=12557

**Comment by Killyana** [comment]
J
