### ISSUE TITLE
NPC: Serfex le Saccageur

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#345]
**Description**

Entry: 28083
Je ne le trouve pas, il a plusieurs points de spawn, peut-être un soucis là dessus ?

**Comment by Killyana** [comment]
Lié au pooling

**Comment by joshwhedon** [comment]
Donc il est bug ou il est juste pas pop ?

**Comment by Killyana** [comment]
Bug de pool, probablement.

**Comment by joshwhedon** [comment]
De bonnes chances que les modifs d'aujourd'hui reglent le probleme. Si non,... tan pis

**Comment by Killyana** [comment]
Oui c'est  fixé

**Comment by Ischjgt** [comment]
Toujours pas. (Il me semble qu'il y avait eu le même problème il y a quelques temps sur l'ancienne version)

**Comment by joshwhedon** [comment]
Un correctif sera applique, aucune idee si il marchera moi sur 30 kills il a repop a chaque fois avec mon fix.

**Comment by Ischjgt** [comment]
Hello,
Tu le sais le bug est toujours là,

J'apporte peut-etre un nouvel élément : j'ai fait réapparaitre Serfex avec npc add temp sur un des point de spawn, il a été tué et maintenant il respawn normalement de nouveau
