### ISSUE TITLE
Proc ANORMAL des poisons sur l'aoe fufu (éventail de couteaux) - Sévérité IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#346]
**Description**

En fufu faire des éventail de couteaux en aoe sans mettre 1 SEUL auto hit sur la / les targets autours met les poisons sur les target alors que ça devrait pas (même à ceux dans notre dos); imaginer vous en pvp 1 fufu fais 1 éventail de couteaux dans 1 pack de 10 players il leur met direct le poison slow + l'anti heal sans avoir mis 1 auto.... et en pve c'est pire car ça permet sur un fight lk de mettre les poisons sur lk + toute les goules en p1 et de faire des p1 à + de 35/40K tout le long de la p1 sans redescendre; voir tout les moment ou y'a du cleave... tout les poisons sont concernées // et si vous me dites que c'est un comportement normal je me demande alors pourquoi en pvp les fufu sur offi d'époque ne mettez jamais d'éventail pour mettre les débuff de poisons sur multicibles en 3v3 ou 5v5 vu que ça permettrait en théorie de mettre l'antiheal + le slow sur 5 personne avec 1 technique...; il ne le faisait que pour trac quelqu'un de vanish car ça le despot s'il prend des dégâts. De plus ça met même le débuff au target derrière nous..

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: voleur
- Race: all class de voleur
- Spécialisation: all spé
- Sort / Talent / Etc: éventail de couteaux
- Circonstances (Donjon, Raid, PvP, autre): testé sur poteau à orgrimmar et vu sur certains voleur en raid...
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc: l'éventail des couteaux met le débuff des poisons.

**Comportement attendu**

l'éventail des couteaux ne met pas les poisons (genre AUCUN) seul les auto hit et les technique qui requière qu'on soit face à la cible et qu'on la tappe effectivement 

**Captures d’écran / Vidéos**

----: prenez un fufu et testé le sur les poteaux à orgrimmar (je viens de faire ça; facile à reproduire)

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
T'es sur de toi sur ce coup la ? Sur les versions plus recentes ils ont mis a jour les descriptions pour indique que les poisons sont appliques.
https://www.wowhead.com/spell=51723/fan-of-knives
https://www.wowhead.com/forums&topic=77026
A premiere vue je dirai que c'est normal. Par contre le taux doit etre le meme que sur les auto attaques.
Si vous avez des sources contradictoires merci de les fournir je reouvrirai.
