### ISSUE TITLE
Sethekk HM : Anzu

### ISSUE THREAD

**Issue by Schreid** [way-of-elendil/3.3.5#347]
**Description**
Anzu continue de lancer son spell "Hurlement paralysant" lorsqu'il est en "Auto-bannissement".

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Salles de Sethekk
- Héroïque
- Anzu
- Hurlement paralysant // Auto-bannissement

**Comportement attendu**
Lorsque le boss est sous Auto-bannissement, il ne peut lancer aucun sort.

**Comment by gtschanz** [comment]
je l'ai déjà bt dans un autre ticket josh (avec en prime les ads ou y'a pas de dégressif sur les control)

**Comment by Killyana** [comment]
Dup https://github.com/way-of-elendil/3.3.5/issues/290

**Comment by joshwhedon** [comment]
Je vais reouvrir celui la pour le corriger a part. C'est deux bugs differents dont un qui n'est pas forcement un bug.
