### ISSUE TITLE
ralentissement sur main de liberté - Sévérité (potentiellement) IMPORTANTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#348]
**Description**
Ce bug est peut être lié à celle de la main de liberté qu'il existe aussi sur sindra et qui annule l'effet supprimant le ralentissement.

Pour produire ce bug; faites un duel mage vs paladin -> lancer un éclair de givre sur le paladin et utiliser la main de liberté en paladin on constate qu'il apparait un ''buff'' éclair de givre en haut à droite qui ralentis le paladin de 40% si on cancel la main de liberté est-ce un comportement normalement attendu; le débuff de vitesse est-il censé être gardé dans le cas ou le mage ''vol'' la main de liberté ou si le paladin se l'enlève ou si on lui dispell et si oui; pourquoi alors le débuff de vitesse apparait dans la catégorie des buff et non plus des débuff ?

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe / Spécialisation: paladin
- Donjon / Mode de difficulté: /
- Champ de bataille / Arène: toute situation
- Sort / Objet / Quête: main de liberté + ralentissement
- Boss / PNJ / Monstre: /

**Comportement attendu**

La main de liberté annule le ralentissement = ok; mais le débuff de vitesse passe t il en buff à ce moment ??? - voir les captures écran

**Captures d’écran / Vidéos**

![Capture d'écran 2020-04-09 22 24 49](https://user-images.githubusercontent.com/63243193/78937530-fadf6a80-7ab0-11ea-8521-36c9ce2f48c5.png)
![Capture d'écran 2020-04-09 22 24 57](https://user-images.githubusercontent.com/63243193/78937560-029f0f00-7ab1-11ea-8c38-6dbcee120637.png)

**Ressources additionnelles**

----

**Comment by gtschanz** [comment]
ça repasse en débuff si la main de libre venait à être annulé mais dans le cas d'un mage qui le duel // si c'est normal que le ralentissement reste sur le pala en switch buff puis debuff; est-ce normal que le mage veut volsteal le ''buff'' de l'éclair de givre qui pour le coup ralentis ensuite le mage; alors que ce n'est pas un buff à proprement parler

**Comment by Endalaust** [comment]
Juste pour info sans aucun rapport avec l'issue, plutôt que de définir la sévérité dans le titre, il y a les labels dans la colonne de droite pour ça ;) Là où on peut sélectionner le label "bug"

**Comment by joshwhedon** [comment]
C'est le meme bug qu'ici: https://github.com/way-of-elendil/3.3.5/issues/300
