### ISSUE TITLE
bug petite abomination - Sévérité HAUTE

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#349]
**Description**

Le bijou petite abomination (nm comme hm) bug; exemple si en pala on duel quelqu'un et on envoie 1 seul jugement en ayant son adversaire de dos on peut avoir 3 proc de granules de colère avec 1 seul jugement... ce qui donne à ce bijou un up grade dps qui n'a pas foi d'être; (c'est très aléatoires (faudra essayer plusieurs fois; parfois le bijou proc 1 x; parfois 2x; parfois 3x d'un coup) et à 7 stack pour la version hm et 8 pour la version nm cela libère 1x les dégâts de l'arme; le fait que ce bijou peut stack plus vite n'est pas normal

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe / Spécialisation: tout les classe qui porte le bijou petite abomination hm (se foot sur putride NM / HM) - bijou très répandu sur les paladins
- Donjon / Mode de difficulté: /
- Champ de bataille / Arène: /
- Sort / Objet / Quête: petite abomination (bijou putricide version nm comme hm)
- Boss / PNJ / Monstre: /

**Comportement attendu**

1 coup = 1 proc

**Captures d’écran / Vidéos**

bug facilement reproductible prenez un paladin + une autre classe; faites un duel avec cette dernière classe et mettez l'adversaire dans votre dos et envoyé uniquement 1 jugement (si ça marche pas au première essaie; faites quelques essaie

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Par chance tu sais si la petite abomination est suppose avoir un cooldown interne ?

**Comment by AngelMasterBE** [comment]
Bonsoir, Je vais ajouter un éclaircissement sur le proc du bijou TAIJ (petit abomination)
En paladin retribution il est possible de faire proc de 1 à 3 Granule de colère, Un jugement peut donc crée 3 granule a condition que le Jugement soit un critique, débuff du jugement ainsi que le proc vengeance vertueuse

-> Information EJ palaret (Archive)
Testing of arcane mechanics is always welcome, but the mechanics of TAJ are fairly well established as of 3.3.2. This is retreading on old ground.

The reason you're seeing more procs on SoV is that each SoV melee attack provides three proc chances (seal + melee attack + sov stack refresh) and each SoR melee attack provides two proc chances (seal + melee attack). Mitigating factors in SoR's favor that make this a bit more complicated is that JoR provides three proc chances on hit and four proc chances on crit (judge damage, judge debuff, righteous vengeance, seal) and JoV provides two proc chances on hit and three proc chances on crit (judge damage, judge debuff, righteous vengeance). The two seals have identical behavior when it comes to CS and DS with two proc chances on hit and three proc chances on crit (cs/ds damage + seal + righteous vengeance.)

http://web.archive.org/web/20100808150558/http://elitistjerks.com/f76/t84213-retribution_bis_lists_3_3_a/p14/

**Comment by joshwhedon** [comment]
Merci pour la source @AngelMasterBE , il semble a premiere vue que c'est le comportement attendu :) . Tellement de bugs depuis la merge que c'est difficile de savoir ce qui est un bug ou pas :D .
