### ISSUE TITLE
Halion 25H braises hors combat - HAUTE sévérité

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#350]
Sur halion 25h les braises ont un comportement étrange au niveau de l'aggro (hors combat, multiples aller-retours, pertes d'aggro inattendues  ect).
Elles restent hors combat tant qu'elles ne prennent pas de dégats ou que l'on s'approche trop.
Testé lors d'un passage p2 : le boss n'est plus là et une météore venait de tomber. Un druide équi était présent seul dans la salle en lumière, mais éloigné des braises (environ 20-30m). Celles-ci l'ont totalement ignoré jusqu'à ce qu'il s'approche.
Comportement attendu : les braises target et se déplacent vers la cible la plus proche, où qu'elle soit.

**Comment by joshwhedon** [comment]
On parle bien des flammes du meteor ?

**Comment by toitit** [comment]
Oui les braises vivantes qui pop en même temps que l'inferno vivant après une météore (je crois que l'inferno vivant à le même problème au fait)

**Comment by joshwhedon** [comment]
Et l'inferno ? Il a fait quoi ? Il a attaque ?

**Comment by toitit** [comment]
il apparaît moins loin du coup il attaque. Mais quand y'avait qu'un joueur il bougeait pas non plus, donc même comportement sûrement.

**Comment by joshwhedon** [comment]
Hum, c'est chelou, moi ils attaquent tous apres quelques secondes (les quelques secondes c'est normal).

**Comment by toitit** [comment]
C'est arrivé que des braises (3 ou 4) restent hors combat de l'autre côté du boss, et n'attaquent que lorsqu'on a traversé à la météore suivante :/

**Comment by joshwhedon** [comment]
Je mets une modification prochaine mise a jour, mais ne pouvant pas reproduire le probleme il faudra me dire si ca se reproduit.
