### ISSUE TITLE
Halion 25hm

### ISSUE THREAD

**Issue by Tautaaaaaaaaa** [way-of-elendil/3.3.5#351]
Beaucoup de bug sont présents sur le boss : 
- Dégats de braises trop grand : druide tank full stuff toi utiliser tout ses CD def pour pouvoir survivre aux braises
- Les braises reset ou reste hors de combats et reste à leur spawn.
- Halion peux double souffle : non tankable 
- Halion fait son combo auto attack et souffle = 60k dégats sur un war tank full stuff sous cd : non tankable

**Comment by joshwhedon** [comment]
Qu'est-ce que tu appelle double souffle ?

**Comment by Tautaaaaaaaaa** [comment]
Il arrive que Halion cast deux souffle à 2/3 secondes d'intervalle

**Comment by toitit** [comment]
J'ai check les recounts, c'est pas un combo mêlée + souffle d'halion, c'est l'inferno vivant qui pose des mêlées à 30k sur le tank sous cd (parfois en même temps que le souffle)

**Comment by joshwhedon** [comment]
OK merci.

**Comment by joshwhedon** [comment]
Niveau degats des braises, il faut les reduire de combien d'aprez vous ? Vous avez des sources sur leurs degats ?
