### ISSUE TITLE
BG: Récompenses Joug d'hiver

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#352]
**Description**
Qu'importe son rang, le joueur gagne 43589 - [Marque d'honneur de Joug-d'hiver] x3 s'il gagne, 

**Comportement attendu**
c'est censé être x1 recrue spell, x2 Caporal, x3 Lieutenant

recrue spellID 37795 
Caporal 33280
Lieutenant 55629

Pas testé si le joueur perd, mais c'est x1 à tous les rangs normalement

Bonus : Aussi, je suis pas sur que ceci soit bien respecté, j'ai pas vu combien d'honneur j'avais reçu mais j'ai bien moins de 3k sur le perso avec lequel j'ai fait le Joug

    Patch 3.1.2 (2009-05-19): Honor gains in Wintergrasp has been slightly nerfed: 

        Wintergrasp Victory now rewards 3000 Honor. (Down from 5000 Honor)
        Wintergrasp Defeat now rewards 1250 Honor. (Down from 3000 Honor)
        Tower Damaged now grants up to 750 Honor. (Down from 1250 Honor)
        Tower Destroyed now grants up to 750 Honor. (Down from 1250 Honor)
        Damaged Building Reward now grants up to 750 Honor. (Down from 1250 Honor)
        Intact Building Defender now grants up to 1500 Honor. (Down from 2500 Honor) (Note: Currently shown as 150 Honor but most likely a typo)

https://wowwiki.fandom.com/wiki/Wintergrasp

**Comment by joshwhedon** [comment]
Je vais jeter un oeil aux recompenses
