### ISSUE TITLE
Quest: Enquêter dans le magasin de l'alchimiste

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#353]
**Description**
1960 - [Enquêter dans le magasin de l'Alchimiste] 
Une fois à 1PV, les 6492 - [Rejeton de la faille] passent amicaux mais reset et rechangent de phase, les rappeler avec chants de manifestation les re-fait revenir mais amicaux cette fois ci, et il est impossible d'utiliser 7247 - [Caisse de coffres de stockage]  sur eux

**Comment by joshwhedon** [comment]
Duplication de https://github.com/way-of-elendil/3.3.5/issues/273 (desole je l'avais pas nommee correctement)
