### ISSUE TITLE
Quest: Du rififi au Valhalas : le retour de Sigrid Née-de-glace

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#354]
**Description**
13216 - [Du rififi au Valhalas : le retour de Sigrid Née-de-glace] 
Le NPC arrive depuis une monture, une fois descendue, elle fonce sur nous mais n'attaque pas et n'est pas attaquable

Entry: 31242.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/83c222826bdc214e211f1a1572bc91396f9c5426
