### ISSUE TITLE
Quest: Du rififi au Valhalas : héros défunts

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#356]
**Description** 
Quest: 13214

Les NPCs n'ont pas une aggro liée
31195 - [Eldreth] 
31193 - [Geness Demi-Âme] 
31191 - [Père Jhadras] 
31192 - [Masud] 
31196 - [Rith] 
31194 - [Talla]

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/608d23fb1e2f2eaa1c3b155f8da4aa7fd02dbe8b
