### ISSUE TITLE
Véhicules: Passagers et changement de map

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#357]
**Description**
"J'ai constaté avec un ami que lorsqu'il descend du mammouth sur le bateau qui fait theramore - paluns, il passe sous la carte ... 
et s'il reste sur le mammouth lors du changement de continent, le passager du mammouth ne passe pas le chargement, et reste dans l'eau !"

**Ressources additionnelles**
C'était déjà là avant

**Comment by joshwhedon** [comment]
Deja signale ici https://github.com/way-of-elendil/3.3.5/issues/204
et tres probablement blizzlike.
