### ISSUE TITLE
Instance: Fort pourpre

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#358]
**Description**
Testé en héroïque
Mourir fait systématiquement recommencer l'instance à la première vague

**Comportement attendu**
normalement il y a des checkpoints après chaque boss

**Comment by Ischjgt** [comment]
Bonus: Les gardes ne sont pas là après un wipe, les mobs apparaissent à l'infini

**Comment by Ischjgt** [comment]
Je réouvre et change le titre
Exactement le même soucis sur ces Instances: GT2 et SDR
J'ai pas test Hyjal :o)

**Comment by joshwhedon** [comment]
Non mais ... faut pas reouvrir les bugs comme ca. C'est pas la meme instance et c'est pas le meme probleme.

**Comment by joshwhedon** [comment]
https://wow.gamepedia.com/Opening_the_Dark_Portal
If Medivh dies, the encounter will reset itself in 5 minutes and players will be able to pick up a new Chrono-beacon from Sa'at.
Donc a premiere vue, et de facon assez attendue, les instances BC pardonnent beaucoup moins, et un wipe signifie recommencer a 0.

**Comment by Ischjgt** [comment]
Toutes mes excuses, il semblerait qu'en fait ce comportement soit normal.

_Upon Death, one must fight through all waves, including the bosses, again. However, in Heroic mode, bosses that have already been defeated are replaced by mobs that are the same but differently named, and provide only 250 Reputation and no loot. In Regular, bosses which have to be fought again will drop loot normally._
https://wowwiki-archive.fandom.com/wiki/Violet_Hold_(original)

_And a side note; avoid wipes like the plague. This aint fun when you're wiping and get to redo everything, plus bosses for no additional loot._ 
https://fr.wowhead.com/the-violet-hold#english-comments
