### ISSUE TITLE
BG: Rivage des anciens

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#359]
**Description**
"de temps en temps les véhicules ne peuvent plus attaquer le mur et briser les mur, de plus certains [joueurs] étaient capable de marcher à travers le mur quand il était encore debout"

le même soucis que https://github.com/way-of-elendil/3.3.5/issues/222  avec les murs ?

Pas testé, je remonte juste le soucis

**Comment by joshwhedon** [comment]
Faudrait trouver dans quelles circonstances ca arrive ... Est-ce que le mur est detruit mais le joueur en a pas vu la destruction parce qu'il etait trop loin ? Etc.

**Comment by Ischjgt** [comment]
> Faudrait trouver dans quelles circonstances ca arrive ... Est-ce que le mur est detruit mais le joueur en a pas vu la destruction parce qu'il etait trop loin ? Etc.

Je pense que c'est ça, il y avait un soucis comme ça il y a quelques années également, je te tiens au courant

**Comment by Ischjgt** [comment]
> . Est-ce que le mur est detruit mais le joueur en a pas vu la destruction parce qu'il etait trop loin ? Etc.

Confirmed

**Comment by Ischjgt** [comment]
(Et le problème est le même avec les bateaux, pour moi c'est pas un soucis de chargement de gob)

**Comment by joshwhedon** [comment]
Un correctif sera mis en place, on espere qu'il marchera.
