### ISSUE TITLE
Spell: Image miroir

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#361]
**Description**
NPC Entry: 31216.

Les images miroirs n'ont quasiment pas de vie et ne tapent pas assez fort

**Comportement attendu**
Désolé pour la vidéo
https://www.youtube.com/watch?v=fN_3MZ7G66c
Pour les dégats c'est au moins le double, pour la vie je crois qu'avant la merge c'était bien

**Comment by Ischjgt** [comment]
Tout pareil. Elles ont 2680 PV actuellement et ne bénéficie d'aucun bonus du joueur

**Comment by Justforsoloq** [comment]
J'avais filé la formule de l'elem d'eau et des images miroirs non ?

**Comment by joshwhedon** [comment]
Oui et les degats sont bons, 33% du spellpower du mage.

**Comment by joshwhedon** [comment]
Les pv tout ce que j'ai trouve c'est https://www.mmo-champion.com/threads/613742-Mirror-Image-Theories-and-Discussion donc ca fera.

**Comment by Ischjgt** [comment]
Answer: They have the same health the mage would have if the mage had all of his gear off and 0 talent points spent. This is just over 4k at 80, and they start at full health.


J'ai pas 2680 au level 80 hein

**Comment by joshwhedon** [comment]
Oui je mets un correctif deja a partir de cette info. LEs degats eux sont bons.
