### ISSUE TITLE
NPC: Élémentaire d'eau

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#362]
**Description**
Entry: 37994.

La vie du NPC est basse

**Comportement attendu**
https://www.youtube.com/watch?v=CGl8B4dMxso
11min 09 y'a le double de HP

(dégats corrects)

**Comment by joshwhedon** [comment]
Il va falloir plus d'info, est-ce que la vie du pet est base sur les stats du joueur ? Quel est le ratio ? Etc.

**Comment by joshwhedon** [comment]
Parce que la actuellement on a les stats qu'on avait avant. A moins de me fournir une formule, ca restera comme c'est.

**Comment by Justforsoloq** [comment]
https://wow.gamepedia.com/Summon_Water_Elemental
The Elemental receives a third of its master's spell power, 30% of its master's Stamina and Intellect, and 35% of its master's Armor.[1]
Trouvé ça je sais pas si ça peut aider

**Comment by Justforsoloq** [comment]
Après c'est wowpedia donc pas 100% fiable

**Comment by joshwhedon** [comment]
Ca aide merci. Pas 100% fiable mais mieux que rien.

**Comment by Justforsoloq** [comment]
Surtout que le petit [1] en fait est une source EJ
^ Roywyn. WotLK - Complete Mage Compendium (3.3 Live). Elitist Jerks. Retrieved on 2009-01-10.

**Comment by Justforsoloq** [comment]
J'ai utilisé la wayback machine
Water Elemental
The Water Elemental gains all raid buffs like auras, totems and procs.

It gains 1/3 (33.33%) of its master's spell power, and all their spell hit from gear.
That means double-dipping from the spell power buffs like Totem of Wrath for example.

Waterbolt then scales with 5/6 (83.33%) of the pet's spell power.
Waterbolt base damage is 256-328 + 11.5*(level-50).

Its Stamina is 118 + 30% master's stamina, Intellect is 369 + 30% master's intellect, Armour is 7822 + 35% master's armour.
Its Health then is 6676 + 7.5 * Stamina and Mana is 1082 + 4.95 * Intellect.

**Comment by joshwhedon** [comment]
Tu peux fournir le lien stp ?

**Comment by Justforsoloq** [comment]
https://web.archive.org/web/20100831131329/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_3_live/

**Comment by Justforsoloq** [comment]
T'as des changements comparé à la version 3.3.5 vu que c'est la 3.3 donc faut pas tout prendre dedans à face value.
Mais pour les stats de l'elem d'eau j'ai pas trouvé d'autres pistes.

**Comment by joshwhedon** [comment]
Oui oui c'est mieux que rien. Ce sera plus proche au moins. Enfin pour les niveau 80 du moins :D . Les niveau d'en dessous aucune idee :D .
