### ISSUE TITLE
Charge/Interception empêche d'être piège givrant/flèche givrante

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#364]
**Description*
La charge/interception du war empêche de se prendre le piège givrant/la flèche givrante du chasseur

**Étapes de reproduction**
Prenez un hunt faites un duel contre un war, posez votre piège givrant ou votre flèche givrante au cac. Le war vous charge/intercepte et ne se prend rien

**Comportement attendu**
Il doit être glaçon.

**Ressources additionnelles**
https://wotlk-twinhead.twinstar.cz/?spell=11578
https://wotlk-twinhead.twinstar.cz/?spell=20616
https://wotlk-twinhead.twinstar.cz/?spell=27753

**Comment by joshwhedon** [comment]
En fait c'est plus grave que ca :D . Rien a voir avec la charge, si le chasseur est controlle (stun, fear, etc), le piege se declenche pas parce que techniquement le chasseur est le lanceur de sort et le sort peut pas etre lance.
