### ISSUE TITLE
Joug d'hiver 2 :)

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#365]
**Description**
- La faction victorieuse ne reçoit que 372 points d'honneur au lieu de 3000 au joug d'hiver
- Les téléporteurs pour les engins situés dans la forteresse ( devant les garages ) ne fonctionnent pas( aucun effet quand on roule sur le téléporteur )  , les catapultes / démolisseurs et engins de siège restent bloqués à l'intérieur 

**Comportement attendu**
3000 ph en cas de victoire au joug d'hiver 
Wintergrasp Victory now rewards 3000 Honor. (Down from 5000 Honor) ( patch 3.1.2 : https://wow.gamepedia.com/Wintergrasp#Patches_and_hotfixes )

Les engins en défense sont censés être tp de l'autre coté du mur lorsqu'ils roulent sur le téléporteur 

**Captures d’écran / Vidéos**
https://ibb.co/4fcbvVC ( pour les points d'honneur )

**Comment by joshwhedon** [comment]
LE probleme d'honneur a deja ete corrige pour la prochaine mise a jour. Je regarderai pour les teleporters.
