### ISSUE TITLE
Cape d'ombre n'enlève pas le debuff "Piège" root des hunts

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#366]
**Description**
La cape d'ombre du rogue n'enlève pas le debuff "piège" (le root 2s) des hunts

**Étapes de reproduction**
Prenez un hunt, faites un duel contre un rogue, posez votre piège au sol, le rogue cape d'ombre et sera toujours root.

**Captures d’écran / Vidéos**
https://www.noelshack.com/2020-15-5-1586526075-wowscrnshot-041020-153804.jpg

**Ressources additionnelles**
https://wotlk-twinhead.twinstar.cz/?spell=19184
https://wotlk-twinhead.twinstar.cz/?spell=31224

**Comment by joshwhedon** [comment]
C'est nouveau ca ? Vu le code ca devrait deja bugger avant.

**Comment by Justforsoloq** [comment]
J'avais pas testé avant, donc je ne sais pas si c'est nouveau.

**Comment by Justforsoloq** [comment]
Up régression depuis le dernier patch.
