### ISSUE TITLE
System: Transmogrification

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#368]
**Description**
La transmogrification n'a plus l'air de marcher pour les boucliers, les items comme le fuseau à soie des ténèbres...
Fonctionne avec des armes à une main comme des masses etc

**Comment by joshwhedon** [comment]
Ne pas marcher = tu peux l'utiliser mais ca se voit pas, ou tu peux pas l'utiliser ?

**Comment by Ischjgt** [comment]
Les items que tu veux transformer ne se voient pas

**Comment by Ischjgt** [comment]
De même pour des items comme https://woehead.way-of-elendil.fr/?item=15070
Toute la gamme ne m'est pas proposé par le PNJ, et inversement quand je les équipe je ne peux pas les transmo

**Comment by joshwhedon** [comment]
J'ai verifie, ca fonctionne. Les objets qui n'ont aucune stats par contre ne peuvent etre  transmog (je mets un check supplementaire pour regarder les resistances aussi). Aussi, une des regles c'est cuir sur cuir, tissu sur tissu, etc.
