### ISSUE TITLE
Le point d'ébulition (toundra boréenne)

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#369]
**Description**
Les deux pnj à "soumettre" meurt avant de se soumettre.

**Étapes de reproduction**
donneur de quête : Impéréen

**Comportement attendu**
Soumission des pnj avant de mourrir

**Comment by Ischjgt** [comment]
La quête a marché chez moi, tu peux réessayer en y allant "doucement" ?

**Comment by Killyana** [comment]
Il est impossible que ces 2 mobs meurent, soit vous avez la quête et y'a un évent une fois leur vie est basse, soit ils despawn

**Comment by Killyana** [comment]
Si vous avez un pet il faut pas l'utiliser pour les évents qui sont déclenchés via les statuts des quêtes, si un pet déclenche l’évent on vérifie pas l'état de la quête de son maître, je ne sais pas si ça va être implémenter un jour
