### ISSUE TITLE
Démoniste : Diablotin

### ISSUE THREAD

**Issue by DrBloody21** [way-of-elendil/3.3.5#37]
Bonjour, sur la classe démoniste le diablotin se comporte de manière très aléatoire.
Celui ci peut arrêter de se battre d'un seul coup ou même ne pas éxécuter l'action sélectionné, courrir dans une direction aléatoire, se bloquer dans une texture (souvent des reliefs) et disparaître sans raison. 
Malheureusement je ne peux pas faire de capture vidéo du problème, mais je pense qu'il s'agit d'un problème dans le codage, et je pense qu'un patch d'une extension plus récente ciblant uniquement le diablotin pourrait régler ce problème.

**Comment by Killyana** [comment]
Le a déjà été corrigé sur TC.

**Comment by joshwhedon** [comment]
Sera corrige avec le merge sous peu (j'espere).
