### ISSUE TITLE
[Quête] Préparatifs de guerre - Le PNJ ne déclenche pas le fly vers la cannonière

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#370]
**Description**
Dans la quête "[Préparatifs de guerre](https://woehead.way-of-elendil.fr/?quest=13418)" , le PNJ "[Officier Van Rossem](https://woehead.way-of-elendil.fr/?npc=31081)" ne déclenche pas correctement le fly lorsqu'on lui parle et que l'on sélectionne "Envoyez-moi à bord" après avoir accepté la quête.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Dalaran (Aire de Krasus)
- Faction / Race / Classe du personnage utilise : Prêtre Draeneï
- Nom de la quête : [Préparatifs de guerre](https://woehead.way-of-elendil.fr/?quest=13418)
- Nom du donneur de quête : [Officier Van Rossem](https://woehead.way-of-elendil.fr/?npc=31081)

**Comportement attendu**
Un fly doit se déclencher lorsque l'on clique sur "envoyez-moi à bord" et nous amener sur la canonnière de notre faction.

**Comment by Killyana** [comment]
Fixé prochaine maj

**Comment by rommni** [comment]
@Killyana Il semble y avoir encore quelques soucis sur cette quete je ne sais pas si je la fait mal mais je viens d'essayer de la faire je parle au pnj sur l'aire de krassus il me fait monter sur une machine volante et vole jusqu'à la couronne de glace mais une fois à la couronne il reste planté en vol stationnaire et je ne peux rien faire (position 67/53) 

![Capture](https://user-images.githubusercontent.com/907396/79311797-3d180a00-7efe-11ea-80c1-d94d8eab8570.JPG)

**Comment by Killyana** [comment]
Non, la version horde n'a jamais fonctionné à cause de la désynchronisation de la position du bateau horde entre le client et le serveur.

**Comment by rommni** [comment]
ha ok dommage

**Comment by joshwhedon** [comment]
Question bete, on peut pas faire que le vehicle fasse le chemin contraire du bateau, et laisser le joueur sortir quand il veut pour atterrir sur le bateau ? Pas super blizzlike mais bon

**Comment by Killyana** [comment]
Sa prendra beaucoup de temps vue le chemin du bateau, en plus il faut ajuste la hauteur à chaque point...
