### ISSUE TITLE
[Quête/PNJ] Mener la charge / Kibli Killohertz / Karen No

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#371]
**Description**
Le PNJ [Kibli Killohertz](https://woehead.way-of-elendil.fr/?npc=32444) apparaît en double.
La quête [Mener la charge](https://woehead.way-of-elendil.fr/?quest=13380) qu'il nous donne ne peut pas être menée à bien. En effet le PNJ secondaire [Karen No](https://woehead.way-of-elendil.fr/?npc=31648) ne parvient pas à nous faire entrer dans le bombardier lorsqu'on lui parle. Le bombardier apparaît au dessus et disparaît aussitôt.

Il est probable que les quêtes suivantes ([Objectif Killo : la vallée de l'Espoir perdu](https://woehead.way-of-elendil.fr/?quest=13382) , [Troupe de choc statique : le Bombardement](https://woehead.way-of-elendil.fr/?quest=13404) et [Une nouvelle cible](https://woehead.way-of-elendil.fr/?quest=13381) ), ainsi que leurs équivalentes de la Horde, subissent le même problème.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Couronne de Glace (Aldur'thar : la Porte de la Désolation)
- Faction / Race / Classe du personnage utilise : Prêtre Draeneï
- Nom de la quête : [Mener la charge](https://woehead.way-of-elendil.fr/?quest=13380)
- Nom du donneur de quête : [Kibli Killohertz](https://woehead.way-of-elendil.fr/?npc=32444)

**Comportement attendu**
Être envoyé dans un bombardier pour accomplir la (les ?) quête(s) y étant liée(s).

**Comment by Killyana** [comment]
Double spawn supprimé
Pour le reste il y'a un ticket ouvert
