### ISSUE TITLE
Quest: Danger ! Explosifs !

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#373]
**Description**
11218 - [Danger ! Explosifs !] 

J'ai du louper un truc mais les gob sont pas visibles pour les joueurs, même phase pourtant

[Whisper Gulch Ore] ID: 186403

**Comportement attendu**
https://www.youtube.com/watch?v=6q3qTMkPtAs

**Comment by Killyana** [comment]
Fix prochaine maj
