### ISSUE TITLE
[Gnomeregan] Bugs dans la zone souterraine près de l'entrée du donjon

### ISSUE THREAD

**Issue by Freyahh** [way-of-elendil/3.3.5#374]
**- Description**
Au cours de mes aventures, j'ai repéré quelques bugs dans la zone de l'entrée du donjon nommé Gnomeregan, dans la région de Dun Morogh, aux Royaumes de l'Est.

À l'heure actuelle, les pillards des cavernes, les pilleurs des cavernes et les envahisseurs des cavernes qui meurent ne réapparaissent pas avant un très long lapse de temps (15/30 minutes environ), et Techbot ne réapparaît pas du tout après être tué, ou alors probablement après un très long lapse de temps (1h peut-être), ou probablement après un redémarrage du serveur.

**- Comportement attendu**
En temps normal, les pillards des Basses-Cavernes, les pilleurs des Basses-Cavernes et les envahisseurs des des Basses-Cavernes réapparaissent assez vite (5 minutes environ) et il en est de même pour le mob spécial de type machine nommé Techbot, présent dans une alcôve à l'Ouest de la zone.

**- Étapes de reproduction**
1) Se rendre dans la zone souterraine près de l'entrée de Gnomeregan ;
2) Tuer un ou plusieurs mobs dans la zone ;
3) Tuer également Techbot ;
4) Se rendre compte que les mobs réapparaissent trop lentement ;
5) S'apercevoir que Techbot ne réapparaît pas du tout après être tué (sauf probablement après un redémarrage du serveur).

**- Captures d’écran / Vidéos**
Pas de screen ou vidéo à la clé. On peut s'en rendre compte simplement en suivant les étapes.

**- Ressources additionnelles**

Envahisseur des Basses-Cavernes :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=6208
- WoW Head : https://fr.classic.wowhead.com/npc=6208

Pillard des Basses-Cavernes :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=6209
- WoW Head : https://fr.classic.wowhead.com/npc=6209

Pilleur des Basses-Cavernes :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=6210
- WoW Head : https://fr.classic.wowhead.com/npc=6210

Techbot :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=6231
- WoW Head : https://fr.classic.wowhead.com/npc=6231

**Comment by Killyana** [comment]
Techbot: https://github.com/TrinityCore/TrinityCore/commit/afe2e67849755f607c6ec13907bb0ed33100fcb3

**Comment by Killyana** [comment]
Pour les autres y'a des commentaires qui indiquent un temps de respawn plutôt long, c'est entre 27min et 28 min, mais je peux pas changer sans preuve

**Comment by Freyahh** [comment]
Fort bien ! :) J'aurais bien voulu être membre du staff du serveur Vanilla, où j'étais seulement en tant que joueur il y a quelques années, car les temps de respawn de ces mobs étaient dans ces eaux-là (5 à 10 minutes), mais je comprends que l'on ne puisse pas changer le temps de respawn sans preuve concrète. En tout cas, merci pour la prise en compte du bug pour Techbot, car lui ne réapparaît vraiment plus :-P
