### ISSUE TITLE
NPC: Drakkari Raptor Mount Drak'tharon

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#375]
**Description**
Name: Risen Drakkari Handler
Entry: 26637.
Name: Drakkari Raptor Mount
Entry: 26824.

"Les "Dresseur drakkari ressuscité" invoquent des raptors niveau 80 en normal à drak'tharon (instance niveau 74-76)"

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b26302cdd0c454f49786d16372767e92deae1396
