### ISSUE TITLE
[Bouclier de Terre] 

### ISSUE THREAD

**Issue by Lerian80** [way-of-elendil/3.3.5#376]
Le sort [Bouclier de Terre] du chaman ne restaure pas de vie au tank. Les stacks descendent bel et bien sur la cible mais via Skada il n'y a aucun heal de cette source.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Chaman
- Troll
- Restauration
- Bouclier de terre
- Halion 25H
- 
- 

**Comportement attendu**
Protège la cible avec un bouclier de terre, qui réduit de 30% le temps d'incantation ou de canalisation de sort perdu quand elle subit des dégâts. Les attaques rendent 337 points de vie à la cible protégée. Cet effet ne peut se produire qu’une fois toutes les quelques secondes. 6 charges. Dure 10 min. Bouclier de terre ne peut être placé que sur une cible à la fois et un seul Bouclier élémentaire peut être actif sur une cible à la fois.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/363
Deja signale, ce sera corrige aujourd'hui.
