### ISSUE TITLE
Spell: Judgement Coefs

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#377]
**Description**
Problèmes de dégats ?
On dirait bien que j'ai pas les mêmes coefs en données, j'ai :
SANS TALENTS LIÉS À CES SORTS :

- Les différents Jugements sous :
Sceau de corruption : 0,14 attack power / 0,22 spellpower => c'est surtout lui qui pose problème
Sceau de piété : 0,2 / 0,32 => OK
Sceau d'autorité : 0,287 / 0,13 => un poil trop de dégats sur le prod
Sceau de justice : 0,16/0,25 => un poil trop de dégats sur le prod
Sceau de lumière : 0,16/0,25 => un poil trop de dégats sur le prod
Sceau de sagesse : 0,16/0,25 => un poil trop de dégats sur le prod

20184 - [Jugement de justice, rank 1 frFR]
20185 - [Jugement de lumière, rank 1 frFR]
20186 - [Jugement de sagesse, rank 1 frFR]

**Comment by joshwhedon** [comment]
J'ai verifie, le jugement de corruption / vengeance a bien les coefficients qu'il faut.  Tu es sur que la cible avait pas corruption du sang sur elle ? Vu que ca augmente les degats.
Jugements de justice, lumiere et sagesse sont un chouilla trop haut, je les corrige. 
Le jugement d'autorite est gere un peu differemment des autres du fait de ses degats etant base sur l'arme aussi. Cela dit j'ai matte les coefficient (qui sont en fait 0.08 et 0.13) et ils sont bons.
https://wow.gamepedia.com/index.php?title=Attack_power_coefficient&oldid=2268555

**Comment by Ischjgt** [comment]
Je suis sur pour le jugement de corruption je calculais avec/sang et le soucis et là que ce soit à 0 ou 5 stacks, du coup si les coefficients sont bon je sais pas mais il y a un soucis avéré avec les dégats et dès le départ :D

**Comment by joshwhedon** [comment]
Les coefficients sont bons, les stack comptent bien pour 10% chaque stack. Il y a pas de soucis avec a premiere vue. Pas trop le temps de chercher plus profondement, tout a l'air bon.

**Comment by Ischjgt** [comment]
Il manque un multiplicateur inné de 10% sur le sceau de corruption
Il est présent sur tous les jugements avec les différents sceaux, je t'ai envoyé un screen sur Discord
