### ISSUE TITLE
[Quête] "Milly Osworth" : Bug avec les conditions d'accès

### ISSUE THREAD

**Issue by Freyahh** [way-of-elendil/3.3.5#379]
**- Description**
Au début la zone de départ des humains à Comté-du-Nord dans la Forêt d'Elwynn, aux Royaumes de l'Est, la quête intitulée "Milly Osworth" ne devient pas disponible au bon moment.

En effet, cette quête ne devient disponible qu'après avoir accompli la quête "La confrérie des voleurs", ce qui n'est pas du tout normal.

**- Comportement attendu**
La quête "Milly Osworth" est censée être disponible uniquement après avoir accompli la quête "Les loups derrière la frontière".

C'est logique étant donné que la quête suivante intitulée "Les vendanges de Milly", ainsi que la quête "Les loups derrière la frontière", doivent pouvoir être faites en même temps.

D'ailleurs, WoE Head précise bien les conditions d'accès de la quête que j'ai mentionné ci-dessus (voir la mention "Requiert").

**- Étapes de reproduction**
1) Se rendre à Comté-du-Nord dans la Forêt d'Elwynn, aux Royaumes de l'Est ;
2) Accomplir la quête "Les loups derrière la frontière" ;
3) Se rendre compte que la quête "Milly Osworth" n'est pas disponible après avoir accompli la quête "Les loups derrière la frontière", ce qui n'est pas normal ;
4) Accomplir la quête "La confrérie des voleurs" ;
5) Se rendre compte également que la quête "Milly Osworth" est disponible après avoir accompli la quête "La confrérie des voleurs", ce qui n'est pas normal non plus.

**- Captures d’écran / Vidéos**
Pas de screen ou vidéo à la clé. On peut s'en rendre compte simplement en suivant les étapes.

**- Ressources additionnelles**

Quête "Milly Osworth" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=3903
- WoW Head : https://fr.classic.wowhead.com/quest=3903

Quête "Les loups derrière la frontière" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=33
- WoW Head : https://fr.classic.wowhead.com/quest=33

Quête "La confrérie des voleurs" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=18
- WoW Head : https://fr.classic.wowhead.com/quest=18

Quête "Les vendanges de Milly" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=3904
- WoW Head : https://fr.classic.wowhead.com/quest=3904

**Comment by Killyana** [comment]
En faite sa nécessite les 2, ici y'a la chaîne: https://wow.gamepedia.com/Milly_Osworth_(quest)

**Comment by Freyahh** [comment]
Étrange, car sur tous serveurs privés que j'ai pu faire, même celui-ci il y a 1 an de cela lorsque j'ai refait un personnage, il n'y avait jamais besoin de faire la quête "La confrérie des voleurs".

D'ailleurs, WoE Head et les autres Database des serveurs privés où j'ai été mentionnent bien qu'il n'y a besoin d'accomplir QUE la quête "Les loups derrière la frontière".

De + , cela paraît logique vu que les quêtes "La confrérie des voleurs" et "La confrérie des voleurs" se font généralement ensembles, vu que ça se trouve exactement au même endroit qu'elles sont censés être faites.

Après, je peux me tromper, mais ça me paraît bizarre tout de même ^^

**Comment by Killyana** [comment]
Regardes à la fin des vidéos https://fr.classic.wowhead.com/quest=18/la-confr%C3%A9rie-des-voleurs#videos:id=166760 à la fin, la quête Milly Osworth devient dispo avec "Bounty on Garrick Padfoot"

**Comment by Freyahh** [comment]
Ah oui, en effet, sur un serveur WoW Classic, la quête devient disponible après avoir accompli la quête "La confrérie des voleurs".

Toutefois, je vais être un peu chatouilleux là-dessus, mais était-ce également le cas sous WOTLK en version 3.3.5 ? Étant donné que tous les serveurs privés sont dans ce cas précis, ça pose question ^^

Après, je n'ai pas d'autres sources que la vôtre, hormis les ressources que j'ai partagé dans le ticket. Je peux également vous partager les liens des quêtes sur les databases des autres serveurs privés, si vous le souhaitez.

**Comment by joshwhedon** [comment]
Il est tres rare pour blizzard de changer les prerequis de quetes des extensions precedentes.
Et desole mais les autres serveurs prives ne sont generalement pas des references valides :) .

**Comment by Freyahh** [comment]
Et bien soit ^^ En ce cas, vous pouvez classer ce report bug en 'Classé' ;-)

**Comment by Killyana** [comment]
Les serveurs privées utilises wowhead qui n'est pas lié à blizzard et contient beaucoup d'erreurs, je vais pas ajouter  "Les loups derrière la frontière" comme prérequis sinon sa va entrer en conflit avec la quête "La prime pour Garrick Ladétrousse" et de toute façon il y'a le prérequis par niveau

**Comment by Freyahh** [comment]
À noter que le pré-requis par niveau a souvent changé suivant les patchs, notamment à l'arrivée de WOTLK pour simplifier la vie des nouveaux joueurs (doublement de l'expérience donnée par les quêtes, changement des pré-requis, etc...).

Mais si ça crée des conflits avec d'autres quêtes, je peux très bien comprendre qu'il n'y ait aucun changement. En tout cas, merci énormément pour vos réponses sur ce report bug :-3
