### ISSUE TITLE
Spell: Fleur de vie

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#38]
**Description**
Serveur test, fonctionne correctement sur le prod
Le heal direct à la fin du HoT heal moins que ce qu'il devrait, 

**Étapes de reproduction**

- Drood 80, aucun talent, Fleur de vie rang max
J'ai pas la formule sous la main donc on va procéder par élimination, voilà les comportements du sort actuellement sur le serveur test :
- Sans talent perso à nu :
Hot            1 stack 53/seconde, 3 stacks 159 => OK
heal direct 1 stack 776,              3stacks, 2328 => OK

- sans talent, add et équip 50358 (+179 PS),
Hot            1 stack 70/seconde,          3  stacks  210 => OK
**heal direct 1 stack 826 (!!!)                    3stacks, 2378 (!!!)**

- sans talent perso à nu, .cast 33891
Hot            1 stack 56/seconde, 3 stacks  168 => OK
heal direct 1 stack 822,              3stacks, 2467 => OK

Désolé pour tous ces chiffres c'est pour te prouver que le soucis vient du calcul avec la puissance des sorts

**Comportement attendu**

- sans talent, add et équip 50358 (+179 PS),
Hot            1 stack 70/seconde,    3  stacks  210 => OK
heal direct 1 stack 868                  3stacks  2604

**Comment by joshwhedon** [comment]
https://wowwiki.fandom.com/wiki/Spell_power_coefficient
Mise a jour des coefficients base sur ces donnees de la 3.3.
Je corrige aussi quelques soucis niveau des calculs (mauvaise prise en consideration de bonus).
