### ISSUE TITLE
[Talent] Combat sauvage

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#380]
**Description**

Lorsque je tappe une cible (sans poisons) et sans l'empoisonner cela affiche le débuff visuel de combat sauvage et j'ai l'impression qu'il y est appliqué; alors qu'il ne le devrait que lorsque la cible est réellement empoissoné

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: voleur
- Race: /
- Spécialisation: combat
- Sort / Talent / Etc: talent: combat sauvage
- Circonstances (Donjon, Raid, PvP, autre): test sur poteau à orgrimmar
- Equipement: dagues / haches
- Buffs / Debuffs / Enchaînement de sort / Etc: combat sauvage 

**Comportement attendu**

Le débuff ne s'applique que si la cible est réellement empoissoné

**Captures d’écran / Vidéos**

Comme on peut le lire dans le descriptif des talents; et on voit ensuite que la cible à le débuff sans avoir les poisons

![Capture d'écran 2020-04-11 01 49 07](https://user-images.githubusercontent.com/63243193/79030000-3ce2dc00-7b97-11ea-8d81-3d3a43c57a30.png)
![Capture d'écran 2020-04-11 01 48 55](https://user-images.githubusercontent.com/63243193/79030006-42d8bd00-7b97-11ea-9295-d8146f1159e1.png)
![Capture d'écran 2020-04-11 01 48 45](https://user-images.githubusercontent.com/63243193/79030014-48ce9e00-7b97-11ea-9056-2529092760b3.png)

**Ressources additionnelles**

----

**Comment by gtschanz** [comment]
![Capture d'écran 2020-05-06 16 45 57](https://user-images.githubusercontent.com/63243193/81191234-173fcb80-8fb9-11ea-8c0e-595377152ac1.png)
 RE- UP ! je constate que ce bt n'a pas été traité; IL EST IMPOSSIBLE de garder ce débuff sans avoir de poisson actif sur soit; constaté en bg y'a 1 jours; cela est très dommageable en pvp car le débuff reste permanent et il implique qd même ensuite +4% dégâts physique subit

**Comment by joshwhedon** [comment]
Va falloir me trouver avec quel poison / dans quelles circonstances ca arrive parce que tous les poisons que j'ai teste, le debuff est bien retire au retrait du poison. Donc le bt a ete traite.
