### ISSUE TITLE
[Quête] "Tranchegueule" : Bug de l'arrivée de Tranchegueule

### ISSUE THREAD

**Issue by Freyahh** [way-of-elendil/3.3.5#381]
**- Description**
Durant la quête intitulée "Tranchegueule", lorsque l'on dépose l'objet "Paquet d'os de dragon" sur le "Bûcher éternel", Tranchegueule apparaît mais n'arrive pas en haut de la colline, ce qui n'est pas normal.

Toutefois, **il existe un moyen de le débloquer** : une fois que le "Paquet d'os de dragon" est déposé sur le "Bûcher éternel", et que Tranchegueule apparaît mais n'arrive pas en haut de la colinne, il suffit de reprendre la quête et de re-déposer une 2ème fois le "Paquet d'os de dragon" sur le "Bûcher éternel", mais cela fait apparaître un 2ème Tranchegueule au lieu d'un seul et les font arriver quelques secondes tous les 2 ensembles, ce qui est problématique pour les joueurs de niveau équivalent à la quête.

**- Comportement attendu**
Au moment où l'on dépose l'objet "Paquet d'os de dragon" sur le "Bûcher éternel", Tranchegueule est censé arriver normalement en hau de la colline, et ce quelques secondes après avoir déposé le "Paquet d'os de dragon" sur le "Bûcher éternel".

**- Étapes de reproduction**
1) Se rendre dans la région de l'Île de Brume-Sang, en Kalimdor ;
2) Aller voir le Prince Toreth sur l'île Balafre-du-ver au Nord-Est de la région ;
3) Prendre et terminer tout d'abord les quêtes "Rétablir la tranquillité" puis "Vers le Rêve" auprès du Prince Toreth ;
4) Prendre ensuite la quête "Tranchegueule" auprès du Prince Toreth ;
5) Se rendre en haut de la colline sur l'île Balafre-du-ver ;
6) Déposer le "Paquet d'os de dragon" sur le "Bûcher éternel" ;
7) Se rendre compte que Tranchegueule apparaît, mais ne s'envole pas vers le haut de la colline, ce qui n'est pas normal ;
8) Reprendre la quête "Tranchegueule" auprès du Prince Toreth ;
9) Déposer à nouveau le "Paquet d'os de dragon" sur le "Bûcher éternel" ;
10) Se rendre compte également qu'un 2ème Tranchegueule apparaît, mais que les 2 Tranchegueules qui sont appararus s'envole pas vers le haut de la colline, ce qui n'est pas normal non plus.

**- Captures d’écran / Vidéos**
Pas de screen ou vidéo à la clé. On peut s'en rendre compte simplement en suivant les étapes.

**- Ressources additionnelles**

Quête "Tranchegueule" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=9689
- WoW Head : https://fr.classic.wowhead.com/quest=9689

PNJ "Tranchegueule" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=17592
- WoW Head : https://fr.classic.wowhead.com/npc=17592

Objet de quête "Paquet d'os de dragon" :
- WoE Head : https://woehead.way-of-elendil.fr/?item=24221
- WoW Head : https://fr.wowhead.com/item=24221

Sort "Incinération des os de dragons" :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=31268
- WoW Head : https://fr.wowhead.com/spell=31268

Entité "Bûcher éternel" :
- WoE Head : https://woehead.way-of-elendil.fr/?object=181988
- WoW Head : https://fr.wowhead.com/object=181988

PNJ "Prince Toreth" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=17674
- WoW Head : https://fr.wowhead.com/npc=17674

Quête "Vers le Rêve" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=9688
- WoW Head : https://fr.classic.wowhead.com/quest=9688

Quête "Rétablir la tranquillité" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=9687
- WoW Head : https://fr.classic.wowhead.com/quest=9687

**Comment by Killyana** [comment]
On n'y peut rien, c'est lié aux grids, il faut s'approcher de lui pour qu'il bouge.

**Comment by Freyahh** [comment]
Dommage que les grids soient aussi peu étendus à cet endroit précis. Ça éviterait d'attendre qu'il atterrisse. Toutefois, ça reste faisable et c'est tant mieux. Du coup, merci pour ta réponse.

**Comment by joshwhedon** [comment]
J'ai essaye quelques trucs sans succes, pas moyen de le faire bouger quand il spawn aussi loin.

**Comment by Freyahh** [comment]
Peut-être faudrait-il rouvrir ce ticket, dans ce cas. Avez-vous réessayé de le débloquer en remettant le paquet une 2ème fois sur le bûcher éternel ?
