### ISSUE TITLE
bug rencontré au joug charge war annule piège chasseur

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#382]
**Description**

Le war (jayprox) me charge j'ai posé les pièges devant moi pour qu'il les déclenche et au lieu de ça; sa charge annule les pièges; est-ce un comportement normalement attendu???

**Étapes de reproduction**
- Emplacement / Zone / Arène / Champ de bataille: joug en duel
- Faction / Race / Classe du personnage utilise: war vs chasseur

**Comportement attendu**

le war charge et dès qu'il a son pied au dessus du trap ça le déclenche

**Captures d’écran / Vidéos**

GO check la vidéo entre 1:33 et 1:40 on voit bien ce dont je parle; la charge déclenche le piège une fois le war dessus

[https://youtu.be/w7LY_r1jGEw](url)

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Deja signale, et deja corrige pour la prochaine mise a jour merci.
