### ISSUE TITLE
[mascote Familles vous Kirin Tor] HF  Lectures studieuses qui ne donne pas  la mascote

### ISSUE THREAD

**Issue by jeremkid** [way-of-elendil/3.3.5#383]
Bonjour il y a un petit problème avec le HF "Lectures studieuses"
Le HF fini on obtient bien le libre "Les écoles de magie des Arcanes - Maîtrise"apres on l'utilise pour ce téléporter  dans la flèches de la citadelle.Arriver devant l'Archimage Vargoth  il ne nous donne pas la mascote "Familles vous Kirin Tor"

Nom personnage in game"hikigam" 
Merci

**Comment by Killyana** [comment]
C'est envoyé par la poste.

**Comment by jeremkid** [comment]
Re bonjour  merci pour l'information.Mais pour quelle sois envoyer par la poste  il faut pas discuter avec l'archimage vargoth?Comme je le disais au dessus,que j'ai mal expliquer d'ailleur.On ne peux pas lui parler le problème et la .

Merci

**Comment by Ischjgt** [comment]
Non, tu n'as rien reçu là?

**Comment by jeremkid** [comment]
non rien du tout sauf le livre pour me téléporter

**Comment by jeremkid** [comment]
Mon nom de perso et Hikigam

**Comment by Killyana** [comment]
Il faut utiliser le livre pour se tp en haut de la citadelle pourpre puis parler à un pnj qui vous donnera le pet

**Comment by jeremkid** [comment]
oui justement  quand je lui parle  il veux pas me  parler  il y a pas de discoure avec lui juste un texte fix donc je ne peux pas avoir le pet maleresement

**Comment by jeremkid** [comment]
dsl pour les explication nul et l’orthographe un grand merci pour l’assistance plus cas attendre ^^

**Comment by Killyana** [comment]
Y'a effectivement une erreur, sa sera corrigé prochaine maj
