### ISSUE TITLE
Quest: Diversions écarlates

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#386]
**Description**

5096 - [Diversions écarlates] 
12807 - [Bannière du Fléau] 

Pas réussi à utiliser la bannière, mauvais emplacement tout le temps

**Comment by Killyana** [comment]
Même bug que https://github.com/way-of-elendil/3.3.5/issues/239

**Comment by Killyana** [comment]
Sera corrigé avec https://github.com/TrinityCore/TrinityCore/issues/24439

**Comment by joshwhedon** [comment]
Je crois que depuis le changement sur le systeme de spawn, si tu selectionne un gameobject proche, et qu'il est pas spawn, ca le trouvera pas.
