### ISSUE TITLE
BG: Vallée d'Alterac

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#388]
**Description**
"Ticket: 15707. Created by: [] Ticket Message: [la team qui était en sérieux désavantage et bien derrière  a win l'alterac sans raison (aucun boss tombé)
timer ?] "

**Comment by joshwhedon** [comment]
Va me falloir un peu plus d'information que ca :D

**Comment by joshwhedon** [comment]
A reouvrir quand il y aura plus d'information disponible, j'ai verifie tous les modes de victoire / defaites, pas vu de soucis, et meme en fermant tot ca donne la victoire a l'equipe avec le plus de points.
