### ISSUE TITLE
NPC: Xink's Shredder (Débitez-les !)

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#389]
**Description**

Name: Xink's Shredder
Entry: 27061.
47921 - [Lancement de lames de scie, rank 1 frFR]
47966 - [Trousse de réparation d'urgence, rank 1 frFR]

- Le lancement de lame ne lance pas de lame devant mais sur un monstre à portée qu'elle que soit sa position
- La trousse de réparation d'urgence ne marche pas

**Comment by Killyana** [comment]
Le spell 47921 - [Lancement de lames de scie, rank 1 frFR] fonctionne correctement sa nécessite juste d'avoir une cible à porté, il inflige des dégâts en conne sur 5 mobs

Pour la trousse de réparation d'urgence sa marque insensible je ne sais pas pourquoi:
https://woehead.way-of-elendil.fr/?spell=47966

**Comment by joshwhedon** [comment]
C'est parce que c'est un robot et les robots ne peuvent etre soignes.

**Comment by Rushor** [comment]
Pour la trousse de réparation d'urgence sa marque insensible je ne sais pas pourquoi:

> because vehicle.cpp _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL, true);
