### ISSUE TITLE
Système: Invocation avec le parrainage

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#39]
**Description**
Serveur prod
Il est actuellement possible d'utiliser l'invocation depuis un perso au dela du niveau 60 (constaté sur un 80)(l'inverse n'est pas faisable).
Il est également possible d'invoquer son parrain (normalement le TP n'est dispo que dans un sens si je ne m'abuse)

**Étapes de reproduction**
- Créer un compte A
- Créer un second compte B, en mettant le compte A en parrain.
Le compte A est maintenant le parrain et le compte B filleul
- Créer 1 perso de la même faction (et de préférence même race, c'est plus facile pour test) sur chacun des comptes, grouper les 2 persos et les ajouter en ami
- .level 79 le perso du compte B
- Après avoir vérifié que les 2 persos sont sur le même continent (en faisant gaffe avec l'extension BC blabla), utiliser l'invocation avec le perso 80

**Comportement attendu**
"Toutes les heures, le parrain peut invoquer son filleul si celui-ci est dans son groupe."
"Le bonus d'expérience et le don de niveau ainsi que l'invocation ne sont valables que jusqu'au niveau 60."
https://way-of-elendil.fr/nous-rejoindre/parrainage.html

**Comment by joshwhedon** [comment]
Summon Friend is an ability only available through the Recruit-A-Friend program. It allows one of a pair of characters on accounts linked through RAF to summon the other to their location.
Les deux ont l'air d'avoir la possibilite de s'invoquer l'un l'autre.

**Comment by joshwhedon** [comment]
LA limite de niveau sera mise a la prochaine maj
