### ISSUE TITLE
Pet: Les pets des chasseurs doivent avoir 100% de la resilience du maitre

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#390]
**Description**
Patch 3.3.0 (2009-12-08): Hunter pets now have 100% of their master's resilience; increased from 40%. 
https://wow.gamepedia.com/Hunter_pet#Pet_scaling
Actuellement ils ont pas de résilience si je me trompe pas

**Comment by joshwhedon** [comment]
Ils ont pas de resilience mais le maitre est utilise pour les calculs de resilience:
if (victim->GetTypeId() == TYPEID_PLAYER)
        target = victim;
    else // victim->GetTypeId() == TYPEID_UNIT
    {
        if (Unit* owner = victim->GetOwner())
            if (owner->GetTypeId() == TYPEID_PLAYER)
                target = owner;
    }
Donc normalement le cas de 100% est deja gere, pour tous les pets / invocations / etc.
