### ISSUE TITLE
Transfert: Zone de récupération

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#392]
**Description**

Un joueur qui a fait une récup a eu un soucis en sortant de la zone instancié, il était bloqué. Je me suis TP sur lui et je me suis retrouvé dans le vide et mort

Peut-etre du à ça :
"
À [] : Donc t'avais pas fini t'as récup, t'avais pas récup tout ton stuff etc, mais t'es allé voir le dernier perso pour sortir?
[] chuchote : non effectivement. 
[] chuchote : je pensais que c'était terminé."

**Comment by joshwhedon** [comment]
Impossible a reproduire de mon cote, il va falloir un peu plus d'info sur ce qui s'est passe. Sa classe, ou le joueur a ete teleporte, etc etc.
