### ISSUE TITLE
Banc de dards, poissons-spores, mixte en eau saumâtre

### ISSUE THREAD

**Issue by Flocapa** [way-of-elendil/3.3.5#394]
Les bancs de dards, de poissons-spore et mixte en eau saumâtre en outreterre n’apparaissent pas (2 jours à les chercher et à attendre un potentiel repop). Les bancs de dards sont censés être en foret de terokkar, et les 2 autres bancs (poissons-spores et mixte en eau saumâtre) dans les marécages de zangar.

**Comment by Flocapa** [comment]
Alors je sais pas si vous avez fermer parce que le bug était corrigé mais en tout les cas le bug est toujours d'actualité. Pire encore il n'y a qu'un seul banc de poisson en Terrokar et il n'est même pas censé être là (c'est un détritus de la pompe à vapeur, ce genre de banc ne doit pop qu'en marécage de zangar).

**Comment by Killyana** [comment]
@joshwhedon j'ai remarqué que Serfex the Reaver et Les bancs de dards sont dans le group 2 de https://trinitycore.atlassian.net/wiki/spaces/tc/pages/87293959/spawn+group+template
peut être sa entre en conflit d'une façon ou une autre avec le pooling.
``` sql
SELECT * FROM spawn_group WHERE SpawnId=80429;
SELECT * FROM spawn_group WHERE SpawnId IN (SELECT guid FROM gameobject WHERE id=182956);

**Comment by joshwhedon** [comment]
Je comprends pas ce qu'ils font dans group template. C'est pas juste utilise pour les scripts ?

**Comment by joshwhedon** [comment]
Ca a l'air corrige. J'ai verifie les spawns ont l'air tous la. Faudra me dire si vous rencontrez encore des soucis.
