### ISSUE TITLE
[Quête] "Ver querelleur" : Bug de la capture des rejetons jormungars

### ISSUE THREAD

**Issue by Freyahh** [way-of-elendil/3.3.5#395]
**- Description**
Durant la quête intitulée "Ver querelleur" donnée par le gobelin Zort au nord de la Désolation des Dragons, en Norfendre, il est impossible de capturer les rejetons jormungars du cœur de glace qui se trouve dans les cavernes de l'Étau de Cristal, ce qui n'est pas normal.

En effet, lorsque l'on sélectionne un rejeton jormungar du cœur de glace et que l'on utilise les "Caisses solides" sur lui, le rejeton ne disparaît pas, une caisse apparaît à son emplacement, mais il est impossible de récupérer de "Rejeton jormungar capturé" en cliquant sur la caisse qui apparaît pour pouvoir avancer dans la quête.

Ceci a été testé tout récemment avec un autre joueur.

**- Comportement attendu**
Au moment où l'on utilise les "Caisses solides" sur un rejeton jormungar du cœur de glace dans les cavernes de l'Étau de Cristal, celui-ci doit disparaître et une caisse doit apparaître à la place, et lorsque l'on clique sur la caisse qui apparaît, on doit pouvoir récupérer un "Rejeton jormungar capturé" en cliquant dessus.

**- Étapes de reproduction**
1) Se rendre à l'Étau de Cristal au nord de la Désolation des Dragons, en Norfendre ;
2) Prendre la quête "Ver querelleur" auprès du gobelin nommé Zort ;
3) Entrer dans les cavernes de l'Étau de Cristal un peu + au nord de la position de Zort ;
4) Trouver et sélectionner un "Rejeton jormungar du cœur de glace" dans les cavernes ;
5) Utiliser l'objet de quête "Caisses solides" sur un rejeton ;
6) Se rendre compte que le "Rejeton jormungar du cœur de glace" sélectionné ne disparaît pas, qu'une caisse apparaît à son emplacement, et que la caisse ne donne aucunement au joueur un "Rejeton jormungar capturé" en cliquant simplement dessus, ce qui n'est pas normal du tout. 

**- Captures d’écran / Vidéos**
Pas de screen ou vidéo à la clé. On peut s'en rendre compte simplement en suivant les étapes.

**- Ressources additionnelles**

Quête "Ver querelleur" :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=12078
- WoW Head : https://fr.classic.wowhead.com/quest=12078

PNJ "Rejeton jormungar du cœur de glace" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=26359
- WoW Head : https://fr.classic.wowhead.com/npc=26359

Objet de quête "Caisses solides" :
- WoE Head : https://woehead.way-of-elendil.fr/?item=36771
- WoW Head : https://fr.classic.wowhead.com/item=36771

Sort "Capturer un rejeton jormungar" :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=47431
- WoW Head : https://fr.classic.wowhead.com/spell=47431

Entité "Rejeton jormungar capturé" :
- WoE Head : https://woehead.way-of-elendil.fr/?object=190510
- WoW Head : https://fr.classic.wowhead.com/object=190510

Sort "Force Captured Jormungar Spawn" :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=47451
- WoW Head : https://fr.classic.wowhead.com/spell=47451

PNJ Donneur de la quête "Zort" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=26659
- WoW Head : https://fr.classic.wowhead.com/npc=26659

**Comment by Killyana** [comment]
J'arrive à loot la caisse y'a juste le mobs qui dispawn pas quand l'a caisse spawn

**Comment by Freyahh** [comment]
Il faudrait voir avec le joueur en question, dans ce cas. Il est côté A2. Après avoir sélectionné le rejeton et cliqué sur les caisses solides, lorsqu'il cliquait sur la caisse qui apparait sur ce dernier, il ne parvenait pas à obtenir le rejeton jormungar capturé. Il s'y est peut-être mal pris, mais je ne pense pas, car la caisse disparaissait à chaque fois qu'il cliquait dessus.

**Comment by Killyana** [comment]
Soit il a l’inventaire full ou il est dans un groupe, de toute façon y'avait un autre bug sur la quête.

**Comment by Killyana** [comment]
Despawn du mobs fixé, à part ça tout fonctionne correctement.

**Comment by Freyahh** [comment]
Parfait ! J'avais peut-être miss clic sur l'interface de groupe sur mon personnage lorsque j'ai changé le mode de butin. J'ai peut-être cliqué sur le bouton 'Mode raid' sans faire exprès. En tout cas, milles fois mercis :-)
