### ISSUE TITLE
[La Bataille pour Fossoyeuse] amortissement de chute ne fonctionne pas

### ISSUE THREAD

**Issue by Chelpard** [way-of-elendil/3.3.5#396]
**Description**
Apres la fin de la bataille de la cour pour descendre dans la ville Thrall invoque des cyclones pour amortir la chute du joueur, Ils ne fonctionnent pas

**Étapes de reproduction**
Apres avoir gagner la bataille de la cour de Fossoyeuse Thrall et Sylvanas se dirigent vers l'ascenseur bloqué
Thrall invoque des cyclones et se tp en bas
Le joueur saute pour dedans pour amortir sa chute 
Le joueur s'explose le crane contre le sol et meurt de dégâts de chute 

**Comportement attendu**
Les cyclones devrait amortir la chute du joueur

**Comment by Killyana** [comment]
Dup https://github.com/way-of-elendil/3.3.5/issues/16
