### ISSUE TITLE
Spell: Combat Sauvage

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#397]
**Description**

Le debuff ne disparait jamais, constaté sur du PvP sauvage

51682 applique 58684
58413 -> 58683

**Comportement attendu**
Je trouve pas quand il doit se barrer exactement :c

**Comment by Justforsoloq** [comment]
Seule ligne que j'ai trouvé sur la durée c'est ça :
Hotfix (2009-04-23): "The Rogue talent Savage Combat should now properly be removed after leaving an arena match. [1]" 
https://wowwiki.fandom.com/wiki/Savage_Combat

**Comment by joshwhedon** [comment]
Avec quel poison ? Parce que j'arrive pas a reproduire, le combat sauvage se retire au retrait des poisons pour moi.

**Comment by gtschanz** [comment]
bah regarde mon ticket josh; j'arrivais même à le mettre en fufu sans avoir de poison actif... (je pense que tu peux associer les 2 tickets

**Comment by joshwhedon** [comment]
On est blizzlike : https://www.mmo-champion.com/threads/622720-So-Savage-Combat
Et oui pour le proc sans poison actif ce sera regle aujourd'hui. C'est surement pour ca que le debuff reste en fait.  Je ferme le bug, si ca se reproduit apres la maj d'aujourd'hui faudra me dire.
