### ISSUE TITLE
Carapace anti-magie

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#399]
**Description**
L'AMS ne marche pas pour évité les flammes sur la reine Lana'Thel, elle laisse aussi passer les maladies du chevalier de la mort en pvp.

**Étapes de reproduction**
- Classe : DK
- Race : Orc
- Spécialisation : Sang
- Spell : Carapace anti-magie
- Circonstances (Donjon, Raid, PvP)

**Comportement attendu**
La carapace du DK doit rendre celui ci insensible à tout les spells sauf le débuf de l'ombreflamme de démo si elle est glyphé (réduc de déplacement)

**Comment by joshwhedon** [comment]
Normal que les flammes passent, les immunites ne concernent pas certains sorts de boss.
Pour ce qui est des maladies, c'est aussi normal. La carapace anti magie est contre la magie, hors les effets de poisons, maladies, etc, ne sont pas des effets magiques.
https://www.wowhead.com/spell=48707/anti-magic-shell#comments
silkfire on 2008/09/26 (Patch 3.0.1)

Curses, poisons and diseases can still be applied, so warlocks have an advantage here.

**Comment by Elahbienscript** [comment]
Pas tout à fait d'accort, si le touché de glace (classé spell magique) ne passe pas dans l'AMS la maladie n'est pas appliquée, comme pour la chaine de glace sinon elle appliquerai aussi la maladie sous AMS. pour la frappe de peste et bien étant donné que le spell appliqué est physique il doit appliqué la maladie normalement. Après j'ai testé L'AMS sur d'autre serveur 'scripté' en pvp et les 2 maladies ne sont pas appliqué avec un tag 'insensible'. 
Pour la reine si la carapace est appliqué avant le débuff des flammes, l'AMS devrait pourvoir absorber le débuff et donc le dk ne pose aucune flammes me semble t'il, si t'as de quoi me prouvé le contraire je veux bien.
