### ISSUE TITLE
Vers de sang

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#401]
**Description**
Les vers de sang sont tjrs bugé et tape à ~20, ils se font paré et esquivé alors que le dk est capé expertise.

**Étapes de reproduction**
- Classe : DK
- Race : Orc
- Spécialisation : Sang
- Vers de sang
- Circonstances (Donjon, Raid, PvP)

**Comportement attendu**
Les vers doivent taper à ~ 200 et ne pas être parry si ils sont dans le dos et que le dk est capé expertise.

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/42
