### ISSUE TITLE
Lévitation du prêtre

### ISSUE THREAD

**Issue by Tontonsid** [way-of-elendil/3.3.5#402]
le refresh de la lévitation annule celle déjà active et fait chuter le personnage avant qu'elle ne soit effective au lieu de simplement prolonger l'effet

**Comment by joshwhedon** [comment]
![image](https://user-images.githubusercontent.com/543699/79057543-dd272680-7ca5-11ea-9124-31e88d2970f2.png)

Je viens de tester, j'ai spamme la levitation, et ca prolonge bien l'effet.
