### ISSUE TITLE
Rchaman / Eveil ancestral

### ISSUE THREAD

**Issue by HetMishtapeu** [way-of-elendil/3.3.5#403]
**Description**
Chaman spé Restauration
Talent restauration ligne 9 / Eveil ancestral rang 3
Ne proc pas

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Chaman
- Orc
- Restauration
- Sort : Vague de soins, vague de soins inférieure, remous / Talent : Eveil ancestral
- Pve (donjon,raids)

**Comportement attendu**
Lorsqu'un heal est lance grâce à Vague de soins, vagues de soins inférieure ou remous, l'éveil ancestral est censé heal une personne ayant le moins de PV dans les 40m pour un montant de 30% du heal produit à la base.

**Comment by joshwhedon** [comment]
Ca proc chez moi, uniquement sur les critiques cela dit, comme indique dans le sort.
![image](https://user-images.githubusercontent.com/543699/79057633-ba494200-7ca6-11ea-9edc-c7c9d01c077c.png)

**Comment by Ewilanwoe** [comment]
Effectivement, après des tests ça semble bien fonctionner en self cast sans être en groupe, mais ne proc plus du tout dès qu'on est en groupe.

En solo : 
![WoWScrnShot_041220_142502](https://user-images.githubusercontent.com/63348105/79068854-4c167680-7cca-11ea-9280-e1780119c861.jpg)

En groupe : 
![WoWScrnShot_041220_142958](https://user-images.githubusercontent.com/63348105/79068864-63556400-7cca-11ea-86ca-86adedb8e0af.jpg)

Quatre critiques d'affilées et 0 proc ...

**Comment by joshwhedon** [comment]
Il va falloir que tu fasse un ticket en jeu et que tu demande a un mj de venir te voir. J'ai teste, en raid, en groupe, a Dalaran, meme de derriere un arbre. Et ca proc sans soucis pour moi. T'es sur d'avoir le talent ? :D 
![image](https://user-images.githubusercontent.com/543699/79095245-42117800-7d9d-11ea-8711-7d1169669f4a.png)

**Comment by Ewilanwoe** [comment]
Oui j'ai bien le talent :D 

Mais effectivement, j'ai refais des tests aujourd'hui, en allant en situation de combat, en groupe et groupe de raid, et aucun souci de proc.
Je comprends pas pourquoi hier ça voulait pas ... Je garderai un œil dessus au cas où, mais à priori plus de problème de ce côté.

**Comment by joshwhedon** [comment]
Bizarre. Tiens moi au courrant si ca se reproduit, et ideallement appelle un gm pour qu'il matte ton perso directement.
