### ISSUE TITLE
[Classe MAGE] Transfert

### ISSUE THREAD

**Issue by AngelMasterBE** [way-of-elendil/3.3.5#404]
Bonsoir

Ce soir a icc25NM, j'ai eu plusieurs bug sur le transfert de la classe mage, Une fois sur le bateau de la horde, j'ai fait un transfert â travers le bateau de la horde puis je suis tombé au sol (Sol neige sous le bateau)

Ainsi que sur le boss Lich king, ou j'ai fait un transfert depuis le centre de la plateforme pour partir vers la zone de transition je me suis aussi retrouver ou la map du boss (puis mort quasi instant)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe : Mage
- Race : Troll
- Spécialisation : Mage Feu/Givre/Arcane
- Sort / Talent / : Transfert
- Circonstances (Donjon, Raid, PvP, autre) : Raid ICC 25 (icc10nm, HM, 25H)

**Comportement attendu**
Transfert 20m en avant

**Comment by joshwhedon** [comment]
Peu de chance qu'on puisse corriger ca, le transfert sur des objets dynamiques ne va pas fonctionner parce qu'ils ne font pas partie des maps.

**Comment by Killyana** [comment]
Faudra attendre que Trinity implémente les maps pour ces objets dynamiques, même si je trouve que le résultat actuel n'est pas dégueux par rapport à avant
