### ISSUE TITLE
[RAID ICC] Lich King

### ISSUE THREAD

**Issue by AngelMasterBE** [way-of-elendil/3.3.5#405]
bonsoir

Ce soir sur le boss Lich king, nous avons eu un bug assez intéressant du type LK qui vol (Arthas qui décide de partir vers les cieux !)

En derniers Phase P5
Pendant le combat, a un moments nous avons perdus les deux tanks, l'agro du 3eme qui était sur LK, ses retrouver dans la deuillegivre (Moisson d'âmes - combat menethil/add) à ce moments la LK est parti voir la "Team Rocket", est parti dans les air direction le ciel (il est parti vers un joueurs hors zone)

Voir screen
https://nsa40.casimages.com/img/2020/04/12/200412054550663128.png

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon : ICC10-25
- Boss : Lich king
- Composition du groupe : Gennesis, Natsukun Glyphozat,pealux,aasarianne,Olivia,chaameau,amical, petitfilou,Zhana,woolix,Kaeryn,eldjim,ashani,layhksa,kenskin,arada,casteris,zepag,joojon,soulmuch,Fistheland,burste, ankhsunamoon

**Comportement attendu**
Je suis pas sûr
Je pense au moment de la personne dans la deuilles, il doit avoir un reset de l'agro ou avoir une agro nul le temps de l'event avant de revenir sur le combat normal

J'ai pas assez d'information actuellement pour validez à 100%, mais le fait que LK parte vers le ciel est pas normal

**Comment by joshwhedon** [comment]
Normalement il peut deja pas attaquer les joueurs dans deuillelombre. Un aura invisible l'empeche : 
https://www.wowhead.com/spell=74276/in-frostmourne-room
la prochaine fois que ca se produit faudrait qu'un mj soit la pour voir qui a ete agro et pourquoi.

**Comment by AngelMasterBE** [comment]
Bonsoir

Après on est pas a l’abri d'un bug très rare et isolé

Le soir ou le bug ses produit, Une personne était présente dans la deuille avant de perte nos tanks, Nous avons eu l'impression qui à voulu suivre la personne la plus haute a l'agro qui était peut-être bien la personne dans la deuille, Car lors que la personne est sorti de l'event de la deuille, LK est revenu vers la plateforme de combat tranquillement

Voila, J'ai pas plus d'information que ça a te donner pour le moment

**Comment by joshwhedon** [comment]
oui oui je sais, mais ce que je dis c'est qu'il va etre difficile de corriger :(. Autre possibilite, un pet avait l'agro. Mais ca voudrait dire que les joueurs vivants avaient moins d'agro qu'un pet.
