### ISSUE TITLE
[Donjon gundrak] Arrivée dans l'instance

### ISSUE THREAD

**Issue by AngelMasterBE** [way-of-elendil/3.3.5#406]
Bonsoir

Actuellement sur le serveur, on arrive dans le donjon Gundrak via la recherche de donjon sur la porte "ouest" coté "Caverne de mam'toth, Alors que on devrait arrivée du coté EST "Tanière de sseratus"

**Étapes de reproduction**
- Donjon : gundrak
-Recherche de donjon

**Comportement attendu**
Arrivée de la porte EST "Tanière de sseratus" au lieux de pop a l'ouest

**Captures d’écran / Vidéos**
https://nsa40.casimages.com/img/2020/04/12/200412015145255634.jpg

**Comment by joshwhedon** [comment]
Non c'est normal, c'est un debug. La recherche de donjon selectionne maintenant une des entres du donjon au hasard lors du debut du donjon, lorsque celui ci dispose de plusieurs entrees :). A moins que vous ayez des sources indiquant que pour ce donjon, on doit toujours se retrouver a la meme entree.

**Comment by AngelMasterBE** [comment]
Re bonsoir josh, je vais faire ma recherche de mon coté pour ce pop d'instance
mais j'ai souvenir de officiel et après wotlk que le pop ce fait toujours du même coté, je vais revenir vers toi si j'ai la confirmation à 100% de l'arrivée EST comme prévue (Si je trouve...)

**Comment by joshwhedon** [comment]
Merci, j'avais cherche un peu de mon cote quand on m'en avait parler et j'avais rien trouve de concluant malheureusement.
