### ISSUE TITLE
Réinit de dj

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#407]
Réinitialiser toutes les instances n'a pas d'effet (à Stratholme)

**Comment by joshwhedon** [comment]
Vous pouvez tenter de degrouper et de regrouper quand ca arrive

**Comment by AngelMasterBE** [comment]
Attention, faire une réinitialisation en étant en mode 5 joueurs **héroïque** fait que vous pas réinitialisation les donjons (Bug connue avant la merge) 
comme dit Josh, il est possible de passer en 5nm vers 5HM ou l'inverse pour pouvoir réinitialiser le donjon normal

**Comment by Rolirolant** [comment]
ok merci pour l'info, la réinit en nm semble fonctionner

**Comment by joshwhedon** [comment]
Mais si vous etes en mode 5 joueurs normal, les donjons normaux sont reinitialises si vous faites une reinit ?

**Comment by Killyana** [comment]
L'option pour rénit les donjons ne fonctionne pas depuis des années, la seule solution c'est de switch la difficulté 2 fois, mais ceci n'est pas disponible avant le niveau 70

**Comment by joshwhedon** [comment]
Je viens de tester en local et ca marche . Avec strathol;me. J'ai loupe un truc ?

**Comment by Killyana** [comment]
Connectes 2 joueurs un au dessous de 70 et un plus de 70
Groupe les avec le haut level comme lead.
Passes en mode hm.
dégroupes puis avec le bas level essais d'entrer dans un donjon et de le reset.
Sa fonctionnera pas parce que le mode est actif est HM (même pour le joueur bas level)

L'option reset les instance ne doit pas reset le mode actif seulement mais tout les modes:
- Mode normal
- Mode HM s'il n'y a pas d'ID (pas de boss tué)

**Comment by Ferro3** [comment]
vérifié
fix ok
