### ISSUE TITLE
[Troll / Régénaration (passif racial] Ne fonctionne pas du tout

### ISSUE THREAD

**Issue by Langfeust** [way-of-elendil/3.3.5#41]
**Description**
La passif racial des Troll "Régénération ne produit pas les 10% de régénération supplémentaire et la régénération ne se fait pas en combat

**Étapes de reproduction**
Pour vérifier, créer un troll et juste commencer un combat (bug remarqué quand je suis passé niveau 15)

**Comportement attendu**
C'est un des très grands avantage de le lvling et le questing de la race.
Régler le problème rapidement serait un plus pour toute la race :)

**Ressources additionnelles**
https://fr.classic.wowhead.com/spell=20555/r%C3%A9g%C3%A9n%C3%A9ration

**Comment by Ischjgt** [comment]
Le talent fonctionne correctement

> Pour vérifier, créer un troll et juste commencer un combat (bug remarqué quand je suis passé 

> niveau 15)

=> Chez moi ça fonctionne correctement, la regen se fait lorsqu'on est en combat

**Comment by Langfeust** [comment]
A hauteur de 1pv par 5sec.
Hors elle devrait être la même que hors combat.
En tout cas, c'est le cas chez moi

**Comment by Ischjgt** [comment]
Le spell :

> Vitesse de récupération des points de vie augmentée de 10%. 10% de la vitesse de récupération 

> des points de vie sont actifs pendant les combats

Hors elle devrait être la même que hors combat. => Non.
110% hors combat et 10% de 110% en dehors des combats

**Comment by Langfeust** [comment]
Mon mauvais!
Mauvaise traduction depuis l'anglais
