### ISSUE TITLE
Instance: Profondeurs de Rochenoire

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#410]
**Description**
Arrivé au Sinistre écluseur, la porte menant à la suite de l'instance finit par s'ouvrir toute seule

La porte : [Bar Door] GUID: 15298 ID: 170571

Dans le journal de combat :
Soldat Rochenœud lance Disparition de Nagmara.
Gouvernante Nagmara lance Disparition de Nagmara.

Name: Private Rocknot
Entry: 9503.
Name: Mistress Nagmara
Entry: 9500.

En fait ce qu'il se passe c'est que Nagmara utilise son spell sur le Soldat Rochenœud comme si les joueurs avaient complétés la quête 4201
De plus, il faut normalement parler à la succube pour que les 2 NPCs utilisent le fameux spell Disparition

**Comment by Killyana** [comment]
Ouvert par:
Entry: 9500.
Name: Mistress Nagmara
AIName: SmartAI ScriptName: npc_mistress_nagmara

**Comment by Killyana** [comment]
J'ai l'impression que l'event dans le cpp qui est déclenché en wp3 se fait aussi au waypoint_data et pas que script_waypoint
