### ISSUE TITLE
Baisse de la plage de dégats des familiers chasseurs 

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#411]
**Description**
Les plages de dégâts des familiers sont largement inférieurs à celles d'avant la merge ( une baisse générale d'environ 30% ( un peu plus pour les BM )) qui à l'air de venir d'un dps des familiers très faible , actuellement un familier 80 avec un chasseur non BM qui a 6000 de pa fait 156 de dps et une plage de dégâts de 312 à 313 ( sur la page de stats du familier )
Le scale sur la puissance d'attaque du chasseurs sont bons ( par exemple en puissance d'attaque le familier reçoit bien 22% de la PA du chasseurs ) cependant le dps du familier est beaucoup trop faible

De plus pour tester ça , une bète non apprivoisée possède une plage de dégâts supérieure à celle qu'on à quand elle est apprivoisée ( même avec un lvl inférieur ) par exemple là j'ai pris ( vous avez les screens ) un condor qui a une plage de dégâts de 307 à 439 avant capture ( lvl 72 ) et qui se retrouve avec 239 - 240 après capture ( lvl 75 ) ( d'ailleurs au passage la plage de dégâts de nos familiers ne varie que d'un point quelque soit le familier apprivoisé j'ai regardé en scannant à Dalaran une dizaine de familiers de chasseurs avec "Connaissance des bêtes"  ) ce qui lui fait un dps de 120 ... ( pour un pet 75 c'est léger )
Le soucis viens probablement des familiers eux mêmes car les familiers reçoivent bien les bonnes valeurs de stats en fonction de celles du chasseur

**Captures d’écran / Vidéos**
https://ibb.co/BVLbp1w ( avant capture ) 
https://ibb.co/ZW5YYQN ( après capture ) 

https://ibb.co/HHj2CNs ( familier actuel avec 5847 de PA pour mon chasseur ) la plage tournait aux alentours des 450 avant la merge 

**Ressources additionnelles**
Le scale de la puissance d'attaque par rapport à celle du chasseur fonctionne bien , celle de l'endurance et de l'armure aussi.

J'ai pas réussi à avoir des screens offi sur les stats des pets donc si y'en a qui lisent ça et qui ont ça sera bénéfique mais actuellement tout les chasseurs sont d'accord pour dire que leurs pets tapent moins qu'avant

**Comment by gtschanz** [comment]
@joshwhedon ça en est où concernant les dégâts des pets ? mon pet chasseur en spécialisation précis (loup) et avec les talents férocité alors qu'il a un up de ma pa se fait dépop par des élémentaires qui ont 11k pv au joug et qui tappe à 300 et mon loup à 100 de dégâts... les pets ont subit un nerfs trop important depuis la merge; je peux aussi check pour te trouver des preuves; mais le nerfs est trop conséquent pour être légit; depuis la merge les pets tapent à peine à 5 à 10% de ce qu'il faisait avant merge

**Comment by joshwhedon** [comment]
Des ajustements seront en place demain dans la journee.
