### ISSUE TITLE
Shattrath: Les NPC Hostiles attaquent les joueurs

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#413]
**Description**

Name: Aldor Vindicator
Entry: 18549.
Name: Scryer Arcane Guardian
Entry: 18568.

Ces NPCs attaquent les joueurs dans Shattrath,  c'est une zone sanctuaire
Bonus : une fois mort, les gardes continuent d'attaques le cadavre des joueurs

**Comment by joshwhedon** [comment]
Heu je crois que c'est normal
T'es pas suppose t'avanturer des les quartier de la faction avec laquelle tu n'es pas allie

**Comment by Ischjgt** [comment]
Oui, et pour ça, tu reçois un débuff Exil (c'est nouveau!, c'est un peu comme un mal de rez) et te fait TP en dehors de Shattrath.
Mais c'est comme te balader à Dalaran dans les quartiers de la faction opposée, t'es TP en dehors, la zone étant une zone sanctuaire, les PNJs hostiles ne t'attaquent pas (exception sur la quête Quel'Delar)

**Comment by Killyana** [comment]
Non ils parlent bien de combat contre ces npcs https://fr.wowhead.com/npc=18549/redresseur-de-torts-de-laldor#comments:id=242514
