### ISSUE TITLE
bug combat trash icc

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#414]
**Description**

Le bug combat après avoir tué des trashs à icc est souvent persistant; on avait des bugs combat après trashs sur givre / putri / parfois encore walkyr - minimum 1 à 2 bug combat trash à icc ce qui est assez pénible chaque fois car pour permettre la regen des heals / cast il faut souvent wype ce qui fait perdre à chaque fois 5 à 10 min pour repop + rebuff

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): all mode
- Boss
- Sort en question / Phase du boss en question / Emplacement: après saurcroc / avant putri / sur l'aile de givre
- Composition du groupe

**Comportement attendu**

pas de bug combat après avoir tué les trahs

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Deja signale ici : https://github.com/way-of-elendil/3.3.5/issues/319
Pas besoin de resignaler.
