### ISSUE TITLE
[Quete] Trahison

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/3.3.5#415]
**Description**
Similairement a https://github.com/way-of-elendil/3.3.5/issues/236 les npcs controlles n'attaquent pas.

**Comment by Ischjgt** [comment]
Entry: 28931 suit le joueur même si celui-ci lui demande d'attaquer un ennemi. Il fait ses spells correctement mais pas d'auto-attacks.
Pour l'instant pour faire la quête il faut cliquer sur l'icone "Reste" du familier en ayant placé le troll chancre-sang au corps à corps de Drakuru

**Comment by Ischjgt** [comment]
Soucis quand le npc controllé est en passif :
- il faut spam le bouton Attaque pour que le troll chancre-sang se mette au corps à corps de Drakuru
- dans cette position, même en étant au corps à corps, le NPC ne fait pas d'auto attaque

**Comment by joshwhedon** [comment]
Corrige prochaine maj mais dans l'immediat il suffit de passer le pet en aggressif ou defensif.
