### ISSUE TITLE
Donjon de la fournaise de sang

### ISSUE THREAD

**Issue by Amenardis** [way-of-elendil/3.3.5#418]
**Description**
Les portes menant au second boss ainsi que celles des orcs ne s'ouvrent pas.

**Étapes de reproduction**
Lors du passage dans le donjon de la fournaise de sang (level 59-68), arrivée dans la seconde salle où il faut activer un levier afin d'ouvrir une par une les portes où se situent des packs d'orcs, la première porte s'est ouverte, les mobs ont été accueilli par un ouragan (droodéqui 80), ensuite la seconde porte aurait dû s'ouvrir, nous avons attendu un peu mais en vain, toutes les portes étant fermées, nous avons donc dû faire appel à un mj (Amandil), afin de nous permettre d'accéder à la suite du donjon.

**Comportement attendu**
Nous aurions dû avoir les portes qui auraient dû s'ouvrir les unes après les autres, nous permettant ainsi de pouvoir continuer le donjon sans avoir à faire appel à un mj.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/2aa32d3beb3340370be71020bf99110c5bb7a484
