### ISSUE TITLE
Guerrier ne peut pas renvoyer le piège givrant/flèche givrante

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#420]
**Description**
Le renvoi de sort du guerrier ne renvoie pas le piège givrant/flèche givrante du hunt

**Étapes de reproduction**
Prenez un guerrier et un chasseur, posez une flèche givrante, utilisez le renvoi de sort du guerrier et prenez le piège. Observez.

**Comportement attendu**
Le renvoi de sort du guerrier consomme le piège (renvoi de sort disparaît et piège aussi)(le hunt bien sûr n'est pas glaçon).

**Captures d’écran / Vidéos**

**Ressources additionnelles**
https://db.rising-gods.de/?spell=23920&locale=2
https://db.rising-gods.de/?spell=60192&locale=2
https://fr.wowhead.com/spell=23920/renvoi-de-sort#english-comments (Important Note: Freezing Trap can be negated if you step over the trap while having Spell Reflection up.)

**Comment by joshwhedon** [comment]
A noter, ils disent bien qui ne peut annule, mais ne peut pas etre renvoye vers le chasseur. Je vais le scripter de cette facon aussi.
