### ISSUE TITLE
Bouclier de terre du chaman pas affecté par les talents/glyphes

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#421]
**Description**
Il semble que le bouclier de terre du rsham ne soit pas 100% optimal sur les talents/glyphes/etc (scaling % des talents)

**Étapes de reproduction**
Un rsham avec bouclier de terre, tapez le.

**Comportement attendu**
Le bouclier de terre est censé rendre plus de vie.

**Ressources additionnelles**
https://wowgaming.altervista.org/aowow/?spell=49284
https://wotlkdb.com/?spell=16213
https://wotlk-twinhead.twinstar.cz/?item=45775
https://wotlk-twinhead.twinstar.cz/?spell=51881
https://www.youtube.com/watch?v=1P2qIWOQ__M (1525 proc bouclier de terre sous MS 50% non crit)
https://www.noelshack.com/2020-15-7-1586708987-avec-talents-et-glyphe-totem-spell.jpg (woe 1070 sous ms 50%)
https://media.discordapp.net/attachments/632722539528847361/698932629910585384/Sans_talents_avec_glyphe.png?width=1118&height=626 (woe sans talents, avec la glyphe 897).

**Comment by joshwhedon** [comment]
Nope, j'ai teste avec un perso tout nu sans talent : 337, avec talent (mais pas celui qui boost les heals du bouclier), 370, avec un peu de spell healing power 467 (juste un casque), avec le talent qui boost les heals du bouclier 503. Avec le glyphe 585 (pour le glyphe j'ai du reappliquer le bouclier pour que ca prenne effet).

**Comment by Gungaar** [comment]
Pourquoi ce bugreport a été fermé alors qu'il y a des preuves que le bouclier de terre est complétement bug???

**Comment by joshwhedon** [comment]
J'ai fait les calculs, et je les ai indique dans les commentaires. Tout est pris en compte actuellement, healing power, talents, glyphes. A moins que vous ne montriez les calculs qui montrent que bouclier de terre est "completement bug", la avec les donnees que j'ai niveau calculs, tout est pris en compte.

**Comment by Gungaar** [comment]
Au vu du précédent commentaires, il manque le talent en amélio qui augmente de 15% le bouclier de terre et il faudrait tester peut-être avec le gear complet.

Dans tous les cas, actuellement le bouclier de terre soigne 40% de moins que ce qu'il devrait. (avec 3100 de healing power, il devrait soigner dans les 3300-3400 non crit)

**Comment by joshwhedon** [comment]
Le bouclier de terre fait 337 de heal de base (c'est a dire sans rien du tout applique).
Il a un ratio de spellpower de 0.4762.
J'ai un perso avec 933 de bonus de heal (j'ai utilise le stuff de recup), ca fait donc 444 de heal en plus. Donc total 791
![image](https://user-images.githubusercontent.com/543699/79120410-2ecece80-7dd6-11ea-8f1f-ff3af99e3153.png)
Maintenant avec talents et glyphe (20% et 10%) plus les autres talents en tout genre, je monte a 1201, ce qui correspond, a la valeur attendue.
![image](https://user-images.githubusercontent.com/543699/79120684-d6e49780-7dd6-11ea-8613-95510239c2ea.png)
Ensuite avec 3100 de healing power, ca fait 1476 de bonus heal, donc de base, 1476 + 337 = 1813. Talent + glyphe, plus on va dire 10% de heal de talents divers et varries, on arrive a environ 2500, loin des 3400.
Maintenant, si vous faites les calculs a partir de ces informations et que vous trouvez des valeurs differentes, merci de fournir les talents qui ne fonctionnent pas d'apres vous.

**Comment by Justforsoloq** [comment]
Fin sur offi on a une preuve vidéo couleur sur couleur qu'on a des procs à 1500 de heals sous MS càd 3000 sans MS.
Et même dans le cas du 2500 on en est pas là, comme à dit gungar il en est à 2140 donc il reste quand même 400 de diff déjà avec la supposition du 2500, et encore plus avec la vidéo offi (même avec des variances de spell power plutôt haute, ce qui n'est pas le cas vu le stuff du rsham de la vidéo, il doit tourner aux alentours de 3K1-3K2 max healing power)

**Comment by joshwhedon** [comment]
Bah ... je vous ai donne les formules, faites les tests avec les formules que j'ai donne. Si vous trouvez des valeurs differentes en 3.3.5 pour le coefficient de sort, fournissez les sources, je changerai. Les 337 de base c'est les donnees client donc, correct par definition.

**Comment by joshwhedon** [comment]
"Donc oui c'est chiant de trouver d'où ça vient, (un peu la flemme des calculs, faudrait que des rshams avec du temps se penchent dessus) mais le soucis est visible néanmoins"
Et oui, et moi je peux pas passer 3 heures sur chaque sort qui "bug". J'ai deja passe plus d'une heure sur celui la a verifier les donnees et a effectuer les tests, pour confirmer que ca marche comme c'est supposer, je peux pas faire que ca.

**Comment by Gungaar** [comment]
Ok, je vais le calcul pour 3100 de spell :

337+(3100*0.4762)=1813.22

Ensuite, on ajoute la glyphe et les 3 talents pour un total de 55% en plus :

1813.22*55%=2'810.491

C'est pas tout à fait blizzlike mais c'est déjà mieux que ce qu'on a là.

**Comment by joshwhedon** [comment]
Non.

**Comment by joshwhedon** [comment]
JE vous ai donne les screens juste avant avec le ratio de spellpower. Soit dit en passant, c'est pas toujours additif les valeurs. Ensuite, je sais pas d'ou vous sortiez 55%. Ils viennent d'ou les 15 %?

**Comment by Gungaar** [comment]
boucliers améliorés en amélioration 2éme ligne tout à droite.

**Comment by joshwhedon** [comment]
En gros ce que je veux dire niveau calculs, c'est plus proche de : 1813 * 1.2 * 1.1 * 1.1 * 1.05 etc. Pas additif.

**Comment by Justforsoloq** [comment]
ça serait plus 1.15 que 1.05 non ?
Et si on fait 1813 * 1.2 * 1.1 * 1.1 * 1.15 on a  3027,3044
Sinon 1813 * 1.2 * 1.1 * 1.1 * 1.05 on a 2764
Très très très loin des 2140 atm (sans ms)

**Comment by Gungaar** [comment]
Ah bah c'est ce qui me manquait pour arriver au calcul juste :

1813.22*1.2*1.1*1.1*1.15=3027.715

**Comment by joshwhedon** [comment]
Je regarderai demain ... trop tard ce soir.

**Comment by Ischjgt** [comment]
https://woehead.way-of-elendil.fr/?item=45775 marche pas chez moi

**Comment by joshwhedon** [comment]
Le probleme est du a un soucis d'rodre dans l'application des bonus. Pour etre 100% honnete, je ne suis pas sur du comportement normal pour ce sort. En gros, les 15% et 20% sont appliques, d'apres les donnees client, non pas au total (heal de base + bonus sort), mais a l'heal de base uniquement. Est-ce un bug ou pas ? Je suis pas 100% sur (c'est les donnees client donc on devrait pouvoir leur faire confiance).
Du coup le calcul est actuellement:
(370 * 1.15 * 1.20 + spellpowerbonus) * 1.1 .* ...
Je change l'ordre pour que ca devienne
(370 + spellpowerbonus) * 1.15 * 1.20 * 1.1 .* ...
Mais je suis toujours pas convaincu que ce fix soit correct (vu que je suis oblige de changer les donnees client pour ca, c'est douteux).

**Comment by Gungaar** [comment]
Même avec le calcul actuel j'arrive pas à ce que se passe en live. Avec le calcul actuel ça me donne 2'273 de soin sur le live ça me heal que de 2'000, très bizarre.

M'enfin ça ira déjà mieux avec le nouveau calcul.

**Comment by Justforsoloq** [comment]
Il semble qu'il y ait une régression de nouveau sur le bouclier de terre.
(1k-1k1 de nouveau sous MS)

**Comment by joshwhedon** [comment]
Je viens de tester et avec un stuff basique je me prends du 2k

**Comment by Justforsoloq** [comment]
J'ferais des tests aujourd'hui, j'avais juste remonté ce qu'un rsham m'a dit (d'où mon il semble, j'étais pas sûr)

**Comment by Justforsoloq** [comment]
Alors il semble qu'il y ait quelques soucis :
1) Hors arène le bouclier de terre semble normal sur le rsham
2) Si le rsham le pose sur un coep war, déjà premier soucis le bouclier de terre tick à 2000 (pour 2700 sur le chaman), alors que ça devrait le heal du même montant.
