### ISSUE TITLE
Ulduar 10 - Léviathan HM : Apparition massive et progressive d'adds liés à la Tour verte

### ISSUE THREAD

**Issue by ChellGlidewell** [way-of-elendil/3.3.5#422]
**Description**
Sur le premier boss d'Ulduar, Léviathan, en mode HM (Avec les 4 tours d'activées), des adds apparaissent massivement (les adds liés à la Tour verte)

**Étapes de reproduction**
- Raid Ulduar
- 10 joueurs, boss en mode héroïque
- Léviathan
- Problème lié à la tour verte
- Composition du groupe : Adamajoana (Mage) ; Yakikaru et Walistik (Druide) ; Liraë (Guerrier) ; Theron et Chell (Paladin) ; Aliura et Aylinn (Chaman) ; Djun (Chasseur)

**Comportement attendu**
- Les adds sont censés apparaître par groupe de 10 à 15 environ 

**Captures d’écran / Vidéos**
- [Screenshot avec les adds](https://cdn.discordapp.com/attachments/488586498942173194/698975567822848050/unknown.png)

**Ressources additionnelles**
https://www.youtube.com/watch?v=JvraP9VCkyk me paraît appropriée comme modèle...

**Comment by Endalaust** [comment]
Lié au crashlog fourni sur slack et/ou discord
Actuellement le PNJ a été passé en p2 pour éviter de lancer le hard mode => 
creature Lore Keeper of Norgannon(37)
