### ISSUE TITLE
Quest: reconnaissance des puisards

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#423]
**Description**
11684 - [Reconnaissance des puisards]  [active]
11713 - [Reconnaissance des puisards] 
34920 - [Carte des champs de Geysers] 

Les objectifs ne se valident que si l'ont est en hauteur (ce qui est normalement impossible)

**Comment by Killyana** [comment]
Il faut se tenir aux bords des puisard pas dedans.
