### ISSUE TITLE
Quête : Rédemption (Tirion Fordring - Maleterres de l'Est)

### ISSUE THREAD

**Issue by Celdelbore** [way-of-elendil/3.3.5#424]
**Description**
La quête consiste à écouter ce qu'a à nous dire Tirion Fordring. Or, lorsqu'on lance la quête, il ne se passe rien. Tirion ne parle pas, même si on attend longtemps.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Tout à l'ouest des Maleterres de l'Est
- Faction : Alliance Classe : Paladin Race : Draenei
- Nom de la quête : Rédemption
- Nom du donneur de quête : Tirion Fordring

**Comportement attendu**
Tirion est sensé parler.

**Comment by Ischjgt** [comment]
Hello, il faut s'asseoir pour pouvoir écouter Tirion parler, bon jeu.

**Comment by Celdelbore** [comment]
C'est ce que j'ai fait, j'ai attendu 5min, mais aucun effet. 


![image](https://user-images.githubusercontent.com/63410621/79132049-e4cff380-7da9-11ea-8f9e-ff86627eda61.png)
