### ISSUE TITLE
[Démo]Consommation de fragment d'âme sous décimation.

### ISSUE THREAD

**Issue by Letwoll** [way-of-elendil/3.3.5#425]
**Description**
Si lors d'un combat, je fais proc le bonus Décimation (Démono) Et que je switche sur un autre mob puis que je spamme le spell, je perdrais des cristaux si le mob dispose de plus de 35%

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Démo
- UD
- Démono
- Feu de l'âme / Décimation / Etc
- Réalisé sur Saurcroc : switche sur les bêtes, ce qui fait proc le buff Décimer qui permet de faire des feux de l'âme gratuitement. Switch sur Saurcroc, spam du feu de l'âme tant que le buff est actif, perte des fragments. pas de perte du buff.
- Equipement
- Décimation

**Comportement attendu**
Je suis censé pouvoir faire un feu de l'âme sans perdre de fragment d'âme. 

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=63158

**Comment by Letwoll** [comment]
Le problème survient essentiellement si on commence le cast avant que le buff disparaisse et qu'il disparait pendant le cast

**Comment by joshwhedon** [comment]
Pas un bug que je sache, la consommation d'energie / mana / reagents / etc se fait au moment ou le sort est lance sur la cible (pas au moment ou il est incante), de ce fait, les effets qui influent sur ca sont calcule au moment ou le sort est lance sur la cible. Jusqu'a preuve du contraire c'est le comportement normal. Merci de fournir des sources qui indiquent que ce n'est pas le cas.
