### ISSUE TITLE
Boss: Kel'Thuzad Naxxramas

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#427]
**Description**
Constaté en 10
Name: Kel'Thuzad
Entry: 15990.

Le groupe a vaincu le boss, il a ressuscité

Bonus: wow error quand j'ai voulu déco/reco dans le raid

Témoignage :
[] chuchote : "ah ne vous rejouissez pas, votre victoire est futile car je reviendrais avec des pouvoirs dépassant votre compréhension" [C'est sa dernière phrase avant que le soucis se produise]
[] chuchote : on le voyait comme une image remanante après le combat, non cliquable
[] chuchote : mais d abord mort, pas de corps puis au bout de qq seconde, reapparition non ciblable

**Comment by joshwhedon** [comment]
Pas pu reproduire, je retire la seule chose qui peut avoir ete responsable.
