### ISSUE TITLE
Ulduar 10 - Problème dans l'étendue du vérrouillage du raid

### ISSUE THREAD

**Issue by ChellGlidewell** [way-of-elendil/3.3.5#428]
**Description**
- Une ID d'un raid Uldu 10 a été partagée, et prolongée par la personne ayant reçu ce partage pour la semaine suivante
- Les mobs ET boss de l'instance sont malgré tout réapparus alors que l'instance de base avait été clean entièrement (réapparition le dimanche 12/04 pour une ID datant du dimanche 05/04 puis prolongée jusqu'au 16/04)

**Étapes de reproduction**
- Ulduar 10
- N'importe quel mode 
- Sur le screen Freya, mais tous les boss ont repop

**Comportement attendu**
Que les adds et bossent de réapparaissent pas malgré une prolongation d'ID

**Captures d’écran / Vidéos**
[Screen devant Freya, avec numéro d'ID et boss présent malgré tout](https://cdn.discordapp.com/attachments/649319559878410278/699004243691962390/unknown.png)

**Comment by Killyana** [comment]
Les 4 gardians vont toujours respawn (via respawn time) vue qu'ils ne sont pas vraiment considérés comme boss par le système du spawn.
La seule solution serait de mettre un respawn time max pour ces 4 boss

**Comment by joshwhedon** [comment]
Ca sera suffisant ? Ca va pas foirer les instance states ?

**Comment by Killyana** [comment]
je pense pas, ou on attende le rewrite des IDs, sa sera fixé

**Comment by joshwhedon** [comment]
On peut doubler les temps de respawn de ces 4 boss, c'est rapides et faible risque.

**Comment by Killyana** [comment]
oui

**Comment by Killyana** [comment]
J'ai mis 8 semaines
