### ISSUE TITLE
Mob: Scientifique de la peste

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#43]
**Description**
Serveur prod et test
- La canalisation du Flot de peste cible aussi les rats 
- Attention, la traduction du sort est mauvaise, le sort augmente les dégats infligés de 100% !

**Étapes de reproduction**
testé en 25hm,
Allez dire bonjour au scientifique de la peste à ICC, ils canaliseront Flot de peste sur les rats 

**Comportement attendu**
Osef des rats, ça doit cibler les potes du scientifique

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=69871

**Comment by joshwhedon** [comment]
@Killyana  Je me demande pour celui la, le smart script est code pour explicitement cibler les rats. C'est une erreur tu crois ou c'est fait expres ? Je trouve rien niveau infos indiquant que ca devrait se passer comme ca.

**Comment by Killyana** [comment]
Oui sa doit cibler les https://www.wowhead.com/npc=10404/pustulating-horror https://youtu.be/Dudz7fa52Bc?t=250

**Comment by Killyana** [comment]
Y'avait pas de target dans le cast IC du spell, c'est corrigé.
