### ISSUE TITLE
bug limon trognepus icc

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#430]
**Description**

sur trognepus le mt2 prend les limon et les fait stack jusqu'à l'explosion; En théorie ça devrait être ça :

1+1 petit limon (2stack)= 1 gros limons (2 stack) // 2 gros limons = (4stack) car 2x2 petit limon). 

Sauf qu'à l'heure actuel 1 gros limon + 1 gros limon revient à faire 1 +1 stack en gros le gros limon a la même valeur que 1 petit limon quand on les packs alors qu'il devrait faire 2 stack par gros limon en + ; ça simplifie grandement le down de ce boss

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: ICC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): all mode
- Boss: trognepus
- Sort en question / Phase du boss en question / Emplacement: trognepus
- Composition du groupe:

**Comportement attendu**

1+1 petit limon (2stack)= 1 gros limons (2 stack) // 2 gros limons = (4stack) car 2x2 petit limon). 

**Captures d’écran / Vidéos**

----: facile à reproduire

**Ressources additionnelles**

----

**Comment by Killyana** [comment]
J'ai vue ça durant les tests, aussi sur tc ils disent que c'est un bug blizzlike, mais sur wowpedia:
* Two small Oozes merge into a Big Ooze (size 1)
* A small and a Big Ooze merge into a Big Ooze with size one larger than the initial one
* Two Big Oozes merge into a Big Ooze with size one larger than the smaller of the two initial ones.
* A Big Ooze of size 5 explodes (see below)

**Comment by joshwhedon** [comment]
https://www.wowhead.com/npc=36627/rotface#article
The first two Small Oozes that merge will form a Big Ooze. Every next Ooze that merges with the big one will add a stack to its Unstable Ooze. When that stack reaches 5 (after the 6th ooze has spawned), the Big Ooze will freeze in place and cast Unstable Ooze Explosion. As soon as the cast is over, everybody should scatter to avoid the flying ooze missiles. Don't forget to avoid the ooze floods, and make sure to stack back in the middle as soon as you can.

Et sur wowpedia : Two Big Oozes merge into a Big Ooze with size one larger than the smaller of the two initial ones.

Donc ca a l'air normal d'apres les sources.
1 petit + 1 petit = 1 gros avec 2 stacks
1 gros + 1 petit = 1 gros avec 3 stacks
1 gros + 1 gros = 1 gros avec 3 stacks.
