### ISSUE TITLE
pic de roche noire supérieur 

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#431]
**Description**

après avoir tué le dragon glyth + le boss qui en descend chef de guerre rend main-noire; la grille dans la salle reste bloqué au lieu de s'ouvrir -> très gênant car c'est l'accès au raid BWL (repaire de l'aile noire) et ça bloque toute la progression

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: pic de roche noire supérieur
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc)
- Boss: chef de guerre rend main-noire
- Sort en question / Phase du boss en question / Emplacement
- Composition du groupe

**Comportement attendu**

la grille se déverrouille à la mort de ce boss.

**Captures d’écran / Vidéos**

----

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/213
Deja signale
