### ISSUE TITLE
bug rivage des anciens

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#432]
**Description**

salle des reliques attaqué; porte cassé (d'après mini map) mais présent en visuel (check screen)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement / Zone / Arène / Champ de bataille: rivage des ancien
- Faction / Race / Classe du personnage utilise: h2 / orc / cham

**Comportement attendu**

porte non présente si cassé

**Captures d’écran / Vidéos**

![Capture d'écran 2020-04-13 05 02 25](https://user-images.githubusercontent.com/63243193/79088872-4c535800-7d44-11ea-946b-9b2289a69189.png)

**Ressources additionnelles**

----

**Comment by joshwhedon** [comment]
Deja signale.
https://github.com/way-of-elendil/3.3.5/issues/359
Normalement vous pouvez meme passer a travers comme si de rien n'etait.
