### ISSUE TITLE
bwl bug dispel

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#434]
**Description**
sur chromaggus on a dispell et les magies dispell passe en buff avec ses effets indésirable et impossible à cancel avec un clic droit dessus (check screen)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: repaire de l'aile noire
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc)
- Boss: chromaggus
- Sort en question / Phase du boss en question / Emplacement
- Composition du groupe

**Comportement attendu**

si débuff dispell il NE doit pas aller dans les buffs et être in dispellable 

**Captures d’écran / Vidéos**

![Capture d'écran 2020-04-13 05 13 13](https://user-images.githubusercontent.com/63243193/79089193-8113df00-7d45-11ea-9618-3694d04fdb18.png)
@@@@@

**Ressources additionnelles**

----

**Comment by Killyana** [comment]
Corrigé avec la maj de demain.
