### ISSUE TITLE
[Les Champs du Chagrin] Ramassage impossible

### ISSUE THREAD

**Issue by aleksdevilseyes** [way-of-elendil/3.3.5#435]
Bonjour,

Il y a un problème avec la quête [Les Champs du Chagrin] à la Ferme des Solliden dans les Clairières de Tirisfal. Le ramassage des 10 potirons est impossible. L'objet est en surbrillance, mais lorsqu'on souhaite le ramasser, rien n'est comptabilisé. Le donneur de quête est le Nécrogarde Simmer à la sortie du Glas.

Merci,
Bonne journée !

**Comment by Killyana** [comment]
Il ne faut pas être dans un groupe de raid pour faire des quêtes.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/f9d117737998a6bdf560b02e9ca3f4a5ce4bfa2a
