### ISSUE TITLE
Butin: Responsable du butin

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#437]
**Description**
Testé 10 et 25
44577 - [Clé héroïque de l'iris de focalisation] 
44569 - [Clé de l'iris de focalisation] 
(et je pense que c'est pour tous les objets un peu pareil)

Ne loot pas si le butin est en "Responsable du butin"

Constaté pour les Têtes d'Onyxia également
https://woehead.way-of-elendil.fr/?item=49644
https://woehead.way-of-elendil.fr/?item=49643
https://woehead.way-of-elendil.fr/?item=18422
https://woehead.way-of-elendil.fr/?item=18423

**Comment by joshwhedon** [comment]
Et c'est un bug ?

**Comment by Killyana** [comment]
oui https://github.com/TrinityCore/TrinityCore/issues/24230
