### ISSUE TITLE
quête : Destin, contre votre volonté

### ISSUE THREAD

**Issue by Ulmenetha** [way-of-elendil/3.3.5#438]
**Description**
Jaina Portvaillant ne propose pas de dialogue alors que la quête dit de lui parler.

**Étapes de reproduction**
Prendre la quête Destin, contre votre volonté au Roi Varian Wrynn puis parler à Dame Jaina Portvaillant

**Comportement attendu**
J'ignore le résultat du dialogue avec Dame Jaina Portvaillant, mais il doit permettre la suite de la quête. 

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Killyana** [comment]
Fixé, prochaine maj
