### ISSUE TITLE
Spell: Vague de lumière

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#439]
**Description**
Surge of light 33150 Rank1
33154 Rank2

proc sur un crit de 
Reflective shield 33201 Rank1
33202 Rank2

**Comportement attendu**
Surge of Light is a priest talent that grants a [25/50%] chance when casting [Smite], [Heal], [Flash Heal], [Binding Heal] or [Greater Heal] to cause your next [Flash Heal] to be instant cast and cost no mana. 

https://wow.gamepedia.com/Surge_of_Light_(priest_talent)

**Comment by joshwhedon** [comment]
Pas trouve de sources, par contre les donnees client indiquent que le sort a le flag suivant
SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED
Ce flag indique generalement que les auras qui sont declenches par autre chose (par exemple dans le cas actuel un proc) peuvent declencher cette aura. Donc, jusqu'a preuve du contraire les donnees client font foi.
