### ISSUE TITLE
Spell: Projection du combobulateur

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#44]
**Description**
Serveur prod et test
Il est possible d'utiliser des objets comme les bottes fusées après avoir reçu la morph, CD activé, animation et buff sont là, mais la vitesse n'est pas augmentée

**Étapes de reproduction**
.aura 71103 et utilise les bottes fusées

**Comportement attendu**
Pas possible de les activer

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=71103

**Comment by joshwhedon** [comment]
Pourquoi ce serait pas possible de les utiliser ? Je comprends que la vitesse soit pas augmente, ce debuff est un debuff sur la vitesse donc les bottes sont annuelees

**Comment by Killyana** [comment]
C'est possible d'utiliser un item en étant : Pacify Silence ?

**Comment by joshwhedon** [comment]
Oui me semble.

**Comment by joshwhedon** [comment]
https://classic.wowhead.com/item=4381/minor-recombobulator#comments
You can't use it on yourself to dispel polymorph, but you can use it on yourself for the heal (but not while polymorphed). It's a nice additional way to self heal in a pinch beyond potions and bandages.

**Comment by joshwhedon** [comment]
Ha pas le bon objet.

**Comment by joshwhedon** [comment]
Ca a pas l'air d'etre un bug cela dit. C'est pas les memes effets que polymorph. Du coup j'ai cherche des sorts similaires (y'en a pas beaucoup). Il y a Dispersion pour pretre.
https://www.wowhead.com/spell=47585/dispersion#comments
I don't know if you guys know the "Potion of Nightmares". But with Dispersion this Potion is actually pretty useful (except the part, that you cannot move while using the Potion). So it's perfect in fights where you use a lot of mana and won't move too much (Patchwerk, KT, etc).

Donc en gros, tu peux utiliser des objets sous ce genre d'effet.
