### ISSUE TITLE
Difficulté quête de fin de Dk

### ISSUE THREAD

**Issue by karatoso** [way-of-elendil/3.3.5#441]
**Description**

Avec un ami, nous avons commencé à monter un dk, arrivé à la fin des quêtes dk, sur les Maleterres de l'ouest en déphasé, on a tenté de faire la quête de La bataille de la chapelle de la lumière.
On a tenté de la faire plusieurs fois jusqu'à se lasser, nous n'étions que 2, je reste persuadé que cette quête nécessite d'être bien plus nombreux. Nous mourrons toutes les 30 secs et la quête, à la fin, ne se valide pas...
Elle devient impossible à faire, et laisse nos dk en déphasé, inutilisables ...

- Emplacement
Maleterres de L'Ouest
- Faction / Race / Classe du personnage utilise
Un gnome (Herkjall) et un humain (Marmont)
- Nom de la quête
La lumière de l'aube
- Nom du donneur de quête
Commandant du fléau Thalanor 

Doit on gagner cette bataille ? comment fait-on si l'on n'est que 2 joueurs à la faire ?
à la fin de la bataille, la victoire est tout le temps pour le camp ally, avec un blocage, pas de suite, pas de remarque sur la quête sur un éventuel échec. Le pnj ally reste fixe, pas d'apparition du Roi Liche...

Merci à toute l'équipe pour la joie que vous apportez aux joueurs de ce serveur !

**Comment by joshwhedon** [comment]
Deja signale, corrige prochaine maj

**Comment by karatoso** [comment]
Merci beaucoup !
