### ISSUE TITLE
[Suite de quête] Vaelen l'Ecorché

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#442]
**Description**
Lors de la prise du caveau des Ombres, [Vaelen](https://woehead.way-of-elendil.fr/?npc=30218#ends) est déjà présent à l'intérieur et propose la quête [Vaelen est de retour](https://woehead.way-of-elendil.fr/?quest=13085). 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Couronne de glace - Caveau des Ombres/Valhalas
- Draenei Prêtre
- Nom de la quête
- Vaelen l'Ecorché (normalement d'abord ici : https://woehead.way-of-elendil.fr/?npc=30056#starts ; puis là : https://woehead.way-of-elendil.fr/?npc=30218#ends)

**Comportement attendu**
Une fois le caveau des Ombres repris, [Vaelen](https://woehead.way-of-elendil.fr/?npc=30218#ends) n'est pas présent. Il faut accomplir la quête [Le décret du caveau des Ombres
](https://woehead.way-of-elendil.fr/?quest=12943) pour ensuite pouvoir lancer la suite permettant de le libérer ( [Récupérer la clé](https://woehead.way-of-elendil.fr/?quest=12949) ), le faisant apparaitre dans le caveau et lançant la suite de quête commençant par [Vaelen est de retour](https://woehead.way-of-elendil.fr/?quest=13085).

**Comment by Killyana** [comment]
Fixé prochaine maj.
