### ISSUE TITLE
Toucher vampirique mauvais coeff spell power

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#443]
**Description**
Le coefficient spell power de la VT est de 320% actuellement au lieu de 120%

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Spell_power_coefficient
[Vampiric Touch] (Dispelled) | 120% | Patch 3.2.0

Le coeff spellpower qui a été utilisé pour le 320% vient de https://github.com/TrinityCore/TrinityCore/issues/21393, d'une discussion caduque où quelqu'un utilise l'UA pour appliquer sa logique sur l'UA à la logique de la VT. (ce qui d'une n'a aucun sens et de deux n'est pas non plus correct, puisque le spell coeff du dispell UA est le bon).

**Comment by joshwhedon** [comment]
2 choses : ils ne se basent pas sur l'UA ils se basent sur les donnees clients, qui indiquent que le dispel toucher vampirique fait 8 fois le tick (tout comme les donnees client indiquent que le dispel de l'affliction instable fait 9 fois le tick). 
Ensuite, faire ce changement signifie que en gros, il n'y a plus aucune raison de ne pas dispel le toucher vampirique, vu qu'au final le dispel fera 40% de degats de moins que si tu le dispell pas. En gros ca retire tout l'interet du truc non ?

**Comment by Justforsoloq** [comment]
Ils se basent sur les données clients d'accord pour le 8x le tick. Mais pour le coeff spell power ils se basent sur l'UA qui a 180% de spellcoef (ils font un raccourci en se disant 9x 20%=180%) et ils appliquent donc cette donnée à la VT (8x40%=320%), alors que noir sur blanc dans les coefs, le dispell vt est noté à 120% de coef (comme l'UA est noté à 180%). 

Et le dispell VT n'est pas comme l'UA un "prevent dispell" à tout prix (et encore l'UA c'est plus le côté silence qui gène que les damage brut). C'est plus le fait de se prendre en un dispell gcd 5-8k (pour un priest stuff selon la rési du joueur en face) quand tu es mid-life/low life et que le sp n'a qu'à reposer sa vt derrière. 
https://www.mmo-champion.com/threads/675834-jesus-christ-shadow-pvp-is-gimped-as-hell/page4 (après patch 3.2, donc le damage vt a été doublé)
"We need better dispell protection and possibly more damage on VT, imo.
And if you're focusing a healer, even in full PvE gear in battlegrounds, they just ignore the damage, dispell it and carry on healing. They also dispell mind trauma which is our healing debuff gone..

**Comment by joshwhedon** [comment]
"Et le dispell VT n'est pas comme l'UA un "prevent dispell" à tout prix (et encore l'UA c'est plus le côté silence qui gène que les damage brut). C'est plus le fait de se prendre en un dispell gcd 5-8k (pour un priest stuff selon la rési du joueur en face) quand tu es mid-life/low life et que le sp n'a qu'à reposer sa vt derrière." Ca a pas de sens ce que tu dis. L'UA aussi tu la repose apres, l'UA aussi tu te prends un dispell gc a plus de 5-8k. Et encore le toucher vampirique y'a pas de silence derriere.
En gros ... c'est un dispell qui sert a que dalle une fois qu'on reduit les degats. 
Bref j'ai pas que ca a faire de discuter un seul sort, le changement sera mis prochaine maj.

**Comment by Justforsoloq** [comment]
Enfin trouvé une vidéo avec un dispell VT bien pris sur offi s8
https://www.warcraftmovies.com/movieview.php?id=164387
21mn37-21m40 dispell VT à 5K467 (crit ? le chiffre est en gros jaune) (et ça montre aussi pourquoi même si le dispell VT fait pas 12k faut pas le dispell des fois)

**Comment by joshwhedon** [comment]
Merci
