### ISSUE TITLE
Quest: Gothik le Moissonneur

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#444]
**Description**
https://woehead.way-of-elendil.fr/?quest=12697
Il y a d'autres prérequis nécessaires à la réalisation de cette quête ?
J'ai croisé 2 joueurs qui étaient bloqués alors qu'ils avaient les 4 quêtes en prérequis rewarded
(et moi aussi)

**Comment by Killyana** [comment]
il faut aussi faire https://woehead.way-of-elendil.fr/?quest=12711
woehead n'est pas à jour
