### ISSUE TITLE
Mort à Andorhal (Maleterres de l'ouest) - fantôme envoyé à Colline des sentinelles (Marches de l'ouest)

### ISSUE THREAD

**Issue by Celdelbore** [way-of-elendil/3.3.5#445]
**Description**
Tout est dans le titre. Morte à Andorhal (Maleterres de l'ouest), mon fantôme à été envoyé à Colline des sentinelles (Marches de l'ouest). 
Nous étions deux et nous avons eu tous les deux le même souci.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe / Spécialisation : Paladin Vindicte Draenei et Paladin vindicte Humain
- Maleterres de l'ouest
- Décès
- Rez au mauvais endroit

**Comportement attendu**
Le fantôme devrait être envoyé au cimetière le plus proche aux Maleterres de l'ouest, et non aux Marches de l'ouest.

**Comment by Killyana** [comment]
Bug très rare qui se produit parfois, impossible de savoir pourquoi.

**Comment by Celdelbore** [comment]
Avec 2 joueurs différents et deux fois de suite... Etonnant ! ^^ 
Merci pour la réponse.

**Comment by joshwhedon** [comment]
C'etait dans une zone specifique d'Andhoral ?

**Comment by Killyana** [comment]
Même bug que https://github.com/way-of-elendil/3.3.5/issues/455
c'est corrigé après le reboot:
Map: 0 (Royaumes de l'est) Zone: 28 (Maleterres de l'ouest) Area: 193 (Ruines d'Andorhal) Phase: 1
