### ISSUE TITLE
Quete : Le colosse de fer 

### ISSUE THREAD

**Issue by nicogarion** [way-of-elendil/3.3.5#446]
Bonjour,
Lorsque l'on sélectionne un Jormungar, il n'y a qu'un seul sort qui apparait et il est impossible d'attaquer le colosse avec.
Merci par avance,
Cordialement

**Comment by joshwhedon** [comment]
Deja signale. Corrige prochaine mise a jour.
https://github.com/way-of-elendil/3.3.5/issues/196

**Comment by Aloawan** [comment]
Depuis le dernier reboot les attaques du jormungar fonctionnent à nouveau mais sont loin d'être assez puissantes pour qu'un joueur seul puisse en venir à bout, le colosse attaque immédiatement dès qu'on émerge et cogne bien trop fort. 
Il faut signaler en plus qu'une fois que l'on a enfoui le jormungar sous terre les commandes pour se déplacer ne fonctionnent plus correctement et quand on émerge on est immobilisé.

**Comment by joshwhedon** [comment]
C'est normal, vous etes pas suppose pouvoir bouger quand vous emergez, c'est le but du systeme submerge / emerge. Quand aux degats des attaques, ce sont les degats de l'officiel. JE crois que la strategie c'est de mettre le poison et ensuite de se submerger pendant qu'il fait des degats, et de recommencer jusqu'a le tuer.

**Comment by Aloawan** [comment]
Ok mais quand on remonte le colosse tape tellement fort que les dégâts du poison ne compensent pas. Après peut-être que je m'y prends mal.

**Comment by joshwhedon** [comment]
Je vais voir les degats et les changer si necessaire

**Comment by Killyana** [comment]
Il faut éviter les dégâts en passant sous terre.

**Comment by Killyana** [comment]
La gestion des spells n'est 100% blizzilke.
Quand le joueur monte dans le jormungar il ne doit pas pouvoir bouger et ces spells doivent être dispo:

![image](https://user-images.githubusercontent.com/6587064/79235569-127d7100-7e6c-11ea-901b-2961fff62df2.png)

Pour pouvoir bouger il doit cliquer sur immersion "1er spell" pour passer sous terre, et la, la barre des sorts change:
![image](https://user-images.githubusercontent.com/6587064/79235809-60927480-7e6c-11ea-880b-143324aecceb.png)

En étant sous terre le joueur peut bouger mais seulement le spell "émerger" doit être visible

**Comment by joshwhedon** [comment]
Les spells je peux pas les changer, on a pas 2 templates de creature different donc je peux pas utiliser la technique habituelle. Sinon oui je l'empeche de bouger au spawn,
