### ISSUE TITLE
Bug porte dans la salle du cerveau de Yogg Saron

### ISSUE THREAD

**Issue by Shendraxqt** [way-of-elendil/3.3.5#449]
**Description**
Dans la p2 sur yogg saron, un groupe de joueur doit aller dans le cerveau de yogg pour le tuer, a ce moment la, les joueurs sont téléportés dans une salle sur 3 au hasard. l'une de ces salles (chambres des aspects, apparence du temple du repos du ver) ne fonctionne pas :
on tue tout les adds de la salle, on a le message du jeu comme quoi la porte vers le cerveau a été ouverte, mais elle reste fermée. ce qui entraine que tout le groupe du cerveau (8 personnes) se font mind controle, et au final cela cause un wype du raid.

**Étapes de reproduction**
- Ulduar 25 joueur (4 keepers)
- p2, salle du temple du repos du ver

**Comportement attendu**
la porte vers le cerveau dois s'ouvrir quand tout les adds de la salle sont morts

**Comment by joshwhedon** [comment]
Par chance vous vous souvenez si c'etait la premiere fois que vous alliez dans une des salles ? Et possiblement est-ce qu'il se pourrait que vous ayez ete envoye 2 fois dans la meme salle ?

**Comment by Limoustique** [comment]
Non Josh, on a eu le même problème, il s'agissait de notre premier passage en bas dans les deux trys qu'on a fait.

**Comment by joshwhedon** [comment]
Et toujours cette salle la ?

**Comment by Limoustique** [comment]
Pour notre groupe oui, mais nous n'en avons pas testé d'autres.
