### ISSUE TITLE
Quête: Le test de droiture (1654)

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#45]
**Description**
testé serveur prod
Abandonner la quête après avoir trouvé les 4 objets, ces derniers sont delete (narmol). 
Une fois cette quête reprise, j'ai pas trouvé comment récupérer une nouvelle fois la gemme purifiée de Kor et la cargaison de minerai raffiné

**Étapes de reproduction**
- .q a/c/rew 1651, 1652 et 1653 
- .q a 1654
- .q a/c/rew 1655 et 1442
- Delete les 2 items de quête/Abandonner et reprendre la quête 1654 
- Impossible de récuperer la gemme et la cargaison de nouveau

**Comportement attendu**
J'ai pas trouvé :(

**Comment by Killyana** [comment]
https://woehead.way-of-elendil.fr/?quest=1655 et https://woehead.way-of-elendil.fr/?quest=1442 doivent être répétable

**Comment by Killyana** [comment]
Fixé prochaine merge.
