### ISSUE TITLE
Spell: Listing Buffs/Debuffs

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#451]
**Description**
Comme prévu depuis ce matin certains buffs et débuffs ont été inversé, j'aimerais pouvoir faire un listing détaillé de ce qui devrait retourner à sa place, je sais pas si c'est utile, c'est en attendant que Josh se réveille

Débuff à la place de buff : 
59620 - [Berserk, rank 1 frFR]
605 [Contrôle mental] (Sur le joueur qui lance le spell)

Buff à la place de débuff :
63050 - [Santé mentale, rank 1 frFR] (https://www.youtube.com/watch?v=iatGk4TOlEA)

J'éditerai la liste ici au fur et à mesure, une réaction sur votre commentaire signifie qu'il a été mis à jour sur ce post

**Comment by Justforsoloq** [comment]
https://github.com/way-of-elendil/3.3.5/issues/440
^

**Comment by gtschanz** [comment]
debuff de chromaggus à bwl + les slow qui passe en buff si le pala use sa main de liberté (je sais pas si les 2 ont été corrigé; mais c'est ceux que j'avais relevé)

**Comment by Sthanks** [comment]
Explosion Morbide --- Dégâts un peu faible

**Comment by Ischjgt** [comment]
Tu peux m'expliquer plus en détail pour Chromaggus stp.
Pour le pal c'est corrigé, et je crois que c'est du à cette correction le soucis

**Comment by joshwhedon** [comment]
Ces soucis devraient etre corriges prochaine mise a jour. Merci de signaler si des sorts ne le sont pas.
