### ISSUE TITLE
BG: Vallée d'Alterac

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#453]
**Description**
1. Possible d'activer/désactiver le marqueur JcJ dans le BG
2. Arrivée après le lancement, le compte des renforts n'est pas là

**Comment by joshwhedon** [comment]
Tu as toujours pu l'activer / desactiver, mais ca n'a pas d'effet. Il y avait un bug avec le flag pvp mais normalement j'ai passe un correctif.
Pour le compte de renforts je l'ai en arrivant apres moi.
