### ISSUE TITLE
Bug du taux de critique des dots du démo affli

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#454]
Sur un raid je me suis rendu compte que en affli, le taux de critique du trait de l'ombre est supérieur au taux de crit de la corruption. Hors, ceci est impossible compte tenu du talent Imprécation (+9% au crit de la corruption) et n'est jamais arrivé avant la merge (observé en raid sur absolument tous les combats).

Testé avec Démo affli 28,2% de crit affiché dans les stats sur un mannequin :
Avec le 2t10 (+5% de crit) : 33% de crit après 150 itérations
Avec le 2t10 + 9% crit du talent Imprécation + 5% de crit du talent Trait de l'ombre amélioré : 27% de crit après 150 itérations.

Après de nombreux autres test :
Il me semble assez clair que le talent Imprécation n'est pas pris en compte dans le crit de la corruption.
Pour ce qui est du 2t10 il semblerait qu'il soit pris en compte (pas sûr du tout).
Pour le talent Trait de l'ombre amélioré, je n'ai pas eu de résultat significatif, mais il semblerait qu'il n'est pas pris en compte non plus (notamment certains tests où le taux de crit baissait de 5% sur 200 itérations avec l'application de ce talent, et de forte disparité selon si la corruption est posé avant ou après l'application du talent, ce qui ne devrait pas être le cas).

Ps : exactement le même problème avec Affliction instable, et au total un manque d'environ 20% de crit sur les deux sorts qui font le plus de dégats.
(j'ai les screens des recounts test si jamais)

**Comment by toitit** [comment]
Après plus de test dans la configuration suivante : sur mannequin avec 300 itérations de corruption (oui c'est long x)).
Démo affli, 37,94% de crit, +5% 2t10, +9% talent Imprécation.

Test 1 : Corruption posé AVANT l'application du talent Trait de l'ombre amélioré :
Résultat : 40,9% de crit.

Test 2 : Corruption posé APRES l'application du talent Trait de l'ombre amélioré :
Résultat : 44,7% de crit.

Confirme bien le problème général du taux de crit (ne prend ni Imprécation ni 2t10 à mon avis)

Et confirme que le calcul des débuff en crit de la cible n'est pas refresh quand la corruption est refresh par le talent Affliction éternelle. (source : https://www.wowhead.com/forums&topic=162195 dernier commentaire)

**Comment by Ischjgt** [comment]
En fait, les dots prennent le taux de critique que tu possèdes au lancement du spell, refresh le spell si le dot est encore sur la cible ne remet pas à jour le taux de critique à jour.

**Comment by toitit** [comment]
Déjà, merci de lire avant de fermer le ticket.... Comme expliqué, au lancement du spell j'ai + de 52% de crit, et après 300 itérations, seulement 40% dans les test (talent et 2t10 ne sont pas pris en compte, d'où le bug).
Ensuite (autre bug), les DEBUFF de la cible en terme de pourcentage de dégâts et de pourcentage de crit doivent être remis à jour comme expliqué dans le lien. Je parle bien des DEBUFF de la cible et non de mes propres buffs, qui eux ne sont pas mis à jour on est d'accord. Et actuellement, ce n'est pas remis à jour sur le serveur

**Comment by Ischjgt** [comment]
Bon, je réouvre dans le doute, c'était pas trop ça quand j'ai test 32484 - [Imprécation, rank 3 frFR]   avec 70839 - [Item - Warlock T10 2P Bonus, rank 1 frFR] 
Une fois le 2T10 enlevé tout à eu l'air de rentrer dans l'ordre
Je réessayerai demain si c'est pas encore solutionné.
Et oui 1000 excuses j'ai (très) mal lu ton ticket

**Comment by joshwhedon** [comment]
"Ensuite (autre bug), les DEBUFF de la cible en terme de pourcentage de dégâts et de pourcentage de crit doivent être remis à jour comme expliqué dans le lien. Je parle bien des DEBUFF de la cible et non de mes propres buffs, qui eux ne sont pas mis à jour on est d'accord. Et actuellement, ce n'est pas remis à jour sur le serveur"
Ils sont definitivement mis a jour. Ils sont recalcule a chaque tick meme. Si vous posez un dot sur une cible, et que la cible recoit un buff de reduction de degats, les degats du dot seront reduits.

**Comment by joshwhedon** [comment]
Et de meme, le taux de critique, a wotlk, est recalcule a chaque tick (c'est une des seules stats qui influe sur les degats qui est recalculee a chaque tick). Apres est-ce que le taux de critique est correct, je sais pas je jeterai un oeil si j'ai le temps.

**Comment by toitit** [comment]
> Et de meme, le taux de critique, a wotlk, est recalcule a chaque tick (c'est une des seules stats qui influe sur les degats qui est recalculee a chaque tick).
Tu parles du taux de crit du lanceur de sorts ou des modificateurs de crit sur la cible ?

**Comment by joshwhedon** [comment]
Bah, techniquement les deux a wotlk. A chaque tick, le dot va regarder si il est critique ou pas (base sur le lanceur de sorts et la cible).
Ca a change a cata par contre si je me souviens bien. A Cata le taux de critique du lanceur de sort est cacule au cast, et dure pour la duration du dot.

**Comment by toitit** [comment]
Sauf erreur de ma part et comme expliqué dans ce lien https://www.wowhead.com/forums&topic=162195 (et sur tous les guides de "dot rolling") le dot garde le taux de crit du lanceur de sorts qu'il a au moment du cast

**Comment by joshwhedon** [comment]
Oui pardon, le taux de crit aussi, j'avais mal lu. J'ai aussi verifie le code et c'est bon.

**Comment by Ischjgt** [comment]
Salut, je suis en train de faire des premiers tests, désolé c'est un poil long
Sans talent qui up le crit, sans T10, j'ai 41.91% de cc des sorts, je devrais avoir pareil sur les ticks corruption et sur les traits de l'ombre
J'ai tapé sur un mannequin 80

Trait de l'ombre
1. Hit 240 (57%) (Min: 2398 Moy: 2670 Max: 3512)
2. Crit 181 (43%) (Min: 3408 Moy: 3920 Max: 5268)
=> ~+2%, ça me semble correct
Corruption (DoT)
1 Tick 215 (62%) (Min: 1052 Moy: 1132 Max: 1546)
2. Crit 133 (38%) (Min: 1772 Moy: 2316 Max: 3092)
~ -4/5% (il arrondit le recount >:( c'était plus que 4)

Enfait déjà de base je pense qu'il y a un soucis mais continuons
J'ajoute juste le 9% de crit sur la corruption, je garde les memes stats et la meme cible, on devrait donc avoir 51.91% corrupt et 41.91% trait de l'ombre

Trait de l'ombre
1. Hit 238 (59%) (Min: 2355 Moy: 2726 Max: 3617)
2. Crit 163 (41%) (Min: 3703 Moy: 4061 Max: 5424)
=> On notera la justesse du trait de l'ombre à chaque fois

Corruption (DoT)
1. Tick 203 (58%) (Min: 942 Moy: 1163 Max: 1592)
2. Crit 147 (42%) (Min: 1837 Moy: 2372 Max: 3184)
On perd maintenant 9-10%
Je saurais même pas te dire d'où ça peut venir vu que le problème était déjà de base, mettre le talent l'a juste accentué.
Je vous tiens au jus prochainement pour le 2T10 et le trait de l'ombre amélioré
