### ISSUE TITLE
Instance: Salles des foudres

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#455]
**Description** .gps
Sur woe: 
Map: 602 (Les salles de Foudre) Zone: 0 ( <unknown> ) Area: 0 ( <unknown> ) Phase: 1 ?
En locale:
Map: 602 (Les salles de Foudre) Zone: 4272 (Les salles de Foudre) Area: 4272 (Les salles de Foudre) Phase: 1

Dans tout le donjon sur woe sa retourne Zone: 0 ( <unknown> ) Area: 0 ( <unknown> ) 

Ceci cause qu'une fois les joueurs morts et libèrent il vont se trouver aux Tarides pour la horde et Westfall pour l'alliance

Je ne sais pas si c'est une map corrompu ou un truc du genre.

**Comment by joshwhedon** [comment]
Je viens de tester sur woe, et moi j'ai bien la bonne zone / area.

**Comment by Killyana** [comment]
C'est fixé
