### ISSUE TITLE
[Sort] Renvoi de sort n'est pas retire apres un renvoi

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#456]
**Description**
La cisaille des vents n'enlève pas le renvoi des sorts du guerrier

**Étapes de reproduction**
Prenez un chaman et un guerrier, faites renvoi de sort en guerrier, utilisez cisaille de vent et regardez.

**Comportement attendu**
La cisaille de vent enlève le renvoi de sort du guerrier

**Ressources additionnelles**
https://db.rising-gods.de/?spell=23920&locale=2
https://wotlk-twinhead.twinstar.cz/?spell=57994

**Comment by joshwhedon** [comment]
Donc il est pas renvoye ? Ou il passe a travers ?

**Comment by Justforsoloq** [comment]
J'aurais du mieux précisé, il est noté comme renvoyé mais n'enlève pas le renvoi de sort

**Comment by joshwhedon** [comment]
Ok merci.

**Comment by joshwhedon** [comment]
C'est nouveau ? Ca marchait avant ?

**Comment by Sthanks** [comment]
Nan le bug c'est pour tout les sorts .. c'est le renvois qui reste 5s et il renvois tout

**Comment by joshwhedon** [comment]
Ouai j'ai remarque apres la question :D . J'essaie de corriger ca pour la prochaine maj, ou celle d'apres selon mon temps disponible aujourd'hui.

**Comment by Sthanks** [comment]
Ty cool ! :)

**Comment by joshwhedon** [comment]
OK c'est ma faute avec le fix sur les renvois de sorts de pieges. Corrige prochaine maj
