### ISSUE TITLE
Item: Certificat de reconnaissance

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#46]
**Description**
Serveur prod 
Il faut actuellement 99 certificats pour obtenir le constructrobot (au lieu de 40 comme indiqué sur la description)

**Étapes de reproduction**
- .add 45924 40
- clic droit sur les certificats, message d'erreur
- .add 45924 59
- (y'en a donc 99), On obtient le pet

**Comportement attendu**
Il faut 40 certificats pour obtenir le familier

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?item=45924

**Comment by Killyana** [comment]
Je pense pas que c'est possible de changer le nombre des Reagents via SpellMgr

**Comment by joshwhedon** [comment]
Corrige prochaine maj
