### ISSUE TITLE
Instance: Profondeurs de Rochenoire

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#460]
**Description**
Ces NPCs là étaient en combat avec les joueurs du groupe après qu'ils aient vaincus 9938 - [Magmus] , ce sont des statues qui crachent des flammes, ils ne doivent pas etre en interaction avec les joueurs

Name: Ironhand Guardian
SpawnID: 47474, current GUID low: 1194.
Entry: 8982.

Name: Ironhand Guardian
SpawnID: 47473, current GUID low: 1228.
Entry: 8982.

Name: Ironhand Guardian
SpawnID: 47472, current GUID low: 1201.
Entry: 8982.

**Comment by joshwhedon** [comment]
Meme probleme de bug combat que https://github.com/way-of-elendil/3.3.5/issues/319, sera regle en meme temps.

**Comment by Ischjgt** [comment]
**Étapes pour reproduire**
- .go c id 9938
- engager le combat
=> Pet passif, tout est normal
=> Pet defensif/Aggressif, les IronHand Guardian qui infligent des dégats aux pets passent en combat avec celui ci
