### ISSUE TITLE
Boss: Ice Tomb Sindragosa

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#461]
**Description**
Name: Ice Tomb
Entry: 36980.

Il est possible de passer à travers un tombeau de glace à l'aide d'une charge, la charge menant le joueur à l'épicentre du tombeau.

**Comportement attendu**
Les joueurs ne peuvent pas le traverser les contours du tombeau le bloque

**Comment by joshwhedon** [comment]
Des preuves que c'est pas possible ?

**Comment by Ischjgt** [comment]
5:05 https://www.youtube.com/watch?v=WOd-dMJQKkI
la charge arrive à l'extremité du tombeau

**Comment by joshwhedon** [comment]
Merci

**Comment by joshwhedon** [comment]
C'est totalement aleatoire en fait, 90% du temps ca va tres bien, et une fois de temps en temps, le chemin foire et trouve rien a cote, du coup envoi le joueur directement sur le mob. On y peut pas grand chose c'est les mmaps, et c'est pas specifique a ce mob, ca le fait avec tout (joueurs, mobs, etc)
