### ISSUE TITLE
Quest: J'ai une machine volante !

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#462]
**Description**
11390 - [J'ai une machine volante !]  

Name: Steel Gate Flying Machine
Entry: 24418.

Impossible de déposer les sacs de reliques sur la plateforme

**Comportement attendu**
C'est censé se faire tout seul en arrivant à la plateforme 
https://youtu.be/qjMMvnVo1XE

**Comment by Killyana** [comment]
Fixé prochaine maj
