### ISSUE TITLE
Quest: Un déluge de feu sur Skettis

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#463]
**Description**
11008 - [Un déluge de feu sur Skettis] 
1. Après avoir utilisé 32406 - [Détonateur de la Garde-ciel]  sur des 185549 - [Œuf de kaliri monstrueux]  (seulement quand ça marche en gros); le joueur se retrouve dismount. 
2. 185549 - [Œuf de kaliri monstrueux]  despawn pas, on peut faire la quête sur le même gob

**Comment by Killyana** [comment]
J'ai corrigé tout les problèmes à part le dismount qui est causé par: Effet #1 | Activate Object : (8)
Pour être sure que sa vient de la, il suffit de cliquer sur les œufs en mode GM ON pour les despawn, puis utilisé l'item de la quête sur les npc_triggers en étant sur la monture volante, la y'aura pas de dismount.

@joshwhedon possible de regarder ça?

**Comment by joshwhedon** [comment]
Y'a un flag sur les goobers pour ca :)
UPDATE `world_335_merge`.`gameobject_template` SET `Data17` = '1' WHERE `gameobject_template`.`entry` = 185549;
