### ISSUE TITLE
Talent Impureté DK IMPIE

### ISSUE THREAD

**Issue by Sthanks** [way-of-elendil/3.3.5#464]
**Description**
Le talent impureté bug sur la gargouille elle prend pas en compte les 20% de PA 

https://www.mmo-champion.com/threads/684585-Unholy-DK-talent-Impurity

--- the coefficient on the gargolye's damage is 40% (or 50% with 5/5 impurity) of the DK's AP, which could be as high as 2500 per hit buffed... DK's death coil has the exact same coefficient

**Comment by Sthanks** [comment]
+ Test sur poto  (Pour les dégâts)
https://www.wowhead.com/forums&topic=133584

**Comment by joshwhedon** [comment]
Merci j'ai trouve d'autres sources qui confirment aussi, je corrige pour demain.

**Comment by joshwhedon** [comment]
Soit dit en passant c'est pas comme ca que ca marche niveau calcul, Impurete n'augmente pas la quantite de puissance d'attaque recu par la goule, ca augmente la proportion de la puissance d
attaque de la goule utilisee pour le calcul de degats.

**Comment by Justforsoloq** [comment]
Josh par contre addendum, ce que voulait report Sthanksc'est pour la gargouille (vu que tu citais la goule dans ton message je ne sais pas si c'est juste une erreur de typo que tu as fait Josh) dont les dégâts ne sont pas up par le talent impureté

**Comment by joshwhedon** [comment]
Oui pardon je voulais dire las gargouille. J'ai fait la modif pour la gargouille.
