### ISSUE TITLE
Terrasse des Magistères

### ISSUE THREAD

**Issue by Flocapa** [way-of-elendil/3.3.5#466]
Le 3 eme boss du mode héro avec ses adds est bug, les adds reset constament, impossible de le tuer et de continuer.

**Comment by joshwhedon** [comment]
J'ai tente de reproduire de mon cote, pas reussi. Vous pouvez me donner plus de details ? Un add particulier qui reset ?

**Comment by joshwhedon** [comment]
On parle bien de la pretresse et de ses sbires d'ailleurs ?

**Comment by Endalaust** [comment]
On parle bien de ce boss
Je suis intervenu une seule fois sur ce donjon, le PNJ de type voleur était inattaquable et les autres tués. C'est visiblement différent du cas reporté

**Comment by Flocapa** [comment]
C'est bien ce boss, en gros, certains adds sont pack dès le debut, je penses qu'il s'agit de ceux là qui reset (de mémoire il y a le voleur et la démo peut-être plus) on peux tuer le boss et les autre adds si on les pull à distance mais la porte derrière ne s'ouvre pas, et les adds restant lorsqu'ils sont pull, font repop tout les autres dont le boss

**Comment by Flocapa** [comment]
On peux techniquement attaquer ces adds mais qu'on soit loin ou au cac, ils font quelques pas puis reset

**Comment by joshwhedon** [comment]
Merci pour les precisions. Je pense avoir un correctif pour :).

**Comment by Amilgaull** [comment]
Nouveau soucis pour ce boss, si la prêtresse est tuée avant de wipe. La prêtresse repop mais fait également repop ses 4 sbires en plus de ceux déjà présent.

**Comment by joshwhedon** [comment]
Je mets un correctif demain.
