### ISSUE TITLE
Professeur Putricide Limon vert 25Hm

### ISSUE THREAD

**Issue by Welcombak** [way-of-elendil/3.3.5#467]
**Description*
Le limon vert: Au passage de la transi ou hors transi le limon vert target une personne (ce qui est normal)si la target meurt pour X raison le limon regéne facilement 30% puis le le limon retarget une personne mais n'explose pas au contact de celle ci ( Ce qui n’est pas normal)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Citadelle de la couronne de glace
- 25 mode Héroïque
- Professeur Putricide
- Transi/phase normal 
- Composition du groupe

**Comportement attendu**
Le comportement attendu pour limon Vert est que lorsque il tue sa target il n'y pas de regene possible ainsi quand il arrive a la nouvelle target le bump doit être pris en compte dans le raid 

**Captures d’écran / Vidéos**
https://clips.twitch.tv/FrozenFinePeafowlLeeroyJenkins 
( Limon regene +no bump hors transi)

https://www.twitch.tv/krunkks/clip/DignifiedTriangularSowPlanking
( Limon vert regene en plein transi apres la mort du Target)

Merci bon jeu a vous

**Comment by Subimase** [comment]
Bonjour, 

Tu as aussi remarqué le déplacement des limons ? Ils ont un déplacement rectiligne et non pas curviligne. En gros, le limon se déplace d'un point A puis B puis C. Il ne va pas d'un point A à C directement selon le déplacement du personnage (si c'est un rouge, déplacement libre ; si c'est un vert, un TP mage ou TP démo est possible). Les deux limons ne prennent pas la trajectoire la plus "évidente", la "plus rapide" pour arriver sur leur cible.

Dans l'ancienne version de WoE, les limons avaient le bon comportement.

Egalement, as-tu remarqué qu'il arrivait que le limon rouge target une personne, puis réinitialisation de son sort de target. En 10H hier, il nous l'a fait à chaque pop. En gros, un personnage A est ciblé. Le limon ne commence pas sa course. Il réinitialise son target pour cibler réellement un joueur. On gagne facilement 5 secondes de dps en plus sur sa tête. 

Nous avons également relevé d'autres bugs : 
- le mage a Iceblock sur le target du limon vert. Cette attitude a figé le débuff période de target du limon vert de manière infini ; 
- le vert, arrivé à destination, n'active pas son sort lorsqu'il touche sa cible. On le voit bien sur tes vidéos. Parfois, il continue juste de target, il arrive à destination mais n'explose pas (fréquence : 1/5 fois).

Cordialement,

Subimase

**Comment by joshwhedon** [comment]
Je mets un correctif demain, dites moi si il y a encore des soucis.

**Comment by Subimase** [comment]
Bug que je n'ai plus revu sur la regen du limon vert. 

Sur les déplacements du limon rouge (https://fr.wowhead.com/npc=37562/nuage-de-gaz), à vérifier (ça n'a pas paru trop déconnant hier soir). Je verrai ça vendredi soir. Si on devait prendre un comparatif du boss Ick (https://fr.wowhead.com/npc=36476/ick#abilities) à la fosse de saron : quand il suit sa cible (avec Poursuite : https://fr.wowhead.com/spell=68987/poursuite), les déplacements sont corrects. Il suit sa cible de la manière la plus efficiente possible. 

Par contre, le limon rouge (https://fr.wowhead.com/npc=37562/nuage-de-gaz) a encore quelques difficultés pour target. Hier soir, quand il pop, il cast son sort de target, puis le réinit (https://fr.wowhead.com/spell=70215/ballonnement-gazeux). Il l'a fait deux fois de suite. 
Alors, j'ai cru comprendre qu'il le fait notamment lorsque le chassou est sous dissuasion et les mages en ice block. L'ICE BLOCK sous l'ancienne merge faisait bug le limon vert (il atteignait sa cible, le target en continu, sans pour autant explosé). 

Subimase

**Comment by joshwhedon** [comment]
Merci.
