### ISSUE TITLE
Boss: Professeur Putricide

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#47]
**Description**
Serveur prod :
Quand le prof lance ses flaques de gelées et ses gelées malléables, il reste immobile jusqu'à que celles-ci aient atteint leur destination.

N.B. : J'émet l'hypothèse que cela vient d'abord des spells, le problème est le même sur Ick de la guilde des bastonneurs (je crois que c'est son blase)

Serveur test :
Le comportement du boss semble être legerement différent, on dirait qu'il revient sur ses pas à ce moment là 

**Étapes de reproduction**
- ICC n'impporte quelle difficulté pour les flaques de gelées, HM pour les malléables
- minimum 2 personnes pour les malléables
- Dès la P1 pour les flaques de gelées, P2 pour les malléables 
- Le tank du boss bouge, lorsqu'un des 2 spells utilisés, le boss reste à sa place le temps que les projectiles aient atteint le sol.

**Comportement attendu**
Le boss doit continuer à suivre le tank

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=70346
https://woehead.way-of-elendil.fr/?spell=70853
https://woehead.way-of-elendil.fr/?spell=72295

https://www.youtube.com/watch?v=7fioPGCDpHM

**Comment by joshwhedon** [comment]
A premiere vue ca a ete regle.
