### ISSUE TITLE
La dame des tigres

### ISSUE THREAD

**Issue by Unlfberht** [way-of-elendil/3.3.5#470]
Lorsque la matriarche des tigres est sur le point de tomber à 0 PV elle est supposée se transformer en troll en nous parler. Au lieu de ça elle se volatilise et l'objectif ne se valide pas. J'ai tenté à plusieurs reprises d'abandonner et de relancer la quête mais le problème persiste.

**Comment by Killyana** [comment]
Script name: npc_tiger_matriarch
