### ISSUE TITLE
Impossible de ramasser le bois/métal ( quête : Je travaille .. pour la horde

### ISSUE THREAD

**Issue by Fianso26** [way-of-elendil/3.3.5#471]
Il est impossible de ramasser le bois / métal demandé pour finir la quête Je travaille ... pour la horde,
J'ai réussi à en ramasser 3/8 et 2/8 mais il ne m'est plus possible d'en loot

Zone : Péninsule des flammes infernale
Classe : Dk orc h2
Quête : Je travaille .. Pour la horde
Donneur : Megzeg Phalangette

**Comment by joshwhedon** [comment]
Tu serai pas dans un groupe de raid par hasard ?

**Comment by Fianso26** [comment]
Négatif, je vois les items, qui brillent .. mais impossible de faire quelconque  action dessus, je suis co ingame : Bestfdpeu

**Comment by Killyana** [comment]
Il faut ramasser les objets sur la coté de l'alliance si t'es hordeu et inversement.
