### ISSUE TITLE
Bataille pour Fossoyeuse

### ISSUE THREAD

**Issue by Mugiino** [way-of-elendil/3.3.5#473]
**Description**
Quand on rend la quête "Une vie sans regrets" à Vol'jin dans la zone de fossoyeuse phasé, ça nous déphase immédiatement pour nous remettre dans la phase de base de fossoyeuse, ce qui rend donc tout l’événement de la bataille de fossoyeuse infaisable (on ne peut même pas prendre la quête suivante).

**Étapes de reproduction**
Faire toute la suite de quête débutant au marteau d'Agmar jusqu'à la quête "Une vie sans regrets", puis la rendre à Vol'jin dans la zone phasée de Fossoyeuse.
**Comportement attendu**
Le joueur ne devrait psa être déphasé, et Vol'jin devrait proposer la quête suivante, qui lance l'événement de la bataille de Fossoyeuse.

**Comment by joshwhedon** [comment]
Si tu quitte la zone et y retourne, l'event devrait etre disponible. LE probleme est deja regle pour la prochaine mise a jour
