### ISSUE TITLE
ICC - Svalna - Crok n'avance plus et le combat ne se lance pas

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#474]
**Description**
Il est toujours possible de se trouver en position de blocage

![image](https://user-images.githubusercontent.com/6587064/79341274-d1e52c80-7f2b-11ea-8c90-e82ba72bafd9.png)

Je ne sais pas pourquoi les pnjs sont revenus au position de départ, mais à ce niveau passer sur les areas trigger ne fait rien

**Comment by Endalaust** [comment]
Je complète en disant que si on passe Svalna en offensive (mod fac 14) sur ce cas de figure, les PNJs engagent instantanément le combat et viennent combattrent Svalna.

Problème majeur, nécessite une intervention manuelle d'un maître de jeu plusieurs fois par jour.

**Comment by joshwhedon** [comment]
Bah a moins de trouver comment reproduire, ce sera pas corrige.

**Comment by Killyana** [comment]
J'ai mod fac Svalna et les pnjs ont aggro seulement une fois Svalna en combat.

**Comment by joshwhedon** [comment]
Normal Svalna a un script qui fait que les pnjs vont l'agro quand elle entre en combat.

**Comment by Freyahh** [comment]
J'apporte ici les ressources WoE Head et WoW Head de chaque PNJ, à savoir Svalna, Crok et les 4 capitaines qui accompagnent Crok, pour aider à la correction du bug :

- Ressources additionnelles

PNJ "Sœur Svalna"
- WoE Head : https://woehead.way-of-elendil.fr/?npc=37126
- WoW Head : https://fr.wowhead.com/npc=37126

PNJ "Crok Plaie-du-Fléau"
- WoE Head : https://woehead.way-of-elendil.fr/?npc=37129
- WoW Head : https://fr.wowhead.com/npc=37129

PNJ "Capitaine Arnath"
- WoE Head : https://woehead.way-of-elendil.fr/?npc=37122
- WoW Head : https://fr.wowhead.com/npc=37122

PNJ "Capitaine Brandon"
- WoE Head : https://woehead.way-of-elendil.fr/?npc=37123
- WoW Head : https://fr.wowhead.com/npc=37123

PNJ "Capitaine Grondel"
- WoE Head : https://woehead.way-of-elendil.fr/?npc=37124
- WoW Head : https://fr.wowhead.com/npc=37124

PNJ "Capitaine Rupert"
- WoE Head : https://woehead.way-of-elendil.fr/?npc=37125
- WoW Head : https://fr.wowhead.com/npc=37125

**Comment by joshwhedon** [comment]
Merci Freya, malheureusement c'est pas le genre d'information qu'il me faut. Ce qu'il me faut c'est un moyen de reproduire le probleme :(

**Comment by Freyahh** [comment]
> Merci Freya, malheureusement c'est pas le genre d'information qu'il me faut. Ce qu'il me faut c'est un moyen de reproduire le probleme :(

Arf je vois :-S Du coup, j'en ai aucune idée ^^

**Comment by joshwhedon** [comment]
Pas de soucis :) . Merci tout de meme de l'aide :)

**Comment by Ischjgt** [comment]
<img width="1007" alt="Capture d’écran 2020-06-11 à 23 24 20" src="https://user-images.githubusercontent.com/60295792/84440829-f95e2a00-ac3a-11ea-9134-17ccbf4d74f5.png">

Il manque le 37122 sur le screen, c'était comme ça quand je suis arrivé, tout le monde est revenu et passé sur le trigger n'a rien fait.

[X] chuchote : Crok a subit l'aggro des essences disjointes
J'arrive à peu près à les mettre dans cette configuration là avec l'aggro des valk'yrs, mais chez moi ils repartent quand meme (j'ai pas réussi à faire en sorte qu'un capitaine meurt d'une Val'kyr/essence, tout seul c'est pas facile)

Quand j'ai .mod fac la soeur, Croc s'est mit à parler
> Crok Plaie-du-Fléau crie : Je vais l'occuper. Renvoyez nos frères à leurs tombes, puis venez m'aider à la terrasser !

**Comment by Ysya555** [comment]
@Traesh  
![image](https://user-images.githubusercontent.com/77018709/152451584-8bcb3ba9-4b3a-4dc8-813f-1ba63e07b9d3.png)

**Comment by Ferro-woe** [comment]
Peut-être que cela sera utile :
Sister Svalna https://wowpedia.fandom.com/wiki/Sister_Svalna
Sister Svalna rewrited (russe) https://www.youtube.com/watch?v=4cNtREls3CQ

**Comment by Endalaust** [comment]
Pour info @Sungis18 histoire de retrouver l'historique d'échange et les apports divers sur ce sujet
