### ISSUE TITLE
Elementaire de feu supérieur 

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#475]
**Description**
L'élementaire de feu ne fait pas assez de dégâts (et de dps). Actuellement il fait environ 800-900 dps et 80-90k damage

**Comportement attendu**
Il fait environ 10% du dps du chaman elem quand consumé entièrement et a un dps d'environ 1k9-2k4 selon les boss et prepot magie etc. 

**Ressources additionnelles**
https://github.com/TrinityCore/TrinityCore/issues/16011
http://www.worldoflogs.com/reports/r990jgnfr802ixrw/sum/damageDone/?s=2160&e=2327 (saurcroc 25h method 08/07/2010 :
Gatina sham elem, elem de feu sup :                                    
Fire Elemental Totem | 266938 | 0.58% |   | 2293.1 | 1588.9 | 116.4s | 69.5%))

**Comment by joshwhedon** [comment]
Il va me falloir plus d'information que ca. L'elementaire est deja scripte pour prendre en consideration les stats du shaman pour ses degats. A moins de fournir les donnees necessaire au scaling, c'est a dire le % de chaque stat donc il doit heriter, il restera tell qu'il est maintenant.

**Comment by joshwhedon** [comment]
Ouai j'ai verifie les seul truc qui manquent c''est le bonus des sorts qui est celui par defaut, donc si je le mets ca va boost certains sorts et en nerf d'autres.

**Comment by Justforsoloq** [comment]
Fin on voit bien qu'il y a un soucis x)
Entre 800 de dps (j'peux fournir screen down saurcroc) et 2K2 t'as un petit gap

**Comment by joshwhedon** [comment]
\o/ Savoir qu'il y a un soucis aide pas a savoir ou il est :D .
Soit dit en passant, les liens fourni sur l'issue, ils marchent pour toi ? Pour moi ils marchent pas donc je peux pas verifier les sources.

**Comment by Justforsoloq** [comment]
Et oui je me doute ^^, faudra que je fasse des calculs mais il y a un assez gros soucis quelque part. J'imagine ça vient des coups blancs qui scale mal.
Euh nop mais c'les seuls stats de l'elem de feu que j'ai trouvé donc j'ai posé ça :(

**Comment by Justforsoloq** [comment]
Et vous n'avez pas moyen de vérifier les stats de l'ancienne machine de l'elem de feu ? Car sur l'ancien core il était correct

**Comment by joshwhedon** [comment]
L'ancien core etait definitivement pas correct, vu qu'on a remis toutes les stats de l'ancien core pour ces pets la recemment :) . 90% des bugs de pets qui ont ete signale sont des bugs existants.

**Comment by Justforsoloq** [comment]
Sur l'ancien core mon elem de feu faisait 200k-205k damage (sur un fight optimisé) soit 9-10% de mon dps, ça semble bien plus proche des logs offi, donc l'ancien core qu'il soit correct ou non s'approchait déjà plus de retail qu'actuellement.

**Comment by joshwhedon** [comment]
J'ai trouve l'origine du soucis. Les pets qui ont des attaques de melees elementaire utilisent plus le bonus du proprietaire. Je sais pas quels autres pets ca affecte mais je corrige de facon generale.
Soit dit en passant, l'ancien core l'elementaire avait aucun bonus pour ses sorts (nova, etc), je corrige ca en meme temps.

**Comment by joshwhedon** [comment]
T'as pas trouve des infos sur l'elementaire de terre par hasard ?

**Comment by Justforsoloq** [comment]
J'ai pas cherché, mais si tu veux je peux m'y mettre (je sais juste qu'il n'était pas utilisé hors pour avoir une reprise d'aggro si un tank mourrait en dj le temps d'un rb)

**Comment by Justforsoloq** [comment]
https://wowwiki.fandom.com/wiki/Earth_Elemental_Totem
Wrath-Logo-Small Patch 3.1.0 (14-Apr-2009): The summoned Earth Elemental should now have significantly more health and slightly more armor. Now scales up in power based on the shaman's spell power instead of attack power. (par contre pour le "plus de vie et plus d'armure" faut que je cherche les stats)

**Comment by joshwhedon** [comment]
Ouai j'ai vu ca aussi, malheureusement ca aide pas des masses, parce que j'ai vu aucune source indiquant les bonus.

**Comment by Justforsoloq** [comment]
J'suis en train de chercher en ce moment ^^

**Comment by joshwhedon** [comment]
Merci.

**Comment by Justforsoloq** [comment]
Legion Patch 7.1.5 (2017-01-10):

    Now has 400% of the caster's armor (was 200%).
    Now has 25% the caster's spell power as attack power (was 5%), and 45% for Primal version.
    Creates a great deal of threat to nearby enemies.
    Now has a duration of 1 minute (was 15 seconds) and a cooldown of 5 minutes (was 2 minutes). 
J'imagine que le "was" concerne wotlk, vu qu'il n'y a pas de référence avant. Mais pas 100% sûr vu que c'est le totem qui a "remplacé" le totem d'elem de pierre

**Comment by joshwhedon** [comment]
Bah, spell power as attack power ... on peut pas aller bien plus bas que 5% de toute facon :D .

**Comment by joshwhedon** [comment]
Un soucis aussi c'est que l'elementaire de terre est plus du tout le meme actuellement, c'est meme plus un totem.

**Comment by joshwhedon** [comment]
"Earth elementals deal physical damage, but as with any earth elemental, they are immune to all Nature spells and effects." C'est le cas actuellement ?

**Comment by Justforsoloq** [comment]
Pas encore testé, il faut que j'aille faire un duel pour voir ça
Par contre les deux elems ont un soucis au niveau de leur hp (les deux ont 8000 hp), ils sont censés avoir un % de la vie du chaman (plus pour l'elem de terre j'imagine), il faut que je trouve le %

**Comment by joshwhedon** [comment]
Me demande aussi si l'elementaire de feu est immunise au feu sur woe

**Comment by Justforsoloq** [comment]
Je vais testé en duel pour les deux dès que j'ai fini de manger.
L'elem de feu a plus de 14K5 pv en tout cas j'ai des logs sur sindra où il se prend un 14K6 de sindra et ne meurt pas. Par contre l'elem de terre pour le trouver quelque part x))))

**Comment by Justforsoloq** [comment]
L'elem de feu est bien immunisé aux sorts de feu (testé contre un mage feu en duel)

**Comment by Justforsoloq** [comment]
Bc icon Patch 2.1.0 (22-May-2007): This pet will now come into the game with full health and mana, including that gained from a percentage of its master’s stamina and intellect. It will also now properly get increased stamina from a percentage of its master’s stamina.
Wrath-Logo-Small Patch 3.1.0 (14-Apr-2009): The summoned Fire Elemental should now have moderately more health and mana
Mais je trouve pas de source en %. :(

**Comment by Justforsoloq** [comment]
L'elem de terre est bien immune aux spells de nature

**Comment by joshwhedon** [comment]
Bon rien pu trouver sur les stats nulle part. J'aime pas mais on sait que elementaire de feu et de terre se basent sur la stamina, et de terre sur l'armure du casteur. Base sur les infos que j'ai, les esprits feraux (les loups) prennent respectivement 35% de l'armure et 30% de la stamina. Je vais appliquer la meme chose. Si on trouve plus precis je corrigerai.

**Comment by Justforsoloq** [comment]
Yep j'continue de chercher en attendant mais c'vraiment dur de trouver des pistes sur la stamina/armor des elems.

**Comment by Justforsoloq** [comment]
/!\ Sur certain boss (dame murmemort que j'ai pu observé) l'elem de feu ne va pas au cac du boss et reste bloqué à une certaine distance en spammant ses sorts (qui ne touche pas forcément d'ailleurs). Il devrait toujours aller au corps à corps en range de mélée

**Comment by joshwhedon** [comment]
Il est loin ? Il a une distance maximum de son totem.

**Comment by Justforsoloq** [comment]
Non proche, mais j'ai l'impression dans les marches ça buggait, si je le pop au dessus des marches pas de soucis.
Et actuellement il fait trop de dégats (1.5x-2x trop) 4k+ dps au lieu de 2-2K4 dps (500k dmg au lieu de 260k environ)

**Comment by joshwhedon** [comment]
:( . Je lui ai mis les stats indiquees. C'est les attaques de melee qui font trop mal ou les sorts ? Avant la merge les sorts avaient pas de bonus du tout.

**Comment by Justforsoloq** [comment]
Faut que je test sur poteau histoire de voir, en raid tu peux pas voir le detail exact des attaques de l'elem de feu sauf via ptet un skada (j'ai recount)

**Comment by Justforsoloq** [comment]
J'pense les coups blancs font trop de dégats (à tester, mais au lieu d'être en average de 4-5k ils sont plus de l'ordre du 7k)

**Comment by Justforsoloq** [comment]
Ouais les sorts sont ok, c'est les mélées qui font 1.5-2x trop de dégats

**Comment by Justforsoloq** [comment]
Yep actuellement après calcul les mélées sur mes tests devraient faire 2282.8 (2283 arrondi) sur poteau, elles font du 3K5+

**Comment by joshwhedon** [comment]
Toujours ? Pourtant j'ai grandement reduit ...
En plus tu as dit :
J'pense les coups blancs font trop de dégats (à tester, mais au lieu d'être en average de 4-5k ils sont plus de l'ordre du 7k)

**Comment by Justforsoloq** [comment]
Ah non j'ai pas testé aujourd'hui

**Comment by Justforsoloq** [comment]
Attends je vais faire les tests

**Comment by joshwhedon** [comment]
Ha ok pas de soucis. J'ai mis des modifs aujourd'hui, en touchant un peu les formules.

**Comment by Justforsoloq** [comment]
Ok ça a l'air bien mieux, je testerais en raid mercredi/jeudi prochain mais là il frappe du 2-2K2 ce qui d'après mes calculs hors raid est normal (il semble avoir encore peut être un peu trop peu de vie, 12k, mais c'est pas forcément une prio tant que je trouve pas un log où l'elem de feu meurt instant et qui pourrait me donner un chiffre exact sur les HP, ou une formule)

**Comment by joshwhedon** [comment]
Niveau vie, j'ai assume le meme calcul que pour les autres pets du meme genre qui eux ont des donnees, c'est a dire 0,3 * stamina du proprietaire. Ca va etre dur de trouver des infos sur ca oui :( .

**Comment by Justforsoloq** [comment]
Après l'elem de feu a une vie de base d'après ce que j'ai trouvé donc peut être qu'il faut faire vie de base + 0,3* stamina proprio 
Level: 1 - 80
React: A H
Stats:
Health: 42 - 5,342  (lvl 1-80)
Armor: 15 - 9,729  (lvl1-80)

**Comment by joshwhedon** [comment]
C'est ce qu'on a actuallement, vie de base + 10 * stamina. Stamina = stamina de base + 0.3 * stamina du proprio.

**Comment by Justforsoloq** [comment]
D'accord, et bien je vais laisser tomber pour le moment, qui sait peut être qu'une solution arrivera à la surface un jour

**Comment by joshwhedon** [comment]
Pas de soucis. Merci pour ton aide :)
