### ISSUE TITLE
Tranche de dégat du dk sang

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#476]
**Description**
La tranche de dégâts à bcp baisser avec la merge, plus de 200 pt, je pense que des talents ne sont pas pris en compte, à vérifier pourquoi cette baisse de dégâts.
**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe : DK
- Race : Orc
- Spécialisation : Sang
- spé : https://wotlkdb.com/?talent#jfVRVh0Icfof0stZfzhhxc:LIGM0V
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement : full 277/284
- Aucun buff sauf le 10% PA passif du dk avec la présence de sang

**Comportement attendu**
J'aimerai comprendre pourquoi la tranche de dmg à baissé, si c'est un bug de non prise en compte de certain talent ect...

**Captures d’écran / Vidéos**
Après la merge : 
![Apres merge](https://user-images.githubusercontent.com/63306323/79356453-470e2d00-7f3f-11ea-86a0-9f78ca30448f.PNG)
Avant la merge :
![stats DK sang (cape hate)](https://user-images.githubusercontent.com/63306323/79356456-47a6c380-7f3f-11ea-8a6e-8da00edbd2d7.PNG)

(Le gemmage et un peu différent du screen après merge d'ou la diff de stat en force/pa).

**Comment by Killyana** [comment]
Ça s'appel un debug, les dégâts des cac étaient trop élevé avant la merge.

**Comment by joshwhedon** [comment]
A premiere vue, les degats sont corrects. Avant la mise a jour les degats des melees etaient trop eleves (a cause de divers problemes, dont les valeurs des equipements qui ne changeaient pas correctement au changement d'equipement).
Si vous faites des tests et trouvez une stat specifique qui pose probleme, merci de fournir les informations, mais dans l'immediat, il s'agit d'un debug plutot que d'un bug.
