### ISSUE TITLE
NPC: Seigneur de feu

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#477]
**Description**
Name: Firelord
Entry: 11668.
Name: Lava Spawn
Entry: 12265.

Les Lava Spawn continuent de spawn même quand le Firelord est mort, il faut que toutes les Lava Spawn soient tuées pour que les invocations s'arrêtent

**Comportement attendu**
Firelord mort = les invocations s'arretent

**Comment by Killyana** [comment]
Blizzlike https://fr.wowhead.com/npc=11668/seigneur-du-feu#comments:id=130137
