### ISSUE TITLE
Quêtes "Les avantages de la science marginal" et "Équipés pour la révolte" Bug

### ISSUE THREAD

**Issue by jeremkid** [way-of-elendil/3.3.5#478]
**Description**
Les deux quetes nous demande de tuer des troupes dans un bombardier.Mais dans les deux quete  impossibe de tirer sur les "Gargouille embusquée".

Sur la quete "Équipés pour la révolte"
On ne peux n'y tirer sur les" Gargouille embusquée"et on ne vous a aucun moment les"Factionnaire couvegivre " donc impossible de les tuer si on ne les vois pas pendant le trajet.

**Étapes de reproduction**

- La Couronne de glace
- H2 /Paladin palret 80/Hikigam
- https://fr.wowhead.com/quest=13374/%C3%A9quip%C3%A9s-pour-la-r%C3%A9volte
-https://fr.wowhead.com/quest=13373/les-avantages-de-la-science-marginale

Merci a vous.

**Comment by joshwhedon** [comment]
Quand tu monte dans la tourelle et utilise les attaques anti aeriennes ca marche pas contre les gargouilles ?
@Killyana  certains spawns ont l'air de manquer pour ces quetes, tu les aurai pas quelque part par chance ?

**Comment by jeremkid** [comment]
Non quand je monte dans les tourelle et que je leur tire dessus ca  fair rien du tout et a la fin quand elle parte il y a marquer rater mais rien de plus impossible de les toucher.

**Comment by Killyana** [comment]
Spawn ajouté en phase 4 https://github.com/TrinityCore/TrinityCore/commit/7b48580296cddc6c64c7fcb0dae2a1e23d6ec833
Phasing à faire

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/567
