### ISSUE TITLE
Repaire de l'Aile noire 1er boss Tranchépine

### ISSUE THREAD

**Issue by Crotodur** [way-of-elendil/3.3.5#479]
Le premier boss du raid, Tranchépine l'Indompté doit être contrôlé à l'aide d'une orbe afin d'utiliser l'un de ses sorts pour casser tous les oeufs de la sale. 
https://fr.classic.wowhead.com/npc=12435/tranchetripe-lindompt%C3%A9

l'orbe devient inutilisable après la seconde utilisation et le boss ne peut plus être contrôlé (laissant environ 70% des oeufs intactes) et ce, même si des joueurs différents tentent l'action. Aucune autre solution que de tomber le boss. Une fois le boss tombée, la porte s'ouvre tout de même vers le reste de l'instance. 

Comportement attendu : pouvoir utiliser l'orbe plus de deux fois afin de vider entièrement la sale des oeufs.

**Comment by Crotodur** [comment]
En fait, des fois en tuant le boss, on wype, et des fois ça passe et ça ouvre la porte ...

**Comment by Limoustique** [comment]
Normalement il est impossible de tuer le boss avant d'avoir détruit tous les œufs, Il est censé faire wipe le raid.

**Comment by joshwhedon** [comment]
Ouai, mais je pense qu'en fait le decompte des oeufs s'est fait mais peut etre pas correctement. Ce qui explique pourquoi ils pouvaient plus utiliser l'orbe (y'avait plus d'oeuf) et ont reussi a tuer le boss. Par contre j'ai pas reussi a reproduire.
Vous avez wipe sur le boss ? Ou vous l'avez tue en une seule fois ?

**Comment by Crotodur** [comment]
En début de semaine c'est passé :
- l'orbe a été utilisable 2 fois puis s'est bloquée, alors on a tué le boss et c'est passé 

On a refait le boss hier :
- l'orbe a été utilisable 2 fois, puis s'est bloquée, on a tué le boss mais cette fois ci ça nous a fait wipe
- après wipe on y retourne, idem l'orbe utilisable que 2 fois, on tue le boss et la ça passe 

Dans tous les cas, il restait encore des œufs à détruire

**Comment by Ischjgt** [comment]
Plus possible d'utiliser l'orbe après avoir détruit 16 oeufs, il y en a une trentaine en tout.

**Comment by joshwhedon** [comment]
Ouai le probleme est justement que les oeufs ne repop pas apres un wipe, et ca foire les decomptes. J'ai reussi a corriger les respawn et ca a l'air avoir corrige le probleme, je mets ca demain il faudra me dire.
