### ISSUE TITLE
Démoniste : Démon vs Fragment d'âme

### ISSUE THREAD

**Issue by sarkolas** [way-of-elendil/3.3.5#48]
**Description**
Je joue démoniste. Quand je me déconnecte en dehors d'Orgrimmar (partout ailleurs) je ne conserve pas le démon invoqué à ma reconnexion, ni dans la page de sélection des personnages, le fragment d'âme ne m'est pas restitué non plus, il est perdu. Lorsque je renvoie mon démon je suis censé récupérer le fragment, mais cela n'est pas le cas.
Quand je rentre dans un battleground et que j'invoque mon démon pendant la préparation donc avant que la porte ne s'ouvre et qu'il est tué au combat je suis obligé de le réinvoquer et je perds encore une fois un fragment d'âme alors qu'il est censé respawn avec moi car j'ai commencé le bg avec lui ; a chaque respawn je perds donc un fragment d'âme. La même chose pendant le joug. La même chose avec les pierres de soins gangrénées si elles ont été utilisées en combat alors que j'ai commencé le bg avec.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Démoniste
- Mort-vivant
- Toutes
- invocation de démon nécessitant fragment d'âme (tous)
- citées plus hau (bg, hors orgrimmar, raid , donjon)
- Tous
- none

**Comportement attendu**
Dans tous ces cas cités plus haut selon mes souvenirs de joueur d'officiel je devrais récupérer les fragments d'âme (et du coup ne pas devoir souffrir les déco/reco ou arrêter de tag bg au bout de deux ou trois bg pour refaire mes fragments sur des mobs…)

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Par chance tu peux me dire si ca le fait toujours ?
