### ISSUE TITLE
Quête de l'arène des Grisonnes ne se valide pas en groupe

### ISSUE THREAD

**Issue by Ezolis** [way-of-elendil/3.3.5#480]
**Description**
Nous étions 4 personnes groupées pour l'arène de Grisonnes mais la quête ne c'est pas validée pour le groupe. Nous avons du faire les boss 1 par 1, et la quête ne se valide que si le lanceur de quête donne le coup de grâce au boss.

Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Bastion de la Conquête
- Faction : Horde
- Nom de la quête : La fosse des conquérants
- Nom du donneur de quête : Grennix Trémeustache

**Comment by Killyana** [comment]
Fixé prochaine maj
