### ISSUE TITLE
Onyxia : fear absent et taunt insensible

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#481]
Bonjour,
Pendant le boss onyxia ne fear pas en p3 et elle était insensible au taunt tout le long.
Ces fait ont était aperçu en raid 10 joueurs, et les tanks étaient des guerriers. Aucun taunt parmi le panel (Provocation/Cri de défi/Coup railleur) n'ont fonctionné.

**Étapes de reproduction**
Taunt: Essayer en raid 10 et en raid 25 et vérifier avec un wartank un paltank, un dk et un droodtank pour voir quel type de taunt est insensible. 
Fear: Essayer en raid 10 et 25, aller en P3 et vérifier si elle incante rugissement surpuissant

**Comportement attendu**
Onyxia devrait fear en p3 et être sensible au taunt

**Ressources additionnelles**
https://wow-tactiques.fr.gd/Repaire-d-h-Onyxia.htm
https://worldofwarcraft.judgehype.com/strat-instances-onyxia1/    (Onyxia incante son rugissement puissant, c'est là que les chamans avec leurs totems, les morts vivants et les prêtres sont très avantagés. -> dixit la strat sur ce lien)

**Comment by joshwhedon** [comment]
L'insensibilite au taunt est normal, c'est un des rares boss insensible au taunt.
L'interruption du fear sera corrigee.

**Comment by joshwhedon** [comment]
En fait l'insensibilite au taunt ca a ete nerf a wotlk. Je corrige aussi

**Comment by Sarlik** [comment]
Super merci Josh
