### ISSUE TITLE
Rogue: Esquives et parades sur techniques générant des points de combo

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#482]
**Description**
"Bonjour, signalement de bug sur les techniques qui génèrent des points de combo (CP) :
Lorsqu'un coup générateur de CP est esquivé ou paré en druide ou en voleur, l'intégralité de son coût est retirée.
Reproduction :
- prendre un druide ou un voleur 80
- lui enlever toute expertise
- spammer une technique qui génère des CP
- constater le coût en énergie si esquivé
Comportement attendu : quand une technique qui génère des CP est esquivée, elle doit ne coûter que 20% de son coût initial.] "

**Comportement attendu**
Ici ça dit 20%
https://eu.forums.blizzard.com/en/wow/t/rogues-ability-energy-cost-when-dodge-parry/96776
Ici 50%
https://www.wowhead.com/forums&topic=12474

**Comment by joshwhedon** [comment]
Aucune info disponible pour la 3.3.5.

**Comment by joshwhedon** [comment]
De ce que j'ai pu trouver jusque la, c'etait un talent qui faisait ca (Surprise attack), et un autre talent pour les finishing moves, et ils ont tous les deux ete retire. J'ai trouve aucune info pour la 3.3.5 concernant un passif / talent / etc (ou pour wotlk en general).
Cette discussion revient d'ailleurs sur les forums avec les royaumes vanilla, les gens ont l'air un peu surpris du comportement aussi. Donc je suppose que c'est quelque chose qui a du changer et a ete retire.

**Comment by Belore** [comment]
Bonjour, je reviens sur la discussion à propos de ce ticket :
Le tout premier patch du jeu, encore en beta, a appliqué cette mécanique : "Abilities now cost less energy if they miss or are blocked." Les seuls changements opérés depuis concernent les "finishers", dont la réduction d'énergie s'obtient par le talent "rapid recovery".
https://worldofwarcraft.judgehype.com/betawow-13avril2004/
Je viens de rechercher toutes les occurrences des mots "énergie" et "energy" dans l'ensemble des patchs jusqu'à la 3.3.5 sans lire de changement à cette mécanique, qui est absente sur WoE depuis la dernière merge.
De plus le thread ci-dessous parle de cette mécanique de jeu, décrite comme telle (et non comme un passif/talent). Il concerne l'extension BC mais à nouveau, aucun changement concernant ces capacités n'est noté dans les patchs suivants.
https://www.mmo-champion.com/threads/929991-Can-the-feral-druids-please-help-me-settle-something

**Comment by Belore** [comment]
Sur cette vidéo datant de 2009, à 9:21, on peut voir un Estropier (60 énergie, 55 glyphé) être esquivé. Le voleur ne perd alors que 12 d'énergie, soit 20% du prix initial de la technique. (Passer la vidéo en 720p vitesse x0,25 pour mieux voir.)
https://www.youtube.com/watch?v=0wnC_3AkMfU

**Comment by joshwhedon** [comment]
Merci, un correctif sera applique pour les rogues. LEs Druide il y a un talent pour.

**Comment by Belore** [comment]
Merci à vous ! Attention, le talent "Précision primale" des druides fait la même chose que le "Rétablissement rapide" des voleurs, et ne concerne que les coups de grâce. Le problème de récupération d'énergie concerne toutes les techniques qui génèrent des points de combo, comme Attaque pernicieuse ou Estropier pour le voleur, Mutilation(félin) ou Lambeau pour le druide.

**Comment by Belore** [comment]
"Précision primale
Rang 2/2
Augmente votre expertise de 10, et vous êtes remboursé de 80% du coût en énergie d'un coup de grâce si celui-ci échoue."

"Rétablissement rapide
Rang 2/2
Augmente tous les effets de soins utilisés sur vous de 20%. De plus, vous êtes remboursé de 80% du coût en énergie de vos coups de grâce s'ils ne touchent pas la cible."

Je précise aussi que la mécanique de remboursement du coût des techniques qui génèrent des points de combo devrait s'appliquer également aux coups "ratés", pour les voleurs et les druides féraux n'ayant pas le cap toucher. SVP, faites-moi savoir si je dois trouver une autre ressource pour montrer ce point-là aussi ! Ça m'a pris un certain temps pour trouver l'autre.
