### ISSUE TITLE
Infusion de puissance/BL

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#483]
**Description**
La Bl écrase l'infusion de puissance du dp alors que c'est sensé se cumuler.

**Étapes de reproduction**
- Classe : 1 dp et 1 autre cast et 1 chaman
- Sort : mettre l'infusion de puissance sur le cast puis lancer la bl du chaman

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
La Bl n'est pas sensé écraser l'infu et les 2 doivent se cumuler

**Comment by joshwhedon** [comment]
https://wowwiki.fandom.com/wiki/Buff
Generalement les buffs similaires ne se stack pas. C'est le comportement normal. Si il y a une exception pour l'un d'eux, merci d'en fournir la preuve, mais a premiere vue c'est ce qui est attendu.

**Comment by joshwhedon** [comment]
Plus precisement sur celle ci:
Patch 2.4.0 (25-Mar-2008): Infuses the target with power, increasing their spell haste by 20% and reducing the mana cost of all spells by 20%. Lasts for 15 seconds. This will not stack with other haste effects, such as Heroism or Bloodlust. Previously increased damage done by 20%.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/pull/23592
