### ISSUE TITLE
DPS Gargouille

### ISSUE THREAD

**Issue by Sthanks** [way-of-elendil/3.3.5#484]
**--- Comparatif dégâts de gargouille ----
(Full stuff s8 opti) Mon dk sous full proc : Scale 271 - Verdict 258 - Proc PA bague 480PA - 150 Force proc deuil
1k8 - 2k - sans dot
https://www.twitch.tv/videos/592625278
--- Vidéo OFFICIEL ----
(Stuff s8) Arme 264 --- Proc crane à croc
2k1 à 2k6+ - Sans dot
https://www.youtube.com/watch?v=jA5I7jCqyfg
Y'a quand même une différence de stuff qui est énorme et les dégâts sont moindre coté WOE,
Je link plus une video d'offi d'un dk full s8, trinket pvp, arme s8 ou s7 258
https://www.youtube.com/watch?v=mCCySuuk_hk**

**Comment by joshwhedon** [comment]
Ce rapport de bug n'est pas utile a moins de fournir les informations manquantes :
- quelle stat est incorrecte et quelle est la valeur correcte
- quel talents ne fonctionne pas
- etc.
Je ne peux pas passer 10 heures sur un pet base sur un "ressenti" de manque de degats.

**Comment by Sthanks** [comment]
Ce matin je tapais du 4K + (Un peu trop) dans l'aprem c'est repasser sur du dégâts de base qui est largement nerf pour un burst de fin de template .. on ta filer les donnés la dernière fois sur les coefficient etc.

-scales with all physical haste benefits at the same rate as the player
-attack power coefficient is 0.4
-base damage per strike is 120
-does not inherit any crit from the player
-does not inherit any +damage % modifiers from the player, such as bone shield, desecration, or blood presence

En sachant que y'a toujours les problèmes de PV elle est à 9K 

merci d'avance

**Comment by joshwhedon** [comment]
Ces stats sont deja celle applique. Ce matin ca tapait a 4k (qui est pas "un peu trop") parce que j'avais tester de changer le multiplicateur de degats du sort et de le mettre a 1, ce qui clairement n'etait pas correct.
Il n'y a aucune info disponible quand aux PV, donc actuellement elle prends un % des pv du DK (le meme pourcentage que la goule, sans les talents vu que les talents parlent explicitement des ghoules.

**Comment by Sthanks** [comment]
Ta pas moyen d'essayer de mettre une stats inférieur a ce que t'avais mis? 2k5 - 3k dps pour un dk full stuff en fin d'extension c'est clairement plus que correct, je suis désoler d'être relou et de te faire perdre ton temps mais on trouvera pas autre chose a ce propos appart des vidéos de retail à l'époque.

**Comment by joshwhedon** [comment]
On change pas des donnees au piff jusqu'a ce que ca ait l'air de marcher :D

**Comment by joshwhedon** [comment]
Je vais changer un truc sur la vitesse de cast, au cas ou ca influe sur le dps, mais je doute que ca fasse une reelle difference.
