### ISSUE TITLE
[Quest] Zone d'exclusion aérienne

### ISSUE THREAD

**Issue by rommni** [way-of-elendil/3.3.5#485]
**Description**
Durant la quête Zone d'exclusion aérienne (12815), on obtient un griffon d'os (29414) pour tuer les Chevaucheur de griffon de l'Assaut (2933).
Ce griffon possède 4 techniques dont 2 effectuant des dégâts:
 - Frappe de peste (54469)
 - Souffle de givre (48766)

Ces 2 spells de dégâts ne doivent avoir d'effet que sur les chevaucheur de griffon de l'assaut, or tous les mobs de la zone peuvent être tués avec ces sorts.

**Étapes de reproduction**
Prendre la quête Zone d'exclusion aérienne à Uzo Mandemort (journa lame d’ébène) . Puis rendez vous sur l’île en face au port de l'assaut, chevauchez le griffon et commencez à lancer des sorts partout.

**Comportement attendu**
Les sorts ne doivent faire des dégâts qu'au chevaucheurs de griffon.

**Ressources additionnelles**
*Liens Wowhead* :

-  Quête: https://fr.wowhead.com/quest=12815/zone-dexclusion-a%C3%A9rienne
-  Objet invoquant le griffon : https://fr.wowhead.com/item=40600/griffon-dos
-  Griffon : https://fr.wowhead.com/npc=29414/griffon-dos#abilities
-  Frappe de peste : https://fr.wowhead.com/spell=54469/frappe-de-peste
-  Souffle de givre  : https://fr.wowhead.com/spell=48766/souffle-de-givre
-  Unique cible devant prendre des dégâts: https://fr.wowhead.com/npc=29333/chevaucheur-de-griffon-de-lassaut

**Comment by joshwhedon** [comment]
Merci pour tous les details, ca accelere beaucoup le travail.

**Comment by rommni** [comment]
Pas de soucis
