### ISSUE TITLE
Fleur de vie Rdrood

### ISSUE THREAD

**Issue by Mougnok** [way-of-elendil/3.3.5#486]
La Fleur de vie du Druide bug : les ticks du hot semblent corrects mais l'explosion de la fleur en fin de timer est ridicule que ce soit avec un, deux ou trois stacks.

**Comment by Endalaust** [comment]
Possible d'avoir plus d'infos, des liens et des calculs? En l'état ce report n'a quasiment aucune valeur et ne suit pas le template de rapport de bug

**Comment by joshwhedon** [comment]
Il va falloir etre plus precis. Voila les infos dont on dispose:
Le soin de base est 776 * nombre de ticks
Le coefficient du bloom final est 0.3857, donc si vous avez 1000 de soin, 385 sera ajoute au soin de base.
Le soin final est affecte par les bonus de soin, talents, etc, MAIS le nombre de stack n'a aucun effet sur ces bonus: The final heal, however, is still unaffected by stacking multiple applications of this spell.
Le sort est actuellement scripte de cette facon, et ce sont les informations qui sont actuellement disponibles. Si vous avez des informations supplementaires indiquant que c'est "ridicule", merci de les fournir.

**Comment by toitit** [comment]
Salut ! 

Sur le fait que le nombre de stacks n'a pas d'effet sur le heal final, j'ai trouvé ça : 
https://wowwiki.fandom.com/wiki/Lifebloom qui dit : "the heal effect is multiplied by the number of applications (en parlant du bloom final)" au patch 3.1.0 et pas modifié après. 
Si j'ai d'autre source, je te dirais.

Ensuite sur la valeur du bloom : 
Testé sur le serv : druide heal 3474 ps, talent à noter : Don de la Nature : +10% heal
Si on calcule : (3474*0.3857 + 776)*1.1 = 2327.5
En réalité : 1512  (au lieu de 2327.5)
De plus avec 2 stacks : 2288 (au lieu de rester constant ou *2 selon l'option choisi)
Avec 3 stacks : 3064 (au lieu de rester constant ou *3 selon l'option choisi)

Pour les ticks, les valeurs sont correctes.

**Comment by toitit** [comment]
Merci pour le fix sur le nombre de stack.
Le problème de la valeur initial du bloom reste le même et ne colle pas à la formule donner : (ps*0.3857 + 776)*1.1
Avec 1014ps : 1284 attendu, 991 sur le serv
Avec 3474ps : 2327 attendu, 1512 sur le serv

**Comment by joshwhedon** [comment]
Je regarde ca.
