### ISSUE TITLE
PNJs joug ne (re)popent pas

### ISSUE THREAD

**Issue by Bigmamath10** [way-of-elendil/3.3.5#487]
Au joug les PNJs des tours lorsque l'on possède le joug ne sont pas présents ou ne repopent pas une fois tués.
Les PNjs dans l'enceinte ont un repop très long il semble.
Lorsque l'on ne possède pas le joug, tout semble correct.

**Comment by joshwhedon** [comment]
C'est qui on :D

**Comment by Bigmamath10** [comment]
Dans mon cas c'est la horde (donc les PNJs allianceux ne popent pas/plus) mais cela le fait peut-être également pour l'alliance  (je n'ai pas de perso allianceux pour te confirmer cela).
Pour les PNjs autour de l'enceinte quand on attaque, le temps de respawn est bien plus long qu'avant le merge mais ça je ne sais pas si c'est normal ou pas.

**Comment by joshwhedon** [comment]
Les pnjs ont un temps de respawn de 30 minutes. Donc si ils sont tues pendant le joug, ils vont pas repop pour un moment.
Maintenant quel est le comportement normal sur offi, aucune idee, si vous avez des infos je suis preneur.

**Comment by Bigmamath10** [comment]
Malheureusement non je n'ai pas les infos d'offi.
Je me base sur mon expérience d'avant merge avec un respawn bien plus rapide, genre 10min.
C'était donc voulu d'augmenter le temps de respawn des PNJs au joug avec les dernières MAJs ?

**Comment by joshwhedon** [comment]
Voulu, non, pas plus que c'etait voulu d'avoir un respawn rapide avant :D .

**Comment by Bigmamath10** [comment]
Ok :D 
Du coup le seul bug qu'il y aurait est que certains PNJs ne sont pas présents, à aucun moment
 Ceux de la tour Guetteflamme (est), je ne les ai pas vu présents une seule fois de la matinée bien que je sois passé régulièrement et que j'ai fait 2 joug en défense (un gagné et un perdu).

**Comment by Killyana** [comment]
Pour le respawn suffis d'aller sur offi, buté un de ces pnjs et déclencher le chrono.

**Comment by joshwhedon** [comment]
J'ai verifie tous les pnjs sont pop. Je repare le temps de respawn pour remettre ce qu'il y avait avant c'etait blizzlike,
