### ISSUE TITLE
[Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by Yepzet** [way-of-elendil/3.3.5#49]
**Description**
Les 2 personnages non joueur : "Mage de sang Drazial" et "Mage de sang Lynnore" , dans la zone "Terres foudroyées", n'acceptent pas les objets de quête que l'on doit leur rapporter.

**Étapes de reproduction**
Informations nécessaires pour reproduire le problème. 
- Emplacement : Terres foudroyées
- Faction : Alliance / Race : Gnome / Classe du personnage utilise : Démoniste
- Nom des quêtes : "Joues de Raillecroc" ; "La vitalité du sanglier" ; "Le coup décisif" ; "La morsure du basilic" ; "La vigueur du vautour"
- Nom du donneur de quête : Mage de sang Drazial et Mage de sang Lynnore

**Comportement attendu**
Le PNJ dois accepter les objets de quête quand on les lui apporte

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.
![WoWScrnShot_021920_143004](https://user-images.githubusercontent.com/61236893/74838839-90b60f00-5324-11ea-9a56-d163e193dfe9.jpg)

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Endalaust** [comment]
C'est un bug générique non lié à la quête elle même. 
Solution : Mettre les items attendus dans sa banque, les reprendre, aller voir le PNJ, rendre la quête

En cas de persistance : Abandonner la quête en conservant les objets attendus sans son sac, la reprendre, rendre la quête

**Comment by Killyana** [comment]
FIxé sur le serveur merge.
