### ISSUE TITLE
La maîtrise des cristaux

### ISSUE THREAD

**Issue by Tdwaterlaw** [way-of-elendil/3.3.5#490]
Bonjour,

J'ai un problème avec la quête journalière des Oracles au bassin de Sholazar : la maitrise des cristaux.
La quête consiste à tuer 50 Frénécoeurs à l'aide de cristaux récupérés au Havre touchétincelle. Cependant il est impossible d'avoir une action avec la boite contenant les cristaux. On ne peut donc pas tuer les frénécoeurs et donc impossible de faire la quête et du coup le haut fait lié à ses quêtes.

Merci d'avance

**Comment by Ischjgt** [comment]
Ça marche chez moi
