### ISSUE TITLE
Caveau du Sanctuaire Serpent 

### ISSUE THREAD

**Issue by Crotodur** [way-of-elendil/3.3.5#491]
Caveau du Sanctuaire Serpent - Raid BC 
(11 joueurs présents)

1 - Lorsqu'on va dans l'eau, il n'y a plus de pop de poissons mais des dégâts dû à l'eau à la place (ce n'est peut être pas un bug mais juste une adaptation par rapport à avant)

2 - Sur le dernier boss Dame Vashj https://fr.wowhead.com/npc=21212/dame-vashj l'animation visuelle des poteaux semble buguée sur la phase 2 du boss. Un rayon reliant l'un des 4 poteaux à Vashj apparaît, indiquant le poteau à désactiver avec les orbes. Une fois le poteaux désactivé, on passe au suivant. La désactivation est bien opérationnelle, seule l'animation visuelle du rayon  reste bloquée sur le premier poteau. 
![WoWScrnShot_041620_172507](https://user-images.githubusercontent.com/63373291/79478540-d3862180-800b-11ea-88c2-5234e9857c8f.jpg)

Le comportement attendu serait qu'une fois le poteau désactivé, le rayon change de poteau. 

Le bug est uniquement visuel, la mécanique fonctionne

**Comment by joshwhedon** [comment]
Je crois que le 1 c'est un fixe en fait.
Pour le 2, il y a pas vraiment d'ordre, les 4 sont supposes canaliser sur le boss. Mais ca bug visuellement. Je corrige prochaine mise a jour pour que les 4 canalisent correctement.
