### ISSUE TITLE
Boss: Le rôdeur d'en bas

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#492]
**Description**
Le boss reset si personne n'est dans l'eau

**Comportement attendu**
Le combat est censé pouvoir se faire sur la plateforme

**Ressources additionnelles**
https://www.youtube.com/watch?v=JhWuAKAwTaw

**Comment by Crotodur** [comment]
Le boss reset même si tout le monde est dans l'eau

**Comment by joshwhedon** [comment]
Je regarderai merci.
