### ISSUE TITLE
Quest: La bataille pour Fossoyeuse (Alliance)

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#493]
**Description**
13377 - [La bataille pour Fossoyeuse] Version Alliance
- Lady Jaina Proudmoore(5981)ne despawn pas et reste bloquée quand on échoue la quête, elle reste bloquée quand on sort du combat également en fait, sur sa dernière cible, elle revient vers nous quand on est de nouveau en combat

- Engorged Blight Worm 32483 ne despawn pas quand on échoue la quête (il doit apparaitre après l'embuscade, ce qui se passe la première fois qu'on lance la quête)

- Engorged Blight Worm 32483 ne cesse d'utiliser 61124 [Ingérer] sur sa cible, aussitot relaché, le joueur/NPC est ravalé (deuxième vidéo que je t'ai link : il y a quelques secondes entre chaque utilisation du spell). Aussi, le joueur/NPC ingurgité doit être projeté loin, ce qui n'est pas le cas ici.

- King Varian Wrynn 32401 bump à tout va, je ne sais pas trop comment c'est censé se passer mais dans le vidéo le spell n'est pas utilisé, le problème c'est qu'ils undermap ensuite 
EDIT: en fait varyan utilise le sort tonnerre de thrall
https://woehead.way-of-elendil.fr/?spell=59507

- Grand Apothecary Putress Entry: 31530  quand le combat commence contre ce NPC, c'est un double de lui qui vient nous attaquer, l'original reste inataquable. Et ce double se fait bump, c'est un vrai problème (comme dit précédement, ça les fait passer undermaps)

**Ressources additionnelles**
https://www.youtube.com/watch?v=y-psRBcr6eg part 1
https://www.youtube.com/watch?v=YLnkdm4v9Bw part 2

**Comment by Freyahh** [comment]
J'apporte ici quelques ressources additionnelles supplémentaires des références de la quête mentionnée ci-dessus, afin d'aider à la correction des bugs :

**- Ressources additionnelles**

Quête "La bataille pour Fossoyeuse" côté Alliance :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=13377
- WoW Head : https://fr.wowhead.com/quest=13377

PNJ "Dame Jaina Portvaillant" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=32402
- WoW Head : https://fr.wowhead.com/npc=32402

PNJ "Ver chancreux congestionné" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=32483
- WoW Head : https://fr.wowhead.com/npc=32483

Sort "Ingérer" :
- WoE Head : https://woehead.way-of-elendil.fr/?spell=61124
- WoW Head : https://fr.wowhead.com/spell=61124

PNJ "Roi Varian Wrynn" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=32401
- WoW Head : https://fr.wowhead.com/npc=32401

PNJ "Grand apothicaire Putrescin" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=31530
- WoW Head : https://fr.wowhead.com/npc=31530

**Comment by Ischjgt** [comment]
- Lady Jaina Proudmoore(5981)ne despawn pas et reste bloquée quand on échoue la quête, elle reste bloquée quand on sort du combat également en fait, sur sa dernière cible, elle revient vers nous quand on est de nouveau en combat

**Comment by Ischjgt** [comment]
Aucune idée de où est Jaina actuellement, mais elle est pas aux côtés de Varyan pour commencer la bataille.

**Comment by Ischjgt** [comment]
- Jaina ne reset pas à la fin de l'event (pareil coté horde ?)

- Dredru reçoit 13272 (Ombre) de dégâts |2 Lancer le tonneau chancreux |2 Grand apothicaire Putrescin.(Excès de dégâts 197)
Dredru reçoit 13469 (Ombre) de dégâts |2 Lancer le tonneau chancreux |2 Grand apothicaire Putrescin.
Dredru reçoit 13469 (Ombre) de dégâts |2 Lancer le tonneau chancreux |2 Grand apothicaire Putrescin.
Dredru reçoit 13469 (Ombre) de dégâts |2 Lancer le tonneau chancreux |2 Grand apothicaire Putrescin.

13k/s
Je crois que c'est parce que Putrescin avait 4/5 ou 6 stacks de son buff qui augmente les dégats, le NPC n'est plus là, si tu as besoin de l'ID dit moi

**Comment by joshwhedon** [comment]
Le buff est stackable mais le fait que Jaina aide pas ... ca aide pas.
