### ISSUE TITLE
Bug "animation de décès" des modèles de Wyvernes de Haut Perchoir (Mille Pointes)

### ISSUE THREAD

**Issue by Drenaas** [way-of-elendil/3.3.5#495]
**Description**
Lorsqu'une Wyverne (quelle qu'elle soit) de la zone de Haut Perchoir en Mille Pointes est tuée, celle-ci se fige après un très court moment dans sa position "normale" et est considérée morte. Je ne peux pas vérifier si cela empêche le dépeçage n'ayant pas le métier. Ce problème peut éventuellement s'appliquer aux autres modèles de wyverne mais je n'en ai pas rencontré d'autres.

**Étapes de reproduction**
- Se rendre au Haut Perchoir dans les Mille Pointes
- Tuer un mob de type "Wyverne", mob rare Tranchecoeur compris (voir photo)

**Comportement attendu**
Animation de décès propre au mob concerné lorsque les points de vies tombent à 0 et repositionnement du modèle selon son propre modèle de "cadavre".

**Captures d’écran / Vidéos**
![Bug Wyverne Milles Pointes](https://user-images.githubusercontent.com/63403129/79565254-a0e23480-80b0-11ea-96ad-663f22f03c39.png)

**Comment by joshwhedon** [comment]
Est-ce que tu utilise le patch HD par chance ?

**Comment by joshwhedon** [comment]
Je dira ique oui mai j'attends ta reponse. Moi j'ai pas ce soucis sans le patch HD. Malheureusement certains bug de ce genre ont lieu avec, mais on ne peut pas y faire grand chose.
![image](https://user-images.githubusercontent.com/543699/79565985-1bcd3e80-80f5-11ea-9c06-1bddea5a5e47.png)

**Comment by Drenaas** [comment]
Je ne veux pas dire de bêtises (le dossier de jeu m'ayant été passé directement téléchargé) mais je pense l'avoir. Pas de problèmes là dessus c'est pas impactant mais je préférais le signaler au cas où :).

**Comment by joshwhedon** [comment]
Oui merci :) . C;est bien de le signaler parce que ca pourrait etre un bug qui impacte certaines choses.

**Comment by Drenaas** [comment]
Pas de problèmes ! Merci à toi pour la réponse !
