### ISSUE TITLE
Sort : Disparition

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#496]
Le sort dispartion des voleur ( https://woehead.way-of-elendil.fr/?spell=26889 ) ne fait plus sortir du combat.

**Comment by Justforsoloq** [comment]
Faut préciser. Pve ou Pvp.
Si c'est en pve durant un boss fight c'est normal.

**Comment by Sarlik** [comment]
Ah ouais en pve ça ne sort pas du combat? même hors boss?

**Comment by joshwhedon** [comment]
En instance, ca ne sort pas de combat, ca ne fait que lacher l'agro et faire que les mobs ne vous attaquent plus.
Hors instance par contre ca vous sort de combat et si vous etes seul les mobs resetent.
Vous etiez en instance ou hors instance ?

**Comment by Sarlik** [comment]
J'étais instance my bad

**Comment by joshwhedon** [comment]
Pas de soucis, c'est un debug nouveau et on a passe 10 ans avec un comportement different, c'est normal de pas savoir :D .
