### ISSUE TITLE
Quest: La bataille pour Fossoyeuse (Horde)

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#497]
**Description**
- Lady Sylvanas Windrunner 31651 réagit de la même façon que Janna. elle reste bloquée à sa dernière cible et revient quand on est de nouveau en combat
- Blight Aberration 31844. bumpable (5minutes11 premiere vidéo pour voir que l'aberration se fait pas bump)
- Khanok the Impassable 32511  https://woehead.way-of-elendil.fr/?spell=69633 interrompu quand il fait une auto attaque, aussi le boss se retourne sans cesse comme si son aggro été reset
- Peu de temps après avoir lancé la quête, après avoir passé la premiere.. On voit Varimathras et un groupe d'abonimations qui veulent nous taper mais ils sont amicales, en fait ce groupe de mob doit apparaitre quand Varimathras s'en va (il passe bien hostile quand Varimathras est parti) ~3min10 première vidéo
- Quand j'ai regardé un joueur faire la quête, 2 Varimathras 31565 étaient en combat

**Ressources additionnelles**
https://www.youtube.com/watch?v=TwMSBSbe_ZM 
https://www.youtube.com/watch?v=9UsKZJYki0I

**Comment by Freyahh** [comment]
J'apporte ici quelques ressources additionnelles supplémentaires des références de la quête mentionnée ci-dessus, afin d'aider à la correction des bugs :

**- Ressources additionnelles**

Quête "La bataille pour Fossoyeuse" côté Horde :
- WoE Head : https://woehead.way-of-elendil.fr/?quest=13267
- WoW Head : https://fr.wowhead.com/quest=13267

PNJ "Dame Sylvanas Coursevent" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=31651
- WoW Head : https://fr.wowhead.com/npc=31651

PNJ "Aberration chancreuse" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=31844
- WoW Head : https://fr.wowhead.com/npc=31844

PNJ "Khanok l'Impassable" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=32511
- WoW Head : https://fr.wowhead.com/npc=32511

PNJ "Varimathras" :
- WoE Head : https://woehead.way-of-elendil.fr/?npc=31565
- WoW Head : https://fr.wowhead.com/npc=31565

**Comment by joshwhedon** [comment]
LA majorite des soucis etaient du au faut qu'a un reset de l'event les npcs n'etaient pas despawn.

**Comment by Flocapa** [comment]
Hello, je viens de retenter l'event, il est toujours infesable : thrall ne peux pas tank le dernier boss (les joueurs non plus on se fait os) et il y a de nouveau 2 Varimathras de pop à la fin.

**Comment by Flocapa** [comment]
En tout cas, rien de ce qui a été signaler sur cette quête n'a été fix que ce soit les spawn/despawn, le comportement des npcs, les aggros, le dernier boss (Varimathras) etc...

**Comment by joshwhedon** [comment]
J;ai ferme le bug il y a 4 heures. La mise a jour a pas ete passee.

**Comment by Flocapa** [comment]
Je ne suis malheureusement pas au courant de la façon ou l'ordre que vous procédez dans la résolution des bugs (quand envoyez vous les majs ? vous fermez le tracker avant ou apres la maj ? ou après vérification de la résolution de ce dernier ?).

**Comment by joshwhedon** [comment]
Les tickets se retrouvent generalement fermes au moment ou le correctif est pret. Generalement ils sont appliques le jour suivant :)

**Comment by Ischjgt** [comment]
Les méchants reset mais pas Janna et Sylvanas
- Lady Sylvanas Windrunner 31651 réagit de la même façon que Janna. elle reste bloquée à sa dernière cible et revient quand on est de nouveau en combat.

**Comment by Amilgaull** [comment]
Lady Sylvanas n'attaque plus aucun pnj après le premier boss. Je pense d'ailleurs que les dégâts causés par Thrall et Sylvanas sont bien en dessous de ce qu'ils devraient (On peut voir notamment sur la vidéo https://www.youtube.com/watch?v=9UsKZJYki0I à compter de 4minutes 30 que le combat contre varimathras dure une dizaine de secondes seulement. On remarque aussi, au début de cette même vidéo que certains mobs se font OS. Actuellement c'est loin d'être le cas et on se retrouve rapidement submergés par les mobs.
Autre point, au moment de l'ascenseur piégé, sur woe l'ascenseur est toujours présent de même que la porte, on peut voir le fonctionnement normal sur cette video https://www.youtube.com/watch?v=TwMSBSbe_ZM à compter de 5 minutes 58. On peut néanmoins passer une fois la porte ouverte et se mettre au bord de l'ascenseur pour tomber, le reste de la chute est bien réalisée.
Infos sur Sylvanas : 
15:13:03 Name: Lady Sylvanas Windrunner
15:13:03 SpawnID: 145493, current GUID low: 347571.
15:13:03 Entry: 31651.
15:13:03 Faction: 250.
15:13:03 NPC Flags: 0.
15:13:03 DisplayID: 28213 (Native: 28213).
15:13:03 Compatibility Mode: 0
15:13:03 Level: 83.
15:13:03 EquipmentId: 1 (Original: 1).
15:13:03 Health (base): 2789000. (max): 2789000. (current): 2789000.
15:13:03 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
15:13:03 Unit Flags: 524288
15:13:03 * UNIT_FLAG_IN_COMBAT (0x80000)
15:13:03 Unit Flags 2: 2048.
15:13:03 Dynamic Flags: 0.
15:13:03 Faction Template: 250.
15:13:03 SpawnTime: Full:1s Remaining:0s
15:13:03 Loot: 0 Pickpocket: 0 Skinning: 0
15:13:03 InstanceID: 0
15:13:03 Phasemask: 64
15:13:03 Armor: 10673
15:13:03 Position: 1591.606201 383.407440 -62.453510.
15:13:03 AIName:  ScriptName: npc_lady_sylvanas_windrunner_bfu
15:13:03 React state: AGGRESSIVE
15:13:03 Active AI: npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI
15:13:03 Flags Extra: 536870912
15:13:03 * CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING (0x20000000)
15:13:03 MechanicImmuneMask: 0
15:13:03 dmg_multiplier: 35.000000
