### ISSUE TITLE
Ombreflamme consomme le totem de glèbe

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#499]
**Description**
L'ombreflamme des démonistes consomme le totem de glèbe du chaman mais applique aussi le slow et le dot.

**Étapes de reproduction**
Prenez un démoniste et un chaman, posez un totem de glèbe, ombreflamme et regardez.

**Comportement attendu**
L'ombreflamme applique le slow et le dot mais laisse le totem de glèbe (les aoe n'affectent pas le glèbe)

**Ressources additionnelles**
https://wotlk-twinhead.twinstar.cz/?spell=8177
https://wotlk-twinhead.twinstar.cz/?spell=61290

**Comment by Justforsoloq** [comment]
Addendum : Possibilité du bug avec toutes les aoe
L'explosion de la bombe vivante du mage, enlève le buff du glèbe sans le casser
Comportement attendu : L'explosion de la bombe vivante n'a aucune incidence sur le totem de glèbe.

**Comment by joshwhedon** [comment]
Je fais des modifs un peu generale, faudra me dire si vous voyez des trucs douteux.
