### ISSUE TITLE
Bug Sort: Disuasion Classe: Hunter

### ISSUE THREAD

**Issue by Zethwa** [way-of-elendil/3.3.5#50]
**Description**
Les effets de la disuation: 100% parade et 100% deflection de spells marchent pas correctment sur elendil. Il y a certain sorts comme par exemple la tempete divine du paladin et la frappe au coeur du dk qui passent a travers.

**Étapes de reproduction**
- Classe: Hunt
- Race: n'importe
- Spécialisation: n'impote
- Sort : disuasion
- Circonstances: PvP

**Comportement attendu**
Le spell doit deflect ou parré toutes autre abilitées hors mis celles qui qui ne peuvent etre ni parré ni esquivé ni raté.

Certes il ya une liste de spells qui peuvent passer a travers la disuasion:

-Overpower (War)
-Chaos Bolt (Demo)
-Cheapshot (Rogue)
-Shiv (Rogue)
-Counterattack (Hunter melee ability)
-Runestrike (Dk)
-Engineering pyro-rocket (Enchant Ingé)

**Ressources additionnelles**
https://github.com/osiris123/Dispersion_Tracker/issues/161

**Comment by Ischjgt** [comment]
J'ai trouvé ça sur le wiki,

Patch 3.2.0 (04-Aug-2009): This ability now allows the hunter to parry spells and attacks from behind as well as in front. Now has a new visual spell effect.

+ ils en parlent ici https://www.mmo-champion.com/threads/801887-Deterrence

*rires sadiques*

**Comment by joshwhedon** [comment]
J'ai teste sur la mise a jour, le probleme a l'air d'etre regle. Ce sera donc corrige quand on la passera.
