### ISSUE TITLE
L'Oeil de l'éternité: Malygos

### ISSUE THREAD

**Issue by craigzour** [way-of-elendil/3.3.5#501]
La guilde Esketudez vient de combattre Malygos dans le cadre d'un progress traditionnel. Nous avons rencontré quelques difficultés liées à ce que nous pensons être des problèmes de script. Même si nous avons réussi à vaincre le boss nous souhaitons vous faire part des différences importantes (en comparaison avec la stratégie officielle).

Raid: Oeil de l'éternité
Difficulté: normal 10 joueurs
Boss: Malygos

1) Pré-phase 1:
* Comportement actuel:
  * Après avoir déverrouillé l'iris de focalisation, Malygos cible un membre du raid et fonce directement sur lui. Une fois arrivé sur la plateforme, Malygos se dirige vers le bord de celle-ci (comme si il voulait fuir le combat) pendant un court instant avant de revenir vers la cible initiale.
  * Malygos n'est pas en contact avec le sol mais légèrement en l'air.
  * L'iris de focalisation ne disparaît pas lorsque le combat commence.
* Comportement attendu:
  * Après avoir déverrouillé l'iris de focalisation, Malygos se dirige vers la plateforme afin de s'y poser (aucun membre du raid n'est ciblé). Une fois posé sur le sol, Malygos cible un membre du raid (le plus proche) et le combat commence.
  * Malygos est en contact avec le sol.
  * L'iris de focalisation disparaît lorsque le combat commence.

2) Phase 1:
* Comportement actuel:
  * Le vortex fait tourbillonner quelques membres du raid.
  * L'étincelle meurt mais ne se transforme pas en buff de zone (de temps en temps).
* Comportement attendu:
  * Le vortex fait tourbillonner la totalité des membres du raid.
  * L'étincelle meurt et se transforme en buff de zone à chaque fois.

3) Phase 2:
* Comportement actuel:
  * Le bouclier anti-magie spawn toujours au centre de la plateforme.
  * Le bouclier anti-magie rétrécit très rapidement.
  * Le bouclier anti-magie ne réduit pas les dégâts magiques subis.
* Comportement attendu:
  * Le bouclier anti-magie spawn à des positions aléatoires sur la plateforme.
  * Le bouclier anti-magie rétrécit doucement.
  * Le bouclier anti-magie réduit les dégâts subis.

4) Phase 3:
* Rien à signaler pour le moment. Il y a peut être un problème sur la mécanique des points de combos mais c'est assez difficile à dire puisque nous l'avons faite qu'une seule fois.

5) Hors combat (wipe):
* Comportement actuel:
  * Libérer l'esprit après la mort renvoie le joueur en fantôme à la pierre et l'empêche de se déplacer (la plupart du temps). Se déconnecter/reconnecter débloque la situation.
* Comportement attendu:
  * Libérer l'esprit après la mort renvoie le joueur en fantôme à la pierre et lui permet de se déplacer afin de pouvoir retourner à pieds dans l'instance.

Tous les détails donnés sur les comportements attendus proviennent de la vidéo suivante https://www.youtube.com/watch?v=HvPvWIEiUsk

**Comment by joshwhedon** [comment]
Phase 1: Je corrige le despawn de l'iris et j'ameliore un peu les visuel. Probleme par contre, le sol n'est pas un vrai sol, du coup Malygos apparaitra toujours un peu au dessus malheureusement.
L'etincelle a toujours spawn sa zone pour moi, je sais pas trop comment le probleme arrive. Vous etes sur que c'est pas qu'elle a atteint Malygos et du coup a ete absorbee ?
Je mets un correctif pour le vortex mais je peux pas trop tester tout seul :D .
Phase 2: le bouclier spawn toujours dans le cercle interne (environ 30 yard maximum du centre), c'est le cas aussi dans les guides. Mais le spawn est bien aleatoire dans cette zone.
Les boucliers changent de taille comme sur la video, d'ailleurs la vitesse de changement de taille provient des donnees client donc tres probablement correcte. Ils reduisent bien les degats des arcanes recu de 50% (les adds font du 15k en dehors, 7,5k dedans), et protege contre la surge de Malygos.

Pour le wipe, pas reussi a reproduire. Ca arrive dans quel cas ? Une phase particuliere ?

**Comment by joshwhedon** [comment]
Merci pour ce rapport de bug detaille en passant.
