### ISSUE TITLE
Death grip range

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#502]
**Description**
Il n'existe pas de range minimum pour la poigne de la mort (après recherche il semble en exister une)

**Étapes de reproduction**
Faites une poigne de la mort sur un joueur au cac

**Comportement attendu**
La distance minimum est de 8m (yard mais j'imagine qu'ils ne font pas le calcul 1 yard = 0,xxx m)

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Death_Grip
Wrath-Logo-Small Patch 3.3.3 (2010-03-23): Minimum range has been changed to 8 yards in PvP.

**Comment by joshwhedon** [comment]
Non en fait ce changement a ete mis uniquement sur le PTR en 3,3,3. Il y a eu tellement de plainte que ca a jamais ete mis sur l'officiel. Trinity avait d'ailleur implemente ca sur le merge mais j'ai du le retirer apres qu'on me l'ai signale. Je peux tenter de te chercher les liens qui le montre si tu me fais pas confiance, je les ai pas gardes.

**Comment by Justforsoloq** [comment]
C'est plus que je me faisais pas confiance à moi même quand j'ai fait ça, car dans mes souvenirs tu pouvais grip au cac, mais quand je suis tombé sur ce fix là j'ai gratté ma tête et je me suis dit que peut être j'étais décadent et que je n'avais plus une si bonne mémoire, donc j'ai fait le report quand même. Je suis content de m'être trompé en le faisant et que ma mémoire était bonne x)
