### ISSUE TITLE
Sort Sang luminescent Buff -> Débuff

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#503]
Le sort Sang luminescent ce place dans les buffs et non dans les débuffs 
https://woehead.way-of-elendil.fr/?spell=35325

(Ce n'est pas hyper important mais j’espère vous aider à avoir un serveur le plus propre possible)

**Comment by joshwhedon** [comment]
Merci :) Ca se corrige facilement. C'est probablement du au fait que le debuff est aussi un buff (agilite augmentee).
