### ISSUE TITLE
Soucis d'interfaction au 18/04

### ISSUE THREAD

**Issue by Nounours-sempiternal** [way-of-elendil/3.3.5#504]
**Description**
Interfaction semble poser soucis

**Étapes de reproduction**
Ce matin (18/04), nous avons tag en donjon aléa HM avec un groupe de guildeux (3 ally : tank / heal et dps). 
Nous avons tout d'abord été groupés avec 2 joueurs hordeux (alors qu'il y avait 437 connectés via un /who 1-80)
L'un des joueurs hordeux n'a pas réussi à rejoindre le donjon dans un premier temps (soucis de fly).
Nous avons commencé à faire la montée de l'occulus en attendant notre 5 eme joueur.

Suite à un missclick sur le portail d'accès à la plateforme du 1er boss, (pour rejoindre les dps qui étaient du coup seuls avec les mobs restants), j'ai voulu me tp out / tp in.

A la base, j'étais situé à Dalaran (devant la banque ally). Le message que j'ai eu m'indiquait que je n'étais pas à un emplacement permettant de rejoindre un donjon ...
Je me suis donc mis en route pour rejoindre l'occulus normalement.
Entre temps, notre collègue hordeux qui n'avait pas pu rentrer dans le donjon a pu le rejoindre.

Une fois arrivé devant le portail d'accès à l'occulus, le passage de ce portail m'indiquait que je ne pouvais pas rejoindre ce raid.
J'ai essayé de rentrer dans un autre donjon (nexus), ça a bien fonctionné ...
En voulant réutiliser la fonction de "tp in", ça m'a tué devant la pierre de TP nexus / occulus / malygos.
Un collègue Ally est sorti pour vérifier que j'étais bien au bon tp (quand même ...)
De mon côté, toujours le même soucis, et ce collègue Ally n'a pas non plus été en capacité de rejoindre le donjon.
Ca s'est terminé en retag ...

2eme donjon : GT4
Même scénario : les 3 joueurs ally précédents retaguent ensemble.
Nous sommes groupés sur GT4 avec un 4eme ally, et un 5eme comparse Hordeux. (avec 494 connectés d'après le même /who 1-80).

Ce dernier n'a jamais été en capacité de nous rejoindre, nous avons donc terminé le donjon à 4.

**Comportement attendu**
L'interfaction ne devrait pas être active avec plus de 250 joueurs connectés simultanément de souvenir.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Comment by joshwhedon** [comment]
Je regarderai mais honnetement je promets rien. Impossible de tester la recherche de donjon en local. Vous auriez pas du vous retrouver groupes en premier lieu. C'est deja arrive avant ?

**Comment by Nounours-sempiternal** [comment]
c'est arrivé ce matin, depuis le merge je n'avais pas eu spécialement ce soucis avant.

**Comment by Ischjgt** [comment]
C'est connu, ça arrive quand l'interfaction en donjon se désactive.

**Comment by Nounours-sempiternal** [comment]
pour le coup, si je peux me permettre, l'interfaction en donjon n'aurait pas dû se désactiver... n'étant normalement pas active du tout durant ces donjons-là (sauf si les seuils ont été relevés sans nous en informer)

**Comment by Ischjgt** [comment]
Pardon j'ai mal lu, j'ai lu "ce matin" sans lire le "437 connectés"
Si tu affirmes que vous étiez ce nombre en rejoignant la recherche de donjon ne prend pas en compte mon commentaire

**Comment by Nounours-sempiternal** [comment]
c'est pour ça que je me suis permis d'ajouter mon commentaire :) j'ai eu un MJ en ligne , qui m'a justement demandé de créer ce ticket.
j'avais fait une requête, donc l'horaire précis / le nombre de connectés à ce moment-là devrait pouvoir être retrouvé
