### ISSUE TITLE
Caravane de désolace

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#505]
https://woehead.way-of-elendil.fr/?quest=5943
En lançant la quête prise sur le pnj https://woehead.way-of-elendil.fr/?npc=11626
La caravane ne bouge pas. 
Dans le même temps, https://woehead.way-of-elendil.fr/?npc=11625 est supposé faire un parcours mais il reste également sur place.
Conséquence du maintien sur place des pnjs, https://woehead.way-of-elendil.fr/?npc=12245#. et https://woehead.way-of-elendil.fr/?npc=12246 ne popent pas.
The Vendor-Tron 1000[60, 38] is a level-38 trade-goods vendor that appears on the road southeast of Thunder Axe Fortress in the contested territory of Desolace. It is part of the Gizelton Caravan, a kodo caravan run by goblins. This caravan travels from the Kolkar Village in the north to Mannoroc Coven in the south (where Super-Seller 680 appears).

Supposedly, the caravan used to arrive here once an hour around the hour mark; but that schedule no longer applies, and the interval appears to simply be however long it takes to travel to the south and back. Vendor-Tron 1000 is only available for a short time while the caravan is stopped.

**Comment by Killyana** [comment]
Le bug consiste dans le fait que les 2 pnjs doivent proposer les quête qu’après l'annonce et non durant les pauses ou le trajet.

**Comment by joshwhedon** [comment]
Oui oui et sur woe c'est le cas.

**Comment by Killyana** [comment]
Je me rappel que l'un des pnjs propose une quête même si la caravane est en pause
