### ISSUE TITLE
Boss: Le roi-liche

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#506]
**Description**
36597 - [Le roi-liche] 
Testé en 10NM, 25NM, 25HM (le soucis est très probablement présent en 10H aussi du coup)

Dans toutes les difficultés, un joueur qui meurt ou Terenas Menethil  qui meurt ne donne pas de soft enrage au boss

10NM et 25NM :
Name: Terenas Menethil
Entry: 36823. 

**Comportement attendu**
NM : "If either the player or the NPC die inside Frostmourne, Arthas gains +200% damage for 15 seconds. "
HM : "In the third phase the entire raid will be pulled into Frostmourne instead of one person. Wicked Spirits will fall from above which must be dodged/killed. Any deaths will still result in Harvested Soul being applied to the Lich King and it can stack. "

Désolé j'ai pas l'ID du spell je regarde un peu

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)

**Comment by joshwhedon** [comment]
SPELL_HARVESTED_SOUL

**Comment by Ischjgt** [comment]
C'est encore en 25Nm, je te dis dans les prochaines heures pour les autres difficultés
