### ISSUE TITLE
Frappe au coeur

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#509]
**Description**
J'aimerai savoir pourquoi le dmg de la frappe au coeur on étaient nerf? sachant que c'est la main attaque du dk sang et que normalement elle sont cencé faire minimun 35% du dps sur poto boss sans compté les cleave. Le DK est cencé être le burst cac le plus fort en raid (+ 108% de dmg physique en raid sans compté les proc) voilà merci.
J'ai une opti  full 277/284 et je tape moins fort qu'un mage feu opti 264 alors que je sais faire mon cycle dps.

**Comment by Elahbienscript** [comment]
![X9LHJ1O](https://user-images.githubusercontent.com/63306323/79670527-0e32ba00-81c4-11ea-8c4f-4b41f73572e8.png)

Un recount qui atteste ce que je dit

**Comment by Elahbienscript** [comment]
apres je cherche encore des source sur le script

**Comment by Ischjgt** [comment]
Ton recount n'atteste rien du tout, on s'est pas d'où ça vient ni dans quelle circonstance il a été fait...
Je t'ai déjà parlé de ça tout à l'heure, je regarde ce soir/demain mais ça sert vraiment à rien de sortir ça, y'a d'autres trucs plus urgents à débug que des suppositions en fait

**Comment by Elahbienscript** [comment]
bah en gros si je te suis, pasque c'est dk sang et que c'est pas top recount on s'en branle ^^ par contre les bug drw ca à bien été report et rescripté pasque "c'étais abusé", là je te donne juste un recount qui te montre que la frappe au coeur c'est 35% du dps du dk sang en full stuff et que sur woe faut être en sueur pour osé mettre 30%. avec 
je comprend que t'as pas que ca à branlé mais moi je demande simplement à comprendre j'ai jaimais dit que c'était bugé ou quoi, je demande pourquoi une telle baisse en faite. Et comme je t'ai dis je vais essayer de te trouver des truc sur le script de la frappe au coeur mais le dk sang est pas bcp joué donc pas grand chose dessus.

**Comment by Elahbienscript** [comment]
Merci en tout cas de te penché dessus, si tu trouve des trucs tant mieux, m^me si ca contredit ce que je t'ai dit

**Comment by Elahbienscript** [comment]
Est-ce que les 10% de DMG/ maladie sont appliqué sur la frappe au coeur? 
Je vois pas bcp de différence avec ou sans maladies sur les dmg de la frappe au coeur (20% en plus normalement ca se vois)

**Comment by Elahbienscript** [comment]
sur wowhead: 
Frappe instantanément la cible et son allié le plus proche, infligeant 110% des dégâts de l’arme à la cible principale et 55% à la cible secondaire.

et sur woe : 
Frappe instantanément la cible et son allié le plus proche, infligeant  76% sur la principale et 38% sur la secondaire

**Comment by Elahbienscript** [comment]
J'ai fait des test sur poto il semblerai que les 10%/maladies soient appliqué, donc case départ ^^
c'est juste que elle tape moins fort en général que avant alors que je ne vois pas la raison, c'est le même spell basé sur les même stats avec le même stuff.

**Comment by joshwhedon** [comment]
Il y a eu de grosses modifications avec la merge, avant la merge beaucoup de techniques de melees etaient incorrectes parce que les stats des joueurs etaient mal calculees (pas recalculees lors de changements d'arme, etc). Je peux jeter un oeil aujourd'hui, mais est il possible que tout soit bien pris en compte maintenant, et qu'avant les calculs etaient foireux ?

**Comment by Elahbienscript** [comment]
et bien c'est la question que je me pose, pasque je trouve que mes frappe au coeur manque de dmg, c'est cencé être ma main attaque avec 35% sur mon recount avec hate cac, sans on devrai être vers les 40%
aujourd'hui elles sont à 30% avec hate cac (20%) je sais pas ou son passé les 5%.
sur ce tout ce que j'ai pu trouvé les dmg de la frappe au coeur sont à 35%.
Après j'ai remarqué que ma tranche de dmg évolue, parfois je perd 300 dmg et je sais pas pq, 2 minute apres je les récupère ou je doit déco reco. Je sais pas si c'est lié ou pas mais bon en full opti 277/284 je galère à maintenir 16k dps voir je les fait pas alors que je sais faire mon cycle et je pense bien joué ma classe.

**Comment by joshwhedon** [comment]
Bah, perso j'ai teste sur mannequin, les degats ont l'air bon. Les pourcentages sont correctement pris en compte, etc. Comme j'ai dit avant la merge, pas mal d'attaques de melee etaient incorrectes (les paladins retribution avaient un probleme similaire). Donc ... je sais pas. Si tu as du temps a l'occasion, fait des tests sur mannequin pour voir si ca correspond bien aux degats attendus par rapport aux attaques de melee. A part ca je vois pas desole.
J'ai aussi regarde par rapport aux tranches de degats de DrDamage, et toutes mes attaques etaient dans la tranche attendue.
Du coup, je ferme le bug pour l'instant, si tu trouve plus d'info quant a ce qui pourrait manquer, ajoute un commentaire et je reouvrirai.

**Comment by Elahbienscript** [comment]
Ca marche merci, je vais voir si je trouve des trucs.

**Comment by Elahbienscript** [comment]
Je voulais savoir si tu avais pris en compte le talent "Gorgé de sang" 5/5 qui offre 10% d'arpen à tout moment et 10% de dmg quand le dk à plus de 75% de vie?
je vais essayer de faire des test mais maintenir 75% hp en sang c'est pas simple avec la régen permanente ^^

**Comment by Elahbienscript** [comment]
(Et au faite je te le marque ici mes les maladies de la DRW disparaissent une fois que celle ci disparait, je t'avais mis des screen sur un autre post je sais pas si tu as pu voir ?)

**Comment by Elahbienscript** [comment]
https://discordapp.com/channels/@me/706955163814068314/706955166879842346

tiens j'ai justforsoloq qui m'a trouvé un lien qui te montre que la frappe au coeur est nerf de ~5% de dmg, si ca peux t'aider pour le script
