### ISSUE TITLE
Spell: Death Knight T10 Melee 4P Bonus

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#51]
**Description**
Serveur prod et test
Le buff Avantage donné par le bonus 4 pièces T10 du DK ne proc pas sur certains sorts alors qu'il devrait.

**Étapes de reproduction**
DK 4T10 DPS, 
Faire en sorte qu'il n'y ait plus de runes disponibles après avoir fait un Anéantissement/Pestilence/Frappe du Fléau/Rafale Hurlante

**Comportement attendu**
J'ai les preuves que ça doit proc sur Anéantissement et Pestilence dans la vidéo plus bas.
Reste à prouver pour Frappe du Fléau et Rafale et peut-être d'autres sorts (il est 4h30, j'édit demain)

**Ressources additionnelles**
https://www.youtube.com/watch?v=vLJ3NljxdP8
3:36 et 5:45 : Le dernier sort utilisé avant que le buff proc est Pestilence
3:48 et 3:53 : Refresh du buff avec Anéantissement

Le sujet avait déja été évoqué sur le ticket 5528 de l'ancien BT

**Comment by Fairivier** [comment]
le 4t10 ne proc pas non plus lorsque l'on fini par une frappe au coeur

**Comment by Skhoss** [comment]
Il marche uniquement si on finit par frappe de sang, le furoncle sanglant ne marche pas non plus pour le déclencher.

**Comment by Fairivier** [comment]
La frappe de mort le fait proc aussi

**Comment by Fairivier** [comment]
pti up la mmort et décomposition ne fait pas proc le 4T10 aussi

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/993

**Comment by Kaasss-woe** [comment]
Corrigé (appliqué demain)
