### ISSUE TITLE
NPC: Roanauk Icemist

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#512]
**Description**

Name: Roanauk Icemist
Entry: 26810.
Name: Taunka Soldier
Entry: 26437.

Ces PNJs sont présents de façon permanente (j'émet l'hypothèse que tout va bien juste après un reboot du serv, j'essaie de te confirmer ça prochainement).

2:09 https://youtu.be/dTV1htL_eRI ; les PNJs ne sont pas là au moment où le joueur l'a libéré dans https://woehead.way-of-elendil.fr/?quest=12069

Ils apparaissent pour https://woehead.way-of-elendil.fr/?quest=12140 (la vidéo c'est la quête juste avant où tu dois libérer Icemist justement).
et je sais pas du tout le comportement qu'ils doivent avoir pas trop trouvé d'infos :( je sais que le joueur les voit encore en prenant la quête suivante par exemple

En fait le gros soucis c'est que ça bloque Overlord Agmar 26379 quand un joueur prend une nouvelle fois 12140

**Comment by joshwhedon** [comment]
Deja signale https://github.com/way-of-elendil/3.3.5/issues/234
