### ISSUE TITLE
[Quest=10859] Déclencheur de crédit npc=21929 qui ne déclenche pas

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#513]
L'utilisation du totem dans la quête 10859 - **Réunir les orbes** provoque bien l'attrait des "boules roses" mais ne comptabilise pas celles-ci.

**Comment by Ischjgt** [comment]
Tout pareil

**Comment by joshwhedon** [comment]
J'ai repasse le sql, j'ai du le manquer.
