### ISSUE TITLE
[Quest=10720] Quête de la marmotte aux tranchantes

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#514]
Les plus petites des créatures
Utiliser le tambour (item=31141) invoque bien une marmotte qu'on peut alors contrôler, mais elle aggro tous les mobs alentour alors qu'elle est supposée passer inaperçue.

Actionner les tonneaux avec la marmotte ne fonctionne pas (message vocal = Je ne suis pas à portée)

**Comment by joshwhedon** [comment]
Salut. J'ai reussi a faire la quete sans soucis. Normalement tu as une barre de sort avec la marmotte (si tu as un pet il faut le renvoyer ca cause des conflits). Dans la barre de sort tu as un sort pour te mettre fufu, et un pour empoisonner les tonneaux. C'est ce qu'il faut utiliser.
PS: le fufu bien sur est limite en distance, passe pas trop pres / devant les mobs.

**Comment by Rolirolant** [comment]
En effet... je ne sais pas comment j'ai pu passer à côté de ça. L'heure tardive probablement ooOO

**Comment by joshwhedon** [comment]
Ou l'alcool :D .
