### ISSUE TITLE
EDC 25 HM ALED les dégâts INSANE 

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#515]
**Description**
dégâts clairement trop élevés... je prend un OS à EDC 25HM avec 587 cap def et 35K armure; j'ai tank x serv; même sous OFFI; vous pouvez m'expliquer les dégâts que je prend avec les screens suivants sur le premier BOSS EDC 25HM; même à offi je me suis jamais fais violer ainsi !

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon: EDC
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc): 25 HM
- Boss: 1er
- Sort en question / Phase du boss en question / Emplacement: placement de straw
- Composition du groupe: random

**Comportement attendu**
 OS sur le 1 er BOSS avec 35K armure + sous CD et 587 cap def - 100% d'un coup

**Captures d’écran / Vidéos**

Impossible à être os sous cd avec STUFF ICC:

![Capture d'écran 2020-04-19 04 32 28](https://user-images.githubusercontent.com/63243193/79677983-f1fc4080-81f6-11ea-9e0b-6a57bf098216.png)
![Capture d'écran 2020-04-19 04 32 15](https://user-images.githubusercontent.com/63243193/79677987-fa547b80-81f6-11ea-85f0-d5085b08fb7a.png)

**Ressources additionnelles**

**Comment by Killyana** [comment]
Y'a eu un commit sur tc qui a update le damagemodifier de plusieurs boss, certains comme Gormok en 25h est trop élevé 119.8  contre 73.3 en 25 nm

Il faut trouver ce commit est check tout les boss qui ont été modiés

**Comment by joshwhedon** [comment]
Ouai j'ai trouve.
UPDATE `creature_template` SET `DamageModifier`=119.8 WHERE `entry`=35440; -- 25HC, 66.8k raw damage
Deja que @gtschanz  est pas bon si en plus les degats sont si eleve c'est mort pour lui :D

**Comment by gtschanz** [comment]
je veux bien être naze xd mais 1 os avec 1 stack d'empaler sous cd; je trouve ça énorme vu mes caps def
