### ISSUE TITLE
Debuff afficher en buff dans le bois de la penombre

### ISSUE THREAD

**Issue by Bleuphonix** [way-of-elendil/3.3.5#516]
**Description**
Un debuff qui reduit la regen PV de 50% la force et l'endu de 7 apparais en buff 
hors c'est un debuff pour le coups 
https://image.noelshack.com/fichiers/2020/16/7/1587292033-bug.png

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- je pense pas que la classe est un importance mais j'etait en voleur a ce moment la
- Bois de la pénombre
- Sort "Rage"
- Loups redoutable enrager 

**Comportement attendu**
Avoir le debuff afficher dans le debuff et non dans les buff

**Captures d’écran / Vidéos**

**Ressources additionnelles**

**Comment by joshwhedon** [comment]
Merci, je corrige ca :).
