### ISSUE TITLE
LFG: Groupes de 6

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#517]
**Description**
6 a être groupé dans des LFG depuis aujourd'hui

**Étapes pour reproduire**

[] chuchote : oui un joueur a leave 
[] chuchote : on a lancé une recherche pour completer
[] chuchote : mais je pense qu'on est 2 a avoir lancé cette recherche
[] chuchote : du coup ca a groupé 2 joueurs au lieu d'un 
[] chuchote : dans le groupe je vois 5 joueurs 
[] chuchote : mais un 6 eme nous as dit en chat de groupe qu'il arrivait a pied alors que tout le monde etait la 
[] chuchote : ca nous l'a deja fait dans le dj precedent a cime d'utgarde

**Comment by joshwhedon** [comment]
Honnetement je sais pas trop comment c'est arrive. Je mets un correctif pour empecher ca d'arriver, mais je sais pas si ca va marcher.
