### ISSUE TITLE
Bug Sacré scaling Prière de soin, Prière de guérison, Cercle de soin (Potentiellement le talent : Providence Divine)

### ISSUE THREAD

**Issue by CGBone** [way-of-elendil/3.3.5#519]
Les sorts Prière de soin, Prière de guérison et Cercle de soin ne scalent pas proprement avec les buffs ou l'augmentation de PS. La moyenne de soin rendu sur ICC est beaucoup plus faible que ce que m'indique Dr Damage en self buff, alors qu'il y a le buff 30 et full buff raid.

Ceci pourrait être dû a un bug sur le talent Providence Divine, qui est le seul talent qui regroupe un bonus sur ces 3 spells, et qui comporte aussi un pourcentage, donc un scaling.

J'ai testé hier soir sans prendre providence divine sur poteau, et mon heal ne changeait pas, cependant unbuff c'est plus difficile à savoir (une différence de 10% est moins visible quand le heal est moins haut)

**Étapes de reproduction**
- Prêtre
- N'importe
- Sacré
- Cercle de soin, Prière de soin, Prière de guérison
- Se sent principalement en ICC où le soin est le même avec le buff 30+raid que en self buff.
- Testé en 4T10, 6270gs, procs cape et anneau ICC. Et testé sur poteau sans ces buffs
- Les buffs n'ont pas l'air d'augmenter le soin moyen de ces sorts. Ou tout du moins pas autant qu'ils le devraient

**Comportement attendu**
Le plus probant est sur la Prière de soin et Prière de guérison, où le tick moyen est quasiment 1K / 1K5 plus bas que ce qu'il devrait être.

**Captures d’écran / Vidéos**
Comparaison sur un try Dame 10H avec buff 30 plus buffs raid et soin medium / crit mediums affichés par Dr Damage.
https://imgur.com/a/UlKq6eP

**Comment by Ischjgt** [comment]
Aucun problème chez moi pour Cercle de soins, Prière de soins, que ce soit avec le talent Providence divine, le 4T10, les glyphes, les multiplicateurs de heal etc... ou tout ce qui a été énuméré ici.
Et le drDamage me montre que tout va bien également
Vérifie d'avoie les rangs au bon sort ?

**Comment by CGBone** [comment]
Alors oui, merci j'ai les sorts au bon rang je suis pas teubé.

Forcément tester un problème de scaling unbuff ça se voit pas. Avez-vous essayé avec le buff 30 et des buffs de raid, puis comparé aux chiffres unbuff ?

**Comment by Ischjgt** [comment]
Testé full gear à ICC buff 30
Même sans ça je peux voir qu'il n'y a pas de problemes scaling ps et multiplicateurs heal
