### ISSUE TITLE
bug frappe-tempête amélioré

### ISSUE THREAD

**Issue by Greymald** [way-of-elendil/3.3.5#52]
**Description**
Le talent frappe tempête amélioré est supposé rendre 20% du mana max à chaque utilisation de frappe-tempête, il m'en rapport dans les faits, un peu plus de 10%.

**Étapes de reproduction**
au 8ème pallier de l'arbre de talent Amélioration prendre 2 points du talent "frappe-tempête amélioré"

**Comportement attendu**
ayant 2298 point de mana max, je suis supposer recevoir ~459 point de mana a chaque utilisation de frappe-tempête, il m'en rapporte 236.

**Captures d’écran / Vidéos**
https://imgur.com/a/ZdHycaL

**Comment by Killyana** [comment]
20% de votre mana de base
