### ISSUE TITLE
EDC5: Chevalier noir

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#521]
**Description**
Constaté NM/HM
D'avance désolé, j'ai pas réussi à reproduire, mais ça arrive assez souvent donc peut-etre que tu auras une piste.

Cas où The Black Knight 35451 reste bloqué en cadavre après la P1.

Une piste peut-etre : avant de revenir en mort-vivant, le cadavre se dirige vers le joueur qui lui a mit le coup fatal

**Comment by joshwhedon** [comment]
J'ai prepare un correctif pour. Je sais pas si ca reglera le probleme, je pense que d'une facon ou d'une autre ils arrivent a empecher un sort de se lancer.
