### ISSUE TITLE
Nexus : bug sur Telestra.

### ISSUE THREAD

**Issue by LomeRque** [way-of-elendil/3.3.5#524]
**Description**
En mode normal au Nexus, sur le premier boss du donjon, Grand Magnus Telestra.
Elle a une abilité (dont le nom m'échappe) qui projète le groupe dans les airs pendant un cours instant, puis tout le monde retombe sur le sol et le combat continue.

Le bug constaté est qu'au moment où elle projète le groupe dans les airs, elle disparaît, mais ne réapparaît pas. Impossible donc de la "target" et de la taper. Elle, cependant, peut toujours lancer son sort qui nous projète.

**Comportement attendu**
Telestra projète le groupe dans les airs pendant un cours instant.

Nous avons wype deux fois à cause du bug. Puis nous avons décidé d'avancer dans le donjon. Nous sommes retournés sur Telestra à la fin du donjon, et, à notre grande surprise, Telestra fonctionnait correctement… Nous n'avons pas pu reproduire le bug pour mieux le décrire.

**Comment by Ischjgt** [comment]
id: 47756 [Puits de gravité]  (spell canalisé par le boss)
(Pas réussi à reproduire mais j'ai souvent vu un problème avec ce spell et/ou la Séparation et le Rassemblement du boss)

**Comment by Ischjgt** [comment]
Ça arrive en NM et HM
Le soucis vient de la séparation et du rassemblement, les joueurs tuent les 3 copies de la séparation, le call pour le rassemblement se fait mais le boss revient invisible et continue à cast ses sorts sur les joueurs. (visible en gm on)

Composition du groupe :
DK tank
Retpal
esham
drood équi
Mage feu

Ça c'est quand il a problème :

NPC currently selected by player:
Name: Grand Magus Telestra
SpawnID: 126480, current GUID low: 109.
Entry: 26731.
Faction: 16.
NPC Flags: 0.
DisplayID: 24066 (Native: 24066).
Spawn group: The Nexus - Grand Magus Telestra (ID: 24, Flags: 4, Active: 1)
Compatibility Mode: 0
Level: 82.
EquipmentId: 1 (Original: 1).
Health (base): 242658. (max): 242658. (current): 115840.
Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
Unit Flags: 34111552
* UNIT_FLAG_UNK_6 (0x40)
* UNIT_FLAG_SWIMMING (0x8000)
* UNIT_FLAG_IN_COMBAT (0x80000)
* UNIT_FLAG_NOT_SELECTABLE (0x2000000)
Unit Flags 2: 2048.
Dynamic Flags: 4.
Faction Template: 16.
SpawnTime: Full:0s Remaining:0s
Loot: 30510 Pickpocket: 0 Skinning: 0
InstanceID: 1844
Phasemask: 1
Armor: 10253
Position: 503.878815 93.273643 -16.124645.
AIName:  ScriptName: boss_magus_telestra
React state: AGGRESSIVE
Active AI: boss_magus_telestra::boss_magus_telestraAI

Flags Extra: 268435457
* CREATURE_FLAG_EXTRA_INSTANCE_BIND (0x1)
* CREATURE_FLAG_EXTRA_DUNGEON_BOSS (0x10000000)
MechanicImmuneMask: 617561983
* MECHANIC_CHARM (0x1)
* MECHANIC_DISORIENTED (0x2)
* MECHANIC_DISARM (0x3)
* MECHANIC_DISTRACT (0x4)
* MECHANIC_FEAR (0x5)
* MECHANIC_GRIP (0x6)
* MECHANIC_ROOT (0x7)
* MECHANIC_SILENCE (0x9)
* MECHANIC_SLEEP (0xA)
* MECHANIC_SNARE (0xB)
* MECHANIC_STUN (0xC)
* MECHANIC_FREEZE (0xD)
* MECHANIC_KNOCKOUT (0xE)
* MECHANIC_POLYMORPH (0x11)
* MECHANIC_BANISH (0x12)
* MECHANIC_SHIELD (0x13)
* MECHANIC_SHACKLE (0x14)
* MECHANIC_TURN (0x17)
* MECHANIC_HORROR (0x18)
* MECHANIC_DAZE (0x1B)
* MECHANIC_SAPPED (0x1E)
dmg_multiplier: 13.000000

**Comment by joshwhedon** [comment]
Impossible a reproduire, je mets un correctif pour voir si ca regle le soucis.

**Comment by Amilgaull** [comment]
Je suis intervenu ce jour pour un soucis similaire sauf que cette fois au moment de la séparation, 1 des 3 adds devient invisible pour les joueurs et inattaquable en mode mj (sauf en .die). J'ai fais reset le boss 3 fois et 3 fois le même bug s'est produit. Voici les infos du pnj qui a posé problème
Pour ma part, j'ai tenté de reproduire le bug en solo et malgré une quinzaine de tentative le bug ne s'est pas reproduit.
15:40:33 NPC currently selected by player:
15:40:33 Name: Grand Magus Telestra
15:40:33 SpawnID: 126480, current GUID low: 109.
15:40:33 Entry: 26731.
15:40:33 Faction: 16.
15:40:33 NPC Flags: 0.
15:40:33 DisplayID: 24066 (Native: 24066).
15:40:33 Spawn group: The Nexus - Grand Magus Telestra (ID: 24, Flags: 4, Active: 1)
15:40:33 Compatibility Mode: 0
15:40:33 Level: 82.
15:40:33 EquipmentId: 1 (Original: 1).
15:40:33 Health (base): 242658. (max): 242658. (current): 118594.
15:40:33 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
15:40:33 Unit Flags: 34111552
15:40:33 * UNIT_FLAG_UNK_6 (0x40)
15:40:33 * UNIT_FLAG_SWIMMING (0x8000)
15:40:33 * UNIT_FLAG_IN_COMBAT (0x80000)
15:40:33 * UNIT_FLAG_NOT_SELECTABLE (0x2000000)
15:40:33 Unit Flags 2: 2048.
15:40:33 Dynamic Flags: 4.
15:40:33 Faction Template: 16.
15:40:33 SpawnTime: Full:0s Remaining:0s
15:40:33 Loot: 30510 Pickpocket: 0 Skinning: 0
15:40:33 InstanceID: 694
15:40:33 Phasemask: 1
15:40:33 Armor: 10253
15:40:33 Position: 494.071899 90.309204 -16.124645.
15:40:33 AIName:  ScriptName: boss_magus_telestra
15:40:33 React state: PASSIVE
15:40:33 Active AI: boss_magus_telestra::boss_magus_telestraAI
15:40:33 Flags Extra: 268435457
15:40:33 * CREATURE_FLAG_EXTRA_INSTANCE_BIND (0x1)
15:40:33 * CREATURE_FLAG_EXTRA_DUNGEON_BOSS (0x10000000)
15:40:33 MechanicImmuneMask: 617561983
15:40:33 * MECHANIC_CHARM (0x1)
15:40:33 * MECHANIC_DISORIENTED (0x2)
15:40:33 * MECHANIC_DISARM (0x3)
15:40:33 * MECHANIC_DISTRACT (0x4)
15:40:33 * MECHANIC_FEAR (0x5)
15:40:33 * MECHANIC_GRIP (0x6)
15:40:33 * MECHANIC_ROOT (0x7)
15:40:33 * MECHANIC_SILENCE (0x9)
15:40:33 * MECHANIC_SLEEP (0xA)
15:40:33 * MECHANIC_SNARE (0xB)
15:40:33 * MECHANIC_STUN (0xC)
15:40:33 * MECHANIC_FREEZE (0xD)
15:40:33 * MECHANIC_KNOCKOUT (0xE)
15:40:33 * MECHANIC_POLYMORPH (0x11)
15:40:33 * MECHANIC_BANISH (0x12)
15:40:33 * MECHANIC_SHIELD (0x13)
15:40:33 * MECHANIC_SHACKLE (0x14)
15:40:33 * MECHANIC_TURN (0x17)
15:40:33 * MECHANIC_HORROR (0x18)
15:40:33 * MECHANIC_DAZE (0x1B)
15:40:33 * MECHANIC_SAPPED (0x1E)
15:40:33 dmg_multiplier: 13.000000

**Comment by joshwhedon** [comment]
C'est pas un add c'est le boss lui meme ca, c'est normal qu'elle soit invisible, elle le reste jusqu'a ce que ses 3 adds soient morts. LA question c'est : est-ce que tu es capable de reproduire le probleme, et comment ? Parce que moi je peux pas, et si je peux pas reproduire, je peux pas corriger.

**Comment by joshwhedon** [comment]
Donc, y avait il 3 adds en plus du boss invisible ?

**Comment by joshwhedon** [comment]
Et est-ce que les adds ont reellement ete tues ?

**Comment by Amilgaull** [comment]
Hmm du coup il y avait peut être seulement 2 adds et moi je voyais le boss en 3ème dans la mêlée. En solo non pas réussis à reproduire malgré de nombreux essais
