### ISSUE TITLE
La Cape de démon balafrée

### ISSUE THREAD

**Issue by Maayal** [way-of-elendil/3.3.5#525]
**Description**
Quand on rend la quête [La Cape de démon balafrée](https://woehead.way-of-elendil.fr/?quest=770) au pnj, l'item de quête [Cape griffée par les démons](https://woehead.way-of-elendil.fr/?item=4854#starts-quest) qui permettait de lancer la quête reste dans le sac et n'est pas supprimé.
Mais on ne peut pas relancer la quête, il faut donc juste rajouter que l'item doit être supprimé des sacs.

**Comment by Killyana** [comment]
C'est une cape que tu peux équiper, donc gardée.
