### ISSUE TITLE
BG - Vallée d'altérac 

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#527]
**Description**
- Le compteur de renfort n'apparaît tout simplement pas ( il est peut etre même pas implanté ) - ce qui serai réglé à priori 
- Les tours et cimetières n'apparaissent pas sur la carte à moins qu'ils soient attaqués ou défendus ( en clair au début la carte est totalement vierge et si une tour est attaquée elle apparaît , si une tour est défendue elle disparaît à nouveau et elle reste apparente si elle est détruite )
- Les joueurs n'apparaissent pas sur la carte ( ceux de notre équipe ) à moins qu'ils soient à portée visuelle
- Un joueur qui undermap en étant en fantôme reste undermap et n'est pas tp au cimetière ( il reste bloqué durant tout le bg ) , un joueur vivant qui undermap quand à lui est tp au cimetière rien à signaler sur ça hormis qu'il y en a eu énormément durant ce bg
- Même si il est pas possible de passer au travers on peut tirer à travers tout les éléments de structure et de décors du bg que ça soit une pierre , un arbre , une colline ou même un mur ( on peut tirer à travers une tour même ) - On peut traverser une structure en étant sous l'effet d'un controle , comme un fear )
- Les généraux et maréchaux ne possèdent pas leurs buffs actifs  si la tour associé est encore intacte (ex si la tour aile de glace est active Vanndar et les maréchaux doivent avoir le buff associé à la tour aile de glace ( https://woehead.way-of-elendil.fr/?spell=45831 ) chose qu'ils ont pas ) - En revanche les maréchaux depop bien si la tour associé est détruite.
- Il est possible de désactiver son marqueur jcj durant le bg 

**Captures d’écran / Vidéos**
https://i.goopics.net/jnNjP.jpg ( pour les bugs de carte )
https://i.goopics.net/br3vd.jpg ( pour le wall cast , içi c'est dans le fortin de l'alliance )

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/453
Le problème n'est pas lié à Alterac directement mais au soucis général de maps qu'on a eu cette nuit et il y a 6 jours (Le soir du 12 ou 13 il y a une semaine)

**Comment by joshwhedon** [comment]
Oui la majorite de ces soucis sont du a la map elle meme qui a eu des problemes hier. Je verifie les autres.

**Comment by joshwhedon** [comment]
Pour ce qui est des renforts / tours et cimetieres / joueurs, j'ai pas reussi a reproduire le soucis. Vous pourriez tenter /reload si ca se reproduit et me dire si ca regle le probleme.

**Comment by joshwhedon** [comment]
Les buffs ils les prennent quand ils agro, j'ai teste ils ont bien leur buff a l'agro.
