### ISSUE TITLE
Mode jcj activable au centre de dalaran

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#528]
Si des joueurs s'assoient sur ces bancs (chacun sur un), ils deviennent attaquables l'un envers l'autre tant qu'ils ne bougent pas. Il est donc possible également de demander un duel.
[Chair] GUID: 61542 ID: 191481
23:28:36 X: 5792.430176 Y: 634.476013 Z: 647.245972 MapId: 571
23:28:36 Orientation: -0.715583
23:28:36 Phasemask 1
23:28:36 SpawnTime: Full:5m Remaining:0s

23:28:39 Selected object:
23:28:39 [Bench] GUID: 61593 ID: 191482
23:28:39 X: 5790.020020 Y: 630.806030 Z: 647.286987 MapId: 571
23:28:39 Orientation: -0.549779
23:28:39 Phasemask 1
23:28:39 SpawnTime: Full:5m Remaining:0s

23:31:03 Selected object:
23:31:03 [Chair] GUID: 61361 ID: 191475
23:31:03 X: 5800.709961 Y: 651.379028 Z: 647.138000 MapId: 571
23:31:03 Orientation: -2.216560
23:31:03 Phasemask 1
23:31:03 SpawnTime: Full:5m Remaining:0s

Fonctionnement normal : seul lieu pvp possible dans dalaran se trouve dans les égouts pour duel.

**Comment by Killyana** [comment]
Problème lié au map qui n'envoient pas les données à certains moments

**Comment by joshwhedon** [comment]
Non :D Celui la est super bizarre.

**Comment by joshwhedon** [comment]
Donc ... C'est juste un banc et une chaise. En fait s'assoire dedans change la zone du joueur :D.

**Comment by joshwhedon** [comment]
Ouai non, je corrige pas :D . C'est les maps qui sont foireuses parce que le banc et la chaise sont un peu basses. Du coup quand tu t'assois dessus, ca te met dans la foret en dessous.
Je les rehausse un petit peu pour que ca arrive pas.
