### ISSUE TITLE
Membre du raid CM à la fin de la P1 de Yogg Saron

### ISSUE THREAD

**Issue by ChellGlidewell** [way-of-elendil/3.3.5#529]
**Description**
A la fin de la P1, en arrivant tout juste sur la P2 donc, le main tank du raid a été CM comme s'il n'avait plus de santé mentale (alors qu'on avait juste passé la P1 et qu'il avait donc toute sa santé mentale). De plus, le tank qui fut CM (Liraë) affirme qu'il ne possédait pas le buff de la santé mentale au moment du CM. 

**Étapes de reproduction**
- Ulduar
- 10 joueurs 
- Yogg Saron en mode 4 Gardiens
- Fin de la P1 / Début de la P2
- Composition du groupe : 
  Liraë & Fairïver - Tank 
  Chell, Adamajoana, Djun, Kaiser, Yakikaru & Theron - DPS
  Aylinn & Aliura - Heal

**Comportement attendu**
Aucun CM n'est censé pouvoir exister dès le début de la P2, la santé mentale ne pouvant, normalement, atteindre 0 à ce stade du combat contre Yogg-Saron. 

**Captures d’écran / Vidéos**
Sur le [screenshot](https://cdn.discordapp.com/attachments/695616758211674134/701547487390990457/unknown.png), on peut voir la barre de vie du tank comme étant quasi-pleine ainsi que le membre du groupe qui fut CM : on se trouve donc bien en tout début de la P1

**Comment by joshwhedon** [comment]
Et il avait toujours la sante mentale dans ses buffs ?

**Comment by ChellGlidewell** [comment]
Non, il affirme qu'il n'avait pas le buff santé mentale au moment du CM, alors qu'on venait de passer tout juste en P2

**Comment by joshwhedon** [comment]
Question, est-ce que le probleme a eu lieu pendant la periode ou le serveur avait des soucis divers et varies ? Soucis de monture / pvp / etc ?

**Comment by Fairivier** [comment]
c'était ce soir vers 23h

**Comment by joshwhedon** [comment]
OK, donc tres possible que ce soit lie aux problemes generaux qu'on avait :(. Je verifierai s ije peux voir ce qui s'est passe.

**Comment by joshwhedon** [comment]
Mouai je sais pas comment c'est arrive. Je mets un correctif on verra si ca se reproduit.
