### ISSUE TITLE
Boss: Léviathan des flammes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#53]
**Description**
Serveur prod, pas possible de voir sur le serveur test pour l'instant.
Constaté en 25, surement en 10
Parler au PNJ Gardien du savoir de Norgannon (33686) en combattant le boss en NM permet d'avoir les crédits du mode HM. Le boss agira comme s'il était en mode normal après avoir changé la difficulté.

**Étapes de reproduction**
- Groupe de 2
- 1 personne lance le Léviathan en mode NM
- L'autre parle au NPC 33686 et lance le mode HM
- Le Boss n'utilise que les facultés du mode NM
- Une fois mort, les joueurs en combat ont les crédits du mode HM

**Comportement attendu**
J'attends la réponse d'Asterie

**Ressources additionnelles**
À la demande d'Amandil, j'ai fait .npc set phase 2 sur le PNJ capable de lancer le mode HM sur le léviathan, c'est le même en 10 et en 25.

**Comment by Endalaust** [comment]
Fixé.
