### ISSUE TITLE
Traduction clé fort pourpre

### ISSUE THREAD

**Issue by Maayal** [way-of-elendil/3.3.5#531]
**Description**
La clé du fort pourpre apparaît dans les sacs en anglais bien qu'ayant un client français. Et sur la porte du fort pourpre il est écrit également "Requiert The Violet Hold Key", mais j'imagine que c'est lié

**Comment by joshwhedon** [comment]
Avez vous joue sur d'autres serveurs avec votre client 3.3.5 ? On a fait des tests et pas de soucis. Il est possible que certaines infos soient dans votre cache. Vous pouvez essayer de le vider pour voir.

**Comment by Maayal** [comment]
Je viens de test en vidant le cache le nom de la clé est toujours en anglais

**Comment by joshwhedon** [comment]
Vous avez obtenu le client que vous utilisez ou ?

**Comment by Maayal** [comment]
Alors là je ne me souviens plus si je l'avais dl sur votre site où si je l'avais d'un autre serveur privé (c'est possible que ça soit un ancien)

**Comment by Endalaust** [comment]
Le soucis est lié au client avec des données EN

Récupérer un client FR fixe ce soucis (sous réserve de vider le cache s'il s'agit du client initial avec les données FR injectées manuellement à la place des données EN)

Pour info, notre client est full FR ;)
