### ISSUE TITLE
[Quete] Impossible de rendre/prendre quete

### ISSUE THREAD

**Issue by Broverhood** [way-of-elendil/3.3.5#532]
Bonjour,

Il m'est impossible à certains moment d'accepter une quête ou de rendre la quête. 

En PJ je vous met un screenshot pour un cas où j'avais les item nécessaires pour réussir la quête mais je n'ai pas la possibilité de terminer la quête en parlant au personnage.

J'avais déjà eu le même problème lors de ma première quete ou cette fois il m'était impossible de démarrer la quête.

J'ai essayé d'abandonner la quete et de la redemarrer mais cela ne résoud pas le probleme.

![Wow 2020-04-20 12-16-27-29](https://user-images.githubusercontent.com/64010112/79741536-b7cb9580-8301-11ea-9891-d81ad39b62c7.jpg)

**Comment by joshwhedon** [comment]
Quand tu clique sur l'option dans le menu il se passe rien du tout ?

**Comment by Broverhood** [comment]
> 
> 
> Quand tu clique sur l'option dans le menu il se passe rien du tout ?

J'ai honte... mdr je débute totalement dans wow je ne savais pas qu'il fallait cliquer a l'intérieur de la boite de dialogue. Désolé ! Affaire résolue et merci ! Désolé pour la perte de temps

**Comment by joshwhedon** [comment]
Haha pas de soucis. Bienvenue sur woe :)
