### ISSUE TITLE
quete cuisinier  Le Rokk [Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by domilo2** [way-of-elendil/3.3.5#533]
**Description**les quêtes du maitre cuisinier Le Rokk à Shattrath ne donnent pas les recettes de cuisine. Elles ne sont pas dans les caisses de récompense
Décrivez le problème de façon claire, précise et concise.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement
- Faction / Race / Classe du personnage utilise
- Nom de la quête
- Nom du donneur de quête

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Le taux de drop des caisses de recompense n'est pas de 100%.  Il y a environ 20% de chance d'avoir une recette.
J'ai obtenu une recette apres 4 coffrets de viande.
![image](https://user-images.githubusercontent.com/543699/79743388-d8b6d980-8347-11ea-9ddf-fab4c24b9737.png)

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?item=33857#contains Ce lien vous donnera une idee des taux de drop.
