### ISSUE TITLE
naxx 25 pas de loot sur KT

### ISSUE THREAD

**Issue by Vaccumdias** [way-of-elendil/3.3.5#534]
Bonjour, 

j'ai fait deux fois naxx 25 full boss. et deux fois il n'y avait pas de loot sur kt (le derner boss)

**Comportement attendu**
avoir du loot sur kt ^^

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Est-ce que Kel'thuzad a despawn et respawn en inciblable ?

**Comment by Vaccumdias** [comment]
oui

**Comment by joshwhedon** [comment]
Je mets un autre correctif, en esperant que ca regle le probleme.

**Comment by Vaccumdias** [comment]
problème réglé merci
