### ISSUE TITLE
Personnage injouable après mind control de mobs

### ISSUE THREAD

**Issue by karatoso** [way-of-elendil/3.3.5#535]
**Description**
Dans l'instance l'enclos aux esclaves aux marécages de Zangdarr, certains nagas font des mind control sur un joueur, comportement possible du mob, mais à la récupération du control du joueurs, certaines de ses touches action restent bloquées, et son perso est alors injouable jusqu'à une déco-reco.

**Étapes de reproduction**
- Donjon
L'enclos aux esclaves
- Sur des Nagas trash
- Composition du groupe
5 joueurs en non héroïque en aléa classique

**Comment by joshwhedon** [comment]
Et avec un reload ?

**Comment by karatoso** [comment]
reload ?

**Comment by joshwhedon** [comment]
Un /reload

**Comment by karatoso** [comment]
Pas essayé, mais ca a fait wipe plusieurs fois mon groupe car tankant en nounours je n'avais plus de sorts d'agro, si de sorts de frappe disponibles suite à la fin du mind control

**Comment by karatoso** [comment]
Je n'ai pas pu continuer jusqu'à la fin de l'instance car mon groupe a fini par abandonner ...

**Comment by Killyana** [comment]
Même bug que le CM de la Dame à ICC et probablement tout autre CM, c'est pas un bug d'interface le /reload ne fonctionne pas, il faut decoreco ou mourir et res.

**Comment by joshwhedon** [comment]
Personnellement j'arrive pas a le reproduire. Il faut faire un truc particulier ?

**Comment by Killyana** [comment]
probablement les spells qui sont utilisés par le joueur durant le cm choppent ce bug visuel

**Comment by Pixel-woe** [comment]
Un peu comme sur la Dame Murmemort après CM en 25 ?

**Comment by gtschanz** [comment]
ça m'es encore arrivé aujourd'hui en icc 25h^^ les touches utilisés pendant le cm reste comme verrouillé comme si elles étaient enfoncé impossible à réutiliser pendant le fight

**Comment by gtschanz** [comment]
j'en profite josh vu qu'un gars a ''ré-open'' ce topic; je viens de voir que le bt original est ouvert depuis +6mois et que les joueurs se sont ''adaptés'' néanmoins cela reste désagréable et très pénalisable pour bon nombre de raid (sachant que ce boss reste pénible à passer en hm) y'a-t-il eu de l'avancement du coup ? (étant un boss du raid de fin d'extension du serveur...) donc qqch qui peut être assimilé à relativement prioritaire; à titre perso ça me le fait après chaque CM je m'en ''contente'' mais je prie chaque fois la rng pour pas me manger un cm... car en plus du bug visuel cela n'indique plus à partir de quel moment les techniques sont utilisables; donc les groupes qui ont un gros dps sont largement avantagés car ils peuvent passer le boss sans plusieurs phase de CM; ce que je trouve à l'encontre du blizzlike ou normalement c'est le gameplay qui doit avantager la qualité d'un raid et non la rng si peu de cm car un ilvl stuff plus élevé pour passer le boss plus rapidement avant que chaque joueur se mange plusieurs fois des cm

**Comment by joshwhedon** [comment]
Je sais bien, mais quand on corrige pas de bugs, c'est pas parce qu'on veut pas les corriger, c'est parce qu'on peut pas.

**Comment by Ferro3** [comment]
vérifié le 12/2/22
à priori le fix est ok : les joueurs n'ont plus besoin de déco/reco s'ils ont été CM

**Comment by Ferro3** [comment]
vérifié le 23/2/22 raid icc25hm **échec**
* Pal ret CM (20sec) : 3 mains de libertés (25sec de recharge) https://woehead.way-of-elendil.fr/?spell=1044 au lieu d'une seule possible
* une autre joueuse chaman élémentaire a du déco car elles voyait ses alliés en rouge

ressource : https://wowpedia.fandom.com/wiki/Lady_Deathwhisper

**Comment by Ferro3** [comment]
vu ce jour 21/2/22 raid icc25hm
un war fury a été CM 2 fois, et 2 fois il a été désarmé, plus d'arme du tout équipées le temps des 2 CM

forcement c'est à l'avantage du raid, mais ça n'est pas sensé se passer comme ça
