### ISSUE TITLE
Edc : Gormok L'empaleur, pop de flamme trop élevé

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#537]
Bonjour, le boss gormok l'empaleur en 10n et en 10h fait pop beaucoup trop de flamme, pour espérer le tomber nous sommes obligé de ne jamais arrêter de kite le boss tout autour de la salle.
Après avoir vu des vidéo de l'officiel de l'époque on peut noter que les flammes sont plus rares et que le tank ne bouge quasiment pas
https://www.youtube.com/watch?v=ahp0QJke07s 
https://www.youtube.com/watch?v=JTJrpUkySyE 

La ou le script est bon c'est qu'il en pose bien 2, mais de manière quasi permanente. Sur la première vidéo on peut facilement compter 15 sec avant la première pose de flamme.

Afin de vérifier ça il suffirait d'aller en mode 10hm ou 25hm et de vérifier les pops de flammes, même en ayant un raid bien dispersé.

**Comment by Sarlik** [comment]
Ah et en deuxieme parti de fight, vers les 40% il ne pose plus aucune flamme

**Comment by joshwhedon** [comment]
En deuxieme partie du combat, il  restait des adds sur son dos ? Parce que les flammes dependent du nombre d'adds sur son dos, donc si vous les tuez tous, il y aura plus de flammes.

**Comment by Sarlik** [comment]
Bah du coup c'est sans doute la raison, par contre pour le pop de flamme en boucle c'est pas normal

**Comment by Sarlik** [comment]
Ah bah tu l'as close..

**Comment by joshwhedon** [comment]
Oui je mets un correctif pour le pop des flammes. Il y a le double qui pop je pense a cause d'un bug.
