### ISSUE TITLE
[Boss] Mère Sharaz

### ISSUE THREAD

**Issue by Fufurette** [way-of-elendil/3.3.5#538]
**Description**
Décrivez le problème de façon claire, précise et concise.

Bonjour, 
je vous contacte concernant 2 boss de fin de raid T6 dans le temple noir, Sharaz et Illidan.

Tout d'abord Sharaz.
Pendant le combat en temps normal, ce boss téléporte des gens du raid a un endroit aléatoire de la salle. A ce moment là, la réactivité du raid est synonyme de survie. Or sur ce serveur, dès que nous sommes téléportés, nous nous prenons des dégâts d'ombre toutes les secondes à l’équivalent de 15k pv a peu près. D'accord il faut en théorie un équipement spécifique mais pas a ce point ! ^^
Le reste est je crois bien script.

Je ne sais pas si j'ai décrit tous les bug de ces boss ... je ne vois pas tout derrière mon écran.
Pourriez vous remédiez aux problèmes de ces deux boss svp ? Même ceux pas cités ^^

Merci d'avance.
Lyhadrïne.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc)
- Boss
- Sort en question / Phase du boss en question / Emplacement
- Composition du groupe

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by joshwhedon** [comment]
Je separe le bug en 2.

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/549

**Comment by Fufurette** [comment]
D’accord 

Du coup le tp va être debug ? ^^

**Comment by joshwhedon** [comment]
Oui prochaine maj.

**Comment by Fufurette** [comment]
Quand sera la prochaine MaJ svp ?

**Comment by joshwhedon** [comment]
C'etait ce matin

**Comment by Fufurette** [comment]
Génial !! Le problème est déjà résolu du coup ! 
Merci le staff 🎊🎉
