### ISSUE TITLE
Scientifique de la peste: Technique Gaz abominable

### ISSUE THREAD

**Issue by Sarlik** [way-of-elendil/3.3.5#539]
Bonjour, j'ai remarqué que le monstre Scientifique de la peste (https://woehead.way-of-elendil.fr/?npc=37023#abilities ) possède l'attaque gaz abominable ( https://woehead.way-of-elendil.fr/?spell=69240 ) 
A l'époque d'offi il ne le faisait pas et ne décimait pas le raid. Pour preuve je link le lien de wow head sur ses capacités en 25h, ça m'étonnerait fortement qu'il l'ai nerf d'une extension à l'autre au niveau de ses capacités.
https://fr.wowhead.com/npc=37023/scientifique-de-la-peste#abilities:mode=h25

Merci par avance

**Comment by joshwhedon** [comment]
Effectivement ils auraient jamais du avoir ce sort.
