### ISSUE TITLE
Perte de tous mes envois effectués avec mon autre perso (même compte)

### ISSUE THREAD

**Issue by archy-one** [way-of-elendil/3.3.5#54]
Je viens de perdre plusieurs envois dans ma boite aux lettres alors que ceux-ci étaient visibles quelques minutes auparavant. Les envois ont été effectués avec mon démoniste vers la boite de mon mage. Je ne peux pas expliquer plus. Pouvez vous jeter un coup d'oeil svp .merci

**Comment by Ischjgt** [comment]
Salut, tu peux me contacter sur Discord stp ?
Ischjgt

**Comment by joshwhedon** [comment]
A regler avec intervention mj, pas grand chose a faire cote bugs.
