### ISSUE TITLE
Bug chasseur

### ISSUE THREAD

**Issue by Alashandra** [way-of-elendil/3.3.5#541]
**Description**
A chaque fois que le chasseur se trouve dans une mine ou une grotte, le pet part au dessus de la grotte, aggro nimporte quel mob et disparait

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Chasseur
- Elfe de la nuit
- BM
- petattack
- zone fermée

**Comportement attendu**
Le pet agit comme s'il devait monter des marches, il devrait juste aller en ligne droite sur le mob attaqué

**Comment by joshwhedon** [comment]
Malheureusement ce n'est pas quelque chose qu'on est capable de regler. Certaines maps ne sont pas gerees correctement par les mouvements de pets, et ca cause des problemes :( . Ce bug est au dela de nos competences.
