### ISSUE TITLE
Dégâts de l'ombrefiel (Prêtre ombre)

### ISSUE THREAD

**Issue by Mugiino** [way-of-elendil/3.3.5#544]
**Description**
C'est très simple, il fait de 50 à 70 de dégâts par coup, ce qui fait qu'il est inutile en phase de burst en SP. Je ne connais pas les dégâts exacts qu'il est sensé faire, mais de ce que j'ai trouvé sur internet ça devrait être du 1k+.
**Étapes de reproduction**
Prendre un prêtre ombre de niveau 80, aller sur un mannequin d'entrainement, invoquer l'ombrefiel et constater ses dégâts.

**Comportement attendu**
L'ombrefiel devrait infliger beaucoup plus de dégâts.

**Ressources additionnelles**
https://fr.wowhead.com/spell=34433/ombrefiel#english-comments
"309blank le 2009-04-15 (Mise à jour 3.1.0)

that is actually wrong, the fiend is a great dps cooldown and i highly recommend using it as such, for example on sundial proccs etc. during the heart phase of xt i have seen my fiend hit for upwards of 7k dmg with a shadowcrawl crit. my fiend did around 2k dps or something like that while it was out. that is huge in terms of burst. i also use it mainly as a burst cooldown in arena, considering that it is now a lot easier for the enemy team to control your fiend in a fear/root/cyclone. when you use it while you are on the offensive you maximize your mana gained AND you can add some nice burst".
J'ai trouvé que ça, mais je suis sûr qu'en cherchant plus on trouverait encore plus de sources.

**Comment by Justforsoloq** [comment]
http://www.warcraftmovies.com/movieview.php?id=164387
6mn26-6mn28 ombrefiel frappe à 1K3 sur un rogue (dans la vidéo les dégats sont entre 1k et 1K3+ selon la rési et la classe adverse).
Wrath-Logo-Small Patch 3.1.0 (14-Apr-2009): Health scaling increased. Now receives 30% of the master's spell power. Mana return increased to 5%, up from 4%. The Shadowfiend now returns mana when its melee attacks land, rather than when it deals damage. Movement speed normalized to player movement speed. Tooltip revised.

**Comment by Justforsoloq** [comment]
Ulduar 3.1 Shadowfiend
Shadowfiend's dps scales with your spell power now (receives 30% of caster's spell power in damage). New Shadowfiend ability, Shadowcrawl, teleports the Shadowfiend to an enemy target and increases its damage done by 15% for 5 seconds.
So if you pick a target, cast shadowfiend, then cast Shadowcrawl within 10 seconds to get the most dps out of shadowfiend you will..

for 10 seconds do = 74 dps + (your spell power x 0.2) x 5
for 5 seconds do = 1.15 x (74 + (your spellpower x 0.2)) x 10
(0.2 comes from 30% coefficient divided by 1.5 attack speed)

Pour une auto attack de l'ombrefiel la formule (74 dps + (spell power x 0,2)) x multiplicateur me semble proche de la réalité
ex : 3000 ps
74 + (3000x0,2) = 674
674 x 1.1 (talent ténèbre) x 1.1 (talent 5 tissage d'ombre) x 1.15 (talent forme d'ombre) = 1223 dégâts environ.

**Comment by joshwhedon** [comment]
La formule est pas tout a fait correcte, elle prend mal en compte la vitesse d'attaque et compagnie (et les degats de base, attack power, etc). J'applique un changement prochaine maj.
