### ISSUE TITLE
Trauma - Proc sur le totem du chaman

### ISSUE THREAD

**Issue by saltyrykko** [way-of-elendil/3.3.5#545]
**Description**
Depuis la merge, la trauma (https://woehead.way-of-elendil.fr/?item=50685) proc sur le totem guérisseur du chaman (https://woehead.way-of-elendil.fr/?spell=58757). 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Donjon
- Niveau de difficulté (normal, héroïque, 10 joueurs, 25 joueurs, etc)
- Boss
- Sort en question / Phase du boss en question / Emplacement
- Composition du groupe

**Comportement attendu**
La trauma ne devrait pas proc sur le totem guérisseur car il ne s'agit pas d'un heal direct du chaman, comme expliqué ici https://fr.wowhead.com/item=50028/trauma#english-comments : 

"__JoL won't proc this just like it doesn't proc any other Proc on Heal items (such as Val'anyr's Shields or Althor's Abacus' proc).

The reason is it's not a heal you cast, it's a debuff on the mob that causes other people to heal themselves.

Similarly, **It won't proc off** Vampiric Embrace **or Healing Stream Totem (as the heal results from damage to a mob, or the totem, rather then your character)** or a glyph that adds a separate heal (such as Glyph of Rejuvenation, Glyph of Holy Light, or Glyph of Prayer of Healing).__"

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
https://fr.wowhead.com/item=50028/trauma#english-comments

commentaire de Shadowics (2,195 – 8·29) le 2009-12-26 (Mise à jour 3.3.0)

**Comment by joshwhedon** [comment]
J'ai teste et pas proc une seule fois en 5 minutes. J'ai aussi teste avec tous les talents de shaman restoration (au cas ou ce soit cause par un talent). Et impossible a reproduire de mon cote.
Merci d'ajouter un commentaire si vous trouver ce qui peut le faire proc. Peut etre un talent, ou un autre sort.

**Comment by saltyrykko** [comment]
On m'a dit qu'il y avait une différence entre la trauma nm et la trauma hm (apparemment elle ne proc sur le totem que dans sa version nm). 

Je viens d'essayer à dalaran avec la trauma nm et j'ai réussi à la faire proc assez rapidement avec le totem.

**Comment by saltyrykko** [comment]
J'ai pas de trauma hm par contre alors je peux pas tester
