### ISSUE TITLE
Salles de Sethek : bug sur le tisseur d'ombre Sith

### ISSUE THREAD

**Issue by Muiltak** [way-of-elendil/3.3.5#546]
**Description**
Le 1er boss des salles de Sethekk fait pop ses adds à 90% . Les adds semblent trop puissant (OS du groupe stuff modéré)

**Étapes de reproduction**

problème à chaque combat

**Comportement attendu**
pop des adds à 75%. Les adds devraient probablement être moins puissants.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

![image](https://user-images.githubusercontent.com/64043615/79800261-2d644f80-835c-11ea-818d-f3c87ea4c85c.png)

![image](https://user-images.githubusercontent.com/64043615/79800208-1c1b4300-835c-11ea-8322-74d4ed74cf6a.png)

![image](https://user-images.githubusercontent.com/64043615/79800160-09087300-835c-11ea-9fec-a9085bee338f.png)

**Ressources additionnelles**
 je n'ai pas ça sous la main désolé :) 

Bonne soirée !

**Comment by joshwhedon** [comment]
Effectivement ils font des sorts qu'ils sont pas supposes faire.
