### ISSUE TITLE
Évocation mage 

### ISSUE THREAD

**Issue by zolkon369** [way-of-elendil/3.3.5#547]
Bonjour, j'ai constaté un bug sur l’évocation du mage, en effet parfois l'évocation ne marche tout simplement pas et se cancel toute seule. Après une discussion avec d’autres mages j'ai pu constater que je n’étais pas un cas isolé, je viens donc le signaler ici en supposant que c'est un bug récurrent.

**Comment by Endalaust** [comment]
Hello
Possible de définir les critères de ce "parfois"? :)

**Comment by Justforsoloq** [comment]
Dès que le mage finit d'effectuer un mouvement de déplacement, si il n'attends pas 1 bonne seconde (voir 2) l'évocation se cancel comme si le mage était encore en mouvement.
Exemple : Je jump dès que j'atteris j'évocation, l'évocation va se cancel.

**Comment by joshwhedon** [comment]
1 seconde est tres exagere. J'arrive a reproduire uniquement si je spam le sort pendant que j'arrete mon mouvement / le saut se finit.

**Comment by joshwhedon** [comment]
C'est nouveau ca ou ca le faisait aussi avant ? Parce que quand je regarde le code du serveur avant la merge, ca devrait deja etre un probleme.

**Comment by zolkon369** [comment]
personnellement ça ne m'arrivait pas avant la merge et concernant les critères du critère du parfois je pense que justforsoloq a bien résumé

**Comment by Mugiino** [comment]
A vérifier, mais il me semble que ça le fait aussi sur d'autres canalisations comme le rituel d'invocation du démoniste.

**Comment by Svad19** [comment]
Ça le fait aussi sur le fouet mentale du sp, et ça ne le faisait pas avant la merge.

**Comment by Subimase** [comment]
Bonjour, effectivement, sur mon mage il arrive également que l'évocation se cancel seul, notamment après un déplacement bref. 

Je ferai une vidéo sur mon prochain raid pour vous aider sur la déclaration du bug. 

Sur l'ancienne merge, aucun problème.

**Comment by joshwhedon** [comment]
Je mets un correctif, un peu risque, faudra me dire si vous voyez des soucis niveau comportements de sort (gens qui cast en bougeant, canalisations qui continuent, etc).
