### ISSUE TITLE
[Boss] Illidan

### ISSUE THREAD

**Issue by joshwhedon** [way-of-elendil/3.3.5#549]
La c'est l’apocalypse à partir de la phase 2 ou Illidan s'envole.
Les braises ne tapent pas spécialement fort. Le bug vient des pops de flammes complètement what the fuck dû aux braises. Il y a des flammes de partout ! Même pas a cause des braises car les braises ne bougent quasiment pas. Les flammes pops a cause de rien en fait. Le laser bleu d'Illidan je ne sais pas car on a même pas eu le temps de voir ^^
En revanche, pendant cette phase toujours, Illidan envoie une balle bleu sur quelqu'un du raid en théorie ne dépassant pas les 5k. Et bien je me la suis pris hier ... 15k ! On est d'accord pour dire que c'est un bug également ;)

**Comment by joshwhedon** [comment]
Je crois que les flammes popaient parce que votre tank a fait faire face aux joueurs les flammes d'azzinoth. Du coup au lieu de pop une flamme sous le tank, une flamme pop sous chaque cible touchee par le cone. Je corrige pour que ca n'invoque une flamme que sous le tank.
La balle bleu fait les bons degats.

**Comment by Fufurette** [comment]
Parfait ! 
Bizarre que la bleu fasse autant de dégâts mais je vous crois :) 
Je vais remonter de toute manière des  temple noir parce que je veux le bouclier a transmo ^^ 
Si le combat entre nous et Illidan se poursuit, je reporterais s’il y a d’autres bugs ou non.
