### ISSUE TITLE
Spell: Dents de la mort

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#55]
**Description**
Constaté serveur prod,
https://woehead.way-of-elendil.fr/?spell=56692 Serait à l'origine des crashs d'aujourd'hui (Dimanche 29 Mars).
Quête 13003

**Étapes de reproduction**
Pas réussi à reproduire, testé avec les memes conditions de classe/talents,

À chaque fois que le crash a eu lieu: Quand la wyrm passe à 25%, au lieu du second panneau de spell qui devrait apparaitre, le joueur s'est fait "tp au milieu de nul part, on prend des dégats, on ne peut absolument rien faire, quand le personnage arrive à environ 1% pv, ça crash." (Témoignage du perso Xyriâ)

**Comment by Killyana** [comment]
Le crash est causé par StopCastingCharm()
