### ISSUE TITLE
Eventail de couteau ne casse pas le fufu/vanish des rogues (sauf certaines conditions)

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#552]
**Description**
L'eventail de couteau ne défufu pas les rogues sauf conditions 

**Étapes de reproduction**
Prenez deux rogues, que l'un fufu/vanish l'autre éventail de couteaux et regardez
/!\ : Sur un vanish l'eventail ne réussira jamais à défufu. Cependant sur un fufu normal l'éventail va réussir à défufu via un proc poison. 

**Comportement attendu**
L'éventail doit défufu via les dégats d'aoe (dégâts physiques)

**Ressources additionnelles**
https://wotlk.evowow.com/?spell=51723

**Comment by joshwhedon** [comment]
L'eventail de couteaux est a part. C'est pas une aoe, c'est une
