### ISSUE TITLE
Main de protection pendant un sap/blind sur un allié

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#553]
**Description**
Le paladin peut main de protection ses alliés pendant qu'il est sap ou cécité.

**Étapes de reproduction**
Faites une arène escarmouche, avec un pala d'un côté, un rogue de l'autre. Utilisez cécité ou assommer sur le pala, qu'il main de protection son coep.

**Comportement attendu**
Il ne peut pas main de protection ses alliés pendant un contrôle.

**Ressources additionnelles**
https://classic.wowhead.com/forums&topic=822
 Blessing of Protection: This spell can no longer be cast on others when stunned. It can only be cast on self (to break the stun) under those circumstances.

**Comment by joshwhedon** [comment]
Benediction de protection c'est different de main de protection.

**Comment by Justforsoloq** [comment]
La main de protection c'est le sort qui a remplacé bénediction de protection mais la main de prot quand tu es sap/blind suit la même règle.

**Comment by Justforsoloq** [comment]
https://www.youtube.com/watch?v=xummB-b9nDE
5mn34 : il est blind et ne peut ni main de protection ni main de liberté.
