### ISSUE TITLE
Boss: Valithria Marcherêve

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#555]
**Description**

- Les joueurs ne font pas de resist sur 71941 - [Cauchemars tordus, rank 1 frFR]   (première vidéo)

- Constaté en 25HM, 25NM et 10HM il y a un temps de pause anormal dans les spawn allant de 15 à 30 secondes après qu'un Blazing Skeleton 36791 (j'ai l'impression que cette pause augmente avec le temps)

- Je pense pas qu'il soit possible que plusieurs joueurs prennent le meme stack de Vigueur/Cauchemars dans les portails, sur les 2 vidéos links, il n'y a aucune strat établie pour que les joueurs se rejoignent, et ils sont pas très nombreux à prendre les portails pour justement qu'il n'y en ai pas qui marchent dessus. (Pour reproduire, parce que je me trouve pas très clair, aller à 2/3/4/25 sur une boule en meme temps et tout le monde aura le stack)
71941 - [Cauchemars tordus, rank 1 frFR]
70873 - [Vigueur d'émeraude, rank 1 frFR] [active]

**Comportement attendu**
- Le cham résist au spell https://www.youtube.com/watch?v=Yfr2nowQ7DI&feature=youtu.be&t=93 (en bas à droite, premier nombre, les dégats pris, 2nd, les dégats resists, le total correspond bien à 200x le nombre de stack)
- https://www.youtube.com/watch?v=LEipp3dDR9I 4:47 un blazing apparait, 4:56 un archimage apparait (c'est du 25Nm sur la vidéo)

**Comment by joshwhedon** [comment]
Je mets un correctif pour les timers et le reste. Pour les timers faudra me dire si ca se passe mieux.

**Comment by rommni** [comment]
@Ischjgt  @joshwhedon  Pour le 3ème point il semblerait que ce ne soit pas un bug c'est effectivement abordé rarement mais j'ai trouvé un guide qui en parle: https://www.engadget.com/2010-02-11-raid-rx-healing-valithria-dreamwalker.html
Dans la partie "The portal Team" il est dit :

> Once you're inside the emerald dream and have refreshed your stack, there's two ways to approach the clouds:
Either have everyone get as many clouds as they need before camping beside one and using that last one to refresh their stack before they exit into reality or...
...meet in a preset spot, have a healer marked and just play follow the leader. If players stay close enough to each other, they should all be able to gain the buff.

Il semble donc qu'il soit possible de partager les stacks. A confirmer.

**Comment by joshwhedon** [comment]
Merci.
@Ischjgt  comme le dit souvent un grand homme: You're fake news !

**Comment by rommni** [comment]
De rien, je confirme par ailleurs comme je n’étais pas sur j'ai continué à chercher et j'ai encore trouvé un autre lien qui en parle : https://fallingleavesandwings.wordpress.com/2010/02/04/healing-valithria-as-a-resto-druid/

> Try to coordinate using similarly located portals.  Last night we all went to her tail when we popped back up, and all tried to take portals by her tail when possible.  Your spawn point in the emerald dream will mirror where your portal spawned.  If you are already close in proximity to each other coming into the emerald dream it will be much easier for you to group up with the other healers in the dream and will allow you to share more could bursts.
