### ISSUE TITLE
quête [attraper des torches]

### ISSUE THREAD

**Issue by Grahaams** [way-of-elendil/3.3.5#557]
**Description**
Bonjour,

La quête "attraper des torches" lié à l'event saisonnier Solstice d'été ne fonctionne pas. Lorsque l'on clique sur l'objet "Torches éteintes" à proximité d'un feu de joie du solstice rien ne se passe. Un cooldown s'active sur l'objet mais aucune animation n'est produite. Impossible d'effectuer la quête. 

Lorsque l'on clique sur l'objet Torches éteintes notre personnage est censé lancer une torche dans les airs.

J'ai demandé à d'autres joueurs, ils expérimentent le même problème.

Merci pour votre aide. 
Cordialement,

**Comment by joshwhedon** [comment]
Ces bugs seront corriges quand l'event sera reellement actif. Les scripts des events n'ont pas encore ete passe.
