### ISSUE TITLE
Event : Solstice d'été

### ISSUE THREAD

**Issue by Shendraxqt** [way-of-elendil/3.3.5#558]
**Description**
l’évent du solstice d'été est partiellement pop actuellement (mi avril).
 => sont fonctionnels le dj de l'event (ahune), les quêtes "honorer les flammes" ainsi que les autres quêtes journalières.
=> seules les quêtes "éteindre les flammes" ne sont pas faisable (pas pop il semble)

**Comportement attendu**
l'event est supposé ne pop que sur la période prévue a cet effet (c'est a dire autour du 21 juin environ)

**Comment by Endalaust** [comment]
Ma faute, erreur de frappe sur une démo durant la formation d'un maître de jeu
Event stoppé manuellement.
