### ISSUE TITLE
[Ulduar 10] Léviathan HM s'inflige lui-même des dégâts

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#559]
**Description**
Lorsque le Léviathan est en mode HM, des flammes tournent autour de la salle. Ces flammes sont supposées infliger des dégâts aux véhicules uniquement.
Il semblerait toutefois que le Léviathan lui-même subisse les dégâts créés, se tuant lui-même et donnant du même coup les HFs liés au mode HM très facilement.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Ulduar 10
- Léviathan des flammes, passé en mode héroïque
- Sort en question : je pense qu'il s'agit de [Inferno de Mimiron](https://woehead.way-of-elendil.fr/?spell=62910) mais je n'en suis pas sûr à 100%, ne s'agissant pas d'un spell casté directement par le boss.
- Composition du groupe : 
Ritsuka, paladin
Maula, DK
Helfman, war
Eteranea, hunt
Skadii, chaman
Vaccumdias, warlock
Naolliya, warlock
Bëlikaot, priest
Nuada, mage

A noter qu'il faudra supprimer à l'intégralité de ce groupe les Hauts-Faits suivants obtenus de façon irrégulière : 
[Bombardement orbital (10 joueurs)](https://woehead.way-of-elendil.fr/?achievement=2913)
[Dévastation orbitale (10 joueurs)](https://woehead.way-of-elendil.fr/?achievement=2914)
[Aux chiottes l'orbite (10 joueurs)](https://woehead.way-of-elendil.fr/?achievement=2915)
[Laissez l'orbite tranquille (10 joueurs)](https://woehead.way-of-elendil.fr/?achievement=3056)

**Comportement attendu**
Les flammes n'infligent pas de dégâts au boss.

**Captures d’écran / Vidéos**

![image](https://user-images.githubusercontent.com/63348105/80020174-e3ed3f00-84d8-11ea-8b33-f77147ce1466.png)

**Comment by Ischjgt** [comment]
Salut, c'était quand?

**Comment by Ewilanwoe** [comment]
Dimanche 19/04, aux environ de 21h.

**Comment by Ischjgt** [comment]
Ok, donc c'est valable pour l'autre post aussi mais je laisse néanmoins ouvert au cas où, je testerai quand même, si je suis là cette nuit.
La nuit du Dimanche 19 il y a eu un problème d'ordre général qui concernait un peu tout le royaume, CF les commentaires ici https://github.com/way-of-elendil/3.3.5/issues/527
Il est très probable que tes 2 posts soient une conséquence de ce problème aussi et que tout marche de nouveau comme il faut.

**Comment by Ewilanwoe** [comment]
Oui, c'est aussi ce que je me suis dit, mais je préférais les signaler au cas où ce soit autre chose.

**Comment by Ischjgt** [comment]
Name: Flame Leviathan
Entry: 33113.
62909 - [Inferno de Mimiron, rank 1 frFR]
62910 - [Inferno de Mimiron, rank 1 frFR]

Merci
