### ISSUE TITLE
[Ulduar 10] Assemblée de fer - Maître des runes Molgeim

### ISSUE THREAD

**Issue by Ewilanwoe** [way-of-elendil/3.3.5#560]
**Description**
Lors de la rencontre contre l'Assemblée de fer, le [Maître des runes Molgeim](https://woehead.way-of-elendil.fr/?npc=32927) pose régulièrement au sol une [Rune de puissance](https://woehead.way-of-elendil.fr/?spell=61974) constituant un buff conséquent (+50% de dégâts infligés) pour le raid et pour les ennemis si ils sont laissés dedans. Normalement, cette rune reste active durant une minute. 

Dans le cas observé, la rune ne restait qu'une seconde avant de disparaître, ne pouvant aider ni le boss, ni le raid. Le problème n'a pas été constaté sur sa deuxième rune ( [Rune de mort](https://woehead.way-of-elendil.fr/?spell=62269) )

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Ulduar 10
- Assemblée de fer - Maître des runes Molgeim
- [Rune de puissance](https://woehead.way-of-elendil.fr/?spell=61974) durant toutes les phases.

**Comportement attendu**
La rune de puissance reste durant une minute et augmente les dégâts infligés de tous ceux restant dedans, boss comme joueurs.

**Comment by Ischjgt** [comment]
C'était quand ?

**Comment by Ewilanwoe** [comment]
Dimanche 19/04, aux environs de 21h30.

**Comment by Ischjgt** [comment]
Constaté aujourd'hui mode 10 et 25, la rune reste jusqu'à qu'un joueur se pose dessus
61974 la marque au sol
id: 64320 [Rune de puissance] le buff reçu

**Comportement attendu**
La rune au sol ne doit pas partir quand un joueur reçoit le buff

(et merci)
