### ISSUE TITLE
Requinquage

### ISSUE THREAD

**Issue by Mougnok** [way-of-elendil/3.3.5#561]
**Description**
Le buff "Requinquage" bug, il est visible dans les buff mais ne rend pas de mana dans la pratique.

Sur les sreen ci-dessous, on peut voir que le buff est actif mais ne donne pas de mana d'apres le skada "mana récupéré".

![WoWScrnShot_042220_204951](https://user-images.githubusercontent.com/63776743/80021932-945c4280-84db-11ea-9f99-263fb74f464b.jpg)
![WoWScrnShot_042220_205045](https://user-images.githubusercontent.com/63776743/80021936-96260600-84db-11ea-9b94-96cb5866f079.jpg)

**Comment by joshwhedon** [comment]
Tu avais pas plusieurs buff de regen mana ? Parce que je crois que ca se stack pas non ?

**Comment by joshwhedon** [comment]
Ca a ete teste par un membre de l'equipe dans plusieurs groupes de raid, sans aucun soucis. Merci de donner plus d'information si le probleme persiste. Dans l'immediat ce probleme ne peut pas etre reproduit.
