### ISSUE TITLE
Dispell offensif n'enlève pas le glèbe

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#562]
**Description**
Le dispell offensif du prêtre n'enlève pas le totem de glèbe (à voir avec celui du chaman)

**Étapes de reproduction**
Prenez un prêtre, un chaman avec un buff, posez le glèbe faites un dispell et regardez.

**Comportement attendu**
Si il y a un buff à debuff, le dispell offensif casse le glèbe.

**Ressources additionnelles**
https://wotlk-twinhead.twinstar.cz/?spell=8177
https://wotlk-twinhead.twinstar.cz/?spell=43577

**Comment by joshwhedon** [comment]
Et il est redirige le dispel ?
