### ISSUE TITLE
Bug dégât druide équilibre sur icc 

### ISSUE THREAD

**Issue by marieqt** [way-of-elendil/3.3.5#564]
**Description**
Le feu stéllaire et colère ne prennes pas en compte le buff 30 %
mes degat sous full proc sont les même sur halion (34k critique sur feu stéllaire ) que dans icc avec le buff 30% 

**Étapes de reproduction**
-  Druide équilibre 
-  elfe de la nuit
- Équilibre 
- Feu stéllaire / Colère 
-  Halion/ icc
- Full 277/284
- sous full proc 

**Comportement attendu**
Augmenter les dégâts de feu stéllaire et colère  dans icc

**Comment by Ischjgt** [comment]
Le buff est fonctionnel pour ces 2 spells, si tu penses qu'il y a un soucis, ce n'est pas de ça.
