### ISSUE TITLE
Range des rebonds de la salve du rsham

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#565]
Observé : 
La portée est des rebonds de la salve du rsham est beaucoup trop grande : au moins supérieur à 20m.

Attendu : 
https://wowwiki.fandom.com/wiki/Chain_Heal : "Jump distance increased by 25% to 12.5 yards." au patch 3.2. (Pas bien saisi la conversion yard/mètre : 12.5 yards = 11.43 mètre selon google, mais les distances en yard indiquées sont les mêmes que celles en mètre dans le jeu).

**Comment by Limoustique** [comment]
Dans WoW uniquement 1 yard = 1 mètre

**Comment by joshwhedon** [comment]
Le rebond ou le sort de base ? Parce que le sort de base a une portee de 40 yards, mais les cibles suivantes c'est 12.5 yards. J'ai verifie ca a l'air bon.
En gros, premiere cible tu peux lancer a 40 yards, mais les rebonds eux meme n'iront pas plus loin que 12,5 yards

**Comment by toitit** [comment]
![Annotation 2020-04-24 015839](https://user-images.githubusercontent.com/48948466/80160951-3ad54000-85cf-11ea-826f-13db5eaa095c.png)

Là avec le chaman (à gauche) je lance une salve sur le druide (au fond) qui rebondi sur le démo (à droite) puis s'arrête.

- Y'a au moins 30 yards entre le druide et le démo, donc il ne devrait pas y avoir de rebond.
- Il devrait y avoir un rebond entre le démo et le chaman puisqu'ils sont suffisamment proches (du moins bien plus proche que le druide et le démo).

**Comment by joshwhedon** [comment]
Pour une raison que j'ignore, Trinity, pour tous les chain (chain lightning, heal, etc) fait le calcul suivant:
maxRange = range * numberoftarget
Du coup ... Ca peut aller super loin lol.
Je vais mettre un correctif pour retirer ca, tenez moi au courrant si c'est pas valid.
