### ISSUE TITLE
NPC: Alliance/Horde Infra-green Bomber - Une nouvelle cible/Mener la charge

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#567]
**Description**
32512 - [Alliance Infra-green Bomber]
31838 - [Horde Infra-green Bomber] 
- Cas où le joueur quitte totalement le véhicule quand il change de places en utilisant 
59196 - [Tourelle antiaérienne, rank 1 frFR]
59194 - [Soute à bombe, rank 1 frFR]
59193 - [Ingénierie, rank 1 frFR]
C'est facile à reproduire mais ça a l'air assez aléatoire
J'ai l'impression que ça arrive quand on lance un des 3 spells et que le véhicule vient de faire un virage

- Spell : Fusée antiaérienne, je sais pas lequel c'est :( 
> les tirs explosent à la portée maximale et non sur les cibles (les missiles traversent les gargouilles).

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/478

**Comment by Ischjgt** [comment]
Les 2 points sont toujours là, 
- c'est un peu plus dur de tomber du véhicule j'ai l'impression, ça arrive quand même assez souvent pour que ce soit notable et génant, de façon aléatoire
- Les spells anti aériens ne touchent pas les gargouilles, ils les touchent seulement quand celle-ci partent en evade (Avec marqué "Evite" du coup - elles peuvent quitter le combat ?) 

À cela s'ajoute 
- 61093 - [Combattre le feu, rank 1 frFR] Le spell n'étant pas l'incendie

**Comment by joshwhedon** [comment]
Voir https://github.com/way-of-elendil/3.3.5/issues/478 deja sicnale
