### ISSUE TITLE
Boss: Malygos

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#569]
**Description**
- 57090 - [Revivifier, rank 1 frFR] : **Si la cible a 0 de point de combo**, lancer ce spell n'en donne pas
- Cas où le boss devient inciblable et ne fais rien en passage de p3 (phase sur les dragons)
Pas réussi à reproduire mais j'avais ça :
Name: Malygos
Entry: 28859.

* UNIT_FLAG_UNK_6 (0x40)
* UNIT_FLAG_IN_COMBAT (0x80000)
* UNIT_FLAG_NOT_SELECTABLE (0x2000000)

**Comment by joshwhedon** [comment]
Les dragons ont ete invoque ? A quel moment du passage en p3 c'est arrive ?

**Comment by Ischjgt** [comment]
En fait je crois que le boss reset

**Étapes pour reproduire**
- Passer le boss en P2 lorsqu'il fait id: 55853 [Vortex]
