### ISSUE TITLE
NPC: Omor l'Intouché

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#570]
**Description**

17536 -  [Nazan]
17307 - [Vazruden the Herald]

- Nazan descend déposer Vazruden quand les 2 factionnaires sont morts OK
- On voit les  2 boss despawn arrivés à tard, puis tout de suite après Nazan réapparait, remonte et ne redescends pas

**Comportement attendu**
https://www.youtube.com/watch?v=x6y0Ntiou7g
- Nazan descend déposer Vazruden quand les 2 factionnaires sont morts
- Nazan remonte, les joueurs combattent Vazruden
- Quand Vazruden est mort, Nazan descend

**Comment by Killyana** [comment]
fixé par https://github.com/TrinityCore/TrinityCore/commit/8ac83744293afe297bce2597107bc5da5445ccbb

**Comment by joshwhedon** [comment]
Ouai je suis en train de mettre leur script entier. Plein de modifs custom qui sont probablement plus valides dans le notre.
