### ISSUE TITLE
[Quetes] [Joug] Journalière / hebdomadaire du jour d'hiver

### ISSUE THREAD

**Issue by rommni** [way-of-elendil/3.3.5#572]
**Description**
J'ai réalisé hier les quêtes du joug d'hiver et je ne peux pas les refaire aujourd'hui, d'autres joueurs présents depuis plus longtemps sur le serveur et les faisant régulièrement m'ont informé qu'ils pouvaient les faire sur un format hebdomadaire (1 fois par semaine), or depuis le patch 3.2.2 et jusqu'au patch 4.0.3a ces quêtes sont sous un format journalier, comme indiqué dans les "patchs changes" de ce lien wowWiki : https://wowwiki.fandom.com/wiki/Wintergrasp_quests

**Liste des quêtes concernées:**
- La défense du siège (A)(13222) : https://woehead.way-of-elendil.fr/?quest=13222
- La défense du siège (H)(13223) :https://woehead.way-of-elendil.fr/?quest=13223
- L'arrêt du siège (A)(13186) : https://woehead.way-of-elendil.fr/?quest=13186
- L'arrêt du siège (H)(13185) : https://woehead.way-of-elendil.fr/?quest=13185
- Pas de pitié pour les sans pitié (A)(13179 ) : https://woehead.way-of-elendil.fr/?quest=13179
- Tuez-les tous ! (H)(13180 / 13178) : https://woehead.way-of-elendil.fr/?quest=13180  /  https://woehead.way-of-elendil.fr/?quest=13178
- Sabotage au sud (A)(13538) : https://woehead.way-of-elendil.fr/?quest=13538
- Abattre les tours (H)(13539) : https://woehead.way-of-elendil.fr/?quest=13539
- Victoire à Joug-d'hiver(A)(13181) : https://woehead.way-of-elendil.fr/?quest=13181
- Victoire à Joug-d'hiver(H)(13183) : https://woehead.way-of-elendil.fr/?quest=13183

Plus aléatoirement chaque jour une quête Alliance parmi:
- Une herbe rare (13156 / 13195) : https://woehead.way-of-elendil.fr/?quest=13156 / https://woehead.way-of-elendil.fr/?quest=13195
- Des os et des flèches (13154 / 13196) : https://woehead.way-of-elendil.fr/?quest=13154 /  https://woehead.way-of-elendil.fr/?quest=13196
- Alimenter les démolisseurs (236 / 13197) : https://woehead.way-of-elendil.fr/?quest=236 / https://woehead.way-of-elendil.fr/?quest=13197
- Protéger les guerriers (13198  / 13153) : https://woehead.way-of-elendil.fr/?quest=13198 / https://woehead.way-of-elendil.fr/?quest=13153

Et une quête Horde parmi:
- Guérison par les plantes (13194 / 13201) : https://woehead.way-of-elendil.fr/?quest=13194 / https://woehead.way-of-elendil.fr/?quest=13201
- Des os et des flèches (13193 / 13199) : https://woehead.way-of-elendil.fr/?quest=13193 / https://woehead.way-of-elendil.fr/?quest=13199
- Alimenter les démolisseurs (13191  / 13200) : https://woehead.way-of-elendil.fr/?quest=13191 / https://woehead.way-of-elendil.fr/?quest=13200
- Ensorceler les Murs (13202) / Surveiller les murs (13192) : https://woehead.way-of-elendil.fr/?quest=13202 /  https://woehead.way-of-elendil.fr/?quest=13192

Beaucoup de quêtes ont plusieurs Ids je suppose que c'est la version lorsque la faction est en attaque et celle lorsqu'elle est en défense, à vérifier si les ids sont tous utilisés :)

**Comment by joshwhedon** [comment]
Apparament c'est un fake, quelqu'un a edite le wowwiki mais y'a pas de sources la dessus dans les patch notes ailleurs.
https://github.com/SunwellTracker/issues/issues/2272
https://www.wowhead.com/patchnotes=3.2.2
https://www.mmo-champion.com/threads/661861-3-2-2-Patch-Notes
https://wowwiki.fandom.com/wiki/Patch_3.2.2
https://www.engadget.com/2009-09-24-wow-patch-3-2-2-impact-on-the-battlegrounds.html
https://wow.allakhazam.com/wiki/Patch_3.2.2

Desole que tu te sois emmerde a lister toutes les quetes :( .
J'ai aussi tente de chercher patch 3.2.2 sur google autour de la date de sortie, et rien a part ce post de wowwiki. Malheureusement wowwiki est edite par un peu tout le monde donc faut verifier un peu partout les sources :(

**Comment by rommni** [comment]
Effectivement désole my bad je me suis arrêté à la première source.

**Comment by joshwhedon** [comment]
Pas de soucis, je me suis fait avoir aussi plusieurs fois :) .

**Comment by joshwhedon** [comment]
Et au moins tu essaie de fournir des sources, c'est mieux que rien du tout ca fait un bon point de depart.
