### ISSUE TITLE
Profondeur de Rochenoire, bug event de l'arène

### ISSUE THREAD

**Issue by Drawn79** [way-of-elendil/3.3.5#575]
Description du bug :
L'event de l'arène au début de l'instance Profondeur de Rochenoire est bug. Le PNJ : Juge Supérieur Mornepierre s'active quand on rentre dans l'arène. Il ouvre ensuite la première grille pour tuer les mobs mais une fois ces derniers tués, le PNJ disparaît et on se retrouve alors bloqué dans l'arène avec les 4 grilles fermées, ou en tout cas celles pour sortir de l'arène.

Étapes de reproduction :
Il suffit d'entrer dans le cercle au centre de l'arène (Cercle de la loi) pour lancer l'event.
L'event bug après le premier pop de mobs.

Comportement attendu :
De mémoire l'event se déroule en 3 ou 4 vagues d'ouverture de grilles avec le pop du boss sur la dernière vague.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Ischjgt** [comment]
J'ai pas réussi à reproduire solo

**Comment by joshwhedon** [comment]
Je sais pas ce qui s'est passe. Peut etre que certains des adds sont passes sous la map pour une raison que j'ignore ? Je mets un fix pour que l'event reset en cas de despawn des adds.
