### ISSUE TITLE
Course Gueule de Dragon : Capitaine Fracasse-Ciel[Class / Sort / Boss / ...] Description courte du bug

### ISSUE THREAD

**Issue by Anex83** [way-of-elendil/3.3.5#576]
Le but de cette quête est de suivre le dit Capitaine sans tomber. Cependant, que l'on perde ou que l'on gagne, il relance la course sans arrêts? De ce fait, si l'on gagne, bien qu'il dise que nous l'avons battu, il relancera la course, et empêchera la quête de se finir correctement.

-Vallée D'Ombrelune, Campement des Gueules de Dragon.
- Alliance / Elfe de la Nuit / Guerrier
- Course Gueule de Dragon : Capitaine Fracasse-Ciel
- Capitaine Fracasse-Ciel

Nous sommes sensé le suivre lors de la course sans tomber, et une fois cette course réussie, le capitaine devrait normalement retourner à sa place sans en bouger, et nous annoncer en tant que vainqueur, ce qui confirmerait la quête.

**Captures d’écran / Vidéos**
( Non disponibles )

**Ressources additionnelles**
https://fr.wowhead.com/quest=11071/course-gueule-de-dragon-capitaine-fracasse-ciel
https://fr.wowhead.com/npc=23348/capitaine-fracasse-ciel

**Comment by joshwhedon** [comment]
Ca le fait avec toutes les courses ? Ou justce celle la ?

**Comment by Anex83** [comment]
Juste celle-ci Envoyé depuis mon téléphone Huawei-------- Message original --------De : joshwhedon <notifications@github.com>Date : sam. 25 avr. 2020 à 01:53À : "way-of-elendil/3.3.5" <3.3.5@noreply.github.com>Cc : Anex83 <lorceta@gmail.com>, Author <author@noreply.github.com>Objet : Re: [way-of-elendil/3.3.5] Course Gueule de Dragon : Capitaine Fracasse-Ciel[Class / Sort / Boss / ...] Description courte du bug (#576)
Ca le fait avec toutes les courses ? Ou justce celle la ?

**Comment by joshwhedon** [comment]
Pas reussi a reproduire de mon cote. Je mets des modifs mais je sais pas si ca aura un impacte. Tu pourras reessayer aujourd'hui et voir si ca marche. Si ca marche pas il faudra surement que tu montre a un gm.
