### ISSUE TITLE
Reputation: The Aldor/the Scryers

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#579]
**Description**
>Dès que je quitte le jeu, je redeviens en guerre avec les clairvoyants alors que je suis désormais amicale. 

(L'icone en guerre est grisée)
D'après Eridium : https://github.com/TrinityCore/TrinityCore/issues/23290
Je le poste ici sans savoir si c'est utile

**Comment by joshwhedon** [comment]
Je mets en place un correctif, cela dit ca affectera uniquement les nouveaux joueurs. Pour corriger pour les anciens joueurs qui ont deja le probleme, il faut les passer hai, et ensuite les remettre au niveau de reputation ou ils etaient.
