### ISSUE TITLE
Profondeur de Rochenoire - Event de l'arène

### ISSUE THREAD

**Issue by Drawn79** [way-of-elendil/3.3.5#582]
**Description**
Toujours le problème dans les Profondeur de Rochenoir pour l'event de l'arène au Cercle de la loi. Le PNJ : Juge Supérieur Mornepierre disparait au moment d'ouvrir la 2e grille pour libérer la 2e vague de mobs. Toutes les grilles restent fermées, impossible de sortir de l'arène.
Bug confirmé par 2 personnes avec des lvl 80 solo

**Étapes de reproduction**
J'ai essayé plusieurs configurations et à chaque fois le bug se produit lorsque l'event se lance, impossible de faire pop la 2e vague de mobs :
 - En solo avec un mon lvl 80,
 - Dans un groupe avec juste mon lvl 80 qui rentre et les autres membres lvl 50 qui restent à l'entrée de l'instance,
 - Tous ensemble (1 lvl 80 et 2 lvl 50) qui rentrent ensemble dans l'arène.
 - Avec ou sans la quête de l'héritage sombrefer pour obtenir la clé, pas de différence.

**Comportement attendu**
Le PNJ Juge Supérieur Mornepierre doit continuer à faire pop des vagues d'add jusqu'à permettre l'accès au reste de l'instance.

Bug testé hier (24/04/2020) et aujourd'hui (25/04/2020) vers 16h dans les 2 cas.

**Comment by Endalaust** [comment]
Soucis toujours présent :(

**Comment by Ischjgt** [comment]
**Étapes pour reproduire**
- Lancer l'event
- Se promener dans la salle où les premiers adds on spawn quand la grille est ouverte
- Quand la vague de petits adds est tuée, le juge réapparait mais reste bloquer à :
Juge Supérieur Mornepierre crie : Hé hé ! Je parie que vous ne vous attendiez pas à ça !

10096 - [Juge Supérieur Mornepierre]
