### ISSUE TITLE
[PvP] Ténacité du Joug d'Hiver active en bg rejoint pendant le joug

### ISSUE THREAD

**Issue by Garhontar** [way-of-elendil/3.3.5#584]
**Description**
J'ai rejoint un champ de bataille nouvellement ouvert alors que je participais à la bataille du Joug-d'Hiver. Arrivé dans le champ de bataille (un Oeil du Cyclone), j'ai continué à être affecté par le buff de Ténacité du Joug d'Hiver, avec une augmentation sensible de mes points de vie (donc pas juste un bug graphique)

**Étapes de reproduction**
-Participer à la bataille du Joug d'Hiver, avec sa faction en sous-nombre de sorte qu'elle soit affectée par le buff Ténacité, et alors qu'on est dans le même temps en recherche de champ de bataille.
-Entrer dans un bg qui proc alors que la bataille du Joug est encore en cours.

**Comportement attendu**
Le buff Ténacité du Joug ne devrait pas s'appliquer alors qu'on change de contexte de PvP

**Comment by joshwhedon** [comment]
Pas pu reproduire mais je mets un correctif qui devrait empecher ca. Le buff est reste longtemps ? Meme apres le bg ?

**Comment by Ischjgt** [comment]
Ça s'est reproduit aujourd'hui, à chaque fois que le joueur rejoignait un BG en étant au joug en cours, il avait la tena, quand le joug a fini, il l'a perdu (dans le BG)

**Comment by joshwhedon** [comment]
Vous avez le message qui vous dit que vous avez quitte le joug ?

**Comment by Ischjgt** [comment]
> je ne me souviens pas très bien, mais il ne me semble pas avoir vu le msg

**Comment by joshwhedon** [comment]
Faudrait me confirmer ca parce que ca change tout si le message est pas apparu.

**Comment by Ischjgt** [comment]
J'ai eu le message perso.
J'attends de retest dans de meilleures conditions (genre dans un véhicule etc) pour t'apporter plus d'infos
