### ISSUE TITLE
Porte-peste d'ébène

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#585]
**Description**
la maladie disparait avec 2 dk impie dans le raid, en gros ils se supprime la peste alors que cela ne devrai pas être le cas.

**Étapes de reproduction**
- Classe : DK 
- Race: orc
- Spécialisation: Impie
- Sort / Talent : Porte-peste d'ébène
- Circonstances (Donjon, Raid, PvP, autre)

**Comportement attendu**
Elle devrai être active pour tout les dk impie présent dans le BG/Raid et ne pas se supprimé.

**Comment by Elahbienscript** [comment]
![WoWScrnShot_042520_203534](https://user-images.githubusercontent.com/63306323/80287882-5574f980-8734-11ea-8003-b38f50b22d0f.jpg)
les maladies sont présente mais la peste d'ébène.

**Comment by Elahbienscript** [comment]
Ou encore : 
![WoWScrnShot_042520_211042](https://user-images.githubusercontent.com/63306323/80288622-63794900-8739-11ea-8b47-27bdceee66ff.jpg)
![WoWScrnShot_042520_211046](https://user-images.githubusercontent.com/63306323/80288625-670cd000-8739-11ea-91d8-f8641419d8b8.jpg)
Ca rend fou en raid ca nique complettement ton cycle dps vu que tu doit la refresh et tu perd 13% de dmg sur tes frappe de fléau

**Comment by Ischjgt** [comment]
Sur ton premier screen le debuff porte peste est présent...
Sur le deuxième je dirais qu'un druide équi a prit la main

**Comment by Ischjgt** [comment]
Et je viens de test, rien est supprimé.

**Comment by Elahbienscript** [comment]
non c'est bien le deuxieme dk impie, avec sa pestilence qui l'enlève on a fait des test, c'est remplacer mais ca ne devrai pas l'être
je perd 13% de dmg sans la maladie

**Comment by Elahbienscript** [comment]
vue que c'est pas ma maladie

**Comment by Elahbienscript** [comment]
on devrai pouvoir être 5 dk impie et avoir les 5 la maladie présente sur le boss

**Comment by Ischjgt** [comment]
Le debuff ne cumule pas pas, c'est 13% dégats magiques pour tout le raid. Et le dk impie n'est pas la seule classe qui possède ce genre de débuff

**Comment by Elahbienscript** [comment]
t'as pas compris ce que je te dis, ca ne se cumule pas, mais la maladie DOIT resté présente sur le boss, le drood me l'enlève pas, le démo non plus, c'est juste le dk impie qui la prend donc je doit pesti comme un triso pour l'avoir

**Comment by Ischjgt** [comment]
Patch 3.1.0 (14-Apr-2009): Multiple death knights can now use this debuff against a target without overwriting each other.

**Comment by Elahbienscript** [comment]
aaaah yes merci ^^

**Comment by joshwhedon** [comment]
Heu je crois que ca change rien au dps de toute facon :D . Elle marche pour toutes les maladies de tout le monde.

**Comment by LLPPAA** [comment]
Le bonus de la peste globale peut être.
Mais pour les attaques/talent qui dépendent du nombre de maladie (frappe du fléau, frappe de sang, frappe de mort, lame incrusté de sang), bah ça fait des dégats/soins en moins puisque seules les maladies du DK lui même sont comptées pour ses capacités :/
Du coup, si le DK A pose ses maladies, il en a trois sur la cible, et quand le DK B pose les siennes, il en a trois pour lui, mais le DK A n'en a plus que deux d'actives (vu que la peste d'ébène du DK A disparait complètement au profit de celle du DK B).
