### ISSUE TITLE
Instance: Stratholme

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#586]
**Description**
[Doodad_LargePortcullis06] GUID: 6911 ID: 175374
La porte se ferme quand l'engage se fait dans la place du massacre mais ne se réouvre pas après un wipe

(J'ai attendu un bon quart d'heure, avant la merge je crois qu'il y avait un timer pour qu'elle se réouvre, pas trouvé d'infos :( )

**Comment by joshwhedon** [comment]
Meme avant la merge ca marchait pas je pense, y'a une typo dans le code.

**Comment by Ischjgt** [comment]
"On a wait 10min devant la grille , J'ai envoyé un message Discord , On a attendu encore 10min [] . Donc 20 minutes d'attente environ ."

**Comment by joshwhedon** [comment]
Ils ont wipe sur quoi ?

**Comment by joshwhedon** [comment]
Teste, pas pu reproduire, la porte se rouvre quand un mob ou le boss evade.
