### ISSUE TITLE
[Joug] Tour insensible

### ISSUE THREAD

**Issue by rommni** [way-of-elendil/3.3.5#587]
**Description**
Aujourd'hui au joug d'hiver, en position défenseur (horde) la tour Guetteflamme (Sud-est) était insensible à toutes attaques des démolisseurs (pas eu le temps de tester avec d'autres engins). Il devient donc impossible de détruire la tour, les 2 autres ont été détruites sans problèmes. Il semblerait que ce bug arrive de temps en temps, je ne sais pas si c'est toujours la même tour ou si cela peut changer. Je n'ai pas trouvé de schéma précis de reproduction, si jamais d'autres personnes ont des infos hésitez pas à compléter.

**Ressources additionnelles**
Tour guetteflamme: https://woehead.way-of-elendil.fr/?object=190358

**Comment by joshwhedon** [comment]
Possible qu'elle ait ete deja detruite mais qu'elle apparaissait comme indemne ? Elle etait detruite sur la carte ?

**Comment by rommni** [comment]
Nop elle était intacte (visible sur la carte et par le bonus) de plus j'étais seul sur les 25 premières minutes de la bataille donc sur que personne n'y ait touché

**Comment by joshwhedon** [comment]
Mouai on y peut probablement rien. Aucune idee comment reproduire, aucune idee pourquoi cette tour.

**Comment by rommni** [comment]
Dommage, est ce que ca peut servir au cas ou ca se reproduise que j'appel sur l'inter un MJ/Dev de façon à jeter un coup d'oeil à ce qui pourrait la faire planter ou ça ne se verrait pas?

**Comment by joshwhedon** [comment]
Peut etre, mais j'en doute. On peut toujours regarder

**Comment by Ischjgt** [comment]
Quand le bug arrive la tour insensible peut se détruire avec un véhicule de la faction qui ne détient PAS le joug (ce qui devrait être l'inverse, pour ça que les joueurs qui possèdent le joug n'arrivent pas à détruire la tour est).

Si le joug est tenu par l'alliance, la tour est horde, mais quand le bug arrive il semble que la tour soit donc de la faction opposée.

Les buffs de dégats sont néanmoins répartis correctement

**Comment by Ischjgt** [comment]
Je crois que le précédent commentaire que j'ai mit est faux, quand c'est arrivé de nouveau aujourd'hui ce n'était plus le cas donc je sais pas je devais être un peu fatigué.

**Étapes pour reproduire**
- Il faut que personne n'ait rejoint a aucun moment le joug précédent. 
- Le suivant, la tour est aura un problème.
=> quand cela arrive les Wintergrasp Tower Cannon 28366 de la tour qui bug sont phasés et ont ces flags là, en plus de ce sur les autres tours qui fonctionnent correctement
UNIT_FLAG_NON_ATTACKABLE (0x2)
UNIT_FLAG_NOT_SELECTABLE (0x2000000)
Les canons des tours bugés sont de la faction 35 alors que les autres sont 1735.

**Comment by joshwhedon** [comment]
Je mets un correctif prochaine maj, aucune idee si ca changera quoi que ce soit. A voir

**Comment by Ischjgt** [comment]
Le problème est toujours là. Même si les conditions semblent un peu hasardeuses, ça reste assez facile à reproduire au final. il est assez aisé de savoir quand la tour va poser problème ou non

**Comment by joshwhedon** [comment]
Si je peux pas reproduire je peux pas corriger. Et j'ai aussi essaye la methode ci dessus sans succes. Merci de reouvrir le ticket quand une methode de reproduction est fourni

**Comment by Ischjgt** [comment]
[Wintergrasp Horde Banner] GUID: 76049 ID: 192502
[Wintergrasp Fortress Door] GUID: 255186 ID: 191810

Ça le fait seulement pour ces 2 Gob apparemment

**Étapes pour reproduire**

- Entrer dans le joug et rester 15 minutes à l'opposée de la tour est (j'ai pas le temps exact)/de la porte principale
- Après le temps écoulé, aller à la tour/peter les murs nécessaires pour pouvoir endommager la porte principale
- Taper le gob, ça marche pas

=> Je me suis rappelé d'un ticket que j'avais fait - que je retrouve plus - où les portes à Mortemines se fermaient de la même façon si on se plaçait trop loin trop longtemps
=> Si les conditions sont remplies, la tour/la porte devient insensible pour tout le monde jusqu'à la fin de la bataille _(en cours de test j'edit dans 15 min :p)_
