### ISSUE TITLE
Spell: Typhon

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#588]
**Description**
- L'animation ne se voit pas toujours

61384 - [Typhon, rank 5 frFR]
53226 - [Typhon, rank 4 frFR]
53225 - [Typhon, rank 3 frFR]
53223 - [Typhon, rank 2 frFR]
50516 - [Typhon, rank 1 frFR] [talent]

**Étapes de reproduction**
spam avec/sans .coo un mannequin

**Comment by joshwhedon** [comment]
Si c'est visuel c'est cote client et on y peut rien.

**Comment by joshwhedon** [comment]
Ouai j'ai teste, on y peut rien, c'est un melange de lag client / serveur.
