### ISSUE TITLE
Bug de Transmo

### ISSUE THREAD

**Issue by Eldjim** [way-of-elendil/3.3.5#589]
Bonjour à tous,

Je ne peut pas transmogrifier ma main droite "Lame de la Vénéneuse" en main droite "Fin de l'espoir",
chose que je pouvais faire avant la merge.

Cordialement, merci !

**Comment by Sthanks** [comment]
Même problème avec l'arme 284 (épée) et Epée longue flamboyante de Teebu

**Comment by Amilgaull** [comment]
C'est normal, pour que l'arme puisse être transmogriphiée, Il faut que l'objet ait au moins une statistique (cela permet d'exclure les objets d’évent par exemple), il faut aussi que l'objet soit de la même classe (cuir, tissu, etc)

**Comment by Sthanks** [comment]
Ouai mais cela marchais avant, pour le coup on ne peu plus utiliser de belle transmo type BC etc

**Comment by Endalaust** [comment]
Une modif a été faites sur la conf, possible de retester et de me dire? Pas de redémarrage requis pour la passer

**Comment by Eldjim** [comment]
Le problème est régler, les transmo fonctionnent !! 

Merci beaucoup et bon courage !! =)
