### ISSUE TITLE
Quête : Ursoc, le dieu ours bug de validation

### ISSUE THREAD

**Issue by nicogarion** [way-of-elendil/3.3.5#590]
Bonjour,
Malgré plusieurs tentatives et réussites à le vaincre, la quête n'est pas validée dans le livre de quête.
Merci pour le boulot.
Bonne fin de journée

**Comment by Ischjgt** [comment]
Hello, la quête est fonctionnelle, tu as bien utilisé les cendres sur le cadavre ? tu n'étais pas en groupe de raid ?
