### ISSUE TITLE
Sceau d'autorité

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#591]
**Description**
Il y a un bug avec le buff perso paladin "sceau d'autorité"
Ce dernier n'est pas appliqué à chaque dégas physique comme ça devrait être le cas :
Lorsqu'on touche une cible moins d'un certain temps apres avoir déja touché cette même cible ça n'applique pas les degas la seconde fois => il semblerait y avoir un court CD interne au degas appliqué par le buff ; environ 0,5s peut etre plus peut etre moins mais ca ruine totalement la mécanique de cleave du paladin ret...

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Paladin
- Vindicte/Protection
- Sceau d'autorité

**Comportement attendu**
Le sceau devrait s'applique sur tout les degas physiques du paladin qui touchent une cible unique.

**Captures d’écran / Vidéos**
None

**Ressources additionnelles**
Common knowledge

**Comment by joshwhedon** [comment]
Je mets un correctif pour reduire le cooldown interne.

**Comment by ronlii** [comment]
Merci beaucoup parcontre je ne comprends pas pourquoi vous mettez un cd interne plutot que de coder le sort tel que => actif sur TOUT les degas physique SAUF sur la tempete divine ou il n'est appliqué qu'une fois.
Le fonctionnement est presque le même sauf que si vous mettez un cd interne ça influera sur les proc proches tel que les inquisition+coup blanc ou tempete divine + coup blanc...
Et même pire lorsqu'on obtient enfin petite abomination c'est un peu le moment clef du palret eh bah non car là encore le hit ne fera pas proc le cleave...

Le palaret est la classe de coeur de nombreux joueurs et je pense que sa mécanique de BASE qui est  la mécanique de proc des sceaux et leur impacte/synergie avec le stuff etc... n'est pas à prendre à la légère car tout l'interet de la classe !
