### ISSUE TITLE
Reine Lana'thel "Ombres Grouillantes"

### ISSUE THREAD

**Issue by Mugiino** [way-of-elendil/3.3.5#595]
**Description**
Les sorts comme "Cape d'ombre" du voleur, "Bouclier anti-magie" du DK et "Bloc de glace" du mage n'empêchent plus les flammes d’apparaître.

**Étapes de reproduction**
Faire la reine en n'importe quelle difficulté, avec des voleurs et des chevaliers de la mort dans le groupe, et attendre que les ombres grouillantes les ciblent, puis utiliser le sort approprié.
**Comportement attendu**
Utiliser une cape d'ombre ou un bouclier anti-magie/un bloc de glace après avoir été ciblé par les ombres devrait empêcher les flammes de pop.

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/594
Pour l'AMS
https://area.way-of-elendil.fr/flyspray/index.php?do=details&task_id=6412

**Comment by joshwhedon** [comment]
Deja signale.
