### ISSUE TITLE
PET HUNT Probleme d aggro

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#600]
Le pet du HUNT a un soucis, le sort de heal envoyé par le hunt, a la place de reduire le niveau de menace du pet (au profit du chasseur). Chaque Tic augmente la menace du PET.

**Comment by joshwhedon** [comment]
J'ai teste et pas de soucis de mon cote. Notez bien que les overheal ne generent pas d'agro.
J'ai reproduit de la facon suivante : envoi du pet sur une cible, mise du pet en passif pour le faire arreter l'attaque, la cible est encore sur le pet. Mend pet, apres quelques ticks, le mob est sur moi.
