### ISSUE TITLE
Brassenoir Mob et bug combat permanent.

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#601]
Le dongeon de brassenoir, nous avons un bug combat, des l entré dans le dongeon. Et il y a des aggro de mob sur la derniere partie, comme les tortue sensé se trouvé dans la salle du dernier boss, qui aggro 100% des fois, a l entré dans la derniere partie du dongeon.

**Comment by joshwhedon** [comment]
Bonjour, il nous est impossible de reproduire ce bug, pourriez vous contacter un mj la prochaine fois que ca arrive et le mj effectuera les commandes necessaires pour obtenir des informations sur ce qui vous met en combat. Merci
