### ISSUE TITLE
Event putri

### ISSUE THREAD

**Issue by Elfluna** [way-of-elendil/3.3.5#604]
Le bug n'est pas rencontré dans chaque raid.

L'event putri ne se lance pas, la porte devant la salle du boss reste ouverte alors que celle du bas s'ouvre.

Le raid était en mode 10HC
Putricide

Merci

**Comment by joshwhedon** [comment]
Vous aviez des gens trop loin ?

**Comment by joshwhedon** [comment]
Il faut que tout le monde soit dans le couloir pour que l'event se lance.

**Comment by Ischjgt** [comment]
Je pense que c'est arrivé parce que la première fois la porte a été ouverte par un MJ

**Comment by joshwhedon** [comment]
Possible, j'attends plus d'info

**Comment by Elfluna** [comment]
plus d'infos ? j'en sais pas plus a vrai dire, isch nous l'a ouverte 1 ou 2 fois après je sais pas, tout le monde était présent dans la salle, personne loin, les deux vannes ouvertes Josh.

**Comment by Ischjgt** [comment]
(1 fois, la première c'était pas moi)
Le groupe n'a pas eu de wipe

**Comment by Elfluna** [comment]
Non isch bien sur, tu nous a ouvert on arrivait dessus, un wipe, on ne pouvait pas repasser, ensuite down.

**Comment by Ischjgt** [comment]
Ça s'est reproduit à l'instant en 10H, rien de spécial à signaler

**Comment by Fairivier** [comment]
après un wype la porte du haut ne se réouvre pas. Fait 2 fois en 10n

**Comment by Endalaust** [comment]
Toujours présent, un enfer à gérer pour les mjs
Détail notable :

L'event semble OK, mais la porte reste close après le 1er wipe, systématiquement

**Comment by joshwhedon** [comment]
Si c'est un enfer, il faut trouver commence ca arrive. Ca fait 10 fois que je passe des modifs pour corriger le probleme, si vous me donnez pas les moyens de reproduire, je peux que corriger a l'aveugle.
