### ISSUE TITLE
Rogue mutilate up poisons (Besoin d'aides pour les pistes)

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#605]
**Description**
Actuellement le rogue mutilate (assa) est légèrement up (via ses poisons). Son poison instantané sera toujours sa première source de dégâts en raid. Son poison instant fait 2-5% de plus que ses mêlées.
Je ne sais pas exactement d'où vient le soucis n'ayant pas de rogues muti sous la main pour test poussés d'où le poste demandant de l'aide pour les pistes et tests.

**Étapes de reproduction**
N'importe quel raid 25 en rogue muti.

**Comportement attendu**
Dans 98% des cas (et encore plus avec un peu de gear 25h) les mélées seront la première source de dégâts (1-4% de plus que le poison instant). 

**Ressources additionnelles**
http://www.worldoflogs.com/reports/5t4o4h4o3vnblduy/details/24/?s=1067&e=1213
http://www.worldoflogs.com/reports/5t4o4h4o3vnblduy/details/13/?s=3403&e=3556

**Comment by joshwhedon** [comment]
Ca peut aussi provenir de la setup du raid, le poison instantanne etant de type magique, les debuffs / buff sur les degats magiques doivent l'affecter.

**Comment by joshwhedon** [comment]
Ca peut etre reproduit sur mannequin ou pas ?

**Comment by Ischjgt** [comment]
Double dipping avec id: 57993 [Envenimer]
8,57*1,5*1,75*1,75*1,5= 59 proc au lieu de 8,57*1,5*1,75

Je connais pas bien la spé j'ai peut-ere louper un truc cela dit

**Comment by joshwhedon** [comment]
Double dipping ? Envenom augmente pas les degats.

**Comment by Ischjgt** [comment]
Sur le Proc par minute

**Comment by joshwhedon** [comment]
Non je pense pas, a moins qu'envenom soit 2 fois sur le rogue.

**Comment by Ischjgt** [comment]
Du coup mon edit :
Je passe de 9 stacks a + de 30 rien qu'en appliquant envenimer
si j'ai poisons améliorés, ce talent aussi est compté 2 fois avec l'envenimer ( c'est compté une fois sans donc correct sans) et ça monte a 60 proc par minute

**Comment by Justforsoloq** [comment]
Bon bah Ischjqt semble avoir peut être trouvé déjà :x

**Comment by joshwhedon** [comment]
J'ai beau tester, j'ai pas ce probleme.  Sans envenom mais avec le talent j'ai du 38% de chance d'appliquer. Avec envenom ca monte a 57%.

**Comment by Justforsoloq** [comment]
Et Josh par rapport au setup, si ça varie un peu (les %), les mêlées restent la première source de dégâts du rogue venom. Déjà même quand il n'a aucune pièce arpen. Et en full full BiS (avec donc de l'arpen) l'écart se creuse encore un peu.
Si sur retail les instants sont 1-5% derrière et sur woe 2-5% devant, tu peux avoir jusqu'à 10% de diff sur les poisons instants (up 3 à 10% de dps)
Actuellement quel que soit le setup sur woe et le rogue sur woe poison instant sera devant.
Si ce n'est pas ce qu'à dit Ischjqt, il faudrait qu'un main Muti puisse aller faire des tests pour voir ce qui donne ce up

**Comment by Ischjgt** [comment]
Je viens de notifier que Kriss donne 2 stacks de poison mortel au lien d'un,
Je pense que le probleme est du même genre avec Envenom

**Comment by joshwhedon** [comment]
Je sais que ca varie vu que c'est des ppms, mais le changement de taux correspond a ce qu'on attend avec ou sans envenom.

**Comment by joshwhedon** [comment]
Je sais pas si c'est un bug pour kriss, l'attaque applique le poison de la main gauche, mais en plus il fait une attaque de melee qui peut appliquer le poison si ca proc.

**Comment by Ischjgt** [comment]
Main droite Poison instant => proc de poison instant beaucoup beaucoup trop élevé sous envenom (avéré)
Main gauche Poison mortel => proc ok ?

Main droite Poison mortel => proc de poison mortel beaucoup élevé ?
Main gauche Poison instant => proc ok.

**Comment by Ischjgt** [comment]
En fait, + de 60 procs par minute avec une dague 1.40, c'est pas possible, même avec un poison qui proc à 100% sur les AA.
Je me demande si le buff donne pas une chance à la main gauche d'appliquer le poison de la main droite

**Comment by Justforsoloq** [comment]
Le poison mortel applique le poison instant quand il a 5 stack d'appliqué c'est normal de ce côté, j'ai peut être mal compris ce que tu as dit

**Comment by Ischjgt** [comment]
Ah beh oui merci, du coup je dis nimp
et du coup je choppe 2-3 procs de poison instantanné sur le meme Kriss
J'ai jamais réussi un seul Kriss sans appliquer 1 seul poison mortel

**Comment by Ischjgt** [comment]
En fait, il y a un truc qui explique la différence de % dans les 2 logs que tu fournis ? dans le 2eme, poison instant= les damages de mélées, c'est ce qui arrive chez moi là en fait

**Comment by Ischjgt** [comment]
Nan, l'autre rogue avec un stuff pvp c'était correct, donc c'est pas les dégats

**Comment by Justforsoloq** [comment]
Bah très clairement tu regardes mon screen tu vois qu'il y a un gros soucis. Sur tous les logs offis les assa leurs mélées et leurs poisons sont très proches (mélée étant devant en plus 90% du temps). Ici sur le screen on voit bien qu'il y a une grosse différence.

**Comment by sithis2a** [comment]
A voir aussi le taux d'application et sur la FoK, faire du 60k DPS sur les adds avant Sindra en stuff récup c'est pas normal du tout.
Faudrait reproduire la situation sur le serveur de dev et voir le nombre de proc et les dmg.

**Comment by Ischjgt** [comment]
Dernier essai pour moi mais je crois que j'ai trouvé
Les bonus de PA due à la vitesse de l'arme en main gauche sont comptés sur les procs poisons instant venant des 5 stacks d'un poison mortel en main gauche, du coup ça nous fait un poison qui bénéficie des vitesses des 2 armes

https://woehead.way-of-elendil.fr/?search=poison+mortel
https://woehead.way-of-elendil.fr/?search=poison+instantan%C3%A9

https://www.youtube.com/watch?v=Z0iZzNn-ZUQ tous ses procs poisons instant tournent autour de 1000, j'ai des écarts de 300 points quand j'équipe une 1.80 à gauche

**Comment by joshwhedon** [comment]
Bah ... normal. La puissance d'attaque prend en compte tout l'equipement, pas juste la main droite.
Quant a la vitesse, pour le ppm c'est l'arme elle meme qui est prise en compte, pas les stats.  Donc le ppm est base sur la vitesse de base de l'arme, rien d'autre.

**Comment by Justforsoloq** [comment]
Comme dit plus haut, je ne pense pas que ce soit les ticks qui sont un soucis. 
Mais les dégâts, mon screen si rien d'autre le montre avec assez d'efficacité x)

**Comment by Justforsoloq** [comment]
Autre rogue sur saurcroc 5k3 gs.
10% again de diff entre instant et mélée.
https://www.noelshack.com/2020-18-4-1588255918-wowscrnshot-042920-151357.jpg

**Comment by Justforsoloq** [comment]
https://www.noelshack.com/2020-18-4-1588256354-wowscrnshot-043020-151247.jpg
Rogue 5k3 gs sur garga. Encore une grande différence entre instant et mélée.

**Comment by Justforsoloq** [comment]
Ah :o c'est quoi au final ?

**Comment by Mugiino** [comment]
Le peuple veut savoir !

**Comment by gtschanz** [comment]
Le peuple ne saura jamais ! @Mugiino
