### ISSUE TITLE
Talent: Armure tranchante/Armé jusqu'aux dents

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#608]
**Description**
Il est nécessaire de faire une déco pour que les changements de puissance d'attaque soient pris en compte par les talents

48978 - [Armure tranchante, rank 1 frFR] [talent] [passive]
49390 - [Armure tranchante, rank 2 frFR] [talent] [passive]
49391 - [Armure tranchante, rank 3 frFR] [talent] [passive]
49391 - [Armure tranchante, rank 3 frFR] [talent] [passive]
49393 - [Armure tranchante, rank 5 frFR] [talent] [passive]

61216 - [Armé jusqu'aux dents, rank 1 frFR] [talent] [passive]
61221 - [Armé jusqu'aux dents, rank 2 frFR] [talent] [passive]
61222 - [Armé jusqu'aux dents, rank 3 frFR] [talent] [passive] 
N.B.: je crois que j'ai noté quelque chose de pareil pour d'autres talents et stats...J'essaie de m'en occuper rapidement

**Comment by joshwhedon** [comment]
C'est pas vraiment ce qui se passe. En fait ces talents sont periodiques, l'aura proc toutes les 30 secondes je crois, et le calcul est refait uniquement au moment de ce proc. Base sur les donnees client, ca a l'air d'etre le comportement attendu. A mon avis la raison est que Blizzard ne voulait peut etre pas de variations massive de degats si le joueur equipe un bouclier temporairement, en tout cas c'est l'explication que je peux trouver a cette decision.
En l'absence d'information sur le sujet, je vais assumer qu'il s'agit du comportement normal (Blizzard a voulu traiter cette aura comme periodic, il doit y avoir une raison).
(PS: je connaissais pas ce comportement avant, ca m'a pris un peu de temps de comprendre ce qui se passait).

**Comment by Ischjgt** [comment]
EToaster le 2008-12-15  (Mise à jour 3.0.3)However,  those abilities only check your armor value roughly every 30 seconds,  so you may not get the AP boost for a bit after you pop the potion.  Of  course, this also applies when the bonus armor fades, so you'll still  get roughly 2 minutes out of it regardless of when you pop it.  It just  may not be the exact 2 minutes you wanted. =)
--
5 | 361206 le 2009-05-04  (Mise à jour 3.1.1)This  is actually not entirely true.  As a DK, you can go into Frost Pres.,  use Horn of Winter, switch back to Blood Pres. and keep the extra AP  from Frost Pres.' Armor.  This only changes when Horn of Winter or  another buff effecting your AP is applied or dropped.  Obviously, this  is a bug of sorts...but it isn't just an "update every 30 seconds"  thing.  Use this pot and HoW after (or get a Greatness proc, Battleshout  etc etc), you SHOULD immediately see the benefits.

**Comment by joshwhedon** [comment]
Non, ca update toutes les 30 seconde. Le gars a juste eu de la chance et a mis ses buffs au bon moment.
