### ISSUE TITLE
NPC: Njormeld

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#609]
**Description**
Le PNJ n'est pas visible par les joueurs ayant accompli la suite de quête récemment (depuis la merge?)
Je connais pas exactement les conditions pour pouvoir voir le npc mais le joueur qui a ce soucis a https://woehead.way-of-elendil.fr/?quest=12976 en complete et ne le voit pas parce que Njormeld a 
id: 56768 [Quest Invis Tier 1] 

**Comportement attendu**
j'ai trouvé ça 
https://github.com/TrinityCore/TrinityCore/issues/8274
C'est pas le bon Njormeld mais c'est le même délire et le Entry: 30127. est évoqué à la fin du ticket

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?quest=12967 et https://woehead.way-of-elendil.fr/?quest=12924 doivent etre completees pour voir le npc. J'ai teste ca fonctionne correctement. Je pense que le joueur en question a un soucis au niveau de sa chaine de quetes d'hodir, il va falloir voir avec lui directement.

**Comment by Ischjgt** [comment]
Il ne pouvait pas prendre https://woehead.way-of-elendil.fr/?quest=12967 parce qu'il ne voyait pas l'autre Njormeld https://woehead.way-of-elendil.fr/?npc=30099 et il avait https://woehead.way-of-elendil.fr/?quest=12966 en rewarded

id: 61208 [Fjorn's Anvil - Quest Invisibility 3]
Du coup c'est bien le ticket github que je t'ai link :D

**Comment by joshwhedon** [comment]
https://woehead.way-of-elendil.fr/?quest=12924 il a besoin d'avoir cette quete dans son journal de quete pour pouvoir le voir. Si il a abandonne la quete il ne pourra pas. Si il l'a complete (chose qui n'est pas possible normalemenT) il ne pourra pas.
