### ISSUE TITLE
Boss: Moisson d'âme et aggro - Roi-liche - ICC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#611]
**Description**
36597 LK
10N et 25N
Cas où le boss se dirige vers le le joueur qui se situe dans la moisson d'âme

**Étapes de reproduction**
- 3 joueurs
- P3
- A tank, B second en aggro, C dernier en aggro
- Moisson d'ame sur B, B entre dans l'épée
- A meurt quand B est dans l'épée => le boss va vers B

**Comportement attendu**
Le boss devrait aller sur C le temps que le joueur soit dans la moisson??

**Comment by Ischjgt** [comment]
36701 - [Esprit déchaîné] 
37695 - [Drudge Ghoul]

J'avais pas pensé à regarder pour les adds.
Pareil pour ceux là, ça semble pas le faire sur les esprits déchaînés

**Comment by joshwhedon** [comment]
Pas compris. Ca le fait encore pour le roi liche ? Ou pour les adds uniquement maintenant ?

**Comment by Ischjgt** [comment]
Jme suis gourré en plus, pour :
 37698 - [Horreur titubante]
 37695 - [Drudge Ghoul]
