### ISSUE TITLE
Pathfinding de la succube sur l'arène des tranchantes (et sans doute des autres familiers)

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#612]
**Description**
En étant sur le pont des tranchantes en envoyant sa succube sur les ennemis en dessous (pilier du dessous), la succube va "bug". Elle va considérer les ennemis à portée d'attaque et donc faire du gauche/droite pendant de long moment.

**Étapes de reproduction**
Tag escarmouche, mettez un joueur en bas derrière le pilier, un demo en haut au dessus et faites lui envoyer sa succube attaquer ce dit joueur

**Comportement attendu**
La succube suit son pathfinding pour y aller.

Soucis de Pathfinding.

**Comment by joshwhedon** [comment]
On y peut rien :(
