### ISSUE TITLE
Cape d'ombre ne fonctionne pas sur les roots des familiers crabe/araignée des chasseurs

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#615]
**Description**
La cape d'ombre n'enlève pas les roots des familiers crabe et araignée du chasseur.

**Étapes de reproduction**
Prenez un hunt avec une araignée ou un crabe et faites un duel sur le rogue. Rootez le avec le sort (pin ou web) et le rogue cos. Regardez.

**Comportement attendu**
La cape d'ombre enlève le root de ces pets (dissipation via magie). /!\ La cape d'ombre n'empêche pas par contre le chasseur d'appliquer le root APRES (fonctionnement similaire à la morsure du serpent en quelque sorte dans l'idée)

**Ressources additionnelles**
https://wotlk.evowow.com/?spell=4167
https://wotlk.evowow.com/?spell=53548

**Comment by joshwhedon** [comment]
Pin et Web sont tous les deux des debufs physiques, SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
A moins de me trouver des sources qui prouvent que ces deux la peuvent etre retire via cape d'ombre, c'est le comportement normal.

**Comment by joshwhedon** [comment]
Dans le cas de Pin c'est meme classifie comme une attaque de melee.

**Comment by Justforsoloq** [comment]
En effet, juste mes souvenirs d'un certain serveur pvp (arono tournomon)(où la cos pin/web était possible) et le fait que cette ligne : 
Type de dissipation | Magie
m'a induite en erreur. Dans les vidéos retail que j'observe généralement les rogues usent le vanish sur le web/pin.
