### ISSUE TITLE
Bug Prêtre discipline talent grâce + pénitence

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#616]
Sur le serv : La pénitence fait proc un effet du talent grâce sur le lanceur de sort au cast de la pénitence, puis un à chaque heal de la pénitence sur la cible de la pénitence.

Comportement attendu : La pénitence ne doit pas faire proc un effet du talent grâce sur le lanceur de sort au cast de la pénitence, seulement un à chaque heal de la pénitence sur la cible de la pénitence.

(C'est assez gênant puisque cela reset les stacks de grâce sur la cible de la pénitence.)

**Comment by joshwhedon** [comment]
"Vos sorts Soins rapides, Soins supérieurs et Pénitence ont 50% de chances de donner la Grâce à la cible, ce qui augmente tous les soins que lui prodigue le prêtre de 3%. Cet effet est cumulable jusqu'à 3 fois et dure 15 s. Grâce ne peut être active que sur une cible à la fois."
Il n'y a rien qui dise que ca doit etre a chaque heal dans la description.
Qui plus est dans les donnees client :
  14 Successful cast positive magic spell
Donc a moins de fournir une preuve indiquant que le comportement actuel est incorrect, il est considere comme correct.

**Comment by toitit** [comment]
Je pensais pas devoir fournir de preuve tellement c'est évident mais bon. Déjà sur la description c'est précisé "à la cible".
Ensuite : https://youtu.be/P8fh4fA6rU0 à 2:15, le prêtre lance pénitence et ne gagne pas de stack de grâce.
Test actuellement sur le serveur, quand tu lance pénitence sur une autre personne comme dans la vidéo, le prêtre gagné une stack de grâce pendant quelques secondes au lancé du sort

**Comment by joshwhedon** [comment]
Merci
