### ISSUE TITLE
Bénédiction de puissance Paladin

### ISSUE THREAD

**Issue by Flocapa** [way-of-elendil/3.3.5#620]
Quand on a le buff "Bénédiction de puissance" (rang 10) et que l'on veux refresh ce dernier, donc en l'activant à nouveau, le jeu refuse en nous indiquant "Un sort plus puissant est deja actif".

Reproduire le bug :
Paladin lvl 80 spé vindicte avec le talent bénédiction de puissance améliorée et avec la glyphe de bénédiction de puissance (30 min au lieu de 10)
Avoir sur soi le buff de la bénédiction de puissance rang 10
Relancer le sort

Comportement attendu : 
Le sort est censé se lancer même avec le buff déjà actif et doit se refresh

**Comment by Ferro3** [comment]
J'ai eu le même problème ce jour avec un druide équilibre avec les 2 points dans la marque.
J'ai voulu reposer un buff simple par dessus un buff de groupe de 3 mins, et le jeu me l'a refusé.
Je m'en suis sortis en annulant manuellement mon buff (clic droit) puis rebuff.

**Comment by joshwhedon** [comment]
Bah si le jeu a refuse c'est que le buff deja present est superieur au buff que tu voulais mettre.

**Comment by joshwhedon** [comment]
Personnellement quand je suis en solo, je peux refresh le buff sur moi sans probleme. Tu etais en groupe avec quelqu'un qui avait un buff equivalent ?

**Comment by Flocapa** [comment]
Je ne suis pas groupé, et je lance strictement le meme le sort
