### ISSUE TITLE
Quête [80*] [Planter la lance de Hodir]

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#621]
**Description**
Passage sous la montagne lors de la réalisation de la quête journalière **[80*] [Planter la lance de Hodir]** https://woehead.way-of-elendil.fr/?quest=13003.
En cas de mort, le cadavre étant sous le décors il est donc impossible de ressusciter.
Le déblocage automatique ne fonctionne pas, le jeu bloque puisque sur une monture en fantôme  (se qui est normal dans **Les pics Foudroyés**).

**Étapes de reproduction**
**[80*] [Planter la lance de Hodir]** https://woehead.way-of-elendil.fr/?quest=13003
Sortir du camps des fils de hodir et prendre le 1er Protodrake en partant de la gauche.
Être un peu lent pour faire la quête aidera à reproduire.
Le Protodrake va vers le nord et passe sous la map, le personnage étant attaché au véhicule, il passe lui aussi sous la map.

A partir de là, si vous échouez la quête (ce qui a été mon cas), il est impossible de libérer puisqu'en chute libre sous la map. Mon jeu ayant planté à ce moment là (wow error), je me suis retrouvé au cimetière en fantôme.
Naïf comme je suis j'ai tenté de récupérer mon corps, et une fois sur place impossible puisque mon cadavre était hors de portée.
Ensuite, n'étant pas un abonnement du cimetière, il m'a été impossible de retrouvé un ange pour rez, mais heureusement Amandil m'a fournie un lien vers les anges https://woehead.way-of-elendil.fr/?npc=6491 du coup avec cette carte j'ai pu ressusciter à l'ange.

**Comportement attendu**
Revoir le trajet du Protodrake pour ne plus passer sous la map.
Permettre une téléportation au cimetière dans la zone des **Les pics Foudroyés** avec le bouton de déblocage automatique.
Vérifier les sortilèges et attaques du Protodrake.

La quête, je pense, est à revoir également dans son exécution:
* Les timers d'esquive me semble décalés.
* Le personnage est remplacé par le Protodrake, la cible également ; j'ai souvenir d'un agencement différent, mais je ne me souviens plus duquel, et il est possible que ma mémoire me joue des tours.
* Les buff et dé-buff ne sont plus visible comme auparavant (probablement lié à l'affichage de la cible)
* Le vol du Protodrake n'est pas du tout comme attendu, il est fixe au lieu de ressembler à une monture Protodrake.

**Conclusion**
Je pense qu'un simple test de la quête permet de constater les problèmes listés.
Ayant des personnages exaltés aux fil de hodir cela ne m'impacte pas, mais je pense aux nouveaux joueurs, la perte de réputation (+650) et de pièces d'or (+31po) est assez importante pour eux.

Bon courage.

**Comment by joshwhedon** [comment]
Tu l'as reussie quand la derniere fois ?

**Comment by Ferro3** [comment]
J'ai fais cette quête 2 fois depuis la migration.
La première fois je l'ai réussie, aujourd'hui non.
Pour la partie historique je fais référence à avant la migration et sur officiel, mais c'est c'est loin.

**Comment by joshwhedon** [comment]
Et quand tu l'as reussie tu as eu les memes problemes ?

**Comment by Ferro3** [comment]
non, je ne crois pas être passé sous la map, ça devait être un autre Protodrake, franchement je ne sais plus.

**Comment by joshwhedon** [comment]
OK, parce que y'a eu une maj aujourd'hui qui a cause des problemes avec les quetes impliquant des vehicules.

**Comment by Ferro3** [comment]
Je signale tout de même qu'un autre joueur à rencontré les mêmes problèmes il y a 1mois environ

**Comment by joshwhedon** [comment]
Oui merci.

**Comment by Paps0** [comment]
Bonjour, j'ai eu le problème je suis passer dans la montagne et j'ai quand même réussit à tuer la wyrm mais impossible de descendre de la monture, le déblocage ne fonctionnait pas, ni le reload. J'ai été obligé de quitter le jeu complètement et à mon retour une chute de quelques minutes en sous-map puis la mort. En libérant, j'ai été téléporté au cimetière le plus proche en vie. Merci par avance.

**Comment by Erzer59** [comment]
Bonjour, moi aussi j'ai eu le coup ce 17/07/2022. 

    J'ai monté le Wyrm; étant la première fois, je ne savais pas trop ce qu'il fallait faire, perdu avec les commandes disponibles. Le combat dure, le wyrm passe dans la montagne, ma poigne de wyrm lâche et je tombe dans le vide. J'ai quand même réussi à prendre une vidéo à l'arrache pour la poster. La déconnexion, personnage coincé, etc, ne fonctionnent pas car le personnage est en mouvement. J'ai du faire Alt F4. 
    En me reconnectant, je reviens en vie 50% pv au cimetière. J'ai tenté une seconde fois, j'ai été tué par le wyrm tout à la fin, avec mon cadavre bien en hauteur dans les montagnes. Une troisième fois fut la bonne.

https://user-images.githubusercontent.com/109001178/179421211-56770560-fb8a-46aa-872a-682e24310eb5.mp4

**Comment by Ferro3** [comment]
reprise du message ci-dessus pour éviter le scrolling :

> J'ai monté le Wyrm; étant la première fois, je ne savais pas trop ce qu'il fallait faire, perdu avec les commandes disponibles. Le combat dure, le wyrm passe dans la montagne, ma poigne de wyrm lâche et je tombe dans le vide. J'ai quand même réussi à prendre une vidéo à l'arrache pour la poster. La déconnexion, personnage coincé, etc, ne fonctionnent pas car le personnage est en mouvement. J'ai du faire Alt F4. 
> En me reconnectant, je reviens en vie 50% pv au cimetière. J'ai tenté une seconde fois, j'ai été tué par le wyrm tout à la fin, avec mon cadavre bien en hauteur dans les montagnes. Une troisième fois fut la bonne.

**Comment by Ferro3** [comment]
normalement, cette quête a été complètement revue en 2020, et est fonctionnelle, d'ailleurs le denier joueur l'a terminé

cependant, d'après ce que je lis, il semblerait que si le trajet s'éternise, il se termine encore dans la montagne et provoque un sous map, avec tout un tas de complications derrière
le cas se présente probablement pour les premiers lancements de la quête où le joueur est, je cite "perdu avec les commandes disponibles"

par contre, la bonne nouvelle : le rez automatique lui fonctionne correctement
