### ISSUE TITLE
[Prêtre] Pierre de foyer sous lévitation, crash

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#624]
Faire une téléportation avec une pierre de foyer ou un anneau de dalaran (il faut vérifier avec le parchemin de l'ile de quel'danas) avec une lévitation en cours provoque un wow error à 100%.
J'ai pour habitude de pécher en lévitation pour ceux qui se demandent.
Je me suis aperçu de ce problème mineur il y a assez longtemps, j'ai re-vérifié depuis la migration le bug est toujours présent.

**Comment by Ischjgt** [comment]
Pas chez moi,
Patch HD?

**Comment by Ferro3** [comment]
Je crois, oui

**Comment by joshwhedon** [comment]
Je viens de tester en local aussi, pareil ca crash pas, ca provient probablement du patch hd. Malheureusement on y peut pas grand chose.
