### ISSUE TITLE
[Donjon] Bug combat Azjol-Nérub

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#625]
Après avoir tué Krik'thir le Gardien de porte, le 1er boss, nous sommes toujours en combat, à 100%.
Peut être une bête dans les murs, aucune idée.

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/472
Je regarde, j'ouvre l'autre ticket et je ferme celui-ci si j'arrive à reproduire là

**Comment by Ischjgt** [comment]
Ah mais du coup https://github.com/way-of-elendil/3.3.5/issues/622
Ça a été compilé tout à l'heure, du coup ré ouvre ce ticket si il y a encore un soucis, mais j'ai testé là et c'était ok
