### ISSUE TITLE
Boss: Kalecgos - Plateau du Puits de soleil

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#627]
**Description**

24850 - [Kalecgos]
24891 - [Kalecgos] dans le royaume spectral)
24892 - [Sathrovarr le Corrupteur] (dans le royaume spectral)

Les joueurs "envoyés" dans le royaume spectral ne voient pas les NPCs  (et tout le reste?) avec id: 44801 [Invisibilité spectrale] Ils choppent seulement :

id: 44852 [Royaume spectral] 
id: 46021 [Royaume spectral] 

(boss pas faisable)

https://www.youtube.com/watch?v=K9mfONlbrTg

**Comment by joshwhedon** [comment]
Impossible a reproduire de mon cote. Dans le royaume spectral, que j'y sois envoye par le boss ou en cliquant sur le portail, je vois bien les npcs.

**Comment by joshwhedon** [comment]
Si les joueurs voyaient pas le reste de l'instance non plus si ca se trouve ils etaient dans la phase de la quete de l'epee.

**Comment by Ischjgt** [comment]
Ischjgt
> id: 44867 [Epuisement spectral]
quand t'as ce buff tu chopes royaume spectral mais t'es pas tp
JoshTheGeek
> t'es pas suppose pouvoir etre cible quand tu as ce buff cela dit
je regarde

**Comment by Ischjgt** [comment]
C'est arrivé aujourd'hui, les joueurs ne sont pas TP en bas mais choppent seulement le débuff royaume spectral

**Comment by joshwhedon** [comment]
T'as reussi a reproduire ca ?

**Comment by Ischjgt** [comment]
Oui, suffit d'être à 2 joueurs et celui qui tank pas se retrouve phasé mais pas TP dans l'autre salle

**Comment by joshwhedon** [comment]
J'arrive pas a reproduire. Soit le soucis est regle, soit y'a des conditions particulieres pour reproduire.

**Comment by gtschanz** [comment]
@joshwhedon  je vois avec simba il refait le raid en théorie samedi à 14H00 si tu devais être dispo (au cas ou le soucis devait apparaître)
