### ISSUE TITLE
[Quête] Louveteau de la clairière de Tombeneige inaccessible

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#629]
Je signale bug très mineur.
Pour la quête **[Préparer l'avenir]** https://woehead.way-of-elendil.fr/?quest=11960 un  [Louveteau de la clairière de Tombeneige] est inaccessible aux joueurs.
Les coordonnées sont 42.6-71.6 ; il se trouve à l’intérieur d'une hutte c'est au nord ouest de la zone.

**Comment by joshwhedon** [comment]
J'arrive pas a le trouver. Il est possible qu'il ait juste bouge dans la hutte a cause de ses mouvements aleatoires.  Il y a avait aussi des soucis niveau selection de position hier, c'est corriger avec la prochaine mise a jour ca devrait regler le probleme.

**Comment by Ferro3** [comment]
Ce problème est en effet réglé : le mob n'est plus là.
Mais un autre **[Louveteau de la clairière de Tombeneige]** est maintenant dans la hutte précédente et présente les même symptômes (est inaccessible aux joueurs) :(
Les coordonnées du nouveau : 43.5 72.1 (il ne bouge pas celui-là, enfin je crois)
