### ISSUE TITLE
(guerrier) aura talent passif saccager désactiver 

### ISSUE THREAD

**Issue by JAGGERstark** [way-of-elendil/3.3.5#63]
**Description**
Le porteur du talent na pas l'aura mes fonctionne pour les autre .
Le changement de spe ne change pas le problème ni le remplacement d’équipement

- Classe : war
- Race : orc
- Spécialisation : fureur
- Talent : saccager (5% crite)

**Captures d’écran / Vidéos**
https://youtu.be/hglLCA81jCY

**Comment by Ischjgt** [comment]
Ça marche;
MP moi sur Discord si tu veux

**Comment by Killyana** [comment]
C'est un bug d'affichage sur les coups critiques, s'il y'a aucun talent qui change le % des cc en spé arme, tu gagnes 10% via https://woehead.way-of-elendil.fr/?spell=12856 et https://woehead.way-of-elendil.fr/?spell=29801 en passant fury avec les 2 talents.
C'est corrigé sur le serveur merge.

**Comment by JAGGERstark** [comment]
bon si c corrigé bien
chelou en tous cas il et afficher et répercuter si c un autre te buff aura, mes  sois même afficher mes pas répercuter dans les state mes activer invisible

**Comment by Killyana** [comment]
Oui le bug existe depuis plus de 2 années, mais juste visuel
