### ISSUE TITLE
Quest: Là-bas tout en bas

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#630]
**Description**
12673 - [Là-bas tout en bas]  [active]

52245 - [Ramasser le cristal chancreux, rank 1 frFR] Le CD s'active mais rien ne se passe

**Comment by Killyana** [comment]
Peut être fixé par https://github.com/TrinityCore/TrinityCore/issues/17945#issuecomment-605180547
Il reste le problème des contrôles du pet qui sont affichés et utilisables par le joueur

**Comment by joshwhedon** [comment]
Il manque un truc dans mon fix sur les pet / smart AI.
