### ISSUE TITLE
Sindragosa (et autres dragons) hitbox

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#631]
**Description**
La hitbox des dragons en boss de raids est mal positionnée. Elle touche les joueurs placées sur le flanc (même au centre)

**Étapes de reproduction**
Faites un raid avec sindra 

**Comportement attendu**
La hitbox des stuns/bump des dragons doit se passer sur le point d'impact de la queue (avec 20 yard de distance).

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?v=DBRx9magQ0c

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Sindragosa_(tactics)
https://github.com/TrinityCore/TrinityCore/issues/12235

Ps : Il me semble que c'est la même pour Halion et autres dragons.

**Comment by joshwhedon** [comment]
Deja signale il y a longtemps, on y peut rien a moins que Trinity y touche. Y'a aucune regle precise sur la facon dont les aoes doivent etre calculees, des fois elles sont supposees prendre la taille de la cible en compte, d'autre fois la taille du caster, mais impossible de savoir ce qui est correct ou pas.
