### ISSUE TITLE
NPC: Tur Ragepaw - Ursoc le Dieu ours

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#632]
**Description**
Quest 12236 - [Ursoc, le dieu Ours] 
12249 - [Ursoc, le dieu Ours] 

Name: Ursoc
Entry: 26633.
Name: Tur Ragepaw
Entry: 27328.

1. Tur en forme de heal n'agit pas quand le combat commence
2. Cas où Tur reste bloqué au spawn d'Ursoc

**Étapes de reproduction**
2. 
- .q a 12236 ou 12249
- Parler à Tur, forme d'arbre
- Lancer le combat contre Ursoc, Tur fait rien, il prend aucune aggro
- Et ensuite mourir => Tur bloqué

**Comment by joshwhedon** [comment]
@Killyana  y'a moyen que tu jette un oeil a l'occasion ?

**Comment by Killyana** [comment]
Fixé prochaine maj normalement.

**Comment by Ischjgt** [comment]
C'est revenu, je saurais pas te dire depuis quand.
1. Tur ne fait rien en forme d'arbre
2. Cas où tu reste bloqué au spawn d'Ursoc

**Étapes de reproduction**
- .q a 12236 ou 12249
- Parler à Tur, forme d'arbre
- Lancer le combat contre Ursoc, Tur fait rien, il prend aucune aggro
- Ursoc despawn si personne a prit l'aggro ou si le joueur meurt, pas Tur

**Comment by joshwhedon** [comment]
@Killyana  des chances que tu puisse rejeter un oeil ?

**Comment by Killyana** [comment]
Faudra voir se que sa donne avec: 
``` sql
UPDATE `smart_scripts` SET `event_phase_mask`=0 WHERE `entryorguid` IN (27328) AND `source_type`=0 AND `id`=26;
UPDATE `smart_scripts` SET `action_param6`=2 WHERE `action_type`=53 WHERE `entryorguid` IN (2732800,2732801,2732802);
``` 
Mais le SAI d'origine est moisie, y'a des set react de partout alors que sa doit être géré dans le wp et le reset de l'event n'est pas fait proprement, la forme heal doit heal sans attaqué se qui est pas scripté correctement, et plein de petits trucs pas blizzlike.

**Comment by Crotodur** [comment]
fait aujourd'hui et ça a marché

**Comment by gtschanz** [comment]
Bonjour; je suis très étonné vu la date à laquelle cela à été publié qu'il n'y a pas eu de correctif depuis; et franchement dans le cas où il n'y en aurait pas; il faudrait à minima reset le pnj pour que le joueur puisse valider la quête.
