### ISSUE TITLE
Boss: Putricide - Poison de Distraction mentale/Malédiction des langages 

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#633]
**Comportement attendu**
Name: Professor Putricide
Entry: 36678.

Le boss est normalement insensible aux auras qui touchent à la vitesse d'incantation.

(C'est très dur de trouver des infos dessus parce que c'est beaucoup plus facile de trouver des infos sur les boss sur lesquels il est possible de le faire (ex Sindragosa, c'est crier partout) plutôt que sur les boss sur lesquels il n'est pas possible de le faire - du coup je suggérerai de mettre tout les boss immune et faire des exceptions plutot que l'inverse :o) )

Ticket 16344

**Comment by joshwhedon** [comment]
Deja le cas, le debuff s'applique mais n'a pas d'effet. J'ai deja mis un fix qui s'applique a la majorite des boss (tout ceux qui peuvent etre interrompus).
