### ISSUE TITLE
Dk : Fréquence de la gargouille + script hit 

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#636]
**Description**
La gargouille cast beaucoup trop vite actuellement en pve (une régression du moment où vous l'aviez mis en low cast time au lieu de son cast time de 2s ?) et ne fait que des frappes de la gargouille là où en pve elle doit inclure des mélées qui mitigent son dps (vous verrez sur les liens)

**Étapes de reproduction**
Pve avec un dk impie

**Comportement attendu**
Gargouille lance moins de gargoyle strike, et plus de mélée.

**Ressources additionnelles**
Gargouille woe sur un garga :  https://www.noelshack.com/2020-18-5-1588368342-wowscrnshot-050120-210157.jpg (43 hit de gargouille)
Gargouille sur un Garga retail fin 3.3.5 : http://www.worldoflogs.com/reports/up5rno2y5w0lta6h/details/76/?s=653&e=763 (16 hit gargouilles et 10 mêlées)

Sur woe la gargouille en pve ne met aucune mêlée augmentant déjà significativement son dps (gargoyle strike >>> mêlée) et met bien trop de strike (elle fait 150k de plus que ce qu'elle devrait).

**Comment by Justforsoloq** [comment]
Donc déjà à vérifier le cast time de base qui doit être de 2s :
https://wotlk.evowow.com/?spell=51963

**Comment by joshwhedon** [comment]
Je vois rien nulle part indiquant qu'elle doit faire des attaques de melee. Par contre j;ai des sources indiquant que la vitesse de melee du dk se transforme en hate pour la gargouille, donc non le cast time n'est pas 2 secondes.

**Comment by Justforsoloq** [comment]
Bah nul part sauf sur les logs retails.... J'ai link des logs retails en fait.

**Comment by joshwhedon** [comment]
Si tu peux en sortir au moins un ca serait bien. Pas que je te crois pas sur parole, mais je te crois pas sur parole.

**Comment by joshwhedon** [comment]
Et le cast time de base est bien 2 secondes. CastingTime (Id 5) = 2.00

**Comment by Justforsoloq** [comment]
De logs retails ? Mon premier post en a un...
J'le remets vu que tu as peut être loupé
http://www.worldoflogs.com/reports/up5rno2y5w0lta6h/details/76/?s=653&e=763
J'en mets d'autres si jamais : 
http://www.worldoflogs.com/reports/rqj75a4o7g4rgw4m/details/80/?s=412&e=512
http://www.worldoflogs.com/reports/rqj75a4o7g4rgw4m/details/80/?s=683&e=911
http://www.worldoflogs.com/reports/rqj75a4o7g4rgw4m/details/80/?s=1489&e=1632 (ici elle ne fait que des strikes, aucune idée de pourquoi sur celui là elle n'en fait aucun ?)
https://www.wowhead.com/forums&topic=133584 (11 Gargoyle Strikes (ave=1748, all hits, no crits), 1 Melee (parried, I was behind dummy, gargoyle appeared in front). Total damage done=19223. Damage per second of 660.)
Par contre même en prenant un fight sur retail où elle n'a fait que des strikes (aucune idée toujours de pourquoi sur des fights elle en fait plus ou non) elle en fait quasiment deux fois moins que sur woe.

**Comment by joshwhedon** [comment]
Mon idee c'est que sur offi, meme si la hate influe sur le temps de cast, elle n'influe pas sur le cooldown du strike. Donc en gros, entre 2 strike, sur offi c'est toujours 2 secondes. Dans le cas du dernier log, soit le mec a pas de hate du tout, soit la gargouille etait pas a distance de melee.

**Comment by Justforsoloq** [comment]
https://www.mmo-champion.com/threads/697868-Gargoyal-and-Haste

**Comment by joshwhedon** [comment]
Base sur les logs disponible, le probleme n'est pas le temps de cast ou l'interval entre les casts, mais la duree de la gargouille.
http://www.worldoflogs.com/reports/up5rno2y5w0lta6h/xe/?x=sourceName+%3D+%22Ebon+Gargoyle%22
La gargouille dure 27 secondes (contrairement aux 40 secondes indiquees par le sort), c'est a dire 16 strikes. Entre les strikes, si a distance de melee et une attaque de melee est disponible, une melee a lieu.

**Comment by joshwhedon** [comment]
En fait non j'ai toujours aucune idee de quand elle fait une attaque de melee. Elle en fait pas a chaque fois, et on dirait que des fois elle decide de taper en melee plutot qu'a distance. Il semble pas y avoir de regles, des fois ca delay meme le cast de son strike.  Bref, aucune idee pour la melee, elle va en faire, de temps en temps, mais vu que je sais pas comment les gerer, ce sera surement moins souvent.

**Comment by Ischjgt** [comment]
>La elle chain cast
donc c'est toujours un enfer
Je pense que la hâte diminue le temps de cast et peut-être diminue le délai entre les casts
mais en tout cas y'a bien un délai

Patch 5.3.0 (21-May-2013): Will now chain cast spells with no delay between casts, allowing it to cast its spells more frequently in the same amount of time.

**Comment by sithis2a** [comment]
> Base sur les logs disponible, le probleme n'est pas le temps de cast ou l'interval entre les casts, mais la duree de la gargouille.
> http://www.worldoflogs.com/reports/up5rno2y5w0lta6h/xe/?x=sourceName+%3D+%22Ebon+Gargoyle%22
> La gargouille dure 27 secondes (contrairement aux 40 secondes indiquees par le sort), c'est a dire 16 strikes. Entre les strikes, si a distance de melee et une attaque de melee est disponible, une melee a lieu.

Le sort indique qu'elle doit durer 30 secondes et pas 40 et il faut prendre en compte son animation d'arrivée et d'envol dans le lot ce qui peut correspondre aux 27 secondes d'activités.
Dans cette vidéo il la lance à 1:03 et elle finit son animation de départ à 1:33 donc 30 secondes: https://youtu.be/VSs17aqQpA0?t=62
