### ISSUE TITLE
4T10 n'est pas pris en compte dans le rolling dot corruption

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#639]
**Description**
Actuellement sur woe, la mécanique de la rolling dot ne prends pas en compte le 4T10 (à voir avec les effets crit.)

**Étapes de reproduction**
Prenez un demoniste, posez votre corruption regardez les dégats. Puis faites proc votre 4T10, faites un refresh manuel corruption et regardez.

**Comportement attendu**
Les %dmg buff et le crit est gardé via une corruption manuelle (la mécanique de rolling corruption).

**Ressources additionnelles**
https://www.wowhead.com/forums&topic=162195
https://wotlk-twinhead.twinstar.cz/?spell=70840

**Comment by Justforsoloq** [comment]
Après d'autres tests : 
Le 4T10 lock ne marche pas du tout avec les dots actuellement (testé avec corruption/affliction instable/malédiction d'agonie)

**Comment by joshwhedon** [comment]
Sera pas corrige, trop de changements a faire pour le permettre.

**Comment by Justforsoloq** [comment]
C'est quand même un énorme nerf des afflis...

**Comment by joshwhedon** [comment]
C'est aussi un enorme buff des afflis, parce que ca veut dire que tu peux mettre tous tes buffs % et garder les memes degats.

**Comment by Justforsoloq** [comment]
Les seuls buffs % de l'affli c'est le 4T10 et le talent 12% caresse de la mort. La talent caresse de la mort marche.
Tu n'as pas lu ce que j'ai mis en dessous j'ai l'impression. Le 4T10 demo ne marche pas tout court pour les dots.

**Comment by joshwhedon** [comment]
Ca change pas le fait que j'y toucherai pas. Changer ca signifie reorganiser TOUS les ordres d'application de buffs / debuffs, et donc introduire plus de bugs que ca en corrigerait. Donc non, a moins que l'equipe de Trinity decide de corriger ca, ce dont je doute, je n'y toucherai pas.

**Comment by Justforsoloq** [comment]
Je comprends peut être pas en fait. Actuellement le 4T10 lock ne marche tout simplement pas sur les dots. En quoi le corriger changerait l'ordre de l'application des buffs/debuffs ?

**Comment by joshwhedon** [comment]
OK en fait en plus je viens de verifier ... et ca marche tres bien.
J'applique la corruption en ayant 70840 sur moi, et tant que je garde la corruption, je garde le meme multiplicateur.
Donc en fait, ... c'est deja implemente et je sais pas comment tu as fait tes tests :D

**Comment by Justforsoloq** [comment]
C'est un ami qui m'a fait le report bug. Je vais emprunter son perso et faire les tests.
