### ISSUE TITLE
Boss: Léviathan des flammes HM

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#64]
**Description**
Maintenant faut que le boss soit sorti (les 2 colosses tués) pour pouvoir lancer le mode HM. (Eridium il a dit non c'est pas bien >:(, je crois que c'est à cause des 4 tours qui sont liées avec )

**Étapes de reproduction**
Entrer dans l'instance, impossible de confirmer le mode HM en parlant au PNJ,
Tuer les 2 colosses pour faire sortir le léviath et c'est bon c'est possible

**Comportement attendu**
Eridium : "ce qu'il faut faire c'est empêcher le gardian de lancer le mode HM si la rencontre est en cours"

**Comment by joshwhedon** [comment]
Ok je corrigerai ca. Comme j'avais dit j'ai pas pu tester le fix.

**Comment by Killyana** [comment]
en cours*
