### ISSUE TITLE
[Apply Aura : Mod Size %] Taille minimale ne peut plus dépasser un certain seuil

### ISSUE THREAD

**Issue by Sydahan** [way-of-elendil/3.3.5#640]
**Description**
Depuis ce jour (02/05/2020) je n'arrive plus à faire descendre la taille de mon personnage au delà d'un certain seuil, qui était possible la veille à la même heure, en respectant les mêmes conditions, et en rajoutant même.

**Étapes de reproduction**
-Application d'un "Petit festin" avec l'effet bien nourri
-Application d'un Elixir Brouillecaboche (sous la forme rappetissant le personnage joueur)
-Application de 7 "Huile de pygmée"

**Comportement attendu**
A partir du 6e stack d'huile de pygmée, le personnage joueur ne rapetisse plus. 

J'ai donc renouvelé en changeant l'ordre d'application des buffs (7 huiles de pygmée - Elixir brouillecaboche - Bien nourri) et la taille minimale est toujours plus grande que la veille.

J'ai essayé avec des Epices de bébé EN PLUS des trois items réduisant la taille de mon personnage, cele ne descend pas plus bas.

**Comment by joshwhedon** [comment]
C'est pas un bug c'est un correctif de Trinity. Voir https://github.com/TrinityCore/TrinityCore/issues/24040.
Sur offi il y avait une limite de taille minimum, parce que sinon le joueur devenait presque invisible apparament. Actuellement le minimum est mis a 0.1 de la taille normale. Si vous trouvez des sources indiquant qu'il s'agit pas du bon ratio, merci de les fournir et on adaptera.
