### ISSUE TITLE
[Bug] Minerai et mob inacessible

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#641]
Un minerai de cobalt est inaccessible sous le sol aux Grisonnes en 70.8 - 13.2
Il y a aussi un Sculpterune-de-fer https://woehead.way-of-elendil.fr/?npc=26270 sous le sol au même endroit

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/4e4a999e49fc7a9d0b55e19bd77fffd59683621a merci de l'avoir signaler
