### ISSUE TITLE
Druide - Don du fauve - Talent Marque du fauve amélioré

### ISSUE THREAD

**Issue by jol064** [way-of-elendil/3.3.5#642]
En tant que druide, en utilisant les points de talents pour "Marque du fauve amélioré", j'obtiens 20% puis 40% (deuxième point) d'amélioration de la marque du fauve.

En vérifiant le sort (popup qui s'affiche en passant la souris dessus), j'ai bien 20% et 40% d'amélioration, mais en lançant le sort, je n'améliore de du sort de base, donc pas des 20% et 40%.

Le problème est présent sur tous les rangs des sorts Marque de fauve et Don du fauve.

Je suis une druidesse, elfe de la nuit.

Merci et bonne journée !

**Comment by joshwhedon** [comment]
"En vérifiant le sort (popup qui s'affiche en passant la souris dessus), j'ai bien 20% et 40% d'amélioration, mais en lançant le sort, je n'améliore de du sort de base, donc pas des 20% et 40%."
Tu parle du tooltip sur les buffs en haut a droite ? Parce que le tooltip ne prend pas en consideration les modificateurs. Si tu matte tes stats elles seront correctes.

**Comment by jol064** [comment]
Oui, je parlais du tooltip.
Je n'avais pas vérifié dans les stats de mon perso.
C'est tout bon du coup !
Merci
