### ISSUE TITLE
L'offensive de Skettys

### ISSUE THREAD

**Issue by jol064** [way-of-elendil/3.3.5#643]
Lorsque je fais la quête "L'offensive de Skettys" à Shattrath, plusieurs vagues d'ennemis arrivent.

Lorsque le dernier est vaincu, la quête n'est pas validée.

Merci !

**Comment by Killyana** [comment]
Il faut juste tuer le dernier mobs pour valider la quête: Avatar of Terokk - On Just Died - Quest Credit 'The Skettis Offensive' 
Target=7 si qq d'autre tué le dernier mob la quête ne se validera pas.

La quête est mal scriptée, normalement sa store la target en quest taken, et en data set sa donne le credit au stored target

**Comment by jol064** [comment]
C'est tout bon, ça marche.

Merci !
