### ISSUE TITLE
Spell: Image miroir

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#645]
**Description**
55342
les images attaquent la dernière cible du joueur qui les invoque

**Comportement attendu**

En fait, j'aurais besoin d'infos pour expliquer ce comportement :

https://www.youtube.com/watch?v=CGl8B4dMxso&t=69s
7:40, le mage utilise le spell
L'élémentaire est sur le paladin mais les images sont invoqués avec le war en target
=> les images attaquent quand même le pal (trait de feu sur le pal à l'open) 
7:45-46, les images ont changé de target et commencent à cast sur le war (elles changent d'axe en fonction de la position du war, pas du pal)
Juste apres, polymorph sur le war, les images changent de target et retournent sur le pal(mais ça, ça y est déjà c'est ok)

**Comment by joshwhedon** [comment]
En pvp elles choisissent la cible la plus proche d'elle, en pve la cible sur laquel le joueur a le plus d'agro.

**Comment by Ischjgt** [comment]
Et du coup par rapport à la vidéo que je te montre?

**Comment by Ischjgt** [comment]
Sur La vidéo que je te montre, le pal est derrière le war quand le mage invoque les images et c'est le paladin qui est attaqué par les images

**Comment by Justforsoloq** [comment]
Perso j'ai des éclairs de givre à 300-400 (par image) en pvp ce qui semble similaire à la vidéo que tu montres.

**Comment by Justforsoloq** [comment]
J'avais pas compris que tu parlais pour le pop image MB.
Et par contre les images comme la gargouille peuvent se "contrôler" si un familier mage/dk est déjà invoqué via les macros petattack/petfollow
