### ISSUE TITLE
[Quête] Louveteau de la clairière de Tombeneige inaccessible

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#649]
Suite de https://github.com/way-of-elendil/3.3.5/issues/629

Ce problème est en effet réglé : le mob n'est plus là.
Mais un autre [Louveteau de la clairière de Tombeneige] est maintenant dans la hutte précédente et présente les même symptômes (est inaccessible aux joueurs) :(
Les coordonnées du nouveau : 43.5 72.1 (il ne bouge pas celui-là, enfin je crois)

**Comment by joshwhedon** [comment]
Les louvetaux ont un spawn aleatoire et bougent un peu. A chaque respawn il est possible qu'un ou deux d'entre eux se retrouvent dans les huttes. C'est a cause de la gestion des maps on y peut pas grand chose.
