### ISSUE TITLE
[Donjon] Entrée dans Gundrak

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#650]
Ceci est un bug mineur.

L'entrée dans le donjon de Gundrak se fait toujours par l'entrée sud ( 81.3 29.0 dans Zul'Drak )
L'entrée fixe attendue serait plutôt l'entrée nord ( 76.1 21.0 dans Zul'Drak )
Si l'entrée doit être aléatoire, ça ne fonctionne pas actuellement.

Le fait d'entrer et de sortir de l'instance nous met toujours dans l'entrée sud.

NB: Si l'entrée deviens aléatoire, alors la téléportation doit maintenir l'entrée choisie, sinon les joueurs feront une sortie / entrée dans le donjon via l'outil et reviendront toujours sur la même entrée, ce qui annule l'effet aléatoire.

**Comment by joshwhedon** [comment]
Elle est aleatoire deja, certains joueurs ont d'ailleurs ete surpris de se retrouver a des entrees differentes quand le changement a ete mis.
