### ISSUE TITLE
[Donjon] Utgrade (Vous n'appartenez pas à cette instance vous allez être téléporté dans 60s)

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#651]
Ce matin, avant le redémarrage, nous avons fait le donjon d'Utgrade en normal avec l'outil donjon.
Juste avant le dernier boss, ou au pull du boss, un message :
**Vous n'appartenez pas à cette instance vous allez être téléporté dans 60s**
à priori sur les 5 joueurs, et tout en étant encore tous groupés, mais je n'en suis pas sûr.
Du coup on s'est dépêchés de tuer le boss avant la fin du timer et des loots et dé-grouper rapidement.

Je n'ai aucune idée de comment et pourquoi c'est arrivé.
Pour les recherches éventuelles, le nom de mon personnage : Wierzbrowski paladin nain
Juste avant le boss j'ai transporté le healer avec un mammouth de voyage de la toundra, c'est peut être ça la raison, du coup la moto serait aussi à vérifier.

Je n'ai pas plus d'information.

**Comment by Killyana** [comment]
C'est la désactivation de l’inter-faction sur les donjons.

**Comment by Ferro3** [comment]
Bon à savoir, merci.
Et du coup si ça arrive au milieu du donjon ?
Il sera impossible de le terminer donc, ha oui c'est un problème.

**Comment by Killyana** [comment]
Faudra peut être désactiver l'inter_faction pour les donjons 80hm, comme ça le problème est réglé, et la garder sans désactivation pour tout le reste.

**Comment by joshwhedon** [comment]
Honnetement je crois pas que ca ait a voir avec l'interfaction. Vous avez rien fait de special ? Quelqu'un a degroupe / regroupe ? Une deconnexion ? Rien du tout ?

**Comment by Ferro3** [comment]
Non rien de spécial à part les précisions donnée dans le 1er post

**Comment by joshwhedon** [comment]
A premiere vue c'est du au systeme d'interfaction :( . Malheureusement pas grand chose qu'on puisse faire sur le sujet donc ca va continuer a arriver de temps en temps.
