### ISSUE TITLE
HT Ouest - Pack de squelette se transforme en serpent a leurs mort.

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#653]
Dans HT ouest sur le plateau ou le boss Illyanna Corvichene se trouve, il y a des pack de squelette non-elite, qui une fois mort se transforme en serpent, parfois dans un ratio de 4 serpent pop pour un squelette mort. Cela ne dois pas être très normal a mon avis.

Bon courage et merci.

**Comment by Killyana** [comment]
Pas un bug https://www.wowhead.com/npc=14370/cadaverous-worm#comments:id=1415427
Par contre la taille des vers bug, mais c'est truc général faudra voir d’où sa vient.
