### ISSUE TITLE
[Raid] EDC - Jaraxus ne se lance pas

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#654]
**Description**
Après avoir parler au pnj qui lance l’évent de jaraxus, une fois jaraxus invoqué par le gnome l’évent se stop et jaraxus reste figé sans rien dire/faire 

**Étapes de reproduction**
- Donjon : épreuve du croisé
- Niveau de difficulté : 10n
- Boss : jaraxus
- Sort en question : lancement du boss

**Comportement attendu**
Jaraxus est sensé tuer le gnome puisle combat doit se lancer

**Comment by joshwhedon** [comment]
C'est arrive comment ? Impossible de reproduire le probleme de notre cote. A quel moment l'event s'est arrete ? Quel fut le dernier texte ?

**Comment by joshwhedon** [comment]
Est-ce que Jaraxxus a insulte le gnome ? Ou ca s'est bloque avant ca ?

**Comment by Fairivier** [comment]
Non il n'a pas insulter le gnome, il est apparu a dit sa première réplique puis c'est freeze. Et je n'ai aucune idée de pourquoi il c'est freeze les bêtes c'était bien passer. Et je ne sais pas si ca peut aider mais le cadavre de glace hurlante n'a pas depop même après l'avoir loot

**Comment by joshwhedon** [comment]
Merci. 
https://github.com/TrinityCore/TrinityCore/issues/24552 a ete rapporte chez Trinity sur le sujet

**Comment by Fairivier** [comment]
d'accord merci

**Comment by joshwhedon** [comment]
Je peux pas faire grand chose pour ce probleme malheureusement, et pas de mouvement du cote de trinity. Il va malheureusement falloir faire avec.
