### ISSUE TITLE
[Joug] L’arrêt du siège

### ISSUE THREAD

**Issue by rommni** [way-of-elendil/3.3.5#655]
J'ai essayé aujourd'hui au joug de réaliser la quête hebdomadaire L’arrêt du siège. J'étais bien en défense (c'est la position prévu pour cette quête). Cependant j'ai détruit une 10aine de véhicules pendant la partie certains en les attaquants simplement, d'autres avec les canons sur les murs et d'autres encore avec les lances grenades LG-AG, aucunes de ces destructions n'a compté pour la quête. (Il me semble que je l'avais réalisé sans soucis la semaine dernière, à confirmer).

**Ressources additionnelles**
- Quête: https://woehead.way-of-elendil.fr/?quest=13185

**Comment by joshwhedon** [comment]
T'etais loin des vehicules quand ils etaient detruits ?

**Comment by rommni** [comment]
Parfois corps à corps parfois très très loin.
