### ISSUE TITLE
Mener la charge / Une nouvelle cible

### ISSUE THREAD

**Issue by Aloawan** [way-of-elendil/3.3.5#656]
Durant ces quêtes il est impossible d'abattre les ennemis qui nous attaquent ( gargouilles et factionnaires), ils évitent tous les tirs, on ne peut les tuer que quand ils apparaissent au loin avant qu'ils ne nous prennent en chasse.
Quand on passe en mode "Réparation" les sorts pour éteindre le feu et remettre le bouclier semblent rester sans effet.
Il arrive également que l'on s'éjecte de l'appareil quand on change de poste mais ceci est plutôt rare.

**Comment by joshwhedon** [comment]
MEme probleme que https://github.com/way-of-elendil/3.3.5/issues/478
