### ISSUE TITLE
Planter la lance de Hodir

### ISSUE THREAD

**Issue by Aloawan** [way-of-elendil/3.3.5#657]
Lors de cette quête le wyrm que l'on tente de tuer nous fait traverser le décor et au moment ou le combat prend fin (mort du wyrm ou de notre perso) on continue à tomber.
Seul l’arrêt brutal du client, alt - f4 permet à la reconnexion d'apparaitre au cimetière.

**Comment by Ischjgt** [comment]
J'ai eu un ticket pour me dire que ça arrivait encore hier

**Comment by joshwhedon** [comment]
Je peux rien faire de plus pour, c'est un bug avec les mouvements j'y peux rien.
