### ISSUE TITLE
Quest: Courses Gueule-de-dragon

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#662]
**Description**
Testé avec Trope le Rote-crasse 23342
Active AI: npc_trope_the_filth_belcher::npc_trope_the_filth_belcherAI
Quest : 11067

Le ticket parle de Murg "Oldie" Muckjaw Entry: 23340 également
Active AI: npc_murg_oldie_muckjaw::npc_murg_oldie_muckjawAI
Quest: 11064

et les autres : 
Name: Corlok the Vet
Entry: 23344.
Active AI: npc_corlok_the_vet::npc_corlok_the_vetAI
Quest: 11068

Name: Wing Commander Ichman
Entry: 23345.
Active AI: npc_wing_commander_ichman::npc_wing_commander_ichmanAI
Quest: 11069

Name: Wing Commander Mulverick
Entry: 23346.
Active AI: npc_wing_commander_mulverick::npc_wing_commander_mulverickAI
Quest: 11070

Name: Captain Skyshatter
Entry: 23348.
Active AI: npc_captain_skyshatter::npc_captain_skyshatterAI
Quest: 11071

Dit moi si tu as besoin que je test pour ceux là aussi

1. Cas où le NPC est bloqué après avoir prit la quête et que le NPC ait dit 
Trope le Rote-crasse dit : Trope va te montrer comment vole un vrai Gueule-de-dragon. Et toi, tu vas lui montrer comment meurt un traîne-savates.
Fait notable : il est desaxé par rapport aux autres NPCs
<img width="1224" alt="Capture d’écran 2020-05-04 à 07 35 03" src="https://user-images.githubusercontent.com/60295792/80938848-e43fe100-8dda-11ea-9b72-4bff162e5f0d.png">

2. On peut valider les courses sans avoir a bougé de l'endroit où l'on prend la quête du moment que l'on est en vol sur une monture 

**Étapes pour raproduire**

1. 
- Un joueur reçoit la mention rewarded sur sa quête
- Visible : Le NPC est désaxé
- Quelqu'un reprend la quête, le PNJ se bloque sur
Trope le Rote-crasse dit : Trope va te montrer comment vole un vrai Gueule-de-dragon. Et toi, tu vas lui montrer comment meurt un traîne-savates.
- Plus possible de reprendre la quête ensuite ou d'interagir avec le NPC

2. 
- Etre sur une monture volante et envol
- Prendre la quête
- Attendre que Trope revienne

**Comment by Ischjgt** [comment]
le 1. Tout pareil pour
Name: Murg "Oldie" Muckjaw
Entry: 23340.

Name: Trope the Filth-Belcher
Entry: 23342.

Name: Corlok the Vet
Entry: 23344.

**Comment by joshwhedon** [comment]
Va falloir me dire comment parce que moi j'ai pas le soucis. Ils finissent pas la course ?

**Comment by Ischjgt** [comment]
Si, comme dit en haut, ça se passe bien la première fois quand c'est reward, le NPC est de côté.
Pas sur mais je crois que les 3 étaient de coté également donc bugés juste après le crash

**Comment by joshwhedon** [comment]
Moi je finis la course et je peux prendre la recompense, ou bien abandonner et reprendre la quete sans soucis.

**Comment by Ischjgt** [comment]
Je sais pas, moi je finis la course et le NPC est bloqué, la course échoue et je peux reprendre normal, à chaque fois que je vais les voir depuis hier les 3 sont bloqués
