### ISSUE TITLE
Système: Hôtel des ventes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#663]
**Description**
Les tris par rareté, Niveaux, temps restants, Vendeurs et offres se font par page

**Comment by joshwhedon** [comment]
J'ai verifie cote serveur, il n'y a rien d'envoye au serveur pour notifier d'un tri, c'est le client qui s'en charge. Donc a premiere vue c'est blizzlike. Blizzard l'a surement voulu pour reduire la charge serveur et eviter que des gens fassent qu'acheter les trucs pas chers en boucle je suppose.
