### ISSUE TITLE
[Rogue] Attaques Focalisées sur absorb

### ISSUE THREAD

**Issue by Sebpp** [way-of-elendil/3.3.5#666]
**Description**
Le talent du rogue "Attaque Focalisées" lui donnant 2 d’énergies pour chaque coup critique en mêlée ne fonctionne pas sur les absorb (shield) 

**Étapes de reproduction**
- Un rogue avec le talent "Attaque Focalisées" en auto-attaque, sur un shield de prêtre ou pala. 

**Comportement attendu**
La description du talent précise à 3/3 : Vos frappes critiques en mêlée ont 100 % de chances de vous donner 2 points d’énergies. https://woehead.way-of-elendil.fr/?spell=51636

**Captures d’écran / Vidéos**
Aucune malheureusement je n'ai rien trouvé.

**Ressources additionnelles**

**Comment by joshwhedon** [comment]
Des preuves qu'il s'agit d'un bug ? En regle general, par defaut, une absorption complete ne declenche pas les procs (vu que ca ne "touche" pas vraiment, et dans le cas present, ca ne "critique" pas vraiment. Je n'ai rien trouve indiquant qu'attaque focalisee devrait proc sur une absorption complete.

**Comment by Justforsoloq** [comment]
Focused attacks ne prend en compte que le fait si la mélée crit ou non :
http://www.worldoflogs.com/reports/9uyqy7rsmyhaa5ey/xe/?s=1985&e=2157&x=sourceName%3D+%22Colegro%22+AND+(spell+%3D+%22Mutilate%22+OR+fulltype+%3D+SWING_DAMAGE+OR+fulltype+%3D+SWING_MISSED+AND+misstype+%3D+MISS_ABSORB)+OR+spell+%3D+%22Focused+Attacks%22&page=1

Log d'un assa sur les valkyrs (boss avec une phase d'absorb), on peut voir qu'il gagne de l'énergie même sur la phase d'absorb. 
(J'ai vérifié avec la mécanique du Jugement of the wise du palaret pour check si l'absorb des valkyrs étaient considérés comme une vraie absorb, et c'est le cas puisque le palaret ne gagne pas de mana via son jugement of the wise durant la phase d'absorb des valkyrs)

**Comment by joshwhedon** [comment]
Bon je me suis creuse la tete pendant 3 heures, et avec le systeme de proc actuel y'a pas moyen de corriger ca. Si je fais un changement pour que les critiques sur absorb soient pris en compte, ils seront pris en compte pour TOUS les procs (donc par exemple judgement of the wises procera sur critiques absorbes). Et si j'autorise attaques focalisees a proc sur les absorbs, ca procera sur les absorbs (meme non critiques). J'ai aucun moyen de corriger ce bug sans retravailler le systeme de proc en entier (et j'ai vraiment aucune intention de faire ca). Desole ce bug ne sera pas corrige a moins que l'equipe de Trinity ne change le systeme de proc en entier.
