### ISSUE TITLE
Quest: la première épreuve

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#669]
**Description**
9678 - [La première épreuve]  
Cela arrive sur d'autres quêtes, je sais pas si c'est général et j'ai plus les noms en tête mais j'ai trouvé là façon de reproduire ici. 
Cas où la quête est en complete dans le journal de quête mais toujours en active avec les commandes MJs et donc pour le NPC à qui rendre

**Étapes de reproduction**
a .q a 9678
b. active le brasero
c. .die le NPC qui spawn / 2 joueurs groupés et le joueur qui ne fait pas la quête tue le NPC qui spawn
- quête complete avec le texte jaune de l'objectif pour le joueur dans le journal mais seulement visuel (il y a bien marqué Objectif atteint d'ailleurs)
=> Il peut réactiver le gob 
=> S'il tue le NPC lui -même en ayant activé le brasero, "Objectif atteint" apparait en jaune sur l'écran du joueur qui fait la quête, la quête est complete

**Comment by Ischjgt** [comment]
Le objectif atteint apparait toujours (mais la quête n'est plus marqué en complete pour le joueur).

Ça peut poser problème pour les quêtes comme Shy-Rotam car cela a pour conséquence de ne plus afficher les infos encadrées dans mon screen pour les joueurs qui n'ont pas validé la quête (il faut faire +de 50% des dégats sur le mob pour valider)

<img width="185" alt="Capture d’écran 2020-05-09 à 15 42 24" src="https://user-images.githubusercontent.com/60295792/81475354-de4b6500-920b-11ea-9d13-82f8a1522902.png">

**Comment by joshwhedon** [comment]
C'est du cas par cas, il faut donner chaque quete qui est dans ce cas la.

**Comment by joshwhedon** [comment]
Donc est-ce que c'est encore un probleme pour la premiere epreuve ou pas ? Si non, il faut ouvrir un autre bug pour les autres quetes.

**Comment by Ischjgt** [comment]
Avant j'avais pas testé pour Shy-Rotam, mais pour la premiere épreuve c'était : Objectif atteint affiché au milieu de l'écran + le complete sur le journal de quête quand le NPC est tué mais pas par celui qui possède la quête
Maintenant, la première épreuve c'est : Objectif atteint affiché au milieu de l'écran seulement, quand le NPC est tué mais pas par celui qui possède la quête

Et ok je pensais que c'était un peu la même chose, pour Shy-Rotam c'est Objectif atteint affiché au milieu de l'écran quand le gob est activé par le joueur qui fait la quête, même sans avoir tué Shy-Rotam (mais la quête est pas validée)

**Comment by Babyface-187** [comment]
De nombreux joueurs se plaignent de ne pas pouvoir faire la quête. 
reproduction : 
activer le brasier
tuer le npc 
-méthode 1 : .die le npc > ne valide pas la quête
methode 2 : tuer le npc avec une arme ou un sort > valide la quête

La quête se valide donc, cependant elle reste active, et est donc impossible à rendre auprès du npc Bloodvalor (17717)
