### ISSUE TITLE
[Evasion de Fort-de-Durn HM] Mort envoie hors de l'instance

### ISSUE THREAD

**Issue by Zorbac** [way-of-elendil/3.3.5#672]
**Description**
Dans GT1 HM, mourir dans le donjon envoie dans le cimetière des Contreforts de Hautebrande, mais pas celui de l'instance, celui du "monde réel".
Il est donc nécessaire de prendre le mal de rez, de voler jusqu'à Fossoyeuse puis d'arriver à revenir jusqu'aux Grottes du temps. Comptez en moyenne 20 minutes de voyage pour revenir.
Et le crétin de dragon à l'entrée de l'instance ne veut même pas nous transporter une deuxième fois.

**Étapes de reproduction**
Entrer dans le donjon. Mourir.
- Donjon : Evasion de Fort-de-Durn
- Niveau de difficulté : héroïque
- Composition du groupe : un voleur 80, un druide 80 mort sur un pack de mobs devant la prison de Thrall.

**Comportement attendu**
Fantôme au cimetière à l'entrée de la Grotte du Temps

**Comment by Ischjgt** [comment]
Salut, tu es sur quel perso stp ? tu peux me MP sur Discord ?

**Comment by joshwhedon** [comment]
Tu es mort dans quelle zone du donjon ?

**Comment by Zorbac** [comment]
Au niveau de la route devant le petit fortin dans lequel Thrall est emprisonné.
On a eu des soucis de traversée de maps dans cette zone (plancher d'un étage, mobs qui volent à travers le pont de l'entrée...).
Ça pourrait être l'origine du bug ?
Dans le cas présent, je n'ai pas eu de traversée de map au moment de la mort problématique. Mais le voleur avec moi est mort comme ça et a fini dans le même cimetière hors instance.

**Comment by joshwhedon** [comment]
Le fait que vous avez eu des soucis de map me fait penser que c'est probablement notre soucis recurrant qui a eu lieu. On a fait des modifs sur les configs pour que ca regle le probleme. J'ai tester de mourrir un peu partout sans soucis jusque la donc on va esperer que ce soit regle.
