### ISSUE TITLE
NPC: Jazzrik

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#673]
**Description**
Le NPC donne de la réput même en étant révéré

https://wowwiki.fandom.com/wiki/Jazzrik
"he awards 5 reputation points for each kill. Jazzrik only gives reputation up to 20999/21000 revered"
https://fr.classic.wowhead.com/npc=9179/jazzrik#english-comments
9179 - [Jazzrik] 
87 - [La Voile sanglante frFR]

**Comment by Killyana** [comment]
Les données DB sont correctes: 5 reputation with Bloodsail Buccaneers (stops at Revered)
MaxStanding=6 Revered
The maximum standing that the creature will award reputation until. If the player achieves this standing or any other standing higher than this, the creature will not award any reputation.

**Comment by joshwhedon** [comment]
Bah c'est pas un bug. he awards 5 reputation points for each kill. Jazzrik only gives reputation up to 20999/21000 revered
Revered va jusqu'a 21000, il donne de la reputation jusqu'a 20999 en revere. Apres il donne plus.
