### ISSUE TITLE
NPC: Witch Doctor Unbagwa - La fièvre de strangleronce

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#677]
**Description**
https://woehead.way-of-elendil.fr/?quest=349
Name: Witch Doctor Unbagwa
Entry: 1449.

- L'event ne se passe bien qu'une seule fois.
id: 12380 [Canalisation de l'ombre] ne se fait pas quand on le relance
On peut quand même parler au NPC pour lancer l'event et se faire prendre un Croc de gorille

- Même la première fois, le NPC fait ses mimiques de quand un troll se met à parler mais il ne dit rien
Comportement attendu :
https://www.youtube.com/watch?v=1ynPlqsjlLo
2:30 crie quand on donne le croc :
> Get ready everyone! Here come the apes!

- Le nom sur Wowhead en fr c'est sorcier-docteur, ça colle d'ailleurs plus avec le nom en anglais

**Comment by joshwhedon** [comment]
@Killyana  le texte tu veux l'ajouter chez Trinity ou je fais juste un sql rapide de notre cote ?

**Comment by Killyana** [comment]
Le texte a été ajouté pour la version cata
Pour classic y'en a pas https://youtu.be/7pj1YH4WSVA

**Comment by joshwhedon** [comment]
Ha cool. Je vois dans cette video qu'il y a beaucoup plus de spawns non ?

**Comment by Killyana** [comment]
Oui, j'ai vue ça, je ne sais pas s'il y'a eu des changements sous bc et wotlk ou pas
Ca c'est le script actuel de la quête: https://github.com/TrinityCore/TrinityCore/commit/0da19d6a0455f05f2700478218fac704b8a0ce6a

**Comment by joshwhedon** [comment]
Le nom du npc en Francais par contre, je sais pas. Dans les textes de quete ils l'appellent sorcier docteur aussi donc je suis tente de le changer.

**Comment by joshwhedon** [comment]
Pas pu trouver le nom reel du npc en 3.3.5.
