### ISSUE TITLE
[Hordes / Recette Bâtonnet runique en adamantite] Le pnj sensé vendre la recette ne la propose pas.

### ISSUE THREAD

**Issue by zanzlibar** [way-of-elendil/3.3.5#680]
**Description**
_Rungor_ ( https://wotlkdb.com/?npc=18960 ) est sensé proposer la recette d'enchantement du _Bâtonnet runique en adamantite_  ( https://wotlkdb.com/?item=25848 ) en un exemplaire, disponible selon un laps de temps que j'ignore. 
Il s'avère que le pnj ne propose pas du tout la recette, on ne voit pas non plus d''icone "plus disponible", donc à priori la recette n'est tout simplement pas vendue. 

**Étapes de reproduction**
na

**Comportement attendu**
na

**Captures d’écran / Vidéos**
na

**Ressources additionnelles**
**Rungor** est au fort Brise-Pierre, Forêt de terokkar.
**Le temps de remise à disposition** de la recette doit  probablement être identique à celui de la transmutation du pouvoir primordial pour les alchimistes. ( https://wotlkdb.com/?item=23574 )
**nota bene** : C'est le **seul et unique moyen de se procurer cette recette**, les bâtonnets sont liés quand ramassés, et chaque bâtonnet requiert le précédent pour être fabriqué. Aussi, **l'absence de cette recette empêche toute progression au delà de 375 en enchantement côté hordes**.

**Comment by Killyana** [comment]
Il faut utiliser woehead vue qu'il utilise la DB du serveur https://woehead.way-of-elendil.fr/?npc=18960
Le pnj vend l'item mais un seul exemplaire est disponible, il faut attendre le restock qui se produit après une certaine durée que je connais pas.

**Comment by gtschanz** [comment]
je confirme je l'ai acheté hier l'item il me semble un peu avant toi^^désolé
