### ISSUE TITLE
Scholo : Pack la salle avant Vecus trop dense

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#682]
Bonjour,

Je pense que il y a beaucoup trop de pack dans la petite salle avec Vecus. C est tres dure de pas pull toute la salle d un seul coup du coup. Et de pas wipe a cause du nombre de npc impressionnant.

Merci

**Comment by Killyana** [comment]
Les spawns sont correctes, y'a une stratt pour faire ce boss: https://wow.gamepedia.com/Vectus
et les étudiants: https://www.wowhead.com/npc=10475/scholomance-student#comments
