### ISSUE TITLE
Scholo : Loot de l ecaille de dragon luisante drop 100%

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#684]
Bonjour,

Sur les dragonnets, l écaille loot a 100%, une quête répétable qui donne de la reput a l aube d argent.
Ca fait beaucoup d'écaille a chaque Scholo. ref : https://woehead.way-of-elendil.fr/?item=13920#dropped-by

alors que sur https://fr.classic.wowhead.com/item=13920/ecaille-de-dragon-luisante , le rate est de 21%
Ce qui semble plus réaliste :)

Bon courage, merci a vous.

**Comment by Killyana** [comment]
Ils ont augmenté le drop rate sous BC: https://classic.wowhead.com/item=13920/healthy-dragon-scale#comments:id=2674040
Il y'a 17 dragonnets en tout et le commentaire dit avoir loot 12, donc possible qu'ils ont éviter 4 dragonnets et que le drop rate est 100%

**Comment by Killyana** [comment]
Vue que le mob drop une écaille pour chaque joueur du groupe, le drop rate sera corrigé à 20%
