### ISSUE TITLE
NPC: Engin de livraison à propulsion D16 - Quand tout le reste à échoué

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#685]
**Description**
https://woehead.way-of-elendil.fr/?quest=12862
https://woehead.way-of-elendil.fr/?quest=13060
30487 - [Engin de livraison à propulsion D16] 
30477 - [Engin de livraison à propulsion D16] 
Testé côté alliance

Le véhicule est commandé, le joueur n'est pas censé pouvoir le controler pour aller voir le PNJ qui termine la quête

https://www.youtube.com/watch?v=EmW_72zioB8

**Comment by joshwhedon** [comment]
@Killyana  elle marche en local pour toi ? Etrangement chez moi ll'action de waypoint se lance, mais rien se passe au final.

**Comment by Killyana** [comment]
On a fixé ca avant mais le sql a disparut de nos scripts.

**Comment by Killyana** [comment]
Par contre je ne sais pas pourquoi l’effet : Apply Aura : Mod Vehicle Flight Speed %
Valeur : 200  de l'aura https://woehead.way-of-elendil.fr/?spell=55971  ne change pas la vitesse
