### ISSUE TITLE
renvoie spell war = bug // Sévérité Haute

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#687]
**Description**
Le war arrive à renvoyer avec son renvoie de spell des fin de dots qu'il a sur lui.

Exemple : faites un duel entre un war mettez lui une arme 1m + shield puis prenez un mage feu mettez lui une bombe vivante et à la avant la fin de l'explosion de la bombe vivante (fin du timer) faites renvoie de sort; le mage se mange l'explosion de la bombe vivante alors que cela est impossible; une fois la dot sur le war posé il doit obligatoirement mangé l'explosion il ne peut pas la renvoyer à partir du moment ou la dot est sur lui

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: war
- Race: all classe war
- Spécialisation: all spé
- Sort / Talent / Etc: renvoie de sort
- Circonstances (Donjon, Raid, PvP, autre): constaté en bg / en duel
- Equipement: shield + arme 1m
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**

Le renvoie de sort du war doit renvoyer tout les spells avant qu'ils ont été envoyé; une fois la dot sur le war il lui est impossible de renvoyer les dégâts; avec la bombe vivante actuellement il peut renvoyer l'explosion de fin de la dot. Ce qui est anormale

**Captures d’écran / Vidéos**

faites un duel entre un war et un mage

**Ressources additionnelles**

------

**Comment by gtschanz** [comment]
c'est même indiqué dans la description même du sort renvoie de sort que cela n'affecte QUE ''vous levez votre bouclier et renvoyez le prochain sort lancé sur vous'' or dans l'exemple de la bombe vivante elle est posé bien avant le renvoie

**Comment by joshwhedon** [comment]
Techniquement l'explosion a la fin c'est pas le meme sort mais bon, oui il devrait pas etre renvoye.
