### ISSUE TITLE
woehead - plutôt une suggestion

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#688]
Pourrait-on indiquer sur le woehead ce que contiennent certains objets ?

d'après le site wowhead il affirme qu'on trouve des perles noires dans ces palourdes en question; mais on ne peut pas corroborer les informations avec une sources issues du serveur way of elendil; serait t'il possible d'y remédier ? merci par avance

exemple:
![Capture d'écran 2020-05-06 16 53 28](https://user-images.githubusercontent.com/63243193/81192147-2a9f6680-8fba-11ea-9cce-575ecd4470a5.png)

**Comment by Endalaust** [comment]
Clique sur le spell "Utilise : Ouvrez la palourde !"

Ca t'affichera cette page : https://woehead.way-of-elendil.fr/?spell=58165#contains

Et ... Voila :)
