### ISSUE TITLE
Gob: Shallow Grave - Zul'Farrak

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#689]
**Description**
 [Shallow Grave] ID: 128308
128972 - [Shallow Grave TRAP]  ?

Il est possible de faire spawn les monstres dans les tombeaux piégés à l'infini si les objets dedans ne sont pas ramassés

**Comment by joshwhedon** [comment]
Et c'est un bug ?

**Comment by Ischjgt** [comment]
désolé vidéo cata
https://www.youtube.com/watch?v=XwfR-NL5ANA

- En fait les gobs vident qui sont pas des traps sont pas censés disparaitre
=> cf première tombe ramassée vers 50 secondes
- Par contre les gobs trap disparaissent bien quand ils sont vident et les mobs sont spawn qu'une fois
=> 2:55 le gobelin ramasse la tombe, cette même tombe est vidée par le tauren vers 3:05

**Comment by joshwhedon** [comment]
MErci

**Comment by Ischjgt** [comment]
Le comportement maintenant :
1. On clique sur la tombe, si elle est piégée, les mobs apparaissent,
2.La tombe reste mais n'est plus cliquable, quand les mobs meurent, on peut recliquer sur la tombe
=> C'est de nouveau le tirage au sort, si elle est encore piégée, ça repasse au 1.
