### ISSUE TITLE
Battleground: Joueur seul

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#690]
**Description**
Ça arrive assez souvent donc je le poste, même si j'ai pas réussi à reproduire.

Cas où un joueur qui rejoint le BG en aléatoire ne voit personne dans le BG
+ "ne pas pouvoir prendre de bases et de ne pas pouvoir monter sur une monture"
C'est arrivé au moment où j'écris ce ticket, sur Carpentras à l'œil et juste avant en Arathi

Il était dans la même phase, j'ai pas le list aura complet  sorry,
le joueur ne faisait rien avant de rejoindre le BG, il venait de se co à Dala puis il a rejoint direct.
Il voyait le BG déjà ouvert (pas de nouveau BG)

Le problème semble arriver plusieurs fois de suite mais Alt+F4 suffit pour revenir à la normale

**Comment by joshwhedon** [comment]
Va me falloir un peu plus que ca. Est-ce que les autres joueurs le voient ? Est-ce qu'un .unaura all regle le soucis ? Est-ce qu'un /reload regle le soucis ?

**Comment by Ischjgt** [comment]
Les autres joueurs ne le voient pas.
Pour le reste je te tiens au courant :p

**Comment by Ischjgt** [comment]
> Voila le soucis que j ai en bg oeil du cyclone:. apres le debut du bg je me suis trouvé dans une sorte de bulle imaginaire de genre 10m a la ronde qui faisait disparaitre les gens qui entraient dedans. Je pouvais voir les gens au loin et eux aussi, mais en s approchant on disparaissait mutuellement. un genre de dimension paralelle. 2eme bg meme soucis, oeil du cyclone toujours. 

Unaura all a rien fait
(C'est pas arrivé pendant le problème de chargement de maps)

**Comment by joshwhedon** [comment]
Et du coup le gm le voit ? Et le voit avec les autres joueurs ? Ou dans une map differente ?

**Comment by Ischjgt** [comment]
Je voyais le joueur avec le problème et les autres joueurs.
C'est pas réapparu depuis 12 jours

**Comment by Kwyzard** [comment]
ça m'arrivais encore la semaine dernière (1 fois en arène nagrand et une fois en battleground cyclone) , grosso merdo enfaite le serveur pense que tu est au spawn et toi tu peux te balader ect c'est pas que tu voit pas les joueurs c'est que coté client tu bouge et tu t'éloigne du spawn donc tu voit plus a partir de X mettres genre en arène aucun problème je voyait bien les gens mes mates comme mon ennemies mais coté serveur tu ne bouge pas mon mate me voyait au spawn, jpouvais me heal moi et mon mate si il venait près du spawn

**Comment by joshwhedon** [comment]
Ne semble plus s'etre reproduit.
