### ISSUE TITLE
Boss: Hadronox

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#692]
**Description**
Quand Hadronox utilise Web Grab sur les araignées il les despawns se qui le fait sortir du combat (evade), ceci explique le spam des logs #reports

Le spell Web Grab ne doit toucher que les joueurs normalement

SPELL_WEB_GRAB                          = 57731,
https://imgur.com/jAjNke7

**Comment by Ischjgt** [comment]
1:30
https://www.youtube.com/watch?v=ewJEd-L7Mg0
On voit le grab sur les adds mais ça leur fait pas grand chose

**Comment by Ischjgt** [comment]
Je pense que les adds sortent même quand les joueurs ne sont pas là, le problème avec les logs #reports est toujours là

**Comment by Ischjgt** [comment]
Le spell touche les familiers des joueurs. Les familiers ont le même comportement qu'avec les araignées quand elles étaient grab quand Killyana a écrit ce ticket (et c'est ce qui fait bloquer le boss en bas)

**Comment by joshwhedon** [comment]
Y'a aucune raison que le sort n'affecte pas les pets.

**Comment by Ischjgt** [comment]
Ok, en tout cas le grab fait passer les pets sous maps, et je sais pas pourquoi mais pour cette raison, si un familier est grab quand les scarabées sont encore en vie, le boss reste en bas. Le message en jaune s'affiche mais il reste en bas
