### ISSUE TITLE
Spell: Yeux de la bête

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#693]
**Description**

Ticket: 16550
> bonjour,
quand j'utilise mon sort "yeux de la bete", a chaque fois que je fais une attaque ou que mon familier se fait taper je suis obligé  de retourner auprès de mon personnage (sans que je puisse controler mon familier) puis seulement la je peux de nouveau attaquer, et ainsi de suite...

id: 1002 [Yeux de la bête] 
Le sort fait quitter le combat au pet, les mobs qui l'attaquent ne le focus plus et fait passer le pet en Passif et en Reste à chaque fois que le joueur prend le controle du familier, ça peut venir de là
(quand la canalisation est finie, le familier revient en "Suis" mais reste en "Passif")

**Comment by joshwhedon** [comment]
C'est suppose etre quoi le comportement normal en fait ?
