### ISSUE TITLE
Spell: Frenzy - Gangr'orc néophyte - Fournaise de sang

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#696]
**Description**

id: 8269 [Frénésie] est cast à 100% de la vie de 17429 - [Gangr'orc néophyte] 

C'est le même spell utilisé pour 15369 - [Ayamiss le Chasseur]  et il marche correctement sur lui

**Comportement attendu**

à 15% de sa vie

**Comment by Ischjgt** [comment]
Il est pas du tout cast par
https://woehead.way-of-elendil.fr/?npc=17799

**Comment by joshwhedon** [comment]
Ajout du sort a 17799
