### ISSUE TITLE
 Boss: Dévoreur d'âmes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#698]
**Description**
Name: Devourer of Souls
Entry: 36502.

Je refais un ticket parce que c'est sensiblement différent de celui-ci
https://github.com/way-of-elendil/3.3.5/issues/613 est réglé,
Mais il y a toujours un cas où le boss meurt en l'air

Du coup nouvelle description : 
Le boss fait un spell comme le piétinement du géant de givre, j'ai pas pu trouver lequel c'était et j'ai rien à propos dans le recount.

=> le boss peut faire un autre spell pendant ce saut, ce qui va le garder en hauteur un peu plus longtemps que prévu. Le tuer à ce moment le laisse en haut.
(=> J'ai l'impression qu'à cause de ce saut et quand cette situation arrive, le boss peut ensuite utiliser toutes ses facultés en même temps)

**Comment by joshwhedon** [comment]
Je vois aucun sort qui fasse sauter le boss ou quoi que ce soit du genre

**Comment by Ischjgt** [comment]
Je sais pas si tu as apporté une correction ou non
Mais oui comme je t'ai dit j'ai rien à propos du saut nul part, mais cf ma vidéo que je t'ai envoyé  en mp sur Discord du coup

Eridium
> Suffit d'ajouter disablegravity pour le boss et sa sera corrigé
Quand j'ai ajouté le fall mouvement pour les mobs morts, je l'ai fait que pour ceux qui volent ou ont disablegravity
