### ISSUE TITLE
Quête : Réservoir de Glisseroc

### ISSUE THREAD

**Issue by Reveillark** [way-of-elendil/3.3.5#699]
Bonjour, j'ai eu un problème sur la quête ["Disparus au combat"](https://woehead.way-of-elendil.fr/?quest=9738) qui consiste à retrouver les compagnon d'une elfe de la nuit de l'expédition cénarienne dans le réservoir de Glisseroc dans le Marécage de Zangar. En effet, parmi eux, le druide [Implorateur céleste Griffe](https://woehead.way-of-elendil.fr/?npc=17894) est retenu prisonnier par le troisième boss de Basse-Tourbière, et en théorie il faut affronter Griffe et le mettre low life pour qu'il devienne amical. Or je l'ai tué, et ça ne m'a pas compté la quête.

**Comment by joshwhedon** [comment]
Bonjour. J'ai teste le pnj. Il faut lui faire des degats sans le tuer (ca peut etre un peu dur a haut level). Si il est blesse alors que le miniboss est mort, le pnj quittera le combat et se transformera.
