### ISSUE TITLE
Aura trincket porte-mort

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#700]
Léger soucis au niveau des auras appliquées par https://woehead.way-of-elendil.fr/?item=50363#see-also ou https://woehead.way-of-elendil.fr/?item=50362
En effet, seules les auras suivantes permettent d'utiliser une monture (volante et terrestre): 
https://woehead.way-of-elendil.fr/?spell=71558
https://woehead.way-of-elendil.fr/?spell=71486
https://woehead.way-of-elendil.fr/?spell=71561
https://woehead.way-of-elendil.fr/?spell=71484
Les suivantes provoquent le message d'erreur suivant : "Vous ne pouvez pas utiliser une monture quand vous êtes sous une autre forme !"
Voici les auras concernées : 
https://woehead.way-of-elendil.fr/?spell=71492
https://woehead.way-of-elendil.fr/?spell=71485
https://woehead.way-of-elendil.fr/?spell=71556
https://woehead.way-of-elendil.fr/?spell=71560

**Comment by joshwhedon** [comment]
Les donnees clients indiquent que les formes de vrykul ne peuvent pas monter sur des montures. Donc a moins de me fournir une preuve qui demontre que sur offi en 3.3.5 on pouvait monter en forme de vrykul, les donnees client font loi.
