### ISSUE TITLE
Buff racial Présence héroïque

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#701]
Le buff racial draenei https://woehead.way-of-elendil.fr/?spell=6562 et/ou https://woehead.way-of-elendil.fr/?spell=28878 n'augmente pas les chances de toucher de 1%.
Étape pour reproduire : 
Créer un draenei, se connecter sur un autre compte en même temps comparer le score de toucher sur l'autre perso lorsque le draenei est à portée du buff et lorsqu'il est éloigné. Le buff est bien présent sur les deux joueurs mais aucune modification n'est visible.

**Comment by Justforsoloq** [comment]
Si tu parles du toucher dans la fiche carac, c'est normal qu'il ne soit pas là. C'est le même principe que le % hit des talents.

**Comment by Ischjgt** [comment]
16.28%, un sans le buff, l'autre avec.
Il est facile de perdre le buff Présence Héroïque si le joueur est trop éloigné du raid

<img width="257" alt="Capture d’écran 2020-05-08 à 20 08 24" src="https://user-images.githubusercontent.com/60295792/81435780-afc87e00-9168-11ea-8dd9-fd6b83bfc689.png">
<img width="354" alt="Capture d’écran 2020-05-08 à 20 14 39" src="https://user-images.githubusercontent.com/60295792/81435783-b1924180-9168-11ea-9503-489b234dd09a.png">

Par contre je laisse le ticket ouvert parce qu'une fois le draenei mort, le groupe reçoit quand même le % de toucher 
"
To cover a lot of previous comments.

Hitcap for 2H Weapons, or for hunters is 263 Rating, or 8%
With a draenei that is 230 Rating, or 7%

For a Hunter with 3/3 Focused aim and no aura the cap is 5%, or 164 rating
Or for a hunter with both the cap is 4% or 132 rating

You should never rely on any other draenei's aura to be hitcapped when it takes such a low rating, As the draenei may die, or be standing too far away for the aura to affect you.
Yes, If the draenei dies you lose the aura (Just like all other auras, why did someone feel the need to ask?)


"
https://fr.wowhead.com/spell=6562/pr%C3%A9sence-h%C3%A9ro%C3%AFque#english-comments
