### ISSUE TITLE
les critiques sur le sort drain d'âme

### ISSUE THREAD

**Issue by jarraxuss** [way-of-elendil/3.3.5#705]
bonjour, je pense ( mais ne suis pas sûr ) que le drain d'âme https://woehead.way-of-elendil.fr/?spell=47855 possède un bug au niveau de son taux de critique, je ne trouve aucune source que ce soit sur wowhead ou sur woehead qui donne le taux critique de ce sort ( ou alors j'ai mal chercher ) donc je me dit que ce sort possède 100% de critique par rapport au critique du joueur. après 300 tick de dégâts j ai fait 300 touche et 0 critique bien que j'ai 30% de critique et que toute les 3 min j'utilise le bijou cristal de glace perpétuelle https://woehead.way-of-elendil.fr/?item=50259 qui monte mon critique a 50% 
https://ibb.co/4TS3wVV
peut être que je fais erreur et que c'est voulu mais dans ce cas caserait cool de le préciser quelque part ^^

étape de reproduction prendre un démoniste de n'importe quelle race ( ici mort-vivant ) et lancer le sort drain d'âme sur une cible

comportement attendu 
je pense que le drain d'âme devrait avoir une chance égale aux chance de critiques du joueur de faire des dégâts critique.

**Comment by joshwhedon** [comment]
Le drain d'ame est un dot, les dots, par defaut, ne font pas de critique, a moins qu'il soit precise qu'ils peuvent critique, ou d'avoir un talent qui leur permet de critique.
