### ISSUE TITLE
Voleur finesse —> bug pas de l’ombre 

### ISSUE THREAD

**Issue by Fufurette** [way-of-elendil/3.3.5#71]
**Description**
Décrivez le problème de façon claire, précise et concise.

Mon problème concerne les voleurs spé finesse. 
En utilisant le sort « pas de l’ombre » contre des mobs, le spawn du voleur doit apparaître juste devant celui du mob et non derrière.
Conclusion, au lieu d’engager le combat contre un mob, c’est le mob qui engage puisqu’il tape le voleur et le défufute. 
Je n’est eu ce problème que sur ce serveur.

J’ai un voleur elfe de sang, je ne sais pas si ce bug n’est que pour cette race ou d’autre. 

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe
- Race
- Spécialisation
- Sort / Talent / Etc
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Décrivez le comportement attendu de façon claire, précise et concise.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Killyana** [comment]
J'arrive pas à comprendre le bug, le sort https://woehead.way-of-elendil.fr/?spell=36554 dit: Vous tentez de marcher à travers les ombres et de réapparaître derrière votre ennemi. Votre vitesse de déplacement est augmentée de 70% pendant 3 s. Les dégâts de votre prochaine technique sont augmentés de 20% et la menace générée est réduite de 50%. Dure 10 s.

**Comment by Fufurette** [comment]
Oui sauf que quand on utilise ce sort, le voleur ne réapparaît pas derrière l’ennemi mais juste devant. 
Qui dit juste devant dit que le mob (ou le personnage joueur, je n’ai jamais essayé en pvp) engage le combat et non le voleur. 
Embêtant quand la majeur partie du dps finesse requiert le camouflage. 

Et oui pardon de m’être mal exprimé sur le premier post ... c’est incompréhensible :/ je me suis tout inversé.

**Comment by Killyana** [comment]
C'est corrigé sur la merge

**Comment by Fufurette** [comment]
C’est à dire le problème est corrigé ? 
Je peux utiliser le sort et réapparaître derrière l’ennemi dès maintenant ?

**Comment by Ischjgt** [comment]
Hello, non, il faut attendre la mise à jour du royaume qui aura lieu prochainement. Tu peux check sur notre site ou sur le Discord pour voir si elle a été passée. Si tu rencontres un soucis en jeu n'hésite pas à me contacter sur Discord. Bon jeu.

**Comment by Endalaust** [comment]
cf https://forum.way-of-elendil.fr/viewtopic.php?id=2798

**Comment by Fufurette** [comment]
Merci des réponses rapides, précises et de prendre en considération ma requête dans un délais très bref :) 

GG le staff !!
