### ISSUE TITLE
Scholomance : Salle du boss / Mob nuage de poison.

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#712]
Dans la salle adjacente au boss, Les mob qui font pop un nuage de poison sont OK, mais le nuage en question ne fait aucun dégât.

**Comment by joshwhedon** [comment]
Va falloir plus de details parce que je vais pas me taper tous les mobs de la Scholomance. Quel boss ? Quelle salle ? Quel mob ?

**Comment by Notil78** [comment]
Oui pardon.

Dans la salle du Docteur Theolen Krastinov, il y a des goules verte, qui quand elle meurt font pop un nuage de poison (jusque là tout est ok), sauf que le nuage ne fait aucun dégât.

[https://wow.zamimg.com/uploads/screenshots/small/39179.jpg](url)

**Comment by Ischjgt** [comment]
https://woehead.way-of-elendil.fr/?npc=10495
On death cast
17742
