### ISSUE TITLE
[PNJ] Messager tombe-hiver

### ISSUE THREAD

**Issue by Unicorn-Dklicieux** [way-of-elendil/3.3.5#715]
Depuis aujourd'hui les messager tombe-hiver ce sont mis à voler en suivant leur path, quand le terrain baisse de hauteur, il reste au même point, je pense qu'il sont donc restés à la hauteur la plus haute de leur parcours.

**Comment by joshwhedon** [comment]
Soucis de map probablement a cet endroit particulier, on y peut pas grand chose.
