### ISSUE TITLE
Cendreglace (enchant arme dk) augmente les dégats mais ne consumme pas

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#718]
**Description**
Cendreglace (enchant arme dk) qui augmente de 20% les deux prochains spells de froid ou d'ombre n'est pas consumé par le voile mortel (mais augmente bien les dégâts de ce dernier de 20%)

**Étapes de reproduction**
Prenez un dk, faites proc cendreglace puis lancez des voiles mortels et regardez.

**Comportement attendu**
Un voile mortel consomme une charge de cendreglace

**Ressources additionnelles*
https://db.rising-gods.de/?spell=17926&locale=2
https://db.rising-gods.de/?spell=53386

**Comment by joshwhedon** [comment]
Je mets un correctif pour, faudra me dire si ca fait drop des charges de facon incorrecte par la suite (genre sur des sorts qui devraient pas drop de charges),
