### ISSUE TITLE
Aspect vipère - pas de regen mana sur 2 sorts 

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#720]
**Description**
L'aspect de la vipère SpellID 34074 ne proc pas sur les ticks du tir explosif ( ni sur les dégâts lors de la pose du dot ) et sur l'application initiale de la morsure du serpent.

**Étapes de reproduction**

- Classe : Chasseur
- Race : toutes
- Spécialisation : Survie 
- Sort / Talent / Etc : Aspect de la vipère , tir explosif , morsure du serpent

**Comportement attendu**

La regen de mana est octroyée sur chaque tick du tir explosif et sur la pose de la morsure du serpent

**Ressources additionnelles**
https://github.com/TrinityCore/TrinityCore/issues/18129 ( un ticket initialement sur la salve + vipère )
https://wow.gamepedia.com/Aspect_of_the_Viper 

Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, but not including the ticks of Serpent Sting or the damage of Volley) to generate a percentage of the Hunter's maximum mana.

**Comment by joshwhedon** [comment]
Ca marche deja avec morsure du serpent. Je corrige pour le tir explosif.
