### ISSUE TITLE
Cristal de météorite - Guide de lumière

### ISSUE THREAD

**Issue by saltyrykko** [way-of-elendil/3.3.5#723]
Le cristal de météorite (https://woehead.way-of-elendil.fr/?item=46051) est censé double stack grâce au guide de lumière, ce qui n'est actuellement pas le cas. 

**Comportement attendu**
Les stacks devraient augmenter 2 par 2 grâce au guide de lumière, ce qui permet d'atteindre les 20 stacks avant la fin du buff. 

**Ressources additionnelles**
Source : mon ancien BT

**Comment by joshwhedon** [comment]
Va me falloir quelque chose de plus precis que "mon ancien BT". Tu as des preuves que ca doublait sur offi ?

**Comment by saltyrykko** [comment]
Les mêmes sources que sur mon ancien BT : 

- https://www.wowhead.com/item=46051/meteorite-crystal#comments

"eleventhseed on 2009/07/18 (Patch 3.1.3)

procs 2 stacks if cast on a target when there's another target with beacon of light nearby, making it quite easy to achieve 20 stacks with fol after roughly 10 seconds"


"By frmorrison (37,767 – 4·41·446) on 2009/07/09 (Patch 3.1.3) 

For a Paladin, if Beacon of Light is up you get 2 stacks per heal (so it will stack fast even if using Holy Light)."

"By Etherius (1,554 – 5·19) on 2009/11/02 (Patch 3.2.2) 

Figuring out the fastest way to stack procs with this trinket is a wasted effort. The best use is to use it on cooldown while performing your normal routine since, if you're going for the most stacks in the least time, unless you are a Paladin (Beacon of Light) you will not be getting as much throughput as you should be doing.

Paladins luck out with this trinket since Beacon counts as a second spell. A well geared one (with 1.3s Holy Lights) will reach 20 stacks in 13 seconds performing the normal routine."

"By cadapter (501 – 8·6) on 2010/10/13 (Patch 4.0.1) 

It appears in 4.0 that the stacks don't double dip with Beacon anymore :("

- https://youtu.be/jv93ko3WeK8?t=171
