### ISSUE TITLE
Talent: Lucioles améliorées

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#724]
**Description**
[13:30:03] 33602 - [Lucioles améliorées, rank 3 frFR]
Message "un sort plus puissant est déja actif" quand on veut poser le débuff Lucioles 770 et qu'un autre débuff de ce style, même moins efficace est présent

Seulement au rang 3

**Comportement attendu**
Ça marche correctement pour les autres rangs
Si un sort est moins/autant efficace il est remplacé
Si un sort est plus efficace, il est posé mais pas remplacé

**Comment by joshwhedon** [comment]
Autre debuff de ce style = ? Un exemple precis ?

**Comment by Ischjgt** [comment]
Lucioles ^^'

**Comment by joshwhedon** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24592
