### ISSUE TITLE
Dispel des dots offensifs à la mort du lanceur

### ISSUE THREAD

**Issue by Sebpp** [way-of-elendil/3.3.5#725]
**Description**
J'ai remarqué le problème aujourd'hui en BG ( à mon avis c'est très récent ). Lorsque le lanceur d'un sort de type DOT meurt, tous ses dots actifs sont dispels des adversaires. 

J'ai fait un test avec un DK : il me met toutes ses maladies ( 20 sec de dot environ ), à l'instant ou je le tue il reste 15/16 sec de dots, et ces derniers disparaissent instantanément sur moi.

**Étapes de reproduction**
N'importe quelle classe à dot mourant alors qu'il a encore des dots actifs sur des adversaires 
(maladies, saignement etc)

**Comportement attendu**
Les dots doivent rester sur les adversaires conformément à leurs durées initiales.

**Comment by Ischjgt** [comment]
C'est tous les débuffs
et
Lorsqu'un mage (hordeux) [vol de sort] le [courroux vengeur] d'un palandin (allianceux), lorsque le paladin meurt, le courroux vengeur est dispell sur le mage
hors il devrait rester pour la durée du buff
mais là le lanceur du sort est toujours considéré comme "propriétaire" du sort volé
