### ISSUE TITLE
Proc Bryntroll cassé

### ISSUE THREAD

**Issue by Elahbienscript** [way-of-elendil/3.3.5#728]
**Description**
L'arme en question proc 2 fois plus que ce qu'elle devrai, elle est sencé faire ~8% du dps maxi.
**Étapes de reproduction**

- Dk spé Impie

**Comportement attendu**
15% de proc est attendu, elle est à 35% de proc sur 100 attaque avec un cycle dps normal.

**Captures d’écran / Vidéos**
![Bryntroll](https://user-images.githubusercontent.com/63306323/81509047-43848080-9308-11ea-86a8-6f49bb47026a.PNG)

**Comment by Justforsoloq** [comment]
D'ailleurs elle peut aussi triple proc sur un tourbillon de war touchant 3 cibles.

**Comment by saltyrykko** [comment]
C'est censé proc sur quasiment tous les trucs présents dans le recount que tu as posté

**Comment by Justforsoloq** [comment]
J'vous mets le lien avec le TC d'un mec en 3.3.0 si vous voulez plus d'info : 
https://fr.wowhead.com/item=50415/bryntroll-le-m%C3%A9diateur-dossements#english-comments

The theorycrafting on this potent weapon is still rather sparse, so I spent several hours testing the limits of the proc and it's dps contribution. First off, the basics:

    The 264 version proc has an average damage of 2250, while the 277 version has an average of 2538.
    The damage does not scale with any character stats (though the dps does, more on that below).
    The damage does scale with any percentage damage increases that affect spell damage, such as Avenging Wrath, Curse of Elements, Blood Presence, etc.
    The drain can proc off of any weapon attack, as well as some odd events such as applying or refreshing effects such as deathknight diseases or the paladin talent Righteous Vengeance. These odd events do have some requirements though. The drain can proc off of the refreshing of some DoTs or debuffs so long as the character is within melee range of and facing the target for the drain. Specific to the deathknight class, the drain can proc off of the disease application of Icy Touch (assuming you are in melee range), can double-proc off Plague Strike (the strike and the disease application), and on each target that is in melee range and in front of you from Pestilence.
    The drain has a base proc rate of 2 procs-per-minute, or 11.3333% chance per swing, and has no internal cooldown.
    The drain can proc multiple times per attack, provided there's are more than one weapon event for the attack. For example, the drain can multi-proc off the following:
    - On any or all of the multiple targets of Cleave, Whirlwind, Divine Storm, Heart Strike, or Sweeping Strikes.
    - From a melee (or special) and it's subsequent seal proc, Blood-Caked Blade proc, or Windfury proc.
    - From both the physical and shadow portions of Scourge Strike.
    The drain can not proc from any spells, excluding the odd events mentioned above.
    The drain is incapable of critting and functions on the spell hit table. However, it doesn't seem to be resistible.

Now, with a 2 PPM baseline, the weapon will deal 2 procs a minute before any waste or special attacks or talents are factored in, giving it a minimum dps of 75. In practice, the proc will usually provide between 200 and 400 dps, depending on the character's haste rating, spec and rotation (and therefore number of procable attacks per second), spell hit chance, and +damage buffs present. A good estimate is that it will provide approximately 4-8% of a character's dps. For many classes, this means the proc is worth the equivalent of between 400 and 800 additional attack power, though it's place on the best-in-slot list is strongly dependent class, spec, haste rating, and rotation. In general is can be assumed to be near the top of the list, however, as the proc itself provides a fairly respectable amount of dps while also making it easier for the healers to keep you alive through miscellaneous raid damage.

References
Melee/BCB Doubleproc
Scourge Strike Doubleproc
Heart Strike Doubleproc
PPM Recount Parse

**Comment by Justforsoloq** [comment]
J'avais posté un TC de la byntroll via 
https://fr.wowhead.com/item=50415/bryntroll-le-m%C3%A9diateur-dossements#english-comments 
mais j'ai lu ça ensuite (même post) : 
Reading bluetracker today, Rets and unholy DKs will be getting "bug fixed" so instead of doing 6-8% of total damage, it should be 3-4%. "We have found a bug with Bryntroll where it procs too often for Retribution paladins or Unholy DKs. For example both portions of Scourge Strike could cause a proc, which is unintended." Source Edit: Seems like they've hotfixed it already, it's doing 3~4% of my total damage now.

**Comment by Ischjgt** [comment]
https://area.way-of-elendil.fr/flyspray/index.php?do=details&task_id=3304
https://area.way-of-elendil.fr/flyspray/index.php?do=details&task_id=3300
https://area.way-of-elendil.fr/flyspray/index.php?do=details&task_id=2726

**Comment by Justforsoloq** [comment]
March 10, 2010
This entire expansion has similarly followed this pattern of people wearing raid gear to PvP and putting out game breakingly huge amounts of damage. For example, unholy DKs with Bryntroll before the proc nerf.

**Comment by Justforsoloq** [comment]
Par rodalpho (30,381 – 9·37·488) le 2010-02-10 (Mise à jour 3.3.2)
Bryntroll has been through several rounds of nerfs. As of 3.3.2, the proc is quite rare. In consequence this item is now the worst ilvl 264 2H weapon for ret pallies, DKs, and warriors if you can use most of the itemization on its replacement. For example, if you can regem/gear to use the hit on Cryptmaker without going too far over the hit cap, Cryptmaker is a far better weapon. Shadow's Edge and the Arthas weapons are better in every way.

**Comment by joshwhedon** [comment]
Je lui mets un cooldown de 500ms, on verra ce que ca change.

**Comment by Elahbienscript** [comment]
Et bien c'est encore plus fumé là, 1ere source de dmg sur un duel c'est le proc....
![Bryntroll](https://user-images.githubusercontent.com/63306323/81721900-e3651a00-9480-11ea-96e0-aaa5be5d5b45.PNG)

**Comment by Elahbienscript** [comment]
et surtout la rési n'est pas prise en compte donc le proc traverse la rési c'est un peu trop abusé..

**Comment by Elahbienscript** [comment]
avec les proc infini qui mettent du 3k sur la brynt hm, ca fosse les duels/arènes c'est un peu dommage

**Comment by joshwhedon** [comment]
LA resilience est prise en compte comme pour tous les

**Comment by joshwhedon** [comment]
Le proc prend bien en compte la resilience.
