### ISSUE TITLE
[Ulduar 25] - Kologarn - Poigne de Pierre

### ISSUE THREAD

**Issue by Lirae** [way-of-elendil/3.3.5#729]
**Description**
La Poigne de Pierre ne relâche pas les personnes grab, peu importe le nombre de dégâts reçus par le bras droit, soit 3 morts inévitables à chaque grab.

     Sort en question : 
Poigne de pierre : Saisit 3 personnes qui ne peuvent plus rien faire et inflige 5k5/sec pendant 10 sec. puis inflige 100k. Pour éviter le OS des personnes emprisonnées, il faut dps le bras. Il faut lui enlever 480.000 pv pour qu'il lâche ses prisonniers. 
(Source : https://worldofwarcraft.judgehype.com/strat-instances-ulduar20/)

**Étapes de reproduction**
- Raid : Ulduar (Mode 25, en mode 10 nous n'avons pas rencontré ce problème)
- Boss : Kologarn
- Sort en question : Poigne de Pierre 
- Ce sort est effectué toutes les 30sec dès le début du fight

**Comportement attendu**
Les dégâts semblent corrects, les personnes sont bien entravées mais malgré les dégâts effectués sur le bras droit (plus du double requis parfois), elles devraient êtres relâchées au sol sous le bras droit.

**Captures d’écran / Vidéos**
Pas de capture ni de vidéo disponible.

**Ressources additionnelles**
Dur de trouver une vidéo potable, sur celle-ci on voit la mécanique (grab à 00:30 et relachement à 00:39) : https://www.youtube.com/watch?v=kUDjBVINs-s

**Comment by joshwhedon** [comment]
J'ai deja teste et les degats absorbes sont corrects aussi. Les joueurs sont relache quand suffisament de degats sont effectues, 80000 en 10 et 380000 en 25. Bien entendu la resistance / armure / etc entre en compte dans le calcul de ces degats.

**Comment by Ischjgt** [comment]
Le bras absorbe les dégats correctement.
Au moment où il subit de nouveau des damages, donc quand le seuil de dégats est atteint, les joueurs ne sont pas relachés.

Ça me le fait qu'en 25
