### ISSUE TITLE
Loot poignée endommagée ally dans un groupe hordeux

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#733]
Un groupe a fait part d'un léger soucis de drop de poignée endommagée : 
Dans le donjon forge des âmes hm, avec un groupe composé d'hordeux uniquement ils ont eu https://woehead.way-of-elendil.fr/?item=50379 de drop sur les trashs. 
Je pense que dans un groupe uniquement hordeux, https://woehead.way-of-elendil.fr/?item=50380 aurait du tomber et pas la version ally. (Ils n'ont donc pas pu la récupérer)
Impossible à reproduire pour ma part.

**Comment by joshwhedon** [comment]
Si l'interfaction est actif, le systeme de loot se fiche de qui est dans le groupe et fait loot une version au hasard. C'est le comportement "normal" (en gros ce ne sera pas corrige).
