### ISSUE TITLE
Jeeves sensible aux pièges hunt

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#735]
Il est possible de faire proc les pièges hunt tel que : 
https://woehead.way-of-elendil.fr/?spell=49056
https://woehead.way-of-elendil.fr/?spell=14311
https://woehead.way-of-elendil.fr/?spell=49067
https://woehead.way-of-elendil.fr/?spell=13809
https://woehead.way-of-elendil.fr/?spell=34600
 sur  https://woehead.way-of-elendil.fr/?npc=35642#summoned-by
Jeeves n'est pas supposé être attaquable et ne doit donc pas faire proc les pièges

**Comment by Amilgaull** [comment]
En fait je viens de tester sur plusieurs pnjs dans dalaran et les pièges s'activent des lors que le pnj est "jaune" ou "rouge" même s'ils restent inattaquables

**Comment by joshwhedon** [comment]
Je mets un correctif il faudra me dire si ca cause des soucis.
