### ISSUE TITLE
Probleme de ciblage lors d'une quete 

### ISSUE THREAD

**Issue by Chromoshomme** [way-of-elendil/3.3.5#736]
Bonjour ! :)

J'ai un soucis au niveau d'une quête : https://woehead.way-of-elendil.fr/?quest=10747 
On me donne un filet à utiliser sur des dragonnets, mais lorsque que j'utilise l'objet en les ciblant, ça me marque " Cible incorrecte " … 

J'ai tout essayé : affaibli, avec ou sans forme ( je suis druide ), déco reco, /reload et je n'arrive toujours pas à les capturer … 

Voila merci d'avance ! :)

**Comment by Killyana** [comment]
J'arrive pas à reproduire tu utilises probablement le filet sur les mauvais mobs, il faut les utiliser sur les https://woehead.way-of-elendil.fr/?npc=21387
