### ISSUE TITLE
[Druide][Balance][Sort]Force de la nature

### ISSUE THREAD

**Issue by Kwyzard** [way-of-elendil/3.3.5#741]
**Description**
Les tréants devrait disposer de plus de dommage et de plus de points de vie en moyenne actuellement les tréants font peu de dommages  et ont seulement 6000 points de vie. Il est fort probable qu'il manque le script de level scaling étant donner que le sort est obtenable vers le niveau 50, aucune infos concrète concernant les dommages qu'ils devraient faire jpeux aller tester sur différents serveur et faire des screen si vous voulez mais c'est tout ce que je peux sortir comme info

**Comportement attendu**
Plus de vie, plus de dommage

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Force_of_Nature
https://wow.gamepedia.com/Force_of_Nature
https://woehead.way-of-elendil.fr/?spell=33831
https://github.com/SunwellTracker/issues/issues/2598 (Tracker autre serveur privée)(Pas de source non plus) 

Ont peux voir aussi que sur les patch il est noté que le spell a été modifier de 3 min a 2 min cette info est a prendre avec des pincettes tous les serveur que j'ai fait le spell était à 3 min
Edit: 3minutes ""confirmé"" par https://github.com/TrinityCore/TrinityCore/issues/24609 

**Info Supplémentaires**
Je vais crée deux rapports supplémentaire concernant les tréants
Un pour leur comportement ils cassent les contrôle alors qu'ils devraient se positionner près la cible et attendre que quelqu'un casse le contrôle (qui est probablement lié à un problème plus général du comportement des familiers)
et l'autre pour un problème avec le talent ronces qui n'applique pas l'hébété : https://github.com/way-of-elendil/3.3.5/issues/742

**Comment by joshwhedon** [comment]
Ils prennent 30% de la stamina du joueur, et 0.9% des degats de nature du joueur. Aucune information n'est disponible quand au fait que ces donnees sont correctes ou pas. Donc a moins de fournir des donnees exactes, c'est le comportement considere normal.

**Comment by Kwyzard** [comment]
Bon ont est la pour démonter la thèse des 9%

**Petites infos** 

Druide Full bis PVE ~ 4000+ spellpower (sans trinket proc)
Druide Full bis PVP ~ 3300+ spellpower (sans trinket proc)
Je ne connais pas l’ordre d'applications des bonus / réductions dégâts donc je fait bonus puis réduction j'imagine que c'est peut être plus complexe si besoin je referais le calcul avec les formules que tu peux me fournir (je prend même pas en compte une éventuel résilience ça serait mal vu quand même)

**Vidéo antérieur à cataclysm** (7 décembre 2010)


https://www.warcraftmovies.com/fr/movieview.php?id=115251 (Date 2009-06-29)
Sur cette video a 0:49 on peux le voir taper sur un mage pour des dégâts variant de **500 à 700** dommage, 
Rien qu'avec cette info si tu considère un **druide équilibre full bis PVE** environ 4000+ spell en raid (sans compter les proc trinket heroic) en appliquant ta formule de 9% des dégâts de spell 

4000 x 9/100 = 360

**360 dégâts pour un Druide PvE full bis avec la règle des 9%** bien sur sur cible sans amure sans résilience

A cela soyons gentil et imaginons qu'il utilise talent "Ronce" 3/3 qui augmentes les dégâts de 15% on passe à

360 x 1.15 = 414 

**Ont est donc a 414 dégâts pour Druide PvE full bis + talent "Ronce" 3/3** (toujours sans armure sans résilience)

Donc rien qu'avec cette règle de calcul qui ne prend même pas encore en compte l'armure des personnage prenez en exemple le mage sur la vidéo un mage 15% de réduction physique (surement beaucoup plus en spé givre pvp mais prenons une fourchette faible peut être un personnage avec peu de gear)

Application des 15% armure :
414 x 0.85 = 
**351,9‬ Dégâts attendu sur le mage** 
**351,9‬ Dégâts attendu sur le mage** pour 4000 de spell power (full bis 284/277 PvE) du druide en comptant 15% armure (et aucune résilience)


Reprenons la vidéo sur le mage la moyenne est d’environ 500 dégâts donc la question est : :
**combien de spell power nécessaire avec 15% d'armure pour arriver à se résultat** 
Donc calcul inverse (et ne sachant pas faire un produit avec inconnu) j'ai tâter les calculs jusqu’à m'approcher de 500 ont arriverais a 5700 de spellpower soit près de 1500 spellpower supplémentaire en PvE ou encore 2200 spellpower supplémentaire en stuff PvP

5700 x 0/100 = 513
513 x 1.15 = 589
589 x 0.85 = 501

Il faudrait donc au druide 5700 de spellpower pour atteindre cette branche des 500 dégâts sur les tréants contre une cible a 15% de réduction physique **avec** Ronce 3/3


**Petites donnée test a 5700 de spellpower en considérant la règle des 9%**
**5700 de spellpower**

Contre 0 armure = 513
Contre 15% Armure = 436,05
Contre 15 % Armure 15% résilience = 370,64
Contre 15 % Armure 15% résilience avec Ronce 3/3 = 426,23
Contre 15% Armure avec talent Ronce 3/3 = 501,4


Tout cela pour démontrez que les 9% sont trop faible comme règle de calcul il est impossible que le druide de la vidéo ait atteint 5700 de spell sans aucun trinket proc (barre de buff) visible.

**Impossible**

La question maintenant quel serait le pourcentage approximativement pour arriver à un tel résultat sans connaitre le stuff du Druide ni le % d'armure ou de resilience des cibles ou encore l'utilisation des points de talents ou non. **Toujours est t'il que la règle est forcement fausse et de loin** on le re dit 5700 spellpower pour espérer toucher en moyenne du 500 avec la règle actuel de calculs 

Donc un minimum d'augmentation est forcement nécessaire

**Comment by joshwhedon** [comment]
On ne change pas les formules au piff.

**Comment by Kwyzard** [comment]
http://www.worldoflogs.com/reports/rqj75a4o7g4rgw4m/details/76/?s=1489&e=1632 Combat de 2min 23 -> 1 seul utilisation du sort -> 69520 de dégâts total
Active time : 26.2s

Je pose ça là juste pour pas perdre les lien je suppose que comme l'entité est un familier elle dispose elle aussi du buff 30% rapide calcul -> ‭48 664‬ dégâts de base sans le buff 30%

**lien additionnels** 
http://www.worldoflogs.com/reports/ofucufas02ju9jd6/sum/damageDone/?s=4002&e=4051
http://www.worldoflogs.com/reports/843kjl17jhfr0eda/sum/damageDone/?s=3148&e=3206
http://www.worldoflogs.com/reports/rqj75a4o7g4rgw4m/sum/damageDone/?s=1489&e=1632

**Comment by Kwyzard** [comment]
Bon je revient à la charge
Post 2008 (3.3.x)
http://www.clanyawa.com/viewtopic.php?t=5411

Donc premièrement un problème concernant le buffing, si j'invoque mes tréants et que je buff marque du fauve sur eux ou qu'un Guerrier fait le Crie PV, aucun changement de vie ni de mana se fait. Donc problème de stats pour ça 

je cite : **"They benefit from totems, auras, Heroism, Battle Shout, and similar AoE buffs, but they must be ongoing or be applied while the Treants are active to have an effect."**

et après plus loin juste pour le plaisir "They contribute anywhere from 45K to 60K damage per cast depending on conditions"

Ici la moyenne est plus de 18-20 k par cast, peut être que debug les stats permettras une augmentation notable a voir ?

Et après comme j'avais dit "* They are not supposed to attack CC'ed targets unless no non-CC'ed targets remain. (This doesn't always work; use them in CC environments with great care.)"

Mais j'imagine que c'est un problème plus global sur le comportement les familiers

**Comment by Ischjgt** [comment]
Réouvert à la demande de Frédéric

**Comment by joshwhedon** [comment]
Aucun interet a reouvrir si aucun coefficient n'est fourni. Si des formules sont fournies, des changements seront fait. Dans l'immediat, rien n'a ete fourni permettant de deriver la moindre formule.

**Comment by joshwhedon** [comment]
Encore une fois, je ne vais pas faire mumuse avec les stats au piff jusqu'a trouver un truc qui plait.

**Comment by Kwyzard** [comment]
J'ai demander une re-ouverture parce qu'il y a bel et bien un bug puisque les tréants ne prennent pas les buffs.

J'ai ensuite supposer que c'était peut être pour ça qu'ils faisaient un dps merdique j'ai en aucun cas demander la re-ouverture pour les dommage mais maintenant qu'on en parle il me vient a l'idée que c'est peut être les dommage de base qui sont pas bon et que ton scaling 0.3 spellpower est peut être bon.

Genre si j'ai 0 spell power mes tréants vont faire 0 dommage ?

**Comment by joshwhedon** [comment]
Comme je l'ai deja dit plus haut:
"Ils prennent 30% de la stamina du joueur, et 0.9% des degats de nature du joueur. Aucune information n'est disponible quand au fait que ces donnees sont correctes ou pas. Donc a moins de fournir des donnees exactes, c'est le comportement considere normal."
Si le buff, au moment de l'invocation des treants, affecte le spellpower ou les pv, ils seront appliques a ce calcul.

**Comment by Kwyzard** [comment]
C'est pas la question si je les invoque et que je cible un tréant et que je le buff il n'y a aucun changement **"They benefit from totems, auras, Heroism, Battle Shout, and similar AoE buffs, but they must be ongoing or be applied while the Treants are active to have an effect."** j'ai tester avec un guerrier les tréant ne prennait pas le Battle Shout

**Comment by Kwyzard** [comment]
Et même en soit ta même pas répondu a me deuxième question je t'ai demander si ils avaient des dommage de base + les 0.9% de spell

Est ce que si j'ai 0 spell il vont faire 0 dégâts tu sais le calcul 0.9% de ma spellpower si j'ai 0 il se passe quoi

**Comment by joshwhedon** [comment]
Y'a des degats de base.

**Comment by joshwhedon** [comment]
![WoWScrnShot_052920_090045](https://user-images.githubusercontent.com/543699/83202460-fbc87a80-a18a-11ea-9569-5e53d55cd4e1.jpg)
Je viens de tester Battle shout et les treants le prennent bien, comme tous les pets.

**Comment by Kwyzard** [comment]
J'ai tester avec celui des pv je crois

**Comment by joshwhedon** [comment]
C'est quoi le nom de celui des pvs ?

**Comment by Kwyzard** [comment]
Crie de commandement

**Comment by joshwhedon** [comment]
Merci, certains buffs sont pas pris en compte correctement si ils sont lance apres l'invocation, je corrige ca.

**Comment by Kwyzard** [comment]
Ok ont verras peut être un peu de dps gagner grâce a ça (cf la hâte melee et les bonus puissance d'attaque de certains classe)

**Comment by Kwyzard** [comment]
Bon le sort est "viable" environ 20 k + pour chaque utilisation (en raid) C'est faible comparé aux logs d'officiel mais j'imagine qu'on se contenteras que de ça pour l'instant
