### ISSUE TITLE
Problème quête vallée d'Ombrelune

### ISSUE THREAD

**Issue by Chromoshomme** [way-of-elendil/3.3.5#744]
Bonsoir ! 

j'ai un soucis avec cette quête https://woehead.way-of-elendil.fr/?quest=10564 ( cette fois je l'ai bien lue :p ) 
je me positionne bien au centre du glyphe en question, j'utilise l'objet et rien ne se passe ... j'ai même attendu 1 minute immobile après activation de l'objet mais toujours rien ! 

Merci d'avance !!

**Comment by Killyana** [comment]
Y'a un timer de 5min entre chaque utilisation de l'item

**Comment by Chromoshomme** [comment]
Le cd était beaucoup plus court ^^ vu que je l'ai spam à un moment parce que ça m'énervait haha
mais je viens d'y retourner 1h après et ça a marché du premier coup ... va comprendre qqch x)
