### ISSUE TITLE
Gob: Porte du sas des scientifiques Vert - ICC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#745]
**Description**
201614 - [Porte du sas des scientifiques Vert] 
201613 - [Porte du sas des scientifiques Orange] 
[Ooze Release Valve] GUID: 150320 ID: 201615
[Gas Release Valve] GUID: 150345 ID: 201616

La porte correspondante à la valve activée est ouverte après un crash, même si l'autre valve n'est pas activée (testé avec la verte)

L'event est toujours faisable ensuite

**Comment by joshwhedon** [comment]
Osef.
