### ISSUE TITLE
Quest: Changer le sens du vent

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#747]
**Description**
13058 - [Changer le sens du vent]  
Impossible de récupérer son corps lorsque l'on meurt après avoir utilisé le marteau de la connaissance
Le corps se situe en phase 256

**Comment by Killyana** [comment]
Je vois pas comment  on peut  fixer ça https://github.com/TrinityCore/TrinityCore/issues/24343

**Comment by joshwhedon** [comment]
C'est assez simple en fait :D . L'aura est pas retiree a la mort, du coup le corps reste en phase 256.

**Comment by joshwhedon** [comment]
PS: Je sais pas si c'est blizzlike, mais bon c'est mieux que de rester bloquer dans la phase a tout jamais.
