### ISSUE TITLE
Boss: Léviathan

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#75]
**Description**
Il reste sur place une fois le combat lancé.
À la fin du combat les pyrites restent dans le ciel et les barrières qui délimitent la zone de combat restent

**Étapes de reproduction**
-Engager le combat contre le Léviathan

**Comment by joshwhedon** [comment]
J'ai nettoye un peu le script. Merci de rejeter un oeil.

**Comment by Ischjgt** [comment]
- Le boss ne veut pas rentrer en combat s'il est aggro par un joueur sans véhicule
(avec un véhicule c'est bon, si le véhicule est détruit le boss reset)

**Comment by joshwhedon** [comment]
C'est normal, le combat ne se fait qu'en vehicule normalement.
