### ISSUE TITLE
Bug Undermap LK HM

### ISSUE THREAD

**Issue by Eryinnn** [way-of-elendil/3.3.5#750]
**Description**
Nous étions en 10Hm, sur LK précisément. Lors de la moisson d'âmes collectives, moi même ainsi que le Druide Tank sommes passés à travers le sol lorsque qu'on a changer de forme.

**Étapes de reproduction**
-Citadelle de la couronne de glace
- 10 HM
- Roi Liche
- Moisson d'âmes, au bord de la salle

**Comportement attendu**
J'aimerais rester dans la bonne phase et ne pas passer a travers le sol

**Captures d’écran / Vidéos**
https://www.twitch.tv/krunkks/clip/BusyAliveMooseMVGame

**Ressources additionnelles**
Sur le clip précédent on me voit en forme de Taunka (proc VPM), et quand je vais me re-tranformer en félin je vais disparaître de l'écran. Je viens de passer à travers le sol et je meurs quelques secondes plus tard comme si j'étais tombé de la plateforme.

**Comment by Killyana** [comment]
Ne changez jamais de forme dans la salle de deuil givre.
Le bug est connue et pas facile à corriger

**Comment by gtschanz** [comment]
bah je vois mal comment il peut éviter les procs taunka de la vpm; concernant le changement de forme à la limite ça ok.

**Comment by joshwhedon** [comment]
Desole mais pas trouve de moyen de corriger ce probleme.
