### ISSUE TITLE
Entrée de UBRS / Sceau d'ascension

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#751]
Bonjour,

L'ouverture de l'entrée de UBRS dans la partie superieur du pic de blackrock (porte a gauche en entrant avec des flambeaux autour, donnant sur des mobs draconiens.) est censé être conditionné par la possession dans le sacs d'un membre du groupe, suite a quêtes, du Sceau de l ascension. Alors qu'elle se trouve 100% ouverte sur le serveur.
 
https://fr.classic.wowhead.com/item=12344/sceau-dascension#guides

Merci, bon courage ++

**Comment by Killyana** [comment]
Requirement removed in 3.08
https://fr.wowhead.com/item=12344/sceau-dascension#comments:id=685047
