### ISSUE TITLE
Xp non convertie en PO au niveau 80 en rendant une quête

### ISSUE THREAD

**Issue by Chromoshomme** [way-of-elendil/3.3.5#753]
Bonjour :) 

J'ai vu que plusieurs personnes ont remarqué ça aussi dans le jeu alors j'ai essayé d'apporter une "preuve " ^^ 
J'ai pris pour exemple une quête en particulier mais je peux apporter d'autres screens avec d'autres quêtes si nécessaire ! 

https://woehead.way-of-elendil.fr/?quest=11330

il est écrit qu'elle rapporte 2 po 40 OU 3po60 si on est niveau 80 ! 

![WoWScrnShot_051420_122449](https://user-images.githubusercontent.com/63233524/81923928-afa00680-95de-11ea-968b-8d1bb9ac6c11.jpg)

![WoWScrnShot_051420_122441](https://user-images.githubusercontent.com/63233524/81923933-b169ca00-95de-11ea-931b-53de0b901251.jpg)

Les screens sont inversés mais on voit clairement que je n'ai reçu que 2po40 si on effectue le petit calcul au niveau de mon total d'argent dans le 1er screen MOINS le total du 2eme ^^

Voila voila :) j'espère que cela pourra être corrigé dans un futur proche ! 
Merci d'avance !!

**Comment by joshwhedon** [comment]
C'est woehead qui est incorrect pas le jeu. Le jeu te dit 2 po 40 pa, et tu as bien recu 2 po 40 pa.
