### ISSUE TITLE
Instance: Verouillage d'ID

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#754]
**Description**
- Impossible d'enlever le verrouillage d'id après un reset, qu'il ait été fait avant ou après le reset, que le joueur soit entré ou non dans l'instance après le reset.

**Comportement attendu**
- Can you "undo" an extension?
    Yes and no. If you have not gone into the instance since it would have normally reset (since it was extended), you can still reset it and get a new ID. However, if you have already gotten saved to the extended instance again, you'll have to wait out the rest of the lockout period for a new ID.

- If you extend an ID, but don't manage to kill any bosses, are you still eligible to reset the instance and get a new ID for the week?
This functionality is being considered, but it is unlikely it will be put in place for Patch 3.2.0. So to answer the question directly, no, you can't do this. Once you enter the instance and click "accept", you're saved for the duration of the lockout period whether you kill any bosses or not.
_As of Patch 3.3.3_ the above answer is incomplete. Provided you were previously saved to this Raid ID from the previous week, and don't attempt or complete a Weekly Raid Quest in this instance, you are eligible to reset the instance. If you're new to this Raid ID (ie was not present for the first week, but present for the 2nd week), and receive the "Save" popup, you will be saved, and will not be eligible to reset the instance. 

https://wowwiki.fandom.com/wiki/Instance_Lock_Extension

**Comment by joshwhedon** [comment]
Vous attendez pas a ce que ce soit corrige.
