### ISSUE TITLE
Quête / event Opération Gnomeregan

### ISSUE THREAD

**Issue by Amilgaull** [way-of-elendil/3.3.5#755]
https://woehead.way-of-elendil.fr/?quest=25393

En prenant https://woehead.way-of-elendil.fr/?quest=25287 il faut utiliser 
Name: 'Thunderflash'
13:13:02 SpawnID: 207188, current GUID low: 259299.
13:13:02 Entry: 39396.
13:13:02 Faction: 64.
13:13:02 NPC Flags: 1.
13:13:02 DisplayID: 22719 (Native: 22719).
13:13:02 Compatibility Mode: 0
13:13:02 Level: 1.
13:13:02 EquipmentId: 0 (Original: 0).
13:13:02 Health (base): 49. (max): 49. (current): 49.
13:13:02 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
13:13:02 Unit Flags: 0
13:13:02 Unit Flags 2: 2048.
13:13:02 Dynamic Flags: 0.
13:13:02 Faction Template: 64.
13:13:02 SpawnTime: Full:2m Remaining:0s
13:13:02 Loot: 0 Pickpocket: 0 Skinning: 0
13:13:02 InstanceID: 0
13:13:02 Phasemask: 1
13:13:02 Armor: 7
13:13:02 Position: -5447.549805 -667.309021 395.188995.
13:13:02 AIName: SmartAI ScriptName: 
13:13:02 React state: AGGRESSIVE
13:13:02 Active AI: SmartAI
13:13:02 Flags Extra: 64
13:13:02 * CREATURE_FLAG_EXTRA_NO_XP_AT_KILL (0x40)
13:13:02 * has gossip menu (0x1)
13:13:02 MechanicImmuneMask: 0
13:13:02 dmg_multiplier: 1.000000
une fois arrivé, le Grand Bricoleur Mekkanivelle <Roi des gnomes> doit arriver sur place et nous permettre de rendre cette quête afin de lancer la suite (https://woehead.way-of-elendil.fr/?quest=25393)
Name: High Tinker Mekkatorque
13:10:10 SpawnID: 1022829, current GUID low: 251441.
13:10:10 Entry: 39271.
13:10:10 Faction: 35.
13:10:10 NPC Flags: 3.
13:10:10 DisplayID: 31658 (Native: 31658).
13:10:10 Compatibility Mode: 0
13:10:10 Level: 83.
13:10:10 EquipmentId: 1 (Original: 1).
13:10:10 Health (base): 5578000. (max): 5578000. (current): 5578000.
13:10:10 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
13:10:10 Unit Flags: 134217728
13:10:10 * UNIT_FLAG_MOUNT (0x8000000)
13:10:10 Unit Flags 2: 2048.
13:10:10 Dynamic Flags: 0.
13:10:10 Faction Template: 35.
13:10:10 SpawnTime: Full:5m Remaining:0s
13:10:10 Loot: 0 Pickpocket: 0 Skinning: 0
13:10:10 InstanceID: 0
13:10:10 Phasemask: 256
13:10:10 Armor: 10673
13:10:10 Position: -5130.089844 451.345001 394.906006.
13:10:10 AIName:  ScriptName: 
13:10:10 React state: AGGRESSIVE
13:10:10 Active AI: AggressorAI
13:10:10 Flags Extra: 64
13:10:10 * CREATURE_FLAG_EXTRA_NO_XP_AT_KILL (0x40)
13:10:10 * has gossip menu (0x1)
13:10:10 * is quest giver (0x2)
13:10:10 MechanicImmuneMask: 0
13:10:10 dmg_multiplier: 1.000000
Actuellement, lorsque l'on arrive après avoir utilisé la machine, nous sommes dans une phase ou il n'y a rien sur place et il faut aller chercher le roi aux coordonnées notées ci-dessus. 
Ensuite nous pouvons rendre la quête et prendre https://woehead.way-of-elendil.fr/?quest=25393 mais l'assaut ne se lance pas.

https://www.youtube.com/watch?v=7saEJx3kEfA&feature=youtu.be
Voila toute la série, les quêtes qui nous intéressent commencent à 4 minutes 25.

**Comment by joshwhedon** [comment]
C'est pas scripte et ca le sera surement jamais, c'est le pre-event cata.
