### ISSUE TITLE
[Druide][Sort]Starfall + Nature's grace

### ISSUE THREAD

**Issue by Kwyzard** [way-of-elendil/3.3.5#757]
**Description**
Le sort starfall ne fait pas proc Nature's grace même si le starfall fait un coup critique

**Comportement attendu**
Le sort starfall n'était pas considéré comme une aoe mais bien un sort à target unique il devrais faire proc le talent Nature's grace en cas de coup critique

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=61346 Nature's Grace
https://woehead.way-of-elendil.fr/?spell=53201 Starfall

Rang inférieur : 
https://woehead.way-of-elendil.fr/?spell=48505 1
https://woehead.way-of-elendil.fr/?spell=53199 2 
https://woehead.way-of-elendil.fr/?spell=53200 3

**Info additionnelles**
Il semblerait qu'étant donner que Starfall n'est pas considéré comme spell à cible unique le totem de glèbe du shaman ne le prend pas en compte (le totem reste actif sans "rediriger" un tick de starfall) peut être qu'a la suite de ce débug cela serat le cas je referais un post avec des sources additionnel si demandez puisque je ne suis moi même pas sur si le totem doit le prendre ou non.

**Comment by Justforsoloq** [comment]
Le totem de glèbe ne doit PAS prendre la starfall :).

**Comment by Kwyzard** [comment]
Parce que le sort en lui même est considéré comme cible unique qui fait ensuite un dégâts aoe mais le sort en lui même n'est pas une AOE

Il y a d'abord le tick sur cible qui ensuite rebondit sur les cibles a coté. Le sort a part en entière n'est pas une AoE comme on l'entend

**Comment by Justforsoloq** [comment]
Je trouve ça étrange, vu que même la première partie du spell est considérée comme aoe : 
"You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 325 to 378 Arcane damage. Also causes 58 Arcane damage to all other enemies within 5 yards of the enemy target. Maximum 20 stars. Lasts 10sec."
(on all targets. Also cause all other ennemies).
Et tu peux le lancer sans avoir de cible ce qui n'est pas le cas des sorts à cible qui rebondit (    Avenger's Shield, Hammer of the Righteous, Chain Lightning, Chain Heal ) ou des cleaves effects (     Heart Strike, Swipe (Cat), Seal of Command, Cleave).
Donc pour moi selon le tooltip, et les sorts area of effect, la starfall est bien considéré comme une aoe.

**Comment by Kwyzard** [comment]
Je vous remercie pour cette recherche de preuve 2h de vidéo 180p c'est vraiment un plaisir intense de faire autant d'effort pour des truc si simple. 

https://www.warcraftmovies.com/movieview.php?id=104715 lien mort reupload ici ->
https://www.youtube.com/watch?v=LCAwQ62jRHU
**Voir 13min08**

Ont voit clairement le Starfall tomber sur le Grounding. Faut t'il que je fasse un autre post concernant ce bug ? Ou vous prenez les deux en 1 ?

> Le totem de glèbe ne doit PAS prendre la starfall :).

**Comment by joshwhedon** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/5079
https://web.archive.org/web/20100808133226/http://elitistjerks.com/f47/t66856-druid_balance_pve_updated_3_3_5_a/
Starfall ne fait pas proc Nature's grace.

**Comment by Kwyzard** [comment]
https://cdn.discordapp.com/attachments/488586498942173194/710629233164156938/unknown.png
Tirer de ton lien web archive

**Comment by Justforsoloq** [comment]
Par rapport au grounding et starfall, en effet après recherche :
Starfall breaks grounding totem in less than a second. Starfire is what you're thinking about.
Le totem de glèbe prend un des ticks de la starfall
