### ISSUE TITLE
[Rogue][Spell]Cloak of shadow + Crab Pin

### ISSUE THREAD

**Issue by Kwyzard** [way-of-elendil/3.3.5#758]
**Description**
La cape d'ombre n'enlève pas le débuff cloué sur place (pin) des familiers de chasseur

**Comportement attendu**
A l'activation de la cape d'ombre le debuff est censé partir

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=53548 Cloué sur place
https://woehead.way-of-elendil.fr/?spell=31224 Cape d'ombre

**Comment by Justforsoloq** [comment]
https://github.com/way-of-elendil/3.3.5/issues/615

**Comment by Kwyzard** [comment]
Ok j'avais pas chercher mais bon 

https://cdn.discordapp.com/attachments/338412868095442955/710605893997166602/unknown.png
Votre propre database : 
https://cdn.discordapp.com/attachments/338412868095442955/710606387427803176/unknown.png

Comment est le comportement des paladin et des prêtre face à ce debuff peuvent t'il le dissiper ? Si oui ça confirmerait la théorie que c'est bien un debuff magique je veux dire ingame c'est quand même marqué magique noir sur blanc

**Comment by Justforsoloq** [comment]
En fait j'ai trouvé ça  : 
https://db.rising-gods.de/?spell=53548
École | Physique
Type de dissipation | Magie

(Ce qui explique le dispell des priest/pala mais que le rogue ne puisse pas cos le pin, après comme j'ai dit sur mon post je suis pas sur, mais j'ai trouvé aucune vidéo retail atm où un rogue cos un pin)

**Comment by Endalaust** [comment]
_Juste pour info c'est les mêmes données sur la db woehead_ :D

**Comment by Kwyzard** [comment]
La cape d'ombre agit comme un dispel magique non ? elle dispel tout de magique sur sa cible ?

**Comment by joshwhedon** [comment]
Non, la cape d'ombre n'est pas un dispel, la cape d'ombre est un effet d'immunite, qui n'affecte que les ecoles de magie.
SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 2 (SPELL_DAMAGE_CLASS_MELEE)
Pin n'est pas un effet magique (malgres son dispel classifie en magie), de ce fait, cape d'ombre, qui immunise contre les effets d'ecole de magie, ne l'affecte pas. D'un autre cote, la bubulle immunise contre TOUS les effets (ecoles de magie et normales).
A moins de fournir des infos qui disent explicitement que la cape d'ombre doit retirer Pin, c'est le comportement normal.
