### ISSUE TITLE
[Spell] Stealth + Absorb

### ISSUE THREAD

**Issue by Kwyzard** [way-of-elendil/3.3.5#759]
**Description**
Si un personnage dispose d'un bouclier prêtre sur lui et qu'il se prend le bump il n'est pas sortit de furtivité

**Comportement attendu**
Le personnage doit être sortit de furtivité si il subit le typhoon 

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?spell=61384 Typhoon
https://woehead.way-of-elendil.fr/?spell=48066 Power Word: Shield

**Info additionnelles**
Il semblerait que le sort orage du chaman n'est pas se problème ? (aucune idée personne pour test)
Il semblerait qu'ouragan dispose du même problème donc problème plus général concernant tous les sorts aoe ? ( A tester aucune info pas pu trouver de prêtre dur dur la vie d'afk dalaran)
Contrairement aux sort "au sol" concecration / mort et décomposition" qui eux ne font pas sortir l'utilisateur de furtivité

**Comment by joshwhedon** [comment]
La furtivite s'enleve uniquement si on se prend des degats non ? Pourquoi une aoe absorbee ferait sortir de la furtivite ?

**Comment by Justforsoloq** [comment]
En fait ça dépend si les knockback sont considérés dans la même zone que les roots/stun de zone.
Les roots (frost nova/talent elem etc) et les stun de zone (racial tauren, shockwave war) même sans faire de dégâts chope le rogue en fufu. Donc à voir si le knockback est censé faire la même (dans mes souvenirs oui, mais j'ai beaucoup de souvenirs d'AT qui polluent ma mémoire de retail)

**Comment by joshwhedon** [comment]
Et sur woe les zones de root / stun (sans degats) retirent la furtivite ?

**Comment by Justforsoloq** [comment]
Yep c'est script pour les root/stun
(Faudrait que je fouille des vidéos d'elem/kin ou dp/r retail mais la flemme ce soir)

**Comment by Justforsoloq** [comment]
Edit : j'ai dit que c'est script mais maintenant que j'y pense pas pu testé correctement donc je vois demain.

**Comment by Kwyzard** [comment]
Commentaire de mon mate :
Du coup perso de mon expérience issue des serv privé le script est :
Shield ou non les sorts d'aoe sortent le rogue de camouflage (ex : cone de glace, pluie de feu, blizzard, nova de feu, nova de givre, talent de sarment sham elem, cri démoralisant, hurlement percant, bump boomie ect)
Ensuite les aoe posées au sol, style consécration / mort et décomposition mettent en combat mais ne font pas sortir du camouflage les voleurs qui ont un shield.
Le dispel de masse de pretre met en combat mais ne fait pas sortir du camouflage shield ou non.

Conclusion, y a des sorts qui font juste des dégats, certains font juste des controles sans appliquer de dégats et enfin certains sorts font ni de contrôles ni de dégâts comme le cri démoralisant du guerrier (d'ailleurs au passage sauf erreur c'est le script actuel du serveur, le voleur se fait défufu avec le cri démoralisant du guerrier, du coup à voir si c'est le cas si shield idk)

Bon ensuite pour le concret :
https://www.warcraftmovies.com/movieview.php?id=130183
timer 6:05 et 6:20 : Sortie du camouflage du rogue portant un shield du fait de la nova de givre du mage, quelques secondes plus tard, sortie de camouflage du fait de la shadow fury du warlock
timer 10:47 environ : Sortie du camouflage du rogue portant un shield du fait de l'explosion des arcanes du mage 

Donc du coup reste à vérifier, l'interaction du camouflage quand on a un shield pour les zones au sol (consécration,mort et décomposition), en tout cas ce qui est sûr c'est que le script n'est pas retail. (et donc le problème ne concerne pas que le typhoon)

**Comment by joshwhedon** [comment]
Au final ce bug a rien a voir avec les druides ou typhons. Donc question : si un sort touche une cible furtive avec un bouclier, et que le bouclier absorbe tout, est-ce que la furtivite doit se retirer aussi ? (Je ne parle pas que d'aoes).

**Comment by joshwhedon** [comment]
https://www.wowhead.com/forums&topic=124541.2 ici ils disent que consecration / death and decay / etc retirent la furtivite.

**Comment by joshwhedon** [comment]
https://vanilla-wow.fandom.com/wiki/Power_Word:_Shield
"In PvP, this spell can be a huge boon to bestow on Rogues and Feral Druids. Any damage taken will unstealth a character. However, if you Power Word: Shield a Rogue, AoE damage that doesn't get through the shield is absorbed, which greatly increases the difficulty of finding a Rogue by laying down an AoE. Power Word: Shield will also absorb the damage from DoT's, allowing DoT'd Rogues to Vanish safely. Just know that if the AoE or DoT damage is greater than the shield will take, then the actual character will take damage and stealth will become undone."
Y'a beaucoup de sources contradictoires sur le sujet.

**Comment by joshwhedon** [comment]
Quant aux videos, il n'est pas clair que le joueur n'a pas pris de degats par les aoes (et il n'est pas clair non plus que le joueur avait le bouclier sur lui au moment du retrait).

**Comment by Justforsoloq** [comment]
Actuellement c'est bien script sur les root/stun.

**Comment by joshwhedon** [comment]
Non ca l'est pas sur les absorb. Genre la nova de glace du mage, si elle est asborbee entierement elle root pas.

**Comment by Kwyzard** [comment]
Ont voit clairement sur les vidéo le debuff d'âme affaiblit et le buff du shield avec ça tu peux être sûr qu'il avait le shield au moment du retrait de la furtivité.

Après c'est très trouble le comportement que le shield devrait avoir : sur ton lien wowhead ils parlent en général et non avec un shield sur la tête donc post pas très intéressant. Parcontre le lien du wiki la partit sur les dots est belle et bien ce qu'on pouvais rencontrer sur les différents serveur privée **"Power Word: Shield will also absorb the damage from DoT's, allowing DoT'd Rogues to Vanish safely."**

Donc il reste la partie **"However, if you Power Word: Shield a Rogue, AoE damage that doesn't get through the shield is absorbed, which greatly increases the difficulty of finding a Rogue by laying down an AoE"** 
La vidéo prouve le pourtant le contraire est ce que le "laying" down est bien ce qu'on dit concernant les "consécration et mort et décomposition" ... difficile a dire

**Comment by joshwhedon** [comment]
C'est bien ce que je dis, il y a des contradictions partout.

**Comment by Justforsoloq** [comment]
J'ai testé sur chaman en me basant sur le lien terrestre (talent) + stun de zone tauren.
Dans les deux cas j'ai pu defufu un rogue sous shield.
J'ai basé mon commentaire sur "c'est script" dessus. N'ayant pas de mage/warprot/lock je ne peux pas faire le test avec d'autres root/stun de zone.

**Comment by joshwhedon** [comment]
Oui mais ton stun de zone ne fait pas de degats, donc il y a pas d'absorbtion. J'ai teste les deux, si y'a pas d'absorb c'est bon, si y'en a ca retire pas.

**Comment by Justforsoloq** [comment]
Oui c'est pour ça que je parlais plus haut des "root/stun sans dégâts" (car c'est ceux que je peux tester).
Donc la composante dégâts du root/stun fait "bug" ce dernier

**Comment by Popeyeddd** [comment]
Petite précision pour ce que je disais par rapport à l’expérience des serveurs privés
Quand je parlais de mort et décomposition et de consécration, un rogue avec shield qui passe sur une consécration préalablement posée ou une mort et décomposition préalablement posée, ne fait que rentrer en combat mais ne sort pas du camouflage. Un rogue qui n'en a pas il se fait sortir de camouflage direct.
Après pour ce qui est de sortie ou non du camouflage pour le rogue portant un shield se trouvant dans la zone du sort au moment ou la consécration/mort et décomposition est posée (moment d'utilisation du sort) je sais plus trop longtemps que j'ai pas joué avec du shield. 

Une fois de plus c'est xp privée ça prouve rien mais ça peut quand meme guider un peu les recherches

Pour les contradictions de ton lien wiki, faut aussi voir que c'est principalement un wiki pour vanilla et que y a des script qui ont rien à voir entre vanilla et tlk donc bon idk

**Comment by Justforsoloq** [comment]
En rogue je n'ai joué que sur private, AT principalement et ça concorde avec ce que dit Popeye, le soucis c'est qu'il faudrait trouver une vidéo d'un rogue (ou un coep rogue) en priest/rogue offi avec plusieurs configs où il se fait spot.

**Comment by joshwhedon** [comment]
Le truc aussi c'est, supposons que les AOE retirent la furtivite meme sur des absorb. Pourquoi que les AOE ? Si je vois un joueur et que je lui lance un sort, qu'il absorbe, pourquoi ca retirerait pas la furtivite ?

**Comment by Popeyeddd** [comment]
Bah pour le coup c'est pas supposons pour les aoe, la vidéo de retail le montre, le rogue est shield et se fait sortir de camouflage avec nova / shadow fury / explosion arcane.
Et pour répondre à ta question, pour moi ofc que ça le sort de camouflage dans ton cas. Pour moi ça parait évident que un mec qui prend les yeux en arène lache un spell random sur le rogue qu'il peut target grace aux yeux, le rogue shield ou non se fait sortir de camouflage.

**Comment by joshwhedon** [comment]
Mais ca reste en opposition avec ce que le wiki indique.

**Comment by Popeyeddd** [comment]
Scuse moi mais tu peux pas te fier à un wiki qui laisse entendre que si les dégats sont absorbés le rogue sort pas de camouflage alors que sur la vidéo c'est clair et net que c'est pas le cas. Aux 3 timer qu'on a donné le rogue a un shield qui persiste après la sortie de camouflage autrement dit les sorts qu'il s'est pris il les a entièrement absorbé et pourtant ça l'a bien sorti de camouflage.

**Comment by Justforsoloq** [comment]
Quand tu attaques/lances un sort sur un rogue fufu ça le defufu. 
Par contre un rogue sous shield n'est pas défufu par des dots qu'il avait sur lui précédemment avant de fufu (tant que le shield tient) OU les aoe déjà posés au sol

**Comment by joshwhedon** [comment]
Va me falloir un peu plus que votre parole la dessus, vous avez des guides qui en parlent de tout ca ?

**Comment by Popeyeddd** [comment]
Imo on trouvera pas de guide qui parle avec exhaustivité de la mécanique
Pour te convaincre faudrait se tapper masse vidéos de retail pour tenter de trouver les situations en question hihi
Un courageux ? ptdr

**Comment by joshwhedon** [comment]
J'ai mis un changement temporaire par accident, c'est surement incorrect mais je vais faire plus de changements dessus.

**Comment by joshwhedon** [comment]
Bon je mets une modif demain. On verra.

**Comment by sithis2a** [comment]
Go réouvrir le ticket et revoir vos modif svp, le rogue ne prends plus les traps givrant et serpent des hunts en camouflage. 
Seuls les pièges immo/explo et patinoire marchent encore correctement :D

![WoWScrnShot_051820_152238](https://user-images.githubusercontent.com/2728272/82218049-93bc9d80-991b-11ea-9d9e-229bf3fc977d.jpg)
![WoWScrnShot_051820_152201](https://user-images.githubusercontent.com/2728272/82218051-94553400-991b-11ea-8c9c-85cbfd8bf095.jpg)
![WoWScrnShot_051820_152258](https://user-images.githubusercontent.com/2728272/82218054-95866100-991b-11ea-8451-7e59f8d212d7.jpg)

**Comment by sithis2a** [comment]
Du coup le bug est apparu depuis votre fix et semble être lié à Maître des Illusions (https://wotlkdb.com/?spell=13971).
Je vais créer un autre ticket.
