### ISSUE TITLE
Raid: interfaction ICC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#76]
**Description**
1. C'est toujours le NPC de la faction Horde Garrosh Hurlenfer qui est à l'entrée de l'instance, Saurcroc et les 3 Généraux Kor'kron
2. Il est possible pour l'alliance de se taper avec Garrosh

**Étapes de reproduction**
- Perso alliance, entrer dans ICC
- Se taper avec Garrosh

**Comportement attendu**
1. Pour la faction Alliance
Garrosh Hurlenfer => Varian 39371
Saucroc => Muradin 39200
Général => Commandant 37190

2. Pas de fight avec Garrosh

EDIT : 
De même pour les instances Gelées, C'est Sylvanas au lieu de Janna
FDA
37583 => 37582
37596 => 37597
37779 => 37774

FDS
*pas fini*

**Comment by joshwhedon** [comment]
InstanceMapLoadAllGrids = 1 casse les spawn dependant de la faction du joueur.

**Comment by Killyana** [comment]
on en a pas besoin de toute façon.

**Comment by joshwhedon** [comment]
Oui je vois pas trop l'interet de ca pour les instances. Mais bon c'est bon a savoir :D .
