### ISSUE TITLE
[PNJ] objets manquant marchand

### ISSUE THREAD

**Issue by gurvancodying** [way-of-elendil/3.3.5#761]
**Description**
Le marchand Madame Ruby à Shattrath ne vends pas les bons objets et possède des duplis

**Comportement attendu**
Elle devrait vendre les objets présents sur le wowhead du server 
https://woehead.way-of-elendil.fr/?npc=19663

**Captures d’écran / Vidéos**

![2020-05-14 22_50_40-World of Warcraft](https://user-images.githubusercontent.com/40847651/81985012-f66d1b00-9635-11ea-8cd9-333f2094495b.png)

**Comment by Killyana** [comment]
Les items avec les nombres 1 et 2, 3 et 4 sont en quantités limités il faut attendre le re-stockage
