### ISSUE TITLE
[Hauts faits] Titres introuvables

### ISSUE THREAD

**Issue by Apochryphos** [way-of-elendil/3.3.5#764]
**Description**
Lorsque je réalise un Haut fait, le titre que je gagne avec celui-ci et qui devrait apparaitre dans le menu déroulant de ma fiche de personnage n'apparait pas dans celle-ci.
J'ai réalisé une requête en jeu mais le MJ n'a pas compris ma demande et m'a répondu sans possibilité de lui répondre.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Aucune idée, certains de mes titres sont disponibles comme "Noble" ou "Parrain" mais ceux du type "De Hurlevent" etc ne le sont pas.

**Comportement attendu**
Tu réalises un Haut fait qui te donnes un titre et celui devient disponible dans le menu déroulant de ta feuille de personnage.

**Captures d’écran / Vidéos**
Impossible de prendre une photo simultané de la feuille de perso et de celle des hauts. Si c'est ce qui est demandé.

**Ressources additionnelles**
/

**Comment by Endalaust** [comment]
Il y a 99% de chance qu'il s'agisse d'un faux positif
Les cas les plus fréquents : 

- Un addon masque l'UI et empêche de voir correctement certains éléments : A essayer sans addons
- La liste déroulante se ... Déroule (je rigole pas, dans 80% des cas c'est le joueur qui n'a pas vu qu'il pouvait scroll sa liste déroulante)

Pour le 1% restant, il s'agit de titre très isolés non lié à un Haut-fait. A la connexion d'un personnage, toutes ses données sont recalculées, y compris ses titres par rapport à ses HFs. Si vous avez un HF de titre, le titre sera recalculé et attribué à chaque connexion du dit personnage.

Si vous avez testé mes 2 suggestions, je veux bien le pseudo du joueur pour aller le constater, comprendre, et fixer si nécessaire.

**Comment by Apochryphos** [comment]
Bon... ça fait 2 jours que je n'arrivais pas à descendre cette fichue liste et là ou je me décide à faire un ticket avant de me co maintenant j'y arrive.
Si ça se reproduit je testerai voir si c'est un addon et reviendrai prévenir la communauté. Merci de la réponse rapide Amandil.
