### ISSUE TITLE
[Arènes] Tirer au travers des piliers

### ISSUE THREAD

**Issue by Apochryphos** [way-of-elendil/3.3.5#765]
**Description**
Il est possible de tirer au travers des piliers dans les arènes, ceux ci sont fait pour gêner la vue en temps normal.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- En arène, Notamment celle de Fossoyeuse, mettez deux personnages chacun à l'opposer d'un même pilier et bien vous pourrez cast un sort sur l'adversaire.

**Comportement attendu**
Les piliers sont là pour gêner la vision et rajouter de la stratégie, ici les hunts et autres tires auto se font un malin plaisir de pouvoir profiter de tirer tout en courant, alors qu'ils ne sont pas sensés.

**Captures d’écran / Vidéos**
Dure de prendre une capture d'une balle.

**Ressources additionnelles**
/

**Comment by joshwhedon** [comment]
On y peut malheureusement rien, c'est un melange de problemes de maps et de lags cote client / serveur.

**Comment by Justforsoloq** [comment]
Non surtout que je pense que tu t'es pris des AA qui sont partis avant que tu passes le poteau et donc tu les a reçus une fois derrière le poteau.
Ou sur fossoyeuse c'est surtout que tu t'es mal placé, car les poteaux de Foss sont plutôt traitre
