### ISSUE TITLE
NPC: Teron Fielsang

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#768]
**Description**
21797 - [Ancient Shadowmoon Spirit]
21867 - [Teron Gorefiend]
21877 - [Karsius l'Antique Guetteur] 
10645 - [Teron Fielsang, je suis...]

Cas où Teron est bloqué et n'a pas despawn

**Étapes de reproduction**
- Lancer l'event en prenant la quête Teron Fielsang, je suis...
- On entre pas en combat contre Karsius si on ne l'a pas touché (normal)

1. Alt+f4 dans Teron en étant pas en combat contre Karsius
- à la reconnexion, les 2 NPCs sont là et amicaux, Karsius finit par despawn, pas Teron.

2. Ou patienter derrière un des murs que Karsius despawn tout seul
https://woehead.way-of-elendil.fr/?spell=37784 Ne passe pas hors champ de vision (je suppose que c'est normal)

**Comment by joshwhedon** [comment]
Donc le soucis c'est juste que Teron despawn pas ?

**Comment by Ischjgt** [comment]
Oui, mais du coup l'ancien esprit d'ombrelune respawn pas et c'est un donneur de quêtes
https://woehead.way-of-elendil.fr/?npc=21797
