### ISSUE TITLE
Bug dégats déchirure (feral)

### ISSUE THREAD

**Issue by Rvmpvmpvm** [way-of-elendil/3.3.5#769]
Bonjour, 
Je me suis aperçu, ainsi que d'autres joueurs de druide feral, d'un gros, pour ne pas dire énorme bug sur les dégats de la déchirure [https://wotlk.evowow.com/?spell=49800](url) .

En effet, étant un "finisher" TOUJOURS utilisé avec 5 points de combo, ce sort représente, dans des conditions normales, approximativement 20% du dps d'un druide feral, ce qui n'est plus le cas depuis la merge.

Voici les dégats actuels : 

Avec buff 30% : [https://imgur.com/WuqfyjM](url)
Sans buff 30% : [https://imgur.com/7rRARyQ](url)

Le second screen étant en raid 10, il y a forcément une différence donc à défaut d'avoir un screen je vous donne un extrait de logs incluant un autre druide que le mien mais avec un stuff similaire ayant été pris sur Halion 25 le 01/04/2020 : [http://www.worldoflogs.com/reports/ibto809kh8jea8o3/spell/49800/](url)

Pour confirmer mon premier screen avec le buff 30 je vous joins également les logs de mon dernier ICC 25h : [http://www.worldoflogs.com/reports/uaxmpz2qhc3yq5dr/spell/49800/](url)

Maintenant, comparons les dégats infligés par mon perso, stuff très correct et ceux fait par un perso full BiS : 
- petit chat [https://imgur.com/WuqfyjM](url)
-gros chat [https://imgur.com/gdzuREs](url)

Cependant, chose bizarre, la mutilation [https://wotlk.evowow.com/?spell=48566](url)
ainsi que le buff du rugissement sauvage [https://wotlk.evowow.com/?spell=52610](url) augmentent bien les dégats de la déchirure mais alors pourquoi pas le buff ICC, ni vraisemblablement pas les procs bijoux, ni les stats des persos. ?

Je me tiens à votre disposition si jamais vous aviez besoin d'infos supplémentaires,
Cordialement,
Un chat triste.

**Comment by Justforsoloq** [comment]
Je vous aide en vous joignant un World of log d'un feral pve des Method en fin d'xpac (normalement bien stuff)
http://www.worldoflogs.com/reports/m95i3mcw4ncujkb0/details/8/?s=1657&e=1798
Average no crit du rip (déchirure) : 3313.6
Average crit rip (déchirure) : 7742.8

(Je nuance quand même le propos qui dit que ça fait 20% du dps, on voit là que c'est plus de l'ordre du 15%)
