### ISSUE TITLE
Boss: Novos l'Invocateur - Drak'Tharon

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#771]
**Description**
Name: Novos the Summoner
Entry: 26631.
47346 - [Champ arcanique, rank 1 frFR]

Quand un joueur arrive au cac, Novos ne cast plus son champ arcanique et est vulnérable aux coups blancs même si la P1 n'est pas finie

**Comment by joshwhedon** [comment]
Je fais un changement qui va affecter toutes les auto attaques sur tout, faudra me dire si ca cause des problemes.
