### ISSUE TITLE
La bataille pour la cime des croisé

### ISSUE THREAD

**Issue by jol064** [way-of-elendil/3.3.5#772]
Bonjour,
Lorsque je dois protéger le drapeau, je suis censé être boosté, mais je ne le suis pas, donc je n'arrive pas a tuer les ennemis.

Elfe de la nuit / chasseur / niveau 78.

Merci

**Comment by joshwhedon** [comment]
Vous avez le buff sur vous non ? Qui augmente les degats ?

**Comment by jol064** [comment]
Oui j'ai le bon, ça m'indique que je suis augmenté, mais je n'ai rien de vraiment augmenté, ni vie, ni mana, ni dps.....
