### ISSUE TITLE
Quest: La caravane de Gizelton

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#773]
**Description**
5943 - [La caravane de Gizelton] 
5821 - [On engage : gardes du corps] 
11625 - [Cork Gizelton]
11626 - [Rigger Gizelton]
11564 - [Kodo de la caravane de Gizelton]

https://fr.classic.wowhead.com/quest=5943/la-caravane-de-gizelton#english-comments

1. During the "escort" leg of the trip both direction, they move more slowly. Otherwise they move at run speed.
**=> C'est pas le cas ici, ils sont toujours en run speed, même pendant les quêtes d'escorte**

2. 00:00 Caravan arrives from it's previous southward journey. Super-Seller 680 spawns.
10:00 Rigger Gizelton says "Time for the Gizleton Caravan to head on out! We'll be back soon but if you cannot wait, head north to Kormek's Hut. We open shop in about an hour." Super-Seller 680 despawns. Caravan sets off eastwards.
10:56 Caravan halts just outside Mannoroc Coven. Rigger Gizelton yells zonewide "This is Rigger Gizelton asking for assistance escorting my caravan past Mannoroc Coven. I'm on the road east of Shadowprey village." The quest then becomes available from Cork.
**=> Cork Gizelton dit : Désolé de quitter un client, mais nous ne pouvons rester plus longtemps, nous avons des gens à escroquer. Nous serons de retour plus tard dans la journée. Au revoir !
Gréeur Gizelton dit : La caravane de Gizelton doit se mettre en route ! Nous serons de retour bientôt, mais si vous ne pouvez pas attendre, allez à la hutte de Kormek vers le nord. Nous ouvrons boutique dans environ une heure.
Ces 2 phrases ne sont pas dites au bon moment, elles doivent être dites lorsque la caravane quitte là où elle s'arrete 10 minutes, Cork Gizelton pour le départ au nord et Gréeur pour le départ au sud**

3. Les NPCs doivent aider à tuer les mobs qui spawn, ils ont l'air hostile avec personne du coup pas besoin de les suivre de très près pour finir les quêtes. 
Je sais pas avec qui ils sont censés être hostiles mais :
"All npc caravan members will help kill if the mobs are close enough.
Two to three fights of about 3 mobs each, all lv 34-38 range IIRC.
You can heal any NPC if they get low on health.
If you fight a mob that isn't part of quest, any mob on side of road, if you bring it close enough to caravan they'll start killing it too."

4. Une fois un tour complet fait, revenu à son point de spawn, la caravane s'arrête
A ce moment il est possible de reprendre 5943 - [La caravane de Gizelton] , donné normalement au sud.
Mais la caravane ne bougera plus :(

Edit : 5. Gréeur Gizelton est toujours dans le derrière d'un kodo ça peut géner pour prendre la quête

**Comment by Amilgaull** [comment]
Je rajoute quelques coordonnées :
La quête https://woehead.way-of-elendil.fr/?quest=5943 n'est supposée pouvoir être prise uniquement lorsque la caravane s'arrête aux coordonnées suivantes : 
Map: 1 (Kalimdor) Zone: 405 (Désolace) Area: 602 (Convent de Mannoroc) Phase: 1
05:54:23 X: -1798.398560 Y: 2118.734375 Z: 63.703762 Orientation: 3.606041
05:54:23 grid[28,35]cell[5,7] InstanceID: 0
05:54:23  ZoneX: 47.034637 ZoneY: 75.068199
05:54:23 GroundZ: 63.704330 FloorZ: 63.704330 Have height data (Map: 1 VMap: 1 MMap: 1)

La elle reste récupérable jusqu'à ce que la caravane aille : 
Map: 1 (Kalimdor) Zone: 405 (Désolace) Area: 405 (Désolace) Phase: 1
05:05:29 X: -1298.906982 Y: 1227.615234 Z: 110.041206 Orientation: 1.563761
05:05:29 grid[29,34]cell[4,2] InstanceID: 0
05:05:29  ZoneX: 66.855637 ZoneY: 58.406906
05:05:29 GroundZ: 110.041351 FloorZ: 110.041351 Have height data (Map: 1 VMap: 1 MMap: 1)
Une fois à cette position la caravane reste immobile et ne bouge plus.

**Comment by joshwhedon** [comment]
Je fais ce que je peux pour cette quete, mais c'est de la merde donc ... les modifs que je fais devront suffire. Escorte bidon.

**Comment by Ischjgt** [comment]
1. Pas test, je le ferai demain [EDIT À VENIR]
2. Je crois que c'est toujours d'actualité
3. Pas test, je le ferai demain [EDIT À VENIR]
4. Je venais surtout pour ça, la caravane ne fait qu'un tour, j'ai testé sans lancer de quête pour l'instant juste en suivant la caravane en gm on

**Comment by joshwhedon** [comment]
On y peut rien faut faire avec.

**Comment by Amilgaull** [comment]
Pas très propre mais pour passer outre le soucis, ne serait il pas envisageable une fois la caravane arrivée au point où actuellement elle bug, d'ajouter une commande pour tuer les pnjs et ainsi reset la caravane. Ainsi il n'y aurait plus de soucis puisque le reste fonctionne ?

**Comment by joshwhedon** [comment]
Non, elle va respawn a son point de depart.
