### ISSUE TITLE
Skill: Compétences d'armes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#774]
**Description**
Il est possible d'up ces compétences sur des mobs gris
https://woehead.way-of-elendil.fr/?skills=6

**Comment by joshwhedon** [comment]
Le levelup des competences d'arme / armure ne depend pas du niveau du joueur mais du niveau de la competence. Si la competence d'arme est celle d'un niveau 40, elle pourra etre montee sur des mobs de niveau 40.
