### ISSUE TITLE
[Etat de combat] Bug du mécanisme d'entrée en combat avec les pet

### ISSUE THREAD

**Issue by Popeyeddd** [way-of-elendil/3.3.5#775]
**Description**
Actuellement, quand une des 3 classes à pet (lock hunt unholy) envoi son pet attaquer une target, le pet rentre en combat et le maitre reste hors du combat. Ce qui jusque là est normal.
Mais si la cible se met à attaquer le pet en retour alors le maitre est mit en combat à son tour, ce qui n'est pas normal.

**Comportement attendu**
Si le pet se fait attaquer par une personne ou si il attaque une personne il entre en combat. Mais le pet est une entité distincte de son maitre et son état de combat ne doit pas être répercuté sur le maitre. Par exemple un hunt qui envoi son pet attaquer une cible ne passe pas en combat, si la cible attaque le pet, le hunt ne passe pas en combat et  par contre si le hunt utilise mend pet sur son pet en combat ofc il rentre en combat

**Captures d’écran / Vidéos**
http://www.warcraftmovies.com/movieview.php?id=122825 environ 3:10 
http://www.warcraftmovies.com/movieview.php?id=152507 environ 9:54

Remarque attention de ne pas retirer la mécanique chelou de retail, qui fait que si un maitre de pet envoi son pet il devient "insapable" sans pour autant être en combat (ne concerne que les vrais pet, donc pas amélio / mage ect) 
doc:
http://www.arenajunkies.com/topic/118924-combat-bug-with-pet/
http://www.arenajunkies.com/topic/154952-pet-combat-sap-bug/
http://www.arenajunkies.com/topic/72876-pet-combat-bug/

PS : au passage autre bug lié au combat, l'incandescence mentale de prêtre ne met pas en combat le prêtre qui l’utilise sur une cible
Ah et re PS : Faudrait vérifier mais le fait de kill une personne nous sort direct de combat, gros gros doute là dessus.

**Comment by Popeyeddd** [comment]
J'ai mis 2 psssss en bas josh hihi

**Comment by joshwhedon** [comment]
Tes liens marchent pas.

**Comment by Popeyeddd** [comment]
Ah beau jeu arena junkies a fermé bah tant pis

**Comment by Popeyeddd** [comment]
http://web.archive.org/web/20160728045642/http://www.arenajunkies.com/topic/118924-combat-bug-with-pet
http://web.archive.org/web/20151225034540/http://www.arenajunkies.com/topic/154952-pet-combat-sap-bug/
http://web.archive.org/web/20190406121130/http://www.arenajunkies.com/topic/72876-pet-combat-bug

**Comment by joshwhedon** [comment]
Pour les autres bugs, si ils sont reellement des bugs, merci de faire un ticket a part avec des sources. (l'incandescence mentale je doute que ce soit un bug, le sort n'a aucun attribut indiquant qu'il ne doit pas mettre en combat).
