### ISSUE TITLE
Item: Glyphe de sceau d'autorité

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#779]
**Description**
https://woehead.way-of-elendil.fr/?spell=31878 et  https://woehead.way-of-elendil.fr/?spell=55109 
Glyphe de sceau d'autorité et Jugements des sages ne cumulent pas

Pas trouvé d'infos sur le fait que ce soit possible ou non, du coup par curiosité, je viens demander

**Comment by joshwhedon** [comment]
Les deux fournissent le meme buff de regen mana (meme id de sort), une aura ne peut etre applique qu'une fois par lanceur de sort.
57669
C'est le cas avec tous les sorts qui declenchent replenishment.

**Comment by joshwhedon** [comment]
J'ai cherche un peu partout, le sort utilise est le bon, donc base sur les regles generales existantes (un sort ne peut etre applique qu'une fois par un joueur), le comportement est probablement normal. Ils ne se cumulent pas mais ils se refresh l'un l'autre.
