### ISSUE TITLE
talent "Morts voraces "

### ISSUE THREAD

**Issue by jarraxuss** [way-of-elendil/3.3.5#782]
Bonjour après plusieurs tests j'ai pu remarquer que le talent "Morts voraces" http://woehead.way-of-elendil.fr/?spell=49572 ne s’applique pas a l’armée des mort https://woehead.way-of-elendil.fr/?spell=42650#modified-by du dk impie alors que le talent précise bien "vos goules" donc soit il y a une erreur et dans ce cas la il faut mettre votre goule donc le pet goule de l'impie soit de corriger et donner plus de stats au goules de l’armée des morts, car actuellement sur trois test une fois en impie full stuff une fois en impie avec aucun équipement et une fois en spe sang full stuff j ai remarquer que mes goules faisait de plus en plus de dégâts alors qu'elle devrait prendre des stats du joueur la elle tapent plus fort quand je n'ai pas de stuff équiper ou que je n ai pas le talent. https://ibb.co/P4RxgWB (premier test avec la spe impie et full stuff
https://ibb.co/qJQsnwn (deuxième test avec la spe impie mais pas de stuff (0gs) )
https://ibb.co/kqX0hL4 (dernier test avec la spe sang sans le talent morts voraces et full stuff )

Étapes de reproduction : prendre un dk lancer l’armée des morts plusieurs fois en changeant son stuff ou sont template

comportement attendu : Les goules de l’armée des morts devrait gagner des stats en fonctions du talent "Morts voraces" et du stuff/stats du dk

**Comment by jarraxuss** [comment]
j ai oublier de preciser qu'a chaque test je donnais le buff vor de l'hiver (+155 force +155 agi )

**Comment by joshwhedon** [comment]
https://www.wowhead.com/forums&topic=97396 confime

**Comment by joshwhedon** [comment]
https://wow.allakhazam.com/wiki/Death_Knight's_DPS_FAQ_%28WoW%29
