### ISSUE TITLE
NPC: Cultist Bombardier

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#784]
**Description**
Name: Chillmaw
Entry: 33687.
Name: Cultist Bombardier
Entry: 33695.

1. Le sectateur mort ne respawn pas si Frissegueule n'est pas mort
2. Si un sectateur est ejecté de Frissegueule et que Frissegueule quitte le combat, celui ci reste au sol

**Comportement attendu**
J'ai pas trouvé d'infos là dessus mais par exemple pour le 1. ça implique que Frissegueule soit tué 2 fois, et y'a rien qui parle de ça

**Comment by Ischjgt** [comment]
1. OK
2. Toujours là

**Comment by joshwhedon** [comment]
Ils despawn apres 5 minutes. Je peux pas les faire despawn hors combat.
