### ISSUE TITLE
Gob: Malykriss Furnace - Je fonds… Je fonds !

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#785]
**Description**
[Malykriss Furnace] GUID: 99727 ID: 193004
https://woehead.way-of-elendil.fr/?item=43289
https://woehead.way-of-elendil.fr/?quest=13138
Impossible de valider la quête si le joueur a fini 13161 13162 13163

**Comportement attendu**
C'est comme https://github.com/way-of-elendil/3.3.5/issues/703
- En fait, est ce que le joueur doit pas repasser en phase 1 quand https://woehead.way-of-elendil.fr/?quest=13164 est finie ?
J'ai perdu la mémoire je saurais pas te dire :(
- Ou alors gob présent en phase 1 et 4

**Comment by joshwhedon** [comment]
Je pense que c'est la phase du gob.
