### ISSUE TITLE
NPC: Tranchegueule

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#787]
**Description**
Entry: 17592.
9689 - [Tranchegueule]  [active]
[Ever-burning Pyre] GUID: 42119 ID: 181988
24221 - [Paquet d'os de dragon] 

après avoir utilisé le Paquet d'os de dragon, Tranchegueule spawn au loin mais reste en l'air et ne bouge pas, si on s'approche un peu de lui (pas sur que ce soit possible pour un joueur, j'ai volé), l'event où il atterit sur le lieu de serres se déclenche

**Comment by joshwhedon** [comment]
Je le fais spawn plus pret pour que le script se declence.
