### ISSUE TITLE
Glyphe des horions "chaman"

### ISSUE THREAD

**Issue by JAGGERstark** [way-of-elendil/3.3.5#788]
****

- Chaman
- orc
- élementaire
- Horions flamme / givre

**Comportement attendu**
réduit le temps de charge global (GCD) déclencher par vaux horions de 1 sec .
https://wotlk.evowow.com/?item=41526
 
je crois qu il ne marche pas je ne vois pas la différence avec ou sens 
même si le gcd et de 1.5 sec et qu il passe a 0.5 on dois voir la différence entre 1.5 sec et 0.5 sec sa fais 70% de vitesse en plus

**Comment by Kwyzard** [comment]
fait le test avec macro gcd

/cast "ton horion"
/run local _,d = GetSpellCooldown(61304); print(d)

**Comment by Ischjgt** [comment]
Ça réduit pas de 1 seconde,
ça réduit à 1 seconde

**Comment by Ischjgt** [comment]
Je laisse ouvert parce que la trad en français est mauvaise
<img width="459" alt="Capture d’écran 2020-05-22 à 17 32 38" src="https://user-images.githubusercontent.com/60295792/82684034-42314d00-9c52-11ea-8e41-39eddf7c1ae9.png">

**Comment by Justforsoloq** [comment]
En anglais "to 1 sec" pas "by 1s" 
Donc je comprends là ce que t'as dit aussi Ischjgt que le gcd est d'1s pas réduit d'1s.

**Comment by joshwhedon** [comment]
La traduction provient des donnees client pour les sorts. Donc le bug est blizzlike (et on peut pas corriger les textes de sorts). Pour ce qui est du gcd je confirme que ca le reduit de 500ms, donc a 1 seconde.
