### ISSUE TITLE
[Important] bug charge/interception/intervention 

### ISSUE THREAD

**Issue by drizz3r** [way-of-elendil/3.3.5#789]
**Description**
Le patern de charge,interception et intervention est bug car malgré le fait de prendre un CC la charge devrait pas s'arrêter du point A au point B, malgré le CC

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Warrior
- Race
- Spécialisation
- Charge/Interception/Intervention
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Les sorts ne devraient pas être arrêtés par des nova/stuns etc, la charge devrait continué son trajet comme dans les vidéos que je link en-dessous

**Captures d’écran / Vidéos**
https://youtu.be/K4958y3xz2c?t=246 - sur la fireblast on voit très bien la charge continué malgré ça on voit bien le war stun, d'autres preuves
https://youtu.be/K4958y3xz2c?t=319 - Fireblast à nouveau dès le début du trajet de la charge
https://www.youtube.com/watch?v=qSGJRoVGFeU&feature=youtu.be&t=5 - on voit bien la nova sur la charge qui ne stop en aucun cas le pathing de la charge

Inutile de préciser que ce sont des vidéos de Gforce sur officiel.
**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Popeyeddd** [comment]
inutile de préciser mais t'as précisé je te signale !! donc c'est pas très cohérent je trouve mais bon

**Comment by joshwhedon** [comment]
Je mets un correctif, mais vraiment dur a reproduire donc faudra me dire si ca casse des trucs.

**Comment by Kwyzard** [comment]
Pour dire vrai ont voit pas grand chose sur les vidéos apporté, le coup de la nova on croirait à un cut vidéo carrément et pour les fireblast la charge se fini quand même loin du mage non ? Ont dirait presque qu'il n'est pas a portée d'auto attaque

**Comment by joshwhedon** [comment]
JE sais mais malgre tout il arrive a etre suffisament proche pour pouvoir stun, donc ca laisse penser que le mouvement s'est fini malgre tout.

**Comment by joshwhedon** [comment]
Y'a un peu de documentation qui indique que la charge s'est toujours comportee bizarrement avec les novas et autres sorts. Ca va etre difficile de savoir le vrai du faux.

**Comment by drizz3r** [comment]
Heu on voit bien qu'il se fait fireblast dès le début de la charge je ne vois pas trop où tu veux en venir pour dire que tu ne vois pas grand chose sur ces vidéos. Et il est bien à porté d'attaque puisqu'il brise genou, il serait question de bien regarder les vidéos avant de poster un commentaire.
Cordialement =)
