### ISSUE TITLE
bug déchirure

### ISSUE THREAD

**Issue by Rvmpvmpvm** [way-of-elendil/3.3.5#790]
La déchirure [https://woehead.way-of-elendil.fr/?spell=49800](url) dans la spé feral dps des druides ne fait les dégats escomptés.
Après plusieurs tests et comparatifs j'en suis arrivé aux conclusions suivantes : 
-le buff 30% d'ICC ne s'applique pas comme vous pouvez le constater sur les screens suivants [https://imgur.com/pgbf11I](url) dans icc en 25. Je vous joins également des logs pris 3 jours plus tard mais dans des conditions similaires [http://www.worldoflogs.com/reports/6odk1aau676kiyas/spell/49800/?s=3106&e=3287](url)
[https://imgur.com/g8lh82Y](url) après halion en 25 également, je n'ai pas pensé à prendre le screen en étant dans l'instance mais avec l'heure et la date vous aurez 24 personnes qui confirmeront que c'est vrai.

-le script du sort ne tient vraisemblablement pas compte des stats du perso : sur le premier screen, un druide full BiS [https://imgur.com/SWQGvcZ](url) sur le second, le mien, stuff correct [https://imgur.com/pgbf11I](url)

Pour étayer le fait que le sort bug ici, voici des logs d'un joueur de chez Method en fin d'extension sur offi [http://www.worldoflogs.com/reports/mdprj1k1x67zaot5/spell/49800/?s=1232&e=1380](url)

Actuellement pour atteindre les dégats normaux de la déchirure il faut être sous hystérie et bénéficier de la morsure sur la reine : [https://imgur.com/t3yB6EB](url) [https://imgur.com/4MLDcKq](url)

Hésitez pas s'il faut d'autres screens/logs je vous en fournirai via discord.

**Comment by Ischjgt** [comment]
Les multiplicateurs de dégats sont bien comptés mais on dirait qu'il y a des stats pas prises en compte, le calcul ne se fait pas à la fin.

**Étapes pour reproduire**
- sans talents sans glyphe, mannquin, forme de félin
- mannequin
- déchirure à 1 stack, noter le tick
- .aura 71530
- déchirure à 1 stack, noter le tick, 
=> c'est pas x2

**Comment by Rvmpvmpvm** [comment]
[https://imgur.com/WHUBvI9](url) ça donne ça

**Comment by Ischjgt** [comment]
(C'était adressé à Josh)

**Comment by Rvmpvmpvm** [comment]
Ah!
Bon j'ai ça aussi si jamais ça aide : 
pas de mutilate, pas de SR, pas de proc berserker : 1.1k min 2.6k max 2.1k moy
mutilate, pas de SR : 1.5k min 3.5k max 2.7k moy
SR, pas de mutilate : 1.3k min 2.9k max 1.9k moy
SR, mutilate, procs : 1.8k min 4.1k max 3.7k moy
SR = savage roar
J'ai testé sur poteau, uniquement avec le buff druide
