### ISSUE TITLE
Impossible de rendre quete Chapitre 1 - Strangleronce

### ISSUE THREAD

**Issue by manu1649** [way-of-elendil/3.3.5#791]
**Description**
Impossible de rendre la quête "Chapitre I" à Strangleronce alors que j'ai les pages 1, 4, 6 et 8 dans mon sac

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Vallée de Strangleronce - Expedition de Nesingwary
- Faction / Race / Classe du personnage utilise : Horde/ Elfe de sang / Paladin / lvl 38
- Nom perso : Ezïo
- Nom de la quête : Chapitre I
- Nom du donneur de quête : Barnil Potepierre

**Comportement attendu**
J'aimerai pouvoir rendre la quête

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

![quete chapitre 1 -A](https://user-images.githubusercontent.com/65810929/82728403-401dcb80-9cf0-11ea-9fb4-c5bd73d4dd3a.PNG)
![quete chapitre 1 -B](https://user-images.githubusercontent.com/65810929/82728404-40b66200-9cf0-11ea-99f4-fa93fbc3a537.PNG)
![quete chapitre 1 -C](https://user-images.githubusercontent.com/65810929/82728405-40b66200-9cf0-11ea-8415-dbe8cbcbabf2.PNG)

**Comment by Ischjgt** [comment]
Salut, abandonne et reprend la quête

**Comment by joshwhedon** [comment]
Oui malheureusement ca arrive souvent quand les objets restent dans l'inventaire trop longtemps. Abandonner et reprendre la quete regle le soucis. Le probleme a deja ete signale pour d'autres quetes.
