### ISSUE TITLE
[Joug] Bug buff de grade

### ISSUE THREAD

**Issue by Popeyeddd** [way-of-elendil/3.3.5#792]
**Description**
Parfois quand on rejoint le joug, on a pas de buff de grade et par conséquent on ne peut pas l'améliorer.

**Étapes de reproduction**
Aucune idée
Cette aprem j'ai queue 2 fois de suite au Npc du joug et les 2 fois j'ai pop dans le joug sans grade. Quand je suis entré via le portail sans queue au npc j'ai eu le grade.
Donc je ne sais pas si il y a un lien ou pure rng

**Comportement attendu**
Ofc obtenir le buff de grade dès qu'on entre dans le groupe de raid du joug

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Kwyzard** [comment]
Ouai il semblerais que quand tu est téléporté d'une zone vers le joug en acceptant la queue du joug tu n'obtient pas le grade, seulement si tu est présent dans la zone et que tu accepte le joug tu obtient le grade

**Comment by Kwyzard** [comment]
Toujours bug

**Comment by joshwhedon** [comment]
Ok je mets autre chose demain

**Comment by Ischjgt** [comment]
C'est arrivé à un joueur ce matin et hier

> chuchote : bonjour , via la file d'attente du pnj à dalaran
chuchote : et effectivement les deux fois ou ça m'est arrivé c'est comme ça que j'y suis rentrée
chuchote : je me demandais si c'était lié

Je réouvre mais peut-etre qu'avec ce que tu m'as dit cette nuit c'est trouvé ?

**Comment by Ischjgt** [comment]
Il vient de m'arriver la même :
Côté Horde en attaque, j'ai rejoint le joug en parlant au PNJ à Dalaran
