### ISSUE TITLE
chasseur: le pet se soigne sans en avoir besoin en début de combat

### ISSUE THREAD

**Issue by Nuktos** [way-of-elendil/3.3.5#794]
**Description**
Depuis un moment, je remarque ce bug, je ne sais pas si c'est depuis que je suis niveau 74 ou si c'est après avoir appelé un MJ en jeu parce qu'il buggait (le pet avait eu des apparences d'amas de chair/amas d'os au lieu de son apparence de phalène bleu), mais en début de séance de farm j'ordonne un /petattack à mon phalène, il fait deux pas, puis il semble se buff, puis reste trois-quatre secondes sans rien faire, avant d'enfin foncer vers l'ennemi. ça n'arrive que la première fois sur la séance, si je prends une monture et ne me bat pas pendant un certain temps, il le refera, mais sinon il ne le refera pas de toute la séance. J'ai d'abord pensé qu'il avait un problème récurrent de path finding, mais ça me semblait gros. J'ai testé sur les mannequins d'entrainement, il ne fait jamais ça, il combat comme normalement. Et dans tous les cas, si je prends l'aggro en premier, mon phalène se buff et suit directement.

Donc j'ai testé un /petattack sur un loup bas niveau de Dun Morogh, il est resté bloqué 3-4 secondes comme prévu puis l'a attaqué, et j'ai regardé l'historique de combat, voici ce que ça dit:
[https://cdn.discordapp.com/attachments/511222463305220108/714238302466605076/unknown.png](https://cdn.discordapp.com/attachments/511222463305220108/714238302466605076/unknown.png)
On voit donc que mon phalène (Painapuru) utilise plusieurs fois "lécher ses plaies" et "poudre de sérénité" de suite, et ce alors qu'il n'a pas besoin de soin. (bon, la poudre donne un buff donc c'est normal qu'il l'utilise, mais une seule fois!). Je pourrais simplement dé-automatiser "lécher ses plaies", mais c'est pas pratique et c'est pas un comportement normal du jeu, avant il n'utilisait pas cette attaque à outrance.

**Étapes de reproduction**

- Classe: chasseur
- Race: draenei (et phalène bleu)
- Spécialisation: voilà l'arbre de talents de mon pet et le mien en maîtrise des bêtes: [https://cdn.discordapp.com/attachments/511222463305220108/714283961257558057/unknown.png](https://cdn.discordapp.com/attachments/511222463305220108/714283961257558057/unknown.png)

**Comportement attendu**
normalement, quand je fais /petattack, mon pet est censé faire juste poudre de sérénité, "piqué" sur le mob  et se battre normalement ensuite.

si besoin, vous pouvez ping `@Nyctémère🌒#0399` sur discord pour qu'on voie ça ensemble

**Comment by joshwhedon** [comment]
Alors j'ai pas trouve grand chose sur le comportement attendu, mais apparament il faut surtout pas mettre ce sort en auto attaque, parce que les pets sont cons et l'utilisent des qu'il est pret.
Cette video explique ca : https://www.youtube.com/watch?v=FiQByHvLXtk
Donc a premiere vue, les pets sont cons, mais blizzlike, il font bien ce qu'ils doivent (c'est a dire le lancent des que le sort est pret plutot que quand le pet est blesse).

**Comment by Nuktos** [comment]
> Alors j'ai pas trouve grand chose sur le comportement attendu, mais apparament il faut surtout pas mettre ce sort en auto attaque, parce que les pets sont cons et l'utilisent des qu'il est pret.
> Cette video explique ca : https://www.youtube.com/watch?v=FiQByHvLXtk
> Donc a premiere vue, les pets sont cons, mais blizzlike, il font bien ce qu'ils doivent (c'est a dire le lancent des que le sort est pret plutot que quand le pet est blesse).

Mais je ne sais pas pourquoi il ne le faisait pas avant, et là on remarque avec "lécher ses plaies" qu'il le lance 3 fois de suite, ce qui n'est pas normal vu que ça ne recharge pas toute de suite, et on voit 5 fois les effets de soin. De plus, il ne le fait ni quand je frappe en premier, ni sur un mannequin.  Donc je pense que c'est plus compliqué que ça et qu'il faut observer plus en détail.

ce qui me dérange c'est pas tant qu'il consomme le sort, mais qu'il reste plusieurs secondes sans réagir. je pourrais juste changer mes habitudes, initier les attaques, mais ça ne m'arrange pas pour le placement distance et pour envoyer mon pet faire des trucs pendant que je ne participe pas au combat (pour faire des quêtes de ramassage d'items, pour dépecer en paix...)

**Comment by joshwhedon** [comment]
Tu as desactive le lancement auto du sort ? Parce que le soucis c'es que c'est un sort canalyse, qui dure plusieurs secondes. Du coup il fait rien pendant la canalysation.

**Comment by Nuktos** [comment]
oui, je l'ai désactivé. ça veut dire qu'on s'en fout du reste?

**Comment by joshwhedon** [comment]
Bah en fait je comprends pas qu'est-ce que c'est que "le reste". Il lance la canalisation une fois, et elle tick plusieurs fois (de ce fait tu as plusieurs effets de soin dans le log). Du coup pendant la canalisation, le pet ne fait rien d'autre que canaliser son sort. Je comprends pas quel est le probleme,

**Comment by Nuktos** [comment]
> > Alors j'ai pas trouve grand chose sur le comportement attendu, mais apparament il faut surtout pas mettre ce sort en auto attaque, parce que les pets sont cons et l'utilisent des qu'il est pret.
> > Cette video explique ca : https://www.youtube.com/watch?v=FiQByHvLXtk
> > Donc a premiere vue, les pets sont cons, mais blizzlike, il font bien ce qu'ils doivent (c'est a dire le lancent des que le sort est pret plutot que quand le pet est blesse).
> 
> Mais je ne sais pas pourquoi il ne le faisait pas avant, et là on remarque avec "lécher ses plaies" qu'il le lance 3 fois de suite, ce qui n'est pas normal vu que ça ne recharge pas toute de suite, et on voit 5 fois les effets de soin. De plus, **il ne le fait ni quand je frappe en premier, ni sur un mannequin**. Donc je pense que c'est plus compliqué que ça et qu'il faut observer plus en détail.
> 
> ce qui me dérange c'est pas tant qu'il consomme le sort, mais qu'il reste plusieurs secondes sans réagir. je pourrais juste changer mes habitudes, initier les attaques, mais ça ne m'arrange pas pour le placement distance et pour envoyer mon pet faire des trucs pendant que je ne participe pas au combat (pour faire des quêtes de ramassage d'items, pour dépecer en paix...)

**Comment by joshwhedon** [comment]
J'ai teste sur mannequin c'est comme ca que j'ai reproduit. Le pet lance le sort immediatement quand en combat, si le sort est pret (il a 5 minutes de cooldown). Il le fait aussi quand je frappe en premier (et qu'il est en aggressif ou defensif).  Aucune idee si il le faisait ou pas avant, tout ce que je sais c'est que maintenant le comportement c'est : si le sort est pret et est en auto cast, le pet le lance des qu'il est pret. Et ca c'est le comportement pour tous les sorts en auto cast.
