### ISSUE TITLE
Crit autohit / Divinestorm Pala ( Coeur du croisée )

### ISSUE THREAD

**Issue by Satarians** [way-of-elendil/3.3.5#795]
Description : Taux de crit anormal en Ret, principalement autohit et divinestorm ( du coup tout ce qui est mélée)

Étapes de reproduction:

    Classe: Paladin
    Race: Pala
    Spécialisation : Retri 7/17/51
    Sort / Talent / Etc : Divinestrom / Autohit / Coeur du croisée ( talent )
    Circonstances : Mannequin d'entrainement de grand maitre ( 80 non elite )

Les talents [Conviction] [Bataille sainte] ont l'air de marcher, Coeur du croisée je sais pas

Comportement attendu :
Un peu plus de crit : 45% de crit + 3% ( Coeur du croisée) = 48%, ici j'ai 39% en DS et 43% en autohit, si on enleve les 22 parades esquives les stats sont légèrement supérieur.

Captures d’écran / Vidéos :

![WoWScrnShot_052520_165333](https://user-images.githubusercontent.com/63306263/82823871-9afa2300-9ea8-11ea-9281-4d6f9509a3a2.jpg)
![WoWScrnShot_052520_113046](https://user-images.githubusercontent.com/63306263/82823874-9e8daa00-9ea8-11ea-882c-6830a46b07b4.jpg)
![WoWScrnShot_052520_113052](https://user-images.githubusercontent.com/63306263/82823880-9fbed700-9ea8-11ea-9627-dc37332b473f.jpg)

**Comment by Ischjgt** [comment]
Tu as le droit de réessayer sur un mannequin 80 de dos
Les boss prennent 5% de critique de moins et le fait que tu te te fasses parade ça influe également ton taux de crit...
Dans tous les cas je regarde cette nuit

**Comment by Satarians** [comment]
jamais l'idée me viendrais de tapé de face, j'ai fait du poto toute la journée avec 3 stuff différents, en vrai   ya rien de concluant, soit un crit trop élever soit trop faible en fonction des sorts mais ya bien un soucis sur le crit, et fleme de recommencer, il en est ou le serv de dev pour faire des tests ?
 1. Satarians 17958464 (100%)

**Comment by Ischjgt** [comment]
Pourquoi tu fermes le ticket ?

**Comment by joshwhedon** [comment]
Si c'est soit trop eleve soit trop faible, ca s'apelle du random :D.

**Comment by Ischjgt** [comment]
> jamais l'idée me viendrais de tapé de face

Ok mais en étant capé expertise alors :D

Bon, voilà comment j'ai procédé 4 mannequins 80 non élite, 32.12% spam DS, 500 hits
Pour le dernier j'ai bien veillé à ce que le débuff cœur de croisé soit posé sur toutes les cibles.

Sans talent, 32.12 :
<img width="254" alt="32 12% Aucun talent" src="https://user-images.githubusercontent.com/60295792/82847757-31056c00-9ef0-11ea-8544-20870e5c5697.png">

Conviction, 32.12 +5 : 37.12
<img width="288" alt="32 12% +5 CONVICTION" src="https://user-images.githubusercontent.com/60295792/82847772-437fa580-9ef0-11ea-8ec2-5e2b40f32751.png">

Conviction + Bataille sainte, 32.12 + 5 + 3 : 40.12
<img width="261" alt="32 12% + 5 + 3 CONVICTION + BATAILLE SAINTE" src="https://user-images.githubusercontent.com/60295792/82847884-eb956e80-9ef0-11ea-8859-a1880f942a30.png">

Conviction + Bataille sainte + Cœur du croisé : 43.12
Désolé, il y en a 400, j'avais un peu la flemme de continuer
<img width="300" alt="32 12% + 5 + 3 + 3 CONVICTION + BATAILLE + COEUR DU CROISE" src="https://user-images.githubusercontent.com/60295792/82847915-0667e300-9ef1-11ea-9a8e-9940b9bd2d8b.png">

Je pense qu'avec 500 coups il peut y avoir une différence de 4/5%
CF mon dernier commentaire https://github.com/way-of-elendil/3.3.5/issues/454 où il y avait un soucis avéré sur Imprécation mais où j'ai quand même eu une bonne diff de 4% sans talent à la corruption
