### ISSUE TITLE
[Quête] La menace vient d'en haut

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#796]
Bonjour.

Il y a un problème en réalisant la quête **La menace vient d'en haut**
https://woehead.way-of-elendil.fr/?quest=13809

Lorsqu'on tape le dragon **Frissegueule** le 1er **Sectateur bombardier** saute, jusqu'ici tout est normal, mais lorsque qu'on le tue, les 2 mobs restant sautent, et disparaissent immédiatement.
Impossible de les attaquer, malgré nos efforts.

La quête est tout de même faisable, on tue 3x **Frissegueule** et en tuant le 1er **Sectateur bombardier** cela permet de valider les objectifs, mais au prix d'attendre le repop.
Nous avons aussi essayé de reset le dragon, mais le 1er **Sectateur bombardier** n'étant plus là, ça ne marche pas.

Il me semble me souvenir que les **Sectateur bombardier** descendaient 1 par 1, mais j'avoue que c'est très vague.

Bon courage.

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/793
