### ISSUE TITLE
Quest: Les larmes de Dahlia

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#798]
**Description**
https://woehead.way-of-elendil.fr/?quest=13078
Ruby Keeper - 27530.
[Dahlia's Tears] GUID: 55103 ID: 192773

- Les gobs à l'est ne sont pas activables pour ramasser ce qu'il y a dedans (seulement en gm on), même après un passage de guardien rubis 

- Quand les dragons font un passage, il manque l'animation du feu, et peut être même le spell tout court parce qu'aucun mort-vivant sur le passage du dragon ne meurt
https://www.wowhead.com/quest=13078/dahlias-tears#comments
"The tears spawn after a Ruby Keeper flies over and breathes fire"

- (Tu sais pourquoi je tombe sur page non trouvée ? https://woehead.way-of-elendil.fr/?object=192773)

**Comment by Killyana** [comment]
Les gobs sont spawns avec un respawn time négative ils respawn quand un dragon passe dessus via le scripts

**Comment by Ischjgt** [comment]
C'est pas le cas pour les gobs à l'est

**Comment by Killyana** [comment]
Je ne sais, sa respawn via l'event wp reached donc improbable que sa fail.

**Comment by joshwhedon** [comment]
Peut etre les memes soucis de movement inform qui se declenchent pas, comme pour d'autres. C'est reproducible ?

**Comment by Ischjgt** [comment]
Si c'est à moi que tu rep :
Non je pense pas que ce soit ça, le dragon à l'est fait quand même son trajet une fois de temps en temps pour faire mine de tout bruler


> C'est reproducible ?
fait .app Pasischjgt, le dragon passe pas sur le gob où je me suis poser

**Comment by joshwhedon** [comment]
@Killyana  il a pas l'air de les respawn. Pour info c'est pas un wp reached c'est via une liste d'action. Du coup la je sais pas si c'est le script qui merde ou bien le code qui permet pas de respawn. Ca marche chez toi en local ?

**Comment by Killyana** [comment]
Je viens de vérifier sur woe:
Y'a 3 drakes guid (108330, 108329, 108202) qui ont le script pour respawn les gobs.
Mais seulement 2 endroit contiennent les gobs ( le chemin de 108330 108202) (spawn manquants)
Et ils respawn bien les gobs en passant.
Le problème c'est que après avoir loot un gob, y'a un drake qui est passé et a respawn le gob que j'ai loot, le gob a respawn mais il était pas cliquable (je l'ai ouvert en GM ON mais y'avait pas d'item dedans, alors que juste à coté y'avait un gob qui clignotait et contenait l'item.


![image](https://user-images.githubusercontent.com/6587064/83022623-189a6c00-a02c-11ea-84a7-a6e14f385583.png)

**Comment by Killyana** [comment]
Le script en lui même est faux, les gob doivent être invoqué par https://woehead.way-of-elendil.fr/?spell=57597  quand le drake passe au dessus de la zone.
Donc pour on fait comme TC, on retire le script des 3 drakes, et en passe les gob en spawn positive en attendant t que l'event soit script

**Comment by joshwhedon** [comment]
Bon j'ai recode en utilisant 57597. Cela dit je pense que 57588 est suppose jouer un role, et je trouve pas le visuel pour les flammes. Du coup ca marchera mais pas totalement blizzlike :(.
