### ISSUE TITLE
[Quête] Ejection des passagers - Frissegueule

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#799]
Pour la quête [https://woehead.way-of-elendil.fr/?quest=13809](url) la menace vient d'en haut (journa du tournoi), le dracoliche Frissegueule [https://woehead.way-of-elendil.fr/?npc=33687](url) est supposé éjecter un sectateur bombardier [https://woehead.way-of-elendil.fr/?npc=33695](url) tous les 25% de sa life. 

Je n'avais pas eu de soucis sur cette quête jusqu'il y a deux-trois jours. Le dragon n'éjecte plus qu'un seul passager, voire aucun, et à la mort du dragon on peut voir les passagers tomber de ses ailes et disparaître.

**Comment by joshwhedon** [comment]
Elle a deja ete signalee et sera corrigee prochaime mise a jour
