### ISSUE TITLE
Instance: Loots EDC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#801]
**Description**
Si un joueur ne fait rien quand un loot tombe depuis un coffre (il ne lance pas les dés ou ne passe pas), le loot disparait quand le boss suivant est lancé

Les caches disparaissent 

EDC5
[Eadric's Cache] ID: 195375
[Confessor's Cache] ID: 195324
[Champion's Cache] ID: 195709

EDC10-25
[Champions' Cache] GUID: 151181 ID: 195633

**Comment by joshwhedon** [comment]
C'est normal. Parce que les coffres sont les uns sur les autres. Ce ne sera pas corrige.

**Comment by Ferro3** [comment]
Et ajouter un délai de 5, 10 secondes sur le mouvement du PNJ pour permettre le rand ?
Cela semble un bon compromis

**Comment by joshwhedon** [comment]
Il se passe quoi sur offi?

**Comment by Ferro3** [comment]
Je n'ai pas l'officiel, désolé.

**Comment by Ischjgt** [comment]
5:50
https://www.youtube.com/watch?v=BWGA7QilwJk

Au moment où la joueur lance la suite de l'évènement, les loots qui n'avaient pas encore été distribué (parce que pas rand par des joueurs ?) sont donnés
