### ISSUE TITLE
Spell: Berserk

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#803]
**Description**
- id: 59620 [Berserk] ne semble pas avoir de CD interne

"Testing in patch 3.3.5 + 4.0.1 Berserking has an internal CD of 60 seconds and a uptime of 15 seconds, Regardless of attacks used to proc it, Once procced its a 15 second buff duration and a 60 second CD, no matter what attacks you use after the 15 seconds has passed nothing can refresh its 60 second internal cool down. "

note : Il peut quand même y avoir double proc

- le buff ne peut pas être retiré

**Comment by joshwhedon** [comment]
Il y a pas de cooldown interne pour les enchantements.  C'est des ppm (proc par minute), et actuellement il a un proc par minute de 1 par minute, donc c'est le fonctionnement correct.
Je corrige le fait qu'on puisse pas le retirer.

**Comment by Ischjgt** [comment]
Je viens d'avoir 3 procs avec la même arme en 30 secondes

**Comment by Satarians** [comment]
closed ? :o

**Comment by Kwyzard** [comment]
Close ici veux dire "fixed" j'ai déjà dit que c'était un peu bizarre comme management du bug tracker, mais ils ont surement fix ça viendra demain matin a la nouvelle compil

**Comment by joshwhedon** [comment]
Donc j'ai explique a Ischjgt. Pour les enchantements, le systeme de proc est un systeme de proc par minute. Le ppm definit, base sur la vitesse de base de l'arme, un taux de chance de proc. Par exemple, une arme qui tape, de base, a 3,6 secondes, avec PPM de 1, aura 6% de chance de proc Berserk. Ca veut aussi dit qu'il y a des chances de proc berserk 2 fois d'affilee, comme il y a des chances de ne pas proc berserk pendant 2 minutes. C'est le fonctionnement des enchantements en tout genre.
Notez bien que la hate augmentera le taux de proc, parce que le PPM est base sur la vitesse de base de l'arme, pas sur la vitesse d'attaque du joueur.
Donc pour obtenir un PPM de 1 par minute, il faut taper a blanc pendant 1 heure, sans hate ni rien, et normalement vous aurez aux alentour de 60 procs (ca peut varier bien sur, vu que comme je l'ai dit c'est un % de chance).
J'espere que c'est plus clair. Notez bien que c'est le comportement general pour tous les enchantements. Soit ils ont un % de chance explicite, soit ils ont un ppm.

**Comment by Satarians** [comment]
j'ai 8 procs en 3min avec plusieurs refresh avant qu'il ne  fade, je reregarderais demain
