### ISSUE TITLE
Quete: Enqueter dans les magasins de l'alchimiste

### ISSUE THREAD

**Issue by potassium8** [way-of-elendil/3.3.5#804]
**Description:**
https://woehead.way-of-elendil.fr/?quest=1960
**Début :** Anastasia Hartwell
**Fin :** Anastasia Hartwell

- Une fois dans la zone, après avoir utilisé le scroll des chants de manifestation, les mobs (rift spawn) pop en étant hostile. J'ai pourtant souvenir qu'ils étaient neutres

- ils pop par pack de 4 alors que c'est un par un sur offi

- Une fois hébétés, impossible de les cibler de nouveau pour utiliser le coffre de stockage sur l'un d'entre

**Comment by Killyana** [comment]
Le nombre des mobs varie entre 1 et 4, tu peux vérifier ça dans les vidéos (pour une raison que je vais pas dire)
Ensuite quand j'ai ré-scripté la quête sur TC elle fonctionnait parfaitement, une fois le mob stun il devient inciblable mais tu peux comme même utiliser le coffre qui cible le mob stun le plus prêt de ton perso.

**Comment by potassium8** [comment]
Merci pour la prise en charge

Super, ça marche =)

J'ai du jouer des pieds et des mains ( surtout de la LoS range) mais ca fonctionne.

Je n'ai pas précisé dans le précédent post que je tentais de sortir de la zone d'aggro du pack de mob pour en garder un seul, ce qui amenait ce dernier à bug inéluctablement

**Problème résolu : issue closed**
