### ISSUE TITLE
Sceau d'autorité

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#805]
Bonjour
Le sceau d'autorité ne proc pas sur la petite abomination en bouteille.
Ce bug est due au fonctionnement du sceau d'autorité sur ce serveur puisque le sceau comprends un cd interne court...
De plus il proc après que des dégas aient étés infligés aulieu d'être activé par le "swing" ou l'activation d'une technique physique (normalement même si on rate, on est esquivé ou paré... le sceau d'autorité doit taper avant. De même si on tue la cible avec le coup blanc, le sceau doit avoir tapé en premier normalement, c'est le fonctionnement normal)
Voir le sujet 591 pour les détails je n'ai plus eu de réponse dessus... Depuis j'ai eu une petite abo et j'ai bien constaté ce dont je parlais à l'époque : 
[github.com/way-of-elendil/3.3.5/issues/591](url)
Comment résoudre => revoir le fonctionnement du sceau
OU retarder de 0,1s les degas de la petite abomination (ça sera fonctionnel au moins)

**Comment by joshwhedon** [comment]
Va falloir me prouver que le sceau est suppose proc meme sur les rates / esquives / etc. Si pas de source, je corrigerai pas.

**Comment by ronlii** [comment]
Ce bug là n'est embêtant que si on n'est pas cap toucher/expertise mais n'a pas une si grande influence en pve hl contrairement au fait que la petite abomination en bouteille ne fasse pas proc un double sceau d'autorité (hit du perso + proc petite abo).
Je veux bien chercher mais c'est quelque chose de très compliqué à trouver...

**Comment by joshwhedon** [comment]
Bah c'est surtout que ca change tout le concept .... Et non, je ne peux pas debug l'abomination. Il y a un cd interne au sceau d'autorite, qui empeche le seau de proc plusieurs fois en succession rapide. C'est le comportement normal pour TOUS les procs, pas uniquement le sceau d'autorite. Donc il va vraiment falloir me prouver que c'est pas le comportement attendu pour que je le modifie, sinon j'y toucherai pas.

**Comment by joshwhedon** [comment]
Pas suffisament d'information fournies. Merci de fournir des preuves du fonctionnement officiel du sceau (proc sur parade / esquives / etc)
