### ISSUE TITLE
[Mécanique du "combat invisible"] Ne devrait pas profiter aux familiers temporaires 

### ISSUE THREAD

**Issue by jackydit** [way-of-elendil/3.3.5#807]
Je précise de suite que j'ai galéré à trouver des sources qui en parle et si jamais des personnes ont des sources à ajouter n'hésitez pas. (et trouver des vidéos qui montre la mécanique c'est la galère)

**Petit point sur la mécanique du "combat invisible" :**
Déjà évoquée ici https://github.com/way-of-elendil/3.3.5/issues/775#issue-620313893
Quand une classe à pet (Hunter / Lock / dk unholy) envoi son pet vers une cible ennemie, une sorte de combat invisible profite au maitre du familier, mécanique qui le protège du sap des rogue (même si le joueur maitre du familier est hors combat). J'utilise le terme combat invisible car il ne s'agit pas d'un état de combat et par conséquent une personne lançant un sort de buff sur le maitre du familier, ne profitera ni d'un statut de combat ni de la même protection au sap. 

**Description :**
La mécanique est implantée sur le serveur et est fonctionnelle. Cependant sur Elendyl, elle concerne également les mages avec leur élémentaire d'eau, ce qui ne devrait pas être le cas. Je n'ai pas test, mais du coup la mécanique doit certainement à tort, aussi profiter aux sham amélio ainsi qu'aux druides équi.

**Étapes de reproduction :** 
Il suffit de prendre un mage d'envoyer à l'attaque l'élémentaire d'eau vers une cible et sans être en combat, vous ne pourrez pas être sap.

**Comportement attendu :** 
La mécanique du "combat invisible" ne doit pas profiter aux mages (si ils n'ont pas la glyphe qui rend le pet permanent), ni aux boomie et ni aux shamélio.
Elle doit donc concerner uniquement Hunt / Lock / Dk (spé impie) / Mage frost (si ils ont la glyphe qui rend le pet permanent)

**Sources :** 
https://github.com/TrinityCore/TrinityCore/pull/12084
Il dit que la mécanique concerne : "Only pets summoned through SPELL_EFFECT_SUMMON_PET"
(le même mec a qui donne l'info avait également fait un report sur le fait que le statut de combat de pet ne lie pas le maitre de ce dernier https://github.com/TrinityCore/TrinityCore/pull/12083)

En partant de cette info, seul le lock et le hunt sont concernés par la mécanique:

![hunt](https://user-images.githubusercontent.com/65913348/83020153-61e8bc80-a028-11ea-8601-8028227d6c54.png)

![lock](https://user-images.githubusercontent.com/65913348/83020234-7af16d80-a028-11ea-97eb-016ba7ac53f2.png)

Alors que les sorts de classes à pet temporaire n'ont pas le même effet dans la database:

![dk](https://user-images.githubusercontent.com/65913348/83020341-a2483a80-a028-11ea-971f-c08de5976686.png)
![equi](https://user-images.githubusercontent.com/65913348/83020352-a5dbc180-a028-11ea-9c6e-878e1045acf7.png)
![mage](https://user-images.githubusercontent.com/65913348/83020361-a83e1b80-a028-11ea-9bf4-99ae8c6ee309.png)

**Cependant, la mécanique s'applique également aux DK impie**, qui grâce à leur point de talent ont un pet permanent (la goule) : [LIEN](https://www.warcraftmovies.com/movieview.php?id=137567&__cf_chl_jschl_tk__=7546be6fb09ba3e736f16aa26decbf404f5ac196-1590583689-0-AYvH5A_iQp05f2j9vy_tc5OWwysgC_YpMEpsJF6oLv1P7X0KdwbPn_HdxyLJFvZCs8xdfS-r97uvprTiABj7wb6_aJ4lhd3tnc4tsPCp0cTkFz8yIfVa6FeX-V2lq4vdzs5u43VQxynE92xwgwnJCAr730z-Ftio6lMlgtY0U2oPEaT5Ferx9fOxABkMKZTSRcONDhyjVaXqYrljrwn1VNpVuHjxc9rDRdWGTFOL2h-fWK3CXmgHYMDwLnI3qn5ccXJzjVfSEpEnVOUNIhCmMBAAsOshsSEo9agK5hUb06_CkXup5cRyqdYHHqLq849W7g) à 26:38 le mec parle de la mécanique pour dk impie.

J'ai pas trouvé de source mais par déduction la mécanique doit également s'appliquer à un mage qui utilise la glyphe de l'élémentaire d'eau (rend le pet permanent). Mais ça n'a limite pas d’intérêt dans un contexte de pvp car elle prive le pet du sort gel.

**Comment by jackydit** [comment]
Edit j'imagine que pour la gargouille de dk, la mécanique ne s'applique pas non plus.

**Comment by joshwhedon** [comment]
Va me falloir des preuves pour chaque type de pet, parce que l'elementaire d'eau est un pet (ca dit meme Josh's pet quand tu l'invoque), pareil pour les treants, pareil pour la goule invoquee avec le talent, etc. Le mec de trinity dit de la merde, ca a rien a voir avec le type d'invocation. Donc a moins de me trouver des preuves exactes, le comportement actuel sera considere comme correct.

**Comment by joshwhedon** [comment]
LA gargouille dk n'est pas un pet (elle n'est pas controllable). Est considere un pet tous les compagnons controllables.

**Comment by joshwhedon** [comment]
Du coup il semble normal que cette logique s'applique a tous les pets controllables. Si tu peux controller ton pet et l'envoyer au combat, il est normal que tu sois mis dans ce mode de combat invisible. Si c'est un pet non controllable par contre, il est normal que tu ne sois pas mis en combat (vu que tu n'as pas forcement ordonne au pet d'aller en combat). Merci de demander une reouverture si des informations supplementaires sont trouvees, mais la dans l'immediat c'est le comportement logique pour cette mecanique.
J'ai teste tous les pets qui ont une barre, ca le fait pour tous a premiere vue.
