### ISSUE TITLE
Mort et décomposition du dk sur bête de saurcroc

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#809]
**Description**
La mort et décomposition n'est pas affecté par le 90% de reduc des bêtes

**Étapes de reproduction**
Faites un saurcroc avec un dk (impie testé) et posez une mort et decompo juste avant/pendant les bêtes

**Ressources additionnelles**
https://fr.wowhead.com/npc=38508/b%C3%AAte-de-sang#abilities:mode=h25
https://wowwiki.fandom.com/wiki/Death_and_Decay_(death_knight_ability)

**Comment by Mugiino** [comment]
J'allais le report :( Fune trop fort

**Comment by joshwhedon** [comment]
Honnetement, je sais pas si c'est suppose etre affecte. Mort et decomposition n'est techniquement pas une aoe (contrairement a consecration), et de ce fait n'est pas traite comme tel. J'ai vu plusieurs discussion parlant d'un comportement different des autres AOEs pour mort et decomposition. Vous avez des donnee par chance qui demontrent que c'est suppose etre affecte ?

**Comment by Mugiino** [comment]
Je trouve pas grand chose, à part https://www.youtube.com/watch?v=VSs17aqQpA0 qui montre un unholy en 2009 qui l'utilisait pas.. mais ça ne veut pas dire que ça marche pas.

**Comment by joshwhedon** [comment]
Oui ca peut juste etre un mauvais unholy :D . Et meme si ca marchait pas ca genererai quand meme beaucoup d'agro non donc ce serait malgre tout utile ?
Soit dit en passant, la question se pose aussi sur les pets en general, qui eux aussi ont de la reduction de degats d'aoe.

**Comment by Justforsoloq** [comment]
Aucun dk n'utilise DnD sur saurcroc (les logs method/autres guildes) : http://www.worldoflogs.com/reports/r990jgnfr802ixrw/details/14/?s=2160&e=2327
En plus de : https://wowwiki.fandom.com/wiki/Death_and_Decay_(death_knight_ability)
Death and Decay is a targetable AoE Death knight ability learned at level 60.

**Comment by joshwhedon** [comment]
Merci.
