### ISSUE TITLE
Spell: Chahuter

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#810]
**Description**
https://woehead.way-of-elendil.fr/?spell=57468

Fait sauter les mobs qui utilisent ce spell vraiment très haut 
Quand c'est moi qui le cast ça à l'air correct

**Comment by joshwhedon** [comment]
Les calculs de saut sont bases sur la taille du lanceur de sort. Un humanoide sautera comme un joueur, par contre un gros monstre sautera beaucoup plus haut. Dans le cas present le mob saute environ 1,5 fois sa taille. Tu as des infos indiquant que c'est pas correct ?
