### ISSUE TITLE
Rogue peut plus désarmer les pieges des hunts

### ISSUE THREAD

**Issue by ColorLeMonde** [way-of-elendil/3.3.5#812]
En rogue nous ne pouvont plus désarmer les pieges des hunts pvp car sa demande Désarmement 400 soit c'est juste une erreur de traduction et s'est Crochetage soit la competence n'existe pas .

**Comment by joshwhedon** [comment]
J'ai demande un peu sur discord, personne a signaler avoir rencontre ce soucis. J'ai aussi teste de mon cote, avec les talents qui affectent les pieges, aucun soucis.
Je vois que 2 possibilites:
- bug qui n'affecte que ton personnage (fais un ticket en jeu et discute avec un mj)
- soucis d'addon foireux

**Comment by Ischjgt** [comment]
Le soucis est là pour certains joueurs, j'arrive pas à reproduire perso
J'ai trouvé ça sur TC, 
https://github.com/TrinityCore/TrinityCore/issues/24801
