### ISSUE TITLE
Boss: Le roi-liche - aggro hors zone de combat - ICC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#814]
**Description**
36597 - [le roi-liche]
36701 - [Esprit déchaîné] 
37698 - [Horreur titubante] 
36633 - [Sphère de glace] 
37695 - [Drudge Ghoul]

Pas mal de conflits si un joueur n'est pas présent dans le fight mais à l'entrée de l'instance par exemple. À la manière de https://github.com/way-of-elendil/3.3.5/issues/611 , si c'est la seule personne en vie à la fin où s'il génère de l'aggro, ils se dirigent sur lui.

**Comment by joshwhedon** [comment]
Bah ... je vais kill tous les joueurs trop loin au debut du combat, a moins que tu me trouve le comportement normal.
