### ISSUE TITLE
Quête : L'alpha des worgs

### ISSUE THREAD

**Issue by Mortekouye** [way-of-elendil/3.3.5#817]
**Description**
Ulfang vous a demandé de tuer Garwal. Ensuite, retournez voir la Guetteuse Feuillelune à la Porte d’acier et rendez-lui le Déguisement de worg. 

J'ai fait la suite de quête mais Garwal n'apparait pas à l'emplacement prévu même avec le déguisement de loup . 

**Ressources additionnelles**
https://fr.wowhead.com/quest=11326/lalpha-des-worgs

**Comment by joshwhedon** [comment]
Bonjour. Je suis alle verifier, il est actuellement pop aux alentours de https://woehead.way-of-elendil.fr/?npc=24277
Par contre il se balade un peu :).
