### ISSUE TITLE
Spell: Ronces

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#818]
**Description**
Testé à tous les rangs
https://woehead.way-of-elendil.fr/?spell=16836
16839
16840

Les attaques de tréants hébètent à 100% de chance et la partie "attacks done to you while you  have Barkskin active have a 5% chance to daze the target for 3 sec." ne marche pas.

**Comportement attendu**

De plus, les dégâts infligés par vos Tréants et les attaques avec Ecorce activé ont 5/10/15% de chances d'hébéter la cible pendant 3 sec.

La traduction est pas tout à fait exacte, le texte en anglais :

In  addition, damage from your Treants and attacks done to you while you  have Barkskin active have a 5/10/15% chance to daze the target for 3 sec.

**Comment by joshwhedon** [comment]
Pour ecorce ca marche correctement deja. Je corrige le taux pour les trants.
