### ISSUE TITLE
Chaîne d'éclair réduit pas les bêtes de saurcroc

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#819]
**Description**
La chaîne d'éclair est réduite par les bêtes de saurcroc actuellement (tape à 200-400)

**Étapes de reproduction**
Prenez un chaman et faites des chaînes d'éclair sur saurcroc et ses bêtes de sang

**Comportement attendu**
La chaine d'éclair n'est pas réduite par les bêtes de sang (un des seuls sorts d'ailleurs)

**Ressources additionnelles**
http://www.worldoflogs.com/reports/m95i3mcw4ncujkb0/details/161/?s=1657&e=1798
https://wowwiki.fandom.com/wiki/Deathbringer_Saurfang
"[Chain Lightning] does not count as AoE versus Blood Beasts, so an elemental shaman can pull up to four of the beasts with one cast."

**Comment by joshwhedon** [comment]
OK va falloir me trouver des sources pour indiquer si c'est aussi le cas pour les pets en general parce que SPELL_AURA_MOD_CREATURE_AOE_DAMAGE_AVOIDANCE c'est un type d'aura utilisee par tous les pets de joueurs.  Modifier uniquement pour les betes de saurcros me parait pas logique.

**Comment by Justforsoloq** [comment]
Euh j'en ai mis deux de sources...

**Comment by Justforsoloq** [comment]
Genre littéralement les deux sources que j'ai mises indiquent noir sur blanc la mécanique x)

**Comment by Justforsoloq** [comment]
J'ai mal lu ta réponse.
Je comprends pas par rapport au truc des pets, je parle de la chaine d'éclair

**Comment by joshwhedon** [comment]
Oui oui, mais mon soucis c'est est-ce que ca concerne aussi les pets de joueurs. Parce que le probleme c'est que SPELL_AURA_MOD_CREATURE_AOE_DAMAGE_AVOIDANCE est utilise par les pets aussi. Donc est-ce que les betes sont un cas particulier et unique (ca m'etonnerait beaucoup), ou est-ce que les pets aussi sont suppose ne pas avoir de degats reduits pour la chaine.

**Comment by Kwyzard** [comment]
Les bête de saurcroc ont littéralement un buff qui indique donc ça doit être appliquer via le buff pas via ton option dans ta database enfaite

**Comment by joshwhedon** [comment]
Non mais ... c'est pas comme ca que ca marche hein :D .

**Comment by Justforsoloq** [comment]
Le 90% reduc aoe ça concerne que les familiers dans un raid de toute façon non ?

**Comment by joshwhedon** [comment]
Oui, mais des sorts de chaine en tout genre, il y en a un packet d'utilises par des mobs en tout genre.

**Comment by Justforsoloq** [comment]
Si la mécanique des bêtes est la même pour les pets, dans ce cas là bah oui la chaîne bypass aussi sur les pets.
Vu qu'on sait noir sur blanc que la chaine d'éclair est à 100% sur les bêtes.

**Comment by Justforsoloq** [comment]
Et en vrai des sorts de chaines (à la chaine d'éclair) utilisés par des boss de raid j'en vois pas du tout

**Comment by Killyana** [comment]
Jaraxxus utilise un https://www.wowhead.com/spell=66528/fel-lightning qui est similaire à la chaîne d'éclaire

**Comment by Justforsoloq** [comment]
Je cherche mais je trouve 0 familiers qui ont été affecté par fel lightning et pourtant ça a jump sur des demo/hunt etc.
http://www.worldoflogs.com/reports/9uyqy7rsmyhaa5ey/spell/67031/?s=1021&e=1192

**Comment by Justforsoloq** [comment]
Petit up par rapport

**Comment by joshwhedon** [comment]
Oui oui j'ai un correctif de pret, mais je suis occupe avec autre chose.
