### ISSUE TITLE
Stat: Résilience

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#82]
**Description**
La réduction de dégats se fait également lorsque les sorts sont lances par une cible amicale (quand un boss fait qu'un joueur fait des degats a ses alliers).

**Comportement attendu**
"Joueurs et leurs familiers/serviteurs"

**Comment by joshwhedon** [comment]
Bug existant depuis toujours je dirai, on l'a juste jamais remarque :D
