### ISSUE TITLE
[ICC Bug combat] Essence disjointe de chasseur

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#820]
Icc 25n. Combat contre les Héraut val'kyr **sur le pont**.
Les Essence disjointe qui apparaissent en copiant un chasseur font un **désengagement** dans le vide, puis reste à notre hauteur, flottant dans le vide.
On ne peut pas les taper (hors champs de vision), et elles ne font rien non plus. 
Forcément, **bug combat** jusqu'au prochain wipe.

**Comment by Ferro3** [comment]
Le bug combat se produit 9 fois sur 10, d'avance merci
