### ISSUE TITLE
La relique  imprégnée d'éclairs

### ISSUE THREAD

**Issue by Aloawan** [way-of-elendil/3.3.5#822]
Durant cette quête l'assemblage dont on a le contrôle possède un sort permettant d'entourlouper les nains de fer soupçonneux. Ce sort ne fonctionnant pas (ou très rarement) il est impossible de s'en servir durant la quête et on se fait attaquer à tous les coups. 
J'avais déjà réalisé cette quête sous l'ancien merge et je n'avais pas rencontré de problème à ce niveau là, le sort fonctionnant parfaitement bien.

**Comment by joshwhedon** [comment]
J'ai eu aucun soucis personnellement donc je comprends pas. C'est sur des nains de fer particuliers qu'il marche pas le sort ?

**Comment by Ischjgt** [comment]
La quête est faisable, mais quand un Iron Rune Steelguard 23673 repère le joueur, appuyer sur le spell 3 ne le calme pas, le golem ne dit rien et rester pres du nain finit par faire sauter la couverture

https://www.youtube.com/watch?v=f0YdUnxwaJ8
~ 1min 30 le joueur est attaqué, le NPC est toujours amical et dit une phrase
Il utilise ensuite le spell 3 et le golem qui sert de déguisement dit une phrase à son tour
Enfin, le nain s'excuse

Je suis pas sur que Iron Rune Golem 24271 puisse repérer le joueur

**Comment by joshwhedon** [comment]
OK par contre les autres marchent du coup. C'est surement juste un des npcs qui est pas gere.

**Comment by Killyana** [comment]
C'est probablement tout les npcs, vue qu'ils utilisent tous 2 actions list avec la 2eme qui doit interrompre la 1ere, quand j'ai script ça c'était possible d'avoir 2 action list qui s'exécutent en même temps, mais plus maintenant, même dans le cas ou on ajoute le flag aux action list pour l'interruption, le npc bluffé restera root vu que unroot ne sera jamais exécuté

**Comment by Ischjgt** [comment]
Je réouvre le ticket, c'est toujours quasiment impossible d'attendre la grotte sans que les nains deviennent hostiles.
Les nains n'ont même pas fait de dialogues pour prévenir qu'ils se méfiaient afin d'utiliser ce sort
44562 - [Entourlouper, rank 1 frFR]
44562 - [Entourlouper, rank 1 frFR]

**Comment by joshwhedon** [comment]
Les dialogues marchent j'ai reteste a nouveau.

**Comment by Ischjgt** [comment]
Les dialogues marchent mais 
1. je pense que les nains détectent le golem de beaucoup trop loin, tellement loin qu'on ne les voit pas parler et ils passent donc ensuite hostiles
2. On a 0 seconde pour réagir suite au dialogue et utiliser le spell pour calmer les nains

Sur la vidéo que j'ai link plus haut https://www.youtube.com/watch?v=f0YdUnxwaJ8 :
1:27 => le nain suit le golem tout en restant amical 
1:28/29 => Il fait son dialogue
1:31 => Le joueur utilise le spell

(il y a donc au moins 4 secondes pour réagir, à compter du déplacement du nain, pas du dialogue)

**Comment by Lokkaz123** [comment]
J'ai fais un test : J'ai couru et j'ai spam le sort "Entourlouper" du début à la fin.

1) Il ne fonctionnait pas tout le temps lorsque le CD était up mais se lançait régulièrement vers des nains ou des golems lors de mon avancé.

2) Je suis arrivé au fond de la grotte sans avoir de nains/golems hostile.

3) L'évent s'est bien lancé mais à la fin de celui-ci la quête n'a pas été validé. (Les nains et golems étaient toujours amicaux)

**Comment by Ischjgt** [comment]
Navré, le problème est toujours là pour mon premier point, il y a un moment, à force de se balader, tout le monde devient hostile, sans qu'il y ait eu de message, j'ai quelques vidéos si tu veux.

Ça à l'air de se faire plus facilement en sautant ou en utilisant les fusées de saut (le spell 1)

**Comment by joshwhedon** [comment]
Autre correctif prochaine maj. Et honnetement si ca marche toujours pas, faudra faire avec.
