### ISSUE TITLE
Ingénierie: enchant cape incomplet

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#823]
L'amélioration d'objet ingé Doublure en toile flexible (https://woehead.way-of-elendil.fr/?enchantment=3605) est supposé apporter un +23 en agilité en + de la possibilité de ralentir les chutes, mais il ne le donne pas.

**Comment by Ischjgt** [comment]
Elle apporte 23 agilité chez moi. Il faut être Ingénieur pour pouvoir bénéficier des bonus.

**Comment by Rolirolant** [comment]
bah pas chez moi

**Comment by Kwyzard** [comment]
regarde tes stats, c'est pas "afficher" sur la cape

**Comment by Rolirolant** [comment]
l'agi est la seule stat encore écrite en blanc, sans aucun modificateurs

**Comment by Ischjgt** [comment]
Tu peux me MP sur Discord stp

**Comment by Rolirolant** [comment]
Ok en effet en enlevant la cape on voit la diff de stats, mais la stat ne devrait-elle pas apparaître en vert avec un score modifié alors?

**Comment by Rolirolant** [comment]
En fait il en va de même pour les autres enchantements aussi
