### ISSUE TITLE
Mort et décomposition interaction arene des tranchantes

### ISSUE THREAD

**Issue by Popeyeddd** [way-of-elendil/3.3.5#824]
**Description**
La zone d'aoe posée en bas du pont affecte également le haut.

**Comportement attendu**
Ne devrait pas affecter le haut.

**Captures d’écran / Vidéos**
https://streamable.com/91xi43

**Comment by Justforsoloq** [comment]
ça fait la même avec la consecration/aoe type magma ?

**Comment by Popeyeddd** [comment]
j'sais pas moii

**Comment by Justforsoloq** [comment]
Va tester et reviens enfant du debug

**Comment by Ischjgt** [comment]
Et c'est pas que à cet endroit. En fait ça fait ça pour pas mal d'endroits sur plusieurs étages.
Ça concerne les maps, du coup pas sur que ton ticket aille bien loin.

(Il me semble que des améliorations sont à prévoir prochainement sur les maps.)

**Comment by Killyana** [comment]
Non, y'aura pas d'amélioration pour les transports de type ascenseurs avant longtemps, ils doivent être considéré comme un transport  à part, ce qui est pas le cas actuellement (juste des gobs)

**Comment by Popeyeddd** [comment]
oki doki

**Comment by Kwyzard** [comment]
"oki doki" tu peux être sûr il a pas compris

**Comment by Popeyeddd** [comment]
C'est pas faux

**Comment by Killyana** [comment]
En d'autre terme quand vous posez une mora sur une des 2 canonnières (qui sont des vrais transports) la zone crée par le sort sera lié à la map de ce transport, donc si le transport bouge la zone bouge avec lui, pour les ascenseurs c'est pas le cas vue que c'est considéré comme étant un "objet statique", donc la zone de mora sera lié à la map de l'arène et non à l’ascenseur vue qu'il a pas de "map".

**Comment by joshwhedon** [comment]
Desole mais ce bug ne sera jamais corrige par nous. La seule possibilite pour qu'il soit corrige c'est que Trinity le corrige. C'est hors de nos competences. Il est connu, il a toujours ete la.

**Comment by Popeyeddd** [comment]
Ça marche np

**Comment by Kwyzard** [comment]
Pourquoi on parle d’ascenseur enfaite ? C'est un bloc fix la sur l'arène des tranchantes, tu veux dire que la map entière est considéré comme un ascenseur ?

**Comment by Popeyeddd** [comment]
"ouai" https://github.com/way-of-elendil/3.3.5/issues/824#issuecomment-637173892 ici stp

**Comment by joshwhedon** [comment]
La map entiere est pas consideree comme un ascenseur, mais l'assenceur lui meme ne fait pas partie de la map, pour le serveur, il n'existe pas, donc si tu place sur l'assenceur, ca foire.

**Comment by joshwhedon** [comment]
D'ailleurs vous verrez le meme probleme avec les aoes qui ciblent a la souris, l'ascenseur est ignore.

**Comment by Popeyeddd** [comment]
bah josh j'sais pas si j'ai rien compris à votre truc
mais y a pas d’ascenseur en fait dans cette arène

**Comment by Popeyeddd** [comment]
c'est un pont le truc

**Comment by Popeyeddd** [comment]
la map avec l'ascenseur c'est arène des valeureux, là sur la vidéo c'est tranchante l'arène

**Comment by joshwhedon** [comment]
Ha oui j'ai confondu. Ouai non c'est un autre probleme (enfin similaire). Les aoes au sol se mette en cercle au sol, partout, et il n'y a pas de logique de hauteur pour elles (c'est un cercle en vue de dessus, quoi qu'il arrive). Du coup, si les joueurs sont sur le cercle, peu importe leur hauteur, ils prennent les degats.
C'est aussi a cause de la gestion des maps. Impossible a corriger pour nous, et je ne sais meme pas quelle est suppose etre le comportement normal pour l'offi.

**Comment by Kwyzard** [comment]
A vrai dire j'attendais cette réponse mais je me demandais en contre exemple
Il me semble que si un death knight met sa Mort et Décomposition en phase 2 du lich king au sol sa mort et décomposition ne touche pas les valkyr qui se positionne au dessus du boss après qu'elles ait été endommager à hauteur de 50 % 

Donc y a bien une "hauteur"

**Comment by joshwhedon** [comment]
il y a pas de sol a ce niveau la, la valkyr vole au dessus du sol. Le probleme n'est pas la hauteur elle meme, c'est la gestion du sol par rapport a la hauteur. Je sais pas comment expliquer :D .

**Comment by Kwyzard** [comment]
han ouai pas compris
