### ISSUE TITLE
Bug sur Dame Vashj - Raid BC - CSS

### ISSUE THREAD

**Issue by Akuponkture** [way-of-elendil/3.3.5#825]
**Description**
Lors du combat final contre Dame Vashj, il suffit de mettre une granule dans l'un des vases et Dame Vashj n'est plus insensible et on peut la tuer.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Raid: Caverne du Sanctuaire du Serpent
- Boss: Dame Vashj
- Phase du boss en question: P2
- Composition du groupe

**Comportement attendu**
Normalement il faut mettre une granule dans les 4 vases pour que la Dame ne soit plus link avec le rayon et redevienne "tappable".

**Comment by joshwhedon** [comment]
J'ai essaye de reproduire sans succes. Un truc special est arrive ? Vous avez wipe a un moment ? etc ?

**Comment by joshwhedon** [comment]
Des nouvelles ?

**Comment by joshwhedon** [comment]
Impossible de reproduire ce probleme. Merci de fournir plus d'information / reouvrir le bug quand il est possible de le reproduire.
