### ISSUE TITLE
NPC: Nat Pagle

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#826]
**Description**

12919 - [Nat Pagle] 
Icone de la bourse pour ce NPC même si la quête 8227 n'a pas été rendue, le NPC ne propose rien en vente, c'est juste visuel

<img width="550" alt="Capture d’écran 2020-06-01 à 20 50 30" src="https://user-images.githubusercontent.com/60295792/83443661-66f3a480-a44a-11ea-9229-2849ea8b56a5.png">

**Comment by joshwhedon** [comment]
Je ne crois pas que ce soit un bug. Il est un vendeur et il a quelque chose a vendre, juste pas pour toi. Je ne pense pas que les flags de ce genre soient suppose etre affiche uniquement si le joueur peut acheter.
