### ISSUE TITLE
Spell: Enflammer

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#827]
**Description**
11119
11120
12846
12847
12848

Un proc du talent met le mage et le(s) joueur(s) qui ont reçu le débuff en combat

**Comportement attendu**

    Actions that will get you into combat

    Casting an offensive Spell
    Casting a Buff or Healing spell on a unit that is in combat
    Getting on a mob's Aggro list
    Certain bosses always put everyone in the group (or raid) in combat when engaged, regardless their distance from the boss 

https://wowwiki.fandom.com/wiki/Combat

À vérifier, j'ai pas plus d'infos

**Comment by joshwhedon** [comment]
C'est pas un bug, c'est un sort offensif, comme d'autres debuffs. Par contre je sais pas trop comment ce sort pourrait mettre en combat sans deja etre en combat avant. Vu que ce sort proc sur un coup critique, donc la cible aura ete mise en combat par le sort qui l'aura proc de toute facon.

**Comment by Ischjgt** [comment]
Le sort met en combat sur un tick de bombe vivante critique
https://woehead.way-of-elendil.fr/?item=45737

**Comment by Justforsoloq** [comment]
En gros tu poses la bombe vivante, tu attends 5s tu sors de combat et là paf tu as un tick crit qui pose l'enflammer et ça te remet en combat (toi et la personne qui a la bombe posée)

**Comment by gtschanz** [comment]
normalement ça ne devrait pas le faire car si on compare à d'autres classe qui dot et ensuite ou il ne se passe plus rien pendant 5 sec ça les remet pas en combat (exemple sp / demo)

**Comment by Kwyzard** [comment]
Pareil pour le bouclier du disco qui redonne de l’énergie (puissance runique, rage, mana ...) on se pose des questions si c'est normal ou pas parce que même sous control si son mate a un bouclier le priest rentre en combat si on fait exploser le shield (et ça parait très très fort en pvp)

**Comment by gtschanz** [comment]
peut-on avoir une idée de l'avancement de ce sujet ? (car ça rend le mage feu plus ''dur'' à play car qui dit bug combat = empêchement de mount et donc de fuir (idem pour regen avec des struddel -> donc gros désavantage

**Comment by Ischjgt** [comment]
Il n'y aura pas d'avancement sans preuve, j'en ai pas trouvé perso :p
