### ISSUE TITLE
Spell: Demonic Aegis persists after talent swap

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#828]
**Description**
https://github.com/TrinityCore/TrinityCore/issues/24733
https://woehead.way-of-elendil.fr/?spell=30145

Persiste après un changement de talent.
Testé au rang 3 pour Fel armor rang 4

refresh le buff/déco reco met à jour l'armure du démoniste

**Comment by joshwhedon** [comment]
Impossible de trouver le comportement normal. Le plus simple est de retirer le buff quand le talent est retire.

**Comment by Ischjgt** [comment]
https://woehead.way-of-elendil.fr/?item=42751
Pour le cas du glyphe de l'armure de la fournaise par exemple, si on enlève le glyphe/change de spé, le changement est immédiatement calculé 

> Le plus simple est de retirer le buff quand le talent est retiré.

Je vois pas pourquoi ce serait fait si ça avantage le joueur :p, de la même manière on en parlerait dans les guides

**Comment by joshwhedon** [comment]
Non mais je veux dire que le plus simple c'est que  quand le talent est retire je retire le buff.
