### ISSUE TITLE
Aura bâton transmogriffié inactive

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#832]
Bonsoir.

Je viens de transmogriffier mon bâton avec [Bâton de l'infusion divine]
https://woehead.way-of-elendil.fr/?item=31289
et l'aura d'enchantement +81 spell  [Ench. de bâton (Puissance des sorts supérieure)] n'apparait pas :(
https://woehead.way-of-elendil.fr/?spell=62948
Le bâton cible est  [Archus, grand bâton d'Antonidas]
https://woehead.way-of-elendil.fr/?item=50429

Est-ce normale, est-ce fixable ?

**Comment by Endalaust** [comment]
C'est lié à l'objet transmogrifié, s'il est pas prévu qu'il affiche un visuel d'enchantement, il n'y aura aucun visuel. 

Impossible de faire quoi que ce soit, il s'agit de données côté client et non côté serveur.
