### ISSUE TITLE
Boss: Mort d'Al'ar - Donjon de la tempête 

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#833]
**Description**

Name: Al'ar
Entry: 19514.
35181 - [Bombardement en piqué, rank 1 frFR]
35367 - [Bombardement en piqué, rank 1 frFR]

Lorsque le boss est tué quand il s'envole en P2 pour utiliser Bombardement en piqué, il ne peut pas être loot. Le joueur voit le cadavre au sol mais il est en l'air.

-

Je crois que tu connais mais je le poste vu qu'il y a eu des corrections sur certains NPCs qui mourraient dans les airs

**Comment by Killyana** [comment]
Aussi il garde le flag non séléctable une fois mort

**Comment by Ischjgt** [comment]
Une fois tué, le cadavre du boss s'envole comme s'il allait utiliser Bombardement en piqué
