### ISSUE TITLE
Spell: Feindre la mort et familiers

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#834]
**Description**
id: 5384 [Feindre la mort] 
Les familiers sont insensibles au spell.

Le joueur doit pouvoir quitter le combat en dehors des instances. 

> passing mobs will act as if the hunter is dead. 
> minions/pets will stop attacking.
https://wowwiki.fandom.com/wiki/Feign_Death

**Comment by joshwhedon** [comment]
Familiers de qui ? Parce que la c'est les familiers du chasseur qui vont arreter d'attaquer. Les familiers d'un joueur enemi vont continuer a attaquer.

**Comment by joshwhedon** [comment]
OK compris.
