### ISSUE TITLE
NPC: Vendeur de l'arène et stuff S4

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#836]
**Description**

https://woehead.way-of-elendil.fr/?npc=26383 Ne vend que les gantelets S4 pour les wars, alors qu'il vend toutes les autres pièces du set pour les autres classes
https://woehead.way-of-elendil.fr/?npc=20278 Pas spawn, je ne sais pas si c'est normal

Aussi, je ne sais pas ce qu'il doit en être pour tous les NPCs sans point de spawn
https://woehead.way-of-elendil.fr/?item=35067#sold-by-npc
Il y en a 1 ou 2 qui sont là mais qui vendent de l'impla par exemple

**Comment by joshwhedon** [comment]
C'est quoi les gantelets S4 :D

**Comment by Ischjgt** [comment]
https://woehead.way-of-elendil.fr/?item=35067#sold-by-npc et tout le stuff ici https://woehead.way-of-elendil.fr/?npc=26383
https://woehead.way-of-elendil.fr/?npc=28225, sur ce NPC ils y sont mais je sais pas pourquoi y'a pas tout sur le Woehead
