### ISSUE TITLE
Quest: Le gambit de Tirion

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#838]
**Description**
https://woehead.way-of-elendil.fr/?quest=13364
https://woehead.way-of-elendil.fr/?quest=13403 

- The Lich King 32184 apparait hostile on peut l'attaquer durant tout l'event
- quand les Zélote élu 32175 se lèvent pour se diriger vers le LK etc pendant l'event, ils se mettent à suivre le joueur pour la vie <3 (si le portail n'est pas pris du moins)
- Thassarian 32310 et Ebon Knight 32309, ils sortent du combat et reviennent à leur position quand un Zélote élu meurt

**Comment by joshwhedon** [comment]
Y'a des trucs que je peux pas regler parce que c'est des smart scripts et si je les change ca va tout peter a la prochaine modif de TC. Mais je fais quelques ameliorations.
