### ISSUE TITLE
File d'attente donjon qui ne se lance pas

### ISSUE THREAD

**Issue by Kaskaskaskas** [way-of-elendil/3.3.5#839]
**Description**
La file d'attente donjon reste à temps <1min et le type (dps) ne se colore pas.

**Étapes de reproduction**
J'avais fait l'épuration de stratholme précédemment et il y a eu un bug et je crois que la file d'attente a été refresh ou quelque chose comme ça, depuis ça bug.

**Comment by joshwhedon** [comment]
Il va falloir que vous voyez avec les joueurs / l'equipe en jeu. Il est tres probable qu'il ne s'agisse pas d'un bug. Il est aussi probable que ce soit arrive au moment ou le mode interfaction a ete desactive. Lorsque ca arrive il faut rejoindre la queue a nouveau.
