### ISSUE TITLE
bug guide de givre sur syndra

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#841]
raid: ICC
Classe: mage
sort: Ice block

vous prenez un mage; vous devez être target par le guide de givre (spell du boss) p1 ou p2 vous utilisez ice block avant l'impact qui doit vous glaconner; à la fin du timer (temps dans le ice block du mage) le guide de givre s'applique; le seul problème c'est que toute les personnes qui se sont pack à côté de la personne sont glaconnés alors avec. Est-ce blizz ? qu'un spell du boss peut être ''temporiser'' de la manière et que ça impacts les autres autours ? (ça a presque causé un wype hier en 25n en p1..

**Comment by joshwhedon** [comment]
Bah il a pas "temporise" du tout en fait. Quoi qu'il arrive, 7 secondes apres que le joueur soit cible par le guide, le gel a lieu. En gros vous avez essaye de gruger, et vous vous etes fait chopper :D .

**Comment by gtschanz** [comment]
nan c'est un player qui a voulu gruger et qui a quasi enculé le raid; et vu que je trouve ce comportement pas totalement blizz je l'ai report

**Comment by joshwhedon** [comment]
Honnetement j'ai aucune idee. Le bug du coup c'est visuel uniquement non ? Le missile vole pas vers la cible, mais touche quand meme au final ?

**Comment by gtschanz** [comment]
il touche certes mais à la fin du timer de l'ice bloc et non à la fin du timer comme indiqué normalement par le débuff

**Comment by joshwhedon** [comment]
J'ai teste plusieurs fois et ca  s'est mis au moment d e la fin du timer, pas au moment de la fin de l'iceblock. J'arrive pas a reproduire votre soucis.
