### ISSUE TITLE
spot de minage bug sous map

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#842]
-> activer la compétence ''découverte de gisements'' (compétence de minage) dans la petite salle / grotte sous icc on voit qu'il y a des spot de minerai mais ils sont ''sous-map'' impossible à farm donc à enlever; le seul soucis c'est qu'ils entre en compte dans le calcul des 40 spot par région pour le farm et qu'ils sont inaccessible ; est-ce blizz ? (je parle de 4 à 7 spot quand même ce qui fausse le farm minage dans la couronne)

**Comment by joshwhedon** [comment]
Faut donner les spots exactes pour qu'ils soient corriges.

**Comment by gtschanz** [comment]
pour indiquer les coordonnées précise

**Comment by Kwyzard** [comment]
https://www.curseforge.com/wow/addons/map-coords/files/399055 devrait faire l'affaire, sinon a l'ancienne screenshot

**Comment by Ischjgt** [comment]
Mp moi sinon

**Comment by gtschanz** [comment]
c'est bon j'ai trouvé la raison il y avait une caverne dont je ne connaissais pas l'existence (en cherchant sur le net)

**Comment by joshwhedon** [comment]
Cool merci de l'update
