### ISSUE TITLE
Spell: Divine Shield

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#843]
**Description**
32375 - [Dissipation de masse, rank 1 frFR] 
642 - [Bouclier divin, rank 1 frFR] 

Le bouclier n'est pas dissipé en priorité par Dissipation de masse. Si le joueur a beaucoup de buff, La dissipation de masse va prendre un buff au hasard, le joueur y insensible et la bulle va rester 

**Comportement attendu**
Ça fonctionne correctement pour l'Iceblock

https://wowwiki.fandom.com/wiki/Patch_2.0.10
Mass Dispel will now target immunity effects first.

**Comment by Ischjgt** [comment]
https://woehead.way-of-elendil.fr/?spell=53553

**Comment by Kwyzard** [comment]
Patch 2.2.0 (2007-09-25): Has a chance to be resisted when dispelling immunity effects. This will be displayed in the combat log. In addition, it will no longer cause rogues and druids in Cat Form to lose Stealth http://www.wowwiki.com/Mass_Dispel

**Comment by joshwhedon** [comment]
Ouai et ca marche correctement.  On a reteste. Ce qu'on suppose c'est que parfois le dispel est resiste (genre par le talent de purification sacree)

**Comment by Kwyzard** [comment]
y a normalement le cap hit aussi, la péné je crois pas

**Comment by Justforsoloq** [comment]
C'est juste que des fois le MD ne dispell pas le bouclier divin (sur AT il m'arrivait de faire 5-7 MD et de ne pas réussir à dispell le divine shield :x, et des fois tu fais un MD et ça part direct). Rng :x
