### ISSUE TITLE
Spell: Jugement avec Sceau d'autorité 

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#845]
**Description**
Les multiplicateurs de dégats liés au dégats des armes sont comptés 2 fois pour le sceau d'autorité

Je crois que les Bonus à la pa qui affectent les dégats des armes sont également comptés 2 fois

**Étapes de reproduction**
Jugement avec sceau d'aurorité sans et avec  https://woehead.way-of-elendil.fr/?spell=20113
-> Le 6% est compté 2 fois sur le jugement avec sceau d'autorité

20375 - [Sceau d'autorité, rank 1 frFR] [talent] [known] [active]

**Comment by joshwhedon** [comment]
T'es sur que tu as pris en compte le bonus de sp ? Parce que le judgement d'autorite a un composant SP et un composant AP.

**Comment by Ischjgt** [comment]
Pas réveillé

**Comment by Justforsoloq** [comment]
Après je n'ai pas bien suivi vos calculs mais par rapport aux % justement la plupart des spells ne doivent pas "double dip" (me semble que le sceau d'autorité ne doit pas justement piocher deux fois dans les % multiplicateurs sp et ap). Mais jsuis en raid donc pas le temps de bien regarder
