### ISSUE TITLE
[Combat] Statut de combat du pet bug avec un dot

### ISSUE THREAD

**Issue by jackydit** [way-of-elendil/3.3.5#846]
**Description**
Quand un joueur lance un sort qui pose un dot sur un pet, le pet et le joueur lanceur de sort restent en combat jusqu'à l'expiration du debuff et restent en combat facile 5 sec après l'expiration du debuff.

**Étapes de reproduction**
Lancez un sort à dot sur un pet, vous resterz avec lui en combat pendant une éternité.

**Comportement attendu**
5/6 sec après la pose du dot, le pet et le lanceur de sort sortent du statut de combat

Ce bug n'existait pas il y a encore 2 semaines j'crois et autre chose lié au pet, la mécanique qui rend insapable le hunter qui envoi attaquer son pet, n'est plus active sur le serveur normal ?

**Comment by jackydit** [comment]
Testé sur hunt uniquement

**Comment by Justforsoloq** [comment]
En vrai faudrait faire un dossier entier consacré aux bugs combats x)
