### ISSUE TITLE
Faucheur d'âme

### ISSUE THREAD

**Issue by ltbastion** [way-of-elendil/3.3.5#847]
**Description**
Les dégâts de la compétence faucheur-d'âme du LK sont instantanés.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Raid ICC
- 25h et potentiellement les autres modes
- Roi liche
- Faucheur-d'âme

**Comportement attendu**
Le faucheur d'âme est posé sur un tank, puis après 5sec le tank subis 70 000 de dégâts d'ombre.

Actuellement le tank prends les dégâts d'ombre instantanément. Si le lk mets une attaque dans le même temps, le tank peu prendre plus de 100k de dégâts.

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**

wowwiki (https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)) 

    Ability rogue shadowdance  [Soul Reaper]ω ϖ ω ϖ Melee range—Strikes the target for 50% weapon damage and afflicts the target with Soul Reaper. This effect deals 50,000 Shadow damage after 5 sec and increases the caster's haste by 100% for 5 sec. Instant. Used on the tank. 60,000 on 25-player and 10-player heroic, 70,000 on 25-player heroic.

**Comment by joshwhedon** [comment]
Pas un bug, il y a 2 composants dans ce sort, d'abord une attaque de melee, et 5 secondes plus tard le tick. J'ai teste et le tick se fait bien apres 5 secondes.

**Comment by Ischjgt** [comment]
CF MP Discord

**Comment by joshwhedon** [comment]
Le probleme est que l'attaque de melee ignore l'armure et utilise la resistance.

**Comment by Theralion** [comment]
Hello, 

Je me permet de remonter un point sur le faucheur d'âme, concernant l'augmentation de la hâte durant le faucheur d'âme, que j'avais déjà signalé en edit dans le ticket https://github.com/way-of-elendil/3.3.5/issues/866

Je n'ai pas l'impression, et ce encore hier soir après la merge, que la hâte du LK soit augmentée durant le faucheur d'âme, les logs de mon recount ne remonte pas assez loin dans le fight pour avoir des infos précises, mais les coups reçus par notre MT semblent constant avant et pendant le faucheur, alors qu'il devrait en prendre 2 fois plus durant le faucheur.

https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)
Melee range—Strikes the target for 50% weapon damage and afflicts the target with Soul Reaper. This effect deals 50,000 Shadow damage after 5 sec and increases the caster's haste by 100% for 5 sec. Instant. Used on the tank. 60,000 on 25-player and 10-player heroic, 70,000 on 25-player heroic. –

Si quelqu'un (MJ ou joueur) à la possibilité de tester/avoir des logs des frappes du LK durant le faucheur avec les timestamps pour vérifier s'il y a bien cette augmentation de hate, je suis preneur :)

**Comment by Theralion** [comment]
à priori notre MT de ce soir à bien vu la hate augmentée lors de nos try de ce soir, donc mon impression d'hier était fausse
