### ISSUE TITLE
[Champs de bataille] Tableau d'affichage illisible du fait de l'interfaction

### ISSUE THREAD

**Issue by Popeyeddd** [way-of-elendil/3.3.5#849]
**Description**
En battleground, le tableau d'affichage fait une distinction entre l'équipe horde et l'équipe alliance, en un coup d'oeil on sait qui est avec qui ect
Sauf que du fait de l'interfaction certains joueurs d'une faction jouent dans l'équipe de la faction adverse et le tableau d'affichage n'en tient pas compte

**Étapes de reproduction**
Il suffit de queue bg et vous réalisez vite que le tableau d'affichage est illisible

**Comportement attendu**
Ofc l'interfaction n'est pas retail, mais j'imagine que le comportement attendu serait d'afficher les joueurs dans l'équipe de la faction dans laquelle ils ont rejoint le bg et pas en fonction de leur faction d'origine. 

**Captures d’écran / Vidéos**
![Sans titre](https://user-images.githubusercontent.com/65403286/84035542-3658c100-a99c-11ea-88d0-c38c301feedb.png)
Là par exemple c'est du 6 contre 7 contrairement à l'affichage et à titre d'exemple je suis avec l'équipe horde, donc qui est avec qui idk

**Comment by Popeyeddd** [comment]
J'sais pas si c'est facilement réalisable, mais si ça peut aider sur pas mal de serv qui ont l'interfaction, les joueurs qui proc dans la faction adverse subissent une sorte de changement de race visuel, alors j'sais pas si c'est juste du cosmétique ou si c'est nécessaire pour script le truc

**Comment by joshwhedon** [comment]
On yp eut rien malheureusement. L'interfaction pvp est un hack, et n'est pas blizzlike,. Du coup il y a des limitation.
