### ISSUE TITLE
Bugs du joug d'hiver

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#850]
**Description**
Bugs dans le joug :
-Les mobs ne dépop pas pendant le joug (les élémentaires) alors qu'ils ne devraient pas être présents pendant l'event pvp.
-Si on accepte l'invitation de joug depuis une autre carte (avec téléportation) on ne peut pas obtenir de grade, alors que ça devrait être le cas, bien entendu.
-Si on accepte l'invitation de joug depuis la carte du joug on n'est pas téléportés à l'entrée du joug ; on reste là ou on est ce qui avantage les personnes déja surplace à l'endroit ou on "grade". On est sensé etre téléporté en défense si on est en défence ou en attaque si on est en attaque quelque soit la carte ou on se trouve en acceptant (la tp fonctionne en dehors de la carte du joug mais le grade bug comme dit précédemment).
-Si on ne détruit pas le mur de face de l'arceau final, impossible de détruire la porte qui reste invincible. (information à vérifier coté script car en tant que joueur c'est compliqué de tester toutes les possibilités puisque personne ne passe par le coté.

![image](https://user-images.githubusercontent.com/57768200/84049325-95becd00-a9ac-11ea-942d-fd9798656cd0.png)

**Comment by joshwhedon** [comment]
Tu peux prouver ce que tu avance pour le point 1 et 3 ?

**Comment by ronlii** [comment]
Il n'y a qu'ici ou les élémentaires sont présent pendant le pvp ; il y a un patch pour ça regardez : 
https://worldofwarcraft.judgehype.com/patch3-0-8/
"Les élémentaires devraient maintenant toujours disparaître quand la bataille commence."

Pour le 3em point il ne semble pas y avoir de trace dans les patch (a croire que ça a fonctionné correctement dés le début sur officiel) mais c'est comme ça sur quasiment tout les serveurs et je n'ai rien vu dans les "wintergrasp strategy" de l'époque qui laisse à penser qu'on peut être ou on veut sur la carte au démarrage de l'event.
https://tagn.wordpress.com/2010/11/12/a-noobs-view-of-wintergrasp-strategy/

**Comment by joshwhedon** [comment]
MErci
