### ISSUE TITLE
Paladin ret sort "Sceau d'autorité"

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#852]
Bonjour
Le sceau d'autorité ne proc pas sur la petite abomination en bouteille.
Ce bug est due au fonctionnement du sceau d'autorité sur ce serveur puisque le sceau comprends un cd interne court...
De plus il proc après que des dégas aient étés infligés aulieu d'être activé par le "swing" ou l'activation d'une technique physique (normalement même si on rate, on est esquivé ou paré... le sceau d'autorité doit taper avant. De même si on tue la cible avec le coup blanc, le sceau doit avoir tapé en premier normalement, c'est le fonctionnement normal)
Voir le sujet 591 pour les détails je n'ai plus eu de réponse dessus... Depuis j'ai eu une petite abo et j'ai bien constaté ce dont je parlais à l'époque :
github.com/way-of-elendil/3.3.5/issues/591
Comment résoudre => revoir le fonctionnement du sceau pour qu'il soit appliqué au swing et non au degas,

OU retarder de 0,1s les degas de la petite abomination (ça sera fonctionnel au moins)

preuves :

-patch 3.2
https://worldofwarcraft.judgehype.com/patch3-2/
"Sceau d'autorité a été repensé. Il inflige dorénavant un montant de dégâts égal à 36% des dégâts de l'arme à chaque frappe, et il inflige nettement moins de dégâts de jugement."

-patch 3.2.2
https://worldofwarcraft.judgehype.com/patch3-2-2/
"cette technique s'enchaîne maintenant pour frapper jusqu'à 2 cibles supplémentaires quand elle est déclenchée par une attaque qui ne touche qu'une cible."

Donc : 
1 : Si je fais une frappe sur une cible (auto attaque ou inquisition ou proc d'arme physique tel que l'arme rafale ou proc bijou main de justice ou petite abomination en bouteille etc...) le proc va toucher la cible ainsi que jusqu'à DEUX mobs autours.

2 : Si je fais un coup physique d'AOE sur 1, 2, 3, 4 cibles ou plus (je n'en connais pas en proc et le paladin n'en utilise que deux à savoir la tempete divine et le marteau du vertueux) le sceau d'autorité est sensé ne pas répandre le cleave aux deux cibles supplémentaire donc pas de "cleave" parcontre j'attire votre attention sur le patch 3.2 : "Sceau d'autorité a été repensé. Il inflige dorénavant un montant de dégâts égal à 36% des dégâts de l'arme à chaque frappe" cette utilisation n'a pas été révoquée au patch 3.2.2 il a juste été buff. Si je touche 4 cibles, le sceau d'autorité touche 4 fois (parcontre il ne cleave pas donc ne touche pas 12 fois, là dessus on est d'accord)

Edit : 
Concernant le fait que le sceau d'autorité est activé par le swing et non le dégas, il y a un guide paladin 2.4.3 dans lequel il est expliqué en détail que le sceau d'autorité peut être appliqué au moment du swing et qu'il fera ses dégas plutard (1s après environ) et qu'on a un moment précis ou on peut changer de sceau et faire proc les deux sceaux. Cette mécanique était utile sur BC car il y avait peut de sorts en paladin vindicte. Bien que les dégas du sceau ai été repensé, l'application du sceau d'autorité n'a pas changé... Bien que ça change peu de choses sur boss, il est vrai que ça réduit énormément les dégas sur les mobs ayant peu de point de vie donc pendant le farm par exemple ou sur les trash...

voilà le guilde : 
https://www.webless.be/?guide=8

Je me permets de préciser que le guide date de l'officiel et qu'il a été complété au fil du temps car certains serveurs avaient un sceau d'autorité qui proc sur dégas et non sur swing (exactement comme ici)
la partie interessante : 

d. Seal Twisting
Le passage suivant est à prendre avec des pincettes, cette technique ne semble pas fonctionner sur le serveur Pheonix pour des raisons liées à la mécanique de SoC.

Le Seal Twisting consiste à jongler entre 2 sceaux. En effet, vous pourrez obtenir un proc Soc+Sob en un coup blanc.

[Voyons la base du comportement de SoC pour commencer : 
SoC a un "CD caché" de 1sec, c'est pour ça qu'il ne proc pas 2 fois sur un windfury. Cette mécanique a été crée afin d'éviter que le proc SoC soit hors portée alors que le white parte. En gros il peut proc 1sec après votre coup blanc. 

Cela signifie qu’à l’instant T où votre swing part, vous avez T+1sec pendant lesquelles SoC proc. En gros on a 1 secondes de libre pour faire du seal twisting. 

Concrètement, cela consiste à foutre un 2éme sceau durant cet instant T+1. Je vois vos "ZOMG §§§§ CTROP CHAUD A FAIRE §§§, mais que nenni ! Tout ce qu'il faut c'est un timer auto swing, genre Quartz (oui encore lui ...) et une bonne latence. 
Tout ce qu'il faut pour que ça fonctionne, c'est bien timer le twist (Pour les ally twist SoC / SoRighteoussness, SoC/SoVengeance, et SoC/SoJustice pour le pvp, pour les BloodElf vous rajoutez SoC/SoB et là c'est complètement cheaté) pile au moment du swing (vous avez cet instant T+1 pour agir fissa, sachant que il faut que ce soit SoC votre sceau de départ). ]

**Comment by joshwhedon** [comment]
"cette technique s'enchaîne maintenant pour frapper jusqu'à 2 cibles supplémentaires quand elle est déclenchée par une attaque qui ne touche qu'une cible."
Ca contredit ce que tu dis concernant le swing, vu qu'ici ca parle de toucher. On ne peut pas declencher un sort au moment du swing si in ne sait pas ce qui va toucher.
Donc je ne pense pas que je vais changer quoi que ce soit au sceau d'autorite, a moins que des preuves plus flagrantes soient fournies.

**Comment by joshwhedon** [comment]
Et NON je ne retarderai pas la petite abomination de 0,1 seconde, la petite abomination marche parfaitement bien telle qu'elle est maintenant.

**Comment by ronlii** [comment]
"Ca contredit ce que tu dis concernant le swing, vu qu'ici ca parle de toucher. On ne peut pas declencher un sort au moment du swing si in ne sait pas ce qui va toucher."
Le terme toucher n'a pas été évoqué ; pas même "inflige des degas" mais bel est bien "est déclanché" ce qui pour moi met en lumière qu'une mécanique spécifique est bel et bien en oeuvre... J'ai fourni suffisamment de preuves... Si vous pensez ne pas être capable d'activer le sceau sur le swing tant pis ; c'est pareil sur tout les serveurs !
Parcontre s'il vous plait faites l'efforts que le sceau d'autorité tape 4 cibles lorsqu'on utilise la divine storm et qu'il proc 2 fois soit 6 cible au maximum lorsqu'on utilise la petite abomination... C'est tout ce que je demande depuis le début ! Ensuite comment vous vous débrouillez avec vos script pour que ça soit possible, ça vous regarde : moi je n'ai fais que donner mon propre avis de joueur mais aussi de développeur car je sais que certaines fonctionnalités sont complexes à mettre en oeuvre.

**Comment by joshwhedon** [comment]
"qui ne touche qu'une cible"

**Comment by joshwhedon** [comment]
Le probleme n'est pas l'implementation, le probleme est que j'ai encore des gros gros doutes sur la validite de ce bug. LEs donnees clients pour le sceau indiquent qu'il proc dans ces cas la :
02 Successful melee attack
  04 Successful attack by Spell that use melee weapon
Ce ne sont pas les donnees d'un sort qui proc au swing, il y a d'autres donnees pour le swing / cast. Donc les donnees client sont en total opposition avec ces informations, qui elles memes sont loin d'etre claires quant au fonctionnement considere normal.

**Comment by joshwhedon** [comment]
En gros, on ne peut pas declencher un sort au niveau du swing, si le proc lui meme est base sur le nombre de cibles touchees, au moment du swing on ne sait pas si l'attaque de melee est un succes.
Changer le proc pour qu'il se declenche sur les miss / dodge / etc, c'est simple, ca reste au moment du toucher, et ca s'aligne avec le comportement normal du systeme de proc. Changer le proc pour qu'il se declenche au moment du swing MAIS en fonction du nombre de cibles touchees, c'est en opposition complete avec le systeme de proc actuel, qui concerne des centaines de sorts dans le jeu.

Donc deja, ce que je demande, c'est une preuve claire que le sceau proc sur les miss / dodge / parry / etc.

**Comment by ronlii** [comment]
On se perds dans des details car il y a eu 2 patchs. Je ferais un récap du sceau depuis vanilla pour expliquer. Plus tard

**Comment by joshwhedon** [comment]
https://www.wowhead.com/forums&topic=98367#:~:text=Seal%20twisting%20was%20also%20used,before%20your%20white%20damage%20hit.
Plus valid en 3.3.5

**Comment by joshwhedon** [comment]
Et sinon j'ai teste, si plusieurs cibles sont touchee, chaque cible est bien touchee par un seul  proc du sceau d'autorite. Donc ca marche comme il faut de ce cote la. Par contre si j'utilise une aoe genre divine storm, et qu'elle touche qu'une seule cible, le sceau d'autorite chaine bien sur une cible proche.

**Comment by joshwhedon** [comment]
Quant a la petite abomination. Je viens de tester, a distance pour toucher une seule cible, tempete divine, j'ai eu 2 proc de l'abomination, une pour la tempete et probablement une pour le sceau. Donc le proc du sceau fait bien proc l'abomination.

**Comment by ronlii** [comment]
Le fonctionnement du sceau normal en 3.3.5 : 
-Effet 1 : Proc sur tout les degas physiques (même les aoe tel que tempête divine ou marteau du vertueux => voir patch 3.2)
-Effet 2 : Proc sur 2 ennemis supplémentaires à portée de cleave SAUF sur degas d'aoe (tempête divine / marteau du vertueux => voir patch 3.2.2)

Le fonctionnement du sceau sur le serveur : 
-Effet 1 : Proc sur tout les degas physiques (même les aoe tel que tempête divine ou marteau du vertueux => voir patch 3.2) MAIS avec un cd interne de 0 sec (pas de proc multiple)
-Effet 2 : Proc sur 2 ennemis supplémentaires à portée de cleave même sur AOE MAIS avec un cd interne de 0 sec (pas de proc multiple)

Problême engendré : 
-Lorsque la petite abomination passe à 7 ou 8 granules et FRAPPE la cible, le coup part en même temps que le coup blanc et donc n'active pas un second sceau d'autorité.
-Lorsqu'on utilise tempête divine sur 4 cibles, il n'y a que 3 sceau et non 4 car aulieu d'avoir l'effet 1 sur les 4 cibles affectées par tempete divine, seule UNE est affectée par l'effet 1 ET l'effet 2 affecte LUI les 2 cibles supplémentaires alors qu'il ne devrait pas (preuve : si vous refaites vos test en faisant tempête divine de dos, seul 1 proc sceau d'autorité sera actif car le cleave ne s'active pas de dos.)

comment résoudre =>
-Retirer le cd interne du sceau tel que c'est le cas sur tout les autres sceau de dégas du paladin pour que l'effet 1 s'applique normalement.
-Empêcher le proc de l'effet 2 sur tempete divine et marteau du vertueux

Précision complémentaire : 
-Pourquoi paladin ça fait des tempêtes divine de dos wtf ? eh bien pour délay l'auto-attaque de 0,1-0,2 seconde parfois => de façon à se tourner juste après la tempête divine et avoir 40% de chance de réinitialiser la tempête divine (bonus 2 part t10)
-L'effet 2 ne dépend pas de l'effet 1 : Lorsque je tape un lapin avec 1 pv (je le one shot) et qu'il y a un écureuil a coté, le sceau d'autorité est sensé cleave et toucher le écureuil.
-vous avez dit le sceau d'autorité fait bien proc la granule de la petite abomineation, je n'ai jamais remis cela en doute, c'est le cas inverse qui est manquant sur ce serveur, c'est à dire le fait que le proc DEGAS de la petite abomination (une demis auto attaque) est sensé faire proc un sceau d'autorité complet, effet 1 ET 2, ce qui n'est pas le cas ici et change tout au cleave du paladin.

**Comment by joshwhedon** [comment]
Il y a pas d'effet 1 et 2 hein, il y a qu'un seul effet qui chaine.
Bref, base sur les patch notes et sur les info que j'ai trouve sur l'abo, je mets un changement prochaine maj. 
PAs la peine d'ouvrir un ticket sur le seal twisting, c'est pas valid en 3.3.5

**Comment by ronlii** [comment]
Il y a aussi la tempête divine qui fait proc seulement 3 fois le sceau max aulieu de 4... Je vous ai exposé clairement pourquoi et comment résoudre, j'ai vraiment espoir que ça soit débug car le dps multi du paladin sera beaucoup plus fort si c'est bien script => sur un reccount normal le sceau d'autorité dépasse les 45% du dps parfois et ici à peine 33-35%
