### ISSUE TITLE
Spell: Sceau d'autorité et vengeance

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#853]
Lorsque le sceau d'autorité fait un coup critique, le talent "vengeance" est sensé être appliqué.

Patch 1.11.0 :
https://worldofwarcraft.judgehype.com/patch1-11-0/
Vengeance – Les coups critiques du Sceau d'autorité peuvent maintenant déclencher cette technique.

Edit Ischjgt: 20375 - [Sceau d'autorité, rank 1 frFR]
20057 - [Vengeance, rank 3 frFR] [talent]

**Comment by Ferro3** [comment]
ok, j'en sais rien je joue pas en PvP (ça m'intéresse pas)
du coup l'impact est mineur en début de combat pour le PvE

**Comment by Justforsoloq** [comment]
"l'impact est en début de combat, du coup surtout pour le PvP, en PvE l'impact est quasi inexistant"
Je te citais juste là dessus ^^, vu que tu disais que l'impact était quasi inexistant en pve, j'faisais juste la remarque qu'en pvp c'était inexistant tout court ^^

**Comment by Ferro3** [comment]
j'avais compris, et tu as très bien fait
