### ISSUE TITLE
Spell: Violation

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#854]
**Description**
https://woehead.way-of-elendil.fr/?spell=55666
https://woehead.way-of-elendil.fr/?spell=55667
Testé rang 2

Le joueur est toujours ralenti si le DK sort de la zone

**Comportement attendu**
"Targets in the area are slowed by 50% by the grasping arms of the dead **while standing on the unholy ground**. Lasts 20 sec."

**Comment by joshwhedon** [comment]
"Targets in the area are slowed by 50% by the grasping arms of the dead while standing on the unholy ground. Lasts 20 sec."
C'est quand la cible est dans la zone qu'elle est ralentie, pas le dk.

**Comment by Ischjgt** [comment]
J'ai lu la traduction française en premier :(
