### ISSUE TITLE
L'Arcatraz = Pack de npc trop nombreux

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#855]
Bonjour,

A l'arcatraz, dans BC, il y a comme sur cette video https://www.youtube.com/watch?v=hJjo5Mb69vM
un pack de Cauchemar protéiforme (https://woehead.way-of-elendil.fr/?npc=20864). Ceux si sont beaucoup trop nombreux, et one shot n'importe quel groupe.

Dans la video c est a 0:50, les npc humanoid sont censé les tuer au fur et a mesure, de sorte qu'il n'en reste qu'un nombre limité, alors que sur le serveur a mon avis il se stack sans limite.

Merci a vous,
Bon courage.

**Comment by joshwhedon** [comment]
Vous avez afk a l'entree ?

**Comment by Notil78** [comment]
lol, il est probable que nous ayons mis du temps a arrivé. possiblement a cause d un coéquipier retardataire.

**Comment by Notil78** [comment]
Nous avons refais hier, et en effet, si on attend pas pour faire ce pack, il est faisable.

**Comment by Killyana** [comment]
Il faut peut être juste augmenter les dégâts des gardes

**Comment by joshwhedon** [comment]
Oui je comptais faire ca, je voulais juste confirmer la situation.
