### ISSUE TITLE
Kologarn - Uldu 10

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#857]
On a eu droit à un boss presque poteau. Le bras n'a pas repop, les élem n'ont pas pop à la destruction du bras. Le tronc balançait bien ses techniques (je crois). Quand le boss est tombé, impossible d'utiliser son corps comme un pont. Tous ceux qui ont essayé sont tombés dans la fosse à ses pieds. D'ailleurs, pendant le combat aussi, impossible d'utiliser certaines tech (comme série meurtière) sous peine de finir dans le trou avec les pieds du boss.

**Comment by joshwhedon** [comment]
Vous savez comment c'est arrive ? Vous avez fait un truc special ?

**Comment by joshwhedon** [comment]
Merci de tenter d'appeler un mj aussitot que le probleme a lieu si vous le rencontrez encore. Pas moyen de reproduire de notre cote.
