### ISSUE TITLE
texte de quête - Alimenter le feu

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#858]
Le temps de marcher sur Gundrak l'est venu, mec. Moi, maintenant, faut que je vous lâche sur les trolls !

Notre mur, ils l'ont passé, et ils ont mis toute une armée juste au **nprd**.

Hahaha !

Ces mecs, ils vont servir à alimenter le feu ! Les chefs, on va les garder, et on va massacrer le reste ! Tout ça, c'est dans mon plan...

Voilà un sceptre pour commander mes abominations. L'armée Drakkari, faut balancer les abominations dessus pour tout tuer ! Et quand les chefs ils viendront, mon serviteur Aile-de-**chiste** il va les choper et les ramener ici.

J'ai mis les fautes en gras

**Comment by joshwhedon** [comment]
Je suis surpris que quelqu'un lise les textes :D
