### ISSUE TITLE
Familier: Perte de familier Maitrise des bêtes

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#859]
**Description**
Perte de familier exotique lors d'un changement dans l'écurie

**Étapes de reproduction**
- Chasseur mini 60, Double spé avec 1 avec Maitrise des bêtes (dernier talent BM) et l'autre sans
- Apprivoiser 2 familiers, 1 pouvant être apprivoisé dans toutes les spés (ex: 31233 - [Loup musculeux] ), 1 exotique (ex: 32485 - [Roi Krush] )
- Spé bête, avec le familier exotique de sorti
- Changer de spé, le pet n'est pas invocable mais il est la dans l'écurie
- .cast 62757, changer de pet, le pet exotique disparait au changement

**Comment by joshwhedon** [comment]
Voir https://github.com/way-of-elendil/3.3.5/issues/24

**Comment by Ischjgt** [comment]
Le soucis que j'explique n'est pas le même que ceux mentionnés dans le ticket que tu me link.
La perte des pets ne se fait plus dans les cas du ticket que tu as mentionnés
