### ISSUE TITLE
Une distinction pour services rendus [70] / Anneau reputation Karazhan

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#863]
Bonjour,

Il y a une mechanique bizare. Si on annule la quete "Une distinction pour services rendus [70]" https://woehead.way-of-elendil.fr/?quest=10738 qui donne l'anneau Révéré Karazhan, pour faire de la place dans le journal de quete par exemple.
Et bien, ça supprime de notre inventaire l'anneau obtenu avec la quête précédente (Honoré).

Normal ? Pas normal ? ca me semble bizard quand même.

Merci a vous,
Bon courage.

**Comment by joshwhedon** [comment]
De ce que je me souviens, c'est normal. C'est pour empecher les joueurs d'obtenir plusieux anneaux en acceptant / annulant les quetes.
