### ISSUE TITLE
taxe des dépôt à l'HV

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#864]
Concernant l'HV, je sais qu'il y a eu une entrave niveau blizz pour une adaptation au serveur avec le prix des dépôts à l'hv; néanmoins les dépôts sur les tissus et les minerai sont extrêmement chère contrairement au reste ce qui entrave ce commerce car il est très peu rentable de passer par l'hv ce qui au final pousse les joueurs à ne pas mettre ses items en vente; petit exemple: sur 1 stack de barre de saronite soit 20 barre de saronite le dépôt est actuellement de 37PO 50 PA; alors que l'item se ''vend'' en général à 60/80 PO les 20; donc on perds 1/2 de la somme en dépôt en soit ce qui conduit bon nombre de joueur à spam l'inter (je vend des minerais); 

Cela ne concerne UNIQUEMENT les barres craftés / les tissus / et dans une moindre mesure le cuir (mais ici effet moindre) et les minerai - pourrait on donc adapté pour ses items (ci-mentionné) le prix de dépôt à la réalité du serveur comme c'est le cas pour quasiment tout le reste ou garde t on des prix de dépôt si élevé uniquement sur 2 type voir 3 type de produits... exemple des plantes ou 1 stack de plante norfendre ne ''coute'' que 3 PO 75 PA; alors que 20 barre de saronite = 37 PO 50 PA soit une différence 11 x supérieur..

autres exemple 1 minerai de saronite coute 37 PA // alors que 1 barre de saronite coute 1PO 87 PA en prix de dépôt alors qu'il ne faut que ''2minerai'' pour craft 1 barre de saronite..

Pour le tissu c'est même pire 1 rouleau de tisse-givre imprégné coute jusqu'à 3 P0 en prix de dépôts x20 pour avoir une stack cela représente quand même 60 P0 de dépôt... qui sont perdu que le stack se vendent OU non !

**Comment by joshwhedon** [comment]
LE soucis a deja ete etudie il y a plusieurs semaines (juste apres le merge). Les valeurs sont correctes au niveau du cut et de la taxe (le cut = quantite de PO prise sur la vente, taxe = quantite de po fixe pour la mise en place de la vente).

**Comment by Kwyzard** [comment]
Et donc vous etes en taxe type "neutre"? donc 30% au lieu de l'habituel 10% horde / Ally ?

**Comment by joshwhedon** [comment]
Qu'est-ce que tu appelle taxe, parce qu'il y a la taxe, et il y a la cut. La taxe c'est fix, base sur la valeur de l'objet en vente au npc (si je me souviens bien). La cut c'est base sur la vente finale. Je crois que du au fait qu'on est oblige d'utiliser les AH neutre, le cut apparait plus eleve, mais au final c'est bien le meme cut partout quand l'argent lui meme est calcule.

**Comment by gtschanz** [comment]
soit; je trouve ça quand même hyper chère pour 1 stack de tissu (même si c'est des épiques) de rekt 60 P0 sans garantie de le vendre; j'ai fais un test sur 2/3 semaine résultat on perd des po vu le peu d'acheteur et ça n'encourage donc pas à utiliser la mécanique de l'hôtel de vente pour certains items (vu la faiblesse de la demande qui est occasionnel) -> ce qui conduit donc à une limitation de l'utilisation de cette mécanique. Je spamerais donc l'interfaction à l'avenir avec mes demandes de vente. dommage !

**Comment by Endalaust** [comment]
Il existe toujours des hotels de vente dans les capitales au passage.. 

Comme a dit Josh, la taxe a un montant visuellement plus élevé que ce qu'elle prend vraiment sur les HDV neutre. Un "problème" visuel impossible à fixer mais qui n'en est en réalité pas un. 

Si vous parlez du cut en revanche, je ne mouille pas n'y connaissant rien

**Comment by Kwyzard** [comment]
me semble que c'est la taxe de dépot qui est différente pour les ah neutre pas le cut

**Comment by Endalaust** [comment]
Je l'ignore, mais si on parle de la taxe de dépôt, c'est thread est un faux positif.

**Comment by gtschanz** [comment]
bah je viens de faire le test pour un rouleau de tisse-givre imprégné = retrait en dépôt indiqué = 3PO pour 1 unité; réalité du terrain = 3 PO réellement prélevé

**Comment by gtschanz** [comment]
donc ''Comme a dit Josh, la taxe a un montant visuellement plus élevé que ce qu'elle prend vraiment sur les HDV neutre. Un "problème" visuel impossible à fixer mais qui n'en est en réalité pas un.'' @Endalaust je ne suis donc pas totalement d'accord avec cet argumentaire

**Comment by Endalaust** [comment]
@joshwhedon pour te permettre d'investiguer : 
https://github.com/way-of-elendil/3.3.5/issues/171 

<img width="992" alt="screenshot_1479" src="https://user-images.githubusercontent.com/1420867/84605997-2d875400-aea2-11ea-9d08-b8ecc1982022.png">

**Comment by joshwhedon** [comment]
Merci je sais que le sujet a ete traite ...
