### ISSUE TITLE
loot de recettes de joa en dj

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#865]
Un de mes persos est joailler et quand une recette de joa tombe, si celle-ci est déjà connue, le jeu me fait passer automatiquement sur le rand. Par contre, avec mes persos non joaillers, je peux cupi sans problème.

**Comment by sithis2a** [comment]
Tu es sûr que ce n'est pas dû à un addon quelconque car perso je peux choisir besoin/cupi/pass sur les plans que j'ai déjà quand ils tombent en donjon ?

**Comment by Kwyzard** [comment]
me semble que je peut cupi genre y a 2 semaine max, c'étais le cas

**Comment by joshwhedon** [comment]
A premiere vue je peux pas reproduire non plus de mon cote. Je dirai comme indique plus haut que c'est un soucis au niveau de config de tes addons.
