### ISSUE TITLE
Dégâts LK et Horreur 

### ISSUE THREAD

**Issue by Mougnok** [way-of-elendil/3.3.5#866]
**Description**
Les dégâts du LK et des Horreurs sont beaucoup trop élevés.
Le MT1 et le MT2 ont 6k6 GS, 42k+ armor et prennent des coups blancs sous CD à 43k pour le MT1 (LK) et des 80k pour le MT2 sur les Horreurs. Les stuns sont faits mais ils ne durent pas indéfiniment, si le MT2 n'esquive pas, ne parade pas ou ne bloque pas le coup de l'horreur, il prend des coups à 80k... et nous sommes sous buff 30 !
Je ne sais pas si le bug vient des dégâts du LK et des Horreurs ou des stats défensives (armure) des tanks mais ce combat est complètement ridicule avec le script actuel.
Nous faisons des logs de nos raids sur Worlsoflogs, si vous voulez voir par vous même.

**Étapes de reproduction**
Raid 25 sur le combat du Roi-liche et observer les dégâts reçus par les tanks (full gear et sous CD)

**Ressources additionnelles**
logs sur Worldoflogs disponible au près de Mougnok ou d'un officier des Tout en Douceheure

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/232

**Comment by Mougnok** [comment]
Je l'ai lu et je refais un post parce qu'apparemment rien n'a été réglé ou n'est bug selon les MJ. Honnêtement allez raid et voyez par vous même parce que c'est insupportable.
Nous sommes sous buff 30 et full gear faut arrêter !
Logs à l'appui je le rappelle

**Comment by Ischjgt** [comment]
- > Je l'ai lu et je refais un post parce qu'apparemment rien n'a été réglé ou n'est bug selon les MJ. 
Mal apparemment

- "Blabla on joue pas", "blabla on connaît rien au jeu".
Si c'est son seul argument, je peux fermer le ticket.

**Comment by Mougnok** [comment]
Mon argument c'est les logs à l'appui !

**Comment by Mougnok** [comment]
Au passage je trouve ta façon de répondre à quelqu'un en tant que MJ un peu limite.

**Comment by Mougnok** [comment]
Peut-être, est-ce juste un problème de réductions de dégâts lié à l'armure. Je ne sais pas pas exactement, je demande juste à ce qu'on se penche vraiment sur le problème.

**Comment by Ischjgt** [comment]
- Tes logs ne servent à rien si c'est pour les comparer à d'autres serveurs privés.
- Je prends la même fourchette de dégats que sur cette vidéo en drood tank 37k armure https://www.youtube.com/watch?v=CVLSV7EL3Hc , sans buff raid.
- Je parle de la même façon que l'on s'adresse à moi, cf ta requête

**Comment by Mougnok** [comment]
Ce sont des logs de notre raid de hier soir 14/06 sur Way of Elendil.

**Comment by Kwyzard** [comment]
link les log stp

J'avais vu sur des log des horreur pas enrage mettre des 40k+ j'avais trouver sa beaucoup aussi, dans l’idée sans buff 30%hp tu te fait littéralement os

**Comment by Ischjgt** [comment]
> Oui LK peut 2 shoot un tank pas bien stuff, et l'horreur peut OS un tank sous le soft enrage, pour ça il faut les stunn.

D'où l'utilité de bien lire le ticket que j'ai link ça sert à rien de commenter si c'est pour pas apporter de nouvelles informations

**Comment by Mougnok** [comment]
Stp Ischjgt, co toi en jeu. Je te donne les logs et regarde les dégâts de l'horreur sur le MT2 full stuff (78k, 82k et j'en passe)

**Comment by gtschanz** [comment]
@Ischjgt @joshwhedon @Kwyzard @Mougnok @Endalaust  (j'ai mentionné tout les participants à la conversation) Pour avoir creusé un peu sur le lk et savoir ce qui ‘’décone’’ voici mon aperçu ;

Voici ma source pour toutes les références : 

[https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)](url)

EN P1 LK :

1)	Les horreurs qui pop dès qu’elles enrage peuvent mettre instant le coup alors que d’après la data base sur le LK il est précisé EXPLICITEMENT :
Increases Physical damage by 200% 1.25 sec cast (7 sec cooldown) – le coup sous enrage ne peut donc être mis que 1.25 sec après (ce qui en théorie permet le travel time de la flèche du chasseur qui disenrage -> actuellement il est donc impossible de MT2 en druide / dk car on ne peut pas stun une horreur enragé (classe sans stun) vu que le coup peut partir à +0.00 sec après le début de l’enrage contrairement au pala / war qui peuvent stun permettant le ‘’traveltime’’ de la flèche qui disenrage ! alors qu'il doit être possible de tanker avec chaque classe en mt2

2)	D’après les sources les infestés sont supposés s’enlever dès que les ‘’victimes ont plus de 90% de leur pv en p1 et non pas 100% comme actuellement:
60 yd range—Deals 6,598 to 7,402 Shadow damage to all enemy players within 50,000 yards. In addition, the targets will take increasing Shadow damage per second. **This effect is removed when the target has more than 90% health**. 2 sec cast. 9,425 to 10,575 on 25-player

--- Il n’ont pas fait de distinction sur les infests P1 / P2 c’est donc la même règle sur les 90% qui s’applique pour l’enlever.

3)	Les horreurs ENRAGE automatiquement à – de 20% ici c’est normal sur elendil ; mais contrairement à l’autre enrage des horreurs celui-ci n’est **‘’que’’ de 100%** au lieu des 200% habituel.
Voici le détail sur les enrage à – de 20% : ‘’Increases the caster's attack speed by 50% and the **Physical damage it deals by 100% for 10 min**. Instant, cast on Heroic when Horrors reach 20% health.’’ -> **ICI un tank sans le buff 30% doit pouvoir survivre cet enrage sans ce faire OS car il ne peut pas être dispell par les chasseur** ; SANS LE BUFF 30 -> rappel. **Et les dégâts des horreurs à – de 20% OS quasiment les tanks avec le buff 30% en étant sous CD (sur elendil)**; il est donc **IMPOSSIBLE qu’ils survivent ça sans le buff 30 même sous CD.**

 
EN P2 LK :

1)	Voici les dégâts normaux sur les faucheurs :
 Melee range—Strikes the target for 50% weapon damage and afflicts the target with Soul Reaper. This effect deals **50,000 Shadow damage after 5 sec** and increases the caster's haste by 100% for 5 sec. Instant. **Used on the tank. 60,000 on 25-player and 10-player heroic, 70,000 on 25-player heroic**. – j’ai vu personnellement des faucheurs qui ‘’excèdait les 70K’’ @Mougnok aurais-tu des faucheurs dans ses cas là sur tes logs ????

Pour toute discussion constructive je vous serais gréer à chacun des participants de présenter ses sources ; les miennes sont ici de la data base de wow comme je l’ai mentionné ci-dessus ; rappel du lien : [https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)](url) - en espérant pouvoir avoir un échange constructif sur ce sujet sans énervement de chacun (joueurs / staff) car je pense que nous voulons tous aller dans le même sens à ce niveau ;)

**Comment by Ischjgt** [comment]
1. Non
![Capture d’écran 2020-06-15 à 17 53 45](https://user-images.githubusercontent.com/60295792/84679290-6cb0b600-af31-11ea-90bd-5007592bd4e8.png)
Timer Heure:Minutes:Secondes
En vert, les AA de l'horreur sans enrager, en orange l'enrager, en rouge AA avec l'enrager, qui arrive 3 secondes après la dernière AA et 2 secondes après l'enrager alors que les précédentes AA ont 2 secondes d'intervalles. 25nm

2. Non, J'avais 92% de pv et l'Infester s'est bien posé puis barré. 25nm

3. Non. Déjà il faut savoir qu'elles enrage qu'en 25HM en dessous de 20%.
Et ensuite voici l'aura que chope l'horreur en 25HM donc quand elle passe sous la barre des 20%. https://woehead.way-of-elendil.fr/?spell=28747

4. C'est correct, je prend un 50k faucheur sans rési ombre en 25NM.

**Comment by Mougnok** [comment]
Qu'en est-il en 25hm ?

**Comment by Kwyzard** [comment]
Donc déjà si tu est sur que le point **numero 2** est bien bug tu peux faire un post à part et on enlève ça de la discussion pour pouvoir parler seulement des Shambling(horreur) et du LK

Alors pour ton point **numéro 1** j'ai émit l'hypothèse sur discord qu'il y avait peut être un reset du timer de l'auto attaque de l'horreur une fois qu'il finissais le cast "de l'enrager" c'était une hypothèse que je me suis imaginez dans le sens est ce que Blizzard avait pensez à cet éventualité ou l'horreur enrage et met une patate de forain directement (et donc un os du MT2 ) ou non. 
Il faut bien que tu fasse la différence entre le cast et le reset auto attaque dont je parlais (aucunement sûr c'est vraiment une hypothèse bien que Erka ait dit sur discord que ça semblait être le cas il faudrait vraiment vérifier ça) la tu cite les **"1.25 sec cast"** c'est le mob qui cast "enrager" pendant 1.25 seconde c'est pas du tout l'histoire du timer d'auto attaque faut bien faire la différence.

D'ailleurs est ce que si tu stun l'abo sur le cast elle prend 7 seconde de cooldown ou le relance direct après ? (pas très important)

edit: donc @Ischjgt tu confirme y a bien un reset du timer auto attaque (swing) lorsque l'abom cast enrage?

Pour le point **numéro 3** comme dit c'est pas un enrage 200% mais "seulement un 100%" c'est **tankable sous CD** du tank les dégâts semble correct même sans buff 30% ont voit les horreurs taper a quoi entre 20 et 26K en moyenne tu double ça ca fait un bon 45K+ de moyenne l'off tank est obliger de cd mais pour moi ça reste normal et prenable même sans le buff 30%

**Comment by Theralion** [comment]
Bonjour, 

Je me permet de rajouter un point à la liste de gtschanz qui énormément varier depuis la merge sur le faucheur d'âme, il s'agit de la 1ère frappe appliquée lors de la pause du débuff, elle doit normalement faire 50% des dégats du LK (mitigée par l'armure vu que c'est une frappe ?), qui est obligé d'être prise sous CD actuellement, et non avant, et cela me parait anormal au vu de la description de la frappe :

https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)
Melee range—Strikes the target for 50% weapon damage and afflicts the target with Soul Reaper. This effect deals 50,000 Shadow damage after 5 sec and increases the caster's haste by 100% for 5 sec. Instant. Used on the tank. 60,000 on 25-player and 10-player heroic, 70,000 on 25-player heroic. –

Je n'ai pas une plage de dégats de l'arme du LK d'offi, si je me base sur le woehead cf post de Endalaust https://github.com/way-of-elendil/3.3.5/issues/232
https://woehead.way-of-elendil.fr/?npc=36597

On est à 184065-271345 pour du 25hm, déjà bien plus haut que pour les autres serveurs cités dans la comparaison soit dit en passant (après je n'ai pas les chiffres blizzard pour dire qui est le plus proche, je fais juste la même comparaison) : 

https://db.rising-gods.de/?npc=36597
25hm : 152473 - 210022

https://wotlk.evowow.com/?npc=36597
25hm : 79169 - 109050

https://wotlkdb.com/?npc=36597
25hm : 79169 - 109050

Je ne sais si ces chiffres sont représentatifs et ceux actuellement définis en DB, mais je n'ai que ça pour me baser dessus.

Si on applique 68% d'armor réduction (tous nos tanks en 25h sont à 40k armor minimum avec les buffs, soit 72% contre du lvl 80, je n'ai plus la formule en tête pour calculer contre du 83+, mais on doit descendre à 68-69% maximum je dirais, ça porte la frappe initiale à maximum : 

271345 (dégâts max) * 50% (débuff SR) * 32% (absorption par l'armure de 68% minimum) = 43 415,2 et ce sans les mitigations apportés par les buffs et talents (3% DP par exemple)

=> Insuffisant pour OS un tank sans CD, hors c'est ce qui nous arrive régulièrement si un CD n'est pas claqué avant la pose du faucheur (je ne parle pas ici des dégâts finaux, seulement ceux de la 1ère frappe)

Je n'ai malheureusement pas de log pour le moment à apporter, je n'ai pas garder les logs de nos trys, mais Mougnok, si tu as des logs sur des faucheurs P2, peux-tu nous les communiquer, car il me semble que nous prenons beaucoup plus que 43K maximum sur cette 1ère frappe.

**Comment by Ischjgt** [comment]
En réponse à Theralion :
https://github.com/way-of-elendil/3.3.5/issues/847 J'ai rouvert ce ticket. Je te tiens au courant.

> Tes logs ne servent à rien si c'est pour les comparer à d'autres serveurs privés.

Si ça vaut pour Mougnok, ça vaut pour toi aussi, et pour moi et pour tout le monde en fait.

**Comment by Theralion** [comment]
Je suis d'accord pour la comparaison avec les autres serveurs privés, j'ai juste repris la même comparaison que celle faite par Endalaust dans le post https://github.com/way-of-elendil/3.3.5/issues/232 pour montrer que autant sur les dégats du 10NM cela allait dans sa direction, autant pour les dégats du 25H c'est clairement l'inverse :)

Mais déjà je ne sais même pas si on peut se fier à ces dégâts écrit sur le woehead comme étant les dégats actuels du LK, car c'est trop élevé pour être tanker, ça voudrait dire que le LK frappe sur un tank actuellement à 55 219-81 403,5 par coup sur un tank avec 70% de mitigation 83+, ce qui n'est pas les dégâts reçus actuellement (plus dans la range 38K-55k) et heureusement car ce n'est pas tankable

**Comment by Killyana** [comment]
Les Dégâts sont effectivement trop haut, ils seront nettement réduits avec la prochaine Maj.

**Comment by Darkprimate** [comment]
Vraiment dommage, ça donnait de l'intérêt a ICC 25h et obligeant les joueurs a try hard, donner leur maximum pour down le boss ( rotation CD à la perfection .. ect ). C'est bête de ne pas laisser les dégats actuel, pour un boss qui est censé être le plus difficile de l'extension, ça aurait du être comme ça dès le début, ça aurait rendu beaucoup moins accessible les armes 284 ..

**Comment by Endalaust** [comment]
Le ticket initial parle des dégâts des horreurs, qui eux n'ont pas été touchés. On parle exclusivement des damages du LK. Tout le rapport du joueur @Mougnok est incorrect, et la difficulté qu'il définie comme trop importante, demeure. Je précise juste, au cas où.

**Comment by Justforsoloq** [comment]
Après @Darkprimate (fianso ?) le truc c'est que t'as le 0% pour tryhard un peu plus (faut pas oublier que le 30% ça a jamais été censé être compliqué, ça passait en PUG en fin d'xpac tlk).
C'est du pve, pas de la rngpack (askip même avec les rotas cd si t'as pas de rng tu peux t'faire os :x)

**Comment by Killyana** [comment]
Je précise que c'est pas un nerf, une mauvaise valeur a été mise à jour dans la DB.
Actuellement c'est possible de se faire OS en ayant un full stuff 277.

**Comment by gtschanz** [comment]
éridium; par curiosité pourrais-tu nous indiquer ce que c'était ? merci par avance :) (ps fianso: t'as même pas down le boss 1x sans le buff 30 ne serait-ce qu'avec 25%; pour parler de difficulté facilité mdr)

**Comment by Killyana** [comment]
Trinity a mis à jours les dégâts (qui semble trop haute en 25h), et  sa a écrasé nos valeurs à nous, j'ai pas fait gaffe au début parce que j'ai regardé au mauvais endroit.

**Comment by Popeyeddd** [comment]
Ptdr j'arrive après la guerre et remarque d'aucune utilité du coup j'imagine mais @gtschanz 
Pour ton numéro 1 : Increases Physical damage by 200% 1.25 sec cast (7 sec cooldown) 
En fait 1.25 c'est le temps de cast de l'enrage ^^ donc ton hunt risque pas de la dispell pendant ces 1.25 sec. C'est pas un temps de répit ,c'est un temps de cast, le buff apparait qu'à la fin du cast de 1.25 secondes. Donc oui quand il apparait ton hunter désenrage, temps du travel time du spell, y a une auto qui part sous buff enrage le plus svt.

**Comment by Popeyeddd** [comment]
ptdrr bah épinarddd avait déjà dis ça en fait lolz
Y a eu un changement de script du coup @Ischjgt ? Par simple curiosité j'fais pas de pve :D
