### ISSUE TITLE
CM yogg saron 10

### ISSUE THREAD

**Issue by Fairivier** [way-of-elendil/3.3.5#867]
**Description**
Hier soir sur Yogg saron 10 sans gardien je me suis fait CM en sortait de la salle du cerveau. Il me restait environ 40 de santé mentale et je suis sorti a 3s de la fin du cast du susciter la folie. De plus pdt toute la durée du CM je pouvais encore contrôler les mouvement des mon personnage (pas normal) mais ne pouvais pas lancer mes sorts (normal). 

**Étapes de reproduction**
- Ulduar
- 10 0G
- Yogg saron
- salle du cerveau

**Comportement attendu**
je suis sensé sortir de la salle du cerveau sans etre CM.

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?v=Wdo-EhZ1HY0 sur la vidéo a 4:03 le joueur sort du cerveau a 2s de la fin du cast et ne se fait pas CM.

**Comment by Ischjgt** [comment]
Pas réussi à reproduire pour les 2 soucis que tu as rencontré.
Tu peux me dire quelle classe tu avais ?
Est-ce que d'autres joueurs ont eu l'un de ces soucis ?

**Comment by Fairivier** [comment]
J'étais en dk impie dps et non je suis le seul à avoir eu ce problème et ce n'est arrivé qu'une seul fois je n'avais jamais vu ce bug avant. On avait déjà eu des CM instant au passage p2 mais la c'est différent.
Je ne sais pas si le fait que j'ai un pet change qqc ou pas.

**Comment by Fairivier** [comment]
peut etre que a cause de ma goule le jeu a considérer que je me suis pris le susciter la folie. C'est une supposition mais comme les 2 autres dps qui étaient dans le cerveau avec moi (un war et une chouette) n'ont pas eu ce pb ca vient peut etre de la goule

**Comment by Ischjgt** [comment]
Je veux bien un nom de perso aussi

**Comment by Fairivier** [comment]
Fairïver

**Comment by Fairivier** [comment]
je précise aussi que je n'ai rencontrer ce bug qu'a un seul try

**Comment by joshwhedon** [comment]
Impossible de reproduire ce probleme. Et aucune idee de ce qui a pu se passer.
