### ISSUE TITLE
Creature: Vengeful Fleshreaper

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#87]
**Description** Quand Vengeful Fleshreaper Entry: 37038 saute sur un joueur et cast  https://woehead.way-of-elendil.fr/?spell=71164 il ne doit pas bouger durant la canalisation de https://woehead.way-of-elendil.fr/?spell=71163

**Étapes de reproduction**
- Donjon ICC
- Niveau de difficulté Toutes
- npc Vengeful Fleshreaper Entry: 37038
- Sort en question https://woehead.way-of-elendil.fr/?spell=71164 & https://woehead.way-of-elendil.fr/?spell=71163

**Comment by joshwhedon** [comment]
C'est un nouveau bug ca ?

**Comment by Killyana** [comment]
Je pense que oui, c'est peut être lié au correctif qui permet aux npcs de bouger durant la canalisation des spells qui ont SPELL_ATTR5_CAN_CHANNEL_WHEN_MOVING 
le spell 71163 n'a pas cet attribut, il a seulement: AttributesEx1: 0x00000004 (SPELL_ATTR1_CHANNELED_1)

**Comment by joshwhedon** [comment]
Bon je mets un script pour simuler un comportement normal. C'est un hack mais ca marche :D
