### ISSUE TITLE
Quete: Reprendre Achérus - Problème phasage

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#872]
**Description**

Cas où le joueur se retrouve en phase 1 après avoir rendu la lumière de l'aube

**Étapes de reproduction**

- .q a  https://woehead.way-of-elendil.fr/?quest=12801 et lancer l'event
- attendre la fin de l'event et rendre la quête
_Pendant la lecture de https://woehead.way-of-elendil.fr/?quest=13165 (ne pas prendre la quête), Darion despawn_
- Porte de la mort et le joueur se retrouve en phase 1
(peut-etre qu'il y a une histoire de déco reco à un moment aussi)

**Comportement attendu**
Le spell fait pas changer pas de phase ?

**Comment by joshwhedon** [comment]
Augmentation du temps de despawn de Darion pour reduire le risque.
