### ISSUE TITLE
Machine de guerre du fléau ; id : 32154

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#873]
**Description**
Voila : lorsqu'on fait la quete "attraper et lacher" on est constamment embêté par des "machine de guerre du fléau" qui ont beaucoup de point de vie et ne sont normalement que des décors SAUF si on se trouve nous même dans une machine volante (c'est une autre quete qui se passe non loin)

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
-"une nouvelle cible" et "équipé pour la récolte" lorsque je n'ai pas ces quetes et que je me trouve proche d'une ou plusieurs machines pour accomplir une autre quete, elles m'attaquent.
-pnj qui donne les quetes : kibli killohertz

**Comportement attendu**
Ce monstre devrait être un simple décors lorsqu'on n'est pas dans la machine volante délivrée par la quête "une nouvelle cible" ainsi que "équipé pour la récolte"
D’ailleurs même lorsqu'on est dans une machine volante, ce mob ne se déplace pas. On le canarde depuis le ciel avec la machine.

**Captures d’écran / Vidéos**
![image](https://user-images.githubusercontent.com/57768200/84801473-84567000-afff-11ea-9402-191cf2fe8791.png)

**Ressources additionnelles**
Je ne trouve pas d'information sur wow head à ce propos ; sur bien des serveurs les machine de guerre du fléau ont étés retirées de la plateforme ou se trouve les mobs relatif à la quête "attraper et lacher", surement pour ne pas avoir à script le fait de pouvoir toucher ou non ce mob-décors.

**Comment by Killyana** [comment]
Oui mauvaise phase pour ces npcs
