### ISSUE TITLE
Bug du buff "Parachute" id : 55001

### ISSUE THREAD

**Issue by ronlii** [way-of-elendil/3.3.5#874]
**Description**
La dynamique de chute n'est pas correctement réinitialisée lorsqu'on utilise la cape parachute d'une certaine façon à savoir qu'en pvp et dans bien des situations on est amenés à utiliser cet enchantement pour gagner du temps sans prendre de dégâts de chute...
En pratique bcp de joueurs ont la macro pour retirer le buff une fois la chute annulée pour ne pas avoir à attendre de toucher le sol.
Actuellement sur le serveur si on fait ça on va se remettre à tomber rapidement dés l'instant ou on retire le buff, aulieu de se remettre à tomber doucement. De plus une fois au sol, qui est à seulement 4 mètres en-dessous, on prends de lourds dégâts.

**Comportement attendu**
Les différents buff de parachute tels que l'enchant parachute (id : 55001), mais aussi le parachute permanent (lorsqu'on se retrouve en monture volante dans une zone avec vol désactivé (id : 44795) et enfin la chute lente du mage (je n'ai pas l'id sous la main), tous ces buffs sont sensés annuler la variable de force dynamique et la garder à 0 durant toute la durée du buff : 

explication : Lorsque je parle de variable de force dynamique, je parle de celle qui augmente au fur et a mesure d'une chute et dont les dégâts de chute dépendent. Sur ce serveur, les différents buff ne font que réduire sont effet et annuler les dégâts de chute si le sol est touché pendant le buff. Mais si on retire le buff pendant la chute et qu'on tombe à nouveau, même de quelque mètres seulement, on risque de mourir !

**Comment by Justforsoloq** [comment]
La partie bug c'est donc surtout là :   "De plus une fois au sol, qui est à seulement 4 mètres en-dessous, on prends de lourds dégâts."
Car la partie "cancel le buff on recommence à tomber vite" est normale.

**Comment by joshwhedon** [comment]
J'ai regarde et malheureusement j'y peux rien. C'est un soucis de lag au niveau des calculs de mouvement, et c'est pas un domaine ou je m'y connais suffisament pour corriger ce bug.
