### ISSUE TITLE
[Quête] La purification de Drak'Tharon

### ISSUE THREAD

**Issue by Zorbac** [way-of-elendil/3.3.5#875]
Bonjour, 
Je cherche à faire le HF Gourou de Drakuru pour lequel 2 suites de quêtes doivent être réalisées.
L'une d'entre elle apparaît validée mais pas l'autre (La purification de Drak'Tharon, id 12238).
Ayant écumé les quêtes de Norfendre et le descriptif me rappelant quelque chose, je suis sûr à 99% d'avoir fait cette suite de quêtes, mais il y a trèèès longtemps (je reviens d'une pause de 8 ans).
Avez-vous moyen de vérifier sur mon personnage (https://way-of-elendil.fr/armurerie-355/joueur/349494-krynn.html) que cette quête est bien réalisée et, à votre discrétion, soit me la valider, soit l'annuler (toute la suite si besoin) pour que je la relance au PNJ ?
Merci.

**Comment by Ischjgt** [comment]
Je te contacte IG
