### ISSUE TITLE
Queue: Arene et BG

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#876]
**Description**
Il n'est actuellement pas possible de queue pour arène et BG

**Comportement attendu**
Patch 3.3.3 (2010-03-23): Players can now be queued for battlegrounds and arenas at the same time.

**Comment by Kwyzard** [comment]
🙃

**Comment by Ischjgt** [comment]
Faut pas se moquer parce que je deviens une relique du passé.
