### ISSUE TITLE
Anhakï paladin 78 ( bug sur la quete "brisons la glace")

### ISSUE THREAD

**Issue by piotte62** [way-of-elendil/3.3.5#878]
La quête brisons la glace est buggué, quand on monte sur le protodrake il est au ralenti il ne sais ni descendre ni monter, on ne peux donc pas libéré les prisonniers comme l'on veut on dois attendre le repop des prisonniers les plus haut pour pouvoir faire la quête et le retour à Brunnhidar est super long!!!

**Comment by Ischjgt** [comment]
MP IG.

**Comment by Ysya555** [comment]
Il suffit d'appuyer sur la barre espace en montant sur le protodrake pour pouvoir le diriger normalement ensuite.
