### ISSUE TITLE
Boss: Yogg-Saron - Ulduar

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#879]
**Description**

Cas où les trashs de Mimiron (dans le couloir avant de prendre le tram) ont été aggro pendant le fight contre Yogg-Saron

**Étapes de reproduction**

Pas réussi à reproduire moi même.
Je pense que ça arrive lorsqu'une classe à pet choppe un TP pour entrer ou retourner dans la salle, j'ai pas réussi à reproduire à vrai dire, ça doit dépendre pas mal de la position du joueur/pet. 
Les trashs ont été aggro au passage dans le portail vers le cerveau apparemment.

**Comportement attendu**

Possible de TP le familier avec le joueur, actuellement le familier traverse les maps pour rejoindre son maître ?

**Comment by joshwhedon** [comment]
Quels trashs exactement ?

**Comment by Ischjgt** [comment]
https://cdn.discordapp.com/attachments/722375864125227030/722377367066247238/WoWScrnShot_061620_001946.jpg
https://cdn.discordapp.com/attachments/722375864125227030/722377380362190848/WoWScrnShot_061620_001955.jpg

Dans les screens du joueur on peut voir

Name: Arachnopod Destroyer
Entry: 34183.
Name: Clockwork Sapper
Entry: 34193.

Ce sont ceux aux couloirs des ingénieurs, pour se rendre au tram

**Comment by joshwhedon** [comment]
Impossible a reproduire de mon cote. A moins de trouver qui / quoi les a agro, je vais pas pouvoir corriger.
