### ISSUE TITLE
[Buff]Priorité sur la durée

### ISSUE THREAD

**Issue by Kwyzard** [way-of-elendil/3.3.5#883]
**Description**
Prenez un buff 60 minutes (Testez avec Don du fauve) et mettez ensuite le même buff en version 30 minutes, la version 30 minute passe dessus (stats similaire)

**Comportement attendu**

Le buff 60 minute doit rester sur la cible et coté joueur on doit avoir une alerte du type "un sort plus puissant est déjà sur la cible"

**Comment by joshwhedon** [comment]
Un peu le bordel a corriger, si je change ca ca risque de casser le stacking des buffs et debuffs. Niveau impact c'est assez mineur, mais je l'ai rapporte chez Trinity, avec de la chance quelqu'un corrigera a un moment, ils ont corrige les autres soucis de stacking que j'ai signale.
https://github.com/TrinityCore/TrinityCore/issues/24843
