### ISSUE TITLE
Quest: Rédemption] PNJ ne parle pas

### ISSUE THREAD

**Issue by Ilona011** [way-of-elendil/3.3.5#885]
**Description**
Au maleterres de l'est, le PNJ Tirion Fordring, donne la quete du nom de "Rédemption", pour valider celle ci il suffit d'ecouter le récit du PNJ, hors celui ci ne nous parle pas, et donc impossible de valider la quete

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Maleterres de l'est
- Alliance / Elf de la nuit / Druide
- Rédemption
- Tirion Fordring

**Comportement attendu**
Le PNJ dois normalement nous raconter un récit

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
https://fr.classic.wowhead.com/quest=5742/r%C3%A9demption#english-comments

**Comment by Ischjgt** [comment]
Il faut s'asseoir
