### ISSUE TITLE
[Druide][Spell]Emprise de la nature (Nature's Grasp)

### ISSUE THREAD

**Issue by Kwyzard** [way-of-elendil/3.3.5#886]
**Description**
Le sort actuellement fait proc des rendement dégressif alors qu'il ne devrais pas.
Si une personne vous frappe 3 fois d’affilé en quelques seconde le sarment passe de 10 seconde a 1 seconde (Rendement dégressif) 

Prenez exemple avec un sarment basique si vous spammez le sort le rendement supérieur reste actif

**Comportement attendu**
Les stacks doivent bel et bien partir mais l'emprise supérieur doit rester sur la cible

**Captures d’écran / Vidéos**
https://www.warcraftmovies.com/movieview.php?id=164959 (2min30) Le DK est sous emprise 10, la goule prend le deuxième stack, le DK grip le druide et le DK prend le dernier stack d'emprise de la nature mais le timer n'est pas rendu dégressif (Toujours a 7 seconde) 

**Ressources additionnelles**
https://github.com/TrinityCore/TrinityCore/issues/13695

**Comment by Justforsoloq** [comment]
J'le mets ici pour les gens du BT.
Mais ta vidéo prouve qu'il existe un dr : 
Dk root 10s => puis quand il grip le rdrood il se prend un root 6.9s (son root était à 5.8s) (et non 10s).

**Comment by joshwhedon** [comment]
https://blue.mmo-champion.com/topic/259193-crowd-control-cc-and-their-diminishing-returns-dr/
https://vanilla-wow.fandom.com/wiki/Entangling_Roots
https://www.engadget.com/2010-02-25-starfall-and-natures-grasp-ptr-changes.html
https://www.reddit.com/r/classicwow/comments/c8x124/if_me_and_my_friend_both_roll_druid_will/
Toutes les sources indiquent que le sort doit avoir un diminishing return.

**Comment by Kwyzard** [comment]
ouai j'ai mal expliqué j'ai parler de DR mais c'est pas ça le truc.

**comportement actuel**
Si rogue taper moi 3 fois d'affilé rogue sarment 1 seconde au lieu de 9+ seconde

**Comportement attendu**
Sa première attaque fait proc 1 stack d'emprise, il est root 10 seconde
Sa deuxième attaque fait proc le deuxième stack d'emprise, il est toujours root encore 9 seconde (du premier stack)
sa troisième attaque fait proc le troisième stack d'emprise, il est toujours root encore 8 seconde (du premier stack)

Enfaite c'est un peu comme l'histoire du buff druide, si y a un buff plus puissant il doit rester en place.
Fait le test avec un sarment ça fonctionne parfaitement juste l'emprise qui a se problème

et grace a ton lien il y a aussi 
"There is a small internal cooldown in between roots to keep say a rogue who hits you twice very quickly from wasting two charges" donc d'après ce qu'il dit y a un icd si une même personne te tape deux fois
https://www.engadget.com/2010-02-25-starfall-and-natures-grasp-ptr-changes.html

**Comment by Justforsoloq** [comment]
D'ailleurs actuellement sur woe ce fonctionnement marche correctement pour les autres sorts de contrôle : 
- Sheep 
- Fear
- Root cast classique 
"Un sort plus puissant est déjà actif" s'affiche quand on termine un cast de sheep sur un sheep 9s tant que la durée n'a pas atteint 50%.

**Comment by jackydit** [comment]
c'est toujours pas clair dsl

**Comment by Popeyeddd** [comment]
Comportement actuel :
Ex :
Un druide utilise emprise de la nature, un joueur utilise une auto sur lui, le joueur en question se retrouve sarment pendant 10 sec et 1 stack sur 3 du buff d'emprise de la nature est consommé sur le druide.
Ensuite, disons pour l'exemple, 2 secondes plus tard, le joueur est encore sarment 8 sec (10-2), il utilise à nouveau une auto attack sur le druide, il consomme alors un deuxième stack d'emprise de la nature et son debuff de sarment passe de 8 sec à 5 sec.

Et c'est bien ça le problème, il vous embrouille en parlant de DR mais osef du DR, ofc l'emprise de la nature crée un DR de root. Par exemple si une personne prend un root à cause de l'emprise de la nature, il est root 10 sec, il se dispell il reprend un root à cause de l'emprise, il est à nouveau root mais 5sec (à cause du DR).

Le problème en l’espèce, c'est que la consommation d'un 2ème stack du buff emprise de la nature, alors que le PREMIER ROOT EST ENCORE ACTIF, refresh le sarment avec application du DR hors il ne devrait pas refresh le debuff si le root toujours actif.

Comportement attendu : (je reprend l'exemple du début)

Un druide utilise emprise de la nature, un joueur utilise une auto sur lui, le joueur en question se retrouve sarment pendant 10 sec et 1 stack sur 3 du buff d'emprise de la nature est consommé sur le druide. (jusque là ok)
Ensuite, disons pour l'exemple, 2 secondes plus tard, le joueur est encore sarment 8 sec (10-2), il utilise à nouveau une auto attack sur le druide, il consomme alors un deuxième stack d'emprise de la nature, SAUF que le debuff du root ne passe pas à 5 sec, il reste à 8sec (si il a pas été retiré entre temps ofc)

Pour conclure, le fait de faire proc d'autres stack d'emprise de la nature ne réduit pas la durée du sarment du premier stack si il est toujours actif, mais il consomme les stack de l'emprise de la nature ofc

**Comment by Ischjgt** [comment]
Oui, c'est ok. Tenez au courant à la prochaine mise à jour svp
