### ISSUE TITLE
Tempête de lames

### ISSUE THREAD

**Issue by drizz3r** [way-of-elendil/3.3.5#887]
**Description**
On peut se faire slow sous tempête de lames, hors on ne devrait pas pouvoir être slow sous ce sort

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- warrior
- Race
- Spécialisation
- tempête de lames
- Circonstances (Donjon, Raid, PvP, autre)
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
essayer en duel vs un mage il arrive à vous slow de temps en temps mais pas facile à reproduire 

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Fournissez des liens vers forums / woehead / wowhead / vidéos / guides / etc qui pourraient aider a confirmer qu'il s'agit d'un bug et a corriger le problème. Notez bien que l'officiel étant maintenant sur une version supérieure a 3.3.5, il est utile de vérifier la date de l'information, afin d'assurer qu'elle correspond a notre version. Notez que bien qu'un lien vers un serveur prive est utile, il ne peut pas être utilise comme preuve de la présence / absence d'un bug.

**Comment by Ischjgt** [comment]
Pas réussi à reproduire.
Par contre quand le joueur qui 46924 [Tempête de lames] reçoit un 42842 [Eclair de givre], le sort passe en buff pour le war

Il doit être insensible.

Autre chose, les débuffs qui slow sont censés partir quand la tempête de lames se lance
https://www.youtube.com/watch?v=IijlbG7yrlc&t=32s
1:45, début du plan à l'arène de Dalaran, on voit le poison Affaiblissant qui se dissipe au lancement de la tempête

**Comment by joshwhedon** [comment]
Poison affaiblissant n'a qu'un seul attribut, le slow. De ce fait, quand l'effet de slow est retire, l'ensemble de l'aura est retiree. Dans le cas de Frostbolt, il a le slow, ET un effet de reduction de soin auquel la tempete n'immunise pas, donc frostbolt n'est pas retire entierement.
Le seul bug du coup c'est le fait que le sort passe en buff.
