### ISSUE TITLE
[LFG] Profondeurs de Rochenoire

### ISSUE THREAD

**Issue by Myster79** [way-of-elendil/3.3.5#889]
**Description**
Dans le donjon "Profondeurs de Rochenoire - Ville haute" après l'event du 2ème boss (Tragi'rel) on doit passer une porte mais celle ci est fermée parce qu'il nous faut une clef

**Étapes de reproduction**
- Donjon : Profondeurs de Rochenoire - ville haute
- Niveau de difficulté 5 joueurs
- Boss : Tragi'rel

**Comportement attendu**
Normalement la porte derrière ce boss doit s'ouvrir quand on clic dessus après qu'on l'ait vaincu. Et seulement en recherche de groupe. Parce que normalement, il faut prendre une quête quand on est mort à un PNJ qui se trouve avant le donjon et le mob à tuer est quant à lui est pratiquement à la moitié de l'instance. Ce qui fait qu'il nous est impossible de terminer cette partie de l'instance.

**Ressources additionnelles**
Mode normal : 
https://wowclassic.judgehype.com/database/fr/item/11000/cl%C3%A9-ombreforge/ => 3ème commentaire explique tout

Mode recherche de groupe : 
https://www.youtube.com/watch?v=NcdC1ZkBSQQ => la porte à 4'48
La vidéo est plus vielle que la 3.3.5 mais quand je le faisais à cette époque c'était la même chose que la vidéo

**Comment by Pixel-woe** [comment]
@joshwhedon En mode solo, ce qui est normal, il faut la clé après l'évent. En recherche de donjon ilne devrait pas demander la clé puisque le donjon est découpé en plusieurs parties lors de la recherche de groupe. Sur officiel il est fort probable qu'il ne requiert pas la clé. Je ne peux pas vérifier sur offi par moi même malheureusement.
Qu'en est il pour le coup ?

**Comment by joshwhedon** [comment]
Oui oui, j'ai mis un correctif qui fait que si on tue le boss en mode LFG, la porte est unlock. Mais uniquement en recherche de donjon. Groupe normal / solo, il faut la clef par contre.
La video semble assez clair sur le sujet, et meme si c'est avant la 3.3.5 je doute que ca ait change.

**Comment by Pixel-woe** [comment]
Ok @joshwhedon  j'avais mal lu désolé
