### ISSUE TITLE
Quest: La rétribution

### ISSUE THREAD

**Issue by piotte62** [way-of-elendil/3.3.5#891]
Bonsoir, la quête buggue aprés avoir parlé à thorim il se place face au vide donne 3,4 phrases et là plus rien il ne combat pas Loken, rien ne se passe!
![WoWScrnShot_062020_225048](https://user-images.githubusercontent.com/67047230/85211346-83e40f00-b348-11ea-8824-983bb38ecaf8.jpg)

**Comment by Ischjgt** [comment]
>Thorim crie : Lève-toi et viens m'affronter, misérable traître !

_Rien_

>Thorim dit : Je t'interdis de…
>Thorim dit : Prononcer…
>Thorim dit : Son nom !!!

https://youtu.be/rk7LIMa-kyc

Aussi, Veranus est hostile au joueur et n'accompagne pas Thorim

Name: Veranus Entry: 30420.
Name: Thorim Entry: 30399.
Name: Loken Entry: 30396.

**Comment by joshwhedon** [comment]
Ca a l'air de marcher maintenant. Veranus j'y touche pas, c'est un script sql l'event, si je touche a un truc prochain merge si ils y touchent ca va tout casser encore.

**Comment by Ischjgt** [comment]
Même problème
