### ISSUE TITLE
Attrapper les torches

### ISSUE THREAD

**Issue by Myster79** [way-of-elendil/3.3.5#892]
**Description**
Quand on lance la torche, elle va directement au sol. on ne peut pas courir derrière en suivant l'ombre pour essayer de valider la quête. c'est la même chose pour le HF Jongleur

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Emplacement : Sur toutes les capitales horde. Je ne sais pas si c'est pareil pour l'alliance
- Elfe de sang paladin
- Attraper les torches + HF Jongleur
- Sur toutes les capitales

**Comportement attendu**
Normalement, quand on lance la torche, on doit voir une ombre au sol pour pouvoir la suivre mais celle ci va directement au sol

**Ressources additionnelles**
Quête attraper les torches : https://www.youtube.com/watch?v=SEWpad1H3xI

**Comment by yakikaru** [comment]
Normalement, tu peux aussi suivre la torche en l'air mais le décor (bâtiment/arbre...) peut masquer la caméra du joueur et donc louper la quête/HF

**Comment by joshwhedon** [comment]
Je fais un reboot demain ca devrait regler le soucis.

**Comment by yakikaru** [comment]
super merci !

**Comment by Theralion** [comment]
Je ne sais pas si le reboot est passé ou pas (je n'ai pas l'impression car pas de changelog), mais le soucis est toujours présent actuellement

**Comment by Ischjgt** [comment]
Tu peux le voir dans le canal status sur Discord.
Le commentaire de Josh est daté 13h11 21 juin, l'uptime du serv est de +de 24h.
Je pense qu'il parlait de la nuit prochaine.

**Comment by Theralion** [comment]
J'ai eu le temps d'essayer avant l'instabilité de ce matin (mais post release), et lorsque lancées sur nous, les torches sont lancées au sol et non en l'air, nous les ramassons immédiatement, impossible de faire le HF

**Comment by Theralion** [comment]
Par contre ça marche bien pour la quête "attraper les torches" maintenant, c'est juste les torche de jonglage utilisées pour le HF Jongleur qui ne partent pas en l'air, mais directement au sol

**Comment by Ischjgt** [comment]
https://youtu.be/AGMWPHNkv6E
1. Les torches ne partent pas en l'air lorsqu'elles sont lancées près du joueur. elles doivent s'élever comme le montre la vidéo.
2. Le HF peut être validé dans tout Dalaran, également Aire de Krasus, Place Tisserune, la zone du Fort Pourpre (là où se déroule la vidéo) etc, ici il ne peut être validé que dans la zone où il y a écrit Dalaran en haut de la minimap

Pour info le HF est faisable.

**Comment by joshwhedon** [comment]
Le 2 je corrige. Le premier probleme j'y peux rien.

**Comment by Theralion** [comment]
Effectivement, c'est que je n’étais pas dans une zone marquée dalaran, c'est pour ça que mon HF ne se validait pas, sinon oui effectivement, le HF est bien faisable même si les torches ne partent pas en l'air
