### ISSUE TITLE
BUG GARGOUILLE DK IMPIE

### ISSUE THREAD

**Issue by Artyclouseau** [way-of-elendil/3.3.5#893]
**Description**
Quand on invoque la gargouille et qu'elle commence à incanter son sort "Frappe de la gargouille", on observe une latence entre chaque sort comme si elle attendait la fin d'un GCD.

**Étapes de reproduction**
- DK
- ORC
- IMPIE
- Invocation d'une gargouille
- Talents classique d'un impie : 0 / 17 / 54
- En toutes circonstances d'après mes premières vagues de tests
- Seulement les buff relatifs au DK impie et à sa spécialisation (Serres de glaces notamment)

**Comportement attendu**
La gargouille devrait enchaîner ses sorts dès qu'elle a fini le précédent car il n'y a pas de GCD sur le sort de la gargouille "Frappe de la gargouille" comme le montre votre DATABASE (voir lien plus bas). Il faudrait donc remédier à ce problème qui réduit les dégâts de cette invocation et donc des DK impies en général

**Captures d’écran / Vidéos**
Voici l'enregistrement de ma gargouille sur Way of Elendil : https://youtu.be/8CdacV6cqPM
Comme on peut le voir à l'image la gargouille fait une pause entre chaque sorts.
Pour illustrer mon propos j'ai fait un test sur un autre serveur : https://youtu.be/Pkpvj4qJPLk
On voit bien ici que la gargouille enchaîne ses sorts sans pause.
De plus si on regarde les Skada à droite de l'écran on voit que la deuxième gargouille (sur l'autre serveur) fait plus d'attaques bien qu'elle ai un temps d'incantation plus long (1.2 sec) alors que celle de Way of Elendil le lance plus rapidement (0.9 sec).

**Ressources additionnelles**
Voici les trois liens qui représente le chemin sur la DATABASE pour arriver au sort "Frappe de la gargouille" et bien voir dans la description du sort qu'il n'y a pas de GCD.
Invocation d'une gargouille : https://woehead.way-of-elendil.fr/?spell=49206
Gargouille d'ébène (invocation réalisé avec le sort précédent) : https://woehead.way-of-elendil.fr/?npc=27829#controlled-abilities
Frappe de la gargouille (attaque du monstre précédent, lui-même invoqué avec le sort précédent) : https://woehead.way-of-elendil.fr/?spell=51963#see-also

**Comment by Justforsoloq** [comment]
T'as pas lu les tickets correctement.
https://github.com/way-of-elendil/3.3.5/issues/636

**Comment by Artyclouseau** [comment]
L'autre serveur n'est pas une référence mais seulement un exemple de non-gcd je dis pas que c'est ça mais alors d'ou vient ce temps d'attente sachant que la gargouille n'a pas de GCD

**Comment by Justforsoloq** [comment]
J't'ai link un ticket, prends le temps de le lire

**Comment by Artyclouseau** [comment]
Je l'ai lu mais il n'y a pas d'indication de la hâte que possédait le DK sur Rétail ni sur WOE ainsi que le nombre de Gargouilles.

**Comment by joshwhedon** [comment]
Le sujet a ete longement discute dans le ticket precedent (et sur discord). Les logs officiels permettent de determiner que non seulement la gargouille est limitee a un certains nombre d'attaques par invocation, mais aussi que la hate affecte ces attaques, et qu'il y a toujours un petit temps entre ces attaques permettant a la gargouille de parfois placer des coups en melee (comme indique par les logs). Est-ce que c'est blizzlike ? On ne peut en etre sur, mais c'est ce qui se rapproche le plus niveau comportement. A moins de fournir des informations officielles precises sur le sujet, le comportement actuel restera.
