### ISSUE TITLE
Appel du maître - chasseur

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#894]
**Description**
Le sort appel du maître du chasseur ( id 53271 ) ne retire pas le débuff d'éclair de givre ( id 42842 ) ni celui de cône de froid ( id 42931 ) des mages.
Non seulement le débuff n'est pas retiré mais le chasseur subit en plus le ralentissement occasionné par les 2 débuffs même si il est sous l'effet d'appel du maître.

**Comportement attendu**
Le familier dissipe les sorts affectant le déplacement ( hébétements exclus ) incluant donc les 2 débuffs au-dessus

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Master%27s_Call

Patch 3.2.2 (2009-09-22): This ability now correctly removes the snaring component of Infected Wounds, Frostfire Bolt, and Slow.

**Comment by joshwhedon** [comment]
J'ai teste, et le fonctionnement est correct. Notez bien le patchnote : 
Patch 3.2.2 (2009-09-22): This ability now correctly removes the snaring component of Infected Wounds, Frostfire Bolt, and Slow.
Uniquement le snare est retire. Appel du maitre ne retire pas l'ensemble du debuff, parce que le trait de givre a aussi un debuff de reduction de heal. En gros, ca retire un effet, mais pas l'aura elle meme.
