### ISSUE TITLE
Quest: Enquête dans les catacombes des Amani

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#896]
**Description**
https://woehead.way-of-elendil.fr/?quest=9193
Impossible de valider la condition "Enquêter dans les catacombes des Amani"

**Comportement attendu**
https://youtu.be/J7LF99tzedk
Le crédit se fait à 3:28

**Comment by Killyana** [comment]
Passes ça juste une fois, je retire le mauvais script avec un prochain commit sur tc:
``` sql
DELETE FROM `areatrigger_scripts` WHERE `entry`=4071;
DELETE FROM `smart_scripts` WHERE `entryorguid`=4071 AND `source_type`=2;

**Comment by joshwhedon** [comment]
MErci
