### ISSUE TITLE
Spell: Poison de distraction mentale

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#9]
**Description**
https://woehead.way-of-elendil.fr/?item=5237 , s'applique sur les Boss
serveur prod + test

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- prendre un voleur
- mettre https://woehead.way-of-elendil.fr/?item=5237 sur une arme
- taper un boss

**Comportement attendu**
Mind-numbing poison doesn't work on most bosses, but notable exceptions are as follows;
Pathaleon The Calculator
Reliquary of souls
Blindeye the seer

**Ressources additionnelles**
https://wowwiki.fandom.com/wiki/Mind-numbing_Poison_(item)

**Comment by joshwhedon** [comment]
Meme probleme que pour malediction des langages. Sera corrige prochaine mise a jour.
