### ISSUE TITLE
Spell: Essaim d'insectes géants

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#90]
**Description**
Putricide guntlet avec les insectes: le spell https://woehead.way-of-elendil.fr/?spell=70475 si je me trompe pas, doit ignorer le los et avoir une plus grande porté, et tant pis s'il y'a des zones ou sa se cumule.
aura appliqué à :
SpawnID: 201423, current GUID low: 843.
SpawnID: 201361, current GUID low: 847.
Entry: 38879.

**Comment by joshwhedon** [comment]
J'augmente le radius un peu (je peux pas mettre le radius par defaut c'est 500 donc ca va se cumuler partout :D .
