### ISSUE TITLE
Boss: L'Assemblée de fer - Boss Undermap

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#900]
**Description**
Name: Stormcaller Brundir
Entry: 32857. 

Constaté en 10. Pas réussir à reproduire.
Il a undermap, il y avait encore des boss de présent.

**Comment by joshwhedon** [comment]
Y'a aucun probleme avec le script, et rien qui puisse le faire undermap. Impossible de reproduire  le probleme.

**Comment by Ischjgt** [comment]
**Étapes pour reproduire**
<img width="1187" alt="Capture d’écran 2020-06-26 à 16 16 06" src="https://user-images.githubusercontent.com/60295792/85867024-9a66ec00-b7c8-11ea-8f24-414e21f0c7d2.png">
- 1 joueur A dans la zone rouge qui tank les 3
- 1 joueur B dans la zone verte
- A vire sa menace, B choppe les boss
=> Les boss passent dans le décor et undermap

**Comment by joshwhedon** [comment]
Soucis de map, on y peut rien a moins que des nouvelles maps reglent le probleme chez Trinity.
