### ISSUE TITLE
" lancer plus de torche " événement solstice

### ISSUE THREAD

**Issue by hermes-gm** [way-of-elendil/3.3.5#901]
Quand on fait la quête journalière de l'evenement du solstice " lancer plus de torche " ( https://woehead.way-of-elendil.fr/?quest=11921 ) normalement le poteau sur lequel on doit lancer la torche à une marque rouge.
J'ai testé à forgefer et ca donne ça :
https://screens.way-of-elendil.fr/wnYEyQwj.jpg
Il y a plusieurs marque en même temps.

**Comment by joshwhedon** [comment]
Je peux pas rescript pour qu'il y en ait qu'un a la fois (beaucoup trop chiant a gerer). J'ameliore pour qu'il y en ait un peu moins a la fois.
