### ISSUE TITLE
Boss: Algalon l'Observateur

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#902]
**Description**
Name: Algalon the Observer
Entry: 32871.

Si tout le monde passe dans l'autre phase en prenant le trou noir, le boss reset.

Phase du trou noir : 16

(Testé en 10)

**Comportement attendu**
Entrer dans le trou noir reset la menace, pas le combat.

**Comment by joshwhedon** [comment]
J'augmente le timer un peu pour qu'il reset pas.

**Comment by joshwhedon** [comment]
En fait pas un bug.

**Comment by Ischjgt** [comment]
Il n'y a pas ce spell https://woehead.way-of-elendil.fr/?spell=64487

**Comment by Ischjgt** [comment]
Je réouvre je sais pas si t'as vu mon commentaire.
Je peux pas voir si le boss cast https://woehead.way-of-elendil.fr/?spell=64487 ou si il passe pas les phases,
mais le raid reste indemne si tout le monde va dans les trous noirs et le boss reset

If everyone enters the Black Holes and Algalon has no player in the normal realm to target, he kills the raid with Ascend to the Heavens, then disappears (=> reset)

**Comment by joshwhedon** [comment]
J'ai teste, apres les modifs que j'ai faites pour augmenter un peu les timers il le fait bien. Mais ca one shot pas ca fait juste enormement de degats.
