### ISSUE TITLE
Porte Kirtonos à Scolomance

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#904]
Bonjour.
Lors d'un donjon tourisme (Lv80), j'ai tué Kirtonos.
L'invocation se passe parfaitement, la porte se ferme, parfait.
Sauf qu'une fois mort, la porte ne s'est jamais ré-ouverte :D
J'ai donc du TP, bisous :)

**Comment by Ischjgt** [comment]
(https://github.com/way-of-elendil/3.3.5/issues/776)
