### ISSUE TITLE
Pénitence dp en marchant

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#905]
**Description**
La pénitence continue d'être cast même en marchant

**Étapes de reproduction**
Prenez un dp, lancez pénitence, attendez d'avoir le premier tick puis marchez partout et regardez.

**Comportement attendu**
La pénitence comme toute canalisation s'arrête quand on bouge

**Ressources additionnelles**
https://db.rising-gods.de/?spell=53007

**Comment by joshwhedon** [comment]
Bah ... je sais pas si tu lag ou quoi, mais moi ca affiche un gros Interrupted et ca arrete la canalisation.

**Comment by Ischjgt** [comment]
.cas 47540 avec n'importe quel classe
Il faut bouger au moment ou tu cast le spell

**Comment by joshwhedon** [comment]
Ca m'est arrive une fois sur 10, c'est lie a https://github.com/way-of-elendil/3.3.5/issues/547
Va falloir vous decider, c'est soit un bug soit l'autre.

**Comment by Ischjgt** [comment]
Je sais pas, moi j'ai aucun problème pour reproduire et je peux attendre pas mal de temps avant de bouger.
Et c'est une situation qui peut arriver assez souvent.
@Justforsoloq c'est la première fois que tu remarques ça ?

**Comment by Justforsoloq** [comment]
Nop, j'avais déjà tiqué un peu en arène mais là c'était vraiment évident.
J'vous upload une vidéo que je viens de faire qui montre un peu la chose : 

https://drive.google.com/file/d/1H96xy8su3NcvIUgosudNtLb8ekAYyfki/view?usp=sharing

**Comment by sithis2a** [comment]
Just héberge tes vidéos sur https://streamable.com/ surtout si elles sont courtes :)
Là en plus sur ton drive il nous faut te faire une demande d'autorisation.

**Comment by Justforsoloq** [comment]
https://streamable.com/w6pv55

**Comment by Ischjgt** [comment]
Aussi Josh, le ticket https://github.com/way-of-elendil/3.3.5/issues/547 fait référence à toutes les canalisations alors que là ça à l'air bien propre à la pénitence. Je peux pas faire ça avec l'évoc l'incandescence etc

**Comment by Justforsoloq** [comment]
Yep j'ai testé avec fouet mental/incandescence etc et ça ne le fait pas du tout.

**Comment by joshwhedon** [comment]
Ca change pas le fait que l'autre ticket a cause ce probleme. Donc il faut choisir, c'est soit l'un, soit l'autre. L'autre ticket desactive l'interruption sur certains mouvements, ce sont ces interruptions qui font que penitence est normalement interrompu. Le systeme compense un "lag" client / serveur pour permettre d'interrompre des sorts malgres les lags / petits mouvements cote joueur.
Donc, avec le fix que j'ai fait ces lags se ressentent beaucoup plus.

**Comment by Justforsoloq** [comment]
Tant pis alors, je pense que l'autre ticket est plus important que celui là en terme expérience de jeu (un sort qui s'arrête est plus ennuyant qu'un sort qui continue)

**Comment by joshwhedon** [comment]
Personnellement ayant beaucoup de mal a reproduire en local, ca montre que le soucis est lie directement ou indirectement a la latence.

**Comment by Traesh** [comment]
fixé prochaine maj
