### ISSUE TITLE
NPC: Skar'this the Summoner

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#907]
**Description**
Name: Skar'this the Summoner
Entry: 40446.
Instance: les enclos aux esclaves

Je me rappelle avoir vu passer un ticket comme ça il y a quelques temps mais je ne le trouve plus.
Le NPC level 80 est là pour les bas levels qui font l'instance aussi et ça galère.

**Comment by Killyana** [comment]
On peut rien y faire, les boss d'évent comme Ahune sont spawn dans la difficulté normal du donjon.

**Comment by Killyana** [comment]
En faite on peut le mettre en tant que civilian, il n'aggro que s'il est attaqué, sa colle plus avec l'event vue qu'il canalise sur le cristal, et une fois aggro il dit : "Comment osez-vous ?! Vous n'empêcherez jamais la venue du seigneur Ahune !"
``` sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|2 WHERE `entry`=40446;
