### ISSUE TITLE
Boss: Le roi-liche - ICC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#908]
**Description**
36597

Cas où les joueurs qui ont vaincus le boss ne reçoivent pas Haut-fait, emblèmes, loots etc

**Étapes de reproduction**
Testé en 10
- 2 joueurs A et B
- A tank le boss
- passer le boss à 10% et attendre la fureur de deuilegivre
- A déco (toujours avec l'aggro
- finir le boss
=> Pas de crédit du down, loots etc

**Comment by joshwhedon** [comment]
Le comportement me semble parfaitement normal. Il n'y a aucune raison pour un joueur deconnecte d'obtenir haut faits ou autres recompenses.
La solution est simple : ne pas deco.

**Comment by joshwhedon** [comment]
Pas compris qu'aucun joueur n'obtient de recompense, je pensais que c'etait juste le joueur deco.

**Comment by Ischjgt** [comment]
C'est arrivé tout à l'heure en 25nm

**Comment by joshwhedon** [comment]
J'arrive pas a reproduire quel que soit le mode. Je mets une autre modif. Sinon vous pouvez aussi essayer d'avoir un raid lead qui deco pas, ca aide.

**Comment by Ischjgt** [comment]
C'est pas le Raid Lead, c'est le MT1.
Ton correctif est passé en 10 mais pas en 25NM

**Comment by joshwhedon** [comment]
Non mais le correctif est pas en 10 ou en 25, le correctif s'applique a tout.

**Comment by gtschanz** [comment]
bah ce soir ça l'a fait, le mt1 il est mort à 3% du boss et ensuite il est partie dormir vu qu'on arrivait à le finir sans lui et ça l'a fait bug, pourrait-on envisager une autre solution en attendant que tu ''solutionne'' ce problème c'est à dire de reset le boss en question ce qui serait en toute légitime, vu qu'il a été down de façon régulière quit à le refaire de manière à récupérer ses récompenses

**Comment by gtschanz** [comment]
car je suis même pas sûr qu'il avait une assistance pour te dire, il n'était en tout cas pas raid lead et encore moins master loot la personne qui est partie
