### ISSUE TITLE
dégâts trash archavon 25

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#909]
![Capture d'écran 2020-06-27 01 59 51](https://user-images.githubusercontent.com/63243193/85909391-e7bf7980-b819-11ea-8c61-42360bced3ed.png)

j'ai mangé un 100 -> 0 avec les stats suivantes se référer à la capture d'écran et j'étais en présence de givre; est-ce normal ? (simple interrogation; je sais pas si c'est normal ou élevé) car ça m'a os (et c'était des trashs; le boss ne me fait 0 dégâts en comparaison

**Comment by joshwhedon** [comment]
Si t'etais tout seul, probablement normal. Ce sort fait des degats partage a 2 cibles. Donc si tu es tout seul tu prends le double des degats normaux.
