### ISSUE TITLE
kalegos plateau de puis de soleil raid bc

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#910]
Bonjour, 

ça fait plusieurs semaine post merge qu'on fait chaque semaine le plateau de puits de soleil chaque semaine on reste chaque fois bloqué sur kalegos car depuis la merge il n'est plus script (il n'y a plus d'invocation du démon dans la salle du bas) et chaque semaine (depuis 4 semaine) on doit appeler un mj pour qu'il vienne nous permettre de le passer;

Serait-il possible de re-script ce boss ?

Merci par avance

**Comment by Ischjgt** [comment]
Je réouvre ici https://github.com/way-of-elendil/3.3.5/issues/627

**Comment by Ischjgt** [comment]
Aussi, note bien que c'est la première fois que j'entends parler de ce soucis depuis le ticket que j'ai link le 1er mai.
