### ISSUE TITLE
Boss : Valithria Marcherêve

### ISSUE THREAD

**Issue by Krunkss** [way-of-elendil/3.3.5#911]
**Description**
Le temps de repop des stacks en mode Héroïque est trop lent.
**Étapes de reproduction**
Prendre les stacks dans les portails en mode 10 où 25Hero, redescendre et remonter lors des portails suivants, les stacks pris lors des premiers ne réapparaissent pas.

**Comportement attendu**
Entre deux prises de portails les stacks sont sensés réapparaitre progressivement suivant l'ordre où on les a pris.

**Captures d’écran / Vidéos**
https://www.youtube.com/watch?time_continue=6&v=Yfr2nowQ7DI&feature=emb_logo
Vidéo de valithria sur officiel par la guilde Raunchy

https://clips.twitch.tv/TriangularGorgeousBillANELE
Vidéo du même boss sur Way of elendil.

On peut voir sur la vidéo d'officiel qu'entre 1:30 où les heals commencent a prendre les portails pour la première fois et 2:15 où ils les prennent pour la deuxième fois, les stacks pris précédemment commencent à réapparaitre. 
On peut même voir a 2:19 un stack entrain de repop.

Sur la vidéo de WOE on peut voir qu'entre la première prise au début de la vidéo et la deuxième à 0:45 les stacks pris précédemment n'ont même pas commencés à réapparaître.

Le souci n'est pas présent en mode Normal, cependant.

**Comment by Ischjgt** [comment]
10HM et 25HM
https://youtu.be/Yfr2nowQ7DI
Les Nuages cauchemardesques ne respawn toujours pas après l'arrivée des nouveaux portails.

**Comment by joshwhedon** [comment]
Correctif prochaine maj

**Comment by Eryinnn** [comment]
Toujours pas fixé

**Comment by joshwhedon** [comment]
C'est le meme temps de respawn en normal et en heroique maintenant. DSonc je vois pas le probleme.

**Comment by joshwhedon** [comment]
Ok j'ai trouve le soucis.
