### ISSUE TITLE
mecanique de deplacement de boss "pousser" absente ou bugger

### ISSUE THREAD

**Issue by Hydro-woe** [way-of-elendil/3.3.5#912]
1) Lorsque la personne qui a l'agro d'un mob/boss se rapproche du centre de la hit box de celui ci le mob/boss est censé reculer pour que son animation d'attaque corresponde mieux au placement (sans toutefois que cela pertube son autohit ou ses technique) et représente une mécanique de placement de boss avec une grande hitbox plus "safe" que de "tirer" celui ci en le retournant au préalable.

2) Cette mécanique est il me semble présente sur le jeux mais avec un porté extrêmement faible qui la rend inapplicable (testé sur thrym en zul'drak, tique a l'entré des grottes du temps, les garde des ossements (cf vidéo) a la couronne de glace et différent boss de raid).

3) Le comportement attendu est visible de 3.00 a 3.44 sur cette vidéo : https://www.youtube.com/watch?v=KmOPuziOWuA
et visible sur boss de raid pour confirmé les dire du tuto entre 0.19 et 0.24 sur cette vidéo : https://www.youtube.com/watch?v=RSbBt9NHsXE

**Comment by Killyana** [comment]
Sa sera implémenté par Trinity prochainement™
