### ISSUE TITLE
luciole farouche

### ISSUE THREAD

**Issue by Hydro-woe** [way-of-elendil/3.3.5#913]
lié au : https://github.com/way-of-elendil/3.3.5/issues/724

**Description**
La luciole farouche n'est plus applicable si un equi avec le talent luciole amélioré a déjà posé sa luciole (la partie importante est dans la preuve vidéo vu qu'elle présente la manière de fonctionné normal et donc potentiellement la manière de résoudre le problème)  
**Étapes de reproduction**
lancer n’importe quelle luciole après qu’un equi ai posé sa luciole amélioré

**Comportement attendu**
La luciole farouche en ours est censé être toujours applicable (c'est pour cela qu'elle fait des dégâts et que son script comporte une agro augmenté su les ratio de dommage).
deux débuff son censé être cumulable sur le boss comme présenté dans ces vidéo : 
paragon vs lk 25H tankPOV : https://www.youtube.com/watch?v=UJz6R18A5u8&feature=youtu.be    (3.51)
tankspot tuto lk 25 : https://www.youtube.com/watch?v=CVLSV7EL3Hc&t=132s       (1.30)

ajout:  il est visible sur les 2 vidéos que le debuff luciole est présent en double ce qui pourrait montrer que : 
-Ou la luciole amélioré n’applique pas les effets en 1 seul debuff mais en 2 et permet l’application de toute les autre lucioles qui serve donc a refresh la partie classique de la luciole
-Ou la luciole farouche et la luciole sont considéré comme 2 debuff différent et dans ce cas les debuff sont cumulé ... ce qui semble complètement craqué

**Comment by discipleofbeer** [comment]
Bonjour, le problème a t'il été identifié ? (Je demande car il n'y a pas de réponse)
Car c'est assez gênant, on perd un de nos moyens de monter notre aggro dès qu'il y a une chouette dans le groupe.

**Comment by joshwhedon** [comment]
Je dirai que dans l'immediat va falloir faire avec, parce que j'arrive pas a faire que les debuff se stack sans que leurs effets se stackent.

**Comment by gtschanz** [comment]
![complémentaire](https://user-images.githubusercontent.com/63243193/100966822-20ccea00-352e-11eb-992f-1ad17911b031.PNG)
j'ai vu que tu m'a redirigé vers ce bt @joshwhedon ; voici l'image de complément; y'a-t-il du nouveau à ce sujet ?

**Comment by joshwhedon** [comment]
Non

**Comment by Hydro-woe** [comment]
Bonjour à tout les présent du topic,

J'ai peut être trouver la solution pour le bug lucioles.
en repartant du fait que plusieurs debuff sont applicable comme visible sur les vidéo et en considérant le fait que faire stacker les debuff luciole par le nounours et l'equi sans qu'il se cumule est difficile/impossible je me suis intéressé à la mécanique du talent enflammer du mage (https://woehead.way-of-elendil.fr/?spell=12654)  
Je pense que le debuff 3% toucher du au talent équi est possible a trigger comme un second debuff comparable a l'enflammer ce qui permettrai le refresh du debuff de base de la luciole possible a lancer par les chaton/nounours et semble correspondre avec le double effet de debuff visible sur les vidéo mentionner plus haut (car le probleme de ces vidéo c'est que l'on ne vois a aucun moment l'effet du debuff :/ seul l’icône de la luciole est visible en double)

Je ne sais pas si c'est réalisable ni blizzlike quoi que rien ne prouve le contraire et cela permettrai de rendre sa mécanique d'aggro au drood.

**Comment by Hydro-woe** [comment]
Bonjour, 
Comme je n'ai pas de nouvelles je relance un peu dailleur j'ai pu observer que sur la première vidéo linké plus haut entre 6.56 et 6.57 on peu observer un des deux débuff luciole se refresh sans que l'autre ne varie (tout en bas a droite des débuff ça refresh et tout en bas a gauche ça ne bouge pas).

du nouveau la dessus ? des tests en cour ? des interrogations ? un besoin d'un eventuel coup de main ?
@joshwhedon

**Comment by joshwhedon** [comment]
Pas de nouveau, pas moyen de corriger ce bug sans en introduire d'autres, du fait que le debuff de luciole ne doit pas se stack avec des debuffs de type equivalent.

**Comment by leodium** [comment]
Bonjour ... 

Est-ce que un fix a été trouvé pour ce bug ?

**Comment by leodium** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24592 ?

**Comment by Ferro-woe** [comment]
Rappel des sorts actuels :
[Lucioles](https://woehead.way-of-elendil.fr/?spell=770) commune à tous les druides
[Lucioles (farouche)](https://woehead.way-of-elendil.fr/?spell=16857) uniquement en Forme de félin, Forme d'ours, Forme d'ours redoutable ; écrase [Lucioles](https://woehead.way-of-elendil.fr/?spell=770)
Lucioles améliorées [Rang 1](https://woehead.way-of-elendil.fr/?spell=33600) [Rang 2](https://woehead.way-of-elendil.fr/?spell=33601) [Rang 3](https://woehead.way-of-elendil.fr/?spell=33602) uniquement pour un spé équilibre (chouette) ; écrase toutes les autres

Aujourd'hui, l'ours ne peut pas utiliser ses [Lucioles (farouche)](https://woehead.way-of-elendil.fr/?spell=16857) par dessus [Lucioles améliorées](https://woehead.way-of-elendil.fr/?spell=33602) ce qui lui pose des problème en raid 25, et ça ne devrait pas être le cas.

Dans la [vidéo](https://www.youtube.com/watch?v=CVLSV7EL3Hc&t=132s) donnée en source par [Hydro-woe](https://github.com/Hydro-woe) on voit clairement 2 débuff appliqués sur la cible.
Sur Woe nous n'en avons qu'un seul.


Du coup pour résoudre ce problème, il faut 2 débuff différents
1- Le premier qui applique [Lucioles](https://woehead.way-of-elendil.fr/?spell=770)
_Réduit l'Armure de la cible de 5% pendant 5 min. Tant qu'elle est affectée, la cible ne peut pas se camoufler ni devenir invisible._
Modifiable par [Lucioles (farouche)](https://woehead.way-of-elendil.fr/?spell=16857) uniquement

2- Le second qui applique l'amélioration
_Votre sort Lucioles augmente aussi les chances que la cible soit touchée par les attaques avec les sorts de **1/2/3%** ainsi que vos chances de coup critique avec les sorts infligeant des dégâts sur les cibles affectées par Lucioles de **1/2/3%**._
en fonction des différents rangs

Ce qui donnerait pour :
- [Lucioles](https://woehead.way-of-elendil.fr/?spell=770) aucun changement
- [Lucioles (farouche)](https://woehead.way-of-elendil.fr/?spell=16857)  aucun changement
- Lucioles améliorées [Rang 1](https://woehead.way-of-elendil.fr/?spell=33600) [Rang 2](https://woehead.way-of-elendil.fr/?spell=33601) [Rang 3](https://woehead.way-of-elendil.fr/?spell=33602) ajout sur la cible ennemie de [Lucioles](https://woehead.way-of-elendil.fr/?spell=770) ET d'un second débuff à créer
1- pour [Rang 1](https://woehead.way-of-elendil.fr/?spell=33600)
_Votre sort Lucioles augmente aussi les chances que la cible soit touchée par les attaques avec les sorts de **1%** ainsi que vos chances de coup critique avec les sorts infligeant des dégâts sur les cibles affectées par Lucioles de **1%**._
2- pour [Rang 2](https://woehead.way-of-elendil.fr/?spell=33601) (modifie [Rang 1](https://woehead.way-of-elendil.fr/?spell=33600))
_Votre sort Lucioles augmente aussi les chances que la cible soit touchée par les attaques avec les sorts de **2%** ainsi que vos chances de coup critique avec les sorts infligeant des dégâts sur les cibles affectées par Lucioles de **2%**._
3- pour [Rang 3](https://woehead.way-of-elendil.fr/?spell=33602) (modifie [Rang 1](https://woehead.way-of-elendil.fr/?spell=33600) et [Rang 2](https://woehead.way-of-elendil.fr/?spell=33601))
_Votre sort Lucioles augmente aussi les chances que la cible soit touchée par les attaques avec les sorts de **3%** ainsi que vos chances de coup critique avec les sorts infligeant des dégâts sur les cibles affectées par Lucioles de **3%**._

Avec cette méthode, ça devrait fonctionner pour tout le monde et réglerait ce problème.
Biz.

**Comment by Endalaust** [comment]
Tous les retours sur ce sujet sont attendus. Il est probable que le bug soit fixé mais que sa résolution introduise f'autres bugs sur le cumul d'auras. Faites nous signe pour tout constat en ce sens ce jour, merci

**Comment by Wilpok** [comment]
> Tous les retours sur ce sujet sont attendus. Il est probable que le bug soit fixé mais que sa résolution introduise d'autres bugs sur le cumul d'auras. Faites nous signe pour tout constat en ce sens ce jour, merci

Le comportement est normal vous pouvez le fermer
