### ISSUE TITLE
Probleme de compte ? ( druide, [toucher guérisseur] Heal ANORMAL (valeur basse)

### ISSUE THREAD

**Issue by Salamandar1** [way-of-elendil/3.3.5#915]
**Description du problème** 

J'ai effectué des tests avec plusieurs personnes dont certaines étaient de mon niveau (40)  et il s’avère que mon sort [Toucher Guérisseur]  à une valeur anormale en comparaison aux autres joueurs, et notamment le rang 7 qui est le dernier que je dispose pour mon niveau et donc je vous présente celui-ci de manière explicite dans les captures d'écrans.

  **Détail et explicatif** 

Je vous présente donc deux captures d'écrans, une de "moi-même" et une autre d'un "joueur test" qui a accepté de me consacrer du temps. 
Les tests ont étés réalisés sans aucun équipement afin qu'il ne puisse pas y avoir de statistique prise en compte et pour mettre en avant la valeur brute du soin.
J'ai ouvert mon grimoire lors de l'utilisation pour que vous pussiez y voir le rang et le joueur test quand à lui le montre directement via sa barre de sort.

  **Autres**

J'ai fait des tests sur le sort [Récupération] ainsi que le sort [Rétablissement] et je n'ai constaté aucune anomalie, nous avions bien les mêmes valeurs brutes avec les autres joueurs.
A signaler que je pensais au départ que le problème venait du fait que j'ai rejoint le serveur en utilisant la racine de jeu d'un autre serveur mais il s’avère que même après suppression totale du dossier et réinstallation sur le site Way of Elendil le problème persiste.

**Comment by Salamandar1** [comment]
![Mon personnage ( valeur anormale)](https://user-images.githubusercontent.com/67529944/85937613-73fa9b00-b905-11ea-868d-2980206f3925.png)
![Joueur TEST](https://user-images.githubusercontent.com/67529944/85937617-7a891280-b905-11ea-90da-31cbc458cd70.jpg)

**Comment by joshwhedon** [comment]
Il est extremement peu probable qu'il y ait un bug lie a votre personnage (ou au sort). Rien ne pourra etre fait depuis le bugtracker, il est preferable que vous fassiez un ticket en jeu afin un membre de l'equipe regarde votre personnage.

**Comment by Xblugs** [comment]
On voit sur le screen que le temps d'incant est pas le même, tu dois avoir la glyphe de toucher guérisseur qui réduit le temps d'incant mais qui réduit aussi le heal produit
