### ISSUE TITLE
Guide de la récupération de tissu

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#916]
Pouvez vous limiter la possibilité de loot [Guide de la récupération de tissu dans le Grand Nord] aux couturiers svp ?
Ou bien donner la valeur de 1cu à l'objet pour que nous puissions le revendre facilement.

https://woehead.way-of-elendil.fr/?item=43876

D'avance merci.

**Comment by joshwhedon** [comment]
Est-ce qu ca peut etre loot uniquement par les couturiers sur offi ?
