### ISSUE TITLE
RAID BC / Karazhan / Partie d'echec

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#918]
Bonjour,

il semble que la partie d’échec de Karazhan ne fonctionne pas correctement. les différents CD de replacements et autres actions ne sont pas présent, les pièces peuvent se placer a plusieurs sur une même case, et le boss alliance (nos sommes Horde) se regen full life a chaque fois que ça vie est au plus bas. Tout ceci empêche de compléter cette évènement, et debloquer les loots associé.

Merci,
Bonne journée.

**Comment by joshwhedon** [comment]
L'event sera mis a jour prochaine mise a jour. Pas 100% blizzlike parce que beaucoup d'info manquante mais ca devrait etre mieux.
