### ISSUE TITLE
Chasseur / Heal du pet et Aggro

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#920]
Bonjour,

Bug encore présent.
Exemple, on lance le pet dans une zone avec des mobs, ils aggro.... le chasseur lance le soin du familier, quand le chasseur utilise la technique les mob viennent sur lui, puis sans rien faire de plus, au premier tic de heal sur le familier, tout les mob aggro vont sur le familier directement. Et je pense que chaque tic renforce l aggro du pet, meme sur des mobs au quel il n'aurai infligé aucun degat, ceci assez pour qu'un heal joueur, puisse heal sans aggro. 

L'aggro généré est puissante, puisqu'il arrive que le heal du pet par le chasseur, reprenne l'aggro en instance aussi .

Je peux vous organiser une démonstration si vous voulez.

Merci a vous,
Bonne journée.

**Comment by joshwhedon** [comment]
J'ai teste a nouveau, que ce soit hors instance ou en instance. J'ai des mobs sur moi, j'utilise Mend Pet, le pet ne reprend jamais l'agro, a aucun moment.
Impossible de reproduire ce probleme de mon cote. Donc va falloir que vous voyez avec un gm en jeu, a premiere vue y'a aucun soucis avec Mend Pet et l'agro genere. 
D'ailleurs tu peux faire l'experience. Fais que ton pet recoit des degats (les heals doivent etre effectifs pour que l'agro face quelque chose), utilise Mend Pet, regarde le % d'agro que tu as sur le mob, et il augmente.

**Comment by Ischjgt** [comment]
**Étapes pour reproduire**
- Chassou sans talent avec n'importe quel pet, **avec 43350 - [Glyphe de guérison du familier]** (c'est le responsable)
- Se balader dans une instance avec le pet avec yeux de la bête par exemple, en allant aggro tous les mobs sans générer davantage de menace
- Quitter les yeux de la bête, le pet revient pres du chasseur, à ce stade là tous les mobs sont sur le familier
- Quand les mobs sont assez près du joueur, lancer guérison du familier
=> Le joueur prend l'aggro au lancement du sort, Au premier tick, le familier reprend l'aggro
