### ISSUE TITLE
[Ecaille du crépuscule pétrifiée] Erreur tooltip bijou

### ISSUE THREAD

**Issue by TrucEtrange** [way-of-elendil/3.3.5#922]
Bonjour,

**Description**
Le tooltip de la scale affiche un proc de 733 d'armure. Hors le proc donne 733 d'esquive.

**Étapes de reproduction**
Équiper l'écaille du crépuscule pétrifiée, observer ses statistiques d'esquive et d'armure.
Se faire frapper et passer sous les 35%, afin d'activer le proc.

**Comportement attendu**
Le tooltip du bijou et le tooltip du proc devraient correspondre, et annoncer un gain d'esquive en cas de proc.

**Captures d’écran / Vidéos**
Sur la première capture, on peut voir mon armure et mon esquive unbuff.
![ArmureEsquiveUnbuff](https://user-images.githubusercontent.com/45370942/86279061-b3610a00-bbd9-11ea-9947-f58e9f198e9c.jpg)
On peut voir le détail du tooltip du bijou, qui annonce un gain d'armure en cas de proc.
![tooltipBijou](https://user-images.githubusercontent.com/45370942/86279054-b22fdd00-bbd9-11ea-99cf-101da2248ced.jpg)
On peut voir le détail du tooltip du proc, qui annonce un gain d'esquive. On peut constater que mon esquive est montée d'environ 10%, ce qui confirme que ce tooltip est correct.
![tooltipProc](https://user-images.githubusercontent.com/45370942/86279057-b2c87380-bbd9-11ea-8c2b-81e8d62d85ac.jpg)

**Ressources additionnelles**
On retrouve le même problème sur Woehead. Le bijou annonce un gain d'armure, l'effet invoqué également, mais le buff correspondant au proc augmente l'esquive.
https://woehead.way-of-elendil.fr/?item=54571
https://woehead.way-of-elendil.fr/?spell=75475
https://woehead.way-of-elendil.fr/?spell=75477

Sur ce wiki, le tooltip annonce bien un gain d'esquive.
https://wowwiki.fandom.com/wiki/Petrified_Twilight_Scale

Bonne journée

**Comment by joshwhedon** [comment]
Ouai, et en anglais c'est correct aussi. On dirait une erreur de traduction chez blizzard. Dans le cas present, les donnees textes des sorts proviennent des donnees client (si ca avait ete l'objet qui avait une mauvaise traduction on aurait pu corriger), du coup on ne peut pas les corriger. Techniquement c'est un bug blizzlike :D .

**Comment by TrucEtrange** [comment]
J'ai trouvé ça assez perturbant quand j'ai eu le bijou, et que j'ai vu un proc de 733 d'armure, c'est absolument nul x)

Merci pour les détails en tous cas !

**Comment by joshwhedon** [comment]
Oui c'est assez peu courrant. Le pire c'est que le proc lui meme a la bonne traduction, mais pas l'aura sur l'objet.

**Comment by Kwyzard** [comment]
techniquement tu peux le corriger non si tu modifie un de test mpq nah ? (coté client obviousement)
