### ISSUE TITLE
Peste dévorante améliorée sur totems ne marche pas

### ISSUE THREAD

**Issue by Justforsoloq** [way-of-elendil/3.3.5#923]
**Description**
La peste améliorée du prêtre ne marche pas sur les totems (on ne peut donc pas les casser via une peste)

**Étapes de reproduction**
Prenez un sp et un chaman faites un duel, essayez de faire votre peste sur un totem et voyez que le totem n'est pas affecté

**Comportement attendu**
Les dégâts brut de la peste améliorée doivent casser le totem (si il n'a pas d'absorb > aux dégâts).

**Ressources additionnelles**
https://db.rising-gods.de/?spell=63627

**Comment by joshwhedon** [comment]
Va falloir prouver qu'elle est suppose marcher. Les totems sont immunise a peste devorante, donc la peste devorante ne touche jamais, du coup peste devorante amelioree de n'applique jamais et n'inflige aucune degat (vu que la peste devorante amelioree elle meme inflige des degats basee sur le dot).
J'ai cherche un peu partout, je trouve rien concernant peste devorante amelioree et le fait que ca devrait proc si il y a immunite.
Merci de demander une reouverture du bug si vous avez des sources indiquant que ca devrait etre different, merci de commenter et je reouvrirai le bug, mais base sur le comportement actuel, ca semble normal.

**Comment by Justforsoloq** [comment]
Alors effectivement les totems sont des aoes. Mais il me semblait que le 'on-hit' de devouring plague est compté comme à part du dot : https://www.mmo-champion.com/threads/646929-Random-Imp-DP-Misses/page2
X hits Y for Z with Improved Devouring Plague.
Y is affected by Devouring Plague.
Y takes W damage from Devouring Plague.

Ps : C'est chiant j'ai un topic qui a l'air de parler du sujet avec des ref offi mais le topic en lui même ne s'ouvre plus (même dans wayback il est n'est pas référencé rip): 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiAssqc2LDqAhUOTsAKHferBJIQFjAAegQIBhAB&url=https%3A%2F%2Fwww.bountysource.com%2Fissues%2F83781247-totem-immune-to-imp-devouring-plague&usg=AOvVaw2ma_Pfq5Snptbo6TXe_1sL
"But when imp. devouring plague hits any totem dropped from shaman, it does ... So no, totem immune to Improved Devouring Plague is not blizz-like behavior ... quoted post is from 2010 and Wotlk release was in 2008 therefore references must" (c'est dans l'en-tête sur la page google)

**Comment by Justforsoloq** [comment]
Après je ne trouve pas de sources plus conclusives que ça donc à moins qu'on arrive à ouvrir le deuxième lien on va pouvoir fermer le sujet

**Comment by joshwhedon** [comment]
Bah, le truc c'est que la facon dont le proc d'improved devouring plague est calcule, c'est X% des degats infliges par le dot. Du coup, si le dot inflige pas de degats, ce serait X% de 0. Mais oui techniquement il est a part du dot, mais malgre tout il faut toucher pour que ca proc (genre tu vas pas proc sur un miss / evade / etc).
Et oui le bountysource j'ai tente d'y trouver des references aussi, mais pas reussi a trouver quoi que ce soit.
Honnetement je sais pas quel est le comportement normal attendu, j'ai cherche un peu partout et c'est un comportement tres specifique donc difficile de trouver quelque chose sur le sujet, surtout apres 10 ans :(.

**Comment by Justforsoloq** [comment]
Oui je me doute, on peut fermer le sujet je pense, si jamais je trouve une vidéo/topic qui montre que c'était avéré j'updaterais de toute façon
