### ISSUE TITLE
shards démo

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#924]
sur la caninière ICC 25 Normal mode j'étais en démo spécialisation démonologie en elfe de sang femelle; j'ai essayé de faire du drain dame sur les ads de la canonnière et j'ai reçu 0 shards sur tout le fight de la canonnière même quand les ads sont mort. ce qui n'est pas normal vu qu'ils sont lvl 82 et donc ''donne'' de l'expérience.

**Comment by Killyana** [comment]
Je crois ,que c'est fixé par https://github.com/TrinityCore/TrinityCore/commit/e3bac11837741518479e9e09a99980366f1a64ae comme tout les autres procs. (les pnj avec le flags extra=64 ne faisaientt pas proc les sorts et les talents avant ce commit.

**Comment by joshwhedon** [comment]
Ouai ca devrait etre fixe prochain merge d'ici quelques semaines.
