### ISSUE TITLE
B0SS LK ICC 25 NORMAL MODE -- Sévérité Sévère

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#925]
@joshwhedon (concernant le premier paragraphe) @staff pour les 2 autres paragraphes

Le MT1 leave le raid sur lk; on tue le boss; aucun loot ne tombe et le boss est mort; serait-il possible de Script cela car de 1 c'est pas un comportement normal blizzard (qui plus est le perso qui a leave n'était pas masterloot et encore moins même assistant...) et de 2 cela vient, pour une erreur de script, de pénaliser 25 joueurs.. id 1264.. même si cela ne change rien à l'absolue que je link le numéro de l'id - ou du moins convenir un reset du boss / des boss en questions à l'avenir en laissant la possibilité de le ''re try'' (ce qui serait légitime au vue du contexte pour les raids suivants qui seraient impactés par le même soucis) - si cela n'était pas ''scriptable''.

merci par avance de faire le nécessaire;

Néanmoins je voudrais insisté sur un point personnel concernant cette requête, un tel soucis ''énerve'' les joueurs si la seul réponse obtenue, est, venant du staff ''vous le tomberez la semaine prochaine je vois pas où est le problème'' link sur l'interfaction par une personne représentative du staff (je conçois que les propos des joueurs n'étaient peut être pas appropriés à la demande initiale et que le comportement de certains était fortement exagéré (parlant des joueurs)! 

Toutefois la réponse émanant du staff à ce propos manque de ''compréhension'' et fortement de ''takt''.. (sachant que je pense que les joueurs présent ici ne veulent pas du ''mal'' au serveur - mais que des réponses formulés ainsi qui représente le staff à travers l'un de ses membres ne produirait que l'effet inverse escompté - des joueurs plus ''salé'', qui provoque inutilement et dont cela se termine par des mutes / ban (certes justifiés, mais qui n'amélioreront rien..) ou qui dans un autre cas ''leave'' le serveur et je pense que rentrer dans un tel cercle vicieux n'est pas bon pour la communauté que représente ce serveur). - ce que je regrette fortement et à tout les niveaux!

**Comment by Ischjgt** [comment]
https://github.com/way-of-elendil/3.3.5/issues/908
