### ISSUE TITLE
Instance/Event: Sindragosa Guntlet

### ISSUE THREAD

**Issue by Killyana** [way-of-elendil/3.3.5#93]
**Description**
L’évent ne se lance pas

**Étapes de reproduction**

- Donjon ICC
- Niveau de difficulté toutes

**Comment by Killyana** [comment]
Npc trigger toujours pas spawn

**Comment by Endalaust** [comment]
https://github.com/joshwhedon/WayOfElendil/blob/merge/sql/updates/woe/post_merge.sql#L100-L140

A la demande d'Eridium j'ai passé ce SQL pour qu'il soit embarqué dans la release de cette nuit à 6h. Merci d'en tenir compte dans l'historisation git ;)
