### ISSUE TITLE
[Quête] Rallier les troupes - mobs au comportement erratique

### ISSUE THREAD

**Issue by Rolirolant** [way-of-elendil/3.3.5#930]
Plusieurs bugs sur cette quête. Elle reste faisable, mais franchement, il n'y a rien d'amusant à essayer de contourner les bugs.
L'objet de quête fonctionne mais ne comptabilise que de manière semble t'il aléatoire (à moins que ça ne compte que les géants qui sont en combat?). Les taupes supposées être le moyen de transport des nains pour arriver sur place poppent mais rien n'en sort sauf coup de bol magistral

Tous les mobs concernés par cette quête (https://woehead.way-of-elendil.fr/?quest=12070) ont un comportement bizarre - que ce soient les géants des grisonnes (https://woehead.way-of-elendil.fr/?npc=26261) ou les géants runifiés (https://woehead.way-of-elendil.fr/?npc=26417) qui s'aggro sans se battre (d'où problème si seuls les géants en combat comptent pour la quête) ou les vengeurs rune de fer (https://woehead.way-of-elendil.fr/?npc=26786) qui ne pop que sur coup de bol.

Faut la tester pour comprendre, c'est assez difficile d'expliquer.

**Comment by joshwhedon** [comment]
Il faut effectivement utiliser l'objet que sur les geants en combat, vu qu'il faut rallier les troupes qui combattent.
Je modifie un peu les timers de respawn.
