### ISSUE TITLE
Karazhan - TP vers Bibliotheque

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#932]
Bonjour,

Le portier à l'entrée de Karazhan peut tp les personnes dans la bibliothèque d'Aran lorsque celui ci a été tué, permettant de gagner un temps précieux lors des soirées wipe sur les boss suivants.

Ceci n'est pas fonctionnel sur le serveur.

Merci,
Bonne journée.

**Comment by Killyana** [comment]
Fixé par https://github.com/TrinityCore/TrinityCore/commit/1837013c07fb2bd0706be31c22ce371177545535
