### ISSUE TITLE
bug perte pet chasseur

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#933]
je pense qu'il doit y avoir un ticket encore ouvert à ce sujet, je ne l'ai pas trouvé et le bug est encore présent.

On perd régulièrement nos pets chasseur suite à un soucis avec l'écurie, ça arrive très souvent si le pet est mort qu'on fait pas gaffe qu'on passe à l'écurie et qu'on passe le pet mort sur le pet vivant; en soit s'il fallait uniquement ''rechercher'' le pet ça irait à la limite encore; MAIS il faut le repex de 5 level puis lui réapprendre des talents et si on a la malchance d'avoir un pet un peu particulier il est chiant à chercher.

exemple, j'ai un loup blanc du bg vallée d'alterac car c'est le skin loup que je préfère, résultat je suis ''baisé'' jusqu'à l'ouverture d'un bg altérac qui n'arrive pas 1x par semaine en général et faut être connecté à ce moment...

Par rapport à ça pourrait-on à minima envisager une récupération des pets si on retourne le chercher et qu'il soit direct level 80 sans avoir à pex les 5 level.. en particulier si le chasseur qui va le chercher est level 80 ? - (car un hunt ne change pas x fois de pet si le chasseur est level 80 - là je me retrouve 1x toute les 2 semaine (environ) à devoir re - aller chercher un pet (le pet pvp ou pve) et perdre 1h chaque fois inutilement pour un bug désagréable non blizz; c'est histoire de pas perdre chaque fois **minimum** 1h à bash des mobs pour l'avoir à nouveau 80....

De plus pourrais-tu m'indiquer ou l'on trouve le pet du bg d'altérac dans la nature sinon ? je ne l'ai trouvé sur aucun guide (le pet loup blanc, merci par avance

**Comment by joshwhedon** [comment]
Deja signale, et on y peut pas grand chose dans l'immediat.
https://github.com/way-of-elendil/3.3.5/issues/24
Et aucune idee pour le pet du bg d'alterac, mais normalement tu peux utiliser woehead ou wowhead pour trouver les mobs avec le meme display.

**Comment by gtschanz** [comment]
@joshwhedon : "Par rapport à ça pourrait-on à minima envisager une récupération des pets si on retourne le chercher et qu'il soit direct level 80 sans avoir à pex les 5 level.." -> dans le post d'avant car c'est très très désagréable de devoir repex toute les 2 semaines 5 level soit 1 à 2h de bash mobs...

**Comment by gtschanz** [comment]
et suggestion à @Endalaust : ça serait sympa de répertorier les skin des potentiels familiers de chasseur sur le woehead à travers une image du pet potentiel en question pour accompagner le texte, ça sera plus parlant

**Comment by Endalaust** [comment]
Il me semble que n'importe qui peut créer un compte sur woehead et envoyer un screen en suggestion
J'ai pas testé depuis le redéploiement de woehead cela dit
