### ISSUE TITLE
Bug pet BG

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#935]
petit doute de ma part, mais les pets ne sont-il pas supposé être rez avec leur maitre dans les bg ? (il me semblait que c'était le cas sur offi d'époque) j'ai essayé de trouver des infos mais je n'ai rien trouvé et dans les vidéos offi que j'ai chercher, les gens ont ''cut'' quand ils die

**Comment by joshwhedon** [comment]
Bah j'ai beau teste, et moi mon pet est tout le temps ressucite quand le gardien des ames me ressucite en bg. J'ai teste toutes les combinaisons possibles (mourrir avec le pet vivant, mourrir avec le pet mort, mourrir avec le pet despawn suite a sa mort, etc), et quelle qu'elle soit, mon pet respawn quand le gardien me ressucite.

**Comment by gtschanz** [comment]
mon pet en question est un ravageur lvl 75 (car je dois le récupérer permanence level  75 vu avec l'autre (bug) je le cherche à la péninsule des flammes infernales et je joue une chasseresse elfe de sang et je te promet que si mon pet est dead bah il resspawn jamais en vie; y'aurait-il d'autres chasseur pour donner leurs point de vue ?
