### ISSUE TITLE
bug talents familiers chasseurs férocité -> réflexes du cobra

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#936]
What it should do - It should increase your pets attack speed by 15% each rank and reduce the pets base damage by 7.5% each rank.

What it currently does - Currently it does increase the attack speed correctly but it is also reducing the damage by 15% each rank resulting in a dps loss (see screenshot)

No Cobra Reflexes taken:

![Capture d'écran 2020-07-06 05 10 43](https://user-images.githubusercontent.com/63243193/86552029-15f23700-bf47-11ea-901c-e4abe73e40cb.png)

Cobra Reflexes Taken:

![Capture d'écran 2020-07-06 05 10 32](https://user-images.githubusercontent.com/63243193/86552045-20143580-bf47-11ea-91bd-3e71d9eeafda.png)

As you can see from the ingame dps the pet loses around 6 dps at my level from just taking the talent. The actual dps of the pet should not go down by taking this talent, the only thing that should change is that each hit will be weaker but the pet hits more to compensate.

-> j'ai testé sur le serveur woe avec les données affichés. De plus ça parait fortement improbable que de prendre un talent qui est supposé augmenter le dps du pet on se retrouve avec un dps qui DIMINUE ! et ça diminue les damages un peu plus de 30% même.

De plus cet éléments est un indicateur qui peut expliquer que la spécialisation beast master qui s'appuie beaucoup sur les dégâts du familier subit un nerf qui ne devrait pas être ! (les autres spécialisation subissent également un nerfs mais c'est plus ''supportable'' vu que le pet ne représente qu'une petite partie du dps en précis par exemple. Mais le nerf est là alors qu'il ne devrait pas l'être !

(anecdote: un bt d'un autre private (certainement) m'a mis la puce à l'oreille et on retrouve également les mêmes valeurs qu'ils avaient.) 

voici mes sources:

lien d'un ancien bt (celui qui m'a mis la puce à l'oreille):
https://github.com/dalaranwow/dalaran-wow/issues/1585

talent qui existe sur offi sous vanilla / bc (avant que ça passe dans les talents des pet en 3.0.2) - on voit bien dans les commentaires en anglais qu'ils parlent d'une augmentation de dps et non d'une diminution en donnant un exemple:

https://classic.wowhead.com/spell=25076/cobra-reflexes#comments

**Comment by gtschanz** [comment]
j'ai pas trouvé d'autres topic sur le net pour justifier, mais il me parait très net qu'un talent d'augmentation de dps ne doit pas au final se retrouver à diminuer le dps !

**Comment by gtschanz** [comment]
dsl d'être ''chiant'' puis-je considérer ce sujet comme clos genre sera fixé ou manque de preuve et je dois encore aller chercher un complément d'information ?

**Comment by joshwhedon** [comment]
Oui corrige prochaine maj, si je mets pas un tag sur le ticket c'est qu'il est / sera corrige.
