### ISSUE TITLE
Bug Quête Samophange (Taride), les valves ne sont pas utilisables

### ISSUE THREAD

**Issue by Feutil** [way-of-elendil/3.3.5#937]
Bonjour,

Lors de la quêtes Samophange dans les Tarides, il faut fermer trois valves de contrôle. Ces valves ne sont pas interactives, on ne peut pas cliquer dessus, ce qui empêche de finir la quête.

Pour reproduire le problème, il faut être de la faction Horde, et prendre la quête Samophlange auprès du PNJ Sputtervalve à Cabestan. La première quête demande juste d'accéder à la Console de contrôle au Centre de recherches de la KapitalRisk. Pas de souci ici, c'est la quête suivante qui bug, donné par cette même Console de contrôle. 

Normalement, les trois valves (situé sur les machines autour de la Console de contrôle) doivent être fermées pour terminé la quêtes, mais elles ne sont pas utilisable. 

Liens vers wowhead : quête initial : https://fr.classic.wowhead.com/quest=894/samophlange
                                   quête suivante bugué :  https://fr.classic.wowhead.com/quest=900/samophlange

Merci d'avance

Feutil

**Comment by Killyana** [comment]
Sera fixé avec https://github.com/TrinityCore/TrinityCore/issues/24952

**Comment by Killyana** [comment]
Sinon il suffit de s’éloigner jusqu'à plus voir les valves puis revenir, ils vont devenir cliquable

**Comment by Ferro-woe** [comment]
Réalisée il a y un mois environ (personnage alliance).
Une déco-reco m'a permis de faire cette quête, sans supprimer le cache.
Biz.
