### ISSUE TITLE
Quest: Les œufs maléfiques

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#939]
**Description**
23749 - [Capitaine Adams] 
https://woehead.way-of-elendil.fr/?quest=11157

Y'a-t-il un prérequis pour lancer la suite de quête ?
Le Capitaine Adams ne la propose pas

**Comment by Killyana** [comment]
Elle a 11157 comme prérequis, mais sa s'affiche pas dans le woehead, je ne sais pas pourquoi
![image](https://user-images.githubusercontent.com/6587064/86600027-c0964400-bf9f-11ea-8fba-592c1c5894e3.png)
