### ISSUE TITLE
bug zone under map

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#941]
![Capture d'écran 2020-07-07 02 50 54](https://user-images.githubusercontent.com/63243193/86678336-c0786180-bffc-11ea-8c58-c2322c460775.png)
![Capture d'écran 2020-07-07 02 50 44](https://user-images.githubusercontent.com/63243193/86678354-c4a47f00-bffc-11ea-95b8-0f8031bddac9.png)
![Capture d'écran 2020-07-07 02 50 36](https://user-images.githubusercontent.com/63243193/86678361-c53d1580-bffc-11ea-9d2f-feaff7463d4c.png)

il faut lire les images de bas à en haut; vous allez au niveau de la statue à dalaran (côté bdg h2) puis devant ce banc, vous avancer de 2 à 3 pas, vous cliquer sur le banc du côté droit et peut importe la classe avec laquelle vous êtes 100% vous allez undermap (à priori ça le fait aussi sur d'autres bancs dans cette zone). Ce glitch ''undermap'' n'existait pas sur offi

**Comment by joshwhedon** [comment]
Le bug a deja ete signale et sera corrige.
