### ISSUE TITLE
Boss: Thaddius - Naxxramas

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#942]
**Description**
15928 - [Thaddius] 
15930 - [Feugen] 
15929 - [Stalagg] 
Si tous les joueurs libèrent après un wipe sur Thaddius alors que le boss n'est pas réapparu, l'instance est bloquée avec "Impossible de changer de zone en cours de rencontre."

Il suffit qu'un MJ entre dans l'instance avec l'ID des joueurs bloqués pour que le soucis soit réglé.
Attendre le respawn du boss sans libérer permet d'éviter ce problème

**Étapes de reproduction**
- Groupe de raid 10/25
- Clean les boss avant Thaddius dans le Quartier des Assemblages
- Aggro Feugen ou Stalagg
- Mourir et libérer aussitôt
=> instance bloquée

**Comment by Killyana** [comment]
Faudra faire gaffe en corrigeant ça, avant sa causait un crash lié au set active: https://github.com/TrinityCore/TrinityCore/commit/1c833f28e471e3787f1d328e44af5f065ad9ca8c
