### ISSUE TITLE
[PNJ] Il marche au lieu de nager

### ISSUE THREAD

**Issue by Endalaust** [way-of-elendil/3.3.5#944]
Le pnj https://woehead.way-of-elendil.fr/?npc=28003 marche sur l'eau au lieu de nager, c'est très perturbant visuellement

**Comment by Killyana** [comment]
Pas facile à corriger https://github.com/TrinityCore/TrinityCore/issues/21872

**Comment by joshwhedon** [comment]
J'ai essaye de bidouiller un peu les templates pour que le visuel rende mieux, pas reussi a le faire nager. Je pense que comme dit Eridium c'est lie a ce bug de Trinity.
J'y peux pas grand chose.
