### ISSUE TITLE
[Quête "Le doux son du tonnerre"] L'event dans la grotte ne se lance pas

### ISSUE THREAD

**Issue by heavyisnotdead** [way-of-elendil/3.3.5#945]
**Description**
Une fois dans la grotte, avec le costume de golem, aggro des mob et l'event ne se lance. La quête ne peut donc être validée

**Étapes de reproduction**
- Fjord Hurlant
- Humaine mage
- Le doux son du tonnerre
- Donneur de quête: Walt, à l'avant poste de la ligue des explorateurs du Fjord Hurlant

**Comportement attendu**
Une fois le costume de golem enfilé, on doit pouvoir descendre dans la grotte sans aggro les mobs grâce à un sort de camouflage. Lorsque l'on arrive à la statue de Titan, un event doit se lancer. 

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?quest=11495

**Comment by Ischjgt** [comment]
La quête est faisable néanmoins
https://github.com/way-of-elendil/3.3.5/issues/822

**Comment by joshwhedon** [comment]
J'ai ete voir, la quete fonctionne. Devant la statue dans la grotte, un event se declenche quand on y passe. Par contre il y a un petit cooldown entre le declenchement des events, du coup si quelqu'un vient de le faire, il faut attendre quelleques minutes (4 ou 5) pour qu'il respawn.

**Comment by Babyface-187** [comment]
Testé la quête : 
L'event se lance bien, cependant la quête n'est pas validée

**Comment by Amilgaull** [comment]
Petite mise à jour concernant ce soucis, le fait d'entrer en combat avec un mob autre que les nains de fer a pour conséquence de rendre les nains hostiles et donc de devoir retourner chercher un assemblage. 
Exemple de mob posant ce soucis dans la zone : 
à l'entrée de l'excavation
Name: Shoveltusk Stag
15:52:54 SpawnID: 108709, current GUID low: 17075.
15:52:54 Entry: 23691.
15:52:54 Faction: 1886.
15:52:54 NPC Flags: 0.
15:52:54 DisplayID: 22131 (Native: 22131).
15:52:54 Spawn group: Dynamic Scaling (Quest objectives) (ID: 2, Flags: 9, Active: 1)
15:52:54 Compatibility Mode: 0
15:52:54 Level: 69.
15:52:54 EquipmentId: 0 (Original: 0).
15:52:54 Health (base): 7984. (max): 7984. (current): 7984.
15:52:54 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
15:52:54 Unit Flags: 32768
15:52:54 * UNIT_FLAG_SWIMMING (0x8000)
15:52:54 Unit Flags 2: 2048.
15:52:54 Dynamic Flags: 0.
15:52:54 Faction Template: 1886.
15:52:54 SpawnTime: Full:5m Remaining:0s
15:52:54 Loot: 23691 Pickpocket: 0 Skinning: 70202
15:52:54 InstanceID: 0
15:52:54 Phasemask: 1
15:52:54 Armor: 6423
15:52:54 Position: 456.205566 -5816.686035 304.448181.
15:52:54 AIName: SmartAI ScriptName: 
15:52:54 React state: AGGRESSIVE
15:52:54 Active AI: SmartAI
15:52:54 Flags Extra: 0
15:52:54 MechanicImmuneMask: 0
15:52:54 dmg_multiplier: 1.000000
Ainsi que : 
Name: Rampaging Earth Elemental
15:53:11 SpawnID: 98000, current GUID low: 95418.
15:53:11 Entry: 24340.
15:53:11 Faction: 1932.
15:53:11 NPC Flags: 0.
15:53:11 DisplayID: 22675 (Native: 22675).
15:53:11 Compatibility Mode: 0
15:53:11 Level: 70.
15:53:11 EquipmentId: 0 (Original: 0).
15:53:11 Health (base): 8982. (max): 8982. (current): 8982.
15:53:11 Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
15:53:11 Unit Flags: 32768
15:53:11 * UNIT_FLAG_SWIMMING (0x8000)
15:53:11 Unit Flags 2: 2048.
15:53:11 Dynamic Flags: 0.
15:53:11 Faction Template: 1932.
15:53:11 SpawnTime: Full:5m Remaining:0s
15:53:11 Loot: 24340 Pickpocket: 0 Skinning: 0
15:53:11 InstanceID: 0
15:53:11 Phasemask: 1
15:53:11 Armor: 6719
15:53:11 Position: 287.128967 -5769.660645 260.014465.
15:53:11 AIName: SmartAI ScriptName: 
15:53:11 React state: AGGRESSIVE
15:53:11 Active AI: SmartAI
15:53:11 Flags Extra: 0
15:53:11 MechanicImmuneMask: 0
15:53:11 dmg_multiplier: 1.000000
à plusieurs endroits dans l'excavation.

L'utilisation du sort https://woehead.way-of-elendil.fr/?spell=44608 sur une plateforme prévue à cet effet comme celle ci : 
 Map: 571 (Norfendre) Zone: 495 (Fjord Hurlant) Area: 3996 (Excavations de Baelgun) Phase: 1
15:50:58 X: 283.263153 Y: -5759.046875 Z: 268.456390 Orientation: 3.620431
15:50:58 grid[32,21]cell[4,1] InstanceID: 0
15:50:58  ZoneX: 72.134483 ZoneY: 70.285980
15:50:58 GroundZ: 222.413513 FloorZ: 268.456299 Have height data (Map: 1 VMap: 1 MMap: 1)
rend les nains hostiles à l'arrivée, rendant impossible la suite de la quête.

https://woehead.way-of-elendil.fr/?spell=44609 n'a aucun effet

**Comment by joshwhedon** [comment]
On y peut rien il faut faire avec.
Et le bluff marche, mais il est utilisable que dans des circonstances specifiques.
