### ISSUE TITLE
Item: Flacon du Grand Nord

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#946]
**Description**
47499 - [Flacon du Grand Nord] 
id: 67017 [Flacon du Grand Nord] (bonus pa)

Impossible de tomber sur le bonus 80 pa en drood, qu'elle que soit la morph

**Comment by joshwhedon** [comment]
https://wowwiki.fandom.com/wiki/Flask_of_the_North
Normal
