### ISSUE TITLE
Intéraction corruption/Essence de la reine de sang en démoniste affliction

### ISSUE THREAD

**Issue by toitit** [way-of-elendil/3.3.5#947]
Sur la Reine de sang Lana'thel (tout modes) : 
La corruption du démoniste affliction n'est pas augmentée pas le débuff [Essence de la reine de sang](https://woehead.way-of-elendil.fr/?spell=70879)

Reproduction : démoniste avec le talent Affliction éternelle, se faire mordre sur la Reine.
Normalement, lorsqu'on refresh le dot "à la main" en lançant le sort sur la cible, la corruption appliquée profite du buff Essence de la reine de sang.
Actuellement, il faut attendre que la corruption disparaisse entièrement, puis relancer le sort pour profiter du bonus.

PS : Si on ne refresh pas la corruption "à la main", qui est refresh automatiquement par le talent Affliction éternelle, elle ne bénéficie pas du buff Essence de la reine de sang (comportement normal).
PSS : Je crois que le problème est présent aussi en prêtre ombre avec le mot de l'ombre : Douleur

**Comment by joshwhedon** [comment]
C'est normal, c'est le concept de rolling dots qui existe en 3.3.5. Certains attributs (les modificateurs de degats entre autre) ne sont calcule qu'a l'application des dots, pas au refresh.

**Comment by toitit** [comment]
Ah c'est un problème plus grave en fait je réouvre un autre ticket
