### ISSUE TITLE
Achievement: Increvables/Il en restera plus d'un

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#949]
**Description**
Testé qu'en 10, pas testé immortel

https://woehead.way-of-elendil.fr/?achievement=2187
https://woehead.way-of-elendil.fr/?achievement=2186

Si un joueur rejoint le groupe à n'importe quel moment où le HF est toujours valide, il aura le HF à la fin du raid

**Étapes de reproduction**
-Clean l'instance jusqu'à KT sans mourir
-inviter un joueur dans le raid
-il participe au combat contre KT et à la fin les 2 joueurs choppent l'increvables

**Comportement attendu**
Je sais pas trop mais je pense pas qui soit possible de tuer juste 1 boss et d'avoir l'increvables (le usebug serait de faire tous les boss les plus dur et de laisser Horreb/Maexxna pour la fin à un joueur low gear pour qu'il ait le HF)

**Comment by joshwhedon** [comment]
https://www.wowhead.com/achievement=2187/the-undying#comments
Interesting to note on this, in our group we had a swap mid way through the raid instance, and one of the 10 had not been there for all bosses yet upon killing KT he also got the achievement along with the rest of the raid that had survived death. Used 2 healers(priest/druid) for all encounters up to Saph and KT where we had a moonkin go respec restoration for more assurance.

Pas un bug.
