### ISSUE TITLE
dégâts familier chasseur

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#950]
![Capture d'écran 2020-07-10 17 20 53](https://user-images.githubusercontent.com/63243193/87170572-cbb7df80-c2d1-11ea-8e52-c5bbd38486a9.png)
![Capture d'écran 2020-07-10 17 22 19](https://user-images.githubusercontent.com/63243193/87170693-f7d36080-c2d1-11ea-9ef3-b710c7ee9953.png)

@joshwhedon suite à mon bt semaine dernière sur le talent réflexe cobra les dégâts du pet chasseur ont subit un gros nerf, peux-tu m'expliquer cette différence en 1 semaine? 2 screen à l'appuie aucune statistique n'a changé sur mon hunt entre temps et même si je me buff chasseur (ce que je n'ai pas mis semaine dernière lors du précédent screen j'ai tjr un dps / sec pet nettement inférieur !

**Comment by gtschanz** [comment]
après le talent réflexe cobra est script maintenant, mais il faudrait pas qu'une correction d'un précédent bt nerf les dégâts artificiellement lors d'une correction

**Comment by joshwhedon** [comment]
Y'a eu absolument aucun changement sur les pets depuis 1 mois outre les changements sur reflexe de cobra. J'ai teste en local et aucun soucis de mon cote. Vois avec un mj en jeu pour qu'ils jettent un oeil.
Je remarque que l'endurance de ton pet a change aussi et a augmente donc tu as du avoir des changements sur tes stats auss.

**Comment by gtschanz** [comment]
euh non car j'avais le même stuff c'est à dire full 277 avec les armes 284 unbuff je suis pas débile pour faire les test et y'a eu des changements dans les stats du pet et je sais pas pourquoi...

**Comment by gtschanz** [comment]
je vais attraper un mj dès que j'en vois un
