### ISSUE TITLE
item meurtrissure noire (arme pugilat icc 264 / 277) 

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#951]
![Capture d'écran 2020-07-10 17 33 14](https://user-images.githubusercontent.com/63243193/87172258-3cf89200-c2d4-11ea-9716-c3c0a9af8abb.png)

il y a 2 chose

> l'arme doit pouvoir proc sur les 2 techniques chamélio frappe tempête /  fouet de lave car c'est des attaques de mêlée comme spécifié dans les commentaires; hier soir quand j'ai analysé le dps d'un chamélio je ne l'ai pas vu proc sur ses 2 techniques; je peux continuer à faire des test et chercher davantage sur ça proc;

> De plus je trouvais que le total dps de cette technique est très base sur le skada que j'ai analysé sur un halion 25 nm le chaman à fait 700K en damage mêlée et l'effet n'a fait que 42k alors qu'il aurait ''dû'' 70K car 10% du damage mêlée après il se peut que la fourchette ne soit pas assez représentative et que je fasse des test sur une plus grosse fourchette

source: https://fr.wowhead.com/item=50035/meurtrissure-noire#english-comments

**Comment by gtschanz** [comment]
de plus dans l'ensemble des commentaire les gens s'accordent globalement à dire que ça devrait faire environ 3% du total dps sur un poteau boss; or sur ce que j'ai pu voir hier cette part était plus de 1.3 à 1.5 sur elendil.

![Capture d'écran 2020-07-10 17 56 33](https://user-images.githubusercontent.com/63243193/87174039-e5a7f100-c2d6-11ea-8c2f-82a9a7ae42a3.png)
![Capture d'écran 2020-07-10 17 54 49](https://user-images.githubusercontent.com/63243193/87174040-e6408780-c2d6-11ea-98da-941dc49c060b.png)
![Capture d'écran 2020-07-10 17 54 26](https://user-images.githubusercontent.com/63243193/87174042-e6408780-c2d6-11ea-8907-00935e12bc7c.png)
![Capture d'écran 2020-07-10 17 54 10](https://user-images.githubusercontent.com/63243193/87174043-e6d91e00-c2d6-11ea-80c7-976cc390c2fd.png)
![Capture d'écran 2020-07-10 17 53 51](https://user-images.githubusercontent.com/63243193/87174044-e6d91e00-c2d6-11ea-8451-f2330d137104.png)

**Comment by joshwhedon** [comment]
Un correctif sera applique prochaine maj, devrait augmenter un peu le proc.
