### ISSUE TITLE
XP: Affichage Gray Level

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#952]
**Description**
![Capture d’écran 2020-07-15 à 02 41 05](https://user-images.githubusercontent.com/60295792/87490309-af0b0700-c645-11ea-84df-019c84a877cb.png)

Niveau 56 :
![Capture d’écran 2020-07-15 à 02 40 25](https://user-images.githubusercontent.com/60295792/87490322-b4685180-c645-11ea-991f-998938adae87.png)

Le mob niveau 45, 46, 47 donne quand même de l'XP quand le joueur est du niveau 56 (normal)

**Comportement attendu**
Affichage du niveau du mob en vert ?

**Comment by joshwhedon** [comment]
C'est gere par le client ca. Donc ca doit etre blizzlike
