### ISSUE TITLE
[Karazhan] Non reset de l'évent de l'opéra après un wype

### ISSUE THREAD

**Issue by Gandrayda** [way-of-elendil/3.3.5#956]
**Description**
Lors d'un wype sur l'évent de l'opéra ( dans ce cas c'était Romulo et Julianne ) celui-ci ne se relance pas et reste actif rendant impossible la rentrée dans l'instance , le message " Impossible de changer de zone en cours de rencontre " s'affiche.  J'étais tout seul sur ce try le 2e perso affiché sur l'interface de raid était resté dehors.

**Étapes de reproduction**
Voici exactement ce que j'ai fait 

- Lancer l'évent de l'opéra ( Romulo & Julianne ) 
- Tuer romulo et julianne séparément
- Wype quand les 2 sont réunis
- Liberer et impossible de re-rentrer 

**Captures d’écran / Vidéos**
https://ibb.co/LJB5FC9

**Comment by joshwhedon** [comment]
Corrige prochaine maj

**Comment by Ischjgt** [comment]
En plus de https://github.com/way-of-elendil/3.3.5/issues/1067
Tous les events bloquent l'instance après un wipe

**Comment by Ischjgt** [comment]
Les boss finissent par despawn mais toujours le même message "Impossible de changer de zone en cours de rencontre"
(testé avec Magicien d'Oz et le petit chaperon rouge mais à priori sur Roméo aussi)

**Comment by Ischjgt** [comment]
Je crois que c'est Barnes 16812 qui pose problème
En lançant l'event, il s'habille, après un wipe, il revient à sa position, décalé, toujours habillé
