### ISSUE TITLE
Quest 10821 : You're fired!

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/3.3.5#957]
**Description**
Les obélisques de la Légion ne sont pas cliquables.

**Étapes de reproduction**
Tuer les NPCs 'Anger Guard' pour récupérer 'Camp Anger Key'x5
Les clefs doivent permettre au joueur d'activer les obélisques pour faire avancer la quête. 

test 1 : 3 obélisques active / 2 inactivables
test 2 : 5 obélisques inactivables
test 3 : 4 obélisques active / 1 inactivable

**Comment by Babyface-187** [comment]
test 4 : 5 obélisques activées, mais l'event ne se lance pas

**Comment by joshwhedon** [comment]
@Killyana  tu as une idee par hasard ? Je vois que c'est une smart AI foireuse a premiere vue, le compteur a pas l'air de marcher comme il devrait. D'ailleurs ca se reset pas correctement non plus.

**Comment by Killyana** [comment]
Le problème n'est pas le compteur mais si un joueur n'active pas tout les obélisques, dans ce cas les obélisques qui ont été activé gardent leur flag et donc ne sont plus cliquables
Il faut que tu changes le set flag via gossip hello par un set loot state 2, l'état sera restauré après data3: 120000  Time in ms before the initial state is restored

**Comment by joshwhedon** [comment]
JE vais regarder merci :).
