### ISSUE TITLE
Affichage aura de devotion

### ISSUE THREAD

**Issue by pinvmaster** [way-of-elendil/3.3.5#958]
Pour une aura de dévotion rang 10 le bonus d'augmentation de l'armure est indiqué a 1807 au niveau du grimoire et des boutons de choix, alors qu'il n'est en réalité que de 1205.
![WoWScrnShot_071220_012000](https://user-images.githubusercontent.com/68517416/87885097-72f3ef80-ca13-11ea-89e1-fdcd147ce4b6.jpg)
![WoWScrnShot_071220_012004](https://user-images.githubusercontent.com/68517416/87885099-78513a00-ca13-11ea-8121-0a9c1071574d.jpg)

**Comment by Kwyzard** [comment]
faut regarder au niveau des stats gagner pas de l'affichage

**Comment by joshwhedon** [comment]
Oui comme indique par Kwyzard, blizzard affiche un texte fixe dans les auras, afin de voir le resultat reel, il faut regarder le tooltip de l'aptitude ou les stats elles meme.
