### ISSUE TITLE
Fouet mental : bug sur les ticks de dégâts

### ISSUE THREAD

**Issue by brolkzer** [way-of-elendil/3.3.5#960]
**Description**
Le sort du prêtre ombre fouet mental n'inflige parfois que 2 ticks de dégâts sur 3.

**Étapes de reproduction**
- Prêtre
- Troll
- Ombre
- Fouet mental
- Sur un poteau
- Cap toucher pour casteur : 17% donc 14% avec la misère du prêtre ombre.

**Comportement attendu**
Le fouet mental est un sort de canalisation qui inflige 3 ticks de dégâts à la cible ennemi.
Or, pour une ou des raisons inconnus il n'inflige parfois qui 2 des 3 ticks de dégâts.
Mon personnage a 15% de toucher et ma classe pose la misère qui m'augmente de 3% mes chances de toucher donc je ne peux rater le tick en question. Si le tick était résisté cela serait notifié sur l'input de dégâts.

**Captures d’écran / Vidéos**

https://www.youtube.com/watch?v=mnZ9SjiuLgM&

**Comment by Theralion** [comment]
Pour info les buffs drood équi et sp ne se cumulent pas pour le toucher :

> Cap toucher pour casteur : 17% donc 14% avec la misère du prêtre ombre, 11 si un druide équilibre est présent.

=> ceci est faux, cela reste à 14% même s'il y a un drood équi qui pose son débuff

Après ça ne change rien au niveau de tes tests à priori, si tu as 15%

**Comment by Mugiino** [comment]
Tu prends peut être des dégâts pendant la canalisation ? Si t'as pas un paladin sous aura de concentration ça peut être la raison.

**Comment by brolkzer** [comment]
Sur certains serveur ça se cumule et il me semblait que ici c'était le cas vu que j'ai reconnu plusieurs similitudes avec le script firestorm. Et non je ne prends pas de dégâts sur la vidéo je suis a orgrimmar entrain de taper un poteau

**Comment by joshwhedon** [comment]
Les effets similaires de buffs ne sont pas supposes se stack. Donc si tu as 2 classes avec toi qui ont le meme type de buff, un seul sera applique.

**Comment by toitit** [comment]
> Pour info les buffs drood équi et sp ne se cumulent pas pour le toucher :
> 
> > Cap toucher pour casteur : 17% donc 14% avec la misère du prêtre ombre, 11 si un druide équilibre est présent.
> 
> => ceci est faux, cela reste à 14% même s'il y a un drood équi qui pose son débuff
> 
> Après ça ne change rien au niveau de tes tests à priori, si tu as 15%

Faut pas oublier le talent focalisation de l'ombre, c'est bien 17-3-3 = 11% le cap toucher du sp (mais pas pour les mêmes raisons)

**Comment by joshwhedon** [comment]
J'arrive pas a reproduire. Tu peux regarder le journal de combat et me dire ce que ca affiche ?

**Comment by brolkzer** [comment]
Je t'ai filmé directement avec le journal de combat.
Il dit que le fouet se dissipe.

https://www.youtube.com/watch?v=QP5-DMh5S0s&

**Comment by joshwhedon** [comment]
Mouai, je sais pas. Je pense pas que je vais pouvoir corriger, a premiere vue ca ressemble a un probleme de lag cote serveur qui fait que le dernier tick se fait pas de temps en temps.

**Comment by brolkzer** [comment]
à vérifier pour les autres canalisations comme le drain d'âme, drain de vie, etc

**Comment by Solosszer** [comment]
Même problème sur le Drain soul de l'afflilock, à la fin du cast le dernier tic disparait de manière random (same lorsqu'on l'arrête en plein milieu après un clip le problème apparaît aussi et le tic précédent ne proc pas).

**Comment by Ischjgt** [comment]
Ça arrive sur tous types/level d'ennemis, pour info le tick qui déconne fait quand même refresh https://woehead.way-of-elendil.fr/?spell=15332

**Comment by brolkzer** [comment]
Perdre 1 tick de fouet mental c'est pas juste dérangeant pour le tissage de l'ombre. Tu perds 1 tick sur 3 du sort qui fait 40% de ton dps

**Comment by brolkzer** [comment]
Et d'ailleurs même pas puisque ça m'arrivait de n'avoir que 2 des 3 stacks de tissage pendant que je testais sur le poteau

**Comment by Ischjgt** [comment]
> Perdre 1 tick de fouet mental c'est pas juste dérangeant pour le tissage de l'ombre. Tu perds 1 tick sur 3 du sort qui fait 40% de ton dps

Nan mais, je dis pas ça pour ça.C'est une info pour Josh et pour qu'il essaie de comprendre le bug, et en effet t'apporte une info supplémentaire :
Chez moi quand le sort fait que 2 ticks le tissage de l'ombre à 5 stacks est REFRESH même sur le 3eme tick qui fait pas de dégats
Par contre si je suis pas au max et que le bug survient il donne que 2 stacks
=> L'anguille est sous la roche

**Comment by joshwhedon** [comment]
Donc le tick se fait quand meme du coup. Ca veut donc dire que quelque chose d'autre se passe (miss, resist, etc)

**Comment by Solosszer** [comment]
> > Perdre 1 tick de fouet mental c'est pas juste dérangeant pour le tissage de l'ombre. Tu perds 1 tick sur 3 du sort qui fait 40% de ton dps
> 
> Nan mais, je dis pas ça pour ça. C'est une info pour Josh et pour qu'il essaie de comprendre le bug, et en effet t'apportes une info supplémentaire :
> Chez moi quand le sort fait que 2 ticks le tissage de l'ombre à 5 stacks est REFRESH même sur le 3eme tick qui fait pas de dégats
> Par contre si je suis pas au max et que le bug survient il donne que 2 stacks
> => L'anguille est sous la roche

À mon avis tu regardes mal et ce sont les deux premiers tics qui font le refresh, si le troisième tic n'est pas là ça ne peut pas refresh, et ça ne peut pas miss en etant cap Hit

**Comment by brolkzer** [comment]
> Donc le tick se fait quand meme du coup. Ca veut donc dire que quelque chose d'autre se passe (miss, etc)

Il se fait pas.

**Comment by brolkzer** [comment]
A la fin de la vidéo ou j'ouvre le détails on voit que 11 ticks ont eu lieu alors que j'ai cast 4 fouet mental, sur le combat log on voit qu'il n'apparaît pas, si il était resisté il apparaitraît quand même et je ne peux pas le rater.

**Comment by Ischjgt** [comment]
En effet j'ai dit de la merde, ignorez mes commentaires.

**Comment by dirsang** [comment]
Salut,

Perso j'ai testé une centaine de fois, et j'ai eu mes 3 tick à chaque fois.
Tu es sur de ne pas relancer ton mf avant qu'il ne soit terminé ?

**Comment by joshwhedon** [comment]
Impossible de corriger le soucis, c'est une combinaison de lag client et serveur, meme pas reproduisible de facon simple.
