### ISSUE TITLE
Quête impossible à rendre

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#961]
**Description**
Cas où le joueur ne peut pas rendre la quête alors qu'il a tous les items. Il s'agit seulement du soucis avec les items qui peuvent se loot même si le joueur n'a pas la quête
(Désolé j'ai pas retrouvé l'ancien post)

**Étapes de reproduction**
- .q a 893
- .q c 893
- .add 5093
- Supprimer un des 2 Eustache tranchecrin (n'importe lequel)
=> Pas possible de rendre la quête sans l'abandonner et la reprendre

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/275
