### ISSUE TITLE
Bug dégâts en mêlée après un CM sur la Dame (Féral DPS) - ICC 25H

### ISSUE THREAD

**Issue by Avril13** [way-of-elendil/3.3.5#962]
**Description**
Je ne sais pas si ça a été report, mais un soucis que j'ai constaté à plusieurs reprises en jouant druide féral sur ICC 25H, c'est qu'à partir du moment où je suis CM par la Dame en 25H, je n'ai plus aucun dégâts de mêlée après le CM, et ce durant tout le fight. Pour y remédier, je déco-reco, mais pendant un fight, ce n'est pas possible. En tant que druide féral, les dégâts en mêlée faisant environ 30% du dps, c'est comme si cette classe ne servait à rien sur ce boss.

**Étapes de reproduction**

- Citadelle de la Couronne de Glace
- Mode 25 Héroïque
- Dame Murmemort
- Après un CM 

**Comportement attendu**
Normalement, un CM ne devrait pas pouvoir enlever les dégâts de mêlée. 

**Captures d’écran / Vidéos**
Je n'ai pas gardé les logs des fois où ça m'est arrivé, mais à plusieurs reprises, tout se passe bien en début de combat sur la Dame. A partir du moment où je me fais CM, je n'ai plus aucun dégâts en mêlée. 
Avec un stuff et une opti corrects, je tourne autour de 10K+ dps, et après un CM en tout début de combat,  j'ai fini à 5k9 dps. (J'ai regardé le top 3 des sorts utilisés : 1. Lambeau 2. Balayage 3. Griffure. Pas de dégâts en mêlée après le CM --> injouable).

Au besoin, je prendrais le screen du recount la prochaine fois pour vous le certifier avec un avant/après CM.

**Comment by joshwhedon** [comment]
https://github.com/way-of-elendil/3.3.5/issues/535
Bug deja signale

**Comment by joshwhedon** [comment]
Essayez un /reload a l'occasion pour voir si ca regle le soucis.
