### ISSUE TITLE
Professeur Putricide impossible à loot si "rez goule" en fight

### ISSUE THREAD

**Issue by Ezolis** [way-of-elendil/3.3.5#963]
**Description**
Cela fait 2 semaines que durant le combat face à Putricide il y a un "rez goule", la personne transformée en goule DPS le boss normalement. Une fois le boss vaincu il n'ai pas possible de le fouiller (0 emblème, pas de loot, pas de réputation, etc...)
(Le problème se présentera peut-être sur d'autre boss, mais nous n'avons pas eu de "rez goule" sur les autres boss)

**Étapes de reproduction**
ICC 10NM
(Peut-être sur les autres versions 10H / 25N / 25H à voir)

**Comment by Ischjgt** [comment]
(Pas réussi à reproduire de mon côté, je peux pas loot le boss en étant en goule mais tout va bien pour les emblemes HF, tous les joueurs voient les loots même en respo butin et je peux le Master loot peut distribué une fois que je suis ressuscité)

**Comment by joshwhedon** [comment]
Impossible a corriger. Techniquement le joueur transforme en goule n'est plus un joueur mais un npc (et le joueur lui meme est mort), et donc ne peut pas loot un boss / npc (un peu comme un joueur sur un vehicule ne peut pas loot non plus). Je sais meme pas si c'est un bug ou bien si c'etait le fonctionnement normal sur offi.

**Comment by Bleuphonix** [comment]
Sur les prince d'un 25nm on eu la même chose avec les circonstance suivante celle que j'ai pue remarquer ou assister potentiellement pas toute les info utile

Une goule aurais probablement tuer le boss suite a un DOT ou un coup directe (déduis par rapport a se report de bug)
les PO / emblème on été distribuer mais le(s) boss (princes de sang) n'ont pas donnée de loot 
on avais 2 rez goule dans le tas dont 1 fait a 5sec de la fin du down max

voila les info que je peux vous donnée peu être minime mais pas plus

**Comment by Ischjgt** [comment]
Je réouvre parce que c'est différent de ce que je tu expliques Josh

**Étapes pour reproduire**
- Joueur A, chevalier de la mort et Joueur B en groupe de raid (n'importe quel mode de butin)
- .go c id 36612 
- mettre le boss à 1 PV
- Joueur B meurt
- Joueur A rez goule joueur B
- Joueur B tue le boss avec une auto-attaque
- Pas de loot (HFs et emblèmes ok)

**Comment by joshwhedon** [comment]
Impossible a corriger, faudra faire avec.
