### ISSUE TITLE
Boss: Vazruden the Herald & Nazan

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#967]
**Description**
[Reinforced Fel Iron Chest] GUID: 20496 ID: 185168
Name: Nazan Entry: 17536.
Name: Vazruden the Herald Entry: 17307.

- Il y a un boss en phase 1 et un autre en phase 2 je sais pas si c'est normal

- [Reinforced Fel Iron Chest] GUID: 20496 ID: 185168 Pas lootable quand les 2 boss sont morts

**Comment by Ischjgt** [comment]
<img width="1026" alt="Capture d’écran 2020-07-24 à 17 02 16" src="https://user-images.githubusercontent.com/60295792/88405401-7e5a6880-cdcf-11ea-83e7-05496144066f.png">

En fait il y en  a 3 là et je sais pas comment le 3eme est apparu, les 2 au sol étaient en phase 1 mais il y en avait un pas visible
C'est juste pour signaler, c'est peut etre un bail avec le script

**Comment by joshwhedon** [comment]
Oui c'est normal, celui qui est monte normalement est invisible, il sert de "controlleur" pour l'event.

**Comment by joshwhedon** [comment]
J'applique un changement sur le boss pour le nettoyer un peu.
