### ISSUE TITLE
Quest 11516 : Blast the Gateway

### ISSUE THREAD

**Issue by Babyface-187** [way-of-elendil/3.3.5#968]
**Description**
Le living flare ne devient jamais instable

**Étapes de reproduction**
-invoquer le Living Flare grâce à l'item 'Sizzling Embers'
-tuer les mobs 'Incandescent Fel Spark' pour que le Living Flare puisse stack (le flare doit être à portée du mob)
-au bout de 8 mobs, le Living Flare se transforme, mais il ne devient pas instable pour autant

**Comportement attendu**
Au bout de 8 mobs, le Living Flare se transforme et devient 'Unstable Living Flare' on peut alors l'emmener au Gateway pour finir la quête.

**Ressources additionnelles**
https://woehead.way-of-elendil.fr/?quest=11516

**Comment by joshwhedon** [comment]
Corrige prochaine maj
