### ISSUE TITLE
Chasseur Survie Tir de Wywern

### ISSUE THREAD

**Issue by aassimar** [way-of-elendil/3.3.5#969]
**Description**
Le tir de Wywern est un contrôle qui endort la cible pendant 30sec, tout effet de dégâts subit pendant cette période annule l'effet d'endormissement de la cible. 
Or, sur WoE, l'effet ne s'annule pas. Toute personne peut DPS la cible endormie, du coup je vous laisse imaginer l'issue d'un combat en PvP

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Chasseur
- Race
- Survie
- Tir de wywern
- BG
- Equipement
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
Lorsque que la cible est contrôle sous Tir de Wywern, toutes sources de dégâts subie par la cible annule l'effet du Tir de Wywern

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
Grimoire Chasseur spé Survie / arbre de Talent Chasseur spé Survie

**Comment by Gandrayda** [comment]
J'ai essayé de reproduire mais de mon côté le sort fonctionne parfaitement, le dodo s'enlève après n'importe quels dégâts infligés que ça soit par nous ou par un autre joueur . Je pense qu'il y a eu confusion étant donné que le dot qui suit la fin du dodo a exactement le même tooltip que celui du contrôle ( ce qui peut donner l'impression que le contrôle est toujours actif alors que c'est le DoT qui l'est ) mais à confirmer par l'auteur du ticket .

**Comment by joshwhedon** [comment]
Je confirme ce que dit Gandrayda. J'ai teste a la fois les sorts, attaque de melee, distance et les dots, et des qu'un degat est recu, le sommeil se retire, et est remplace par la dot.
