### ISSUE TITLE
[Event Tauren Chieftains Profondeur de Blackrock] Ne se lance pas.

### ISSUE THREAD

**Issue by LLPPAA** [way-of-elendil/3.3.5#971]
Lorsque l'on possède une Télécommande navrebière (https://woehead.way-of-elendil.fr/?item=37863) et que l'on parle à Ognip (https://woehead.way-of-elendil.fr/?npc=28210) dans le sinistre écluseur, on peut déclencher un concert des Tauren Chieftains. Le dialogue est bien présent, mais quand l'event se lance, la seule chose qui se passe c'est la disparition des gobelins et des instruments, et rien de plus.

Preuves : 
https://fr.wowhead.com/npc=28210/ognip-boumboulon#english-comments
https://www.youtube.com/watch?v=hZtQk5Wt-_Q&feature

**Comment by LLPPAA** [comment]
L'event doit aussi se lancer à 8h (du soir je suppose), mais je n'ai pas pu tester si cette partie marchais ou pas.

**Comment by joshwhedon** [comment]
En fait il se lance, mais il met quelques minutes
