### ISSUE TITLE
Profondeur de Blackrock, Gardien noir (Zimrel)

### ISSUE THREAD

**Issue by LLPPAA** [way-of-elendil/3.3.5#972]
Le Gardien noir Zimrel (https://woehead.way-of-elendil.fr/?npc=9441) n'est pas apparu après l'ouverture et l'observation du tableau se trouvant dans la voûte noire (https://imgur.com/NoNQI0w).

L'event du cercle de la loi n'avait pas été fait et tous les spectateurs ont été tués avant la révélation de ce gardien noir. Je ne sais pas si le problème concerne uniquement ce gardien dans ces conditions ou tous les gardiens.

Normalement, lorsqu'on ouvre/lis l'inscription sur le tableau, un gardien noir aléatoire est choisit et apparait à l'endroit qui lui est lié. C'est ce gardien qui donne la clef du gardien noir permettant d'ouvrir le coffre sombre (https://woehead.way-of-elendil.fr/?object=160845).

https://fr.wowhead.com/item=11197/cl%C3%A9-du-gardien-noir#english-comments

**Comment by joshwhedon** [comment]
J'ai teste tous les gardiens et ils spawnent bien a l'endroit ou ils sont supposes. La seule chose a laquelle je peux penser c'est qu'il ait despawn apres un moment.

**Comment by LLPPAA** [comment]
Ah, c'est vrai qu'il est possible que j'ai mis du temps avant d'aller au bon endroit ... Bon, j’essaierai d'être plus rapide la prochaine fois.

**Comment by joshwhedon** [comment]
Je sais pas, peut etre qu'il y a un soucis :D . Tiens moi au courrant si tu reeessaie. Pas grand monde rapporte les bugs sur ce donjon (moi c'est un de mes favoris).
