### ISSUE TITLE
[PNJ] [Mammouth de voyage de la toundra]

### ISSUE THREAD

**Issue by Ferro3** [way-of-elendil/3.3.5#976]
Lors de l'incantation de la monture [Mammouth de voyage de la toundra] en face de Shandy Cireluisante (à Dalaran), les PNJ ne sont pas dans le mammouth de voyage mais au sol.
De plus il ne disparaissent pas avec le temps.

Actuellement 8 PNJ sont pop (29/7 18h30)

En fait, cela se produit partout.
En re-bootant le jeu, le problème a disparu, mais les PNJ sont toujours présent. J'en ai semé aussi à UC.

Shandy Cireluisante https://woehead.way-of-elendil.fr/?npc=36856

**Comment by joshwhedon** [comment]
Impossible a reproduire de mon cote, vois avec un mj en jeu je pense.
