### ISSUE TITLE
Terrasse des magister NM - Prêtresse Delrissa

### ISSUE THREAD

**Issue by Notil78** [way-of-elendil/3.3.5#978]
Bonjour

Dans la version NM de Terrasse des magister, suite au kill de Prêtresse Delrissa + ses ADD, la porte derrière (https://woehead.way-of-elendil.fr/?npc=24560) ne semble plus s ouvrir.

De plus l orbe derrière le boss de fin de l instance, ne permet plus de TP.

Merci,
Bon courage.

**Comment by joshwhedon** [comment]
Deja signalee et sera corrigee prochaine maj.
Une solution en attendant et de ne pas tuer avec des aoes.
