### ISSUE TITLE
Quête L'épreuve du lac : Crash au clic droit sur le colifichet du sanctuaire

### ISSUE THREAD

**Issue by Charyline** [way-of-elendil/3.3.5#979]
Dès le lancement de la quête, un timer se lance et il faut récupérer un item au fond du lac à Reflet-de-Lune. Il scintille au fond de l'eau. Au moment de faire un clic droit, le jeu crashe.

- Emplacement : Reflet-de-Lune
- Faction / Race / Classe : Druide lvl 19 (je devais y aller au lvl 14 et j'ai eu 2 quêtes, je ne sais pas si celle-ci vient plus tard qu'au 14)
- Nom de la quête : L'épreuve du lac
- Nom du donneur de quête : Dendrite Brasétoile

Je faisais cette quête en parallèle, donnée par Mathrengyl Pasdelours à Darnassus : https://wotlk.evowow.com/?quest=6121

**Comment by Theralion** [comment]
Tu as le patch HD et la forme aquatique du drood ?
Si c'est le cas, il faut que tu démorph avant d'interagir avec des objets sous l'eau, le combo patch HD + forme aquatique du drood fait crash sur l'interaction avec des objets (items, plantes, etc)

**Comment by Theralion** [comment]
Commentaire dans la FAQ pour plus de détails : 

5. * Problème en jeu * 
#Je suis druide, et j'ai crash après avoir ramasser un item dans l'eau. 

- Vous avez surement installé la version du jeu avec le « patch HD », c'est un bug connu. Il sera résolu lors de la prochaine mise-à-jour. En attendant, ramasser les items en étant sous aucune forme de druide, ou télécharger le jeu avec le « patch Original ».
