### ISSUE TITLE
Gob: Uldum Pedestal

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#980]
**Description**
[Uldum Pedestal] GUID: 17230 ID: 142343
Name: Stone Watcher of Norgannon
Entry: 7918.

https://woehead.way-of-elendil.fr/?quest=2966
qui donne sur 
https://woehead.way-of-elendil.fr/?quest=2954

Il est impossible de refaire apparaitre le Stone Watcher of Norgannon après que le joueur l'ait invoqué une fois en rendant la quête 2954 si :
- le joueur n'a pas eu le temps de prendre la suite
- le joueur a abandonné 2967 ou 2977 (la suite)

**Comment by joshwhedon** [comment]
Et il peut cliquer sur le piedestal sans la quete ou pas ?

**Comment by Ischjgt** [comment]
Non aucune interaction n'est proposée

**Comment by joshwhedon** [comment]
Donc c'est bloque cote client, du coup c'est probablement le comportement normal. Et pour pouvoir reprendre il faut surement etre avec un autre joueur.  En gros au mieux ce que je peux faire c'est l'empecher de despawn pour que le joueur ait tout son temps. Mais les autres cas ... bah c'est probablement "normal".
