### ISSUE TITLE
flèche givrante

### ISSUE THREAD

**Issue by gtschanz** [way-of-elendil/3.3.5#981]
**Description**
j'ai duel un perso à moi en étant en double compte zira vs zatana. (zatana full pve sans aucune résistance à aucune sorte
J'ai à plusieurs reprise utilisé la flèche givrante sur mon perso (de base pour configurer tidy plate) et à ma grande surprise le piège s'est souvent PAS déclanché voir à carrément été ANNULE.

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Classe: chasseur
- Race: elfe de sang
- Spécialisation: précis
- Sort / Talent / Etc: flèche givrante
- Circonstances (Donjon, Raid, PvP, autre): pvp duel (mais j'avais aussi déjà remarqué ce bug en bg)
- Equipement: stuff à zira
- Buffs / Debuffs / Enchaînement de sort / Etc

**Comportement attendu**
La flèche givrante DOIT OBLIGATOIREMENT geler quelqu'un qui arrive sur le piège. cela ne doit pas être comme sur les 3 screen ci dessous. C'est ULTRA génant car cela rend le chasseur inutilisable en arène quasiment si un de ses main sort de control peut fade sans raison

**Captures d’écran / Vidéos**

**Comment by joshwhedon** [comment]
Et ca dit quoi dans le journal ? Parce que la va me falloir un peu plus d'information si je veux reproduire. Le piege se place au sol ou pas ? Ou il se place pas du tout ?

**Comment by joshwhedon** [comment]
OK, on a regarde et c'est parce que le perso avait pas mal de resistance au givre.
