### ISSUE TITLE
Attaque automatique qui ne fonctionne plus suite a un contrôle mental

### ISSUE THREAD

**Issue by Shotsx** [way-of-elendil/3.3.5#983]
Lorsque je subit sur mon Druide un contrôle mental a la fin de l'effet quand je reprend les commandes de mon personnage celui-ci n'effectue plus aucune attaque automatique (dégât blanc) le bug disparais après avoir quitté l'instance du donjon/raid ou avoir déco reco , je ne sait pas si il survient sur tout les classes ou uniquement les druides farouche 
A savoir que le bug m'est arriver a plusieurs fois en donjon (salle de pierre nain sombrefer) ou raid (Dame Murmemort) et que le bug est survenue a chaque contrôle mental que j'ai subit 

**Étapes de reproduction**
-Subir un contrôle mental de n'importe quelle monstre ou boss
-Attendre la fin de l'effet 
-lancer une attaque automatique 

-**Comportement attendu**
-Rejoindre le camps adverse temporairement (l'ia lance tout les sorts sous ça main) 
-A la fin de l'effet nous sommes capable de lancer les attaques physique automatique normalement (clique droite)

**Captures d’écran / Vidéos**
-j'éditerait plus tard

**Comment by joshwhedon** [comment]
MEme probleme qu'ici
https://github.com/way-of-elendil/3.3.5/issues/535

**Comment by Crotodur** [comment]
Oui et non, puisque dans l'autre ticket, on parle juste de sorts inutilisables, là on parle des auto attaques. Peut être lié à la classe ?

**Comment by joshwhedon** [comment]
Non le probleme est general avec le controle mental et les actions de joueur.
