### ISSUE TITLE
Under map Boss labyrinthe des ombre 

### ISSUE THREAD

**Issue by Bleuphonix** [way-of-elendil/3.3.5#986]
**Description**

Pendant l’évent de Kréator on a fait le DJ Labyrinthe des ombres et lorsque le boss Grand maître Vorpil a voulut tous nous TP sur lui on a été TP en dessous de la plateforme soit under map

**Étapes de reproduction**

- Donjon : Labyrinthe des ombres
- Niveau de difficulté: normal
- Boss : Grand Maître Vorpil
- Sort en question : https://woehead.way-of-elendil.fr/?spell=33563
- Emplacement : 3 d'entre nous en bas de l'escalier et les 2 autre sur l'escalier de mémoire
- Composition du groupe : Rcham / Wartank / fufu / mage / DK

**Comportement attendu**

on reste sur la plateforme et on est TP sur l'emplacement du boss

**Captures d’écran / Vidéos**

https://cdn.discordapp.com/attachments/584034185736486933/741353471084724374/WoWScrnShot_080720_192606.jpg
on est déjà sous map

**Ressources additionnelles**

https://www.youtube.com/watch?v=6OO-aXQeo2Q vers les 14min 06 second

**Comment by joshwhedon** [comment]
Ce sera corrige avec le prochain merge, c'est a premiere vue un soucis de maps, donc probablement dans quelques semaines. J'ai pas reussi a reproduire moi meme en passant.
