### ISSUE TITLE
Illidan à l'escarpement de l'aile du néant

### ISSUE THREAD

**Issue by Ushkka** [way-of-elendil/3.3.5#987]
**Description**
Je suis arrivée à l'escarpement et Illidan était présent : j'ai pensé que quelqu'un venait de finir de monter la réputation de l'aile du néant Je commence les quêtes et cherche les œufs : pas d’œufs. J'ai attendu, mais toujours une heure après il y a toujours Illidan, et aucun œufs !

**Étapes de reproduction**
- Aucun œuf ne pop

**Comportement attendu**
12 œufs de drake du néant devraient apparaître à l'escarpement de l'aile du néant.

**Comment by Ischjgt** [comment]
Pas réussi à reproduire pour Illidan, c'est la quête 11108.
Pour les œufs c'est un autre soucis

.gob near 100 à l'escarpement, les gobs sont bien là mais quand je vais dessus l'œuf n'y est pas. J'ai pas en tête le temps de respawn

**Comment by Ushkka** [comment]
Concernant Illidan, j'ai simplement trouvé ça curieux. Surtout que par la suite, il est mort d'un coup sans raison (il y avait 2 Illidan l'un sur l'autre). Mais je ne sais pas si sa présence empêchait le lancement de la quête car je suis arrivée aujourd'hui à l'escarpement, je n'en suis pas à là.

Concernant les oeufs, je comprends pas trop mais ils sont censés être là mais ils n'apparaissent, c'est ça ?
J'ai parlé avec un alli qui était dans la zone, il avait trouvé un œuf qui n'était pas présent sur le pattern du woehead. Il ne voyait pas non plus les autres œufs.
Je crois que le respawn des œufs est entre 10 et 20 minutes, je ne sais plus exactement non plus.

Un reboot serveur permettrait de les actualiser ?

**Comment by Ischjgt** [comment]
C'est moi qui les ai tué.

**Comment by Ischjgt** [comment]
Oui désolé j'ai oublié de te répondre.
J'arrive pas à reproduire pour l'instant mais j'ai peut-être un élément de réponse :

Si le joueur est sur monture,
41519 - [Marque de Hurlorage, rank 1 frFR] [active]
41528 - [Marque de Hurlorage, rank 1 frFR] [active]
ne se met pas sur le joueur, il perd juste son illusion. 
De la même façon, Yarzill le Mercenaire ne prends pas le joueur pour le sauver si ce dernier est sur monture

**Comment by joshwhedon** [comment]
Devrait etre corrige prochaine maj merci.
