### ISSUE TITLE
Spell: Controle mental sur NPC

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#990]
**Description**
C'est peut-etre le même probleme que sur les autres tickets avec les CM sur les joueurs.
CM sur un NPC **en instance donjon ou raid** le rend inactif quand il sort du controle.
Le NPC est en combat contre le joueur mais il ne fait aucune action et sa vie regen quand il subit des dégats

**Comment by joshwhedon** [comment]
Corrige prochaine maj
