### ISSUE TITLE
L'AOE du gaz de corruption de gangrebrume ne correspond pas au visuel.

### ISSUE THREAD

**Issue by LLPPAA** [way-of-elendil/3.3.5#992]
Lorsque Gangrebrume (troisième boss du plateau du puits de soleil, https://woehead.way-of-elendil.fr/?npc=25038) s'envole en phase 2, et qu'elle utilise son souffle de corruption, on peut être corrompu même si on est hors de l'effet visuel qui correspondrai au souffle. La seule stratégie est donc de la tuer avant qu'elle s'envole.

**Comment by joshwhedon** [comment]
Corrige prochaine mak
