### ISSUE TITLE
Chevalier de la mort : bug du 4P T10 DPS

### ISSUE THREAD

**Issue by Unleashh** [way-of-elendil/3.3.5#993]
**Description**
Ce post a déjà été créé, mais rien ne bouge et semble à l'abandon. De plus, les explications n'ont pas été très claires. 
Je veux parler du Proc 4P T10 du Dk (Avantage) qui ne proc pas suffisamment.
En effet, comme l'indique le bonus, le 4P est censé proc lorsque que _**toutes les runes sont en recharge**_
Cela veut bien dire ce que cela veut dire :  dès que toutes les runes, sans exception, sont en CD; le 4P est censé proc. Ce n'est _pas du tout_ le cas ici : en effet, le 4P T10 ne prends pas en compte les runes de mort. C'est à dire que lorsqu'on dispose des runes de mort et qu'on les utilise, le 4P ne proc pas même si toutes les runes sont en CD. C'est TRES gênant, particulièrement en DK givre. On doit pouvoir profiter d'un uptime de 100% sur le proc ce qui n'est clairement pas le cas ici.
Même combat au pull : je balance mes maladies ensuite drain sanglant (proc rune de la mort) -> Armure incassable -> Pesti -> anéantissement. Toutes mes runes sont en CD, pourtant le proc Avantage n'apparait pas (j'ai mis un weakaura bien dégueu en plein milieu de l'écran pour montrer clairement l'uptime).
ça signifie donc que je ne bénéficie pas du proc au pull (gros nerf). Il faudrait alors changer la rotation au pull pour le faire proc mais ça fait perdre des GCD, c'est de la merde.

Vidéo démontrant mes explications ci-dessous

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- DK
- Orc(osef)
- Givre
- Avantage : 4P T10 DPS
- EVERYWHERE

**Comportement attendu**
Le 4P T10 DOIT proc à _chaque fois_ que toutes les runes sont en CD, peu importe l'ordre d'utilisation ou de la nature des runes (rune de la mort ou rune de sang)

**Captures d’écran / Vidéos**

https://vimeo.com/448054921
(désolé si la qualité est pas top)
On voit bien ici au pull que je n'ai pas de proc 4P, ni après avoir utilisé mon Arme runique et après avoir re-consommé toutes mes runes : il faut attendre la 35e seconde avant d'avoir un proc (après 25secondes de combat, c'est juste énorme, c'est après les trinkets, après la fury etc). C'est le temps pour que mes runes de la mort redeviennent des runes de sang, et que je les consomme.
A la 45e seconde, pareil :  j'ai re-consommé TOUTES mes runes, et le proc ne se refresh pas.
Et ainsi de suite. On a un uptime du proc global qui est vraiment dégueulasse, le 4P devient presque inutile dans ces conditions.
S'il vous plait, pourriez vous fix ceci ?

**Comment by joshwhedon** [comment]
Rien ne bouge parce qu'aucune solution n'a ete trouvee.
