### ISSUE TITLE
En rêve : pnjs n'interagissent pas correctement.

### ISSUE THREAD

**Issue by LLPPAA** [way-of-elendil/3.3.5#995]
Lors de la quête En rêve (https://woehead.way-of-elendil.fr/?quest=5944), à un moment le Généralissime Taelan Fordring (https://woehead.way-of-elendil.fr/?npc=1842) et le Grand Inquisiteur Isillien (https://woehead.way-of-elendil.fr/?npc=1840) ne se combattent pas comme ils le devraient au moment où ils sont censé le faire. De plus, une fois Taelan mort, on est censé combattre Isillien. Qui est un poteau. Il n'attaque pas, et se laisse descendre petit à petit. En plus dans Tirion Fordring arrive, Isillien récupère tous ses points de vie et les deux pnj ne se combattent pas non plus. Au moins Tirion attaque les autres pnj de la croisade.

Accessoirement, le déplacement de Taelan de son point d'origine dans le fort jusqu'à la tour où on retrouve Isillien, est assez ... chaotique ?

**Comment by joshwhedon** [comment]
Deja signale ici.
https://github.com/way-of-elendil/3.3.5/issues/679
