### ISSUE TITLE
Impossible de valider la quête "Le ragoût de la marche de l'ouest"

### ISSUE THREAD

**Issue by spychest** [way-of-elendil/3.3.5#998]
**Description**
Une fois tous les ingrédients réunis il est impossible de valider la quête "Le ragoût de la marche de l'ouest"

**Étapes de reproduction**
Fournissez les informations nécessaires pour reproduire le problème. Par exemple
- Marche de l'ouest
- Aliance / Elfe / Druide
- Le ragoût de la marche de l'ouest
- Salma Saldean

**Comportement attendu**
Normalement une fois les ingrédient réuni on doit pouvoir rendre la quête à Salma Saldean 

**Captures d’écran / Vidéos**
![bug](https://user-images.githubusercontent.com/48262723/90699986-ef812480-e284-11ea-8bbb-ffd84c692b8e.png)

**Ressources additionnelles**
https://fr.classic.wowhead.com/quest=38/le-rago%C3%BBt-de-la-marche-de-louest

**Comment by joshwhedon** [comment]
Bonjour, c'est un probleme connu avec ce genre de quetes (et assez general). Pour le regler pour toi meme, tu peux soit abandonner la quete et la reprendre, soit mettre tous les objets en banque et les ressortir.
Le probleme plus general sera regle quand on aura une solution.

**Comment by spychest** [comment]
Ok très bien merci pour l'astuce =)
